### ISSUE TITLE
Netflix on a Mac

### ISSUE THREAD

**Issue by DaAwesomeP** [BrowserWorks/waterfox#10]
There does not appear to be a 64-bit version of Silverlight for Mac OSX, so Netflix simply won't work until they add HTML5 support for Firefox. Are there any workarounds besides simply switching to another browser for Netflix?

**Comment by DaAwesomeP** [comment]
@MrAlex94 Do you have any experience with this?

**Comment by MrAlex94** [comment]
Unfortunately I don't think Microsoft will ever release a 64-Bit version of Silverlight for OS X, especially with Netflix moving to HTML5.

**Comment by DaAwesomeP** [comment]
Do you think that Adobe/Mozilla will release a 64-bit version of the EME plugin?

**Comment by MrAlex94** [comment]
Yes definitely, I'd say by Q1 2016 Mozilla will be aiming to release 64-Bit release builds, so they'll have to come up with a solution.

**Comment by DaAwesomeP** [comment]
Hmmm. When they start to do that, make sure that you mention the optimizations that Waterfox uses (like using the Intel C++ compiler) so that it will really work well. Thanks for your help.
