### ISSUE TITLE
v56.2.10 x64 - Can't access stackoverflow.com, error "MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING"

### ISSUE THREAD

**Issue by DeepMac** [BrowserWorks/waterfox#1001]
When trying to access any page on https://stackoverflow.com/ I get an error that TLS handshake can not be completed, with the specific error being MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

I am able to successfully access the page with Internet Explorer. I've had no problems accessing it until the most recent update. I have not made any changes to my addons or configuration recently.
I tried with both the default user-agent and serveral variations.

![waterfox-stackoverflow-fail](https://user-images.githubusercontent.com/4560942/58578893-e0ddc600-8217-11e9-8195-80a0ad1c6456.png)

**Comment by grahamperrin** [comment]
Not reproducible at <https://stackoverflow.com/> with 56.2.10 on FreeBSD-CURRENT or Lubuntu Linux.

**Comment by DeepMac** [comment]
Tested again today and it now functions. PC has not been restarted, nor browser (literally same session running). Putting this down to shenanigans at Stackoverflow with their load-balancers or similar network topology.
