### ISSUE TITLE
bugs.chromium.org Monorail largely unusable with dom.moduleScripts.enabled false in Waterfox Classic

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1002]
Spun off from https://redd.it/bg86n1

A few weeks ago it was possible to view an issue by switching to the old UI. 

Now, neither the new UI nor the old UI works with Waterfox 56.2.10. An example: 

- https://bugs.chromium.org/p/chromium/issues/detail?id=896897
- old UI https://bugs.chromium.org/p/chromium/issues/detail_ezt?id=896897

Screenshot (FreeBSD-CURRENT) – Waterfox in safe mode to the left, Firefox to the right):

![image](https://user-images.githubusercontent.com/192271/58749565-821a8580-847f-11e9-96a7-4c3a815aa281.png)

Meta/tracking: #538

**Comment by grahamperrin** [comment]
If it helps, from https://www.reddit.com/r/waterfox/comments/bg86n1/chromium_bugs_new_ui_fails/elly4e8/ for outdated 56.2.9: 

> I see JavaScript errors,
> 
> `TypeError: window.prpcClient is undefined`

**Comment by laniakea64** [comment]
Same issue here.

I did a search relating to that error, based on the results I tested **Firefox 59.0.3** -

Firefox 59.0.3 in default configuration: fails as described.

Firefox 59.0.3 with `about:config` > `dom.moduleScripts.enabled` set to `true`: works.

**Comment by pjpreilly** [comment]
Firefox 59.0.3 with about:config > dom.moduleScripts.enabled set to true: works.

Hey Mikey!

**Comment by pjpreilly** [comment]
It would seem this issue would have larger ramifications than just this instance. Any thoughts?

**Comment by laniakea64** [comment]
> It would seem this issue would have larger ramifications than just this instance. Any thoughts?

It does.  Another example - https://github.com/serj-kzv/mozlz4-edit/issues/6

**Comment by grahamperrin** [comment]
Cross reference https://bugs.chromium.org/p/monorail/issues/detail?id=5670

**Comment by grahamperrin** [comment]
… _largely unusable_ because it's no longer possible to seek issues.  

![image](https://user-images.githubusercontent.com/192271/58753981-f543ec00-84bf-11e9-942d-e77ad6745a98.png)

**Comment by grahamperrin** [comment]
about:config?filter=dom.moduleScripts.enabled

I imagined that the preference didn't exist in 56.2.10 but here it is, `dom.moduleScripts.enabled` `false` by default. 

Making it `true` seems to make things good with Monorail, let's discover whether there are any unexpected side effects with sites elsewhere …

**Comment by grahamperrin** [comment]
In the case at https://github.com/MrAlex94/Waterfox/issues/1005#issuecomment-498643360 it seems that reverting to `false` for `dom.moduleScripts.enabled` has no adverse effect. 

In this case (Monorail), reverting to `false` leads to recurrence of the issue: 

![image](https://user-images.githubusercontent.com/192271/58878614-96eb5900-86cb-11e9-98af-780b3cce3d42.png)

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/dc1c88f60b59bc5ea0572522d5a45df8b4959618

Will disable if big issues crop up, but I don't believe they will.
