### ISSUE TITLE
Black screen on some videos

### ISSUE THREAD

**Issue by jackpallet** [BrowserWorks/waterfox#1003]
**Describe the bug**
When I play some videos they have a black screen
Here for example: https://xhamster.com/videos/sexy-tgirl-emma-on-a-shopping-trip-11722818 When I try to play the video I have only a black screen.
Tried to start waterfox in Safe mode and it works. 
Then I've tried to disable ALL plugins one by one.  Result: when I play the video I obtain a black screen. Tried to create a new clean profile, result: BLACK SCREEN. How is possible?

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate Service Pack 1 64 bit
 - Waterfox Version: 56.2.10 (64 bit)

**Comment by grahamperrin** [comment]
From <https://support.mozilla.org/kb/troubleshoot-firefox-issues-using-safe-mode#w_safe-mode-window>:

> … temporarily disable your extensions and themes, turn off hardware acceleration and reset toolbar and button customizations. …

So if you can not reproduce the issue in safe mode, I should look next at hardware acceleration. 

about:preferences#general ▶ Performance

**Comment by jackpallet** [comment]
Ok, it works
Thanks

**Comment by grahamperrin** [comment]
Thanks – if you like, close the issue.
