### ISSUE TITLE
website not displayed

### ISSUE THREAD

**Issue by pidossi** [BrowserWorks/waterfox#1005]
I have problem to surf correctly https://www.gazzetta.it
Waterfox (last version, 56.2.10) displays only the first image, not the header with videos and the lower images.
No problem with Edge and Chrome.

**Comment by grahamperrin** [comment]
Waterfox 56.2.10 on FreeBSD-CURRENT, normal mode (various extensions): 

![image](https://user-images.githubusercontent.com/192271/58780346-9ae68080-85d0-11e9-9525-0aa455207580.png)

> ReferenceError: event is not defined

> ReferenceError: utag is not defined

> TypeError: RcsOrchestrator is not a constructor

> ReferenceError: callReviZoneId is not defined

Safe mode: 

![image](https://user-images.githubusercontent.com/192271/58780579-442d7680-85d1-11e9-8708-baf4cfd00852.png)

Falkon: 

![image](https://user-images.githubusercontent.com/192271/58780635-72ab5180-85d1-11e9-8ed3-8f99676256ca.png)

**Comment by Lorienna** [comment]
- OS: Windows 7
- Waterfox version: 56.2.10
- Browser profile: new
- URL: https://www.gazzetta.it/

### dom.moduleScripts.enabled = false
<img src="https://user-images.githubusercontent.com/26753987/58878471-079a7180-86dc-11e9-80a2-6edebd8e87db.jpg" alt="screenshot">

### dom.moduleScripts.enabled = true
<img src="https://user-images.githubusercontent.com/26753987/58878380-d15cf200-86db-11e9-8c28-4cbc87abbb4e.jpg" alt="screenshot">

**Comment by grahamperrin** [comment]
@Lorienna thanks, this also helps at https://github.com/MrAlex94/Waterfox/issues/1002#issuecomment-498455149

**Comment by Lorienna** [comment]
@grahamperrin You're welcome. The site now works fine with Waterfox 56.2.10 by default:

### dom.moduleScripts.enabled = false

<img src="https://user-images.githubusercontent.com/26753987/58877661-fcdedd00-86d9-11e9-896c-79d362ea20e7.jpg" alt="screenshot">

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/dc1c88f60b59bc5ea0572522d5a45df8b4959618
