### ISSUE TITLE
Branding Policy on Redsitributed Builds/PPC64LE builds

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#1009]
I am not clear exactly as to what the branding policy is for custom builds that are redistributed by end users. I use Linux on a PPC64LE desktop and would have to compile Waterfox from source in order to use it.

I would like to not repeat what happened with the Pale Moon developers [here](https://github.com/jasperla/openbsd-wip/issues/86)

I try to help other PPC64LE users out by releasing pre-compiled binaries of browsers when I compile them since they can be difficult to compile properly on PPC64LE. For example, see my pre-built Firefox Repo [here](https://github.com/djames1/firefox-ppc64le-bin).

I am also willing to contribute in the future to make sure that PPC64LE continues to work in Waterfox and would be happy to produce official PPC64LE builds for you. That would make you the only web browser that has official upstream PPC64LE builds. Currently Firefox/Waterfox have no official JIT for PPC64LE, but there is a JIT in progress [here](https://github.com/classilla/jitpower)

The mozconfig I would be using for my redistributed builds is something similar to the following:
```
export CC=clang
export CXX=clang++
#Firefox fails with -O3 on power9
ac_add_options --enable-optimize="-O2 -mcpu=power9"
ac_add_options --target=powerpc64le-unknown-linux-gnu
ac_add_options --enable-pulseaudio
ac_add_options --enable-alsa
ac_add_options --disable-gpsd

export MOZ_GECKO_PROFILER=
export MOZ_ENABLE_PROFILER_SPS=
export MOZ_PROFILING=
export MOZ_MAINTENANCE_SERVICE=

mk_add_options MOZ_MAKE_FLAGS=-j4
mk_add_options AUTOCLOBBER=1
mk_add_options MOZ_OBJDIR=objdir-68

ac_add_options --disable-debug
ac_add_options --disable-dmd
ac_add_options --disable-crashreporter
ac_add_options --disable-profiling
ac_add_options --disable-signmar
ac_add_options --disable-tests
ac_add_options --disable-verify-mar

ac_add_options --enable-application=browser
ac_add_options --enable-ccache=sccache
#TODO: Test if this will work on PPC64LE
ac_add_options --disable-lto
#TODO: Firefox on PPC64LE has issues with --enable-release. Figure out if Waterfox has these issues too.
ac_add_options --disable-release
ac_add_options --disable-updater

ac_add_options --with-app-name=waterfox
ac_add_options --with-app-basename=Waterfox
ac_add_options --with-branding=browser/branding/alpha
```

**Comment by MrAlex94** [comment]
Please feel free! I'm more than happy to merge any patches you may have as well. 
I only ask you to keep Waterfox as is though, in terms of not changing any functionality or bundling anything with it (i.e. default search, not bundling any PuPs)

**Comment by ghost** [comment]
@MrAlex94 I'll do that then. I actually wound up using a different .mozconfig. I had some issues with the one I posted.

I've created the following [repo](https://github.com/djames1/waterfox-ppc64le-bin)
