### ISSUE TITLE
v68: Sync tab in Preferences not accessible

### ISSUE THREAD

**Issue by tycrek** [BrowserWorks/waterfox#1011]
**Describe the bug**
I cannot view the "Sync" tab of the browser Settings. Nothing shows up or the tab does not respond to clicks depending on which method is used.

**To Reproduce**
*Method 1*
1. Go to 'Options' through the "hamburger" menu in the top right.
2. Click on 'Sync'
3. Tab is now highlighted, but the UI does not change and you remain on the same screen as before.

*Method 2*
1. Click the Account Button (can be enabled through Customize)
2. Click 'Sync Settings'
3. Sync tab is highlighted, yet there is no UI.

**Expected behavior**
The sync tab should behave as it does in regular Firefox. I understand that Waterfox is built for privacy and security, but I would also like to be able to sync all my extensions and bookmarks.

**Screenshots**
[Screenshot](https://ibb.co/CPmFMNm) (Dark mode is applied from Shadowfox)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 (Build 17763.503) x64
 - Waterfox: 68.0a1

**Additional context**
I'm somehow signed in to my Firefox account despite not being able to see the sync page, probably from when I installed Waterfox the first time.

**Comment by Ibuprophen** [comment]
See if the following addon helps you with accessing the "about:sync" in the address bar. 

https://addons.mozilla.org/en-US/firefox/addon/about-sync/

Just a suggestion... 👍 


~Ibuprophen

**Comment by tycrek** [comment]
@ibuprophen1 Looks like this extension will work for now, thanks for the suggestion.

I'll keep this issue open as the Sync page should optimally work as expected or just be removed altogether.
