### ISSUE TITLE
68.0a2 regression: WebExtensions Experiments no longer available

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1012]
@MrAlex94 commented somewhere on Reddit that it was planned to enable WebExtensions Experiments in Waterfox 68.  And they WERE enabled in 68.0a1.

But they are not available in 68.0a2.

I fixed it locally by adding this line to my mozconfig customisations -
```
ac_add_options "MOZ_ALLOW_LEGACY_EXTENSIONS=1"
```

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/6dc6672ccfb1ecd7f9f39c5f8f72bf38b1c526a4

🙂

**Comment by laniakea64** [comment]
Hi @MrAlex94 this issue is back again in self build from https://github.com/MrAlex94/Waterfox/commit/090a765e6d7ca41794158191bd216a141d138de1 .  Same local fix as before gets it working again.

**Comment by laniakea64** [comment]
Fixed again by https://github.com/MrAlex94/Waterfox/commit/c995ffde704376fc1704efaca35122b87b9defd2 , thanks! :tada:
