### ISSUE TITLE
v68: Consider Using ld.gold and PGO For Official Builds (At least on Linux)

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#1013]
It appears mozilla's facilities for doing these are now working correctly...

mozconfig:
```
export MOZ_PGO=1
ac_add_options --enable-gold 
```

To build, we need xvfb:
 ```
  export PATH="$srcdir/path:$PATH"
  export MOZ_NOSPAM=1
  export MOZBUILD_STATE_PATH="/path/to/mozbuild" # can be wherever

  # LTO needs more open files
  ulimit -n 4096

  xvfb-run -a -n 97 -s "-screen 0 1600x1200x24" ./mach build

```

**Comment by MrAlex94** [comment]
Do you have any success building on Linux with LTO?

**Comment by ilikenwf** [comment]
Using the built in LTO in v68 works perfectly, it broke after a while in
the master branch and I never tried to fix it.

**Comment by hawkeye116477** [comment]
For me LTO works but not at all distros, only had problems on SUSE Leap 15.1, Tumbleweed, CentOS 7 and Ubuntu Xenial. On two last I got error `undefined reference to gMozillaPoisonValue`, on two first it hang on libxul.so and after some time `shutdown signal` (on OBS).

Update: With 68.0a2 apparently I has more successes with PGO+LTO. Only it fails on Leap 15.1 and Tumbleweed.
