### ISSUE TITLE
v68 - Building Without webspeech and/or speechd seems to break the build

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#1014]
This one may not really matter a lot since these features can be negated in about:config, but using these:

```
ac_add_options --disable-synth-speechd
ac_add_options --disable-webspeech=1
```

I get the following error:

```
11:25.94 dom/media/mediacapabilities
11:32.80 In file included from waterfox-alpha-git/src/Waterfox/obj-x86_64-pc-linux-gnu/ipc/ipdl/UnifiedProtocols27.cpp:101:
11:32.82 waterfox-alpha-git/src/Waterfox/obj-x86_64-pc-linux-gnu/ipc/ipdl/PSpeechSynthesisChild.cpp:8:10: fatal error: 'mozilla/dom/' file not found
11:32.82 #include "mozilla/dom/SpeechSynthesisChild.h"
11:32.82          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:32.86 1 error generated.

```

I was able to work around it with this hacky patch:

http://sprunge.us/n6GgLr

**Comment by MrAlex94** [comment]
Might be worth filing this with [Mozilla](https://bugzilla.mozilla.org/), it's happened a few times where a component is disabled and a call to a header has been forgotten to be wrapped in if guards. Your patch is probably the way it would be resolved as well if you're up for filing it there.
