### ISSUE TITLE
68 Alpha does not backup bookmarks daily

### ISSUE THREAD

**Issue by rebop** [BrowserWorks/waterfox#1015]
**Describe the bug**
AS shown, bookmark backups is sporadic rather than daily in 56 (I thought 56 had an issue as well, but seems to be working fine now with latest updates).

**To Reproduce**
Check bookmarkbackups folder:

**Expected behavior**
One backup per day

**Screenshots**
![image](https://user-images.githubusercontent.com/13785042/59148823-3eb1a100-89c2-11e9-8cec-4856f51abdf3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Win 7  64 bit
Have not yet checked Win 10 with Alpha

**Comment by grahamperrin** [comment]
> One backup per day

That would surprise me (not expected). 

```text
grahamperrin@momh167-gjp4-8570p:~/.mozilla/firefox/58ectoj2.default/bookmarkbackups % date ; 
Sat  8 Jun 2019 21:42:25 BST
grahamperrin@momh167-gjp4-8570p:~/.mozilla/firefox/58ectoj2.default/bookmarkbackups % ls -hlrt
total 3655
-rw-------  1 grahamperrin  grahamperrin   125K 10 Mar 23:37 bookmarks-2019-03-10_1184_sYTbLBvt26z-VeEH1l-EDg==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   126K 24 Mar 15:26 bookmarks-2019-03-24_1194_uQi6qIjWITpGNWKa3XosrA==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   126K 26 Mar 09:16 bookmarks-2019-03-26_1195_UVG4S0GDMMo8asMMaA+iIQ==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   126K 29 Mar 08:48 bookmarks-2019-04-04_1195_p-r1FuBkZC9yfbCkjqEuFw==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   126K 17 Apr 06:42 bookmarks-2019-04-17_1196_iQK-x8-oemvhPnZKFBJpwQ==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   127K 23 Apr 18:59 bookmarks-2019-05-06_1197_c5VvYX58zMzMDbLOaDxLqQ==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   127K  9 May 08:40 bookmarks-2019-05-09_1198_Kok7PyqCGlHEUyYNBPHuCg==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   127K 13 May 14:40 bookmarks-2019-05-14_1198_sh1x5iHTby9lWFtd3o1CAg==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   109K 18 May 09:15 bookmarks-2019-05-19_1198_X4SIGSpR3IeGQMtdhgZCMA==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   109K 21 May 05:42 bookmarks-2019-05-21_1198_ro2oL1GULgvllhxIofr0Sg==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   109K 25 May 02:43 bookmarks-2019-05-25_1199_evSFU9TrVj8Xo2A4H5Nnlg==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   110K 27 May 11:29 bookmarks-2019-05-27_1211_5833R8Qs6Dsd2skHds30AA==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   113K  1 Jun 18:21 bookmarks-2019-06-02_1254_sm-EXHH00AIZQH9iSQj9Og==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   113K  3 Jun 00:48 bookmarks-2019-06-03_1255_LD5XWDiiWNtpbOdS2hISbQ==.jsonlz4
-rw-------  1 grahamperrin  grahamperrin   113K  6 Jun 19:38 bookmarks-2019-06-08_1256_sTgl89cHfzgtQDTT8FW4lw==.jsonlz4
grahamperrin@momh167-gjp4-8570p:~/.mozilla/firefox/58ectoj2.default/bookmarkbackups % 
```

**Comment by rebop** [comment]
56 does indeed do one a day and previous versions did as well. I did read ton Mozilla somewhere that IS the expected behavior for one per day.

From the example given in the Firefox tutorial, it would appear that Firefox performs an automatic backup of the user's bookmarks in a haphazard fashion, i.e. sometimes every day and other times several days (weeks) go by without Firefox automatically backing up the bookmarks. Does anyone know how often we can rely on Firefox performing an automatic bookmark backup? I'm new to Firefox and want to know if I need to perform regular manual backups of the bookmarks to be safe in case of crash. Thanks!
Chosen solution

Firefox will create a JSON backup each day that you start Firefox. If you keep your computer running and do not close Firefox then there may not be a JSON backup created.

If you close Firefox and no backup is created on the next start then you may have an extension interfering or other problems with your profile folder or cleanup software (e.g. CCleaner) that removes the backups.

**Comment by grahamperrin** [comment]
> Firefox will create a JSON backup each day that you start Firefox. 

I never found this, at any installation … <strike>can we find technical documentation? </strike> this might help to explain (with added emphasis) : 

>> …  compressed .jsonlz4 JSON backup then this is done when you start Firefox **and** Firefox detects that there have been changes to to bookmarks, i.e. the calculated hash value differs from the hash value in the most recent JSON backup. …

- https://support.mozilla.org/en-US/questions/1242772#answer-1178740

**Comment by Squall-Leonhart** [comment]
> 
> 
> 56 does indeed do one a day and previous versions did as well. I did read ton Mozilla somewhere that IS the expected behavior for one per day.
> 
>

no it doesn't,  bookmarks are only backed up when changes are made.

**Comment by rebop** [comment]
ahhhhhhh, thanks, Now that makes perfect sense. A day rarely goes by I don't make some sort of change in my bookmarks in my "working" browser, hence a daily backup. While testing 68, I rarely do anything with bookmarks and so that explains what appeared to be an issue for me. Thanks!
