### ISSUE TITLE
v68: Display addon versions in add-ons manager list?

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1017]
This useful feature was added to Waterfox 56 in https://github.com/MrAlex94/Waterfox/pull/566 .  Could this please be ported to Waterfox 68?

**Comment by p1usminus** [comment]
You could try this in a userContent.css file: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/aboutaddons/addonlists_show_addon_version_number.css

with the xml in the chrome folder too: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/aboutaddons/addonlists_show_addon_version_number.xml

In my file the rules are within this @-rule: @-moz-document  url-prefix(chrome://mozapps/content/extensions/extensions.xul), url-prefix(about:addons) { 
...
}

**Comment by laniakea64** [comment]
I was able to port the patches from https://github.com/MrAlex94/Waterfox/pull/566 to Waterfox 68, but they're only effective when `about:config` > `extensions.htmlaboutaddons.enabled` is set to `false`.  Looks like another patch is needed for when that's set to `true`, as it is by default in latest Waterfox 68.0a2.

Edit: I was able to get this working with `about:config` > `extensions.htmlaboutaddons.enabled` set to `true` as well.  I hope I find the time to get all these patches submitted as a pull request.

**Comment by laniakea64** [comment]
Fixed by https://github.com/MrAlex94/Waterfox/pull/1029

**Comment by grahamperrin** [comment]
@laniakea64 @MrAlex94 for (distant) future reference:

- Mozilla bug [1564525 - Removing extensions.htmlaboutaddons.enabled pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1564525)

**Comment by laniakea64** [comment]
@grahamperrin Waterfox Current shows addon versions in both htmlaboutaddons and classic `about:addons`.  Did you mean to post that in https://github.com/MrAlex94/Waterfox/pull/1194 ?
