### ISSUE TITLE
Can not update themes in 56.2.10.1

### ISSUE THREAD

**Issue by Chesshur** [BrowserWorks/waterfox#1018]
I updated to the latest Waterfox which is 56.2.10.1 and I am still unable to update several of my themes. I am able to download them through the addon manager, however, they are never truly updated since they keep reappearing in the addon manager. And manually installing them after downloading the xpi won't work either since I get the corrupt addon error message. It's getting annoying that the updates keep showing up and I can't get rid of them, can you do anything about them or is this going to be an permanent unsolvable issue for Waterfox? 

These are the problematic themes:
https://addons.mozilla.org/en-US/firefox/addon/aziraphale-crowley-the-serpent/
https://addons.mozilla.org/en-US/firefox/addon/nightwish-the-crow-the-owl-/?src=search
https://addons.mozilla.org/en-US/firefox/addon/simply-ineffable/
https://addons.mozilla.org/en-US/firefox/addon/joey-and-scapegoat/
https://addons.mozilla.org/en-US/firefox/addon/cherry-hotmail-skin/
https://addons.mozilla.org/en-US/firefox/addon/cherry-hotmail-skin/
https://addons.mozilla.org/en-US/firefox/addon/wings-evangelion/
https://addons.mozilla.org/en-US/firefox/addon/judal-sleep/
https://addons.mozilla.org/en-US/firefox/addon/digi-halloween/
https://addons.mozilla.org/en-US/firefox/addon/longing-for-spring-sakura/

**Comment by grahamperrin** [comment]
Duplicate (known symptom) of https://github.com/MrAlex94/Waterfox/issues/972#issuecomment-495521922
