### ISSUE TITLE
HTML5 gaiming problem

### ISSUE THREAD

**Issue by regrepl** [BrowserWorks/waterfox#1023]
There is a webbrowser game based on html5 technology
Command & Conquer - Tiberium Alliances
www.tiberiumalliances.com

It dosen't work propertly. You can log but you can not interact with interface of the game. Like it was just not accepting the action. Not all of them are workicg, some are other don't. It worked on older version. Currently is unplayable on waterfox. Please consider checking it out what is the issue.

**Comment by grahamperrin** [comment]
New to me, but I registered and found my way around a few things (without really taking notice; I don't intend to play). 

Can you share a screenshot with an indication of an example of the problem? 

Thanks
