### ISSUE TITLE
Bookmarking Issues in 68

### ISSUE THREAD

**Issue by rebop** [BrowserWorks/waterfox#1024]
**Describe the bug**
Bookmarking a page will ONLY allow the bookmark to go to other bookmarks. Then will not allow rearranging to another folder or deleting until the browser is closed and reopened.

**To Reproduce**
Use any bookmarking method: CTL D, Star or right click menu

**Expected behavior**
TO be asked where to save the bookmark

**Desktop (please complete the following information):**
Windows 7 64 bit

**Comment by laniakea64** [comment]
already fixed by https://github.com/MrAlex94/Waterfox/pull/975

**Comment by rebop** [comment]
Cool. Thanks. I could not recall if I reported this or read that someone else did.
