### ISSUE TITLE
Waterfox does not appear to work with Discord anymore due to changes in microphone permission handling

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#1025]
**Describe the bug**
Attempting to use the Discord web application initially popped up a message incompatible versions. Spoofed updated firefox user agent just incase it was a fake error however app would not request microphone permissions and continued to act like no microphone permissions were provided after manually overriding the permission to allow in page info. Guessing FF recently changed something in how permissions work that has not been pushed to Waterfox. 

**To Reproduce**
https://discordapp.com and log in
Attempt to enable voice and provide microphone permissions. 
prompted with a browser compatibility error using default user agent string 
failure to allow microphone permissions or enable voice when attempting to spoof a updated Firefox user agent as well.

**Expected behavior**
Functional voice chat
**Screenshots**
![image](https://user-images.githubusercontent.com/2266606/59522897-d8cf8880-8e9d-11e9-9af1-cd74031a68ae.png)

Spoofed Firefox User Agent with microphone permissions manually overrides to always allow 
app appears to assume permissions are still denied 

![image](https://user-images.githubusercontent.com/2266606/59523041-349a1180-8e9e-11e9-8bec-2c53a8c9b86c.png)

![image](https://user-images.githubusercontent.com/2266606/59523015-24823200-8e9e-11e9-9f79-191a2a922eef.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro X64
 - Version 56.2.10.1

**Comment by Squall-Leonhart** [comment]
probably requires a service worker.

**Comment by grahamperrin** [comment]
From <https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/e66hdxs/>:

> `Firefox/60.0`

> If you like, refine the user agent string, but **omit** the word `Waterfox`.

**Comment by grahamperrin** [comment]
> … appears to assume permissions are still denied …

Please, you clarify? 

For me, the in-site hint re: permission is momentary: 

https://put.re/player?id=UbswHtZ7.mp4

**Comment by mikeloeven** [comment]
It looks like the issue is just the unsupported browser error. The other problem about not asking permissions and not seeing manually set permissions was confirmed to be a discord problem a bad update yesterday since patched 

`Gerard (Discord)    Jun 14, 15:58 PDT    Hey Mike,      I checked with the team and found that they pushed an update earlier!      Could you try refreshing your browser and see if it's working now?      Keep me posted here.      Best,    Gerard`



I have just tested it on Waterfox again and the audio is once again working however I still have to change the user agent to get past the unsupported browser dialogue

**Comment by freezewind** [comment]
Same here fro current. The Discord web application initially popped up a message incompatible versions .
Version: 2020.08
Firefox 68.12.0esr doesn't has this problem.

**Comment by hawkeye116477** [comment]
>  The Discord web application initially popped up a message incompatible versions .

There is already user-agent override added on Classic, so it shouldn't.

**Comment by freezewind** [comment]
I have try to override the UA with firefox 80, but it doesn't work.
I think there is a problem other than UA.

Edited: Sorry, I found out that it works with a new profile. I will post the problem when I found it
Edited: I found out that I forgot to enable the "Enable WebRTC peer connection".
