### ISSUE TITLE
Restrore FreeBSD compatability

### ISSUE THREAD

**Issue by tuaris** [BrowserWorks/waterfox#1034]
Waterfox used to have a port but it was removed due to non-trivial issues in porting. 
https://www.freshports.org/www/waterfox

**Comment by grahamperrin** [comment]
56.2.10.1: [Building Waterfox Classic on FreeBSD · grahamperrin/Waterfox Wiki](https://github.com/grahamperrin/Waterfox/wiki/Building-Waterfox-Classic-on-FreeBSD)

56.2.11: does not build in the same way (bugged by #1032). 

### Beyond Classic

My guess: the prospect of maintenance will be more attractive if the eventual release of Waterfox 68 does not diverge too far from the essence of Firefox ESR 68 …
