### ISSUE TITLE
update browers

### ISSUE THREAD

**Issue by wkuzma** [BrowserWorks/waterfox#1036]
when trying to access xfinity I get https://internet.xfinity.com/unsupported-browser.html

**Comment by grahamperrin** [comment]
With an extension such as [Custom UserAgent String](https://addons.mozilla.org/addon/custom-user-agent-revived/) you can set a UA override. 

For `https://internet.xfinity.com/` this simple (short) override seems to be effective:

`Firefox/65.0`

Similarly effective: 

`Firefox/65.0 Waterfox/56.2.11`

**Comment by wkuzma** [comment]
Thank you that worked perfectly

**Comment by grahamperrin** [comment]
Thanks for the confirmation, you can close this issue.
