### ISSUE TITLE
Waterfox for Android nowhere to be found on Google Play Store

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#1038]
**Describe the bug**
Cannot find Waterfox for Android on Google Play Store

**To Reproduce**
1. Go to Google Play Store on an Android device.
2. Type: Waterfox browser, or Waterfox browser for Android in the Search field.
3. Waterfox doesn't appear in the list.

**Expected behavior**
The Waterfox download should appear. 

**Screenshots**
![Screenshot_20190621-122356](https://user-images.githubusercontent.com/33827636/59917411-1f832c80-9422-11e9-9721-c9417cbc5065.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J5 (2016)
 - OS: Android
 - Version 7.1.1
- Security patch level: June 1, 2018 (phone is out of warranty now).  

**Additional context**
The list of available browsers is quite long, but Waterfox is not among them.

**Comment by Telmesomething** [comment]
I have Waterfox installed on my laptop and decided to go to the Google Play Store using that and then copied the URL to my phone. That loads Waterfox, but when I try to download it, I have to sign in (?). That's extremely annoying since I use Keepass with which I can create and then copy/paste 200-bit passwords in the respective fields on sites, but it's much more difficult on a phone. Google seems to think I made a mistake and subsequently wiped the field. 

Is there some other (and easier) way to solve this conundrum? 

![Screenshot_20190621-131809](https://user-images.githubusercontent.com/33827636/59919988-51e45800-9429-11e9-8f5a-dd0bf03c6588.jpg)

**Comment by hawkeye116477** [comment]
@Telmesomething I've bad news for you, you have 32-bit OS and new Waterfox is currently only for 64-bit OS. Despite you have 64-bit CPU, Samsung decided to make 32-bit OS.

**Comment by Ibuprophen** [comment]
The Beta version of the Waterfox App that's for 32-bit can be obtained by the steps outlined on the following post. 

https://github.com/MrAlex94/Waterfox/issues/730#issuecomment-421647220 

Good Luck! 


~Ibuprophen

**Comment by Telmesomething** [comment]
> @Telmesomething I've bad news for you, you have 32-bit OS 

Damn... I'd taken it for granted that it was the 64-bit flavor, but after downloading the AnTuTu benchmarking app I see that you're correct. 

Thanks  for responding anyway hawkeye116477.

**Comment by Telmesomething** [comment]
> The Beta version of the Waterfox App that's for 32-bit can be obtained by the steps outlined on the following post.

Thanks ibuprophen1, but I think I'll pass on that one. I guess it's about time to invest in a new device and I'll be very careful this time to select the 64-bit version. 

I hardly ever use the phone for browsing anyway because I don't like the small screen. My Windows 8.1 laptop is more than enough for my needs, but after updating to 56.2.11 on that today I noticed that it's also available for Android, but couldn't figure out why it doesn't appear in the Play Store. 

Anyway, thanks for responding.

**Comment by Ibuprophen** [comment]
It's weird that ARM/32-bit devices are still being used/released to this day. 

I do know that the ARM64/64-bit and even in many cases the x86 devices as well are increasingly being used for newer devices but, hasn't completely been implemented to replace its 32-bit counterpart/cousin. 

With that stated... There's also the increase of ARM64/64-bit "capable" devices being released and the Manufacturers are installing/using ARM/32-bit Firmware that basically has the user stuck with (the knowledge of) basically having an ARM/32-bit device. 

I'm hoping, praying, lighting a candle, etc... that @MrAlex94 reconsiders the support for the ARM/32-bit devices. 

I've got to look for the source i had seen recently that approx 40-45% (+/-) of Android users are using either a device that's ARM/32-bit OR a device with the firmware (type of restriction) that, essentially, makes the device an ARM/32-bit. 

Thank you very much for your patience with my little rant... LOL! :-) 


~Ibuprophen

**Comment by androidacy-user** [comment]
Now it's literally nowhere to be found and I'm on arm64, a pixel 2 xl. A Google search led me here

Is the Android version dead now or what?

**Comment by Ibuprophen** [comment]
It's not uncommon for Android Devices to be 64-bit capable, but the Android OS itself is 32-bit. 

~Ibuprophen

**Comment by androidacy-user** [comment]
Did you even bother to look up the device? Trust me, 100% arm64, OS, kernel, Snapdragon 835 and all

**Comment by hawkeye116477** [comment]
`Is the Android version dead now or what?`
In short, Google removed it and doesn't want to tell why.

**Comment by LeeBinder** [comment]
> ### G5.0 Beta 1
> 
> ✨ New:
> 
>     Waterfox is now awaiting approval from Google to be listed on the Play Store!

source: https://www.waterfox.net/docs/releases/G5.0b1

**Comment by vehosah** [comment]
> > ### G5.0 Beta 1
> > ✨ New:
> > ```
> > Waterfox is now awaiting approval from Google to be listed on the Play Store!
> > ```
> 
> source: https://www.waterfox.net/docs/releases/G5.0b1

At last some news
