### ISSUE TITLE
Waterfox bookmark issue

### ISSUE THREAD

**Issue by ROCKNROLLKID** [BrowserWorks/waterfox#104]
Since Waterfox 49, for some reason, when I go to try to create a bookmark, it sometimes will just save the bookmark before I even press the done button. It is rather annoying when I am trying to rename a bookmark to something because it always finishes before I am actually done with it.

**Comment by MrAlex94** [comment]
@ROCKNROLLKID, this may be a Firefox UX issue. Can you repro with Firefox?

**Comment by ROCKNROLLKID** [comment]
I can't replicate this with recent versions of Firefox or Waterfox anymore, so I assume this was fixed already. I will go ahead and close this.
