### ISSUE TITLE
Broken Addon-s in Android beta + new version won't install.

### ISSUE THREAD

**Issue by zenerbufen** [BrowserWorks/waterfox#1040]
**Describe the bug**
I have been using waterfox beta for about a year as my daily browser with virtually zero problems. however this last few weeks my addons stopped working and I am no longer to browse as I am used to or log into many websites using addons.

**To Reproduce**
1. Open waterfox beta for android
2. attempt to use addons
3. open addon settings for disabled addon
4. unable to verify
-attempt to use new version instead-
5. open play store
6. waterfox page
7. try to install
8. not supported

**Expected behavior**
I expected my addons to continue to work, or for the new version to install.

**Screenshots**
On other device, hard to transfer without addons and browser working. can provide if needed.

**Desktop (please complete the following information):**
 - OS: windows
 - Version Pro insider build 18908.rs_prerelease.190524-1658

**Smartphone (please complete the following information):**
 - Device: LG Stylo 4
 - OS: Android 8
 - Version 8.1.0 Security patch may 2019
**Smartphone CPU**
  - CPU Clock Speed: Up to 1.8 GHz
  - CPU Cores: 8x ARM Cortex A53, Octa-core CPU
  - CPU Architecture: 64-bit

**Additional context**
I love the work you have done over the years. waterfox is the best browser by far. I have been using it as my daily driver and only browser on my phone. I had totally replaced usage of all other browsers on my phone.  

I am lost and my phone feels as if it is nearly unusable without the syncing and addons I have come to depend on! It is no fun to jump through tons of extra hoops and relearn a bunch of stuff to use an inferior browser on my phone.Please fix the old or new version so I can continue to use it on my phone!

**Comment by hawkeye116477** [comment]
@zenerbufen It appears that despite you have 64-bit CPU, LG decided to make only 32-bit OS, so newest Waterfox won't work currently until Alex will make 32-bit version.
