### ISSUE TITLE
v68: Bookmark keywords starting with + don't work (regression compared to v56)

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1042]
**Describe the bug**
Bookmark keywords beginning with `+` don't work in Waterfox 68.  Instead of loading the bookmark URL, Waterfox just does a web search for the portion after the `+`.  This is regression compared to Waterfox Classic.

**To Reproduce**
1) bookmark https://www.waterfox.net/
2) Bookmarks > Show All Bookmarks, find and select the bookmark
3) set keyword to `+wf`
4) new tab, enter `+wf` in address bar

**Expected behavior**
Waterfox website should have been loaded.

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04.64-bit
 - Waterfox 68.0a2

**Additional context**
n/a

**Comment by p1usminus** [comment]
I have a suspicion that this is related to address bar results modifiers, listed here: https://old.reddit.com/r/firefox/comments/9h5ia5/if_youre_not_using_the_bookmark_menu_youre/e69b4ye/

Typing a + seems to restrict results to either a web search or pages with tags (I tested with a bookmarked page with a tag) - so bookmarks with keywords containing + are excluded.

**Comment by laniakea64** [comment]
> I have a suspicion that this is related to address bar results modifiers, 

Where is the related code in Waterfox?

**Comment by p1usminus** [comment]
> 
> Where is the related code in Waterfox?

I think this is the relevant module: https://github.com/MrAlex94/Waterfox/blob/gecko68/toolkit/components/places/UnifiedComplete.jsm#L609

There are several sections that refer to restrict/ion beyond line 609, but the first one starts there from what I could see.

Lines 394-405 set up the map of tokens to behaviours using UrlbarTokenizer: https://github.com/MrAlex94/Waterfox/blob/gecko68/browser/components/urlbar/UrlbarTokenizer.jsm#L64

(In Waterfox Classic this all happens in one file: https://github.com/MrAlex94/Waterfox/blob/master/toolkit/components/places/UnifiedComplete.js)

**Comment by laniakea64** [comment]
Thanks @p1usminus that led me to this - https://github.com/MrAlex94/Waterfox/commit/20e5ae999075fe13d84e59e5e8f85e2978f9f4ca
(I think that commit is likely **not** the culprit here.  I'm linking it because the commit _message_ is related -
> keywords and aliases can't in general begin or end with a restriction character, but we don't have an input check to prevent those.
> For now the tokenizer can't recognize keywords or aliases, because it can't be made asynchronous until the Quantum Bar is the default implementation, and anyway the complexity must be considered at that point.
> 
> The best we can do is to stop splitting out restriction character in the middle of the search string.
> This will allow a part of the old interaction like searching for "keyword? something".

There is also related information in the Mozilla bug referenced by that commit, as well as the bugs that bug links under "Tracking" and "See Also".)

Sounds like Mozilla knows this is an issue and they don't like this either.  Sounds like it would be easier for me to just change the one affected bookmark keyword in my bookmarks than someone try to fix this.
