### ISSUE TITLE
v68: Lacking user-accessible way to uninstall orphaned searchplugin-extensions

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1045]
When upgrading from an older Waterfox 68.0a2 to the latest Waterfox 68.0a2 (self build from https://github.com/MrAlex94/Waterfox/commit/85165bfd6f5fd250ce60f80c379d5ee679c9ee97), I noticed there was cruft left behind by old searchplugin-related extensions that Waterfox had deleted and replaced (https://github.com/MrAlex94/Waterfox/commit/67eaa9366fd591ff9b745dd9bfd41f8fd82f89ca).  The old stale extensions were still active in my profile according to `about:support` and `about:debugging`, even though they had no visible effect.

I could not find a UI that allowed me to uninstall these useless dead extensions, so in order to get rid of this cruft, I ended up running this code in Browser Console -
```
AddonManager.getActiveAddons().then((r) => {
  for (let addon of r.addons) {
    if (addon.id.endsWith('@search.mozilla.org')) {
      console.log(`Uninstalling ${addon.id}...`);
      addon.uninstall();
    }
  }
});
```

It is unreasonable to expect users to be able to use Browser Console to manage their extensions!  Ideally this specific management would be done automatically, but if that is not possible, stale/orphaned searchplugin-extensions need to show up in Add-ons Manager or something like that.

**Comment by MrAlex94** [comment]
I'll look into importing these as well. Sorry, some of the docs are still pointed to Thunderbird-centric files.

**Comment by laniakea64** [comment]
> I'll look into importing these as well.

Sorry if I'm missing something, but what are "these" in this context?

**Comment by GitCurious** [comment]
Unfortunately this code seems to have stopped working with latest Current Waterfox.
