### ISSUE TITLE
Patreon posts "select file" buttons are not working. 

### ISSUE THREAD

**Issue by SenpaiSharp** [BrowserWorks/waterfox#1047]
For uploading images to Patreon, there are blue buttons that say things like "Select image file" that when clicked, are supposed to open up the Open Dialog and let you pick out your image or whatever other kind of file. In Waterfox 56.2.11, these buttons do not work.

![example 1](https://i.imgur.com/IrKHYUq.png)

![example 2](https://i.imgur.com/MkgvhI3.png)

Interestingly enough, if you go to the upload audio section, there is a "Select audio file" blue button that does not work, but next to it there is an area that allows you to "Add optional artwork" that is NOT a blue button and clicking on it actually does open the dialog for that part.

![example 3](https://i.imgur.com/dnRr35S.png)

I tried a few of the most common useragent overrides but nothing changed.

**Comment by grahamperrin** [comment]
I signed up, to test, but I have no idea where to start. 

Can you given an example URL, or directions? Thanks. 

**Postcript**: at https://www.patreon.com/settings/profile the **Choose new image** button works for me. Waterfox Classic 56.2.10.1 on FreeBSD-CURRENT. Does it work for you?

**Comment by SenpaiSharp** [comment]
Unfortunately, it will be difficult to do that. I guess I should have considered this, but you'll actually need to have a creator's account to access any of these pages, not just a standard membership. That requires of you some kind of service to provide, a pitch and waiting for Patreon's approval. This could prove tricky to debug.
