### ISSUE TITLE
Odd render bug where things ghost...

### ISSUE THREAD

**Issue by diabloterrorgf** [BrowserWorks/waterfox#1052]
Came from FF56 to latest stable WF. Now I get some weird render bug with the pages ghosting or text looking.... off. Like it's being bolded then some arbitrary part of the page it's not then it starts looking bolded again. I tried no add-ons.

https://i.imgur.com/7SJZi4f.png Ghosting
https://i.imgur.com/cG08Fej.png Font issues

**Comment by diabloterrorgf** [comment]
Might be related to issue #1008 as I can "scroll" the pages sometimes and it will render correctly.

**Comment by grahamperrin** [comment]
Cross reference https://redd.it/c8zqi6

**Comment by diabloterrorgf** [comment]
Waterfox Alpha does not seem to have the bug.
