### ISSUE TITLE
Custom elements missing on Waterfox 68?

### ISSUE THREAD

**Issue by hawkeye116477** [BrowserWorks/waterfox#1054]
Here is written, that editable menulists have been re-implemented as custom elements => https://github.com/MrAlex94/Waterfox/wiki/List-of-changes-in-Gecko-up-to-version-68#menulist-editabletrue, but it seems that `chrome://messenger/content/customElements.js` isn't available on latest Alpha.

**Comment by laniakea64** [comment]
`chrome://messenger/*` is specific to Thunderbird and SeaMonkey mail.  If this file exists in Waterfox it would be at a different URL.

I was unable to find it extracting both `omni.ja` files and doing a grep for `menulist-editable`.

**Comment by hawkeye116477** [comment]
So documentation is to improve. On some other places also `chrome://messenger/` is written.

**Comment by hawkeye116477** [comment]
Ok, documentation improved, so closing.
