### ISSUE TITLE
impossible to install the French language

### ISSUE THREAD

**Issue by franco27** [BrowserWorks/waterfox#1055]
with version 68.0a1  Alpha Waterfox / Windows 10 x64

I can't install the French language
on this page 
https://addons.mozilla.org/en-US/firefox/addon/fran%C3%A7ais-language-pack/

**Comment by franco27** [comment]
with Waterfox -  Android version

there is the same problem

**Comment by grahamperrin** [comment]
Reproducible with 68.0a2 (20190801144413) on Windows. Tested: 

- https://addons.mozilla.org/fr/firefox/addon/fran%C3%A7ais-language-pack/
- https://addons.mozilla.org/en-GB/firefox/addon/english-gb-language-pack/

**Comment by MrAlex94** [comment]
Will look into the error

**Comment by grahamperrin** [comment]
Thanks. Not chasing :) just observing.

**Comment by grahamperrin** [comment]
**about:config?filter=extensions.getAddons.langpacks.url**

Why is `extensions.getAddons.langpacks.url` locked as valueless?

The value in Firefox 69.0:

`https://services.addons.mozilla.org/api/v3/addons/language-tools/?app=firefox&type=language&appversion=%VERSION%`

**Comment by grahamperrin** [comment]
For reference, the source of <https://addons.mozilla.org/firefox/downloads/file/3379574/francais_language_pack-68.0buildid20190813150448-fx.xpi>:

https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Ffirefox%2Fdownloads%2Ffile%2F3379574%2Ffrancais_language_pack-68.0buildid20190813150448-fx.xpi

----

I used about:preferences#general in a new profile in Firefox 68.1.0esr (64 bits) to find and install French, then quit Firefox and copied `addons.json` and the `extensions` directory of a new profile for Waterfox Current 68.0b1 (20190908151900). Result: 

![image](https://user-images.githubusercontent.com/192271/64923577-d2211c00-d7d2-11e9-8611-a51d186bd622.png)

- the dictionary is disabled and can not be enabled
- version 68.0buildid20190813150448 of the language pack is incompatible. 

Note, this is strictly experimental – not an encouragement to copy things from Firefox.

**Comment by grahamperrin** [comment]
For reference, another symptom of the issue: 

![image](https://user-images.githubusercontent.com/192271/65828295-3c38c700-e291-11e9-9967-64d3d2712b0c.png)

Source: 

- [Waterfox Current can’t update your languages right now. Check that you are connected to the internet or try again.](https://www.reddit.com/r/waterfox/comments/damc3q/waterfox_current_cant_update_your_languages_right/)

A screen recording: https://put.re/player/pRHnWHGf.mp4

Note, this issue #1055 does **not** affect the preferred language for displaying pages (content): https://put.re/player/5f2o3z8s.mp4

After a fix for this Waterfox Current issue, someone might like to check that nothing like #866 is reproducible. #866 is for Waterfox Classic, and the differences between the two branches are great enough for me to assume that #866 will be not reproducible with Waterfox Current but still, a check will be good. Localisation and internationalisation issues love to take developers (and end users) by surprise `:-)`

https://redd.it/d36svq Alex's comment noted with thanks: 

> … Mozilla have a new l10n system and I just had to get used to it :-)

– and for search purposes I'm adding keyword **i18n** to this issue.

**Comment by r3tr0g4m3r** [comment]
This issue happens with Waterfox Current 68.0b1 in Arch Linux , if i try to install the xpi manually or by using the URL of the spanish language pack the browser does nothing ( https://addons.mozilla.org/firefox/downloads/file/3379637/spanish_chile_language_pack-68.0buildid20190813150448-fx.xpi )

**Comment by grahamperrin** [comment]
Waterfox Current 2019.10 (20191015121210) on Linux: no longer reproducible. 

After installing, preferring the language and restarting: 

![image](https://user-images.githubusercontent.com/192271/67122662-34ac7400-f1e6-11e9-89ef-74a017587650.png)

**Comment by grahamperrin** [comment]
On closer inspection, it's: 

- possible to install using the link in the opening post (and, I guess, using links found via <https://addons.mozilla.org/language-tools/>) 
- not yet possible to use about:preferences to seek languages 

![image](https://user-images.githubusercontent.com/192271/67123863-4ba09580-f1e9-11e9-86df-1f2cfecf067e.png)

**Comment by joberreiter** [comment]
Waterfox Current 2020.02 on Windows: still reproducible.

**Comment by megapro17** [comment]
Still not fixed. Garbage browser

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/1522#issuecomment-610841290

> Language packs from AMO aren't compatible with Waterfox Current.

Also #1412

**Comment by dmak** [comment]
Same problem in Waterfox 2020.06: I cannot change the default language.

![image](https://user-images.githubusercontent.com/366965/85923387-c8ad0000-b88a-11ea-8a25-8697f0e14219.png)

Forum thread suggests adding first a dictionary addon, but first of all this is not obvious, and second I already have a dictionary installed for German.

> For reference, another symptom of the issue:
> 
>     * [Waterfox Current can’t update your languages right now. Check that you are connected to the internet or try again.](https://www.reddit.com/r/waterfox/comments/damc3q/waterfox_current_cant_update_your_languages_right/)
> 
> A screen recording: https://put.re/player/pRHnWHGf.mp4
> 
> Note, this issue #1055 does **not** affect the preferred language for displaying pages (content): https://put.re/player/5f2o3z8s.mp4
> 
> After a fix for this Waterfox Current issue, someone might like to check that nothing like #866 is reproducible. #866 is for Waterfox Classic, and the differences between the two branches are great enough for me to assume that #866 will be not reproducible with Waterfox Current but still, a check will be good. Localisation and internationalisation issues love to take developers (and end users) by surprise `:-)`

**Comment by T0MuX** [comment]
Hi, exactly the same issue on Waterfox 2020.09 (Archlinux x64 - Linux 5.4.70-1-lts). Unable to setup my language pack (French/Français). I tried 3 ways : 
1) the one one the previous screenshot
2) get the .xpi file of my language pack and put it manually in the extensions folder (doesnt work, waterfox doesnt start anymore)
3) install the .xpi trough the "Install addon from a file" option, but it says my file is maybe corrupted.
For information, I got the .xpi file from [there](https://ftp1.nluug.nl/os/Linux/distr/opensuse/repositories/home:/hawkeye116477:/waterfox/Arch/x86_64/)

**Comment by aguenther** [comment]
Still persists on Waterfox Current 2020.10 (64-bit) (xubuntu linux).

**Comment by T0MuX** [comment]
@MrAlex94 hi, why do you close this issue, it is solved  ? I cant see any solution arround here

**Comment by MrAlex94** [comment]
Languages are now integrated in all browser versions. No need for language packs.

**Comment by BobHD** [comment]
Not on Waterfox Classic 2022.08. I can't use anything else than English in input fields like this one.
I would need to use an older French version, is there a repository for that?
