### ISSUE TITLE
Page search scroll markers

### ISSUE THREAD

**Issue by andrew-laughlin** [BrowserWorks/waterfox#1056]
Opera has a nice feature where search hits on a page (from ctrl-f) are marked on the right side scroll bar. This would be a nice feature in WF.

**Comment by steanne** [comment]
this is available by using an extension.  i don't think the modern webextensions can do it, but you can find an archived copy of Scrollbar Search Highlighter by using the Classic Add-on Archive Extension.

https://www.waterfox.net/addons/

**Comment by grahamperrin** [comment]
> Scrollbar Search Highlighter

Doesn't work for me, Waterfox 56.2.10.1 with KDE Plasma on FreeBSD-CURRENT.

**Comment by steanne** [comment]
okay, does work for me when i tested it last night (i only installed it to check, as it's not actually something i want) on waterfox 56.2.10-1 with xfce on manjaro 5.1

the broader interpretation is "you can use extensions to do that and here's a classic extension archive where you can find an example of one."  i do not assume that is the only one out there with that functionality.
