### ISSUE TITLE
Waterfox 68a1 becomes transparent after waking laptop from sleep while an youtube video is paused in any tab

### ISSUE THREAD

**Issue by RaitaroH** [BrowserWorks/waterfox#1057]
**Describe the bug**
Waterfox becomes transparent after waking the laptop from sleep.

**To Reproduce**
1. Have waterfox alpha opened on youtube... have a video start than pause it. For some reason this thing ONLY happens if I have a video paused in some tab. After this it does not matter on what other tab I am before I suspend, what matters is that I have a video paused on youtube somewhere.
I also want to mention I have autoplay off. When I say "not playing" I mean it wasn't even loaded, when I mean paused I mean paused.
2. Suspend. I usually do `systemctl suspend`, but the normal kde way of doing it with the `Application Launcher`> `Leave`> `Sleep` also causes this.
3. Hit power button. External screen wakes up (laptop screen is set to not turn on). It doesn't matter if I type my password and hit enter, or if I use kdeconnect to issue `loginctl unlock-session` instead of typing my password for the bug happen as long as step 1 is in check.
4. Waterfox seems fine but then turns transparent. It also doesn't matter if I used the lockscreen widget to continue the video playback before I could actually get to waterfox itself, or kdeconnect for the same thing.

**Expected behavior**
Waterfox alpha becomes transparent for some odd reason.

**Screenshots**
![youtube_with_blur](https://user-images.githubusercontent.com/19552720/60759126-01274e80-a028-11e9-948b-5c0968cbe2b0.png)
![youtube_without_blur](https://user-images.githubusercontent.com/19552720/60759127-01274e80-a028-11e9-97de-aadb90b125a4.png)
![reddit](https://user-images.githubusercontent.com/19552720/60759302-9c6df300-a02b-11e9-9d16-6816ee2c7733.png)

**Desktop (please complete the following information):**
Operating System: KDE neon 5.16
KDE Plasma Version: 5.16.2
KDE Frameworks Version: 5.59.0
Qt Version: 5.12.3
Kernel Version: 4.15.0-54-generic
OS Type: 64-bit
Waterfox: 68.0a1 (2019-05-07) (64-bit)

**Additional information**
I have almost all windows be transparent with a kwin rule. Waterfox is one of the windows that I make transparent. Making waterfox 100% transparent doesn't change anything if steps are reproduced, I tried.
Also obviously this is the only application where this happens.

**Comment by grahamperrin** [comment]
Which compositor rendering backend do you use, and which others are available?

Here: 

- FreeBSD-CURRENT
- KDE Plasma 5.16.2
- KDE Frameworks 5.59.0
- Qt 5.12.2
- XRender in use. 

When I last tried OpenGL 2.1 and 3.0 in lieu of XRender, there were problems e.g. blacked-out areas in Waterfox Classic and some other apps.

**Comment by RaitaroH** [comment]
According to the Compositor settings I have:
Scale method: Smooth
Rendering backend: OpenGL 3.1
vsync: Auto

Edit: I just tested it out and it happens on OGL 3.1, 2.0 and xRender too. For xRender it almost looks like the window is not even there at all.

**Comment by RaitaroH** [comment]
I have discovered another way this happens.
1. start waterfox
2. open youtube, have a video playing
3. switch desktops (for me 1 > 2)
4. kwin hangs a while https://bugs.kde.org/show_bug.cgi?id=408475
5. go back to the desktop where waterfox is
6. now waterfox is transparent

I thought perhaps is happening only when the laptop is on AC, but happens even when on power (I notice this after a few experiments). I also thought perhaps it happens if on the 2nd desktop I change the power from AC to battery, or vice-versa. It might be possible that a combination of the above causes kwin to start hanging and maybe waterfox to react, I am not sure.

Edit: after logging out and back in, I can say the above still holds true, but I am not sure if the power status change affects anything.
