### ISSUE TITLE
v68: Disable "Recommend (extensions/features) as you browse"

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1058]
Currently Waterfox 68 has the following prefs defaulted to `true` -

`browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons`
`browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features`

These are the settings "Recommend extensions as you browse" and "Recommend features as you browse", respectively.  I suspect these settings might not work in Waterfox, because I didn't notice this until I went through `about:preferences` for unrelated reasons, and the associated "Learn more" links do nothing.  If however these settings actually are functional, and if some users want this, it should be **opt-in**: pushing extensions on people who didn't request such recommendations seems spammy and anti-user.

Both prefs should be defaulted to `false`.  If they don't work they should be locked to `false` to avoid mis-impressions.

**Comment by grahamperrin** [comment]
> opt-in

👍

Nit (for readers who may be unfamiliar with the behaviour): 

> pushing extensions 

It's the appearance of recommendations, not extensions, that can feel pushy. 

Particularly obtrusive where the URL area is not particularly wide; YMMV. 

> as you browse

Also wrong, IMHO, the default clutter in the **Extensions** area: 

![image](https://user-images.githubusercontent.com/192271/61010448-30aec180-a36e-11e9-8263-76d895d8d8b9.png)

Is there a preference to suppress recommendations in this area? 

The adjacent area, **Recommendations**, is not difficult to find.

**Comment by laniakea64** [comment]
> Also wrong, IMHO, the default clutter in the **Extensions** area:
> 
> ...
> 
> Is there a preference to suppress recommendations in this area?

That is totally broken in Waterfox 68.0a2, and thus has already been hard-disabled - https://github.com/MrAlex94/Waterfox/pull/1041

**Comment by grahamperrin** [comment]
Thanks, does #1041 prevent appearance of the Recommendations area?

**Comment by laniakea64** [comment]
> Thanks, does #1041 prevent appearance of the Recommendations area?

It doesn't affect it.  The Recommendations area is still there in both htmlaboutaddons and classic `about:addons`.  But it doesn't actually show recommendations, and it didn't before that PR either.

**Comment by grahamperrin** [comment]
(Thanks … I'm still limited to the binary that shows _Get Add-ons_ (not _Recommendations_) – I guess, I should take a closer look after the next binary is distributed.)

**Comment by laniakea64** [comment]
It likely wouldn't be hard for me to do a pull request to resolve this issue, but as noted in the description I would need to know whether "Recommend extensions as you browse" and "Recommend features as you browse" actually work in Waterfox.  I don't know how to check.

**Comment by laniakea64** [comment]
I wasn't looking at the right things when searching the Waterfox code in relation to this.

To answer my own question, **Seems this was intentionally disabled in https://github.com/MrAlex94/Waterfox/commit/1983d09d4f35d6d9e58f8088b55018e40525feb4#diff-d7a0401e94f68887594ad1d1d9f9c28dR1307 .**

So these prefs need to be locked to `false`, and the preferences UI should probably be removed to avoid confusion.  I will try to look into creating the patches for this, but so far this is proving somewhat more involved than just a simple pref flip.
