### ISSUE TITLE
Downloads Window Open/Close causes Crash.

### ISSUE THREAD

**Issue by pjpreilly** [BrowserWorks/waterfox#1059]
Bug in 56.2.12 on mac os X Lion 10.7.5 in Safe mode ....

Newly introduced, not an issue in 56.2.11......

    Open Tools->Download window (with at least one entry in Download History).

    Close window.

    Observe browser crash.

Repeatable on multiple machines macbook 4,1 & macbook 3,1.

Not observable in Linux.
No issues in mac os x 10.14.5

Process:         waterfox [1888]
Path:            /Applications/Waterfox.app/Contents/MacOS/waterfox
Identifier:      org.waterfoxproject.waterfox
Version:         56.2.12 (5619.7.9)
Code Type:       X86-64 (Native)
Parent Process:  launchd [131]

Date/Time:       2019-07-11 00:59:53.361 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1196123 sec
Crashes Since Last Report:           256
Per-App Interval Since Last Report:  7581 sec
Per-App Crashes Since Last Report:   22
Anonymous UUID:                      4B64AF20-57E4-4EC9-B310-FEF9E693E931

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: 0x000000000000000d, 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000103b18000-0000000103b1a000 [    8K] r-x/rwx SM=COW  /Applications/Waterfox.app/Contents/MacOS/waterfox

Application Specific Information:
objc_msgSend() selector name: retain
objc[1888]: garbage collection is OFF

**Comment by grahamperrin** [comment]
https://redd.it/cz9zcy

>> … built with OS X 10.11 SDK once again, which should alleviate crashes. …

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by grahamperrin** [comment]
@MacMoinsen please follow these steps with Waterfox Classic 56.2.12. The first step is an address: 

1. about:config?filter=browser.tabs.remote.force-disable
2. add (or set) a boolean preference
3. `browser.tabs.remote.force-disable`
4. `true`
5. quit.

Is the next run of 56.2.12 free from the issue?

**Comment by MacMoinsen** [comment]
@grahamperrin 

Hi,
I set this boolean preference 
`browser.tabs.remote.force-disable | true`
as you suggest, but the crashing remains.

A crash occurs when I choose "Show all Downloads" from the Download status pop-up: The 'All Downloads' window appears and the browser crashes after a second.

Another crashing occurs _sporadically_ when I right-click on images on websites and choose "Save image as...". The save target pop-up appears but after choosing a location, the browser crashes. I tested this several times, both with the add-on 'Ublock Origin' activated and deactivated – in both states, a crash occurs, but not every time. 

Hope that helps. I'm attaching the crash report file.

Cheers

[Crash report Waterfox_2019-10-24-015635_xxx.txt](https://github.com/MrAlex94/Waterfox/files/3765097/Crash.report.Waterfox_2019-10-24-015635_xxx.txt)

**Comment by grahamperrin** [comment]
@MacMoinsen thanks, and I should probably encourage a separate issue for the **Save image as…** crash, which (at a glance) involves a [modal dialogue](https://en.wikipedia.org/wiki/Alert_dialog_box#Usage).

**Comment by grahamperrin** [comment]
From <https://www.reddit.com/comments/dmkrxs/-/f5665mb/>: 

> Steps to reproduce:
> 
> - Try to Download a file
> - Open the Download Manager (Tools > Downloads)
> - Close the Download Manager
> 
> And the browser crashes. Here's the log output:
> 
>> `2019-10-25 09:54:11.451 waterfox[846:707] Mozilla has caught an Obj-C exception [NSInvalidArgumentException: -[NSImage drawInRect:]: unrecognized selector sent to instance 0x136655880]`
> 
> https://developer.apple.com/documentation/appkit/nsimage/1519863-drawinrect
> 
>> macOS 10.9+
> 
> All occurrences of NSImage drawInRect should be removed to ensure compatibility with MacOS 10.8.5.

**Comment by tmkk** [comment]
If the problem comes from [this](https://github.com/MrAlex94/Waterfox/commit/232f10ceada165afc96a6f92abc690ea4cb7e588#diff-2b861b8ee353b5d8f20ce32254b27a47R372) (a commit between 56.2.11 and 56.2.12), it can be replaced with backward-compatible code
`[iconImage drawInRect:NSMakeRect(0, 0, width, height) fromRect:NSZeroRect operation:NSCompositeSourceOver fraction:1.0];`

```diff
--- image/decoders/icon/mac/nsIconChannelCocoa.mm.orig	2019-10-28 00:18:29.000000000 +0900
+++ image/decoders/icon/mac/nsIconChannelCocoa.mm	2019-10-28 00:19:09.000000000 +0900
@@ -369,7 +369,7 @@ nsIconChannel::MakeInputStream(nsIInputS
   [NSGraphicsContext setCurrentContext:[NSGraphicsContext graphicsContextWithGraphicsPort:ctx
                                                                                   flipped:NO]];
 
-  [iconImage drawInRect:NSMakeRect(0, 0, width, height)];
+  [iconImage drawInRect:NSMakeRect(0, 0, width, height) fromRect:NSZeroRect operation:NSCompositeSourceOver fraction:1.0];
 
   [NSGraphicsContext setCurrentContext:oldContext];
 
```
