### ISSUE TITLE
Can Only Load 4 Add-Ons at Startup

### ISSUE THREAD

**Issue by Petros606** [BrowserWorks/waterfox#1060]
Using Waterfox 56.2.11 (64-bit), Windows 7

I believe this is a duplicate and has already been reported.

I have 6 Add-ons installed. If all are enabled, only 4 are enabled after closing browser and restarting. The others are automatically disabled.

Add-ons:

Browser Backgrounds 0.49
Enhancer For YouTube 2.0.93
Ghostery 8.3.4
uBlock Origin 1.20.2
Dark Mode for Firefox 1.6
Video DownloadHelper 7.3.6

If you enable all 6, close browser then restart, only the first 4 Add-ons will be enabled. The others are disabled.

Someone at Mozilla said to try changing extensions.logging.enabled to true, but that did not help. I set it back to false.

**Comment by grahamperrin** [comment]
> Dark Mode for Firefox 1.6

What's the address for this extension? 

The other five are enabled without difficulty (and not automatically disabled) with Waterfox Classic 56.2.10.1 on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/61074654-19281500-a410-11e9-8623-1c57063e09f9.png)

**Comment by Petros606** [comment]
Dark Mode for Firefox V 1.6  https://addons.mozilla.org/en-US/firefox/addon/dark-mode-for-firefox/

You are using a version of Waterfox I do not have. Mine says it's up to date with V 56.2.11, not 56.2.10.1

**Comment by Petros606** [comment]
And when you close Waterfox browser and restart no Add-on is disabled automatically?

**Comment by grahamperrin** [comment]
The six extensions, enabled with 56.2.12 on Lubuntu Linux: 

![image](https://user-images.githubusercontent.com/192271/61078276-2c3ee300-a418-11e9-8469-cfee88f30ab8.png)

> … only 4 are enabled after closing browser and restarting. The others are automatically disabled.

I can not reproduce those symptoms.

**Comment by Petros606** [comment]
I'm not using Linux. I'm using Windows 7 (64 bit). Waterfox V 56.2.11.

**Comment by Petros606** [comment]
Just downloaded and installed Waterfox update to V 56.2.12 for Windows 7 (64-bit). 

Same exact problem still occurs. The Add-ons above are installed. If you enable all of them, the first 4 I installed will stay enabled, but the last two on the list are disabled when you close browser and then restart.

**Comment by grahamperrin** [comment]
Reproducible with a new profile? 

- about:profiles

**Comment by Petros606** [comment]
If I disable one of the first 4, such as YouTube Video Enhancer, and enable one of the last two, such as Video DownloadHelper, when I close browser and restart same thing occurs. YouTube Enhancer is now enabled and Video DownloadHelper is disabled. It's as if the first 4 Add-ons are locked as enabled and won't change despite settings.

**Comment by Petros606** [comment]
Not reproducible with new profile. Problem is not there now. 

Don't know what might be different in new profile.

**Comment by grahamperrin** [comment]
OK, try refreshing the problematic profile. 

- about:support

**Comment by Petros606** [comment]
Refresh of profile did not fix problem. This was the default profile. I just created a new profile, imported my bookmarks, re-installed Add-ons, and issue is gone. I'll keep working with the new profile.

Thanks for helping!
