### ISSUE TITLE
os x Lion is BROKE!

### ISSUE THREAD

**Issue by pjpreilly** [BrowserWorks/waterfox#1061]
Found another instance of a crash on os x Lion 10.7.5 with 56.2.12....

1. Open Preference and scroll to Performance ...
2. Uncheck "Use recommended ....."
3. Uncheck "Use hardware acceleration...."
4. Close Preferences Tab
5. Browser will soon crash.
..tested on macbook 4,1 & 3,1.

Process:         waterfox [196]
Path:            /Applications/Waterfox.app/Contents/MacOS/waterfox
Identifier:      org.waterfoxproject.waterfox
Version:         56.2.12 (5619.7.9)
Code Type:       X86-64 (Native)
Parent Process:  launchd [131]

Date/Time:       2019-07-11 14:53:17.953 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1197321 sec
Crashes Since Last Report:           257
Per-App Interval Since Last Report:  8408 sec
Per-App Crashes Since Last Report:   23
Anonymous UUID:                      4B64AF20-57E4-4EC9-B310-FEF9E693E931

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: 0x000000000000000d, 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 000000010ee74000-000000010ee76000 [    8K] r-x/rwx SM=COW  /Applications/Waterfox.app/Contents/MacOS/waterfox

Application Specific Information:
objc_msgSend() selector name: retain
objc[196]: garbage collection is OFF

**Comment by MrAlex94** [comment]
Hardware acceleration has never worked and should remain turned off.

**Comment by grahamperrin** [comment]
> - …
> - Uncheck "Use hardware acceleration...."
> - …

After the crash, does 56.2.12 remain stable with the feature disabled?

PS sorry, crossed paths with Alex's comment.

**Comment by pjpreilly** [comment]
...Here it is boiled down....
1. Open Preferences
2. Change something (check/uncheck) (I just did smooth scrolling this time but it doesn't really matter what)
3. Close Preferences Tab
4. Browser will soon crash

Browser remains stable as long as nothing is changed in Preferences tab.

Process:         waterfox [1185]
Path:            /Applications/Waterfox.app/Contents/MacOS/waterfox
Identifier:      org.waterfoxproject.waterfox
Version:         56.2.12 (5619.7.9)
Code Type:       X86-64 (Native)
Parent Process:  launchd [131]

Date/Time:       2019-07-11 15:23:14.507 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1198477 sec
Crashes Since Last Report:           262
Per-App Interval Since Last Report:  9457 sec
Per-App Crashes Since Last Report:   28
Anonymous UUID:                      4B64AF20-57E4-4EC9-B310-FEF9E693E931

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: 0x000000000000000d, 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000109bff000-0000000109c01000 [    8K] r-x/rwx SM=COW  /Applications/Waterfox.app/Contents/MacOS/waterfox

Application Specific Information:
objc_msgSend() selector name: retain
objc[1185]: garbage collection is OFF

**Comment by pjpreilly** [comment]
Verified happening in Safe Mode.

**Comment by pjpreilly** [comment]
...Maybe check your build logs? I don't think all went as it should have.

**Comment by MrAlex94** [comment]
Waterfox 56 has never supported hardware acceleration or e10s on version of macOS < 10.10

**Comment by pjpreilly** [comment]
Yeah I know ...Preferences is causing the crash ... not any one option in there!!!

**Comment by pjpreilly** [comment]
... Like I said checking or unchecking smooth scrolling & then closing the tab will cause the crash.

**Comment by pjpreilly** [comment]
... Found if I open Preferences Tab then access Dashboard App(contents not relevant, empty will work) the browser will IMMEDIATELY crash. This should be easily reproducible by anyone on os x 10.7.5. Lion.
Tested in Safe Mode.

**Comment by grahamperrin** [comment]
https://redd.it/cz9zcy

>> … built with OS X 10.11 SDK once again, which should alleviate crashes. …

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by grahamperrin** [comment]
@pjpreilly can you edit the subject line here? 

To make the issue distinctive when viewed amongst a list of other issues. Thanks.

**Comment by pjpreilly** [comment]
I'm done! I've given you guys a link to download a os x Lion install image. If you want to test it download the image & install it & test it on YOUR platform. Go the extra mile if you really care!

**Comment by pjpreilly** [comment]
Stage it if you really care!

... to make any progress.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/1217#issuecomment-544823883
