### ISSUE TITLE
No update shown in 56.2.11 in "about waterfox"

### ISSUE THREAD

**Issue by c33s** [BrowserWorks/waterfox#1062]
**Describe the bug**
being on waterfox 56.2.11 looking for an update does not show a update even if there should be an update (56.2.12)

**To Reproduce**
1. Go to 'Help' > 'about waterfox'
2. you see "waterfox is uptodate" even if 56.2.12 exist

**Expected behavior**
normal update behavior. there is a new version .... click here to update

**Desktop (please complete the following information):**
 - OS: win
 - Version; 7x64

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/cb6uu9/-/eti1ocr/?context=1>:

> … updates rolled out reasonably soon afterwards.
