### ISSUE TITLE
Waterfox does not display user profile info properly on QRZ.com with uBlock Origin installed

### ISSUE THREAD

**Issue by willbprog127** [BrowserWorks/waterfox#1065]
**Describe the bug**
Amateur radio operator profile information does not show up in Waterfox when using uBlock Origin on QRZ.com.  This is with a completely new Waterfox profile.  Using a completely new profile in Firefox with uBlock Origin works fine, so it does not appear to be only a uBlock Origin problem.

**To Reproduce**
1. Rename your current Waterfox profile to something else (just for testing)
2. Start Waterfox
3. Go to the Firefox add-ons page and install uBlock Origin
4. Go to https://www.qrz.com/db/N6ZN
5. Observe that there is *no* user profile information for N6ZN under the 'Biography' tab, even though the footer for that section shows 1067 bytes currently being used for the Biography (meaning it's not an empty biography).

**Expected behavior**
N6ZN's biography information should be displayed.

**Desktop info**
 - OS: macOS 10.14.x, MacOS 10.11.x
 - Waterfox version: 56.2.12 (64-bit)

**Additional context**
Although I'm not 100 percent sure, it appears this site is using Javascript and JQuery to synthesize an iframe to display the user's information.  This works fine on Firefox with uBO but obviously not on the current Waterfox.

This bug is worrisome, because what if other content on other sites is not being displayed due to this bug?  I do a lot of research, especially for computer programming information, and this could omit important information I need.

Thanks! 👍

**Comment by grahamperrin** [comment]
Also [Issue with Water fox incorrectly loading QRZ.com · Issue #612 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/612)

**Comment by hawkeye116477** [comment]
**Mozregression result:**
* Last bad: Firefox v58.0a1 (2017-09-21)
 * First good: Firefox v58.01 (2017-09-22)

Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=319a34bea9e4f3459886b5b9e835bd338320f1fd&tochange=3d72fdb0e561ea59d9e5850c3e71367dbb8a7148

Update: I guess that's the fix => https://bugzilla.mozilla.org/show_bug.cgi?id=1379148, I'll test and add to PR.

**Comment by grahamperrin** [comment]
@hawkeye116477 OT, please, why do you sometimes suppress links?

I sometimes suppress when referring _without certainty_ from one thing in GitHub to another in GitHub – to avoid automatic cross-referencing – but I can't guess why (above, for example) there's no link to bug 1379148. 

TIA

**Comment by hawkeye116477** [comment]
@grahamperrin GitHub doesn't like links, sometimes they block users for too many links (they consider a bot).

**Comment by ghost** [comment]
Bug 1379148 also mentioned here: https://github.com/MrAlex94/Waterfox/issues/856

**Comment by grahamperrin** [comment]
@hawkeye116477 thanks for the explanation (and don't change your habit if it's a worry).
