### ISSUE TITLE
waterfox can't display images with div and a elements

### ISSUE THREAD

**Issue by vesselict** [BrowserWorks/waterfox#1066]
I have problems with latest version on both windows and linux of displaying images on sites without `<img />` element but with` <div>` and `<a> `elements ...

On firefox everything works just fine.

**Comment by laniakea64** [comment]
> latest version

56.2.12 or 68.0a2?



> sites without `<img />` element but with` <div>` and `<a> `elements ...

Could you please share some example links?

**Comment by vesselict** [comment]
sure..
https://www.insomnia.gr/classifieds/category/68-motorola/

56.2.12 I had this problem on older versions too.

**Comment by laniakea64** [comment]
I see the same issue here in Waterfox 56.2.12, new profile.  Works fine in Waterfox 68.0a2 in my main profile.

So far I was unable to figure out why it isn't working in 56.2.12.  There are no related errors in the console, and setting user-agent override of Firefox 60 or Firefox 68 didn't help.

That site is using a standard method of 'lazy loading images', i.e. the images should load only when you scroll them into view, so I would suspect this breakage is not isolated to the one site.

**Comment by colvacdir** [comment]
As of version 56.2.14, this problem still exists. Has any progress been made on what's causing the issue and if it will be fixed in a future version?

I tested the sample URL mentioned above with a couple of similar browsers, Firefox ESR 52.9.0 and TenFourFox FPR 16, and it works fine with both of those, which indicates it's specifically tied to Waterfox.

**Comment by hawkeye116477** [comment]
It seems that images are loaded by `https://cdn2.insomnia.gr/uploads/javascript_global/root_framework.js.76eb380d05b2cd352f3268aa6cf46ad8.js`. It uses `data-background-src` to apply background to css. That's fixed on FF 57.

**Comment by micokeman** [comment]
I also noticed that this site deosn't work on Waterfox version 56.2.14 

https://www.mlb.com/standings#wildCardSubNav

**Comment by grahamperrin** [comment]
Meta, tracking: #538

@micokeman FYI there's related discussion at [mlb.com Banner Rendering Issues. : waterfox](https://www.reddit.com/r/waterfox/comments/d62qit/mlbcom_banner_rendering_issues/)

**Comment by hawkeye116477** [comment]
**Mozregression result:**
- Last bad: Firefox v57.0a1 (2017-09-18)
- First good: Firefox v57.01 (2017-09-19)

Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=42151fcd6cfc216d147730d0f2c6a2acd52d22fd&tochange=a0eb21bf55e1c1ae0ba311e6f2273da05c712799

`I tested the sample URL mentioned above with a couple of similar browsers, Firefox ESR 52.9.0 and TenFourFox FPR 16, and it works fine with both of those, which indicates it's specifically tied to Waterfox.`
This is not entirely true, seems that was working fine on FF 52, but they broke it on next versions, removed something which was needed and seems that's the fix => https://bugzilla.mozilla.org/show_bug.cgi?id=1399605 (they restored that condition).

**Comment by hawkeye116477** [comment]
@vesselict If problem with `insomnia.gr` is fixed, then you can close issue :smile:.
