### ISSUE TITLE
alpha 68.0a1 hulu SourceMap networkError

### ISSUE THREAD

**Issue by Commissar0617** [BrowserWorks/waterfox#1068]
**Describe the bug**
looks like the issues regarding location services are back in alpha. the fix applied prior.. is already applied by default, it seems. 

**To Reproduce**
open hulu

"We are unable to determine your location

If this issue persists please try a different browser to watch Hulu with Live TV on your computer"

**Expected behavior**
hould work. attempted to do the fix from 58, but already applied. almost liek ti's a hardcoded disable, but i find that hard to believe. 

**Screenshots**

**Desktop (please complete the following information):**
 - win 10
10.0.18362 build 18362

WF alpha 68.0a1 (2019-05-07)

**Comment by Commissar0617** [comment]
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://www.hulu.com/static-assets/h3o-browse/_next/static/commons/main-925de7de185b09ac7d63.js
Source Map URL: http://ssgs.dc.prod.hulu.com/site-source-maps/h3o-browse/static/commons/main-925de7de185b09ac7d63.js-fccc57c6e30c8d5ce47b.js.map


shows this in console

**Comment by grahamperrin** [comment]
> location services

When 68.0a2 becomes generally available, please try https://roadtrip.glitch.me/ ▶ **Start the road trip**

For me it does appear to find my location (the map changes), but then there's an endlessly spinning asynchronous progress indicator. The same with both Waterfox Classic 56.2.12 and Waterfox 68.0.2 on Windows 10 – 

![image](https://user-images.githubusercontent.com/192271/62427315-56b74f80-b6e9-11e9-9ce2-9f01a246a9e1.png)

– but I don't know whether this is a peculiarity of testing in a virtual machine. 

(No such issue with Waterfox Classic on the host machine, FreeBSD-CURRENT.)
