### ISSUE TITLE
Waterfox 68.0a1 does not start

### ISSUE THREAD

**Issue by galstudio** [BrowserWorks/waterfox#1070]
When running, waterfox gives the following error:

XPCOMGlueLoad error for file /opt/waterfox/libxul.so:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/waterfox/libxul.so)
Couldn't load XPCOM.

 - OS: ubuntu 16.04
 - WF alpha 68.0a1

**Comment by grahamperrin** [comment]
Amongst the results at <https://www.google.com/search?q=%22%2Fusr%2Flib%2Fx86_64-linux-gnu%2Flibstdc%2B%2B.so.6%3A+version+%60GLIBCXX_3.4.22%27+not+found%22>: 

- https://stackoverflow.com/a/46613765/38108

The answer there is a year old so the versions might be outdated but I guess that the essence is the same: 

>> … need to upgrade `libstdc++6` …

### OS

> ubuntu 16.04

Re: https://wiki.ubuntu.com/Releases can you update? I imagine that doing so will (also) resolve the issue.

**Comment by galstudio** [comment]
Thank you, updated. How to install a language pack?

**Comment by hawkeye116477** [comment]
For Alpha langpacks currently not working.

**Comment by galstudio** [comment]
:(

**Comment by grahamperrin** [comment]
Subscribe to #1055 for updates re: language packs. 

If the start problem is resolved, you can close this issue. Thanks.
