### ISSUE TITLE
Suggestion: Built-in new tab Speeddial

### ISSUE THREAD

**Issue by ThePharaohArt** [BrowserWorks/waterfox#1073]
I've recently been using Opera, Vivaldi and Yandex browser and have fallen in love with speeddials in the new tabs. It makes the browser feel a bit more personal showing only the websites that you have selected to pin there either separately or in a folder. As well as allow users to upload their own picture as background of the startpage.

Hopefully Waterfox can have it's own version of what speeddials look like.

**Comment by grahamperrin** [comment]
Have you tried the Alpha of Waterfox 68?

**Comment by ThePharaohArt** [comment]
Yes, i have. And my suggestion still stands.
Waterfox simply uses Firefox's version of recent websites similar to Google Chrome, not speeddials still has a lot left to be desired when compared to Vivaldi, Opera or Yandex.
