### ISSUE TITLE
v68: Suggestion - neuter hardcoded search engines

### ISSUE THREAD

**Issue by GitCurious** [BrowserWorks/waterfox#1075]
Fx recently introduced hardcoded search engines as plugins - which are enabled by default.

Uneditable by the end user.

Even if they are "disabled" in search options and removed from the list of available options, they are still enabled !

**Suggestion: to allow more user control in Waterfox and either remove the generic list completely or at least have them not enabled running by default.**

**Comment by laniakea64** [comment]
The issue of the lack of needed user-accessible control is already filed: https://github.com/MrAlex94/Waterfox/issues/1045
