### ISSUE TITLE
question about non-alpha appimages

### ISSUE THREAD

**Issue by linuxgirl22** [BrowserWorks/waterfox#1078]
Hello :-) Just to ask if there will be non-alpha appimages. Worried incase the non-alpha waterfox will leave the AUR also, as I really don't want to go over to the alpha, for as long as possible (don't like using sync, and it looks like local backup wouldn't be an option?). 

(Really appreciate appimages, as, if there are issues with upgrades, which appear unable to be blocked now, when I look at settings, then the appimage is there.) Not sure how many users there are for non-alpha appimages, and I understand if busy, but it would be great to know what's happening and be able to plan accordingly. Thanks.

**Comment by hawkeye116477** [comment]
Stable AppImages still will be.
`I understand if busy`
It's not much work to do, only bump version :smile: For now it's repackaged from official package, but I'm gonna change that to be like with alpha, so it will be from CentOS and sometimes will appear little faster, as I will not have to wait until it appears on official site (I will publish it after tag on git and changelog on site).

**Comment by linuxgirl22** [comment]
Hi and thank you very much indeed, for responding, and for your work on the appimages. That's great news! :-)

**Comment by linuxgirl22** [comment]
Thank you very much for adding the latest stable appimage. :-)
