### ISSUE TITLE
Waterfox 56 rendering issue on many sites

### ISSUE THREAD

**Issue by N-R-G** [BrowserWorks/waterfox#1079]
Various site aren't correctly visualized with waterfox 56.2.12

example:
https://lichess.org/editor/8/8/8/8/8/8/8/8_w_-_-
appears to be an issue only with old firefox forks (before quantum):
https://awau.moe/4F5g5J3.png

others example in this reddit thread:

https://www.reddit.com/r/waterfox/comments/cfbh47/waterfox_breaks_certain_pages_on_pimoronicom/

**Comment by hawkeye116477** [comment]
Possibly related => https://bugzilla.mozilla.org/show_bug.cgi?id=1302667

Update: One of error on console is about `worker-src`, but after adding changes from `https://hg.mozilla.org/mozilla-central/rev/bbb4d0097263` and building rendering bug still happens, only error on console disappears .
Seems that something is not right with `grid-area: spare-bottom;`.
