### ISSUE TITLE
68.0a: cannot install language pack.

### ISSUE THREAD

**Issue by h0cheung** [BrowserWorks/waterfox#1082]
It stays at verifying, and can never be installed.

**Comment by grahamperrin** [comment]
[impossible to install … language · Issue #1055 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/1055)

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/1055#issuecomment-543903015 

> … no longer reproducible …
