### ISSUE TITLE
Can't login at belgacom.be

### ISSUE THREAD

**Issue by PiliJ** [BrowserWorks/waterfox#1083]
I'm trying to login as usual at https://login.belgacom.be/oauth/authorize?response_type=code&client_id=forum-insided-fr-client_id&redirect_uri=https%3A%2F%2Ffr.forum.proximus.be%2Fsso%2Freturn%2Foauth_proximus&state=b8d4e3d6eaa5a1e901f66114d1d1a2f258db9ad9&scope=USER+INFO+PLAIN ... in vain ! I receive a blanco page.
It's not the case with Firefox or IE.
Waterfox version 56.2.12.
Thank you.

**Comment by grahamperrin** [comment]
Is the issue reproducible with Waterfox in safe mode? 

- about:support

In safe mode, at https://www.proximus.be/login does login succeed?

**Comment by PiliJ** [comment]
I didn't think about that, I must say.
No, it works in safe mode, so that one of my modules would be responsible!?
Thank you grahamperrin.

**Comment by PiliJ** [comment]
First test was the good one : "Addon Compatibility reporter 2.2.4" was still active and had not been a problem so far.
Thank you again !
