### ISSUE TITLE
Request: Add support for KeePassXC-Browser

### ISSUE THREAD

**Issue by stefanos82** [BrowserWorks/waterfox#1084]
I use it with Chromium and with Firefox-ESR on my system (Debian testing 64-bit), but when I install the addon on WaterFox it cannot recognize the Firefox browser integration.

I guess it sees a different user agent behind the scenes, that's why it breaks.

**Comment by hawkeye116477** [comment]
`https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900`

**Comment by stefanos82** [comment]
Cool. What I did to make it work was to copy the entire folder named `native-messaging-hosts` from `~/.mozilla/` and copied it to `~/.waterfox/`.

Thank you @hawkeye116477
