### ISSUE TITLE
I can't see Waterfox in Android Playstore

### ISSUE THREAD

**Issue by Sadi58** [BrowserWorks/waterfox#1085]
Although I have 64-bit CPU (Sony Xperia L1) I can't see Waterfox in Android Playstore neither on my phone nor on my laptop when I visit http://play.google.com/store.

 - Device: Sony Xperia L1
 - OS: Android
 - Version 7.0

**Comment by DI555** [comment]
I hope it will be 'releases' here on github though! With F-droid store!
 Btw gp store is an evil ;), it injects spyware/metrics in their .apk (((.

**Comment by grahamperrin** [comment]
Cross references: 

- https://redd.it/ci65w6
- https://www.reddit.com/comments/d0sqos/-/ezfsi46/

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/dctx5f/-/f2c6w8n/

> I've been talking to Google. Their CS is zero. There isn't much to report back 🤷‍♂️

**Comment by 4evermaat** [comment]
@grahamperrin can you advise where to download legit copy of waterfox for android?

**Comment by grahamperrin** [comment]
I have no idea. Was anything relevant in Reddit? Maybe not limited to the three posts/comments linked from above. 

Reddit often can't find what's required in Reddit, so be prepared to try a Google search of `site:www.reddit.com/r/waterfox/`

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/dctx5f/-/f2c6w8n/?context=1

> I've been talking to Google. Their CS is zero. There isn't much to report back 🤷‍♂️

**Comment by Ibuprophen** [comment]
If anyone is referring to the 32-bit Waterfox App, the Beta version is still available on the Play Store that can only be seen/obtained by following the steps (outlined on the following post) requiring your signing up for the Beta version "first" and then you'll be able to see it on the Play Store. 

https://github.com/MrAlex94/Waterfox/issues/730#issuecomment-421647220 


Good Luck! 



~Ibuprophen

**Comment by grahamperrin** [comment]
> can't see Waterfox in Android Playstore

It's no longer missing. 

https://play.google.com/store/apps/details?id=net.waterfox.waterfox

- updated 2019-06-09
- version 68.0a2

@Sadi58 would you like to close this issue?

**Comment by grahamperrin** [comment]
For clarity (this might be known from something in Reddit, but it's not yet clear in this issue): 

- https://play.google.com/store/apps/details?id=net.waterfox.waterfox seems to present the application **only** if you are signed in; and if you previously installed the application.

Top left, it's truly not found: 

![image](https://user-images.githubusercontent.com/192271/67638821-c9972780-f8e0-11e9-8400-39836cb78a33.png)

– and with a signed in view, clicking the **Installed** button confirms: 

> This item isn't available.

![image](https://user-images.githubusercontent.com/192271/67638864-475b3300-f8e1-11e9-87e7-d8706839a671.png)

For the `/releases/` page link to the unavailable item: 

- WaterfoxCo/Waterfox#582

**Comment by Sadi58** [comment]
I chose to unsubscribe from this because I've concluded (1) that a web browser must be multi-platform and have synchronization feature, and (2) that it must have a strong team of developers and maintainers even if it is based on Chromium or Firefox. Otherwise you tend to face numerous problems. So good-bye to Waterfox, hello to Vivaldi or Brave browser.

**Comment by grahamperrin** [comment]
@Sadi58 sorry to lose you. 

Please, do not overlook Alex's comment (quoted above, https://github.com/MrAlex94/Waterfox/issues/1085#issuecomment-538193294) about zero customer support from Google; from this I assume that he **has** requested re-presentation of Waterfox in Google Play Store. 

If – _if_ – a developer gets nothing from Google, then is it fair to question the strength of a team that's seeking support from the organisation? 

Whilst I can not comment upon (have no knowledge of) details of this Waterfox case …

----

… I was, years before Waterfox existed, involved with a different open source project that suffered through a somewhat insane set of 'developments' to Google Groups. I'm glad to say that (after some years) things became sane but during the period when I tried, repeatedly, to explain the insanity: it was like banging my head against a brick wall. Not a rant against Google, just a factual observation …

**Comment by MrAlex94** [comment]
Sorry to see you go, but I don’t see what’s stopping you from using one of the various Firefox mobile browsers and using the sync feature of those while using Waterfox on desktop until things are resolved?

**Comment by Miouyouyou** [comment]
@MrAlex94 Could the removal of your app be related to the presence of donation links inside the app ?

The [Wireguard open source app](https://www.phoronix.com/scan.php?page=news_item&px=WireGuard-Is-Back-Play-Store) actually got removed from the Play Store for that reason, and [the Wireguard Android team actually removed all donations links from the application](https://git.zx2c4.com/wireguard-android/commit/?id=f0bab44b4a17b65e9f7e718a9ba9b2bc37041268) in order to get the app accepted back.

**Comment by Sadi58** [comment]
@MrAlex94 @grahamperrin Thank you and sorry for this. This is not actually the only reason for leaving Waterfox as an alternative to the biggies like Google Chrome and Mozilla Firefox. All the best...

**Comment by smnthermes** [comment]
What about F-Droid?

**Comment by grahamperrin** [comment]
> What about F-Droid?

▶ [F-Droid · Issue WaterfoxCo/Waterfox-Android#40 …](https://github.com/MrAlex94/Waterfox/issues/234)

**Comment by DI555** [comment]
still wait to see all the builds at least here in 'releases' , an free of gp services at all!

**Comment by grahamperrin** [comment]
Additional cross-references include: 

* https://redd.it/eukvn4
* https://redd.it/faq5yb
* https://redd.it/foclzf

## Some recent highlights

https://github.com/MrAlex94/Waterfox/issues/1038#issuecomment-578054148

>>>  In short, Google removed it and doesn't want to tell why.

[Waterfox has joined System1](https://www.waterfox.net/blog/waterfox-has-joined-system1/)

>> … understand what System1 does … partnership, … know the team … the right people to help me grow Waterfox. Down to earth …

<https://old.reddit.com/r/waterfox/comments/f3hi8s/privacy_browser_waterfox_appears_to_be_sold_to/fhl6crp/> with added emphasis: 

> … Thanks, I appreciate the rationality and also now that **System1** are onboard they're **helping sort out the issues with Google Play** :-)

https://www.system1.com/what-we-do#applications

> … newest addition, the Waterfox browser. …

**Comment by EmberHeartshine** [comment]
I run a personal F-Droid repository for apps that can't or won't be accepted/submitted to the mainline F-Droid repo (usually because they include nonfree components). If @MrAlex94 is willing to package standalone APKs (preferably using the Github Releases system, but I can work with anything that uses numeric version numbers; in one case I scrape the SourceForge page and parse the HTML) I can include it in my repo.
