### ISSUE TITLE
Incompatibility issue with Stay-Open Menu extension, browser.bookmarks.openInTabClosesMenu not working

### ISSUE THREAD

**Issue by Redyn** [BrowserWorks/waterfox#1086]
The extension doesn't seem to work at all with Waterfox, despite working with Firefox 52.9.0 and earlier.

I also tried this method:
https://www.askvg.com/firefox-tip-keep-bookmarks-folder-menu-visible-to-open-multiple-bookmarks-in-new-tabs/

But for some reason, browser.bookmarks.openInTabClosesMenu is a string rather than a boolean in my profile, and is non-functional.

**Comment by grahamperrin** [comment]
From <https://web.archive.org/web/20180730124942/https://addons.mozilla.org/en-US/firefox/addon/stay-open-menu/>:

>> **Version 3.0.2 is not compatible with Firefox 56.**
>>
>> See http://forums.mozillazine.org/viewtopic.php?f=48&t=633732 for information on a version compatible with Firefox 56 as well as details on other available versions. …

– there's a link to 3.1.1a1.

**Comment by Redyn** [comment]
My bad.

Is browser.bookmarks.openInTabClosesMenu supposed to be non-functional in Waterfox, though? Because I tried deleting it and recreating it as a boolean, and it still didn't work.
