### ISSUE TITLE
I have a sincere question

### ISSUE THREAD

**Issue by HETLAN** [BrowserWorks/waterfox#1087]
I have a sincere question. I don't know where to ask. no container option. Isn't that the big shortcoming? for example, how to protect from facebook? ublock, tampermonkey scripts and so on. etc. Does it protect us? please answer.

Please give me some info. I couldn't find the answer to my questions so I wrote it here. please help me

finally .. guess plugins aren't syncing? : /

please do not cover the subject. Help with questions.

**Comment by grahamperrin** [comment]
> container

▶ [Containers-related extensions with Waterfox 56.*](https://www.reddit.com/r/waterfox/comments/akfc0n/containersrelated_extensions_with_waterfox_56/)

> Facebook? ublock, tampermonkey scripts 

You'll probably find most such things discussed in the community support area (Reddit).

**Comment by hetlan** [comment]
Thanks a little helped. container plugini is incompatible. I install it smoothly, but the top right side of the plug-in opens empty. would be in older firefox versions.

**Comment by hetlan** [comment]
The page load speed depends on the amount of ram and its empty. for example, firefox developer edition also has a different ram busy or less performance, but not as much as WATERFOX. the other thing I noticed is that WATERFOX is ordinary, ie the normal firefox version [like firefox quantum], for example, the speed test shows a higher than normal ping. I don't know how to tell the difference. firefox developer edition is something you know between chromium and firefox. beautiful, fast. but it has telemetry problem. I think someone who knows the WATERFOX project well can understand my problem. do you understand? @grahamperrin

**Comment by Commissar0617** [comment]
move to alpha. 56 is almost2 years old, and while alex has done good keeping security updated, but it's still getting really long in the tooth

**Comment by HETLAN** [comment]
I wrote it a little but I understand it better if you simply rewrite it with a period and a comma. I would love to. || I think you know what I'm saying? Is it like I tried to explain the alpha version?

**Comment by HETLAN** [comment]
alpha ..

Quality of Life Improvements to be changed in future versions:

Change highlight row to have 4 rows by default. ;/
Allow reading of all manifests. :/

**Comment by MrAlex94** [comment]
> move to alpha. 56 is almost2 years old, and while alex has done good keeping security updated, but it's still getting really long in the tooth

Yeah, it's crazy looking how much the web has changed in those years. Anyway next Alpha is up, and it'll be useable day to day, it's just alpha in terms of what features will change etc.

**Comment by HETLAN** [comment]
he didn't even wear it. Sync is a trivial problem anyway. had already written. that's what you need. is not it?
