### ISSUE TITLE
Can't play ph videos

### ISSUE THREAD

**Issue by nomosaic** [BrowserWorks/waterfox#1088]
win7 waterfox x64 56.2.12
The video playing part has a black view.
![20190731195809](https://user-images.githubusercontent.com/14254798/62209912-71c64e80-b3cd-11e9-88a3-14ce1dac1ae1.jpg)

**Comment by grahamperrin** [comment]
Reproducible with Waterfox in safe mode?

- about:support

Reproducible with a new profile? 

- about:profiles

Playback works here, Waterfox Classic 56.2.12 on FreeBSD-CURRENT

**Comment by nomosaic** [comment]
> 
> 
> Reproducible with Waterfox in safe mode?
> 
>     * about:support
> 
> 
> Reproducible with a new profile?
> 
>     * about:profiles
> 
> 
> Playback works here, Waterfox Classic 56.2.12 on FreeBSD-CURRENT

I'm using in windows, Chrome 75 played well. Safe mode is the same with the normal mode.

**Comment by grahamperrin** [comment]
Thanks. Is the issue reproducible with a new profile?

No problem here with Waterfox Classic on Windows 10.

**Comment by nomosaic** [comment]
Pornhub videos are not loaded if I enable the Shadow Dom option in "about:config".

**Comment by Squall-Leonhart** [comment]
then don't enable it.
