### ISSUE TITLE
68.0a2 tabs now have black background with black text

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1090]
**Describe the bug**
In latest 68.0a2 tabs background is black with Default or Light theme.  Because those themes use black text, this leaves the tab unreadable and visually unusable.

**To Reproduce**
Tools > Add-ons Manager > Themes, enable either Default or Light

**Expected behavior**
Tabs should be gray/light-gray with black text.

**Screenshots**
![Screen shot 2019-08-04 1](https://user-images.githubusercontent.com/16628411/62426178-8e090a80-b6af-11e9-8f61-79d3a65dd131.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04
 - Waterfox 68.0a2 self built from https://github.com/MrAlex94/Waterfox/commit/b5059dc5ab2699d335dfa9c8c01a5a3c3a7942bd

**Additional context**
Sometimes the tabs look as expected briefly after a restart.  But as the browser is used, e.g. if the Add-ons Manager is opened, it will revert back to the unusable black background.

The black background also happens with Dark theme and with personas, but in those cases the text is white and light grey respectively, so one workaround could be to use either Dark theme or a persona.

**Comment by grahamperrin** [comment]
68.0a2 on Windows (to the right), default theme: 

![image](https://user-images.githubusercontent.com/192271/62426730-7433eb80-b6e0-11e9-87a8-db56fa20ba88.png)

– and light: 

![image](https://user-images.githubusercontent.com/192271/62426738-99285e80-b6e0-11e9-81ad-46029400d52a.png)

**Comment by grahamperrin** [comment]
Reproducible with (unannounced) build 20190906171246 of 68.0b1: 

![image](https://user-images.githubusercontent.com/192271/64485018-7ffc5b80-d212-11e9-85d8-941adf4ff74a.png)

Below, the bug is **not immediately apparent** – it occurs (for example): 

- after taking the about:preferences route to **about:support**

https://s.put.re/pbN6Ux85.mp4

Another example, thanks to @troysjanda:

- after taking the hamburger menu route to **about:addons**

… and so on.

**Comment by grahamperrin** [comment]
Cross references: 

- https://www.reddit.com/comments/d15yea/-/ezr7139/?context=1
- [UserChrome.css stops working if user open about:addons : waterfox](https://www.reddit.com/r/waterfox/comments/d1z27a/userchromecss_stops_working_if_user_open/)

**Comment by MrAlex94** [comment]
Hmm, will see look into why the CSS isn't unregistering properly.

**Comment by laniakea64** [comment]
> Hmm, will see look into why the CSS isn't unregistering properly.

@MrAlex94 Because it's being reapplied by this code -
https://github.com/MrAlex94/Waterfox/blob/ab1960eee6162fd2b824118e3208414013718f7d/toolkit/mozapps/extensions/internal/AddonSettings.jsm#L67-L72

**Comment by MrAlex94** [comment]
That’s correct, looks like I missed out the unregister code I used when
testing.

**Comment by laniakea64** [comment]
Fixed by https://github.com/MrAlex94/Waterfox/commit/0e1ff89a741a6853547465dd0d5d6ae9ffad6684 .  Thanks! :+1:
