### ISSUE TITLE
The links on the website still point to 68.0a1 instead of 68.0a2 For Windows

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#1092]
I didn't check the others, however I know the build is up there as changing the URL got me the installer. Just FYI

**Comment by ilikenwf** [comment]
...also it's installer attempts to install to the "Waterfox" directory, not the "Waterfox Alpha" directory.

**Comment by tycrek** [comment]
If anyone comes here looking for it, [this](https://storage-waterfox.netdna-ssl.com/Waterfox/aurora/WINNT/Waterfox%2068.0a2%20Setup.exe) is the link to the installer.

I'm glad to see the sync page and bookmarking has been fixed.

**Comment by grahamperrin** [comment]
Re: https://www.reddit.com/comments/cm7g9g/-/ew0gnv2/ I shouldn't expect an update to the page until after builds for all three platforms have been seeded.

**Comment by grahamperrin** [comment]
From <https://www.reddit.com/comments/cm7g9g/-/ewrlt61/?context=1>:

> … Some more bug fixes then next alpha :-)

**Comment by Commissar0617** [comment]
says there's an update, points to a2, but 404s now

**Comment by grahamperrin** [comment]
<https://www.waterfox.net/update/Waterfox/68.0a1/aurora/WINNT/update.xml> at the time of writing: 

```xml
<updates>
 <update type="major" appVersion="68.0a2" buildID="20190801144413" detailsURL="https://www.waterfox.net/blog/waterfox-68.0a2-release-download" displayVersion="68.0a2" extensionVersion="68.0a2" platformVersion="68.0a2" version="68.0a2">
  <patch type="complete" URL="https://storage-waterfox.netdna-ssl.com/releases/win64/update/waterfox-68.0a2.en-US.win64.complete.xz.mar" hashFunction="SHA512" hashValue="7ac903014c247d990f23d1fbabea213ea5bb27be8dd9575589db23fa28392a1a35e386e1fae3e57ab05bf5ad84cdc2575a0a834ee5b9180fed7139a5ac86814a" size="53778562"/>
 </update>
</updates>
```

– and `https://storage-waterfox.netdna-ssl.com/releases/win64/update/waterfox-68.0a2.en-US.win64.complete.xz.mar` is not yet available. 

As the auto-update for Waterfox Classic is currently _to follow_, so I guess the auto-update for the alpha is also to follow …

**Comment by grahamperrin** [comment]
@ilikenwf you can probably close this issue now. Thanks.
