### ISSUE TITLE
Dissenter Extension displays incorrectly on Windows 10 version

### ISSUE THREAD

**Issue by tcreek** [BrowserWorks/waterfox#1093]
So here is the Windows version.

![2019-08-08](https://user-images.githubusercontent.com/4149717/62729395-7b5e4080-b9e3-11e9-960f-8334a06b9327.png)

And the Linux (Debian) so you can see the comparison

![Screenshot from 2019-08-08 13-35-42](https://user-images.githubusercontent.com/4149717/62729531-bfe9dc00-b9e3-11e9-8bc1-ad80050993bf.png)

Since it is the same version of the extension, I am assuming it is Waterfox with the issue.

Both OSs are using version 56.2.12, and both using Dissenter version 0.1.10

**Comment by grahamperrin** [comment]
56.2.12 on Windows 10: 

![image](https://user-images.githubusercontent.com/192271/62730764-913a2880-ba18-11e9-9a81-07df133beda5.png)
![image](https://user-images.githubusercontent.com/192271/62730847-c181c700-ba18-11e9-84b2-fb700a865b21.png)

**Comment by tcreek** [comment]
Well, seems some are having issues. I have removed it, and installed again with same results.

**Comment by SenpaiSharp** [comment]
Do you have any other plugins that would be messing with the default zoom levels of web pages or altering their content in any other major way?

**Comment by tcreek** [comment]
No. I have the same one 3 ones on each browser.

TrackMeNot
TabMixPlus
Dissenter

**Comment by grahamperrin** [comment]
Reproducible with a new profile? 

- about:profiles

Can you provide a full-screen shot? It might help to sort of read between the lines of the issue …

**Comment by tcreek** [comment]
I created a new profile, It is the same exact result.

**Comment by tcreek** [comment]
I created a new profile, It is the same exact result.

![2019-08-24](https://user-images.githubusercontent.com/4149717/63642941-c5565000-c68c-11e9-80b2-609139459883.png)

**Comment by grahamperrin** [comment]
Thanks, is that full screen or a full window?

What resolution is the display?

**Comment by tcreek** [comment]
That is full screen @ 1920 x 1080

**Comment by grahamperrin** [comment]
Which version of Windows? 

What's the hardware setup? 

[Windows scaling issues for high-DPI devices](https://support.microsoft.com/help/3025083/windows-scaling-issues-for-high-dpi-devices)

Maybe report the issue to developers of the extension, https://github.com/gab-ai-inc/gab-dissenter-extension/issues

**Comment by tcreek** [comment]
Windows 10. It's a one year old laptop.  I use the browser in an external monitor. Moving the browser to the main laptop screen, which is also 1920 x 1080, makes the extension appear correctly.

I will give them a try and see what they have to say

**Comment by grahamperrin** [comment]
> … laptop … 1920 x 1080, …

What make and model is the laptop?

**Comment by tcreek** [comment]
HP Pavilion Laptop 15-CC5XX

**Comment by grahamperrin** [comment]
Does it have the 4K (3,840 x 2,160) IPS option?

**Comment by tcreek** [comment]
I am not sure about that, but it is capable of supporting an external 4k monitor.

**Comment by tcreek** [comment]
Here is a screen shot of FireFox 69.0.2 with Dissenter version 0.1.10 on the same screen as is Waterfox

![2019-10-03](https://user-images.githubusercontent.com/4149717/66149130-0de02200-e5d8-11e9-8ae5-43760d44eb9f.png)

**Comment by grahamperrin** [comment]
If you like, use [mozregression](https://mozilla.github.io/mozregression/) to tell which build of Firefox was the last to be bugged in the same way as Waterfox Classic. 

If that can be told, then it should become easier to pinpoint the Mozilla commit(s) from which a fix might apply to Waterfox Classic.

**Comment by tcreek** [comment]
Seems to me a Waterfox issue

![2019-10-07](https://user-images.githubusercontent.com/4149717/66318681-6158b580-e8e1-11e9-807f-4d5f0960a5aa.png)

**Comment by grahamperrin** [comment]
… with Waterfox primarily using code from Firefox; can you use mozregression?

**Comment by tcreek** [comment]
Yeah, that is what I tried. I attempted a bisection of version 55 and 56. It kept bringing up version 56

**Comment by grahamperrin** [comment]
> 55 and 56. 

You'll probably find the bug reproducible with Firefox 56.0.2 (yes?) so instead, try a higher range.
