### ISSUE TITLE
Video streaming services stoppend working overnight

### ISSUE THREAD

**Issue by Jaap12345** [BrowserWorks/waterfox#1097]
Two (netflixlike) video streaming sites stopped working last night: https://www.videoland.com and https://www.npostart.nl

I tried them in Firefox and they also didn't work there at first.
But when I updated the OpenH264-videocodec plugin and the Widevine Content Decryption Module they worked again.

I guess an external video streaming library or  content decryption library (google?) that is been used by both sites has been updated last night at is not compatible anymore with one of those 2 plugins.
![waterfox](https://user-images.githubusercontent.com/47142342/63005425-c90ff880-be7c-11e9-84cd-ec2a85f6dcee.png)

**Comment by MrAlex94** [comment]
Yep looks like there’s a new CDM module but Google keep changing the API
and it’s not easy keeping track, Mozilla have a whole team dedicated to it!

I’m doing my best to support CDM10 so it should last for a couple of years.
Won’t be quick though.

**Comment by MrAlex94** [comment]
Whew, https://github.com/MrAlex94/Waterfox/commit/b1e0f2a7b186f1dc8a9091719affb7c6de68f624 marks the final commit for CDM10 support! And also fixed some memory leaks along the way. Not looking forward to anything like that again any time soon 🥵
