### ISSUE TITLE
Alternate source for Android APK 

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#1099]
Just wondering if there is an alternate source for the Android APK file since the play store listing is gone

**Comment by DI555** [comment]
I've asking to put all builds (include all .apk) here on repo releases, on github!

@MrAlex94 , please, imo here on github it's the best place!
And F-droid's plans will wait!

**Comment by tcreek** [comment]
Forget F-Droid. They have gone full blown SJW with censorship.

https://f-droid.org/en/2019/07/16/statement.html

**Comment by hawkeye116477** [comment]
@MrAlex94 Where are you?
