### ISSUE TITLE
Please compile for ARM7, ARM64 isn't as common as you think.

### ISSUE THREAD

**Issue by Ph0rkoz** [BrowserWorks/waterfox#1100]
So on PCs its not 2003 anymore and 90% of CPUs have one form of 64 bit instructions or another. On android, that is not the case and may people have 32bit OSs or 32 bit only CPUs. 

The party only got started in 2016 and most other apps are still arm32 compatible for this reason. Furthermore, the benefits to arm64 are rather limited as many devices aren't equipped with amounts of memory that require 64 bit addressing.

Please consider even posting an APK of the alpha, it shouldn't require many if any changes on your part while someone like me downloading many gb of data and setting up a toolchain would take a considerable amount of effort and time. We don't all update our phones every year.

**Comment by mikeloeven** [comment]
I'm still using an S5 here dropping 32bit support would rob me of the only android browser i have found with good addon support

**Comment by LeeBinder** [comment]
ditto

**Comment by Ibuprophen** [comment]
I agree & support this. 

This topic is actually located on the https://github.com/MrAlex94/Waterfox/issues/730 issue that I had submitted a while ago. 

Let's keep our fingers crossed! :-) 


~Ibuprophen
