### ISSUE TITLE
linux/56.2.12 ... bookmarks and history system will not be functional

### ISSUE THREAD

**Issue by linuxgirl22** [BrowserWorks/waterfox#1102]
Just setting up Waterfox on laptop, arch (beginner), and it looks as if 56.2.12 has turned into alpha version? Big red error message saying "bookmarks and history system will not be functional". I'd thought 56.2.12 was going to remain, so there could be a choice between running it or the alpha version? Or is it something else? Had copied over profile folder as normally do. Can't find anything on Reddit etc about this.

**Comment by hawkeye116477** [comment]
@linuxgirl22 Read https://support.mozilla.org/en-US/kb/fix-bookmarks-and-history-will-not-be-functional

**Comment by linuxgirl22** [comment]
Hi and thanks for responding. I'd followed that link when first booting into Waterfox, and it's more that I'm concerned that 56.2.12 isn't staying non-alpha. Very large amount of bookmarks etc, as most people probably have too, and not keen to spend hours recreating everything, eek. There was no message on Reddit or anywhere saying that 56.2.12 would change to alpha, and I can't find any posts about this issue elsewhere, so it was a big surprise to see the message. Will read through the link again, and hope there's a better solution than creating a new profile. 

EDIT: have read further, and tried to bring in a clean html version of bookmarks ... nothing appears, and copy/pasting hundreds of links manually doesn't feel like a good option. I never sync/sign in, ffor privacy reasons, so it's just a raw bookmarks upload. Libappimage broken again, so can't load up an older appimage on the laptop, so unfortunately I'll need to look for another browser.

**Comment by grahamperrin** [comment]
56.2.12 is a normal release of Waterfox Classic, not alpha.

If aiming to start Waterfox Classic leads to a start of alpha e.g. 68.something – and if you had (previously) aimed to install alpha alongside Classic: 

- check that installation of the alpha has not overwritten Waterfox Classic. 

Re: https://www.reddit.com/comments/cm7g9g/-/ew0g51i/ there _is_ (by default) the potential to overwrite on Windows, I don't know whether there's equal potential on Linux.

**Comment by grahamperrin** [comment]
> copied over profile folder

From what?

**Comment by linuxgirl22** [comment]
Hello and thanks for responses. Sorry, I should have explained better ... new laptop, with no previous browser install, and I'd installed the AUR version (waterfox-kde ... 56.2.12-1). I'd copied profile folder over from external drive. 

![wfox opened](https://user-images.githubusercontent.com/35760727/63306438-6dad9280-c2e2-11e9-9089-8aa7db0f096c.png)

**Comment by linuxgirl22** [comment]
Just to confirm the same happens with waterfox-bin 56.2.12-1 (AUR). Trying to run a previous appimage then results in the same.

**Comment by grahamperrin** [comment]
Thanks, 

> … copied profile folder over from external drive. …

From an installation of Waterfox Classic?

**Comment by linuxgirl22** [comment]
No, just the isolated .waterfox folder, copied from Home, which I back up on an external. After installing Waterfox, I overwrite the computer's .waterfox with my backed up one. I've never used alpha; solely the Classic version. Used Waterfox for a long time, and always backed up and restored in this way, which was working really well ... keeping bookmarks, add-ons, settings, etc.

**Comment by grahamperrin** [comment]
I guess, it's the type of thing that might happen if one or both of the databases was backed up whilst in an inconsistent state (with the effect of the state not apparent at the time). 

Try: 

1. about:support
2. Places database
3. verify integrity

**Comment by linuxgirl22** [comment]
Sorry, but I don't understand the advice pointers. 
I've now made sure of no profile folder being in Home, then run the appimage ... which opened without the red bar ... then, when adding my backed up profile to Home, the red bar shows again on opening Waterfox, so it must be something to do with the new laptop/usb and corruption of the profile.  
Have been able to bring in the html backup, which isn't loading toolbar bookmarks onto the bookmark bar, but at least they're accessible to be manually added, which is good news. :-)

**Comment by grahamperrin** [comment]
`about:support` is the address of the **Troubleshooting Information** page, **Verify Integrity** is a button on the page: 

![image](https://user-images.githubusercontent.com/192271/63406859-fad81080-c3e2-11e9-938c-ef88402a3010.png)

**Comment by linuxgirl22** [comment]
Thanks :-)
