### ISSUE TITLE
Error on building for Linux

### ISSUE THREAD

**Issue by hawkeye116477** [BrowserWorks/waterfox#1103]
@MrAlex94 When I building from 56.2.13 tag on Linux I got `/home/abuild/rpmbuild/BUILD/waterfox-56.2.13/ipc/chromium/src/base/process_util_linux.cc:172:33: error: use of undeclared identifier 'privs'`

Problem is here => `https://github.com/MrAlex94/Waterfox/commit/5b5fab3055a206a608dfa3f05956478d0e090031`

Looking at bugzilla and hg mozilla it seems that you removed too much.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/commit/5b5fab3055a206a608dfa3f05956478d0e090031 (committed 2019-08-16)

**Comment by Polynomial-C** [comment]
Same here on Gentoo Linux:
```
/var/tmp/portage/www-client/waterfox-56.2.13/work/Waterfox-56.2.13/ipc/chromium/src/base/process_util_linux.cc: In function 'bool base::LaunchApp(const std::vector<std::__cxx11::basic_string<char> >&, const file_handle_mapping_vector&, c
onst environment_map&, bool, base::ProcessHandle*)':
/var/tmp/portage/www-client/waterfox-56.2.13/work/Waterfox-56.2.13/ipc/chromium/src/base/process_util_linux.cc:172:33: error: 'privs' was not declared in this scope
     SetCurrentProcessPrivileges(privs);
                                 ^~~~~
make[4]: *** [/var/tmp/portage/www-client/waterfox-56.2.13/work/Waterfox-56.2.13/config/rules.mk:1063: process_util_linux.o] Error 1
```

**Comment by hawkeye116477** [comment]
Looking at `https://hg.mozilla.org/mozilla-central/log/f33ef94ef46cf5294152b98a00220568fa6ed4bc/ipc/chromium/src/base/process_util_linux.cc` and changes which Alex made, I guess that he tried to add changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1401790 and https://bugzilla.mozilla.org/show_bug.cgi?id=1316153, but something messed. I tried to revert https://github.com/MrAlex94/Waterfox/commit/5b5fab3055a206a608dfa3f05956478d0e090031 and then manually applied changes from both Bugs and seems that build was success.

**Comment by PhantomX** [comment]
This fixed for me, but I don't know if it will cause any problems later :

```
diff --git a/ipc/chromium/src/base/process_util_linux.cc b/ipc/chromium/src/base/process_util_linux.cc
index f8cfb32..5501747 100644
--- a/ipc/chromium/src/base/process_util_linux.cc
+++ b/ipc/chromium/src/base/process_util_linux.cc
@@ -169,8 +169,6 @@ bool LaunchApp(const std::vector<std::string>& argv,
       argv_cstr[i] = const_cast<char*>(argv[i].c_str());
     argv_cstr[argv.size()] = NULL;
 
-    SetCurrentProcessPrivileges(privs);
-
     execve(argv_cstr[0], argv_cstr.get(), envp);
     // if we get here, we're in serious trouble and should complain loudly
     // NOTE: This is async signal unsafe; it could deadlock instead.  (But
-- 
```

**Comment by grahamperrin** [comment]
about:buildconfig for successful build 20190819233138

### Target 

`x86_64-pc-linux-gnu`

### Build tools

`/usr/bin/clang-3.9 -std=gnu99`   3.9.1   `-Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wclass-varargs -Wloop-analysis -Wstring-conversion -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wformat -Wno-gnu-zero-variadic-macro-arguments -Wformat-security -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -pipe`
 
`/usr/bin/clang++-3.9 -std=gnu++11`   3.9.1   `-Qunused-arguments -Qunused-arguments -Wall -Wc++11-compat -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings -Wno-invalid-offsetof -Wclass-varargs -Wloop-analysis -Wc++11-compat-pedantic -Wc++14-compat -Wc++14-compat-pedantic -Wc++1z-compat -Wcomma -Wimplicit-fallthrough -Wstring-conversion -Wno-inline-new-delete -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wformat -Wno-gnu-zero-variadic-macro-arguments -Wformat-security -Wno-unknown-warning-option -Wno-return-type-c-linkage -fno-exceptions -fno-strict-aliasing -static-libstdc++ -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -pthread -pipe -g -O2 -msse3 -march=x86-64 -mtune=generic -w -fomit-frame-pointer`

### Configure options

`--target=x86_64-pc-linux-gnu --enable-application=browser --enable-update-channel=release --disable-tests CC=clang-3.9 CXX=clang++-3.9 --enable-release --enable-stylo=build --enable-rust-simd MAKE=/usr/bin/make --enable-alsa --disable-crashreporter --disable-maintenance-service '--enable-optimize=-O2 -msse3 -march=x86-64 -mtune=generic -w' --enable-pulseaudio --disable-signmar --enable-updater --disable-verify-mar --with-app-basename=Waterfox --with-app-name=waterfox --with-branding=browser/branding/unofficial --with-distribution-id=org.waterfoxproject`

**Comment by hawkeye116477** [comment]
@grahamperrin It doesn't help, config options are good, but @MrAlex94 send broken source files to GitHub, he had good proper files locally, so he built successfully as 2 months ago (https://github.com/MrAlex94/Waterfox/issues/1032).

As i told apparently he tried to add changes from `https://bugzilla.mozilla.org/show_bug.cgi?id=1401790`, `https://bugzilla.mozilla.org/show_bug.cgi?id=1316153` and maybe also `https://bugzilla.mozilla.org/show_bug.cgi?id=1259852`, but looks like incomplete (especially not all changes from third bug).

**Comment by MrAlex94** [comment]
Apologies - https://github.com/MrAlex94/Waterfox/commit/e19194a11adea6f9892969eb98a750476a6ce044

**Comment by hawkeye116477** [comment]
Ok, now can build, but I see here https://github.com/MrAlex94/Waterfox/commit/5b5fab3055a206a608dfa3f05956478d0e090031#diff-a704bf7f41113bff9ab1a01c5a3644cbR157, that you started adding something from https://hg.mozilla.org/mozilla-central/rev/0567ed7f6074#l1.32 and looks like not all changes added from hg.mozilla.
Missing including header file => `#include "mozilla/UniquePtr.h"` and some other changes.

Also from this partially => `https://bugzilla.mozilla.org/show_bug.cgi?id=1316153`.
