### ISSUE TITLE
Widevine Causing Kernel Panic in OS x Lion 10.7.5

### ISSUE THREAD

**Issue by pjpreilly** [BrowserWorks/waterfox#1105]
Kernel panics with WF 56.2.13 with new Widevine plugin active on OS x Lion 10.7.5

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by grahamperrin** [comment]
When exactly does the panic occur?

If `about:addons` is the sole tab (no other window or tab), then does the panic occur when you aim to switch the plug-in from _Never_ to _Always_?

[Troubleshooting: getting more from kernel panics with keepsyms (address to symbol translation) | MacRumors Forums](https://forums.macrumors.com/threads/troubleshooting-getting-more-from-kernel-panics-with-keepsyms-address-to-symbol-translation.1834117/)

**Comment by pjpreilly** [comment]
If about:addons is the sole tab (no other window or tab), then does the panic occur when you aim to switch the plug-in from Never to Always? 

NO, but if you enable on **[THIS](https://6abc.com/girl-14-in-custody-after-man-found-dead-inside-home/5680132/)** page it will.
or if you enable it THEN load the page it will too!

**Comment by grahamperrin** [comment]
Thanks. 

MacBook4,1 – yes? 

Which one of these? https://everymac.com/ultimate-mac-lookup/?search_keywords=MacBook4,1

Incidentally the main video at https://6abc.com/girl-14-in-custody-after-man-found-dead-inside-home/5680132/ does play on an operating system (to the right) that is **without** Widevine; no DRM: 

![2019-11-09 08:28:35](https://user-images.githubusercontent.com/192271/68525609-625b7900-02cb-11ea-937e-880b915bc1d0.png)

- Firefox 70.0.1 to the right
- the main video plays equally well in Waterfox Classic 2019.10 (20191103135811) on FreeBSD-CURRENT.

**Comment by pjpreilly** [comment]
4,1 both & 3,1 too, I'm aware of your other assertions.
