### ISSUE TITLE
Mention tips on GitHub doesn't work

### ISSUE THREAD

**Issue by hawkeye116477** [BrowserWorks/waterfox#1108]
When I want someone mention, then usually tips should be shown about who I want to mention. This works on Vivaldi and Firefox, but not on Waterfox 56. Can this be somehow fixed/implemented on Waterfox's side?
On console I have error `TypeError: customElements.upgrade is not a function`, it seems that disappears when I set `dom.webcomponents.customelements.enabled` to `true`, but mention tips still doesn't work.

**Comment by laniakea64** [comment]
Does it help to use a Firefox 60 user-agent for Github? -
`Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0`

**Comment by hawkeye116477** [comment]
@laniakea64 No.

**Comment by grahamperrin** [comment]
Did this only recently stop working with Waterfox Classic?

**Comment by hawkeye116477** [comment]
@grahamperrin No, as I remember this worked sometime ago on Waterfox, but I don't remember when it was.

**Comment by Ibuprophen** [comment]
I would like to confirm what @hawkeye116477 had reported regarding Waterfox Beta v56.1.0 (ARM). 

I actually don't recall this ever working. My own workaround was to use the "Request Desktop Site" setting. 

I just toggled the `dom.webcomponents.customelements.enabled` to `true` and it began working. 

TBH... I just noticed this reported issue and was happy to get it working again using that suggestion... LOL! :-) 

EDIT: I've been using the `Mozilla/5.0 (Android 8.0.0; Mobile; rv:66.0.5) Gecko/66.0.5 Firefox/66.0.5`agent for about a month or so that didn't affect this issue but, did improve my experience on many other websites (personally). 


~Ibuprophen

**Comment by hawkeye116477** [comment]
I should probably tell if it's on PC or smartphone, but that 56 version for Android isn't even on Google Play now, so I didn't take it into consideration. Anyway I talked about stable version for PC.

**Comment by Ibuprophen** [comment]
Yes, the Beta version is still available. I can see it in the Play Store as seen by the attached screenshot I had just made. 

[Screenshot_20190823-182844](https://user-images.githubusercontent.com/18060271/63627191-70570300-c5d4-11e9-97db-06c0b61286c9.png)


~Ibuprophen

**Comment by grahamperrin** [comment]
> see it in the Play Store 

I, too, saw an _installed_ version. 

On my Android I had (2018-08-18) beta version 60.1.0 but as expected – #1085 – this morning after I uninstalled, I could not find any version to reinstall. 

> Mention tips

Maybe more than that, at least for users of Refined GitHub 19.1.31.1822. I have lost the ability to automatically preview the title of an issue (a tip) whilst writing. This feels like a very recent loss – like, within the past few days – so re: https://redd.it/ctttof I guess that it coincided with the reported end of support for legacy markup.

**Comment by grahamperrin** [comment]
With `dom.webcomponents.customelements.enabled` `true` I lose the ability to paste an image whilst writing. 

Waterfox Classic 56.2.13 (20190822231313) on FreeBSD-CURRENT.

**Comment by hawkeye116477** [comment]
`With dom.webcomponents.customelements.enabled true I lose the ability to paste an image whilst writing.`
I wrote previously that unfortunately doesn't help in that case, maybe on Android that have positive effect, but not on PC (Linux). Only error message disappears.

**Comment by hawkeye116477** [comment]
Possibly related => https://bugzilla.mozilla.org/show_bug.cgi?id=1443722.
Appears that this is not implemented on Waterfox 56.2.14.

**Comment by Ibuprophen** [comment]
Just curious... 

If changing the `dom.webcomponents.customelements.enabled` to `true` doesn't work out... 

Does changing the `dom.webcomponents.enabled` to `true` have the same undesirable affect as well? 

Thanks a Bunch! :-) 


~Ibuprophen

**Comment by hawkeye116477** [comment]
@Ibuprophen Yes, same negative effect.
As I wrote, this is rather job for @MrAlex94 to implement this :smile:

**Comment by Ibuprophen** [comment]
I understand now... Thanks for the clarification! :-) 


~Ibuprophen

**Comment by IzzySoft** [comment]
Just to mention: this did work for me until about 2 weeks ago. Stopped working around the time I updated to 56.2.13 – both on Linux and Windows (and stays broken with 56.2.14). Playing with the UA didn't fix it here either.

Another strange thing starting at the same time, but only on Linux: in the navigation bar on top, the "More" menu stayed open right from the time of loading the page. Fixing that one was rather easy via a userstyle. In case somebody else is affected:

```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("github.com") {
  .btn-link.reponav-item:hover + .dropdown-menu-content.js-menu-content, .dropdown-menu-content.js-menu-content:hover { display:block !important }
  .dropdown-menu-content.js-menu-content { display:none; }
}
```

**Comment by grahamperrin** [comment]
Thanks, 

> Another strange thing

Cross reference: 

- [Waterfox Classic: Refined GitHub: More menu](https://www.reddit.com/r/waterfox/comments/ctttof/waterfox_classic_refined_github_more_menu/)

**Comment by IzzySoft** [comment]
Uh, yes, that – and thanks for spreading the word :smile:

Now we just need someone to come up with a userscript. Though I'm afraid that is not that easy. OTOH I wouldn't wonder if that could be done by comparing page source in WF with the same from a browser where it works. Wouldn't be the first time Github omits script entries based on browser, so maybe we'd just need to insert that back.

Anyone tried with a Chrome-based UA string, for example? Though I'm not sure what that might break then…

**Comment by grahamperrin** [comment]
> need someone to come up with a userscript. 

For @… completion, yes?

@github | cc @ACyphus re: https://github.com/MrAlex94/Waterfox/pull/784#issuecomment-439939670 in November 2018, GitHub granted a UA-oriented whitelisting, for Waterfox to continue working normally. Thanks again for that. 

----

Now – for this recent _mentions_ issue – is another whitelisting possible/appropriate?

TIA for any advice

**Comment by hawkeye116477** [comment]
`Now – for this recent mentions issue – is another whitelisting possible/appropriate?`
I guess that's rather not possible. They'll rather need to use som polyfill to support Waterfox or that's rather job for Alex.

**Comment by IzzySoft** [comment]
> For @… completion, yes?

Yes. That stopped working for me at about the time I updated to 56.2.13. Which includes the "tips".

And aren't those @… thingies called "mentions"? I thought we're talking about the very same thing: You start typing the "@", then usually a "tip" opens listing participants in the thread (plus the owner of the repo, if I got that correctly).

Thanks for the link – it seems that yes, another white-listing might be required (Github staff should be able to tell).

**Comment by grahamperrin** [comment]
> aren't those @… thingies called "mentions"?

I do think so. 

(I threw the phrase _@… completion_ into the mix partly for search engine purposes, because other people might use words such as complete or autocomplete or auto-completion.)

**Comment by grahamperrin** [comment]
@hawkeye116477 re: your other comment yeah, I, too, have doubts. 

(Re: polyfills, I saw your recent `https://github.com/collinbarrett/FilterLists/issues/938` – thanks.)

**Comment by hawkeye116477** [comment]
Seems that GitHub/Microsoft fixed this.

**Comment by IzzySoft** [comment]
Confirmed: It magically started working again yesterday. As for the "More" button, that was only half fixed: the drop-down now is completely hidden and doesn't open even on click. My UserStyle still fixes that.

**Comment by grahamperrin** [comment]
> … lost the ability to automatically preview the title of an issue (a tip) whilst writing. …

This, too, appears to be fixed: 

![image](https://user-images.githubusercontent.com/192271/64904172-f9d29000-d6bd-11e9-90c9-f63fc18ecec8.png)

Thanks @github

----

> … the "More" button, …

(Not a feature of GitHub.)

**Comment by IzzySoft** [comment]
Not? Then who places that there?

![Selection_119](https://user-images.githubusercontent.com/6781438/64910746-421f9b80-d71a-11e9-9019-13bc77bb8c55.png)

Looks like I'm using too many UserScripts and lost track then…

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/1108#issuecomment-529042837

> … Refined GitHub …

**Comment by IzzySoft** [comment]
Oh. Good guess I guess, I'm using that… Thanks! And uh, you've linked me that before and I didn't get *that* part, shame on me…

**Comment by grahamperrin** [comment]
NP :)
