### ISSUE TITLE
blank page on facebook 

### ISSUE THREAD

**Issue by jackpallet** [BrowserWorks/waterfox#1110]
Hi, when I try to connnect on facebook.com I obtain only a blank page, restart waterfox in safe mode doesn't help

 - OS: Windows 7 ultimate Service pack 1
 - Waterfox Version 56.2.13 (64 bit)

**Comment by grahamperrin** [comment]
Not reproducible here with 56.2.13 on Windows 10. 

Can you reproduce the issue with a new profile? 

- about:profiles

**Comment by jackpallet** [comment]
Also with other profiles I had the same error on waterfox while no problems on firefox. I had changed anything but today facebook on waterfox works again. Really strange. However I close the issue
