### ISSUE TITLE
New Hoxx VPN extension doesn't work

### ISSUE THREAD

**Issue by jackpallet** [BrowserWorks/waterfox#1113]
The new version of this useful extension doesn't work on waterfox. It's possible install the extension but then is unable to connect to any server

Extension: Hoxx VPN Proxy 3.7.0 (older vesion are been deactivated from Hoxx)
OS: Windows 7 ultimate Service pack 1
 Waterfox Version: 56.2.13 (64 bit)

Of course the same extenson on firefox works good

![Nuova immagine bitmap](https://user-images.githubusercontent.com/46008931/63795051-76662000-c903-11e9-9b98-5bf96a4e589d.jpg)

**Comment by grahamperrin** [comment]
Have you sought advice from the developers of the extension?

**Comment by jackpallet** [comment]
I have sent a support request to Hoxx. I'm waiting their reply

**Comment by jackpallet** [comment]
No hopes from Hoxx support. Their reply:

`Waterfox is based on old FF version which we do not support anymore... this is probably why...`

**Comment by SenpaiSharp** [comment]
Doubtful that much can be done. Does it work on the Alpha?

The advice to use the desktop client seems like your best bet and probably what I would err on the side of anyhow, unless your desktop also does not support it or you're trying to route specific traffic through a specific instance of Waterfox.

**Comment by jackpallet** [comment]
Thanks for you reply but I' don't want use desktop client. I'll use some other similar extension until the problem will not been solved. Unfortunately, for me Hoxx VPN was the best
