### ISSUE TITLE
56.2.{12,13} on OSX 10.8, crash predictably. Issue appeared after upgrading from 56.2.11

### ISSUE THREAD

**Issue by rorya** [BrowserWorks/waterfox#1114]
Open WF 56.2.{12,13} on OSX 10.8.5, open Preferences (Command-,) (also seems to happen when enough windows are open and you attempt to open a new Private Window.

Note this happened right after upgrading from 56.2.10. So something in between 56.2.10 and 56.2.12 has changed, which trigger this class of app crashes.

Only workaround seems to be to revert to 56.2.11.

For example, a crash when trying to open Preferences in one profile I have for this browser:

waterfox-bin[69776:f07] -[NSImage drawInRect:]: unrecognized selector sent to instance 0x17b189d40
waterfox-bin[69776:f07] Mozilla has caught an Obj-C exception [NSInvalidArgumentException: -[NSImage drawInRect:]: unrecognized selector sent to instance 0x17b189d40]

![image](https://user-images.githubusercontent.com/96693/63810202-2f236380-c8f2-11e9-8c73-4fcbe34528a1.png)

I've noticed, it seems all these 56.2.{12,13}/OSX_10.8.5 crashes seem to have the "unrecognized selector sent to instance..." errors in common.

2019-08-29 UPDATE: downgraded to 56.2.11 and noticed it disappears with that release. So, that means this particular class of issues are with v56.2.{12,13}. I've edited this ticket to reference the problem starting with 56.2.12, not 56.2.13, though 56.2.13 exhibits the same problem.

**Comment by grahamperrin** [comment]
Cross reference [Waterfox crashes when downloading anything](https://www.reddit.com/r/waterfox/comments/cvq6yw/waterfox_crashes_when_downloading_anything/)

> … 10.8.5 …

– in particular, https://www.reddit.com/comments/cvq6yw/-/eyn3vkg/ with directions to disk images for outdated versions 56.2.11, 56.2.12 and 56.2.13 of Waterfox Classic.

**Comment by pjpreilly** [comment]
Any chance of an interim build with older x-code to test issues with OS x 10.7 & 10.8?

> Cross reference [Waterfox crashes when downloading anything](https://www.reddit.com/r/waterfox/comments/cvq6yw/waterfox_crashes_when_downloading_anything/)
> 
> > … 10.8.5 …

**Comment by grahamperrin** [comment]
https://redd.it/cz9zcy

>> … built with OS X 10.11 SDK once again, which should alleviate crashes. …

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by pjpreilly** [comment]
OS x Lion install link has been provided to ensure Waterfox Classic functionality on depreciated Mac os's 10.7.5 as well as 10.8.5.

**Comment by grahamperrin** [comment]
@rorya with **build `20191022184353`** of Waterfox Classic 2019.10 for Mac OS X, please follow the steps below. 

(Build `20191015152520` of version 2019.10 must not be used.)

The first step is an address:

1. about:config?filter=browser.tabs.remote.force-disable
2. add (or set) a boolean preference
3. `browser.tabs.remote.force-disable`
4. `true`
5. quit.

Is the next run of Waterfox Classic 2019.10 (20191022184353) free from the issue?

**Comment by rorya** [comment]
FYI, @grahamperrin I'm now using the latest WF-Classic as of this writing, v2020.03.1. First, on this version at least, there is no config knob named browser.tabs.remote.force-disable in about:config. Also, I'm still using WF-Classic on OSX 10.8.5,

Major, consistent (since the "Classic" fork, basically) issues noticed:
- I think ever since the rename to Waterfox Classic, this clash-on-download has existed. So I have to make sure to avoid clicking any links that download anything, as it's leads to a sure crash. I believe it's still the same "unrecognized selector sent to instance" error is in prior, recent releases.
- Attempting to open Preferences, leads to another consistent crash. It also is due to the NSInvalidArgumentException: [NSImage drawInRect:] error, like when you try to download something. In the rare instance it doesn't crash when the download dialog pops up, it does when you dismiss it by clicking 'cancel'.

**Comment by MrAlex94** [comment]
This should be better supported now: [Download](https://cdn.waterfox.net/releases/osx64/installer/Waterfox%20Classic%202020.07.2%20Setup.dmg). Please re-open if still having issues.
