### ISSUE TITLE
68.0a2

### ISSUE THREAD

**Issue by tycrek** [BrowserWorks/waterfox#1116]
**Describe the bug**
Nothing in Preferences. Can see 4 tabs: General, Home, Search, Privacy & Security. None of them have any options.

**To Reproduce**
1. Click hamburger menu
2. Click Preferences
3. Select any of the 4 tabs

**Expected behavior**
The tabs should list their respective options instead of being empty.

**Screenshots**

**Desktop (please complete the following information):**
 - Manjaro Linux x64
 - Kernel 4.19.66-1-MANJARO

**Comment by grahamperrin** [comment]
What build ID? 

- about:support

**Comment by laniakea64** [comment]
https://github.com/MrAlex94/Waterfox/pull/1109

**Comment by grahamperrin** [comment]
@tycrek you should find that this issue is no longer reproducible with Waterfox 68.0b1. If so, you can close this issue – thanks.
