### ISSUE TITLE
v68+ Consider Removing Entirely or Otherwise Adding Options to Truly Disable The "Content Blocking" Stuff from Mozilla

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#1120]
In reality these lists from disconnect.me leave much to be desired and will waste resources if you're already running something better like uBlock origin and/or uMatrix.

Additionally, with Mozilla's partners, including the Soros open society foundation, I'm concerned these lists will be used someday to block sites that Mozilla or partners of Mozilla don't like for political or ideological purposes.

While we're at it, we should consider doing the same with the safebrowsing stuff. Right now, Ungoogled-Chromium makes 0 unsolicited requests on start, while Waterfox and Firefox both hit mozilla.org in various ways, and some google domains, and now, these disconnect.me lists also...not to mention the new DNS over https stuff that...I think is still not defaulted to on, thankfully.

I'm not trying to push anything on anybody, but I see these supposed features as being similar to pocket...

I'm already using ghacksuserjs + customizations to kill this for myself, but I think it should all be taken into consideration.

**Comment by laniakea64** [comment]
@ilikenwf I mostly agree with your rationale here, but don't we already have these options?  `about:preferences` > Privacy & Security > Content Blocking, set to "Custom" and un-check everything (except possibly cookies, which can be set to an option that doesn't involve a content blocking list).

> While we're at it, we should consider doing the same with the safebrowsing stuff. 

Again, doesn't this option already exist?

**Comment by ilikenwf** [comment]
Last I checked, doing that, the browser was still updating the lists and
possibly enabling them.

See

extensions.blocklist.enabled
extensions.blocklist.detailsURL
extensions.blocklist.itemURL
extensions.blocklist.url

I go quite above and beyond on the safebrowsing stuff too as waterfox
still seems to make unsolicited requests to mozilla and google servers,
last I checked, with a new profile. This is unacceptable IMO.

**Comment by ilikenwf** [comment]
Here's a fresh profile, just via about:networking...the captive portal detection is another thing I take issue with having enabled by default...likewise, why the heck are we hitting bing?

![image](https://user-images.githubusercontent.com/414778/64464439-703c2480-d0f7-11e9-8793-e31ff0c10dc6.png)

**Comment by ilikenwf** [comment]
...the only valid request I see there is to waterfox.net - I think the rest are inappropriate, except maybe for digicert, but that would not even be necesary if we weren't contacting the mozilla mothership...including their location services.

**Comment by laniakea64** [comment]
> extensions.blocklist.enabled
extensions.blocklist.detailsURL
extensions.blocklist.itemURL
extensions.blocklist.url

This is the blocklist of malicious addons/extensions/plugins.  It has nothing to do with content blocking or Safe Browsing.

> why the heck are we hitting bing?

Bing is the default search engine of Waterfox.  Search suggestions in address bar are enabled by default, that connection would have occurred as you were typing `about:networking` into the address bar.

(Before I reply to the other parts of your comments, I need to find the time to double check what unsolicited connections Waterfox makes with my main profile and if there are any, try to figure out what they're doing.)

**Comment by ilikenwf** [comment]
Sorry on pasting the wrong prefs...I have them cleared out but don't
remember which ones are the ones...

**Comment by grahamperrin** [comment]
> the blocklist of malicious addons/extensions/plugins. 

:+1:  

– and should be enabled by default.

**Comment by ilikenwf** [comment]
I can rename the issue to imply more that we need to audit the out of the box startup connections.

I still take issue with these lists, the location services call, and the captive portal call, along with the safebrowsing list updates if/when they get updated.

**Comment by grahamperrin** [comment]
> [captive portal detection](https://github.com/MrAlex94/Waterfox/issues/1120#issuecomment-529037268)

Back to #681 please so that discussions are not too scattered. 

Also more generally [Connections to a lot of servers · Issue #270 …](https://github.com/MrAlex94/Waterfox/issues/270)

**Comment by grahamperrin** [comment]
> consider doing the same with the safebrowsing stuff.

-1 to removal. #452
