### ISSUE TITLE
Waterfox 56.2.14 crashes immediately on launch @os x 10.7.5

### ISSUE THREAD

**Issue by efficientbaxter** [BrowserWorks/waterfox#1122]
with Segmentation fault: 11.

**Comment by efficientbaxter** [comment]
workaround: downgrade to version 56.2.13

**Comment by grahamperrin** [comment]
Cross reference (with input from Alex): 

- [56.2.14 OS x … CRASH ON LAUNCH. : waterfox](https://www.reddit.com/r/waterfox/comments/czdi2h/56214_os_x_lion_crash_on_launch/)

Meta, tracking: #538

**Comment by rorya** [comment]
Also crashes on launch on 10.8.5. not a segmentation fault. Unfortunately I don't have the backtrace available right now, seems I replaced my clipboard contents, which had a screenshot of it. So, 56.2.11 remains the highest stable version.

**Comment by grahamperrin** [comment]
> … don't have the backtrace …

[macos - Where can I find my crash logs? - Ask Different](https://apple.stackexchange.com/questions/26480/where-can-i-find-my-crash-logs)

– a few answers, they're old but from what I recall of Mac OS X pre-Yosemite, most advice there should be good for Lion and Mountain Lion. 

Backtrace not available in the Lion case that opened with https://redd.it/czdi2h

With or without a backtrace, use of **dtruss** might be revealing. It's [no longer available](https://svnweb.freebsd.org/base?view=revision&revision=300226) on FreeBSD so I can't offer a glimpse of what to expect with Waterfox, but here's a (Mac OS X 10.6) copy of the manual page: 

- http://www.manpagez.com/man/1/dtruss/

dtruss is number 5 at [Brendan's blog » Top 10 DTrace scripts for Mac OS X](http://dtrace.org/blogs/brendan/2011/10/10/top-10-dtrace-scripts-for-mac-os-x/) ([highlights](https://diigo.com/0xcp0)). Hint: 

> … The output (of `dtruss`) will be many pages, …

– so I should hesitate before pasting huge chunks of output under this issue. 

If the (long) tail of the output is potentially revealing, maybe paste it to https://pastebin.com/ and then link from here to ask whether it brings things closer to an explanation. 

HTH

**Comment by grahamperrin** [comment]
https://twitter.com/waterfoxproject/status/1172623430237196291 | https://redd.it/d3vy5w

> I am aware of small but pertinent issues in the latest Waterfox in regards to … some crashes on older systems. Investigating and will hopefully have a fix soon.

**Comment by grahamperrin** [comment]
> 56.2.13

Thanks, and for anyone who can't find the download link: 

[Waterfox download archive](https://github.com/MrAlex94/Waterfox/issues/418) … ▶ [Moved to](https://github.com/MrAlex94/Waterfox/issues/418#issuecomment-401091893) … ▶ https://github.com/grahamperrin/Waterfox/wiki ▶ Archive of change logs, announcements and downloads … 

- [56.2.11](https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#56211)
- [56.2.12](https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#56212)
- [56.2.13](https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#56213)

**Comment by grahamperrin** [comment]
@efficientbaxter please open the disk image at https://www.waterfox.net/releases/ and overwrite your outdated Waterfox Classic application with Waterfox Classic 2019.10. 

If Waterfox Classic 2019.10 does not crash at launch time, you can close this issue. Thanks.

**Comment by efficientbaxter** [comment]
👍 Yeah, WORKS!

Thank you very much!
