### ISSUE TITLE
macOS: WF 56.2.14 tab crashes when saving as PDF and volume has space in the name

### ISSUE THREAD

**Issue by ElhemEnohpi** [BrowserWorks/waterfox#1123]
**Describe the bug**
On macOS (tested on Sierra 10.12.6), beginning with the latest Waterfox 56.2.14, saving a web page as a PDF via  File>Print causes the tab to crash if the destination volume has a space in its name.

**To Reproduce**
1. Go to any web page
2. Choose 'Print' from the 'File' menu, or press command-P
3. From the popup menu at the lower left, choose "Save as PDF"
4. Choose a folder on a volume that has a space in the volume name. It can be a hard drive, USB stick, or mounted DMG image.
5. Click 'Save'

**Expected behavior**
A PDF version of the web page is saved to the destination folder, just as it is in Waterfox 56.2.13.

**Actual behavior**
"Gah. Your tab just crashed." No PDF file is saved.

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - Version: Waterfox 56.2.14

**Comment by pjpreilly** [comment]
Same results on Mojave 10.14.x

**Comment by grahamperrin** [comment]
Meta, tracking: #538

**Comment by grahamperrin** [comment]
A potential workaround, from <https://www.reddit.com/comments/cz9zcy/-/f0p7tnr/>: 

>  "open in preview" first and "save" my opened page to PDF.

**Comment by grahamperrin** [comment]
Reproducible with 56.2.14 in safe mode?

- about:support

Reproducible in single-process mode?

- about:preferences#general

– be prepared for a possible crash of the entire application (not just one tab).

> **Expected behavior**
> 
> A PDF version of the web page is saved to the destination folder, just as it is in Waterfox 56.2.13.

https://github.com/MrAlex94/waterfox/compare/56.2.13...56.2.14

**Comment by ElhemEnohpi** [comment]
> A potential workaround, from https://www.reddit.com/comments/cz9zcy/-/f0p7tnr/:
>> "open in preview" first and "save" my opened page to PDF.

Thanks!
> Reproducible with 56.2.14 in safe mode?

Yes, tab crashes in safe mode.

> Reproducible in single-process mode?

No, saving succeeds with multiprocess unchecked.

**Comment by ElhemEnohpi** [comment]
Seems to be fixed in version 2019.10, thanks...

**Comment by ElhemEnohpi** [comment]
@MrAlex94 the same thing is happening again after updating from WF Classic 2020.03 to 2020.05 (could have started in 2020.04, not sure because I never got that version).

**Comment by pjpreilly** [comment]
> @MrAlex94 the same thing is happening again after updating from WF Classic 2020.03 to 2020.05 (could have started in 2020.04, not sure because I never got that version).

Use this:
https://github.com/CL-Jeremy/Waterfox/releases

**Comment by ElhemEnohpi** [comment]
Still present in 2020.06. Can this be re-opened?

@pjpreilly thanks - I think I'll stick with the official/latest release, but what is the difference with yours?

**Comment by pjpreilly** [comment]
@ElhemEnohpi  10.7.5 & 10.8.5 have issues launching WF Classic since 2020.4
