### ISSUE TITLE
68.0b1 (20190907162938) about:preferences broken on Windows

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1127]
#1109 seems to have made things good on Linux (thanks) however as noted at <https://redd.it/d15yea>, Saturday's unannounced 20190907162938 build seems to be broken on Windows: 

![image](https://user-images.githubusercontent.com/192271/64492430-a5698380-d26b-11e9-92f1-38827e3af8f4.png)

Meta, tracking: #538

**Comment by laniakea64** [comment]
When this issue occurs, any related messages in the Browser Console (Ctrl-Shift-J)?

**Comment by MrAlex94** [comment]
It was a pull issue, am fixing now.

**Comment by ghost** [comment]
@MrAlex94 
Does the next Waterfox update include a fix? This basically makes the browser "unusable".

Thank you and others for the hard work. WF is awesome.

**Comment by grahamperrin** [comment]
Fix confirmed, thanks. 

https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs%2C-announcements-and-downloads#680b1 updated. 

@Korsola https://www.waterfox.net/releases/ includes updated links.
