### ISSUE TITLE
68.0b1 incorrectly uses Firefox branding in about:debugging

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1129]
`about:debugging#/runtime/this-firefox` ("This Waterfox") uses a Firefox logo to represent "Waterfox Current (68.0b1)".  It should be a Waterfox logo.

**Comment by grahamperrin** [comment]
Reproducible with 2019.10?

**Comment by laniakea64** [comment]
> Reproducible with 2019.10?

2019.10 switched to using the "Firefox developer" logo.  Not totally sure what to think of that in light of e.g. https://github.com/MrAlex94/Waterfox/issues/485 , but since this logo seems to represent Waterfox more than it represents the devtools, I would still suggest changing it to a Waterfox logo.

Also, 2019.10 still uses a monochrome Firefox logo to represent "This Waterfox" in the `about:debugging` sidebar.
