### ISSUE TITLE
wrong version contained in download

### ISSUE THREAD

**Issue by kleytr6s** [BrowserWorks/waterfox#1132]
I downloaded the windows portable 56.2.14 version. But, an update for version 56.2.14 were sent. Most likely a previous version is contained within the windows portable download.

**Comment by grahamperrin** [comment]
Thanks, 

> **portable**

Cross reference https://www.reddit.com/comments/cz9zcy/-/ez07x64/

>> … After installing, it shows 56.2.12 (64-bit) in the About Waterfox windows. … 

Meta, tracking: #538

**Comment by 4evermaat** [comment]
ok.  Looks like this post is a little redundant:
https://www.reddit.com/r/waterfox/comments/d24rr5/windows_waterfox_56214_portable_shows_as_56212/

**Comment by grahamperrin** [comment]
More cross references: 

- https://redd.it/d24rr5
- https://redd.it/d4bkqm

From <https://www.reddit.com/comments/brjghh/-/f06rxd2/> re: Waterfox _Current_ portable: 

> For primary distributions i.e. those that are announced at https://www.waterfox.net/blog/ and linked from https://www.waterfox.net/releases/ – build priorities seem to be something like this: 
> 
> 1. Waterfox Classic for Windows
> 2. Waterfox Classic for Linux and macOS
> 3. Waterfox Classic portable for Windows
> 4. Waterfox Current for Windows
> 5. Waterfox Current for Linux and macOS
> 6. Waterfox for Android on Google Play Store. 
> 
> Beyond those: there are some community-built distributions. 

Re: #943 and [What is a portable app? | PortableApps.com](https://portableapps.com/about/what_is_a_portable_app) (as guidelines, not a strict definition) what would be required for a community build of Waterfox _Classic_ portable?

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/d4bkqm/-/f0dntk2/>:

> It was packed incorrectly. I will resolve that.
