### ISSUE TITLE
Some japanase and other languages characters not shown correctly

### ISSUE THREAD

**Issue by davidbepo** [BrowserWorks/waterfox#1133]
**Describe the bug**
some japanese or other non-latin characters are shown as rectangles with numbers inside

**To Reproduce**
in the linux version go for example here:
https://twitter.com/KOMACHI_ENSAKA

**Expected behavior**
characters are rendered normally

**Desktop (please complete the following information):**
 - OS: Manjaro linux
 - Version: latest but has been happening for a while

**Comment by grahamperrin** [comment]
> latest

Waterfox Classic 56.2.14 or Waterfox Current 68.0b1?

<strike>I suggest seeking advice from the Manjaro community, more generally you might find an explanation in other Linux areas. </strike>

Consider the presentation in these four browsers, on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/64646460-0da49a80-d40f-11e9-9d58-bbcfa74a7718.png)

Left to right: Chromium, Falkon, Firefox, Surf. 

If I recall correctly, this type of problem is resolved through installation of appropriate fonts but (for myself) I simply have not done so.

**Comment by davidbepo** [comment]
56.2.14
i dont think fonts are the issue here since chromium works, and copying the characters to other program also works
also this issue is a regression, but it has been happening for a wile

**Comment by davidbepo** [comment]
since you mentioned it i also tried waterfox 68 and it also works correctly

**Comment by grahamperrin** [comment]
OK, I ran Manjaro in a VirtualBox guest, now I see what you mean. Maybe. 

Is your view the same as this?

![image](https://user-images.githubusercontent.com/192271/64651227-e357da80-d418-11e9-8e5a-1130405611dd.png)

– fewer illegible characters than on FreeBSD but still, not correct …

**Comment by davidbepo** [comment]
yes, the same

**Comment by grahamperrin** [comment]
https://github.com/gorhill/uBlock#user-content-ublock-origin

– are Chinese (…) and Korean (…) affected as shown here? 

![image](https://user-images.githubusercontent.com/192271/64828822-efcb6700-d5c1-11e9-9c94-9634e5dcac81.png)

**Comment by hawkeye116477** [comment]
@davidbepo Is that fixed now?

**Comment by davidbepo** [comment]
yes, it can be closed now
