### ISSUE TITLE
Multiprocess + FlashGot = Double click on regaining focus

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#1136]
With _**FlashGot**_ extension installed and _**Multiprocess**_ enabled a single click is treated as double click when regaining focus.

To reproduce just click on other application or taskbar that Waterfox would lose focus and single click on Waterfox to have a double click effect. It was described [here](https://github.com/MrAlex94/Waterfox/issues/820).

While the extension is no loger maintained and there is no alternative for its functions it would be nice to have that fixed on Waterfox side.

**Comment by laniakea64** [comment]
Have you asked FlashGot forums about this? - https://forums.informaction.com/viewforum.php?f=2

**Comment by maxoku** [comment]
@laniakea64
Bug already was reported [here](https://forums.informaction.com/viewtopic.php?f=11&t=22397&sid=f6b4b95ed852d331e554159c7b17bde1) a long time ago and still no fix.
Last update of extension was almost 3 years ago.

**Comment by grahamperrin** [comment]
[e10s (multi-process) compatibility reports at addons.mozilla.org (AMO)](https://gist.github.com/grahamperrin/12e03fe3d305901c093cb68bce43fe92)

**Comment by maxoku** [comment]
@grahamperrin 
Am I suppose to read something specific there? Cuz I don't get it.

**Comment by grahamperrin** [comment]
Just a list, which includes the extension

**Comment by maxoku** [comment]
I know it's not fully compatible, otherwise it wouldn't have bugs. I'm asking for a solution here, not stating the obvious.

I wounder why anyone haven't made a different extension with those functions? It's literally the only extension that provides them.

**Comment by maxoku** [comment]
I was looking for an alternative. Free Download Manager has a support for Firefox, but can't do anything with Waterfox. I installed an add-on 'Download with Free Download Manager (FDM)'. It seems to be made for version 5, but I use version 3, so I changed the path to the executable. It does work as sends the request, but it also opens the main window of manager, which is annoying. FlashGot doesn't do that and I can't find out what it does exactly. If I could resolve this problem I would use it as a replacement. The other thing would be only to find a proper video downloader.

**Comment by grahamperrin** [comment]
> an alternative

https://redd.it/8nvoxc suggestions included [Bulk Media Downloader](https://addons.mozilla.org/addon/bulk-media-downloader/)

**Comment by maxoku** [comment]
@grahamperrin 
In what way it's an alternative? It's a poor alternative only of one function which doesn't help me at all on that point.
And fyi I already read that page. I know how to use google lol.

**Comment by grahamperrin** [comment]
> In what way it's an alternative? 

Not a question for me; I didn't make the suggestion.

**Comment by maxoku** [comment]
What I need is to send downloading to the external download manager. When I can just click on a link with right mouse button it's only a half of a problem. But when the site doesn't just share a link and gives link to the browser after loading a page then without FlashGot I can't download it with my external download manager. If the browser somehow would share the link with me and I could just click on it with right mouse button I could use official add-on of FDM that provides (only) a context menu item.
It's also about Current version. If am I about to switch to it I need such function also there. If there will be nothing than I can't not only switch to the Current version, I can't use Multiprocess in Classic.

**Comment by maxoku** [comment]
After new update of the Current version the official add-on of Free Download Manager stopped working, there is no context menu item to download anything.
