### ISSUE TITLE
Running issue of user compiled gecko68 on Windows 10

### ISSUE THREAD

**Issue by antonio-fr** [BrowserWorks/waterfox#1139]
When I compile Waterfox gecko68 branch in Windows 10, it compiles fines. Then when run, it directly says "Couldn't load XPCOM.". When I compile Firefox latest release v69.0.1, it compiles and runs fine.
Is there special dependencies required?
Is there a way to disable XPCOM, with "ac_add_options" directives ?

**Comment by antonio-fr** [comment]
Any chance I can get some help about this issue?

**Comment by MrAlex94** [comment]
Apologies for the late reply - this got lost in all the notifications.
XPCOM is needed for Waterfox to work. What command are you running to try
and execute Waterfox?

**Comment by antonio-fr** [comment]
I use 'mach run'. Same issue when double click on the exe binary to launch it.
So with mach this is in objdir-68/dist/bin 'waterfox.exe -no-remote -wait-for-browser -profile objdir-68/tmp/profile-default'

I think Firefox 69 and 70b are also using XPCOM ? Anyway, they're working fine, compilation and run.
