### ISSUE TITLE
Waterfox Current first run UX

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1142]
Re: https://redd.it/d2qa0m I tried to recreate a 68.0b1 first run user experience (UX) on Windows 10. 

I: 

1. quit Waterfox current
2. deleted profiles that were not created by Waterfox Classic
3. refrained from quitting Waterfox Classic
4. uninstalled Waterfox Current
5. installed 68.0b1

– then half-expected a first run of 68.0b1 to present the standard page that explains separation between profiles. 

Instead, the first run of Waterfox Current behaved as if option `-p` was used and the profile manager presented just one profile – _Default_ – which I knew was in use by Waterfox Classic, and I did **not** want Current to automatically update any extension in the Classic profile, however this was a disposable test environment so I threw caution to the wind and chose the default. 

As expected, only one instance of Waterfox could run with the one profile so I allowed Waterfox Current to **Close Waterfox** (Classic) then glanced at history and quit. 

I used Waterfox Classic to create a _Waterfox Current_ profile then reused the Waterfox Current icon in my task bar to relaunch Waterfox Current. 

As expected, there reappeared the Waterfox (Current) dialogue re: Waterfox (Classic) already running so I cancelled, then used `waterfox -migration` to have the import wizard at Waterfox Current start time. 

I soon realised that the import wizard could not run for Waterfox Current because the one and only profile was in use by Waterfox Classic so again I cancelled, then used `waterfox -p` and set recently created _Waterfox Current_ as my default profile for the Waterfox Current application. 

Screen recording: https://s.put.re/QjdfoTYp.mp4

#### A

In steps 1–4 above, **what did I miss?** 

Specifically: I want to recreate the Waterfox Current first run UX that includes **automated** presentation of the page that explains separation between profiles. 

**Postscript**: maybe I should have deleted the `installs.ini` file – sibling to <strike>the `Profiles` directory </strike>`profiles.ini`. (That's a guess, based on the content of the file.)

#### B

<strike>With or without a first run UX: **what's the address** of that page about separation?</strike>

**Comment by grahamperrin** [comment]
Re: the postscript above, I tried adding a step. 

1. Quit Waterfox current
2. delete profiles that were not created by Waterfox Classic
3. delete `installs.ini`
4. refrain from quitting Waterfox Classic
5. uninstall Waterfox Current
6. install 68.0b1.

A first run of the freshly installed Waterfox Current presents neither the **about:newinstall** page nor the **Important News** dialogue. 

![image](https://user-images.githubusercontent.com/192271/64905264-88024280-d6cd-11e9-941a-26eaf3d79f07.png)

What triggers the appearance of those two things?

**Comment by MrAlex94** [comment]
I don't think you missed anything. There were branding issues, which I believe are now resolved and there is proper separation in 2019.10. I've tested a myriad of ways - hopefully I haven't missed anything too obvious.

**Comment by grahamperrin** [comment]
Thanks. Back to a key point, 

> Specifically: I want to recreate the Waterfox Current first run UX that includes automated presentation of the page that explains separation between profiles.

More specifically: 

- I'd like to know how to trigger the routine. 

I assume that using the operating system to add a new user will lead to a run of the routine _for the new user_, but that's relatively extreme. 

I'd like to know how to trigger the routine for an _existing_ user.
