### ISSUE TITLE
Waterfox crashes on launch

### ISSUE THREAD

**Issue by TheTechRobo** [BrowserWorks/waterfox#1144]
**Describe the bug**
See #304. Crashes on Lion. I tried to download a file, it crashed and now it crashes whenever I open it. I am currently using Chrome 45.

**To Reproduce**
1. Download a file
2. Crashes
3. Repoen

**Expected behavior**
A "This is embarrasing tab"!.

**Desktop (please complete the following information):**
 - OS: [OS X Lion]
 - Waterfox Version [The latest one (I think)]

**Additional context**
Please help asap :)

**Comment by TheTechRobo** [comment]
Process:         launchd [51608]
Path:            /Users/USER/*/Waterfox 2.app/Contents/MacOS/waterfox
Identifier:      org.waterfoxproject.waterfox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [174]

Date/Time:       2019-09-13 07:56:58.413 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1798007 sec
Crashes Since Last Report:           163390
Per-App Crashes Since Last Report:   49
Anonymous UUID:                      E1408B0C-3062-4998-9255-1006A3076956

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 0

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4336464
    thread_create: 0
    thread_set_state: 32

Model: MacBookAir3,1, BootROM MBA31.0061.B07, 2 processors, Intel Core 2 Duo, 1.4 GHz, 2 GB, SMC 1.67f10
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313132533654465238412D47372020
Memory Module: BANK 1/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313132533654465238412D47372020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD1), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 11 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD TS064C, 60.67 GB
USB Device: FaceTime Camera (Built-in), apple_vendor_id, 0x850a, 0x24600000 / 2
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x04500000 / 3
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x821b, 0x04530000 / 5
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0242, 0x04300000 / 2


That is Apple's explanation

**Comment by TheTechRobo** [comment]
Here's apple's explanation:

**Comment by TheTechRobo** [comment]
Process:         launchd [51608]
Path:            /Users/USER/*/Waterfox 2.app/Contents/MacOS/waterfox
Identifier:      org.waterfoxproject.waterfox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [174]

Date/Time:       2019-09-13 07:56:58.413 -0400
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          1798007 sec
Crashes Since Last Report:           163390
Per-App Crashes Since Last Report:   49
Anonymous UUID:                      E1408B0C-3062-4998-9255-1006A3076956

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 0

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 4336464
    thread_create: 0
    thread_set_state: 32

Model: MacBookAir3,1, BootROM MBA31.0061.B07, 2 processors, Intel Core 2 Duo, 1.4 GHz, 2 GB, SMC 1.67f10
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313132533654465238412D47372020
Memory Module: BANK 1/DIMM0, 1 GB, DDR3, 1067 MHz, 0x80AD, 0x484D54313132533654465238412D47372020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD1), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 11 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD TS064C, 60.67 GB
USB Device: FaceTime Camera (Built-in), apple_vendor_id, 0x850a, 0x24600000 / 2
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x04500000 / 3
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x821b, 0x04530000 / 5
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0242, 0x04300000 / 2

**Comment by pjpreilly** [comment]
Lion & Mtn Lion are the problem ....

*This system can run the last version of OS X 10.10 "Yosemite" and OS X 10.11 "El Capitan," although advanced feature support is minimal (Mac-to-Mac AirDrop is supported). It is capable of running macOS Sierra (10.12) as well, although it does not support the Universal Clipboard, Auto Unlock, or Apple Pay features. Finally, this model is capable of running macOS High Sierra (10.13), and it supports HEVC (High-Efficiency Video Coding), but it does not support hardware accelerated HEVC. It is not compatible with macOS Mojave (10.14) or later versions of the operating system
--

**Comment by TheTechRobo** [comment]
Oh... I'll just stick with 56.2.10 (it failed to update to 56.2.11 a while back so I had to update manually and lucky me!

Is this bug going to be fixed or no? Thanks!

**Comment by brahmwindeler** [comment]
56.2.8 through 56.2.13 work fine on my 2008 MacBook (White) with Lion 10.7.5. The latest (56.2.14) is crashing at startup again. I've had to disable automatic updates in order to stay on 56.2.13 at this point.

**Comment by pjpreilly** [comment]
Yep!

**Comment by grahamperrin** [comment]
@TheTechRobo please open the disk image at https://www.waterfox.net/releases/ and overwrite your outdated Waterfox Classic application with Waterfox Classic 2019.10. 

If Waterfox Classic 2019.10 does not crash at launch time, you can close this issue. Thanks.

**Comment by TheTechRobo** [comment]
Waterfox Classic 2019.10 works... but sucks... here's why:

- So. Slow!! 2GB of RAM is not much but much slower than older releases
- It gave me a kernel panic when loading 3 tabs

I am not willing to try the kernel panic again in case corruption.

Thanks!

**Comment by grahamperrin** [comment]
> not willing to try the kernel panic again 

You need not retry. 

If there's not already a separate issue for panics with Waterfox Classic 2019.10, please raise a new issue (with _Waterfox Classic_ in the title) then we can show you how to regain the report from the previous panic. 

Thanks

> in case corruption.

Loosely speaking: a kernel panic can occur to _prevent_ (or minimise) corruption.

**Comment by TheTechRobo** [comment]
UPDATE: Waterfox Classic 2020.03 is up and functional. Though I think I'm going to start a new issue about a kernel panic (or find an existing one). 

Thanks for all your advice :slight_smile:
