### ISSUE TITLE
About:preferences borken 68b1

### ISSUE THREAD

**Issue by Commissar0617** [BrowserWorks/waterfox#1149]
looks like possibly the fix for about:preferences hasn't made its way to current?

**Comment by grahamperrin** [comment]
You might have outdated, non-announced build 20190907162938 on Windows. 

<https://www.waterfox.net/releases/> includes the full installer for a more recent build of 68.0b1. 

Related: 

- https://www.reddit.com/comments/d15yea/-/ezr4xzv/
- https://github.com/grahamperrin/Waterfox/wiki/Archive-of-change-logs,-announcements-and-downloads#680b1

**Comment by Commissar0617** [comment]
uh, yeah... interesting how WF autoupdater said i was up to date,.,.,.
