### ISSUE TITLE
geoid error with 68b1

### ISSUE THREAD

**Issue by Commissar0617** [BrowserWorks/waterfox#1151]
hulu states "We are unable to determine your location". web console shows unknown geoid error. 

error [geo lib] 2 Unknown error acquiring position commons.b28f809aa266559ac96e.js:1:370580
    NextJS 10
        methodFactory
        e
        E
        _invoke
        t
        a
        u
        o
        N
        c
    nrWrapper https://www.hulu.com/profiles?next=/:62

**Comment by grahamperrin** [comment]
Which operating system?

**Comment by Commissar0617** [comment]
windumbs 10 pro

**Comment by grahamperrin** [comment]
**about:config?filter=geo.wifi.uri**

With `geo.wifi.uri` valueless (a default with 68.0b1 on Windows): 

![image](https://user-images.githubusercontent.com/192271/65212995-493d0580-da9c-11e9-8ed8-c43b4c056d92.png)

With the value taken from https://www.reddit.com/comments/8oief0/-/e06jqjf/?context=1 – 

`https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%`

– no problem. Tested: https://roadtrip.glitch.me/

**Comment by Commissar0617** [comment]
yep, that fixes it. also fixes alpha.

**Comment by grahamperrin** [comment]
Meta, tracking: #582 in particular https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-398939358
