### ISSUE TITLE
Updating to 68.0b1

### ISSUE THREAD

**Issue by rebop** [BrowserWorks/waterfox#1152]
I have Waterfox and WF Alpha on one computer. Alpha "a" was installed in c:\program files\waterfox alpha with the profile in C:\Users\xxxxxxxxx\AppData\Roaming\Mozilla\Waterfox\Profiles- etc. as opposed to ...Roaming\Waterfox where 56's profile is.

If I use the full installer for "b" and redirect as custom to c:\program files\waterfox alpha, will all go well without affecting my 56 installation?

Thanks.

**Comment by grahamperrin** [comment]
### Application

> full installer for "b"

Just take care to **not** allow installation of Waterfox Current to the path that's associated with Waterfox Classic on Windows: 

`C:\Program Files\Waterfox\`

– if you do allow it, there'll be a prompt to **Upgrade** (not **Install**) but the distinction between the words is easily overlooked. 

### Profiles

Take care to **not** use Waterfox Current with your Waterfox Classic profile. 

Whilst each app will default to its own profile, it's possible to choose a different profile – about:profiles and so on.

**Comment by rebop** [comment]
Thanks, Graham. But they are BOTH upgrades. (I am assuming what you call "current" is 68.

What I am more worries about is not the executables in Program Files but the proper profile and the "classic" profile not being disturbed. And it was put in that odd spot as mentioned above.

Same answer? Just trying to be overly cautious and be sure they are separate installations and profiles.

**Comment by grahamperrin** [comment]
> … what you call "current" is 68. …

True. The distinction between Classic and Current is at https://www.waterfox.net/releases/ – blink, and you'll miss it :-)

Re: https://www.waterfox.net/blog/ I guess that the terminology for 68 will be mentioned in a blog post re: 68.0b1.

**Comment by grahamperrin** [comment]
From #1142:

> … As expected, only one instance of Waterfox could run with the one profile …

So if you run (and do not quit) Waterfox Classic before attempting to start Waterfox Current 68.0b1, then Waterfox Current will either: 

a) start, with a Waterfox Current profile (e.g. _68-edition-default_); or 

b) cautiously refuse to start, if the Waterfox Classic profile (e.g. _default_) is in use. 

----

I can manually force misbehaviour: 

![image](https://user-images.githubusercontent.com/192271/65110987-26461f00-d9d2-11e9-8f9c-339e4237f9ab.png)

![image](https://user-images.githubusercontent.com/192271/65111015-44ac1a80-d9d2-11e9-8c9b-c458ae51ec0d.png)

> **Close Waterfox**
> 
> Waterfox is already running, but is not responding. The old Waterfox process must be closed to open a new window. 
> 
> [**Close Waterfox**] [Cancel]

Whilst this traditional dialogue uses the word _old_, it is not version-sensitive (old does not mean Classic). In this situation, the default button – **Close Waterfox** – **_will_** close Waterfox Classic and allow Waterfox Current to proceed with the same profile. 

----

If in doubt: 

- before your first run of Waterfox 68.0b1, quit Waterfox Classic and set aside a copy (backup) of your Waterfox Classic profile(s). 

#### Alpha, beta

I don't expect anyone to use an alpha of Waterfox Current alongside a beta of Waterfox Current but if this is done, I should expect the alpha to use its own _dev-edition-default_ profile. 

https://github.com/MrAlex94/Waterfox/blob/6c9d3ffe686d1a666a486eafd1e414a904bf6699/toolkit/profile/nsIToolkitProfileService.idl#L33

**Comment by rebop** [comment]
Thanks. I think I expected most of that but now on your terminology the unanswered question for me is that if I upgrade to Beta from Alpha which it continue to use the dev-edition-default profile in C:\Users\xxxxxxxxxxxx\AppData\Roaming\Mozilla\Waterfox\Profiles\hflsftq0.dev-edition-default, not touch the classic profile and not create an entirely new one? This will tell me more about what I might have to save, copy or recreate to have Beta look and act like Alpha and maintain an entirely separate Classic.

Thanks.

**Comment by rebop** [comment]
Hi Graham. Still holding off. Can you comment on my last question above? Thanks!

**Comment by grahamperrin** [comment]
A screen recording from around nine days ago: https://put.re/player/4DeSorjP.mp4

Focus: from around 09:50 on the timeline (07:10:14 on the clock, bottom left). 

If I'm not mistaken, an upgrade from 68.0a2 to 68.0b1 will cause Waterfox Current to use (by default) the same profile as Waterfox Classic. 

@MrAlex94 if this bug is reproducible (meta, tracking: #538) then FWIW, I'm inclined to treat it as _wontfix_. Considerations: 

- alpha, edge case
- 68.0a2 was discoverable but not formally announced (no blog post, and so on)
- IIRC, without reviewing the entire recording, the bug is less (or not) likely to occur with an upgrade from 68.0a**1** to 68.0b1.

**Comment by rebop** [comment]
So, still not clear :) My goal:

I have Current and Classic running as separate installations on the same machine and using the Classic profile for Classic only and my profile from Current "01a" with "01b" since I have done so much work to learn alpha and configure to be somewhat usable for me, albeit weeks ago and have forgotten how I got to where I am.

"Perhaps" it is best to save the 01a profile, uninstall 01a, install 01b and then overwrite the 01b profile with the saved 01a? If not, what would you recommend?

**Comment by grahamperrin** [comment]
> … overwrite the 01b profile with the saved 01a? … 

Maybe not advisable. 

Re: https://github.com/MrAlex94/Waterfox/issues/329#issue-284338459 there's the potential for extension-related problems to arise from absolute paths, and I have no idea whether this type of thing was fixed in the Mozilla code base for Waterfox Current. 

> … what would you recommend?

1. Exit all instances of Waterfox
2. backup profiles for Waterfox Classic and Waterfox alpha
3. uninstall Waterfox alpha
4. restart Windows
5. install 68.0b1 **and do not** upgrade (i.e. do take care to install to a previously unused path)
6. decline the installer invitation to start Waterfox
7. use command line option `-p` to start the profile manager for Waterfox Current
8. create a profile to be used as the default for Waterfox Current. 

Something like this: 

![image](https://user-images.githubusercontent.com/192271/65822096-abcd9880-e236-11e9-89de-04c9fb94fd54.png)

End result, YMMV: 

![image](https://user-images.githubusercontent.com/192271/65822105-c7d13a00-e236-11e9-8908-3a5739828db2.png)

**Comment by rebop** [comment]
And then I lose all the work I did on Alpha.... Wish I would have known. The only good news is I think I can make this work when I have to some day. But for now, cannot take the time nor remember what I did to get where I am again. Foolish me thought the Alphas would "upgrade" as the Classic.

**Comment by grahamperrin** [comment]
> the work I did on Alpha

You should be able to copy things such as `places.sqlite` and `prefs.js` (whilst the applications are not running), what other things did you have in mind?

### Upgrading from alpha, to 68.0b1

It's probably possible, with a combination of these three things: 

- a copy of the required profile, to the directory that contains the `profiles.ini` for Waterfox Classic
- **temporary** edition of the `profiles.ini` for Waterfox Classic
- care to not start Waterfox Classic until after completion of a Waterfox Current import/migration routine …

**Comment by rebop** [comment]
Well, I should be able to move User Chrome. Unsure on changes to About Config. Moved icons. Configurations of extensions. And in some cases specific versions of extensions that work when newer do not. Bookmarks I can move of course.

All I can think of over coffee right now. Might be more...

**Comment by grahamperrin** [comment]
> … potential for extension-related problems to arise from absolute paths, and I have no idea whether this type of thing was fixed in the Mozilla code base for Waterfox Current. …

I did some testing. As far as I can tell, the paths are not (or no longer) an issue. 

I copied a 68.0a1 profile – with a user-installed extension – from `~/.mozilla/waterfox/` and edited `~/.waterfox/installs.ini` and `~/.waterfox/profiles.ini` to make use of the copy. 

Rough guide, YMMV: 

![2019-09-29 16:33:07](https://user-images.githubusercontent.com/192271/65835432-e8080400-e2dd-11e9-9c9a-7603d0c9b6ee.png)

![2019-09-29 16:35:47](https://user-images.githubusercontent.com/192271/65835434-edfde500-e2dd-11e9-92be-d9fe7d5b5273.png)

![2019-09-29 16:40:43](https://user-images.githubusercontent.com/192271/65835437-f48c5c80-e2dd-11e9-918d-dba88174e4dc.png)

![2019-09-29 17:00:20](https://user-images.githubusercontent.com/192271/65835442-feae5b00-e2dd-11e9-9f13-31823330578d.png)

**Comment by rebop** [comment]
Good stuff. Thanks for checking that Graham.

**Comment by grahamperrin** [comment]
@rebop 

Without me reviewing _all_ of what's above … the recent soft and hard launches of Waterfox Current 2019.10 seem to be almost completely free from update-specific issues. 

Should we close this _updating to_ 68.0b1 issue?

**Comment by rebop** [comment]
Yes indeed, Graham. this is no longer an issue. We have new ones :) But this can be closed.
