### ISSUE TITLE
Google search suggestions missing from Waterfox Current

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1163]
Spun off from <https://www.reddit.com/comments/d5p24x/-/f0qaf7h/>:

![image](https://user-images.githubusercontent.com/192271/65211210-cdd85580-da95-11e9-98aa-de78ea72c574.png)

![image](https://user-images.githubusercontent.com/192271/65211221-dcbf0800-da95-11e9-86f7-cee6bc30166f.png)

Meta, tracking: #538

**Comment by grahamperrin** [comment]
I no longer see the issue with icons. 

Still, no suggestions from Google. Waterfox Current 2019.10 (20191023104314) on Manjaro Linux: 

![image](https://user-images.githubusercontent.com/192271/68726054-37697180-05b8-11ea-9743-b7c504e3338a.png)

**Comment by Achaean** [comment]
Same problem here (at Linux as well).

**Comment by BananasGoMoo** [comment]
I also have this problem:
Windows 10, Waterfox Current 2020.01

**Comment by BananasGoMoo** [comment]
Still having this problem in 2020.03

**Comment by grahamperrin** [comment]
An obtuse workaround: make Startpage the default. 

(For its _web_ results (but not its _news_ tab results), Startpage.com uses Google.)

**Comment by BananasGoMoo** [comment]
> 
> 
> An obtuse workaround: make Startpage the default.
> 
> (For its _web_ results (but not its _news_ tab results), Startpage.com uses Google.)

Thanks! Do you know if Alex is working on this bug currently? Or any info.

**Comment by grahamperrin** [comment]
For overviews of work on bugs, please see for example #538 and https://github.com/MrAlex94/Waterfox/issues?q=is%3Aopen+label%3Abug+sort%3Aupdated-desc

**Comment by martinso22** [comment]
Still not fixed! Devs? What are you waiting?

**Comment by BananasGoMoo** [comment]
still a problem for me

**Comment by HeIsAChar** [comment]
me too

**Comment by Jaitsu** [comment]
Pleased to report that the problem seems to be solved in G3.0.2! I have working Google search suggestions.
