### ISSUE TITLE
Shockwave Flash 32.0.0.223 plug-in not loading reliably in Waterfox Current on Linux

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1165]
https://redd.it/d6dfjb is indicative of a regression between alpha and 68.0b1. 

https://helpx.adobe.com/flash-player.html ▶ **Check now**

- shows the flash version at https://helpx.adobe.com/flash-player.html#flashContent
- does not present the customary information at https://helpx.adobe.com/flash-player.html#warningbody
- does not present the animation at https://helpx.adobe.com/flash-player.html#flashContent_tree

Note the non-appearance of a plug-in icon: 

![image](https://user-images.githubusercontent.com/192271/65267581-3878a800-db0d-11e9-88d9-9bc24be14df1.png)

– but this non-appearance is not consistently reproducible. A few seconds before taking that screenshot, with a previous run of 68.0b1 in the same virtual machine, I **did** have the plug-in icon, and I had previously clicked to allow and remember the allowance, but IIRC the plug-in icon remained red. 

Not reproducible with 68.0b1 (20190908151900) on Windows 10. 

Meta, tracking: #538

**Comment by tcreek** [comment]
I doubt it is even worth the time or effort it to fix.

You do realize Flash Player is basically dead, and will be EOL next year?

https://theblog.adobe.com/adobe-flash-update/

**Comment by grahamperrin** [comment]
> You do realize 

Yes, as does Alex; [reddit.com/comments/bnihh4/-/enbdijs/?context=1](https://www.reddit.com/comments/bnihh4/-/enbdijs/?context=1)
