### ISSUE TITLE
waterfox archived versions

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#1166]
Hi, on this page "https://github.com/MrAlex94/Waterfox/releases", it seems that only source code files for each waterfox versions are available. Are there windows files anywhere? Thanks.

**Comment by grahamperrin** [comment]
[Waterfox download archive](https://github.com/MrAlex94/Waterfox/issues/418) … ▶ [Moved to](https://github.com/MrAlex94/Waterfox/issues/418#issuecomment-401091893) … ▶ https://github.com/grahamperrin/Waterfox/wiki ▶ Archive of change logs, announcements and downloads

**Comment by MrAlex94** [comment]
https://cdn.waterfox.net
