### ISSUE TITLE
Waterfox Current DRM (Widevine)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1168]
Meta, tracking: #538 

### Netflix

https://redd.it/d8c4jr reports symptoms: 

![image](https://user-images.githubusercontent.com/192271/65477763-3604ae00-de7f-11e9-9909-0e1610297643.png)

> Whoops, something went wrong…
> 
> Streaming Error
> 
> This title is not available to watch instantly. Please try another title. 
> 
> Error Code: F7121-1331

### Amazon Video

- OK in Waterfox Classic 56.2.14 on Windows 10
- will not play in Waterfox Current 68.0b1 (20190908151900)

![image](https://user-images.githubusercontent.com/192271/65477635-d3abad80-de7e-11e9-8d45-2e91be175d38.png)

> Video Unavailable
> 
> We're experiencing a problem playing this video. For assistance, please go to [www.amazon.co.uk/videohelp](https://www.amazon.co.uk/videohelp).

Tested: 

- the movie at https://www.amazon.co.uk/gp/video/detail/B00X674KKU
- not the trailer; this does not use DRM. 

The version of the Widevine CDM is only marginally different (4.10.1440.18 in Current, 4.10.1440.19 in Classic): 

![image](https://user-images.githubusercontent.com/192271/65477706-0e154a80-de7f-11e9-9e0c-affc30391e51.png)

I doubt that a UA override will be effective in this case. I tried both of these: 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0` from Firefox 60.9.0esr (64-bit), which can play the movie

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0`

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/d8c4jr/-/f1b7dj2/

> I am aware, Widevine needs an update.

**Comment by grahamperrin** [comment]
[Netflix Error F7121-1331](https://help.netflix.com/en/node/100151)

> … typically points to information stored on your browser that needs to be refreshed. …

– although with Waterfox 68.0b1, this may not be the case. 

Workaround, thanks to Alex: https://www.reddit.com/comments/d91j8x/-/f1fs6hy/

**Comment by grahamperrin** [comment]
From <https://www.reddit.com/comments/dcah5v/-/f272v77/?context=1>

> … beta 1. In Linux its working but in windows no

– and <https://www.reddit.com/comments/dcah5v/-/f288wtj/>: 

> Next update has the fix, will release ASAP :-)

**Comment by grahamperrin** [comment]
> … The version of the Widevine CDM is only marginally different (4.10.1440.18 in Current, 4.10.1440.19 in Classic): …

– and confirming [what askelam reported](https://redd.it/dcah5v) in Reddit, inferior 4.10.1440.18 **does** work as expected on (Manjaro) Linux: 

![image](https://user-images.githubusercontent.com/192271/66262377-0f773900-e7d6-11e9-931c-700fea92a506.png)

- tested with the example from the opening post, <https://www.amazon.co.uk/gp/video/detail/B00X674KKU>

![image](https://user-images.githubusercontent.com/192271/66262379-1a31ce00-e7d6-11e9-9178-8b50f4f93ee6.png)

**Comment by grahamperrin** [comment]
### Netflix error F7121-1331 on Waterfox Current

https://redd.it/dp5vma for Waterfox _Classic_ 2019.10 observes a workaround that involves trimming the Waterfox-specific tail from the UA string and applying the override to specific sites (not universally). 

Waterfox Current 2019.10 for Windows uses no such tail: 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0`

I don't have Netflix, can't test. 

Can any user of Netflix **on Windows** tell whether late October build 20191022131008 of Waterfox Current 2019.10 is **free from error F7121-1331**?

Thanks

**Comment by grahamperrin** [comment]
### Amazon Video

> will not play in Waterfox Current 68.0b1 (20190908151900)

Not reproducible with Waterfox Current 2019.10 on Windows.

**Comment by Bielecki** [comment]
### Netflix
Can confirm Netflix working well on default useragent on Waterfox Current 2019.10 on Windows 10

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/d8c4jr/-/f64x8rg/ noted with thanks.
