### ISSUE TITLE
What about the cliqz integration?

### ISSUE THREAD

**Issue by cnleo** [BrowserWorks/waterfox#1169]
Is it complete removed in Waterfox? I have read it still exist for German Users with German language.

https://www.ghacks.net/2017/10/06/mozilla-to-launch-firefox-cliqz-experiment-with-data-collecting/
https://support.mozilla.org/en-US/kb/cliqz-recommendations-firefox

**Comment by grahamperrin** [comment]
### Integration

To the best of my knowledge, the integration was essentially an extension. 

You'll probably find no more than one system extension with Waterfox Classic – a theme: 

![image](https://user-images.githubusercontent.com/192271/65562177-42e7d700-df3d-11e9-9cd8-37dccaf26520.png)

The `features` directory comprises language packs. 

```text
$ date ; uname -v
Wed 25 Sep 2019 02:38:49 BST
FreeBSD 13.0-CURRENT r352657 GENERIC 
$ pkg query '%o %v %R' waterfox
www/waterfox 56.2.14 poudriere
$ ls -hl /usr/local/lib/waterfox/browser/features/ | grep -v -i langpack
total 95283
$ 
````

### Without integration

The more modern [Cliqz Tab](https://addons.mozilla.org/addon/cliqz/) – an extension but not a system extension – offers on-boarding at MyOffrz, https://myoffrz.com/on-boarding/ (German, I can't find an English alternative). 

English https://myoffrz.com/en/lp1/ offers a MyOffrz extension: 

- https://addons.mozilla.org/firefox/downloads/latest/myoffrz/addon-9609-latest.xpi

https://addons.mozilla.org/addon/myoffrz/

MyOffz extension preferences: 

![image](https://user-images.githubusercontent.com/192271/65563811-c2c47000-df42-11e9-8edc-75d8b4a67d77.png)

– translated by Google: 

> ☑ Allow Human Web
> 
> To personalize offers without creating a profile, we use a technology called Human Web. The community user contributes with completely anonymous collected data to the statistics we use to create trigger rules for our offers. [Learn more.](https://sparalarm.chip.de/datenschutzerklaerung/)
> 
> ☑ Allow transmission of usage data

Also in the pop-up:

> No personal data leaves your device. Your browser automatically identifies what you might be interested in based on your previous use. 

Source code for CliqzTab and MyOffrz:

- https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Faddon%2Fcliqz%2F
- https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Faddon%2Fmyoffrz%2F

**Comment by cnleo** [comment]
Is there still in Waterfox the possibility to remote/pre-install Addons like “Mr. Robot”/cliqz without letting the user know?

https://tech.slashdot.org/story/17/12/15/228235/mozilla-slipped-a-mr-robot-promo-plugin-into-firefox-and-users-are-pissed
