### ISSUE TITLE
Waterfox Current: User-Agent identifies as "Firefox 2019.0"

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#1171]
The default user-agent string of Waterfox Current built from https://github.com/MrAlex94/Waterfox/commit/bc9d5fccbaa7a076aaaec1695fc9f5a08861b281 is -
```
Mozilla/5.0 (X11; Linux x86_64; rv:2019.0) Gecko/20100101 Firefox/2019.0
```
(I looked at http://useragentstring.com/ in a new profile.)

Is this intentional?  If so, why this change?

**Comment by MrAlex94** [comment]
It’s just meant to be the display version, am going to push the change.
