### ISSUE TITLE
Waterfox Classic fails to load web pages when built macOS 10.15 Beta 9

### ISSUE THREAD

**Issue by MrAlex94** [BrowserWorks/waterfox#1172]
**Describe the bug**
Waterfox Classic built on macOS 10.15 Beta 9 no longer can load web pages.

**To Reproduce**
1. Build Waterfox Classic on macOS 10.15 Beta 9.

**Expected behavior**
Compilation to be successful.

**Error Message**

> Unexpected response from server
> 
> Waterfox doesn’t know how to communicate with the server.
> 
>  Check to make sure your system has the Personal Security Manager installed.
>  This might be due to a non-standard configuration on the server.

** Console Output**
```
NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService] nsUrlClassifierListManager.js:69
NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]  crypto-SDR.js:50
Error: Initialization failed  storage-json.js:89:13
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Initialization failed" {file: "file:///Users/akontos/Workspace/Waterfox/objdir-classic/dist/Waterfox.app/Contents/Resources/components/storage-json.js" line: 89}]'[JavaScript Error: "Initialization failed" {file: "file:///Users/akontos/Workspace/Waterfox/objdir-classic/dist/Waterfox.app/Contents/Resources/components/storage-json.js" line: 89}]' when calling method: [nsILoginManagerStorage::initialize]  nsLoginManager.js:129
[Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: resource://gre/modules/XPCOMUtils.jsm :: XPCU_serviceLambda :: line 266"  data: no]  (unknown)
NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]  browser.js:1746
```

If anyone else can help with this, would be much appreciated 🤔

**Comment by grahamperrin** [comment]
>> `Error: Initialization failed  storage-json.js:89:13`

I thought first of https://firefox-storage-test.glitch.me/ but (D'oh!) you'll be unable to load the page. 

Are `http://` URLs bugged? E.g. <http://dougengelbart.org/content/view/243/253/>

Reproducible with a new profile?

**Comment by pjpreilly** [comment]
Why are you building CLASSIC on an unsupported OS. Maybe build it on an older Mac OS where it will be used since Firefox is NOT supported on OS x less than 10.9?

**Comment by grahamperrin** [comment]
Use of a [_pre_-release version of an OS](https://web.archive.org/web/20190929062119/https://www.apple.com/macos/catalina/) for a build of an app that might gain end use on _released_ versions elsewhere is, debatably, not best practice however it is reasonably commonplace. A canary in the coal mine is a sane/essential part of a broader strategy to building.

**Comment by MrAlex94** [comment]
@pjpreilly, [here](https://send.firefox.com/download/875e4fd41637a6e3/#71SZLMmDakqGzHDWwKag0A) is a build for you to try.

**Comment by pjpreilly** [comment]
Tested the build on macbook 3,1 os x 10.7.5 Lion and:

It launches & runs with no immediate crash. (fixes 56.2.14 regression)
Fixes on 6abc.com & mlb.com are evident but,
All other browser crashes & kernel panics are as before.
Downloads and accessing Preferences caused a browser crash while turning on DRM & default Newtab causes a KP.

If your intent was to test the two items that now work you have succeeded! Two steps FORWARD!

**Comment by pjpreilly** [comment]
.... Looks like the "Watch Videos" on 6abc.com is working now too!!!!!
@grahamperrin how 'bout that!

**Comment by grahamperrin** [comment]
Thanks, what's the build ID?

- about:support

(I don't have a Mac here.)

**Comment by pjpreilly** [comment]
Build ID 	20191009132218

I believe it's an interim TEST build.

**Comment by pjpreilly** [comment]
@MrAlex94  anything coming down the line to test sometime soon?

**Comment by pjpreilly** [comment]
Are there any improvements/differences from test build to latest release or are they the same?

**Comment by MrAlex94** [comment]
The same for now

**Comment by pjpreilly** [comment]
Thx, looking forward for more test builds to shake out the cobwebs.
