### ISSUE TITLE
DNS over TLS/HTTPS option is missing in network settings

### ISSUE THREAD

**Issue by gloschtla** [BrowserWorks/waterfox#1173]
One important feature is missing in Waterfox: In the network settings there is no given option to use a custom DoT or DoH connection. I tried to use [DNSwarden Adblock](https://github.com/bhanupratapys/dnswarden/blob/master/README.md) according to [this tutorial](https://www.zdnet.de/wp-content/uploads/2019/04/Firefox-Benutzerdefinierten-DNS-Server-mit-Doh-Support-eintragen.jpg). But then I discovered, the option to activate encrypted DNS requests does not exist in Waterfox.

**Comment by grahamperrin** [comment]
[No "network.trr" hierarchy in Waterfox · Issue #928 …](https://github.com/MrAlex94/Waterfox/issues/928)

> … DNS-over-HTTPS …

**Comment by grahamperrin** [comment]
Enhancements made to Waterfox Current. 

@gloschtla if you like, please close this issue.

**Comment by gloschtla** [comment]
in the Connection settings of Waterfox 2020.03.01 (64-bit) I still cannot see the last entry "DNS over HTTPS", which I know from Firefox.

**Comment by grahamperrin** [comment]
Waterfox Current: 

![image](https://user-images.githubusercontent.com/192271/76711138-3894e180-6705-11ea-991b-0f0acf83fae7.png)

> Waterfox 2020.03.01 (64-bit) 

That's probably Waterfox _Classic_ `2020.03.1`. Re: https://www.reddit.com/r/waterfox/comments/f9howq/will_dns_over_https_be_added_to_waterfox/firpq7w/ there is less chance of Waterfox Classic gaining the relevant code.
