### ISSUE TITLE
Enter key doesn't work in the address bar

### ISSUE THREAD

**Issue by swashdev** [BrowserWorks/waterfox#1175]
**Describe the bug**
When typing in the address bar, pressing the enter key does not begin navigation and does not initiate searches unless one of the search suggestions has been highlighted by the mouse cursor.

If no search suggestions have been produced by the program, nothing happens when the enter key is pressed.  If a search suggestion is highlighted by the mouse cursor, whatever the user has typed in is then searched or a URL is navigated to, whichever applies according to normal operation.  It doesn't appear to matter which suggestion is highlighted, as long as the cursor is inside the box which contains the search suggestions.

**Expected behavior**
The enter key is meant to function as a shortcut for the "go" or "search" button on the address bar, even if no search suggestions have been provided.

**Desktop (please complete the following information):**
 - OS: Xubuntu 19.04 (64-bit)
 - Waterfox Version: 56.2.14 (64-bit)

**Comment by grahamperrin** [comment]
> If no search suggestions have been produced by the program, nothing happens when the enter key is pressed.

Not reproducible here with build 20190903144949 on Lubuntu. 

A screen recording: 

- <strike>2019-09-29 00:56.zip</strike>
- with a new profile [2019-09-29 01:12.zip](https://github.com/MrAlex94/Waterfox/files/3666146/2019-09-29.01.12.zip)

Can you reproduce the issue with Waterfox Classic in safe mode? 

- about:support

What's the build ID?

Is the issue reproducible with a new profile? 

- about:profiles

If we can make the issue reproducible, it might help to explain some of the following:

- [Bookmarks are not working anymore and the Enter button doesn't work on URLs? : waterfox](https://www.reddit.com/r/waterfox/comments/9y829n/bookmarks_are_not_working_anymore_and_the_enter/) (2018-11-18, archived)
- [making "enter" work again in address bar (and removing GO arrow) : waterfox](https://www.reddit.com/r/waterfox/comments/b2kd5v/making_enter_work_again_in_address_bar_and/) (2019-03-18, archived)
- [Waterfox on Linux sometimes won't do anything after pressing Enter key : waterfox](https://www.reddit.com/r/waterfox/comments/bezpqs/waterfox_on_linux_sometimes_wont_do_anything/) (2019-04-19)
- [Pressing Enter on the address bar doesn't do anything, Bookmarks not working : waterfox](https://www.reddit.com/r/waterfox/comments/bl5ub7/pressing_enter_on_the_address_bar_doesnt_do/) (2019-05-06)

**Comment by NebelNidas** [comment]
Yeah, it seems to only happen very rarely. But I had this multiple times already, too. Unfortunately I couldn't test enough, since it was always on school PCs or others I had only short access to. Very strange, seems to be non-OS and software related, since in my cases it happened on multiple Windows 10 and 7 computers, some almost clean installed.

**Comment by grahamperrin** [comment]
Thanks, I _sometimes_ found <kbd>Return</kbd> not working when expected but (to the best of recollection) _never_ a problem in this situation: 

> If no search suggestions have been produced by the program, nothing happens when the enter key is pressed. 

Three split-second frames from the (problem-free) screen recording: 

![2019-09-29 01:12:18 frame a](https://user-images.githubusercontent.com/192271/65835912-34564280-e2e4-11e9-9956-408e755bce28.png)

![2019-09-29 01:12:18 frame b](https://user-images.githubusercontent.com/192271/65835920-4932d600-e2e4-11e9-9dee-cc896eed0e94.png)

![2019-09-29 01:12:18 frame c](https://user-images.githubusercontent.com/192271/65835923-518b1100-e2e4-11e9-8ae1-16ac9d4f8260.png)

– that's the result of me typing enough nonsense for the application (or should I say, the installed search engine) to cease suggesting. 

@swashdev before you key <kbd>Enter</kbd>: 

- is the sole menu item visibly highlighted/selected?

What's your preferred search engine and if it wasn't integral to Waterfox, what was its origin?

**Comment by swashdev** [comment]
Restarting with add-ons disabled doesn't seem to help the problem.  I can use the Enter key to visit a website from the start screen, but from then on the problem continues to present itself.  I have found that pressing the Backspace key brings up the normal search suggestions and then the Enter key works, but then typing anything else causes the problem to come back again.  It's almost like pressing Backspace causes the address bar to wake up and remember that I'm typing into it.

_Edit_:  Typing a slash `/` also causes the address bar to "wake up" as described above.  Weird.

The Build ID for my copy of Waterfox is 20190903144949; I got it from the Releases page on waterfox.net.  The problem does not appear to present itself in a new profile.

My default search engine is Startpage.  When I imported my Firefox settings into Waterfox, I got a warning that the plug-in wasn't compatible with my version of Waterfox, so I uninstalled it and then re-installed a new copy of the plug-in [from the Startpage website](https://www.startpage.com/en/search/download-startpage-plugin.html).

**Comment by Squall-Leonhart** [comment]
I have sporadic reproduction in a profile, but not in others, all use the same settings and extensions.

**Comment by Slater91** [comment]
The address bar stopped working with the latest update (2020.07.02) for me. The only solution I found is to remove the search bar, but this implies a loss of functionality. The issue is consistently present and persists across app and system reboots, and is also present in safe mode.  No other app exhibits the issue, including Firefox.
I am using KDE neon, based on Ubuntu 18.04.

**Comment by hawkeye116477** [comment]
@Slater91 For me address bar works fine. Also just saying 2020.07.02 isn't sufficient, you mean Current or Classic?

**Comment by Slater91** [comment]
Sorry, you are right! I forgot to mention that. It happens in Current, while Classic works fine.
I just noticed that the address bar in Current stopped working again, adding back the search bar made it work. Please let me know if and how I can provide further info to understand where the issue stems from.

**Comment by hawkeye116477** [comment]
Ok, I can reproduce now, seems it could be still same source of problem as on #1686 and #1683, regression from #1678. Apparently problem is somewhere on another place.

CC @MrAlex94

**Comment by InvisibleManX** [comment]
@Slater91 
@hawkeye116477 

Again, if a Home Page button is placed in front of the address bar, it gets magically fixed, just like the search problem was getting fixed by it in the preivous update -_-
