### ISSUE TITLE
Donation improvement 

### ISSUE THREAD

**Issue by g3ngr33n** [BrowserWorks/waterfox#1178]
Hello,

First I would like to thanks everyone involved on this project, Waterfox is for me the last browser acceptable to run without being "sandboxed" by a qemu.

As much as I desire make a donation, strip refuse to accept my credit card. I tried for several month now... While I haven't the single problem with paypal, strip is a no can do, look like not all country are supported.

That's said, offering few other method to donate, as paypal, cryptocurrency... could allow some folk, to donate to the Waterfox project.

Thanks,

**Comment by grahamperrin** [comment]
Also: 

- #582 
- #1145
- https://twitter.com/grahamperrin/status/1007927335939649536 – the linked blog post moved to https://www.waterfox.net/blog/waterfox-56.2.1-release-download and no longer has commentary, but comments re: PayPal appear under a few other posts
- https://redd.it/d0jag8
- https://redd.it/9txtd7 ▶ Alex's 2017 comments at https://redd.it/67eicq and https://www.reddit.com/comments/5ysn9e/-/dexsrac/?context=1

**Comment by g3ngr33n** [comment]
Alright, paypal is a no can do, but there is other donation system available : Skrill, Wepay, Webmoney... And other way to give : cryptocurrency, "Waterfox goods" (t-shirt...)...

**Comment by grahamperrin** [comment]
Thanks, 

> …  paypal is a no can do, … 

– and to avoid any misunderstanding (for people who might speed-read this issue): as far as I recall, from the 2018 tweet, PayPal became a no can do _for coffee_ e.g. 

![image](https://user-images.githubusercontent.com/192271/66089398-03da0700-e577-11e9-973f-3871bda4b466.png)

Re: https://redd.it/9txtd7 I became familiar with [Liberapay](https://liberapay.com/) probably after beginning to use free [Framasoft](https://framasoft.org/) services such as Framasphère …

**Comment by g3ngr33n** [comment]
Woot, liberapay noted down, didn't known this one. I will add : [Flattr](https://flattr.com/)

**Comment by grahamperrin** [comment]
https://www.waterfox.net/blog/waterfox-2019.10-release-download/#commento-comment-card-2031d76d3c24dc08e761a400a3b9a3cead353ed95238585cd1d689da5a37b225

> I tried to do the buy me a coffee thing, because this browser has solved so many problems I had with Firefox, Chrome, Edge, IE and Vivaldi and I wanted to say thank you. However, I was unable to make a contribution. For a start the payment was incorrectly configured at £0.80 and then it was "refused in the United States", whatever that means. I wish you could let people pay by Paypal, which is SO MUCH EASIER!
