### ISSUE TITLE
Version 52 not in Update XML

### ISSUE THREAD

**Issue by Scrxtchy** [BrowserWorks/waterfox#123]
The website (and git) have had 52 for a few days, but my client hasn't heard of it's existance
Checking out the update XML from my about:config, It's just empty

https://www.waterfoxproject.org/update/win64/51.0.1/en-us/release/update.xml

```
<updates>
</updates>
```

**Comment by aloki** [comment]
Automatic updates always delayed by 24 hours to make sure there aren’t any pressing issues before seeding to everyone. Just wait or install update manually.

**Comment by MrAlex94** [comment]
Sorry about that. I haven't released the automatic update yet as just wanted to test it some more due to Mozilla changing the updater a bit. Planning to today 🙂

**Comment by Scrxtchy** [comment]
Looks like it has rolled out
