### ISSUE TITLE
Update to Firefox 52.0.1 reverts SelfSupportBackend patch

### ISSUE THREAD

**Issue by PandaCodex** [BrowserWorks/waterfox#126]
Hello, @MrAlex94 

Commit  [Update to Firefox 52.0. Fix various small issues such as Netflix, about:home. Enabled various HTML5 features.](https://github.com/MrAlex94/Waterfox/commit/57a3535b6e0a7aa9871874c0e2d6070cd67aac83) reverted the following patch [Delete SelfSupportBackend](https://github.com/MrAlex94/Waterfox/pull/108)

Have you thought about cleaner commits looking at history you have many changes for many things bundled into a single messy commit. Making single clean commits helps for easier git readability for coming contributors and helps narrow down problematic changes, where if nice clean single patch commits simply revert that change where currently reverting that change would affect multiple changes. This intern makes for a chaos like git repository. Look how clean Mozilla repository is maybe take notes for improvements for Waterfox.

**Comment by MrAlex94** [comment]
Hi Panda, 

I do agree that this repo is a mess and has been for a while. I do have a cleaner repo with all the changes in patches that I'm going to replace this branch with. 

As for the SelfSupportBackend, the commit only added back the files. They aren't used at build time as you can see [here](https://github.com/MrAlex94/Waterfox/blob/master/browser/modules/moz.build) and [here](https://github.com/MrAlex94/Waterfox/blob/master/browser/components/moz.build).

Anyway in the coming weeks I'll be making sure to clean up this repo.
