### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [BrowserWorks/waterfox#127]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

Please let me know if you are interested and would like me to generate an AppImage.

**Comment by MrAlex94** [comment]
Ah thanks for bringing this to my attention! This will help a lot with Linux releases. I'll read up on the docs and make some test images, but definitely looks like it'll be better than just the pre-built binaries archived.

**Comment by probonopd** [comment]
You can use the existing pre-built binaries and convert them into an AppImage; in fact this is what I do for my demo Firefox AppImage. See https://github.com/probonopd/AppImages/blob/master/recipes/meta/Firefox.yml

If you are interested, I can do the same for Waterfox.

**Comment by MrAlex94** [comment]
Yes that would be awesome if you could!

**Comment by probonopd** [comment]
If memory serves me right, @TheAssassin was recently working on the Firefox yml file, so maybe he could have a look here?

**Comment by TheAssassin** [comment]
I have created an AppImage YAML definition for Waterfox.

Wasn't too much work as I was working on basically the same definition for Firefox Developer Edition anyway, so I was able to adopt most of that script's code.

You could further use this as a base for upstream AppImages (e.g. nightlies or continuous integration builds). You could upload the result to your website for future releases, too.

If you have further questions or need assistance in adjusting the definition, join #AppImage on Freenode or on Gitter, there should be someone around who can help you (if not, just stay around a few... hours... or days... it's IRC, so you never know).

**Comment by MrAlex94** [comment]
Great, thanks a lot!

**Comment by Serkan-devel** [comment]
Any updates here?

**Comment by Serkan-devel** [comment]
bump

**Comment by Serkan-devel** [comment]
...

**Comment by Serkan-devel** [comment]
Maybe this could help against https://github.com/MrAlex94/Waterfox/issues/318 and https://github.com/MrAlex94/Waterfox/issues/395 by just swapping appimages out or with appimage-update

**Comment by TheAssassin** [comment]
@Serkan-devel you could think about integrating libappimageupdate into the update check. It provides a C++ interface which you can use to check for updates, perform updates, ...

**Comment by ghost** [comment]
Is appimage available for waterfox? where can I download the file?

**Comment by Serkan-devel** [comment]
Doesn't exist yet, but I'm looking into it

**Comment by hawkeye116477** [comment]
It's here now => `https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/Waterfox-latest-x86_64.AppImage`. It has bad version number, cuz I don't know how to change that on OBS. If i make that locally with recipe method, then version is correct.

**Comment by Serkan-devel** [comment]
can this be upstreamed?

**Comment by grahamperrin** [comment]
> can this be upstreamed?

To where? Somewhere other than AppImageHub?

**Comment by probonopd** [comment]
https://www.waterfoxproject.org/en-US/waterfox/new/?scene=1

**Comment by Serkan-devel** [comment]
@probonopd can't find it on there

**Comment by probonopd** [comment]
Exactly, it _should_ be upstreamed to be there...

**Comment by grahamperrin** [comment]
https://appimage.github.io/apps/#/Waterfox/

- thanks @probonopd @hawkeye116477 

https://redd.it/9rsvcm

**Comment by Serkan-devel** [comment]
@grahamperrin but what about on the official waterfox download page?

**Comment by grahamperrin** [comment]
I'm not a site editor.

**Comment by probonopd** [comment]
@MrAlex94 now that there is a Waterfox AppImage, it would be nice to see it included on the Waterfox homepage.

https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/Waterfox-latest-x86_64.AppImage.mirrorlist

Typing this from Waterfox on Clear Linux OS (an operating system for which no distribution-provided Waterfox package exists).

![](https://user-images.githubusercontent.com/2480569/49338165-28dbb180-f616-11e8-9da2-16d6788dbc77.png)

**Comment by hook321** [comment]
If the appimage is linked to on the official website I think the debian packages should be as well.

**Comment by c-s-n** [comment]
I'm piggybacking on this "packaging" topic, since I stumbled upon the seemingly new Snap *waterfox-snap* [in the Snapcraft Store](https://snapcraft.io/waterfox-snap). That seems to be provided by @YamiYukiSenpai [via this repository](https://github.com/YamiYukiSenpai/waterfox-snap).
Since that Snap doesn't feel very official yet, and there are still many open tasks listed in the repo readme, maybe forces can be joined here?

For reference, [here is also a Waterfox-packaging related reddit discussion](https://www.reddit.com/r/waterfox/comments/6vqjww/snap_package_for_waterfox_for_linux/).

**Comment by Serkan-devel** [comment]
@c-s-n please open a seperate issue and not clutter this one

**Comment by grahamperrin** [comment]
▶ [Any thoughts of having a Snap version of Waterfox?](https://www.reddit.com/r/waterfox/comments/ce7fnr/any_thoughts_of_having_a_snap_version_of_waterfox/)

**Comment by probonopd** [comment]
@grahamperrin please open a seperate issue and not clutter this one

**Comment by grahamperrin** [comment]
@probonopd it was direction to the separate discussion; to avoid duplication/multiplication.

**Comment by ghost** [comment]
https://github.com/MrAlex94/Waterfox/issues/1752

**Comment by chaserene** [comment]
@MrAlex94 please reopen this. Waterfox still doesn't have an official AppImage, only a 3rd party build.

**Comment by hawkeye116477** [comment]
I assume that's closed, cuz no one from Waterfox team has time to do that and/or learn how to do that.

**Comment by donPabloNow** [comment]
@probonopd Likewise, with the release of Hawkeye's Appimage package for Waterfox (https://github.com/hawkeye116477/install-waterfox-linux), which is accessible through Opensuse (https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/waterfox-classic-latest-x86_64.AppImage.mirrorlist), it is now feasible to run Waterfox on Intel's ClearLinux* v3k+ operating system . This is only one of the possible distributions available through various platforms.
