### ISSUE TITLE
Isolate the Waterfox profil to another location

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#130]
Hello,

one suggestion, you should one day create these folders (like below) :

```
C:\Users\WagnerGMD\AppData\Local\WaterFox
C:\Users\WagnerGMD\AppData\Roaming\WaterFox
## If you need one example, CyberFox (or PaleMoon) is a good one.
```
Because I had just install WaterFox and no, I don't want to use the same profil (for each programs like Firefox-Stable_v52, Firefox-Nightly_v54 and WaterFox_v52). You should isolate the profil to avoid mistake or confusion.
It would be easier to clean because sometimes there's something wrong inside the profil (damaged, corrupted, strange bug, etc)

Kind regards.

**Comment by darkmoon2** [comment]
I agree that the profile should be in a separate folder, especially since Firefox now releases a 64-bit build of their application as well, it would be nice to be able to open them side by side which you cannot do because of the shared profile location.

**Comment by WagnerGMD** [comment]
A few months ago, I had discover one solution could be to use the **WaterFox portable**. And it was mentionned (the same subject) on a reddit topic(s [one example](https://www.reddit.com/r/waterfox/comments/5vrimx/waterfox_profile_folder/)).
But I believe the people would rather this : "give us the choice" (for that just add a checkbox (enable by default) inside the Waterfox installer).

You need to clarify it; describe the difference (like performance, trouble, etc) between them (the portable and installer). Because it's seem you don't have a FAQ (or I didn't find it)...

**Comment by WagnerGMD** [comment]
> From now I'll be keeping a separate directory no matter what, it has caused too many issues in the past unfortunately. I'll keep the import option available of course (and try to improve it!).

Good news, it was introduced in the latest (Waterfox_v55).

**PS :** You can check this [reddit topic](https://www.reddit.com/r/waterfox/comments/6trq5j/test_out_waterfox_55_here_please_read_full/) and [this one](https://www.reddit.com/r/waterfox/comments/6xm233/waterfox_sync_and_waterfox_account/) too.
It would be also a nice improvement for the [Nightly.](https://blog.nightly.mozilla.org/)
