### ISSUE TITLE
Install script and desktop icon?

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#131]
Since the official instructions for installing Waterfox (such that you'll be able to update without elevating the browser to root) on most distros is just to drop it somewhere in your home directory, and make symlinks, I think it'd be a good idea to include a simple bash install script for integrating it better into your system. I wrote one such script for it here:

`#!/usr/bin/env bash`
`ln -sf $(pwd)/waterfox-bin /usr/bin/waterfox`
`ln -sf $(pwd)/browser/icons/mozicon128.png /usr/share/icons/waterfox.png`
`ln -sf $(pwd)/waterfox.desktop /usr/share/applications/waterfox.desktop`

All it would require is symlinking into various locations, and including a waterfox.desktop file. I've already written that too for my personal use:
http://pastebin.com/XNnaUysU

Doubtlessly my solutions aren't perfect, but some variation of these would make Waterfox installation a LOT easier, especially for relative noobies who don't know how to install stuff that isn't in their package system.

BTW, feel free to use the code I've shown here if it suits your purposes, as it's public domain. :)

**Comment by MrAlex94** [comment]
Thanks, with the new website will come better documentation as well, so this will help.
