### ISSUE TITLE
Responsive Design Mode

### ISSUE THREAD

**Issue by UltimHate** [BrowserWorks/waterfox#132]
Hi there !
My latest version Waterfox 52.0.1 (64 bits) is still displaying the earlier version of the Responsive Design Mode (before Firefox 52). Is it normal ?

**Comment by MrAlex94** [comment]
@UltimHate, could you expand a bit more on what you mean?

**Comment by MrAlex94** [comment]
There hasn't been a response in a while, please re-open if you would like.
