### ISSUE TITLE
edit bookmark save button greyed out but does work

### ISSUE THREAD

**Issue by dmaclip** [BrowserWorks/waterfox#135]
the save is always (as far as I can see) greyed out however its functionality does work for me
![capture](https://cloud.githubusercontent.com/assets/20878066/24413136/8cc8a452-13a8-11e7-8c94-984767f8f362.png)

**Comment by dmaclip** [comment]
looks like ALL ok and save buttons throughout act like this

**Comment by MrAlex94** [comment]
Looks like a graphics issue, @dmaclip please re-open if this still occurs.
