### ISSUE TITLE
ssl_error_access_denied_alert after updating to 52.0.1 on Mac Sierra

### ISSUE THREAD

**Issue by bvasilchik** [BrowserWorks/waterfox#136]
I just updated to 52.0.1 (64-bit) on mac with Sierra OS and for some reason gmail and the waterfox site were both giving me this error SSL_ERROR_ACCESS_DENIED_ALERT but when I opened regular firefox they did not. I found a workaround via this [article](https://community.spiceworks.com/how_to/119513-resolving-ssl_error_access_denied_alert-in-firefox) and now it works. I wasn't sure why updating caused this issue to happen

**Comment by MrAlex94** [comment]
This should be remedied now, please re-open if it still occurs.
