### ISSUE TITLE
Embedded Media using JWPlayer cannot enter fullscreen mode when viewed in waterfox 

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#139]
There appears to be an issue with websites using JWPlayer where the player will not properly enter fullscreen mode in waterfox. It appears to be an issue unique to waterfox as i was unable to replicate this on the other browsers I tested which include Internet Explorer, Opera, Chrome and the most recent build of Mozilla Firefox 

I did the usual procedure of clearing cache and cookies and restarting the browser to confirm that the issue was in the browser and not the cached data. Additionally I tested the issue both on the website where I encountered it as well as on JW Players own test page so Confirming its an issue with the player and not just the website layout 

Demonstrations of the issue can be found here 
https://www.youtube.com/watch?v=N_9BTDVbbuM&feature=youtu.be
https://www.youtube.com/watch?v=9BW2REN3yMc&feature=youtu.be

**Comment by MrAlex94** [comment]
Can you repro in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode)?

**Comment by MrAlex94** [comment]
Just a FYI, I haven't been able to reproduce this, so will close. Please re-open if it still occurs.
