### ISSUE TITLE
Reuses Firefox Profile(s)

### ISSUE THREAD

**Issue by paulrrogers** [BrowserWorks/waterfox#14]
This complicates running alongside Firefox. Please use a new profile folder as Palemoon and other forks do.

**Comment by MrAlex94** [comment]
You can set Waterox to use a different profile with -p -no-remote on its shortcut.

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
http://kb.mozillazine.org/Command_line_arguments

**Comment by paulrrogers** [comment]
Thanks, but I was aware of--and using--that workaround. It strikes me as a bit of a hack since the program is otherwise entirely separate from the official Firefox. For example, it is a separate program in Windows' Programs listing.
