### ISSUE TITLE
Feature: Add ipfs protocol support

### ISSUE THREAD

**Issue by raspher** [BrowserWorks/waterfox#140]
https://ipfs.io/
development currently in alpha, but anyway its WORKING alpha. its more fast than http.

here you have an experimental project https://github.com/beakerbrowser/beaker

**Comment by MrAlex94** [comment]
Mozilla are keeping an [eye](https://bugzilla.mozilla.org/show_bug.cgi?id=1354807#c2) on it, as am I. When it matures a bit more, it'll be worth looking into for sure.

**Comment by wuniversales** [comment]
Beaker uses the dat protocol, ipfs is another protocol ...
It would also be good to have support for both.

**Comment by MrAlex94** [comment]
Available with [ipfs companion](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/).
