### ISSUE TITLE
Make an android browser of waterfox like the mozilla version

### ISSUE THREAD

**Issue by Serkan-devel** [BrowserWorks/waterfox#143]
While I see there is a waterfox app on the playstore but it is very slow compared to the <a href="https://play.google.com/store/apps/details?id=org.mozilla.firefox">mozilla version</a> of it.

Are there any plans for making a fork of the firefox-for-android project?

**Comment by MrAlex94** [comment]
I may do so in the future, would seem like a good path to take Waterfox.

**Comment by MrAlex94** [comment]
This will be released shortly, anything specific you'd like to see in the Android release?

**Comment by dimqua** [comment]
As much changes from desktop version as possible.

**Comment by Serkan-devel** [comment]
Maybe a slight blue tint in the background surrounding the tabs.

**Comment by Serkan-devel** [comment]
Or instead of a slight blue tint it could reflect the color of the website icon or something like on mobile google chrome

**Comment by Serkan-devel** [comment]
And maybe release it on the F-droid store please..

**Comment by hockeymikey** [comment]
Ideally I would love if it had a similar level of customization as the desktop version.  I don't care for Firefox on Android much due mainly to the UI so ability to customize would be great.  Give the ability for the user to change more settings and features around to make the browser how they most like it.
Even something simple like a userChrome.css to modify the UI would be a great start.  I don't think this would be too tricky, there are many methods for altering views.  Hardest part would be ensuring good performance and that the modifications aren't discarded with say a screen rotate.  Maybe some sort of cached version of the layouts would be able to facilitate this but that's just a theory off the top of my head.
Released on F-Droid would be awesome.

**Comment by Serkan-devel** [comment]
Maybe view/delete individual cookies

**Comment by Serkan-devel** [comment]
https://gitlab.com/fdroid/rfp/issues/373 When will it be submitted to f-droid,

**Comment by MrAlex94** [comment]
Thanks for the suggestions. Need to work a bit more on the Android version, it’s not so great at the moment.

**Comment by grahamperrin** [comment]
[Waterfox Focus Android version please! · Issue #355 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/355)

**Comment by D0ve** [comment]
It would be great if possible to port Desktop version fully to Android !!!

But if only modifying existent android version in plans, would like to suggest 'switching UI modes' or splitting them for elements to switch on/off :
https://github.com/MrAlex94/Waterfox/issues/359
This helps using tabs or more ui elements on smaller screen devices.

**Comment by MrAlex94** [comment]
@D0ve, Firefox for Android used to be XUL based, but unfortunately the UX was not very good and was resource heavy, so Mozilla switched to using the native UI.

Things have changed on the smartphone landscape in terms of computing power - but I image the resources necessary to get a XUL based browser on mobile will be quite tough again.

**Comment by Serkan-devel** [comment]
Ironically the newer Firefox for Android versions look more awful and lags even more than the XUL-versions

**Comment by D0ve** [comment]
@MrAlex94 Wow!  Usual FF UI on Android,-really the greatest browser!!!
Because now - it's exist a big lack of ui elements in ANY Android browser(with their using native ui), they're just poor of elements and possibilities(((.
It will be one and only best browser for Android!!!

**Comment by D0ve** [comment]
@MrAlex94   Might be that futured GreatFullUI android version should take implementation of UI scale future (for supporting various display resolution '"out-of-the-box").
 I think will may take the extension smth. like that(plus needed  'scalling app ui' / 'scaling of icons' support):

https://addons.mozilla.org/en-US/firefox/addon/theme-font-size-changer/

**Comment by benryanau** [comment]
Latest release 55.2 rather far behind other platforms.. think it shows by the crashes and mem iasuea..

**Comment by AjvarXX** [comment]
The problem is that when you click Menu-Bookmarks or History then aforementioned pages are opened on behalf of current page instead of being opened in the new tab. Waterfox for Android.

Also yeah, crashes sometimes.

**Comment by Serkan-devel** [comment]
Now that it's released on the playstore, when will the f-droid version follow? There are foss f-droid builds of firefox already named "fennec". Using their source as reference could help for including ti into f-droid. 

People with customs roms, region locks, etc. can't and/or don't want to use the proprietary playstore as package manager

**Comment by D0ve** [comment]
@Serkan-devel 
builds are planned in 'releases' section here ...

**Comment by Serkan-devel** [comment]
@D0ve on F-Droid or on the github page?

**Comment by MrAlex94** [comment]
F-Droid is coming once I remove GP integrations.

**Comment by Serkan-devel** [comment]
Can this issue be left open until it's released?

**Comment by D0ve** [comment]
>>> on F-Droid or on the github page? >>>

@Serkan-devel 
Imo logically both places, but firstly on f-droid, because need to get f-droid sign for android build;
but after on github too, because github place will include either other platform versions and non public release versions  like betas, rc's , test's , etc.
Am I right , Alex ;) ?

**Comment by D0ve** [comment]
@MrAlex94 and if possible, please, before close this issue take a look on this one https://github.com/MrAlex94/Waterfox/issues/359
I dunno exactly 3 or 2 android modes of ui interface type is hardcoded in it,
but apk somehow decides which one needed to switch 'on':
for tablet , for phablet or for smartphone (or only tablet and smartphone ).
Could you please investigate a little, is it possible just put thats apk decisions to about:config switch?
(btw this about:config switch could be happily used in a future to switch to another new desktop's xul interface on android for testing and/or using)

**Comment by Serkan-devel** [comment]
When will Waterfox be on F-Droid?

**Comment by D0ve** [comment]
@Serkan-devel 
I'm awaiting either, hope asap ;)

**Comment by MrAlex94** [comment]
The patches have all been applied so I just need to patch and ship :-)

**Comment by DI555** [comment]
May be shoudn't close this issue ? ..., it's about inner Waterfox interface-more powerful , not 
like native android...like now.

Btw, the link:
https://staging.f-droid.org/search?q=Waterfox&lang=en
is my favorite this summer ;) !!! Because google.play injects in their apks spyware((( !!!

**Comment by Serkan-devel** [comment]
When will it be shipped?

**Comment by Ibuprophen** [comment]
@DI555, there's no search results on F-Droid with the name Waterfox... 


~Ibuprophen

**Comment by MrAlex94** [comment]
I actually am still building the code base with all these new changes.
Removing the GPE integrations is chaos, but getting there!

**Comment by Serkan-devel** [comment]
@MrAlex94 any updates on this?

**Comment by Ibuprophen** [comment]
@Serkan-devel, it looks like you have an Android device that's ARM 32-bit. The Only version of the Waterfox app that's compatible with the Architecture for this device is the Beta version of the app and this is a bit tricky for seeing on the Play Store. 

Please see the following post that reflects the 2 ways for obtaining this for your Android device. 

https://github.com/MrAlex94/Waterfox/issues/730#issuecomment-421647220

Good Luck! :-) 


~Ibuprophen

**Comment by Serkan-devel** [comment]
@ibuprophen1 but I also have an S6. And I'm rather waiting for a GP-free version but thanks

**Comment by IzzySoft** [comment]
@MrAlex94 any ETA for the GCM free mobile version? At F-Droid we're waiting to process [this request](https://gitlab.com/fdroid/rfp/issues/373) to include Waterfox. Using Waterfox on all my PCs and Laptops, I'd especially welcome it there 😉

**Comment by DI555** [comment]
@MrAlex94 , while we're waiting f-droid's version, could it be possible to place all the builds here on github in 'releases' (or here but in another repository especially for that), please! 
You promissed;)?

**Comment by DI555** [comment]
@MrAlex94 , seems mozilla plans to drop fennec (((   ... and targeting on focus with geckoView....
Alex, could it be easier now to build full desktop FF version for android?
It will be great leap forward for mobile browser!!!

**Comment by Serkan-devel** [comment]
Maybe one could builld mobile versions of waterfox vased on fennec. F-droid has put some effort to free it from proprietary binaries so

**Comment by IzzySoft** [comment]
@MrAlex94 more than a year ago, you wrote:

> F-Droid is coming once I remove GP integrations.

How far has that progressed? I don't want to press, I ask because I'm triaging "old issues" on our end (F-Droid), and again came to the one asking to [package Waterfox](https://gitlab.com/fdroid/rfp/issues/373). Being a happy Waterfox user on Desktop, I'd really like to see that happen 😃

**Comment by IzzySoft** [comment]
1.5 years later, 3rd triage run since my last post, RFP still sits waiting. Do we have a chance? Or do we need to :cry: and close that RFP as "unsolvable"? That would be a real pity.

**Comment by IzzySoft** [comment]
Sad, but we had to close the request. Should WF finally be ready for F-Droid, just give us a ping and we gladly assist.
