### ISSUE TITLE
Windows vista x64 and waterfox (Not a valid Win32 Application)

### ISSUE THREAD

**Issue by PandaCodex** [BrowserWorks/waterfox#144]
Waterfox 52.0 would not install with installer on windows vista showing following message 

`Sorry, Waterfox can't be installed. This version of Waterfox requires SSE2 or newer and a processor with SSE2 support. Please click the OK button for additional information.`

Waterfox 52.0.2 if extracted from installer using 7zip still runs fine, Mozilla Firefox 52.0 branch installers shows a different error preventing installations on windows vista

`Sorry, Firefox can't be installed. This version of Firefox requires windows 7 or newer. Please click the OK button for additional information.`

For current windows vista users, they were still able with updater to install 52.0 branch, just not able too with your installer, with the release of Waterfox 53.0 same error message shows on installation but if you extract Waterfox then run it you get following error type.

`Not a valid Win32 Application`

This means windows vista users can no longer run Waterfox on there systems but main issue is when using updater it downloads then installs latest Waterfox update like normal without issue but it never opens back up after update showing above error when trying to start it.

Now not sure how large your windows vista user-base is but this could have been handled better, with Firefox they detected OS then changed users to Firefox ESR channel allowing them to keep using Firefox without issue or downtime where as with Waterfox they are left with an error message and a browser they can't use.

If you dropped windows vista support, should you make a post/thread somewhere letting users know, do you still support windows xp as Waterfox has not worked on that OS for many many versions.

**Comment by avsaponchik** [comment]
/* offtopic
Why do someone in 2k17 needs Vista? I can even understand the need of XP because some of DOS programs won't work properly under NTVDM...

But vista?
*/ offtopic

**Comment by RandomGuyDTB** [comment]
Waterfox is a 64-bit app, I think the problem is that you're trying to run it on 32-bit Windows. I have no clue why you'd wanna use Vista, but you can still get Windows 10 for free using the Windows Media Creation Tool (https://www.microsoft.com/en-us/software-download/windows10ISO) if you wanna update.

**Comment by grahamperrin** [comment]
A few months ago, https://www.waterfoxproject.org/downloads began stating a requirement for _Windows 7 64-Bit or later_.

> … Waterfox 52.0.2 if extracted from installer using 7zip still runs fine, …

I wondered whether 52.0.2 would run on 32-bit Windows 7 Enterprise, it doesn't: 

![2018-01-13 02 51 56](https://user-images.githubusercontent.com/192271/34908975-34b744de-f891-11e7-9bea-fa2e9bf90a73.png)

![2018-01-13 03 03 34](https://user-images.githubusercontent.com/192271/34908978-3dc69a52-f891-11e7-9bc0-c250c349e3e1.png)

**Comment by PandaCodex** [comment]
This issue was Waterfox x64bit on Windows Vista x64, has nothing to do with a x86 operating system

**Comment by grahamperrin** [comment]
Thanks for clarifying (I was testing based on [the 32-bit supposition](https://github.com/MrAlex94/Waterfox/issues/144#issuecomment-305193242)). I'll delete my comment.

**Comment by mirh** [comment]
> Not a valid Win32 Application

If you are getting that, even if you have the right architecture, then it means somebody has tinkered with linker settings (making the executable require this or that windows version). 
AFAIK people reports waterfox 53 to work on Vista.. Is this still a thing?

**Comment by freedom7341** [comment]
Same issue here. Only way to even get "close" to installing it is by extracting it, then once installation is over, the error in the image happens.
![error](https://user-images.githubusercontent.com/36094486/35762908-71d2017a-085d-11e8-86a4-91e0b42c67f9.PNG)
EDIT: OS is Windows Vista Ultimate SP2.

**Comment by grahamperrin** [comment]
> # … Vista …

https://www.waterfoxproject.org/downloads states: 

>> Windows 7 64-Bit or later 

That requirement appeared some time between [April 2017](https://archive.is/lB8yl) and [August 2017](https://web.archive.org/web/20170818114712/https://www.waterfoxproject.org/downloads). 

Side note: [April 2017](https://web.archive.org/web/20170424103703/https://www.waterfoxproject.org/) was also the last Wayback Machine capture of a home page mention of support for XP. 

----

From [Windows Vista 64-bit & Waterfox 54 issue: TryAquireSRWLockExclusive could not be located in the Dynamic Link Library KERNEL32.DLL · Issue #166 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/166) (2017-06-19): 

>> … list Waterfox 53.0.3 as the final release for Vista.
>> 
>> Last versions of software for Vista/2008: http://www.msfn.org/board/topic/175262-last-versions-of-software-for-windows-vista-and-windows-server-2008 …

> … provisionally put 53.0.3 on that list. …

Linked from that list: [Off-Topic: @ROYTAM1: Restoring XP and Vista support to Waterfox 56?](http://kmeleonbrowser.org/forum/read.php?19,144023) (2017-12-20) and linked from that topic: 

- [Remove rust requirement? · Issue #321 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/321)

> … weigh the cost–benefit of reverting the patches that affect XP/Vista support. …
