### ISSUE TITLE
Waterfox feature desception

### ISSUE THREAD

**Issue by PandaCodex** [BrowserWorks/waterfox#145]
Recently encountered a user who claims your statements of Waterfox features are deceptive on the part where you claim removal of a feature but is only preference disabled.

`Removal of Sponsored Tiles on New Tab Page`

The user states it should say disabled by preference not removal under fact they mean different things that its deceptive in regards to fact tiles still show in there Waterfox instance when sharing a Firefox profile.

If above feature was removed tiles would not show in Waterfox. Tried to explain to user but they were adamant your deceiving you're user base so this issue is to clarify it.

**Comment by PandaCodex** [comment]
Any update on this ??

**Comment by MrAlex94** [comment]
Yes, I'll be removing the code properly in 54.0 🙂
