### ISSUE TITLE
about:addons inaccessible (Waterfox Crash) when [NoScript Security Suite] installed

### ISSUE THREAD

**Issue by PandaCodex** [BrowserWorks/waterfox#146]
Currently from last versions of Waterfox about:addons "Get addons" page inaccessible with a browser hang and crash when popular security addon suite [NoScript Security Suite](https://addons.mozilla.org/en-US/firefox/addon/noscript/) is installed, this issue doesn't happen in Firefox.

No longer can open about:addons had to start in safe mode then remove NoScript, CPU usage spikes
very high with large memory usage sometimes.

**Comment by MrAlex94** [comment]
I feel it may be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1320571. I'll contact the NoScript developer directly and ask if I can help see what's wrong in regards to Waterfox (or 3rd party builds not from Mozilla in general it seems?).

**Comment by PandaCodex** [comment]
Any update on this, still crashes

**Comment by Greveyaro** [comment]
Yes I can confirm still crashes when opening addons with NoScript installed.
