### ISSUE TITLE
Wrong site's language in Waterfox?

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#147]
I'm from Poland and recently switched on Win 8.1 computer Firefox to Waterfox 53. From that time web sites started do set their languages by default to English. Locale is set to Polish and there wasn't any problem like that in Firefox Polish version. There isn't any language versions of Waterfox, only English where I can set locale to Polish, so maybe that's the problem. Is there a way to fix that? Maybe a setting or something?

**Comment by MrAlex94** [comment]
You should be able to change your locale in Preferences > General > Locale Drop Down box.

I added it as part of Waterfox to make selecting language easier 🙂

**Comment by maxoku** [comment]
Locale is already changed to Polish, but sites still set English by default^^.

**Comment by hawkeye116477** [comment]
@maxoku Wejdź w opcje-treść-języki-wybierz, a potem zaznacz i skasuj polski, a następnie wybierz polski i dodaj ponownie. To powinno pomóc 🙂.
Go into options-content-languages-choose, then select and remove Polish and then choose Polish and add it again. This should help you 🙂.

**Comment by MrAlex94** [comment]
Has been fixed in an update.
