### ISSUE TITLE
Odd white box in upper left of screen

### ISSUE THREAD

**Issue by llloyd4** [BrowserWorks/waterfox#148]
Hello! This is Waterfox 52.0.1 on Windows 10 x64. Right, so, on running this I see a strange white box in the upper left corner of the window - https://gyazo.com/b307388364ee8acdbe92fd5478cb31c7 - but if I close Fraps it goes away. I restart Fraps it returns. So something between Fraps and Waterfox is breaking. O.o

**Comment by MrAlex94** [comment]
@llloyd4  still occur?

**Comment by MrAlex94** [comment]
Please re-open if you have any more information.
