### ISSUE TITLE
Facebook video calling?

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#149]
Is it possible to use video chat on Facebook (and others) using Waterfox or not? The main issue is that the camera doesn't work. I can see a person with which I'm chatting but that person can't see me, as also I can't see myself on preview in bottom right. It seems that even when I gave permission for camera and microphone they are still being blocked.

**Comment by MrAlex94** [comment]
I can't repro this, does this occur in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode)?

**Comment by MrAlex94** [comment]
Please re-open if you have any more information.

**Comment by maxoku** [comment]
It's fixed.
