### ISSUE TITLE
The close/minimise/maximise buttons for a waterfox window do not work on Windows 10 as of 40.0.2

### ISSUE THREAD

**Issue by SwadicalRag** [BrowserWorks/waterfox#15]
I have tried disabling all addons I had installed just to check if it was an addon-related issue, but it is not the case.

(also, semi related issue: the Windows 10 window control buttons are larger than that of older versions of Windows, so if too many tabs are open on waterfox, the last opened tab expands into the "hitbox" of the minimise button.)
![Image](http://i.imgur.com/foNZBrm.png)

**Comment by Random1984** [comment]
Does the issue solve setting an old-style windows theme? (Just curiosity)

**Comment by SwadicalRag** [comment]
If you meant setting Windows' theme to a high-contrast one, then nope, that doesn't solve the issue.

**Comment by Random1984** [comment]
So I understand the problem isn't in the compatibility with Windows 10 themes, it looks like Waterfox should implement another buttons style.
Thanks a lot!

**Comment by MrAlex94** [comment]
I'll look into this properly tomorrow for you.

**Comment by SwadicalRag** [comment]
Thank you

**Comment by SwadicalRag** [comment]
Just an update: the issue still persists on 40.1.0
