### ISSUE TITLE
Add-On blocked

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#153]
Waterfox 53.0.1 for Mac is blocking my attempts to download the Add-on [PrivacyBadger](https://www.eff.org/privacybadger), in spite of the fact that the security preferences "Warn you when sites try to install add-ons" and "Block dangerous and deceptive content" are unchecked.

**Comment by grahamperrin** [comment]
Privacy Badger 2017.11.20 added without difficulty to Waterfox 56.0 on Mac OS X 10.9.5.

**Comment by grahamperrin** [comment]
@MrAlex94 would you like to close this issue?
