### ISSUE TITLE
Does Waterfox support DDE?

### ISSUE THREAD

**Issue by raelb** [BrowserWorks/waterfox#154]
Hello,

Firefox supports DDE. To connect to the browser code will look something like this:

`SetLink(Browser, 'WWW_GetWindowInfo')`

For Firefox the browser name = `firefox`.

Palemoon also supports DDE. In that case browser name = `Pale Moon`.

I could not get DDE to work with Waterfox when using the string `waterfox`.

Is it not supported?

Thanks

**Comment by grahamperrin** [comment]
#538

**Comment by MrAlex94** [comment]
This is now fixed, i.e Waterfox Current is now `waterfox-current` for the browser name.
