### ISSUE TITLE
Water fox portables works only one time whenever installed first, than refuse to start with a notices.

### ISSUE THREAD

**Issue by spamkutu** [BrowserWorks/waterfox#156]
I use windows 8 turkish (non service packed, just 8 with all updates)  and its message me this. (Waterfox 53.0.3 Portable 3-5 lower versions also do the some )

"The update could not be installed. Please make sure there are no other copies of Waterfox running on your computer, and then restart Waterfox to try again."

than got this message and stop working after installer launch no waterfox dont work.

"Waterfox, Portable Edition cannot be started. You may wish to re-install to fix this issue. (ERROR: waterfox.exe could not be found)"

**Comment by MrAlex94** [comment]
This sounds like a broken update. If this has happened since then, please let me know.
