### ISSUE TITLE
Does not use system certificate store?

### ISSUE THREAD

**Issue by bgstack15** [BrowserWorks/waterfox#158]
Latest Linux build: 53.0.3 (64-bit)
Korora 25 xfce
Trusted certificate for the freeipa domain is not listed in the Waterfox certificate store.
Firefox 53.0.2 (64-bit) reads the system certificate store with the root ca installed for the freeipa domain.
The certificate is listed in these possible files or directories for the system store:
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
/etc/pki/nssdb/
/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

**Comment by MrAlex94** [comment]
Can be toggled with `security.enterprise_roots.enabled` in `about:config`.
