### ISSUE TITLE
Crashing xul.dll

### ISSUE THREAD

**Issue by ElPoonPoon** [BrowserWorks/waterfox#159]
Every now and then I have Waterfox crash and it blanks out the tab I was using at the time. It has so far always been in the middle of filling out a form, such as an online order form with Address lines etc.
Closing and re-opening Waterfox and trying to use the same tab again seems to always have it crash when I start filling out any of the form lines again. The only fix is to close the offending tab and start again, which isn't a guaranteed fix. Every time it has happened I have had multiple tabs open, not sure if that's a factor.
![waterfox crash](https://user-images.githubusercontent.com/28710669/26881138-e5cb1daa-4bd9-11e7-8e04-99859aea9470.png)

**Comment by MrAlex94** [comment]
@ElPoonPoon,

- Does this occur in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode)?

**Comment by IS4Code** [comment]
Yes.

**Comment by MelchiorGaspar** [comment]
I have this issue was well, XUL.DLL, frequent but intermittent crashing...
I will start my own top to list what I have seen...

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/793#issuecomment-439253264 for the MelchiorGaspar case.
