### ISSUE TITLE
Ghost of FF crashed of first install

### ISSUE THREAD

**Issue by JWvanLohuizen** [BrowserWorks/waterfox#16]
The new ugly  version with the ghost of FF icon crash in 1st load for the first time ever with using WF.It crash 4 or 5 times the first 3 days of using it. Now it hasn't been able to load web web pages for 4 days.

I downgraded to WF 39 but no joy.  Changed profiles and it crashed again.  What did you do kill waterfox????

Thank God for chrome.

**Comment by JWvanLohuizen** [comment]
FF using the same profile has no issues!!!

**Comment by MrAlex94** [comment]
Something doesn't seem right that going back to 39 doesn't work if it worked before and nothing in the profile has changed. Could you try an [empty profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and see if this still happens?

**Comment by JWvanLohuizen** [comment]
Testing further FF does load pages just not quickly.

FF 64bit now in beta

**Comment by JWvanLohuizen** [comment]
Back to WF nothing

**Comment by JWvanLohuizen** [comment]
It also has to be forced closed.each time I forgot to mention

**Comment by JWvanLohuizen** [comment]
or it will crash after a minute or so

**Comment by MrAlex94** [comment]
Is this on an empty profile? Also could I get a list of your system specs?

**Comment by JWvanLohuizen** [comment]
I'm telling you you've jinked it with the ghost off icon and the horrible new look.

Your smoking the same Windows "-10" weed pipe

**Comment by MrAlex94** [comment]
Looks like you don't want my help to try and resolve the issue. Issue closed.
