### ISSUE TITLE
Ecosia Search Missing

### ISSUE THREAD

**Issue by ViciousMagician** [BrowserWorks/waterfox#160]
Got used to using this but the last update its gone and even installing their addon doesn't work to get Ecosia search back.  
![image](https://user-images.githubusercontent.com/24388947/26928172-0e05ddca-4c23-11e7-8b66-35b492b96b56.png)

**Comment by grahamperrin** [comment]
Not reproducible with Waterfox 56.0 on FreeBSD-CURRENT. 

@ViciousMagician is this still an issue for you, with Waterfox 56?

**Comment by MrAlex94** [comment]
If you have the Ecosia extension installed as well, it will remove Ecosia from the search engine list. Remove the Ecosia extension, then go to the website and [re-add the search](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_add-a-search-engine).

Please re-open if you still have issues.
