### ISSUE TITLE
-profilemanager commandline parameter opens new window

### ISSUE THREAD

**Issue by BGMcoder** [BrowserWorks/waterfox#161]
When I run `waterfox.exe -profilemanager` (wfx64 version 53.0.3 on Windows 7x64) a new window opens instead of the Profile Manager.  I can get to the Profile Manager window using the ProfileSwitcher addon and so I even unchecked the option for "Use the selected profile without asking at startup" and the commandline parameter still doesn't work.

Am I doing something wrong or is it just not working?

**Comment by Scrxtchy** [comment]
Is the browser currently open when doing so? 
I use -P without fail, if used without a profile name, it loads the profile switcher. 

Using --no-remote will load another instance of the browser if it's already open, since it will try to use the current active process otherwise

**Comment by MrAlex94** [comment]
Please re-open bug if needed.
