### ISSUE TITLE
Feature Request: Can you bring old search bar style back?

### ISSUE THREAD

**Issue by cdytoby** [BrowserWorks/waterfox#162]
![default](https://user-images.githubusercontent.com/15671368/27041376-1cadf7a8-4f94-11e7-94b5-34ae7cac7343.png)

Like this. In Firefox, it can be done by adding a plugin, here is the link.
https://addons.mozilla.org/zh-CN/firefox/addon/old-search-fixed2/?src=api
But it doesn't work in Waterfox, the search bar will be useless with this plugin.

The new style really slowed my control down.

**Comment by hawkeye116477** [comment]
@cdytoby You can just install Classic Theme Restorer and go to preferences of CTR and enable old search bar.

**Comment by timur-g** [comment]
Duplicate #302.
