### ISSUE TITLE
Windows Vista 64-bit & Waterfox 54 issue: TryAquireSRWLockExclusive could not be located in the Dynamic Link Library KERNEL32.DLL

### ISSUE THREAD

**Issue by WinClient5270** [BrowserWorks/waterfox#166]
Hello everyone. 
I just upgraded my Windows Vista virtual machine from Waterfox 53 to 54, and after doing so, I got the following error message:
The procedure entry point TryAquireSRWLockExclusive could not be located in the Dynamic Link Library KERNEL32.DLL. 
According to the MSDN Library, TryAquireSRWLockExclusive is a Windows 7+ function, so of course when Waterfox looks for this function under Windows Vista, the user is presented with this error. 
Since Waterfox still claims to support Windows Vista, I found it prudent to report this issue so it can either be fixed, or Waterfox can simply drop support for Vista and update the system requirements page to reflect this. 
Now, I'm not trying to be rude, but I'm not interested in hearing "Why would you use Vista in 2017?" nonsense, because I don't use the OS myself (I'm perfectly happy with Windows 8.1, and I mentioned that this is a virtual machine in the first sentence of my post, not a physical computer). I just wanted to make Waterfox developers aware of this issue for the reasons listed above, in addition to the fact that I maintain a list on the MSFN forum called "Last versions of software for Windows Vista and Windows Server 2008" (link at the end of this post for those interested), and if this issue isn't going to get fixed, I will have to remove Waterfox from the list of browsers that actively continue to support Vista, and list Waterfox 53.0.3 as the final release for Vista.
Last versions of software for Vista/2008: http://www.msfn.org/board/topic/175262-last-versions-of-software-for-windows-vista-and-windows-server-2008/
Thanks, 
WinClient5270

**Comment by MrAlex94** [comment]
Hi sorry about that! I'll have a look to see if I can fix it :-)

**Comment by MrAlex94** [comment]
Could you provisionally put 53.0.3 on that list. I'm going to do a fair bit of research for maybe doing a separate release for old systems.

**Comment by WinClient5270** [comment]
Although I don't use Windows Vista anymore, that sounds like an excellent idea, and I hope that it is materialized.
Anyway, I have updated the list to reflect the new information. Thanks for updating the system requirements to prevent any confusion for any Vista users that may seek to install the browser.

**Comment by mirh** [comment]
Found the responsible: https://bugzilla.mozilla.org/show_bug.cgi?id=1331205
It shouldn't be pretty difficult to patch/revert. 

OTOH TryAcquireSRWLockExclusive/TryAcquireSRWLockShared were also introduced [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1331205). 
There doesn't seem to be anything else then.

**Comment by wolfbeast** [comment]
FTR: [slim reader/writer (SRW) locks](https://docs.microsoft.com/en-us/windows/desktop/Sync/slim-reader-writer--srw--locks) are the successor to [CRITICAL_SECTION](https://docs.microsoft.com/en-us/windows/desktop/Sync/critical-section-objects) mutex locks in XP/Vista. They are a little easier to use in code and more performant, but functionally the same as using critical section locks. If you want XP/Vista compatibility, you have to use critical sections everywhere there are now SRW locks. This shouldn't influence any higher level code as long as you properly lock and unlock in the correct places.

**Comment by Squall-Leonhart** [comment]
Kindly leave Vista in the past where it belongs.

**Comment by grahamperrin** [comment]
+1

in that Vista no longer meets the minimum requirements for Waterfox. 

https://web.archive.org/web/20190412134147/https://www.waterfoxproject.org/en-US/waterfox/new/ the mention of XP/Vista _might_ have been a quirk of the period during which Waterfox site content was based on content that was open sourced by Mozilla. 

https://web.archive.org/web/20190420132504/https://www.waterfox.net/releases/ (2019-04-20) the minimum requirement for Windows was: 

> 7 64-Bit

**Comment by wolfbeast** [comment]
Isn't this what I just said? ;-) I'm all for SRW locks, in fact I've converted all of them for UXP quite a while ago and it makes sense for any modern software to do.

**Comment by WinClient5270** [comment]
> 
> 
> Kindly leave Vista in the past where it belongs.

Right after you _kindly_ stop replying to a thread posted 3 years ago.. Looks like I'm not the only one "living in the past" 🙄

**Comment by Squall-Leonhart** [comment]
> 
> 
> > Kindly leave Vista in the past where it belongs.
> 
> Right after you _kindly_ stop replying to a thread posted 3 years ago.. Looks like I'm not the only one "living in the past" roll_eyes

This issue was just referenced because someone wanted to run WF on vista.

Maybe you need to live in the present?

**Comment by WinClient5270** [comment]
> > > Kindly leave Vista in the past where it belongs.
> > 
> > 
> > Right after you _kindly_ stop replying to a thread posted 3 years ago.. Looks like I'm not the only one "living in the past" roll_eyes
> 
> This issue was just referenced because someone wanted to run WF on vista.
> 
> Maybe you need to live in the present?

I’d hardly call Feb. 2018 “the present” so maybe you should take your own advice. 

Unsubscribing from this thread now, the best option for XP/Vista users is to simply use roytam1’s browser builds, available over at MSFN. Thank you to @MrAlex94 for showing interest in Vista regardless.

**Comment by grahamperrin** [comment]
Alex linked to this issue yesterday from <https://www.reddit.com/r/waterfox/comments/fi0zrr/what_is_happening_on_windows_vista/fkfbgem/>, the opening post there was firm but polite in this aspect: 

> … Don't tell me things like unsupported versions of Windows …

i.e. the poster is aware of the lack of the support. I respect his wish for people to not question his use case.

**Comment by grahamperrin** [comment]
> roytam1’s browser builds, available over at MSFN.

@WinClient5270 thank you, and for anyone with an interest: 

https://msfn.org/board/profile/135771-roytam1/
