### ISSUE TITLE
[PrivacyMatter] The function Clear history doesn't seem to work

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#167]
- Removed Telemetry
- Removed data collection
- Removed startup profiling
- etc

Hello,

according to this list, you might want to take a look about the cookies. Because **apparently** there is maybe a trouble... In fact, the data (**specially the cookies** (with PaleMoon_v27.4.0a1, Nightly_v56.0a1, Cyberfox_v52.2.0 and Waterfox_v54 under Windows 10_v1607 x64)) aren't removed...
At least, if you use another software (not Firefox) to check it (one [report](https://pastebin.com/PwQQ4La7)), Because once you have closed the browser, it can't see (or detect) them (like [in this picture](http://nsa38.casimages.com/img/2017/06/21/170621040044405724.png)) neither remove them...

Unless the software (such as Ccleaner, etc) is wrong ? That's a mistake (or a bug) ?
Did I miss something on the page **about:preferences#privacy** ? As you can guess, nothing seem's to work :
1. [Clear_All_History](http://nsa37.casimages.com/img/2017/06/21/170621045525188474.png)
2. [Settings_For_Clearing_History](http://nsa37.casimages.com/img/2017/06/21/170621045525227620.png)
3. [Clean_history](http://nsa38.casimages.com/img/2017/06/21/170621043325379074.png)

`pref("browser.privatebrowsing.autostart",true);`
There is another solution ? Because for the moment, no the Private Browsing isn't a solution for me... I don't want to lose another data (the forms).

Do you think it's something related about the **HSTS** ? One advice, you might want to check the file **SiteSecurityServiceState.txt** (inside the profil).
Do you have another idea ? Can you delete it or change the attribute (only read mode) ?

**Comment by zymase** [comment]
CCleaner considers data collected in Dom Storage as cookies.
If you close Firefox and delete the webappsstore.sqlite file you should notice that CCleaner fits with the browser's cookie analysis.

To forbid Dom Storage, set dom.storage.enabled to false, but it isn't advised as many sites require it. Better is to delete that webappsstore.sqlite file once in a while or -- better -- to include it in CCleaner.

 But be aware that some sites -- few -- keep the user's data that would fit correctly in a traditional cookie ... in that Dom Storage instead, with which I don't agree : examples : 

http://www.clocktab.com/
https://www.qwant.com/

With such sites deleting webappsstore.sqlite will delete your data as well (including login when qwant.com is concerned).

**Comment by grahamperrin** [comment]
I can't help with what's above (sorry) but have you tried **Forget about this site**? In a context menu, in the Library window …

**Comment by grahamperrin** [comment]
Please, have you tried Forget about this site?
