### ISSUE TITLE
[Website] Wrong link targets when on the Downloads page

### ISSUE THREAD

**Issue by vlakoff** [BrowserWorks/waterfox#168]
When on the [Downloads page](https://www.waterfoxproject.org/downloads), on the top navbar the "About" and "Features" links don't work.

That's because they are anchored links and should be changed from `/downloads#about` to `/#about`.

<br>Note the [Blog & News page](https://www.waterfoxproject.org/blog/) already has correct links.

**Comment by MrAlex94** [comment]
Thanks, this has been fixed 😁
