### ISSUE TITLE
Issue with FF add-on CheckMyHTTPS 

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#169]
EDIT : obsolete. 
I contacted the developer of CheckMyHTTPS who explained that the add-on checks for the application's name in order to use the correct interface ("Firefox" => desktop, "Fennec" => mobile), and that because Waterfox uses it's own name it isn't recognized by CheckMyHTTPS. He added that an updated version of CheckMyHTTPS is on its way that will include 'Waterfox'.
EDIT-end

Hi,

I'm a Firefox user (ESR, 52.2.0) and decided to have a try with Waterfox, test was performed with previous Waterfox 54.0.0

I have 68 add-ons. Waterfox started correctly, all add-ons functional except one:
CheckMyHTTPS - https://addons.mozilla.org/en-US/firefox/addon/checkmyhttps/

CheckMyHTTPS doesn't start, remains mentioned in about:addons but its toolbar button has disappeared, as well in the Customize panel (I assume it isn't functional therefor)

I opened a new profile and started Waterfox again, hence no add-ons. I installed then CheckMyHTTPS from its AMO page : same issue.

Uninstalled Waterfox, installed the Firefox 54 version this time in order to know if the issue was 54-specific or Waterfox-specific. Firefox 54 ran CheckMyHTTPS correctly.

One add-on is not a tragedy yet,
1- I really care for this add-on,
2- I'm curious to know why that add-on and that add-on only wouldn't run on Waterfox 54.0.0

Thanks for investigation/advice.

**Comment by grahamperrin** [comment]
> … its toolbar button has disappeared …

Not reproducible with more recent version 4.3.0 on Waterfox 56.0.4.1. 

> EDIT : obsolete. …

Would you like to close this issue? Thanks.
