### ISSUE TITLE
waterfox crashes and show no windows report

### ISSUE THREAD

**Issue by strichking** [BrowserWorks/waterfox#170]
my waterfox started crashing yesterday. I managed to find out where the error could be available to reading because when I tried to open waterfox at same time windows error reporting process where running and also closed when waterfox process went away. I'm going to atach all the files if some of you need.

the error: http://i.imgur.com/kxH4zUw.png
this file come as informative after the error in wer. http://i.imgur.com/cmw2WHq.png
this too: http://i.imgur.com/YXjPKd2.png
I can't manage to attach the fthempty.txt because it is purged after the process closes.

More about the random crashes; sometimes I'm browsing in random webpages and the browser crashes, sometimes it won't open until I restart my PC.

**Comment by grahamperrin** [comment]
Is this issue reproducible with Waterfox 56.0.3?
