### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#173]
```
An error occurred during a connection to : "storage-waterfox.netdna-ssl.com". Peer received a valid certificate, but access was denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
```

Hello,

according to this message and the fact it was block by the antivirus (eset_v10). I will assume, for now there is one trouble if you want to download Waterfox.
I had check a few times and it's the same message.

Kind regards.

**PS :** Almost one month later damn...  At least, yes there is one solution. You need to add this adress url in your **whitelist** (or exclude) inside your antivirus (Web ---> Advanced settings).

**Comment by MrAlex94** [comment]
Strange that the AV is giving issue, MaxCDN are a huge provider!

**Comment by Squall-Leonhart** [comment]
Seeing this on beamdog 

https://www.beamdog.com/products/neverwinter-nights-head-start-english

![unknown 1](https://user-images.githubusercontent.com/1098176/34666198-3e2c89f8-f4b7-11e7-823b-0e925978c315.png)

It's caused by the server rejecting Waterfox useragent

https://github.com/MrAlex94/Waterfox/issues/178

**Comment by grahamperrin** [comment]
> … caused by the server rejecting Waterfox useragent

According to that page, 

>> The connection to the server was reset while the page was loading. 

Are we certain that the reset is a response to a user agent string? 

----

Compare with the opening post: 

>> An error occurred during a connection to : "storage-waterfox.netdna-ssl.com". Peer received a valid certificate, but access was denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT
>> 
>> The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
