### ISSUE TITLE
Issue with video and Mountain Lion

### ISSUE THREAD

**Issue by KawaiiAurora** [BrowserWorks/waterfox#174]
I've just discovered WaterFox a few weeks ago and on Mountain Lion, it works well but I have one issue.

No videos play (no YouTube or other sites). 

I have observed the issue in versions of FireFox from 52 onwards but I've divised a fix for FireFox 52 ESR and that is by changing "esr" to "beta" in /Contents/Resources/defaults/pref/channel-prefs.js

Is it possible that this issue gets fixed (seeing that every version of OS X back to 10.5 is supported)?

I observed the issue on a late 2006 iMac with the following specs:

- 2.16GHz C2D
4GB RAM
Geforce 7600GT
OS X 10.8.5 with MLPF

Thanks,
Aurora

**Comment by parrotgeek1** [comment]
Thanks for finding the fix!

**Comment by grahamperrin** [comment]
> … No videos play (no YouTube or other sites). …

Is the issue reproducible with Waterfox 56.0.1 on Mountain Lion?
