### ISSUE TITLE
OSX 10.6.8: Waterfox Setup 54.0.1: sigtrap

### ISSUE THREAD

**Issue by JamesC1** [BrowserWorks/waterfox#177]
Waterfox appears to make an assumption which is false on my system.

The dump is below and refers to files in /usr/lib, so here's some ls and find output:

$ ls /usr/lib/libc*
/usr/lib/libc.dylib		/usr/lib/libcupscgi.dylib
/usr/lib/libcblas.dylib		/usr/lib/libcupsdriver.1.dylib
/usr/lib/libcharset.1.0.0.dylib	/usr/lib/libcupsdriver.dylib
/usr/lib/libcharset.1.dylib	/usr/lib/libcupsimage.2.dylib
/usr/lib/libcharset.dylib	/usr/lib/libcupsimage.dylib
/usr/lib/libclapack.dylib	/usr/lib/libcupsmime.1.dylib
/usr/lib/libcom_err.dylib	/usr/lib/libcupsmime.dylib
/usr/lib/libcpp_kext.a		/usr/lib/libcupsppdc.1.dylib
/usr/lib/libcrypto.0.9.7.dylib	/usr/lib/libcupsppdc.dylib
/usr/lib/libcrypto.0.9.8.dylib	/usr/lib/libcurl.2.dylib
/usr/lib/libcrypto.0.9.dylib	/usr/lib/libcurl.3.dylib
/usr/lib/libcrypto.dylib	/usr/lib/libcurl.4.dylib
/usr/lib/libcups.2.dylib	/usr/lib/libcurl.dylib
/usr/lib/libcups.dylib		/usr/lib/libcurses.dylib
/usr/lib/libcupscgi.1.dylib
$ find /usr -name "libc++*"

If there's a simple local symptom-fix with macports, then I'm up for it.

---------------------

Process:         waterfox [84595]
Path:            /Volumes/Waterfox/Waterfox.app/Contents/MacOS/waterfox
Identifier:      org.Waterfoxproject.waterfox
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [317]

Date/Time:       2017-08-07 22:22:37.634 +1200
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          3670305 sec
Crashes Since Last Report:           6
Per-App Crashes Since Last Report:   2
Anonymous UUID:                      67EA0060-E6C8-4310-AD62-EBE1A708262C

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /usr/lib/libc++.1.dylib
  Referenced from: /Volumes/Waterfox/Waterfox.app/Contents/MacOS/waterfox
  Reason: image not found

Binary Images:
    0x7fff5fc00000 -     0x7fff5fc3bdef  dyld 132.1 (???) <DB8B8AB0-0C97-B51C-BE8B-B79895735A33> /usr/lib/dyld

Model: MacBookPro8,1, BootROM MBP81.0047.B27, 2 processors, Intel Core i7, 2.7 GHz, 8 GB, SMC 1.68f99
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 512 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 5.100.198.104.5)
Bluetooth: Version 2.4.5f3, 2 service, 12 devices, 2 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: ST500LT012-1DG142, 465.76 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: FaceTime HD Camera (Built-in), 0x05ac  (Apple Inc.), 0x8509, 0xfa200000 / 3
USB Device: Hub, 0x0424  (SMSC), 0x2513, 0xfa100000 / 2
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 5
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x821a, 0xfa113000 / 8
USB Device: Apple Internal Keyboard / Trackpad, 0x05ac  (Apple Inc.), 0x0245, 0xfa120000 / 4
USB Device: Hub, 0x0424  (SMSC), 0x2513, 0xfd100000 / 2
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0xfd110000 / 3

**Comment by MrAlex94** [comment]
This is due to Clang (and its libc++) being used on later versions, which 10.6 didn't have. You can [manually](https://stackoverflow.com/questions/18033255/install-libc-on-mac-10-6-8) install it. I'll try get it statically linked in a test build and run some tests to see if it breaks.
