### ISSUE TITLE
User-Agent: Waterfox

### ISSUE THREAD

**Issue by iffin2l** [BrowserWorks/waterfox#178]
I'd like to know if it's possible to remove Waterfox after Firefox agent to avoid identification
Most people don't use Waterfox. I believe it's safer to leave as if it was default Mozilla Firefox

**Comment by WagnerGMD** [comment]
According to this [reddit topic](https://www.reddit.com/r/waterfox/comments/6of9ct/bug_unable_to_access_website_since_upgrade_to/), there is also another trouble (related to the user-agent).
Because (I had check again today and) it's seem to be true, CloudFlare block the browser.

**Comment by iffin2l** [comment]
I believe it would be both safer and better to change from _'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0.0.1 Waterfox/54.0.0.1'_ to _Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0(Firefox/**current release**)_

**Comment by MrAlex94** [comment]
@iffin2l, do you mean Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 _(Waterfox/current release)_ ?

**Comment by iffin2l** [comment]
@MrAlex94 Hi Alex, I thought it could be a good thing to let as if it is a default Firefox. Like this _Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0_
Or.. perhaps having two options, the one with the agent _Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 Waterfox/55.0_ and the other one without the Watefox(current release). This is strictly my privacy concern only. Nothing that would break any website I believe
Thank you

**Comment by WagnerGMD** [comment]
Just to inform. Right now, I'm able to access to [pricehipster.com](https://pricehipster.com/). So I will suppose the trouble with **CloudFlare** might be gone.

**Comment by juneyourtech** [comment]
The User Agent Switcher add-on solves many of the issues I have, though I don't use Waterfox.

Firefox for Android has an about:config option to change user agents, like this:

general.useragent.override.domainname.tld (UA string, supports subdomains, too)
general.useragent.site_specific_overrides (true/false)

These two do not work in desktop versions of Firefox.

For most sites, I'm okay with using the defalt user agent — be it IceCat or Waterfox — just so, that sites would recognise, that an alternative browser is in use. But some sites do require either Firefox or a certain version of it.

**Comment by ghost** [comment]
It is possible to override the User Agent on Waterfox 52.0.2 at least, which I am using.

WF already has `general.useragent.override.chase.com` and `general.useragent.override.discordapp.com`
set to the browser's User Agent with Waterfox[VERSION] removed.

All we have to do is modify (create if editing the about:config) a hidden setting called `general.useragent.override` and give it the same value as that of `general.useragent.override.chase.com` (to make it easy and faultless).

For instance at this time I have:
`general.useragent.override.chase.com` = Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

I create/modify my `general.useragent.override` and set it to above.

If I then check my User Agent on a site such as https://whoer.net/ I'll notice:

> Browser
> Headers:
>     Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0.2
> JavaScript:
>     Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0.2

**No Waterfox 55.0.2 mentioned.**

A bit cumbersome maybe, and requires modifying the value when Waterfox is updated, but it works.

Personally I admit a conflict between the privacy advantage of having Waterfox removed from the UA and the pleasure of knowing that I am identified as a Waterfox fan.

**Comment by juneyourtech** [comment]
@mazesy IMHO, since Waterfox is going to keep on supporting XUL, then eventually, it could be meaningful to use a unique user-agent string. And indeed, I have the same feelings wrt the UA string when using GNU IceCat in Android, though for some sites, I must still identify it as Firefox.

**Comment by juneyourtech** [comment]
Site-specific user-agent strings are possible on desktop Firefox and derivatives, after all, since I now finally got the right extension combination:

[UAControl](https://addons.mozilla.org/en-US/firefox/user/KRyoumei/) + [User-Agent JS Fixer](https://addons.mozilla.org/en-us/firefox/addon/user-agent-js-fixer/)

Works like a charm.
But _both_ have to be installed, or it won't work.

Note also, that it's not just the main domain, but some of the additional domains hosting scripts, too. Especially with Skype for Web.

To find out, which domains a site requires for functioning, use the User Agent Switcher for global UA switching with the default Firefox UA, and NoScript. That should show the list of script-hosting domains, but not all domains are required to be added with most sites, as many are simply domains used for ads and tracking.

The usual combo is www.site.tld and cdn.site.tld, but typically not apis.hugeservice.tld, and certainly not ads.adnetwork.tld

This extension combination should make it possible to use the Waterfox user agent string for most sites, and the Firefox (or other) UA string for sites that specifically require that.

**Comment by 007SecretUserAgent** [comment]
According to my tests with the User Agent Switcher extension, the big french streaming site dailymotion.com seems not to work at all with the default Waterfox user agent. Example video (but same problem for all, even embedded in other sites) :
https://www.dailymotion.com/video/xpuyk6
The videos say something like "Oh no ! An unexpected error happened" and don't play. They play normally when I set a firefox user agent instead, on Waterfox. And this is true for the firefox browser too, if I change its user agent for a waterfox one, dailymotion videos don't play.
I don't know how many other sites made such a stupid design decision but it may be a problem for basic Waterfox users...
What to do ? Fake user agent by default ? Warn users and explain them what to do ? Contact the problematic websites ? Ignore the problem ?

**Comment by WagnerGMD** [comment]
From my point of view, it's clear one real bad stupid design. Then at first I would say to try to contact these websites... But if you're very patient and very brave because the path might be very long and very hard.

About Dailymotion, sorry but you're sure this link is good ? Because right now, no it doesn't seem to work. 
http://www.dailymotion.com/embed/video/xpuyk6
At the contrary, now (with the right adress) it's seem to work fine. I had try anothers videos and it's all right (for the both browsers : Firefox and Waterfox). In the last months, I haven't met any trouble (but I watch on occasion). So I will conclude this trouble doesn't concern Dailymotion.

**Comment by grahamperrin** [comment]
## Dailymotion

With a default string for Waterfox 56.0 on FreeBSD-CURRENT –

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.0`

– and with Adobe Flash Player https://www.freshports.org/www/flashplayer installed, both of the following appear to require activation of Adobe Flash: 

- https://www.dailymotion.com/video/xpuyk6 
- http://www.dailymotion.com/embed/video/xpuyk6

With a terser string for `https://www.dailymotion.com/`, neither page requires Flash: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0`

Maybe relevant: 

- https://github.com/dailymotion/uas-parser

----

At least one other service requires a custom string. I treat these issues as service-specific, not an issue with Waterfox. 

My preferred extension for site-specific and domain-specific strings: 

- [Custom UserAgent String](https://addons.mozilla.org/addon/custom-user-agent-revived/) also known as _Custom User-Agent (Revived)_

**Comment by 007SecretUserAgent** [comment]
@WagnerGMD Yes I also tried using your modified link with the /embed/ added and the problem remains the same for me. The URL I gave without the /embed/ is the type of URL you get when you browse dailymotion.com normally, clicking on videos from the dailymotion starting page for example.

@grahamperrin Yes I think you found the explanation : with the flash plugin enabled, dailymotion videos want to use flash for waterfox useragents, and when flash is installed but disabled, which is how I was browsing the site, videos show an error message for waterfox useragents (without explaining that they're actually expecting flash and can't find it !).

Suggestion to solve the problem for everybody : waterfox should by default come with a new pref
general.useragent.override.dailymotion.com
set to a firefox user agent like
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
for instance, or a more modern one. I tried to create this pref and it solved the problem.

Note : my config is windows 7 x64, waterfox 55.2.2. Flash plugin 27 from 
https://get.adobe.com/fr/flashplayer/.

**Comment by grahamperrin** [comment]
https://twitter.com/grahamperrin/status/937553230996885504 addresses a suggestion to Dailymotion …

**Comment by WagnerGMD** [comment]
@007SecretUserAgent The trouble is probably related to the OS, no ? Clarify or remind because I didn't find it.
Because I'm under W10 and no I didn't think about on the moment.

**Comment by Squall-Leonhart** [comment]
https://www.beamdog.com refuses secure  connection with the waterfox user agent on windows, but works on Mac.

**Comment by grahamperrin** [comment]
> https://www.beamdog.com …

Cross reference https://www.reddit.com/r/waterfox/comments/7ov4a3/waterfox_5602_is_now_available_with_important/dscylhe/

> … the waterfox user agent on windows, …

For 56.0.2, what's the string? You can get it at <https://udger.com/resources/online-parser>

**Comment by Squall-Leonhart** [comment]
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.2 Waterfox/56.0.2

If i change it to use one of the linux or OSX user agents, or remove Firefox/56.0.2 or Waterfox/56.0.2 (keeping the other) it works.

The Get request is literally blocked in network console.
 

> Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.2 works
> Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Waterfox/56.0.2 works
> 
> Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.2 Waterfox/56.0.2 does not work.
These tests were performed in a 8.1 vm, hence the nt build number.

https://www.codedog.pl/ mentioned in https://github.com/MrAlex94/Waterfox/issues/360 has the same facilitating cause.

**Comment by grahamperrin** [comment]
<https://www.beamdog.com/> today: 

- does not work with 
  `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.2 Waterfox/56.0.4`
- does work with 
  `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Waterfox/56.0.4`
- does work with my default, 
  `Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4`

I guess that it's reasonable for a secure server to: 

- refuse communication with Firefox 56.0.2, which does exist and is known to not have fixes for some known vulnerabilities
- ignore the pretence of Firefox 56.0.4, which does not exist.

**Comment by WagnerGMD** [comment]
`https://duckduckgo.com/?q=useragent`
Then yes there is another way. I believe it could be more useful (or easier) for the people which use DDG. 

**PS :** No don't worry @grahamperrin because it's just a little suggestion. Then as you wish but after a little moment (a few weeks), I still believe it might improve a little the previous post (more complete and more choice for the people).

**Comment by grahamperrin** [comment]
> … Skype for Web … 

@juneyourtech big thanks for that hint. It probably explains a report that I received, a few days ago, of Waterfox not working for Skype at one of the (Windows) computers in our building. 

Debatably the type of thing that should be documented in the [Waterfox ESR](https://github.com/MrAlex94/Waterfox/issues/410) context, as (with Mozilla) ESR is associated with enterprise use.

**Comment by grahamperrin** [comment]
Review time. Focusing, with added emphasis: 

> ## User-Agent: Waterfox

> … **remove Waterfox** after Firefox agent …

I'm not aware of any significant issue arising from that change. 

Should we maybe close this issue? 

For subjects other than the UA, I'm almost certain that we have discussions elsewhere in GitHub and/or Reddit. 

TIA

**Comment by RealRaven2000** [comment]
browser-update.org just flagged waterfox as "not compatible" for access to my medical card information site, is there anything we can do to signal Waterfox 56.2 is up to date?
I raised https://github.com/browser-update/browser-update/issues/397 with them.
My UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
I suggest adding Waterfox to the UA as well

**Comment by RealRaven2000** [comment]
browser-update.org just flagged waterfox as "not compatible" for access to my medical card information site, is there anything we can do to signal Waterfox 56.2 is up to date?
I raised https://github.com/browser-update/browser-update/issues/397 with them.

My [unmodified] UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

I suggest additionally appending Waterfox to the UA as well so that website can detect it.

**Comment by grahamperrin** [comment]
@josselex @MrAlex94 just FYI in lieu of my current default,

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0`

– I'll experiment with this: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2.0) Gecko/20100101 Firefox/56.2.0`

(Truly there'll never be a Firefox 56.2.0.)

----

Note to self: `#thinkbubbles #FreeBSD` half-expect problems with the web interface to AMO, but that's not a reason to refrain from the experiment. Postscript, 2018-05-31: the recent fix of https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226919 eases things for me.

**Comment by grahamperrin** [comment]
From @RealRaven2000: 

> … Should we fake our UA and just lie about the version number to stay in sync with the real Firefox?

Whilst Waterfox does so – in a way that describes itself as recognisably outdated – the consequences will include some services finding issues with the browser. 

---

Outdated Firefox 56 aside, for a moment: from a different angle, 57-oriented https://github.com/MrAlex94/Waterfox/commit/22dcd9a96ef94eb43868b2c33e8ec8e3aece0f2f (2018-03-24) <strike>caused </strike>was in the midst of a different set of issues. And so on …

… there's not an absolute answer, no panacea, for the (naturally) unusual Waterfox situation at this time.

**Comment by grahamperrin** [comment]
## Browser-Update.org

For reference

browser-update/browser-update issue 397 is closed, with this comment: 

----

> Hi,
> 
> I now whitelisted Waterfox by looking for "Firefox 56.2" in the user agent string. A few notes from me:
> 
> - Please add a an explicit name of the browser to the user agent string. You can keep the Firefox part but add your own string. This makes it easier to detect the browser. And this is how hundreds of other browsers forked from chrome or firefox or webkit do it. Only then you may even think to "lie" about the firefox version. You will be backwards compatible by default but it will make it possible for services as this to whitelist the browser. I think blacklisting will not occure that often!
> - I cannnot recommend Waterfox for users if it will be stuck at the base of firefox 56 forever since sites may require newer technologies. The question is if it will get the features of newer firefox versions. Let's see.
> 
> Please move the discussion (to) the Waterfox github page.

----

Special thanks: 

- to @RealRaven2000, for taking the initiative in this case
- to the developers and providers of the Browser-Update.org service, for considerate action and observations.

**Comment by RealRaven2000** [comment]
thanks to browser-update on their action. I agree adding Waterfox to the UA string would be helpful for all sorts of reasons - somebody raised the issue of Fingerprinting, but I am not sure whether simply stating the browser name is such a big problem in this context. Surely the first thing to address would be cookies & IP addresses.

**Comment by grahamperrin** [comment]
Recently I'm experimenting with this string, which I call 'EXPERIMENT A-01':

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2`

– **not** Waterfox-specific. 

## Discord

Tonight I briefly used this (EXPERIMENT A-02) solely for a test of Discord: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2 Waterfox/56.2`

Result:

- _Unmute_ is impossible – "UNSUPPORTED BROWSER"
- _Undeafen_ is similarly impossible

– consistent with the earlier report from @bn4t. 

Discord finds difficulty with a user agent string that is Waterfox-specific. 

Reverting to EXPERIMENT A-01 allows audio to be used, but this is a blunt approach.

## Sites that require, or benefit from exceptions

Extensions such as Custom UserAgent String (see <https://github.com/MrAlex94/Waterfox/issues/178#issuecomment-348861936>) can be used.

**Comment by Squall-Leonhart** [comment]
the problem is that we had this previously  and it broke secure sessions on some pages

**Comment by grahamperrin** [comment]
From post-closure discussion in the Browser-Update.org area: 

>> … pretend to be version 60?
> 
> This would still be better tan "Firefox 56.2" I suppose, and would actually fix the "outdated" messages.

The pretence of Firefox 60 with Waterfox 56.2.0 can be troublesome for people who might install things whilst seeking or browsing extensions at **Add-ons for Firefox** – <https://addons.mozilla.org/firefox/> (AMO).

## Fingerprint resistance – `privacy.resistFingerprinting`

about:config?filter=privacy.resistFingerprinting

If `privacy.resistFingerprinting` is `true` with Waterfox 56.2.0 then a pretence of Firefox 60 will not apply; during _normal_ browsing, AMO will behave as if Waterfox is Firefox ESR 52.0. And so on …

## `privacy.resistFingerprinting.block_mozAddonManager`

_If_ `privacy.resistFingerprinting.block_mozAddonManager` is present for you (boolean, `false` or `true`) then you might find interest in: 

- [uplift "privacy.resistFingerprinting.block_mozAddonManager" feature · Issue #441 …](https://github.com/MrAlex94/Waterfox/issues/441) (closed)
- [privacy.resistFingerprinting.block_mozAddonManager by laniakea64 · Pull Request #449 …](https://github.com/MrAlex94/Waterfox/pull/449) (fixed #441)
- and possibly [Waterfox 56.1.x to be treated as if it's … 57 for add-on services e.g. AMO · Issue #484 …](https://github.com/MrAlex94/Waterfox/issues/484) NB https://github.com/MrAlex94/Waterfox/issues/484#issuecomment-394198020

**Comment by grahamperrin** [comment]
@Squall-Leonhart I do recall that (yes) … possibly _overlapping_, at times with a separate issue. Some interpretation challenges IIRC. Details maybe in one of the earlier posts? TBH I'll probably not sift through. (Clearing my head now after a busy week at home.)

**Comment by WagnerGMD** [comment]
Somewhere (probably on another topics), remember this fact : I had try @grahamperrin to warn you about this trouble.
```
lockPref("privacy.resistFingerprinting",true);
## It's must remain enable to avoid this trouble.
## Otherwise it will block the installation (a lot of addons).
```
Because that's true it could be one real trouble on AMO (which use (or rely on) the **useragent**) specially if you want to install any addons.

**PS :** Because I haven't see this warning everywhere but only sometimes (on AMO).

**Comment by josselex** [comment]
What is the current user agent string of firefox now? I want to white-list it for browser-update.org but i can't!
What about the idea to call it 52.0.2 and so on? 
I need anything to identify it.

**Comment by grahamperrin** [comment]
@josselex thanks for asking. 

For now: 

- the string for Waterfox 56.2.2 is (as before) indistinguishable from the string for outdated Firefox 56.0. 

Looking ahead: 

- https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-407641749 there's a quote about Waterfox 60 (with Firefox ESR 60 as its basis). 

----

### about:config?filter=general.useragent.override

For the past few weeks, around 99% of my browsing has been with this override: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2 Waterfox/56.2`

- problematic in only one area, `addons.mozilla.org`. 

For AMO, I'll add something to open issue #484.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/commit/8e978a6df522a2e12ab3080d691fec490db01a56

### Postscript

> … WF already has `general.useragent.override.chase.com` and `general.useragent.override.discordapp.com`

NB those overrides were removed by the commit for Waterfox 56.2.3. 

Probably related: 

- [Problem w/ signing in at Chase.com : waterfox](https://www.reddit.com/r/waterfox/comments/9ic1h9/problem_w_signing_in_at_chasecom/)

**Comment by eleius** [comment]
I wanted to remove "waterfox" from the user agent to reduce fingerprinting, so I thought I could use general.useragent.override but I'm worried this could break addon compatibility checks (there's a general.useragent.override.addons.mozilla.org already, not sure if it take precedence overe the other setting?)

**Comment by grahamperrin** [comment]
`general.useragent.override` can be set (or reset); `general.useragent.override.addons.mozilla.org`, if present, will remain effective.

**Comment by grahamperrin** [comment]
Cross references: 

- [User Agent : waterfox](https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/) (2018-09-07)
- [User agent (UA) string overrides: discussion : waterfox](https://www.reddit.com/r/waterfox/comments/d79h2l/user_agent_ua_string_overrides_discussion/) (2019-09-21)
