### ISSUE TITLE
macOS Broken Bookmark Importing

### ISSUE THREAD

**Issue by bdscharf** [BrowserWorks/waterfox#179]
Bookmark importing from another browser (Chrome) and from an HTML file both do not work. Bookmark menu is empty after importing. Importing from Chrome "completes" without error, and import from HTML is error-free as well.

Waterfox version 54.0.1, Chrome version 60.0.3112.90, macOS Sierra version 10.12.6

EDIT - Looks like the bookmarks went into Firefox Nightly. If this is expected behavior, feel free to delete this issue! After deleting Nightly and all Firefox-related files, the bookmarks still do not appear when importing from Chrome.

**Comment by grahamperrin** [comment]
> …  54.0.1, … like the bookmarks went into Firefox Nightly. …

From [Waterfox 56 Release](https://www.waterfoxproject.org/blog/waterfox-56.0-release-download): 

> … Waterfox now uses its own profile directory. … 

– so you can probably close this issue.

**Comment by bdscharf** [comment]
Thanks! Closing.
