### ISSUE TITLE
Missing security bug in your 40.0.3 merge

### ISSUE THREAD

**Issue by nixiValor** [BrowserWorks/waterfox#18]
your missing [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1164766)
[commit](https://github.com/mozilla/gecko-dev/commit/183a73b7d1ffb128cf85b2d1e7df8ce44935e0f8)

This bug is patched in firefox 40.0.3 is there a reason why it was left out.

**Comment by leelaylay** [comment]
��������������������������

**Comment by MrAlex94** [comment]
No idea why, the current Waterfox branch is based on v40.0.2 which was cloned from that exact repo about 2 weeks ago. I'll add in the patch now.

**Comment by nixiValor** [comment]
@MrAlex94 well to my understanding based on [commit](https://github.com/MrAlex94/Waterfox/commit/0016ae1ee002f92a48e425480ba34246f3fa2d5c) & the [browser version file](https://github.com/MrAlex94/Waterfox/blob/master/browser/config/version.txt) the current repository branch is 40.0.3 allegedly based from Firefox 40.0.3 branch.

This patch is not present in the current release test build [you posted](https://www.reddit.com/r/waterfox/comments/3jmhv4/waterfox_4003_test_builds/) is it not based on firefox 40.0.3?

**Comment by MrAlex94** [comment]
No it's based on 40.0.2 with patches applied. 
Added the patches listed in the commit log (didn't apply what wasn't build by WF, so Linux & b2g patches): https://github.com/mozilla/gecko-dev/commits/release
