### ISSUE TITLE
Specific search engines for locales

### ISSUE THREAD

**Issue by hawkeye116477** [BrowserWorks/waterfox#180]
@MrAlex94 Why Waterfox removed specific search engines for locales, for example wikipedia has only english version from recently, startpage too and removed allegro.pl also?

**Comment by precompute** [comment]
You can define custom search engines, right click on any search box (like wikipedia's) and click on "Add a keyword for this search". You can define separate keywords for separate locales. You'll have to remember them, but this is the easiest solution to independently implement.

**Comment by hawkeye116477** [comment]
@t-e-r-m I know that, but Firefox has specific search engines for locales and Cyberfox also has by default, so why @MrAlex94 removed them?

**Comment by MrAlex94** [comment]
It's the language packs that control the search engines for locales that aren't en-US, since Waterfox doesn't build binaries for each locale which is the reason for deleting them.

**Comment by hawkeye116477** [comment]
@MrAlex94 Cyberfox also doesn't build binaries for each locale and has specific search enignes for locales -> https://github.com/InternalError503/cyberfox-languagepacks/tree/master/releases/52.3.0/pl.xpi/browser/chrome/pl/locale/browser/searchplugins.
