### ISSUE TITLE
About Waterfox

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#183]
Its an error, when i click on about Waterfox. See picture.

https://imgbox.com/tdGCVkCW

[URL=http://imgbox.com/tdGCVkCW][IMG]https://i.imgbox.com/tdGCVkCW.jpg[/IMG][/URL]

**Comment by MrAlex94** [comment]
What version of Waterfox?

**Comment by ghost** [comment]
Latest 55.0.1

**Comment by ghost** [comment]
With 54.0.1 "about Waterfox" works without error.

**Comment by ghost** [comment]
I can´t insert pictures here with waterfox. i hope, you can see the picture linked.

**Comment by ghost** [comment]
I come from germany 👯

**Comment by ghost** [comment]
Have you an idea?

**Comment by MrAlex94** [comment]
Yes I think I've got it, will fix in 55.0.2.

**Comment by ghost** [comment]
Give´s a date to come 55.0.2?

**Comment by grahamperrin** [comment]
Fixed, yes?

**Comment by grahamperrin** [comment]
Review time. Close this?
