### ISSUE TITLE
Waterfox does not start

### ISSUE THREAD

**Issue by galstudio** [BrowserWorks/waterfox#186]
When you start an error appears:

PCOMGlueLoad error for file /opt/waterfox/libxul.so:
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/waterfox/libxul.so)
Couldn't load XPCOM.

I have ubuntu 16.04

**Comment by piknik** [comment]
I have the same problem with the new version 55 update. Doesn't occur in 54.
Ubuntu 16.04

**Comment by hawkeye116477** [comment]
Latest Waterfox was compiled with little newer libstdc++, so probably you should follow instructions from https://www.reddit.com/r/waterfox/comments/6u4cur/waterfox_55_do_not_work_on_linux_mint_182/dls0062/ or wait for new version compiled with older lib.

**Comment by grahamperrin** [comment]
@galstudio can you start 56.0.3?

**Comment by galstudio** [comment]
@grahamperrin yes, i start without a problem

**Comment by grahamperrin** [comment]
Review time. Let's close this, thanks …
