### ISSUE TITLE
Continued support for complete themes

### ISSUE THREAD

**Issue by freundTech** [BrowserWorks/waterfox#187]
In addition to removing support for NPAPI plugins Firefox also plans to remove support for complete themes in Firefox 57, only keeping support for lightweight themes (https://blog.mozilla.org/addons/2017/02/24/improving-themes-in-firefox/).
Lightweight themes can change the top bar background picture and a few colors, while complete themes can change the look of pretty much every UI element using CSS.

Does Waterfox plan to support complete themes in the future?
Also what are Waterfoxes plans for the Firefox Photon UI? Will Waterfox adapt the new UI or try to keep the old UI?

**Comment by TomJansen** [comment]
> Also what are Waterfoxes plans for the Firefox Photon UI? Will Waterfox adapt the new UI or try to keep the old UI?

The only substantial thing that the photon UI changes is the menu, right? Would it be possible to switch between the menu we have now and the photon menu? Or some hybrid of the two? I place a lot of extensions in the menu, and I don't want to lose that option.

**Comment by grahamperrin** [comment]
See also: 

- [Hiding titlebar on Linux : waterfox](https://www.reddit.com/r/waterfox/comments/8ca9tt/hiding_titlebar_on_linux/)

**Comment by grahamperrin** [comment]
For reference only, recently in Reddit: 

- [updating old themes to work with waterfox](https://www.reddit.com/r/waterfox/comments/a39mcp/updating_old_themes_to_work_with_waterfox/)
- [Firefox themes break under waterfox](https://www.reddit.com/r/waterfox/comments/a6b5fa/firefox_themes_break_under_waterfox/)
- [An archive of XUL (complete) themes? : waterfox](https://www.reddit.com/r/waterfox/comments/ab5r18/an_archive_of_xul_complete_themes/)
