### ISSUE TITLE
Segfault in mozilla::GStreamerReader::ElementAddedCb

### ISSUE THREAD

**Issue by nixiValor** [BrowserWorks/waterfox#19]
This [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1145230) fix is missing in your code merge of firefox 40.0.3 & waterfox 40.0.3
[commit](https://github.com/mozilla/gecko-dev/commit/dd847259c0e7fc502ac8fae8478bc36bfd26160d)

was this bug fix left out due to conflicts ?

**Comment by MrAlex94** [comment]
It's left out because there currently isn't a Linux Waterfox build. It'll be in 41 anyway.

**Comment by nixiValor** [comment]
if you based waterfox 40.0.3 from Firefox 40.0.3 this patch should exist people should be able to build your project from source on linux which i currently have from the current branch.

i manually added the patch.
