### ISSUE TITLE
Does Waterfox have unique targetApplication ID for addons?

### ISSUE THREAD

**Issue by vanowm** [BrowserWorks/waterfox#192]
Just curious, it seems all my addons are working fine as is with Waterfox, but do we have a special targetApplication ID to target specifically Waterfox in the addons (like Palemoon does)?

**Comment by jbeich** [comment]
Probably not, see
https://github.com/MrAlex94/Waterfox/blob/79492ecca4785f362537ddca9db3feeb2b29d197/browser/confvars.sh#L50
