### ISSUE TITLE
[REQ] Display addon's version at the title

### ISSUE THREAD

**Issue by vanowm** [BrowserWorks/waterfox#193]
Firefox used to display addon's version at the all addons list, now we have to click on each addon to see what version it is.
Would be nice if Waterfox brought that back.

**Comment by PandaCodex** [comment]
Cyberfox has this, could port it over to Waterfox if @MrAlex94 wants. Cyberfox had many old features that if Alex wanted could be ported over. 

Remember the old download window from Firefox 24 they kept that, old settings window just 2 i can think of.

**Comment by WagnerGMD** [comment]
In the meanwhile, you might find one solution with one addons like [Classic Theme Restorer](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/)

PS : I won't advice [CyberCTR](https://8pecxstudios.com/Forums/viewtopic.php?f=5&t=475) because if I remember right, it doesn't work (or it's buggy because it doesn't show the version). But it doesn't concern Cyberfox.

**Comment by PandaCodex** [comment]
@WagnerGMD show version in CyberCTR was removed since Cyberfox has the feature built in by default, they have a setting in CyberCTR that prevents collapse of the addon version number when window is small in size.

**Comment by WagnerGMD** [comment]
When I had discover the bug (because on the moment, for me it was true), I wasn't aware. Then thank you for the explanation @PandaCodex.

**Comment by grahamperrin** [comment]
[Add-ons Manager - Version Number](https://addons.mozilla.org/addon/amversionnumber/)

[Simple Add-on Manager](https://addons.mozilla.org/addon/simple-add-on-manager/)

**Comment by Peacock365** [comment]
@PandaCodex 

Off-topic: Would it be possible to restore the locale selector when the new preferences layout (_browser.preferences.useOldOrganization_ set to **false**) is used? The locale selector doesn't show up in this case. I assume it was never implemented for the new preferences layout. I hope this obvious missing item gets fixed. :-)

**Comment by laniakea64** [comment]
Addon versions were restored in https://github.com/MrAlex94/Waterfox/pull/566 . Close this?

**Comment by grahamperrin** [comment]
Thanks. 

Which version is shown in the _Available Updates_ context – the available version, or the installed version? 

Related: [Add-ons manager ▶ Available updates ▶ viewing version numbers – and avoiding unwanted updates : waterfox](https://www.reddit.com/r/waterfox/comments/8k0hq3/addons_manager_available_updates_viewing_version/)

## Orientation

[Waterfox 'Locale select' interface not available with browser.preferences.useOldOrganization false · Issue #494 …](https://github.com/MrAlex94/Waterfox/issues/494)
