### ISSUE TITLE
make install does not exist.

### ISSUE THREAD

**Issue by nimbius** [BrowserWorks/waterfox#194]
the makefile for waterfox does not contain a make install option.  is this intentional?

**Comment by MrAlex94** [comment]
You can't use make directly and Mozilla have actively been phasing it out for a few years now.

Instead, [mach](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/mach) is used.

**Comment by grahamperrin** [comment]
Review time. Close this?
