### ISSUE TITLE
Handle unboxed arrays in jsarray.cpp fast paths

### ISSUE THREAD

**Issue by nixiValor** [BrowserWorks/waterfox#20]
it appears you tried to apply this [patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1163091) but only partially the rest appears to be missing.
[commit](https://github.com/mozilla/gecko-dev/commit/70ebb7d2bacb0d832602f9d91de80d0933b9f4b3)

is there a reason why the full patch was not applied is there issues with it.
anything i can help with.

**Comment by MrAlex94** [comment]
It says in that bug it's landing in 41. I haven't applied any of that patch, what's there is currently in the same version of Firefox.

**Comment by nixiValor** [comment]
the current modifications to

```
js/src/builtin/SMID.cpp
js/src/gc/Marking.cpp
js/src/gc/Nursery.cpp
js/src/gc/Nursery.h
js/src/jit/EffectiveAddressAnalysis.h
js/src/jit/jitcodeMap.cpp
js/src/vm/debugger.h
js/src/vm/ReceiverGuard.cpp

Below are few examples of changes in watefox not in firefox relative to bug 1163091
js/src/builtin/SMID.cpp
line 19 ++ #include "jsprf.h"

js/src/gc/Marking.cpp
line 42 ++ using mozilla::PodCopy;
line 43 ++ using mozilla::PodZero;

js/src/jit/EffectiveAddressAnalysis.h
line 10 ++ #include "jit/MIRGenerator.h"

js/src/jit/jitcodeMap.cpp
line 1555 ++ JS::ForEachProfiledFrameOp::FrameHandle::FrameHandle(JSRuntime* rt, js::jit::JitcodeGlobalEntry& entry,

js/src/vm/ReceiverGuard.cpp
line 7 ++ #include "builtin/TypedObject.h"
line 8 -
line 11 ++ using namespace js;

```

say otherwise & the changes in the files are not present in firefox 40.0.3 branch when running a diff of waterfox 40.0.3 & firefox.40.0.3 branch.

you have https://github.com/MrAlex94/Waterfox/tree/master/intl/icu the whole tree version different to firefox even firefox nightly which is testing the next safe branch of icu.

there are many changes visible when running a diff of current git branch of waterfox & firefox 40.0.3 did you use or do you use the same code i this git repository for the browser builds you release. if not where can i find its code.
