### ISSUE TITLE
Importing profiles v55

### ISSUE THREAD

**Issue by Scrxtchy** [BrowserWorks/waterfox#200]
Downloaded the build from the website since it's not on the update yet

Importing my profile broke pretty much the entire browser in terms of the extensions and configurations I had imported.
the extensions where all loaded, at a default state from my brief experiance.

I don't use a default profile, and it imported from whatever source, out of the 5 browser profiles I use, none of which were copied over.

Copied over the profiles.ini, deleted the default and copied the appropriate profile folders over directly as a fix

**Comment by MrAlex94** [comment]
Yes sorry, it's quite difficult to import everything without a couple of things breaking. Growing pains for moving away from Mozilla unfortunately 😳

**Comment by grahamperrin** [comment]
Review time. I'm almost certain that things are hugely improved. Close this?
