### ISSUE TITLE
about:debugging cleanup

### ISSUE THREAD

**Issue by Scrxtchy** [BrowserWorks/waterfox#201]
Since putting all the language options into the default installation of Waterfox, the debugging list is filled with around 90 different language packs.

Unsure if there can be anything done about this cleanly

**Comment by MrAlex94** [comment]
Yes, I'm planning to find another way to handle this as it has bloated the download sizes as well.

**Comment by ghost** [comment]
@MrAlex94

Idea A:
- Make separated language installer/portable using a script (see "Tor Browser"'s download page)

Idea B:
- Include only English, and add [Add more] button next to the language selection pulldown menu.
- When the user clicked [Add more], navigate to the Waterfox webpage where user can download separated "language pack".
