### ISSUE TITLE
Enabling Electrolysis goes white

### ISSUE THREAD

**Issue by szepeviktor** [BrowserWorks/waterfox#216]
```js
// e10s
user_pref("browser.tabs.remote", true);
user_pref("browser.tabs.remote.autostart", true);
```
After watching YouTube a couple of minutes the document part of the windows goes white or black.
(screenshot works OK from developer toolbar)

**Comment by MrAlex94** [comment]
Even in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode)?

**Comment by szepeviktor** [comment]
No.
😄 But not even in normal mode.
Closing it for now...
