### ISSUE TITLE
Replace the string Firefox with Waterfox in the private browsing window

### ISSUE THREAD

**Issue by TomJansen** [BrowserWorks/waterfox#217]
In the private browsing window, you see sentences like "With Tracking Protection **Firefox** will block..." and "When you browse in a Private Window, **Firefox** does not save..."

Please change this to Waterfox

**Comment by MrAlex94** [comment]
Thanks! Will change this, looks like it's a hard-coded string.

**Comment by TomJansen** [comment]
Thank you!

**Comment by grahamperrin** [comment]
Fixed.
