### ISSUE TITLE
Linux Freetype2 update causes poor font rendering

### ISSUE THREAD

**Issue by xircon** [BrowserWorks/waterfox#218]
Manjaro Linux thread https://forum.manjaro.org/t/unstable-freetype2-update-causes-poor-font-rendering-in-waterfox/31691

Downgrading to freetype2-2.8-2 fixes, suggested fix improves a little, but still poor.  Firefox is OK.

It is a bug:
https://bbs.archlinux.org/viewtopic.php?id=230087
https://bugzilla.mozilla.org/show_bug.cgi?id=1400721
https://bugzilla.mozilla.org/show_bug.cgi?id=1393467

**Comment by alium** [comment]
fixed via patch from https://bugzilla.mozilla.org/show_bug.cgi?id=1393467.
or backport https://skia.googlesource.com/skia/+/d1f2d15b36f6a6a9d199581b998a7ca924a1f1a8%5E%21

**Comment by alium** [comment]
fixed with 55.1.0.1

**Comment by qifei9** [comment]
I still have this issue in 55.1.0.1

**Comment by alium** [comment]
Ok, this is posible, Archlinux use another source (maybe patched):
https://dl.bintray.com/hawkeye116477/waterfox-deb/pool/w/waterfox/waterfox-kde_55.1.0.1_amd64.deb

**Comment by xircon** [comment]
@qifei9 same here, not fixed

**Comment by MrAlex94** [comment]
Fixed in 55.2.0
https://github.com/MrAlex94/Waterfox/commit/4f725e960f942a09ed03fefc68043cd4d0206f35
https://github.com/MrAlex94/Waterfox/commit/151f16458f86cfd272c5f43861ed25be2ef93c49

Let me know if it still occurs when build is out.
