### ISSUE TITLE
55.1.0 Segfaults on Ubuntu 17.04 & 17.10 (Beta)

### ISSUE THREAD

**Issue by zedzedalpha** [BrowserWorks/waterfox#221]
It auto downloaded the update and I foolishly hit restart so I was locked out until I could redownload 52.0.2 again.    It's started downloading again so I suspect I'll have to downgrade and disable automatic updates when I close the browser again. 

```
Redirecting call to abort() to mozalloc_abort

Segmentation fault

```

Both the .tar.bz and the .deb from [bintray.com/hawkeye116477/waterfox-deb/waterfox](https://bintray.com/hawkeye116477/waterfox-deb/waterfox)

52.0.2 (64-bit) works fine.

**Comment by MrAlex94** [comment]
Ah I'll have to look into why 55.1.0 isn't working on Ubuntu! I may have to downgrade my dev environment, seems to be causing a lot of issues! Apologies, will remedy ASAP.

**Comment by zedzedalpha** [comment]
No worries.  You may want to post something for Ubuntu users about setting it to "Check for updates, but let me choose whether to install them" until it's sorted out.

**Comment by PandaCodex** [comment]
Have you tried building using the config options in https://github.com/MrAlex94/Waterfox/pull/197 you will have to revert https://github.com/MrAlex94/Waterfox/commit/7ff595a6db0433d643fdee65141828e8134cf541 if building it yourself. So it can be built correctly with the right flags.

**Comment by MrAlex94** [comment]
Your flags aren’t different apart from enabling code coverage (which is redundant for a release build, more [here](https://developer.mozilla.org/en-US/docs/Mozilla/Testing/Measuring_Code_Coverage_on_Firefox) and not statically linking libgcc. No need to change anything.

A local build will solve the issue though 🙂, just happens I’m using Fedora 26 which is using very up to date packages and linking against them too.

@zedzedalpha, have posted in the release notes about, will tweet a bit later on about it as well.

**Comment by hawkeye116477** [comment]
It's strange, because it works on Ubuntu 14 and 16, but doesn't work on Ubuntu 17.

**Comment by grahamperrin** [comment]
If it helps: 56.0.2 and 56.0.3 run for me on Kubuntu 17.10. From https://www.waterfoxproject.org/downloads

----

@zedzedalpha can you verify the fix? If so, please close this issue. Thanks.

**Comment by hawkeye116477** [comment]
@grahamperrin It's already fixed from some time ago. Waterfox and waterfox-kde from my apt repository also contains this fix :smile:.

**Comment by grahamperrin** [comment]
Review time. Close this?
