### ISSUE TITLE
Impossible to build  

### ISSUE THREAD

**Issue by nyancat18** [BrowserWorks/waterfox#223]
Host, manjaro

version 55.1

https://p.teknik.io/wczFe

**Comment by nyancat18** [comment]
it eats all ram avaible and you need turn off your pc

itsnt a "mach" issue *cliqs build fine*

i've 16 ram

**Comment by MrAlex94** [comment]
From a quick glance I can see you don’t have the jobs flag set, so it doesn’t seem you are overloading your system. 

You do have a lot of config options though and seem to be using Clang 5 which may be an issue. I’ll check Bugzilla in a bit to see if there are any bugs related to Clang 5 and building Firefox.

**Comment by hawkeye116477** [comment]
@nyancat18 I see that you try to build waterfox-kde, which I'm maintainer of that package. I also have Manjaro Linux (stable) and Clang 5 and for me build is succesfull. It maybe problem with new glibc, someone from Manjaro Team also have that problem -> https://github.com/manjaro/packages-community/issues/370. Try to replace ucontext patch with this https://git.archlinux.org/svntogit/packages.git/plain/trunk/glibc-2.26-fix.diff?h=packages/firefox and reply me if that helps.

**Comment by hphilm** [comment]
The issue is with **freetype v2.8.1** and maybe with **glibc v2.26**.

**Comment by nyancat18** [comment]
@hawkeye116477 @philmmanjaro
with https://git.archlinux.org/svntogit/packages.git/plain/trunk/glibc-2.26-fix.diff?h=packages/firefox     i'll fix it?

>i'll test at some hours  (i've some updates,  after  i finish this i test)

>glibc 2.26-4 (base)

**Comment by hawkeye116477** [comment]
@nyancat18 I don't know, because I have freetype2 v2.8-2 and glibc v2.26 and I don't have that problem. So you must test it yourself. If it doesn't work anyway, you probably should downgrade to freetype2 v2.8 or just install waterfox-kde-bin. Well, unless there is some other solution yet that I do not know about it.

**Comment by nyancat18** [comment]
doh   


i'm testing now   

>configure and lesser jobs

**Comment by nyancat18** [comment]
with the new patch *replace ucontext with this ff bugfix*, failed again

**Comment by nyancat18** [comment]
@mralex94 yeah
>clang5 
and  only clang (no clang-tools-extra)  

i've the number of jobs added as a flag 

>X=$(bc <<< "1*$(getconf _NPROCESSORS_ONLN)")
>mk_add_options MOZ_MAKE_FLAGS=-j${X%.*}


i've replaced this with
>mk_add_options MOZ_MAKE_FLAGS=-j7  

i've an fx 8350

**Comment by hawkeye116477** [comment]
@nyancat18 Try new version from aur.

**Comment by grahamperrin** [comment]
@nyancat18 please, how are things now – can you build 56.0.3?

**Comment by grahamperrin** [comment]
Is this still an issue? Maybe time to close …
