### ISSUE TITLE
No sound using ALSA and JACKD

### ISSUE THREAD

**Issue by breescorner** [BrowserWorks/waterfox#224]
Hello, I have no sound or video. Is it possible to use Waterfox with ALSA and Jackd? (I disable pulseaudio for recording reasons).

Other than that... it's a beautiful browser. Thx!

----
my OS: Ubuntu 14.04

**Comment by hawkeye116477** [comment]
Waterfox is compiled with Pule Audio and Alsa support, but without Jack support, so should work with Alsa.

**Comment by bitofhope** [comment]
I'm getting no sound on jackd and ALSA.
Output to terminal as follows:

```
Sandbox: seccomp sandbox violation: pid 6103, tid 6139, syscall 49, args 43 139714318655344 110 21 13 0.
Cannot bind server to socket err = Function not implemented
Cannot bind socket
Cannot connect to the server
```

which appear once I attempt to play audio. All other ALSA applications are working normally.

**Comment by criztovyl** [comment]
Maybe even try https://github.com/jackaudio/jackaudio.github.com/wiki/WalkThrough_User_PulseOnJack

**Comment by bitofhope** [comment]
I was specifically using Waterfox so I wouldn't have to use Pulseaudio, though.
I can manage with mpv and youtube-dl for my audio needs for now.

**Comment by breescorner** [comment]
@bithope Me too. I'm hunting for the perfect browser for my audio system. I'm dependent on Jackd to control ALSA, and have pulseaudio disabled.

**Comment by iiv3** [comment]
WaterFox 55.2.2 does use ALSA on my system. I also don't have Pulse Audio installed. (The replacement "apulse" already support Firefox playback, but I do prefer native ALSA).

I would actually ask @hawkeye116477  to disable/unload jackd for waterfox and see if it works with native ALSA.

---

I do suspect that the problem might be combination of browser sandboxing and alsa->jackd wrapper.
Simply put, if audio is not opened before the sandboxing is enabled (like it is done for pulse), then you have to make a special exception for the files it uses (like it is done for ALSA). I do suspect that the jack wrapper is not exempt.

I looked up this subject when FF deprecated ALSA. This link might be useful:
https://bugzilla.mozilla.org/show_bug.cgi?id=1309098#c18

**Comment by grahamperrin** [comment]
[Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)

**Comment by MrAlex94** [comment]
Any updates?

**Comment by grahamperrin** [comment]
2019.10 (20191023220600) and 2019.10 (20191023104314) on Manjaro Linux: 

![image](https://user-images.githubusercontent.com/192271/68514867-e46d8280-0276-11ea-8a65-e4b0a6df890e.png)

Respectively: 

`--target=x86_64-pc-linux-gnu --enable-application=browser --enable-update-channel=release --disable-tests CC=clang CXX=clang++ --enable-release --enable-av1 --enable-stylo=build --enable-rust-simd MAKE=/usr/bin/make --enable-alsa --disable-crashreporter --disable-maintenance-service '--enable-optimize=-O2 -march=nocona -mtune=nocona -w' --enable-pulseaudio --disable-signmar --enable-updater --disable-verify-mar --with-app-basename=Waterfox --with-app-name=waterfox --with-branding=browser/branding/unofficial --with-distribution-id=org.waterfoxproject`

`--enable-application=browser --target=x86_64-pc-linux-gnu --enable-update-channel=aurora --disable-tests '--enable-optimize=-O2 -march=nocona -mtune=nocona -w' CC=clang CXX=clang++ --enable-alsa --enable-rust-simd --disable-verify-mar MAKE=/usr/bin/make --disable-crashreporter --disable-signmar --enable-updater --with-app-basename=Waterfox --with-app-name=waterfox --with-branding=browser/branding/waterfox --with-distribution-id=net.waterfox`

----

PS is this comment misplaced? It was primarily a response to today's ALSA-related https://www.waterfox.net/blog/waterfox-2019.10-release-download/#commento-comment-card-a40711b67ba344b9a071867384af676ae98577ac9d0875a5a8c75489178f1733
