### ISSUE TITLE
Fix Waterfox making too may writes for SSDs

### ISSUE THREAD

**Issue by ROCKNROLLKID** [BrowserWorks/waterfox#225]
By default, Firefox sets browser.sessionstore.interval to every 15 seconds. While this isn't a issue on HDDs, SSD users like me suffer from too many writes (up to 20gb per day). Most people don't know how to about:config commands. Is there a way to add some kind of check if a user is on a SSD and set the value much higher, like maybe every hour or so?

**Comment by juneyourtech** [comment]
The entire session store thing might need re-architecting to something more granular/atomic that would remove the need to reconstitute places.sqlite all the time. I'm not a developer, though.

**Comment by MrAlex94** [comment]
[This comment](https://news.ycombinator.com/item?id=12566008) from [this thread](https://news.ycombinator.com/item?id=12565023) should give some insight.

**Comment by juneyourtech** [comment]
@MrAlex94 A +1 just for the fact that you gave me a link to it. I read the whole discussion. The re-architecting of session restore seems to have been on the back burner at Mozilla for far too long.

How many other people are maintaining WaterFox with you?

**Comment by ghost** [comment]
Be it Firefox or now Waterfox I've always had my profile installed on a RAMdisk (Dataram in my case). All (or practically all) Waterfox session disk operations being performed in RAM is truly beneficial. Allows as well the following setting which may be risky on a non RAM disk:
```
// SQLITE DISK SYNC MODE - 0: risky sync mode - 1 (default): safe sync mode - 2: extra-slow-extra-safe sync mode.
user_pref("toolkit.storage.synchronous", 0); // ONLY ON RAMDISK
```
Disk cache disabled, memory cache set to 1GB, 250 MB RAMdisk only is fine to handle my Waterfox profile together with my Thunderbird profile (with mail nevertheless on hard disk!).

**Comment by grahamperrin** [comment]
Mozilla bug [934967 - [Session Restore] Read/write data with lz4](https://bugzilla.mozilla.org/show_bug.cgi?id=934967#c5)

> RESOLVED FIXED in Firefox 56

**Comment by grahamperrin** [comment]
> ## … writes for SSDs

Suggested reading: 

- [Firefox 57 high wear and tear of ssd? : firefox](https://www.reddit.com/r/firefox/comments/7f4fuj/firefox_57_high_wear_and_tear_of_ssd/)
- [Is the whole “Firefox kills your SSD”thing still true? : firefox](https://www.reddit.com/r/firefox/comments/7iotkm/is_the_whole_firefox_kills_your_ssdthing_still/)
- [Firefox seems to be thrashing my hard drive : firefox](https://www.reddit.com/r/firefox/comments/875dhq/firefox_seems_to_be_thrashing_my_hard_drive/) with reference to Mozilla bug [1441918 - Antimalware Service Executable very active when using Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1441918)

Cross reference: 

- [Firefox "eating" SSD. What about waterfox? : waterfox](https://www.reddit.com/r/waterfox/comments/9vcr2b/firefox_eating_ssd_what_about_waterfox/)

> … `browser.sessionstore.interval` …

Follow: 

- Mozilla bug [1330635 - (ss-perf) Sessionstore performance tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=ss-perf)
