### ISSUE TITLE
DRM checkbox is still present, even though DRM is supposed to be eradicated (tested on macOS)

### ISSUE THREAD

**Issue by magicgoose** [BrowserWorks/waterfox#226]
<img width="829" alt="screen shot 2017-09-28 at 08 52 51-or8" src="https://user-images.githubusercontent.com/1442206/30951290-c6ec3f5a-a42a-11e7-9ca3-55149e5054f9.png">

I think it should be absent or grayed out or something, if this is purely visual phenomena.

Latest version, installed from official .dmg (sha256 = 9d1cacde04a5fa27994e4b6d0cfa789d6890fbe1bd33aca0e62fc3d1b21eca48); macOS 10.12.6. Profile imported from regular Firefox.

**Comment by criztovyl** [comment]
Feature list just says "disabled EME" not "removed EME", which means DRM, so I think you can still enabled it?

[![bildschirmfoto vom 2017-09-28 08-09-50](https://user-images.githubusercontent.com/2174918/30951651-6f50037c-a424-11e7-9291-5321d3f97b7a.png)](https://www.waterfoxproject.org/)

*Edit: EME &rarr; DRM.*

**Comment by magicgoose** [comment]
Hmm, really… I should have read it more carefully. I've heard from some other people that it's "removed" and got confused.

So, some users actually want it? Or it is not very easy to remove while keep code easy to merge with upstream?

**Comment by criztovyl** [comment]
IIRC the DRM is nonfree and Firefox downloads it on demand (and so Waterfox would do too) so I guess some users want to have the possibility to enable and disable it as required.

(btw; what about DRM click-to-play? Only if it's enabled and not yet a thing, though.)

**Comment by MrAlex94** [comment]
It was completely removed, but was requested to be added back as optional. 

This way it is not downloaded unless specifically requested.

**Comment by ghost** [comment]
various big sites are basically forcing you to use it....
This is why some users need it.

**Comment by magicgoose** [comment]
> This is why some users need it.

—
>  This is why some users think they need it, but really they need to stop depending on these sites.

that would be more fair IMO
