### ISSUE TITLE
Peculiar behavior with the latest update

### ISSUE THREAD

**Issue by stefanos82** [BrowserWorks/waterfox#228]
Hey @MrAlex94, I hope you are doing well mate.

After I restarted my browser, the latest update was installed and have noticed a rather peculiar behavior with the latest version.

Whatever I do, either I click on a link or type a website on address bar, it freezes like 5 to 10 seconds and then loads it.

I have noticed from my task manager (XFCE4) that it uses 100% of a single core and every 2 seconds it switches to a different core until it loads the website.

This behavior is rather weird I must admit.

I'm using Debian testing 64-bit fully updated on a daily basis.

Is there anything I could check to remedy this rather awkward behavior?

Cheers.

P.S.: If you can speak Greek, it would be fantastic mate. My English is of a mediocre level and I don't always feel comfortable...

**Comment by MrAlex94** [comment]
Your English is fine, don't worry! My Greek has gotten rusty since I moved away from Cyprus, so I'll try English for now.

Could you try in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode)?

If it doesn't make much difference in general browser, I think I may know the issue and it will be resolved in 55.2.0 🙂, specific to Linux distros.

**Comment by stefanos82** [comment]
Oh, a compatriot, HA! lovely 😄 

OK, I will play around with Safe Mode and I will let you know.

**Comment by grahamperrin** [comment]
@stefanos82 please, how are things with 56.0.3? Can we close this issue?

**Comment by stefanos82** [comment]
I'm still on 56.0.2 for some reason. 

Why can't I get any updates?

Performance-wise, it feels a bit better than before.

**Comment by grahamperrin** [comment]
> … Why can't I get any updates? …

If you're bugged by anything like https://github.com/MrAlex94/Waterfox/issues/361 then you can download a full installer from <https://www.waterfoxproject.org/downloads>.

----

> … Performance-wise, it feels a bit better …

Try 56.0.3 in safe mode. Better than 56.0.2 in normal mode?

Does Mozilla's [Add-on Compatibility Reporter](https://addons.mozilla.org/addon/add-on-compatibility-reporter/) reveal any extension that's not compatible with multi-process Firefox? If so, then with Waterfox 56.0.3 you should manually **disallow multi-process** Waterfox before working with that extension.

**Comment by stefanos82** [comment]
I upgraded manually for the second time. The first was with version 55.x to 56.x and I don't think this is convenient to do every single time.

Normal mode or safe mode, the behavior is the same most of the time.

With Chromium I load websites immediately; with Firefox and Waterfox can get delays of 5 to 10 seconds, not with all pages but with the majority of them for some peculiar reason.

**Comment by MrAlex94** [comment]
Sorry about that @stefanos82, I'm working on improving the update system massively. I just don't push updates to any specific builds that I haven't tested/think will cause too many issues which is probably why then you've checked for updates they haven't been available until I've gotten things to a reasonable state.

Starting with 56.1.0+, things will be working a lot more smoothly.

**Comment by stefanos82** [comment]
@MrAlex94 can you please change the way auto-upgrade takes place?

It just crashed my browser while I was chatting in web.skype.com in order to force an upgrade **without letting know about it**.

This is a crucial issue mate, it's really important. Imagine what would have happened if I was in the middle of a bank transaction!

Also, can you please fix the `Submit Feedback` option not to send me to Firefox?

**Comment by grahamperrin** [comment]
> … `Submit Feedback` …

That's a separate issue. Please subscribe to: 

- [Waterfox ▸ Help ▸ Submit feedback… · Issue #399 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/399#issuecomment-361037167)

-----

Also: with this issue originally focused on five–ten second _freezes_, it will probably be useful to raise a separate issue for any _crash_. Thanks.

**Comment by grahamperrin** [comment]
Review time. Focusing: 

> … freezes like 5 to 10 seconds and then loads it. …

Is that still an issue with 56.1.0, with Stylo disabled?

**Comment by stefanos82** [comment]
Most of the times, yes, but not always; it's still the same behavior I'm afraid.

**Comment by grahamperrin** [comment]
Thanks. Better with 56.2.0?

#538

**Comment by stefanos82** [comment]
@grahamperrin I will need a couple of days to stress it enough to see how the latest version behaves.

I have updated it a couple of minutes ago and when opening multiple tabs it still behaves the same; but when I load one link at a time, I can see a slight difference in performance.

**Comment by grahamperrin** [comment]
Thanks. 

Do you use Dolphin?

----

At http://mdn.github.io/to-do-notifications/ do the bullet points near the foot of the page include the point below? 

> - Database initialised.
