### ISSUE TITLE
Unwanted tooltips since WF 55.x (cause=enabling e10s)

### ISSUE THREAD

**Issue by GitCurious** [BrowserWorks/waterfox#230]
I am seeing unwanted popup tooltips on web content since WF v55

It does not happen with WF v54

I can not see any about:config settings or browser options that control this, also I do not see any references in the Firefox changelogs that this is a new "feature"

An example image showing exactly what I mean:

![2017-09-30_090015](https://user-images.githubusercontent.com/18083484/31044411-d29071f8-a5c6-11e7-831c-234fd9739ba1.png)

This example is from a random Amazon link but it happens on other sites as well.

Has anyone else noticed this new behaviour ?
and more importantly, has anyone found a way to revert it back to normal - not showing these annoying tooltips ?

**Comment by MrAlex94** [comment]
Is it possibly a Windows change? If not, this thread [comment](https://support.mozilla.org/en-US/questions/1081366#answer-776018) is still relevant and you can follow the same steps.

**Comment by GitCurious** [comment]
Thanks Alex, 

I always had browser.chrome.toolbar_tips turned off....
and this _still_ works OK on the UI toolbar tooltips

but I did figure out what is the cause of these "Title" tooltips appearing recently on web page content,
it is because I had recently enabled the "Enable multi-process Waterfox" setting.

When I turn that off, they disappear (!)

I never imagined it could be that.
