### ISSUE TITLE
Support for Google Hangouts

### ISSUE THREAD

**Issue by kenorb** [BrowserWorks/waterfox#231]
I'm trying to join Hangouts call at https://hangouts.google.com/, but I've got the error:

> Plug-in blocked

> Hangouts requires the Google Talk plug-ins to make calls. Click the Unblock or Trust button at the top of your browser to enable them. [Learn more.](https://support.google.com/hangouts/?p=plugin&hl=en-GB)

I don't have any option to unblock the plug-in.

**Comment by grahamperrin** [comment]
What's your operating system and version? 

Is the issue reproducible with Waterfox 56?

Do your microphone and camera pass the tests at [WebRTC Troubleshooter](https://test.webrtc.org/)?

----

[Gigaom | So long plug-ins, Google Hangouts works with WebRTC](https://gigaom.com/2014/07/06/so-long-plug-ins-google-hangouts-works-with-webrtc/) (2014-07-06)

[How does Hangouts use WebRTC? webrtc-internals analysis - webrtcHacks](https://webrtchacks.com/hangout-analysis-philipp-hancke/) (2014-07-29)

From [Hangouts video and phone calls in Firefox - Hangouts Help](https://support.google.com/hangouts/answer/7334146)  (2017-02-24): 

> ... Firefox is ending support for plug-ins, so Hangouts won’t be able to support video and phone calls in Firefox until Hangouts is updated to resolve the problem. Google is working on a solution ...

-- Google presents that help where a video error occurs with a WebRTC-compatible browser, which seems wrong to me.

**Comment by kenorb** [comment]
I'm on macOS Sierra. Will re-try with 56 soon.

**Comment by kenorb** [comment]
The latest I can update to is 55.2.2 (64-bit), how I can test it with 56?

**Comment by grahamperrin** [comment]
Re: https://www.waterfoxproject.org/downloads Sierra should meet the requirements for Waterfox 56.0. 

----

Considering the recent expert response https://productforums.google.com/d/msg/hangouts/BRemM5VUnTQ/AkcMqs95BgAJ (2017-11-16) to a question about compatibility with Firefox Quantum (57), I'm not hopeful about compatibility of Hangouts with Waterfox … but I follow this with interest. (Over the weekend, I tested Hangouts and a few other WebRTC-based solutions).

**Comment by kenorb** [comment]
Actually it did work in v55.2.2, as I didn't notice small icon where I can actually unblock the plugin.

<img width="829" alt="screen shot 2017-12-12 at 11 11 21" src="https://user-images.githubusercontent.com/266306/33884740-ca92a2b8-df38-11e7-84fd-e0a883cc0fdb.png">

**Comment by grahamperrin** [comment]
I reported an issue to Google. 

Hangouts now works for me with Waterfox 56.0.1 **without** a plug-in. 

```text
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # date ; uname -v
Tue 19 Dec 2017 16:44:42 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # pkg info waterfox | grep -i version
Version        : 56.0.1.s20171212
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # 
```
