### ISSUE TITLE
55.2.0 won't start in Mac OS Mavericks

### ISSUE THREAD

**Issue by derralf** [BrowserWorks/waterfox#233]
Waterfox 55.2.0 won't start in Mac OS 10.9.5
Errors:

```
waterfox[997]: -[BorderlessWindow setTitleVisibility:]: unrecognized selector sent to instance 0x11eaec880
```
```
waterfox[997]: Mozilla has caught an Obj-C exception [NSInvalidArgumentException: -[BorderlessWindow setTitleVisibility:]: unrecognized selector sent to instance 0x11eaec880]
```

**Comment by grahamperrin** [comment]
Here: Waterfox 56.0 launches without error on build 13F1911 of Mac OS X 10.9.5.

**Comment by grahamperrin** [comment]
@derralf would you like to close this issue? 

Or (with Waterfox 56.x) is there still a problem for you?

**Comment by grahamperrin** [comment]
Review time. Close this? 

For me, all recent releases of Waterfox have launched on Mavericks.
