### ISSUE TITLE
Icons top left missing

### ISSUE THREAD

**Issue by sjorzel** [BrowserWorks/waterfox#237]
Since the last update the red, yellow and green icons in the top bar have been missing. Switching the theme doesn't solve this problem, a fresh install neither.
<img width="1392" alt="schermafbeelding 2017-10-06 om 09 17 26" src="https://user-images.githubusercontent.com/4116478/31267116-3798954e-aa77-11e7-9314-a938ee5fc099.png">

**Comment by MrAlex94** [comment]
Unfortunately an issue with macOS 10.13 systems :-(. Waiting for Mozilla's patches to fix!

**Comment by grahamperrin** [comment]
Not reproducible with _Default_ or _Compact Light_ themes with Waterfox 56.0.4.1 in safe mode on (slightly outdated) pre-release build 17E139J of Mac OS X 10.13.4.

**Comment by grahamperrin** [comment]
Review time. If I recall correctly, this was fixed.
