### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by l29ah** [BrowserWorks/waterfox#238]
It would be awesome if you tagged the releases, as it looks like you don't publish the source snapshot archives along with the binaries, and this is a hassle for source-based distros, while github can generate the archives for every tag automatically.

**Comment by grahamperrin** [comment]
At <https://github.com/MrAlex94/Waterfox/issues/442#issuecomment-366858384> @AjvarXX wrote: 

> … I would like to beta test this fix …

+1 to beta testing, if it's manageable.
