### ISSUE TITLE
dom.battery.enabled should be set to false by default

### ISSUE THREAD

**Issue by hook321** [BrowserWorks/waterfox#239]
https://www.reddit.com/r/privacytoolsIO/comments/3fzbgy/you_may_be_tracked_by_your_battery_status_of_your/

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/670b2bb2f4e6fe10a24c8807d360d6a618ecbfd3

**Comment by grahamperrin** [comment]
#1170
