### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by guilhermemarconi** [BrowserWorks/waterfox#24]
Hey guys.

I heard about Waterfox and think it's really cool! But I did not found a Linux version.

Today I use Ubuntu and it would be great to testing Waterfox here.

What do you think? :smile:

**Comment by patrick-othmer** [comment]
+1. Would be really nice

**Comment by edmundcraske** [comment]
Bit disappointed that the website just says 'Download for PC' when really it means 'Download for Windows'...

**Comment by MrAlex94** [comment]
Linux is definitely on the cards, but ICL on Linux is much different to Windows, so its got some really strange errors. Might use Clang for Linux instead like on Mac.

@edmundcraske, I updated it to Windows rather than PC earlier today. Apologies.

**Comment by nick149** [comment]
Could you download the source code and install/compile it from source?

**Comment by DaAwesomeP** [comment]
+1 While there is a 64-bit version from Mozilla, it doesn't have the noticeable improvements that Waterfox has.

**Comment by Serkan-devel** [comment]
+1 for LInux support

**Comment by fengchenxiujisd** [comment]
+1 for LInux support

**Comment by Tim-NL** [comment]
+1 for Linux support ^^

**Comment by pangzhaiwei** [comment]
+1 for Linux support

**Comment by Serkan-devel** [comment]
Is this issue actually noticed?

**Comment by Serkan-devel** [comment]
Even google ultron is LInux confirmed https://github.com/jcpyun/googleultron/issues/1

**Comment by MrAlex94** [comment]
It's finally here everyone and it has been a long time coming 🙃

Built with Clang :-)

[DOWNLOAD](https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-50.0.en-US.linux-x86_64.tar.bz2)

**Comment by fengchenxiujisd** [comment]
version `GLIBCXX_3.4.21' not found ..

**Comment by MrAlex94** [comment]
@fengchenxiujisd, could you try installing the libstdc++6 package?

**Comment by fengchenxiujisd** [comment]
@MrAlex94,thank you.
libstdc++6 version lower..
