### ISSUE TITLE
All tabs lost and infected by araby online since 03 October 2017 release

### ISSUE THREAD

**Issue by juanitotc** [BrowserWorks/waterfox#240]
Once waterfox (win64) rebooted after the 03 Oct 2017 update, all my tabs were lost and each time I reboot I get the home page for the malware araby online.

Regedit doesn't find "araby" anywhere - is it hidden in the new waterfox profile somewhere?

How do I get rid of araby online from waterfox?

**Comment by hook321** [comment]
Open your other browsers and see if the same thing happened

**Comment by juanitotc** [comment]
The only other browser I have is chromium and it does not happen with that.

**Comment by juanitotc** [comment]
Is there any update on this?

There has been one more update to waterfox, but the problem remains - on re-boot all my open tabs are lost and the startup tab is reset to arabyonline.

**Comment by criztovyl** [comment]
Maybe it's installed as a global plugin. Check `%APPDATA%/Mozilla/Firefox`, there should be an "plugins" or "addons" folder (dont know the correct name currently.)
Losing your tabs seems also be caused by arabyonline - it hijacks the file that stores your session.

Anyway, I think that, as this is not an problem with Waterfox itself, this issue tracker meight be the wrong place to ask. I unfortunately do not know where is a better place.

**Comment by criztovyl** [comment]
The correct path to look for the global extension seems to be `%APPDATA%\Mozilla\Extensions`.

**Comment by juanitotc** [comment]
That folder is empty.

I did not have the arabyonline problem prior to the last but one waterfox update...

**Comment by criztovyl** [comment]
The last updates comes with this note, the config/settings reset may caused arabyonline to re-appear.

>NOTE: SOME SETTINGS (INCLUDING ADD-ONS) MAY BE RESET! Unfortunately due to the way the profile import works, this was necessary. You CAN change which profile to use, the same way as Firefox, if you’d like to use the old location. There will be teething issues, please be patient and just report any issues you do have, I will try my best to have them resolved.

I can help you trying to uninstall arabyonline, but you will need to share a list of your installed programs (if you do not want to attach them here, you can send the screenshots to mail@criztovyl.space):
Go to Control Panel &rarr; Programs and screenshot the list page by page using the Snipping Tool, then we can try to find the malicious program.

**Comment by juanitotc** [comment]
Thanks for the offer of help - email sent.

**Comment by criztovyl** [comment]
We went off into an 1:1 Mail conversation and solved the problem now.

- arabyonline was set as an start parameter in `user.js`
- session did not restore b/c of the config/session reset of v55 and had to enabled again in Preferences ("When Waterfox starts").

Thx.

**Comment by criztovyl** [comment]
@juanitotc @MrAlex94 I think this issue can be closed.
