### ISSUE TITLE
Using `xdg-open` on links from shell just loads homepage in new window

### ISSUE THREAD

**Issue by v4violet** [BrowserWorks/waterfox#2404]
### What happened?

When using `xdg-open` to open links from shell it opens a new window to the homepage

**Expected:**
`xdg-open "https://google.com"` opens https://google.com in the currently open window

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by v4violet** [comment]
Whoops, did some research into how `xdg-open` works and found that a `.desktop` file (which i cant find for waterfox so i made my own) requires `%u` to open the program correctly

**Comment by v4violet** [comment]
As an after-note, i would be nice to have a `.deb` or other install format file available for easy install for new users (such as myself)

**Comment by brianpeiris** [comment]
Just to make this explicit to anyone else. In your waterfox.desktop file, you need to add `%u` at the end of the `Exec=` line. For example:

```
Exec=/path/to/waterfox %u
```
