### ISSUE TITLE
beacon.enabled should probably be set to false by default

### ISSUE THREAD

**Issue by hook321** [BrowserWorks/waterfox#241]
https://rationallyparanoid.com/articles/firefox-about-config-security.html
There could be a reason to have it enabled that I don't know about though.

**Comment by ltGuillaume** [comment]
👍

**Comment by ydf** [comment]
also like dom.serviceWorkers.enabled

**Comment by grahamperrin** [comment]
> … `dom.serviceWorkers.enabled`

[Get rid of service workers. · Issue #545 …](https://github.com/MrAlex94/Waterfox/issues/545)
