### ISSUE TITLE
LastPass not working 100%

### ISSUE THREAD

**Issue by foreachthing** [BrowserWorks/waterfox#247]
Using Waterfox 55.2.2 (64-bit) and LastPass 4.1.54.

Whenever I go to a website with a stored login/password, I can not get "Show Matching Sites" working. "Show Matching Sites" is _always_ empty.
Also empty is the menu "Sites". It does list the created folders - but those are empty as well.

Workaround: I need to go to "My Vault", search for the site to login from there.

All this works with FF 55.0.3 (64-bit).

If you need more information, please let me know.

**Comment by lilking420** [comment]
I fixed this yesterday with the LP Beta found here... [http://lastpass.com/lastpass_password_manager-4.1.80.2beta-an+fx.xpi](url)

which i found on this page... [https://blog.lastpass.com/2017/10/lastpass-beta-firefox-57.html/](url)
it seems an issue with lastpass rather than waterfox... 
HTH!

**Comment by foreachthing** [comment]
Sweet! Thanks for the hit with the beta.
This works: http://lastpass.com/lastpass_password_manager-4.1.80.2beta-an+fx.xpi in WF 55.2.2

**Comment by lilking420** [comment]
You are quite welcome.  Lastpass is an addon that i cannot go without.  Glad it helped!
