### ISSUE TITLE
Printer Default Does Not Reset

### ISSUE THREAD

**Issue by jayemayjay** [BrowserWorks/waterfox#248]
Waterfox saves last successful printer configuration as default and does not reset to OS printer defaults, even after Waterfox is closed and reopened. For example, changing Waterfox to print lanscape for ONE job is now default for EVERY subsequent job unless options are manually changed back. Closing and restarting Waterfox has no effect. Current version is 55.2.2 (64-bit), but this has been an issue since I began using Waterfox back at version 40.?.?. Currently running Windows 10 Home (64-bit).

**Comment by MrAlex94** [comment]
What if your preference setting for **print.use_global_printsettings**?

There seems to be a fair few [unresolved bugs](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=Printer+default) in relation to this.

**Comment by jayemayjay** [comment]
Sorry to sound like I do not know, but I do not: where would this setting be made / input. I am guessing it is located somewhere other than the Settings GUI. In fact, I cannot find ANY printer configuration settings in the GUI. Appreciate the assist!

**Comment by MrAlex94** [comment]
Ah apologies! If you type about:config into the address bar, you will find a large amount of configurations settings. There should be a search box for you to type in, if you could find out what print.use_global_printsettings value is, that would be a good starting point.

**Comment by jayemayjay** [comment]
Thank you! print.use_global_printsettings value is set to true
