### ISSUE TITLE
Limited Search engines configuration

### ISSUE THREAD

**Issue by Kiude** [BrowserWorks/waterfox#249]
Hello everyone!

I'm a very fresh WF user as the upcoming 57-FF made me discover this alternative to keep using my favorite addons world :)

I'm having an issue with the search engines configuration. Even though I associated a keyword/key-letter to my favorite search engines, I don't see them appear on the SE list in the settings menu. Or in the search engine suggestions when writing directly in the address bar.

Does anyone know what is up with it? Any trick to fine-tune all the search engines available to me on my profile? Thx! :)

**Comment by grahamperrin** [comment]
> … associated a keyword/key-letter …

With Waterfox 56.0.4.1, I (temporarily) made something other than Ecosia the default, then associated Ecosia with keyboard _cosy_. 

With _cosy_ as a prefix to a search term, Ecosia was used. 

@Kiude would you like to close this issue? Thanks.
