### ISSUE TITLE
Update of Waterfox in Google Play Store? 

### ISSUE THREAD

**Issue by bla-ke** [BrowserWorks/waterfox#251]
Hello! 

It's just a question. In Google Play Store you can find Waterfox (https://play.google.com/store/apps/details?id=com.waterfox.waterfox), but it's a release form 2015 (sic!). Is somebody going to update it? Or maybe it's a fake application? Versions from Play and from the website are different. 

Thank you for your reply :)

Greetings, Daria

**Comment by Syping** [comment]
from my little research it seems inofficial, they might have to pull it down from the Store first and have to say they are the actual creator of the project.

See: Storm Technologies -> Storm Browser
They might could have uploaded the Waterfox browser to silent promote their own

**Comment by PandaCodex** [comment]
MrAlex made it with a third party, along side Waterfox search when he tried to make his own search engine, it was released in the apple store also, but was never maintained by ether party and seemed to only function for searching not like Mozilla version of the browser. Lots of promises but died off sadly

**Comment by Serkan-devel** [comment]
https://github.com/MrAlex94/Waterfox/issues/143
https://github.com/MrAlex94/Waterfox/issues/234
Might be relevant to this discussion

**Comment by Serkan-devel** [comment]
There is an apk-download on their website https://www.waterfoxproject.org/downloads
But I'm actually waiting for an F-Droid release.

**Comment by bla-ke** [comment]
Hi, thank you so much for your replies! 

Because this topic is similar to others, I'm gonna close it.

The best wishes, Daria

**Comment by MrAlex94** [comment]
Yes so the app on the play store is from when I tried to make a spin-off startup of making a search engine where the revenues went to charity that the user wanted. Unfortunately, it buckled but since the company is no more I can't request Google to remove it from the play store which is annoying as the app is broken and doesn't work very well!

**Comment by bla-ke** [comment]
Oh... I feel sorry :cry:...

It seems the only one way is F-Droid. Thank you so much for your reply, Alex :).
