### ISSUE TITLE
56.*

### ISSUE THREAD

**Issue by ZatsuneSakurako** [BrowserWorks/waterfox#252]
There's still no 56 version is it normal?

**Comment by dimqua** [comment]
Yes, since v55.2 already include v56 security fixes from upstream. 
See: https://www.waterfoxproject.org/blog/waterfox-55.0-release-download

**Comment by alium** [comment]
can you read ? Release 56 around mid to end October. https://www.waterfoxproject.org/blog/waterfox-55.0-release-download
if be have a time. MrAlex94 is human, not robot...

**Comment by ZatsuneSakurako** [comment]
I didn't see, and don't worry, I understand that.
