### ISSUE TITLE
Allowing anonymous user stylesheets

### ISSUE THREAD

**Issue by rnhmjoj** [BrowserWorks/waterfox#253]
More than 10 years ago in an attempt to fix a stupid [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=285140) Mozilla [completely disabled](https://bugzilla.mozilla.org/show_bug.cgi?id=424184) styling anonymous elements via userContent.css.

The motivation was preventing "non-technical" people from messing up the browser when copy-pasting themes into user{Chrome,Content}.css. Nowadays almost nobody uses this method anymore and people modifying these files probably know what they are doing.
Moreover even web-extensions can't touch these style so there is absolutely no way to customize elements like scrollbars and player UI in recent Firefox versions.

I tried to remove the checks that filter out the user style but my patch is not entirely working:
the style seems to be only partially applied, some rules doesn't work and I can't figure out why.

```patch
--- a/layout/style/nsStyleSet.cpp
+++ b/layout/style/nsStyleSet.cpp
@@ -1124,9 +1124,7 @@
   bool haveImportantUARules = !aRuleWalker->GetCheckForImportantRules();
 
   aRuleWalker->SetLevel(SheetType::User, false, true);
-  bool skipUserStyles =
-    aElement && aElement->IsInNativeAnonymousSubtree();
-  if (!skipUserStyles && mRuleProcessors[SheetType::User]) // NOTE: different
+  if (mRuleProcessors[SheetType::User]) // NOTE: different
     (*aCollectorFunc)(mRuleProcessors[SheetType::User], aData);
   nsRuleNode* lastUserRN = aRuleWalker->CurrentNode();
   bool haveImportantUserRules = !aRuleWalker->GetCheckForImportantRules();
@@ -1144,7 +1142,7 @@
                                static_cast<ElementDependentRuleProcessorData*>(aData),
                                &cutOffInheritance);
   }
-  if (!skipUserStyles && !cutOffInheritance && // NOTE: different
+  if (!cutOffInheritance && // NOTE: different
       mRuleProcessors[SheetType::Doc])
     (*aCollectorFunc)(mRuleProcessors[SheetType::Doc], aData);
   nsRuleNode* lastDocRN = aRuleWalker->CurrentNode();
@@ -1152,7 +1150,7 @@
   nsTArray<nsRuleNode*> lastScopedRNs;
   nsTArray<bool> haveImportantScopedRules;
   bool haveAnyImportantScopedRules = false;
-  if (!skipUserStyles && !cutOffInheritance &&
+  if (!cutOffInheritance &&
       aElement && aElement->IsElementInStyleScope()) {
     lastScopedRNs.SetLength(mScopedDocSheetRuleProcessors.Length());
     haveImportantScopedRules.SetLength(mScopedDocSheetRuleProcessors.Length());
@@ -1287,8 +1285,7 @@
   if (mRuleProcessors[SheetType::Agent])
     (*aFunc)(mRuleProcessors[SheetType::Agent], aData);
 
-  bool skipUserStyles = aData->mElement->IsInNativeAnonymousSubtree();
-  if (!skipUserStyles && mRuleProcessors[SheetType::User]) // NOTE: different
+  if (mRuleProcessors[SheetType::User]) // NOTE: different
     (*aFunc)(mRuleProcessors[SheetType::User], aData);
 
   if (mRuleProcessors[SheetType::PresHint])
@@ -1303,7 +1300,7 @@
       mBindingManager->WalkRules(aFunc, aData, &cutOffInheritance);
     }
   }
-  if (!skipUserStyles && !cutOffInheritance) {
+  if (!cutOffInheritance) {
     if (mRuleProcessors[SheetType::Doc]) // NOTE: different
       (*aFunc)(mRuleProcessors[SheetType::Doc], aData);
     if (aData->mElement->IsElementInStyleScope()) {
```

I'm asking here since Mozilla WONTFIXed the first bug report and I'd like this to be propertly working before proposing a change upstream. Anyone interested or has any idea?

**Comment by criztovyl** [comment]
Maybe it's better to do a pull request for this, makes commenting on code and such easier :)
Although it's always better to talk about the feature you want first, but you already did some work, a PR seems a better way here.

**Comment by dimqua** [comment]
>almost nobody uses this method anymore

But currently it's the only way to modify the UI of Firefox 57+, since WebExtensions can not modify browsers appearance.

**Comment by rnhmjoj** [comment]
@criztovyl sure, I will.

@dimqua That's more reason to do this: it can only be beneficial for themes

**Comment by MrAlex94** [comment]
I will have a look into this a bit more. 

Which rules haven't been applying?

**Comment by rnhmjoj** [comment]
Try this scrollbar [theme](https://hastebin.com/ojupixopas.css).
The auto-hide transition works as expected but the color is blueish and a vertical 1px-wide line appears when hovering the scrollbar.
