### ISSUE TITLE
[Linux] DRM box checked and widevine enabled. Unable to play any HTML5 DRM content.

### ISSUE THREAD

**Issue by mikedebian** [BrowserWorks/waterfox#254]
Bug:

In Firefox I was able to watch my IPTV through my web browser, but not in waterfox. For obvious reasons, because it's from my ISP and has DRM, it's no point in linking to it. Rather I've linked to a test page on the bottom of this report.

Using OpenSUSE Tumbleweed and Waterfox 55.2.2 (64-bit).

DRM was not removed, but disabled as per webpage (in case anybody wonders why this bug is created).

After having enabled it and testing it out on a few websites, I get various streaming errors.
In the terminal I get this information which I've put in a pastebin.

The link is here [Link](https://pastebin.com/yZvCR4Qi)

From line 25 - end is where the error always appears.

I have libstdc++6-7.2.1+r253932-1.1.x86_64 and 32 bit version installed, and I'm using the tarball release of waterfox, which is placed in /opt/waterfox.

What I've tried:

Resetting widevine install as per instructions [here](https://help.netflix.com/en/node/40835)

Tried with a completely fresh profile using the profile manager.

Here is a [link](https://bitmovin.com/mpeg-dash-hls-drm-test-player/) to test DRM player.
The test error is:
DRM: Failed to create and initialize a MediaKeys object
The terminal error is however listed in the pastebin.

Tried on two completely different hardware setups, but with the same underlying OS (Tumbleweed).

**Comment by criztovyl** [comment]
You seem to have problems with seccomp sandboxing.
I would say that Firefox has an whitelist installed that is not applied for Waterfox, maybe because you chose `/opt`, maybe because the binary is named `waterfox`.
[This Reddit thread](https://www.reddit.com/r/firefox/comments/549r58/netflix_with_firefox_on_linux/) suggests this alxo happens for Firefox, with the suggestion to disable seccomp via `MOZ_DISABLE_GMP_SANDBOX=1` environment variable.

**Comment by criztovyl** [comment]
You may check whether it's really seccomp via `grep Seccomp /proc/<pid>/status`. Should be 2.

**Comment by mikedebian** [comment]
grep Seccomp /proc/5740/status
    Seccomp:        0

Using

    MOZ_DISABLE_GMP_SANDBOX=1 waterfox
 
    Seccomp:        2


Solves this problem

Is it because my /opt/waterfox is writable by my user? I do this for updates.
Changing it back to root:root, makes no difference. Same error though.

If there is a preferred way to install it in a proper location so that DRM does not complain, please let me know. Have a good weekend!

**Comment by criztovyl** [comment]
> Is it because my /opt/waterfox is writable by my user? I do this for updates.

This should not be the problem. :)

> If there is a preferred way to install it in a proper location so that DRM does not complain, please let me know. Have a good weekend!

I did some research but couldn't dig up anything :D 
I think you will have to go with `MOZ_DISABLE_GMP_SANDBOX=1` for now.

**Comment by MrAlex94** [comment]
Hey sorry for the late reply! You could try modifying **security.sandbox.content.level**, to 1 or 0. See if either work?

**Comment by grahamperrin** [comment]
Review time. @mikedebian please, is this still an issue with 56.1.0?

**Comment by jorgicio** [comment]
> Hey sorry for the late reply! You could try modifying **security.sandbox.content.level**, to 1 or 0. See if either work?

Tried here with Firefox, and no, it doesn't work.

Default value here was 4. Set to 0 and nothing happens.
