### ISSUE TITLE
Waterfox is trying to connect with Amazon servers [Android]

### ISSUE THREAD

**Issue by bla-ke** [BrowserWorks/waterfox#257]
Hi!

I'm not an advanced user of Android, but I noticed something strange - Waterfox is trying to connect with Amazon servers everytime when I restart this application. I saw it thanks to NoRoot Firewall - it can be easily blocked. Are developers going to remove this?

Screenshot:
http://images.tinypic.pl/i/00943/vco3iy6etluf.jpg

**Comment by MrAlex94** [comment]
Thanks for the heads up! I’ll try see what it’s connecting to 🤔

**Comment by bla-ke** [comment]
Well, it's still a better score than Firefox (it's trying to connect with much more addresses) 🤔... Also Firefox Focus isn't good at all, "privacy" doesn't fits to Google addresses. 
 
If I find out something else, I will tell it. 

Greetings, Daria

**Comment by grahamperrin** [comment]
From the Wayback Machine: 

![vco3iy6etluf](https://user-images.githubusercontent.com/192271/40079635-70f2633a-5880-11e8-9520-b0b8e71136c6.jpg)

**Comment by MrAlex94** [comment]
Patches have been landed to remove Google-isms. Will keep an eye for any other possible connections.
