### ISSUE TITLE
How to remove fullscreen notification about esc

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#258]
The fullscreen notification when the mouse reaches the upper limit of the screen, that, you can get out of fullscreen with esc is very annoying. It can't be removed in about:config (i'm not talking about the even more annoying pop up notification that you can deactivate)

Please remove that -_-

**Comment by MrAlex94** [comment]
Could you take a screenshot?

**Comment by ghost** [comment]
-_- Simpler explanation. It's the pop up thingy, that you see on youtube videos when they go fullscreen. (youtube is now fullscreen, exit fullscreen esc)

**Comment by PandaCodex** [comment]
You can turn off the animation by changing this preference value in about:config
From-> `full-screen-api.transition-duration.enter` `200 200`
To-> `full-screen-api.transition-duration.enter` `0 0`

Additional preferences to play with

> full-screen-api.warning.delay
> full-screen-api.transition-duration.leave
> full-screen-api.transition.timeout
> full-screen-api.warning.timeout

**Comment by ghost** [comment]
Yes, already done that.
full-screen-api.transition.timeout 0
full-screen-api.warning.delay 0
full-screen-api.warning.timeout 0

then open a youtube video in fullscreen.
move the mouse against the upper limit of the screen. It's not just the first time, but everytime the mouse touches the top of the screen.. This is not tolerable when you have to interact with the fullscreen app, it get's in the way of clicking things....

**Comment by Lorienna** [comment]
Negative integer values of `full-screen-api.warning.timeout` and `full-screen-api.warning.delay` remove the notification when going fullscreen, and when pointing the mouse cursor at the top of the fullscreen video, respectively.

You can add a leading hyphen to their existing values or set them e.g. to `-1`.

It's also possible to set `full-screen-api.warning.timeout` to `0` and `full-screen-api.warning.delay` to e.g. `2147483647` (the maximum allowed number of milliseconds corresponding to ~24.855 days of delay) as an alternative.

**Comment by ghost** [comment]
Just to note that as of writing, classic theme restorer(1.7.8) does the same error (sets them to 0). I made a pull request fixing this.
https://github.com/Aris-t2/ClassicThemeRestorer/pull/403

So in the future, the option of CTR should be functional.

**Comment by Lorienna** [comment]
FTR, another solution is to add the following snippet into the `userChrome.css` file:

```css
#fullscreen-warning {
  display: none !important;
}
```
