### ISSUE TITLE
Set network.IDN_show_punycode to true as default.

### ISSUE THREAD

**Issue by TomJansen** [BrowserWorks/waterfox#261]
Hello. If you go to https://xn--80ak6aa92e.com/, it will show as apple.com in the URL bar. This can be a security issue. 
More info here: https://www.xudongz.com/blog/2017/idn-phishing/

By setting network.IDN_show_punycode to true this can be fixed, but unfortunately, this is not the default option for Waterfox.

**Comment by ghost** [comment]
> By setting network.IDN_show_punycode to false this can be fixed, but unfortunately, this is not the default option for Waterfox

Maybe did you mean _**to true**_ rather than _**to false**_?

1- `network.IDN_show_punycode` is _false_ by default (at least on Waterfox 55.2.2)
2- `network.IDN_show_punycode` is better set to _true_ (enforce Punycode for Internationalized Domain Names to eliminate possible spoofing security risk).

**Comment by TomJansen** [comment]
@mazesy whoops yes I made a mistake. It needs to be set as true.

**Comment by criztovyl** [comment]
Or just use a font that renders those glyphs ugly :D

![bildschirmfoto vom 2017-11-05 18-45-33](https://user-images.githubusercontent.com/2174918/32417413-aeabe63c-c259-11e7-95cf-00d173dd0dc0.png)

(It's fun.)

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/bb8aa754a7ec4da02587ec046700afc2e127f0d1
