### ISSUE TITLE
after update over 55 iframe html5 loading problem

### ISSUE THREAD

**Issue by TihomirS** [BrowserWorks/waterfox#262]
Hi,

this is my favorite browser for last 3 years :)
after last updates ..i stop see html content loaded in iframe
you can test it on - https://banners.live/VZ4DQZGL9R5DMZJ
this is simple banner show system .. image banners are fine but html5 banners not shown in waterfox..
you can see it on Crome or other browsers.

Is this a config issue?

Best,
Tihomir

**Comment by grahamperrin** [comment]
Firefox 5.8.0.2 to the left, Waterfox 56.0.4.1 to the right: 

![2018-03-04 15 58 40](https://user-images.githubusercontent.com/192271/36947543-15be5eb8-1fc5-11e8-8a68-43f0ae50e8d3.png)

**Comment by TihomirS** [comment]
thank you.
wrong settings issue...
