### ISSUE TITLE
most addons dont work anymore because of a new update

### ISSUE THREAD

**Issue by matthew4444** [BrowserWorks/waterfox#265]
this is one of the many https://addons.mozilla.org/en-US/firefox/addon/hoxx-vpn-proxy/

**Comment by matthew4444** [comment]
i downloaded waterfox today and this happens when i try to get into a addon i really like and a lot of the addons do the same now: This add-on requires a newer version of Firefox (at least version 57.0a1). You are using Firefox 55.2.2.

**Comment by matthew4444** [comment]
please fix this

**Comment by matthew4444** [comment]
im at school.so i cant talk ,it will a be long time til i can talk again,.sorry

**Comment by myfonj** [comment]
I'd recommend trying previous Version 2.3.0 : https://addons.mozilla.org/en-US/firefox/addon/hoxx-vpn-proxy/versions/ : current versions targets Firefox 57 (released today) and newer; current Waterfox is based on Firefox ~ 55.

This is IMO change of AMO pages deprecating addons for Fx 56- or wrong metadata of the ext: version with "Firefox 57 support **added**!" is marked as 57+ **only**.

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/addon/hoxx-vpn-proxy/versions/?page=1#version-2.3.0 2.3.0 added to Waterfox 56.0 (64-bit) on FreeBSD-CURRENT. 

Higher versions of the add-on apparently not compatible – 

![2017-12-03 19 50 03](https://user-images.githubusercontent.com/192271/33529080-5c16960e-d863-11e7-83c2-7927f52ca71a.png)

– and a check for updates found nothing applicable ☑️ 

https://github.com/mozilla/addons-server/issues?q=is%3Aissue+Waterfox | https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+Waterfox no mention of Waterfox.

**Comment by grahamperrin** [comment]
@matthew4444 if you have not already done so, please subcribe to https://github.com/MrAlex94/Waterfox/issues/346
