### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by 17052016** [BrowserWorks/waterfox#266]
What is the fastest way to build? Don't feel like navigating on mozilla's site.
Thanks in advance.

**Comment by criztovyl** [comment]
`./mach build`

**Comment by MrAlex94** [comment]
Cd into the directory and run ./Mach bootstrap to get all the required
components then ./Mach build.

Of course I recommend reading the docs as it talks about the necessary
requirements for your specific environment.

**Comment by 17052016** [comment]
Thanks.
