### ISSUE TITLE
Waterfox for android x86 build

### ISSUE THREAD

**Issue by Tomatoide** [BrowserWorks/waterfox#269]
This is a request for a x86 build for android, thanks.

**Comment by MrAlex94** [comment]
Sure, I’ll look into the differences.

**Comment by Tomatoide** [comment]
Really hope this makes it to the upcoming 56.1 release, as firefox for android already had x86 builds for a long time, thank you I appreciate your hard work!

**Comment by LafinJack** [comment]
Maybe a Waterfox 56 for Android? :)

**Comment by grahamperrin** [comment]
https://www.reddit.com/r/waterfox/top/ ▶ [Waterfox's current status : waterfox](https://www.reddit.com/r/waterfox/comments/818z1k/waterfoxs_current_status/)

> … 
> ## Browser
> 
> …
> - Android builds are coming back on Google Play and the F-Droid repository. …

**Comment by Tomatoide** [comment]
Sadly there is still no x86 build.

**Comment by grahamperrin** [comment]
Cross reference: [Android X86 app : waterfox](https://www.reddit.com/r/waterfox/comments/8rdeh9/android_x86_app/)

**Comment by grahamperrin** [comment]
@MrAlex94 did you very recently make a comment re: focus on 64-bit, words to that effect?

(I recall reading something, can't find it now.)
