### ISSUE TITLE
Connections to a lot of servers

### ISSUE THREAD

**Issue by bla-ke** [BrowserWorks/waterfox#270]
Hello!

I decided to run Wireshark (to check functions and other things) under Linux. I turned on my browsers to check connections (Chrome, Waterfox, Firefox) and I noticed some questionable things... I noticed that Waterfox is connecting with (after removing `~/.waterfox` directory, with the release page):
- `detectportal.firefox.com`;
- `ocsp.digicert.com`;
- `location.services.mozilla.com`;
- `aus5.mozilla.org`;
- `shavar.services.mozilla.com`;
- `tracking-protection.cdn.mozilla.net`;
- `34.214.189.176` (`ec2-34-214-189-176.us-west-2.compute.amazonaws.com`);
- `93.184.220.29`
- `162.125.18.133`
- `104.18.34.252`
- `ciscobinary.openh264.org` (to download codecs probably)
- `google-analytics.com`
- `clients1.google.com`
- `ssl-google-analytics.l.google.com`
- `platform.twitter.com`
- `syndication.twitter.com`
- `use.typekit.net`
- `ocsp.pki.goog`
- `ss.symcd.com`

For what does it connect with all those servers? :thinking:

Thank you so much for your reply,
Daria.

**Comment by WagnerGMD** [comment]
Hello,

I assume you are looking for the word : "**HSTS**" and the file "**SiteSecurityServiceState.txt**". In this case, no it isn't only a trouble related to Waterfox (but Firefox itself).
You will need to configure the browser (that's just a few examples) :
```
lockPref("datareporting.healthreport.uploadEnabled",false);
lockPref("datareporting.policy.dataSubmissionEnabled",false);
pref("extensions.getAddons.cache.enabled",false);
pref("extensions.update.autoUpdateDefault",false);
pref("extensions.update.enabled",false);
pref("toolkit.telemetry.reportingpolicy.firstRun",false);
pref("toolkit.telemetry.shutdownPingSender.enabled",false);
pref("toolkit.telemetry.enabled",false);
lockPref("social.remote-install.enabled",false);
```
Under Windows it can be checked (list of cookies) via one software like Ccleaner (etc).
And another solution could be to erase then put in read mode (at least if SiteSecurityServiceState.txt exist).

**Comment by bla-ke** [comment]
Hello! 

Thank you so much for the reply. I'm going to check the configuration tomorrow, because I don't have access to my PC now. It's pretty surprising - number of the connections is pretty big (in my opinion).

Many thanks, 
Daria.

**Comment by WagnerGMD** [comment]
You're welcome and no problem you can the time I will understand.
Yes it's big and I was surprised too several months ago when I had discover this trouble.

**Comment by bla-ke** [comment]
Hello! 

I did everything as you said - I edited my config file and also put in read mode `SiteSecurityServiceState.txt`. Of course I erased it before. Now my Waterfox connects only to `waterfoxproject.org` (I disabled `network.captive-portal-service.enabled` too).

Many thanks again. I'm a user who likes to have everything under control - I know it isn't possible after all, but I'm still trying to. Does @MrAlex94 want to do something with it? Or just leave it, connecting with those servers? 🤔

**Comment by WagnerGMD** [comment]
Hello,

glad to know you're welcome @bla-ke (and it was my list (I was thinking to complete after)).
I understand sometimes I would like to have the control, it's just better. Just to give one good example, we don't have anything about **privacy.trackingprotection.enabled**... How are we supposed to restore the exceptions ? The GUI is very limited and the warning isn't very visible IMO.

**Comment by MrAlex94** [comment]
Thanks for this, has reminded me I haven't checked what connections have been made in a while. There are a few there that aren't necessary at all. 

I believe disabling OCSP queries would stop a lot of these connections as well > Preferences > Advanced > Certificates > Query OCSP responder servers to confirm the current validity of certificates

I'll check out these connections regardless though and see what needs changing, thanks :-)
