### ISSUE TITLE
provide a way to verify the download (pgp or sha256)

### ISSUE THREAD

**Issue by WPFilmmaker** [BrowserWorks/waterfox#271]
As per title it would be very good having a way to verify the download of the download from the page.

**Comment by MrAlex94** [comment]
That's in the pipeline, probably will add it to the 56 release.

**Comment by WPFilmmaker** [comment]
@MrAlex94 Thanks a lot!

**Comment by MrAlex94** [comment]
Quite a delay on this! But it's available for G5+, just append `.sha512` to the download URLs.
