### ISSUE TITLE
Waterfox does not appear in the menu list (Lubuntu 16.04.2)

### ISSUE THREAD

**Issue by WPFilmmaker** [BrowserWorks/waterfox#272]
Hi as per title Waterfox does not create a voice on the app menu on Lubuntu. This is not very user friendly as creating a menu it is a nightmare for someone who is not expert. Chromium and FF do that and I think it would be nice if waterfox would appear in the menu as well.
I also noticed that for linux only a archive file is provided, no .deb or universal package system for us?:)

**Comment by criztovyl** [comment]
@hawkeye116477 has created an APT repository for Waterfox :)
https://github.com/hawkeye116477/waterfox-deb

If installed from that repo Waterfox also should appear in your apllication/menu list.

**Comment by WPFilmmaker** [comment]
@criztovyl Thanks a lot :)

**Comment by simo002m** [comment]
Or just do this:
mv waterfox ~/.local/share/
cd ~/.local/bin
ln -s ../share/waterfox/waterfox

Paste this in to a .desktop file, just call it something like waterfox.desktop

[Desktop Entry]
Type=Application
Name=Waterfox
Comment=A free, open and private browser
Exec=waterfox
Icon=waterfox
Terminal=false
Type=Application
Categories=GNOME;GTK;Network;WebBrowser;

Then do
sudo mv waterfox.desktop /usr/share/applications

**Comment by criztovyl** [comment]
There is no need to move into `/usr/share/applications/`, `.local/share/applications/` should be enough :)
