### ISSUE TITLE
Question marks instead of characters

### ISSUE THREAD

**Issue by andoruB** [BrowserWorks/waterfox#273]
I'm using Waterfox 55.2.2, and every time I try to search for something containing cjk characters, the search instead replaces all those characters with question marks.
So, for example if I search for "テスト無題 testing", it searches for "????? testing"
I've tried to run the browser into safe mode to make sure no addons were interfering with the handling of searches, but this still happens in safe mode...

Here's a screenshot:

![screenshot_2017-11-14_19-10-53](https://user-images.githubusercontent.com/4868784/32793814-ab21311c-c96f-11e7-97ff-66ca342d5490.png)

**Comment by MrAlex94** [comment]
Does this happen no matter which search engine is set?

**Comment by andoruB** [comment]
No, it does not. I wonder how come I didn't try this before...
After trying different search engines and found out that unicode characters worked. It seems that after installing the DuckDuckGo addon, it introduced a faulty search engine entry. (or at least that's what I assume). I'll close this issue for now.
