### ISSUE TITLE
Links from external applications don't open

### ISSUE THREAD

**Issue by nullbasis** [BrowserWorks/waterfox#274]
In Ubuntu 16.04, using Waterfox 55.2.2, whenever I click a link from an external application such as Slack or Thunderbird, it doesn't open. Instead it instantiates a new Waterfox window (not tab, window) open to the default Waterfox start page.

**Comment by criztovyl** [comment]
How did you install Waterfox?
Sounds to me lika an issue with the `.desktop` file (missing `%u`)

**Comment by nullbasis** [comment]
I downloaded the archive from waterfoxproject.org, extracted it, and ran the program from the extracted ~/waterfox folder.

**Comment by criztovyl** [comment]
There should be a `userapp-Waterfox.desktop` in `~/.local/share/applications`, can you check that? (`find ~/.local/share/applications/ -type f -iname "*waterfox*"`)
Also try to look at `~/.config/mimeapps.list` at section `[Default Applications]` and look for `x-scheme-handler/http` and check the referenced `.desktop` file :)

**Comment by nullbasis** [comment]
There's no `userapp-Waterfox.desktop` in the specified folder. Only `waterfox.desktop`, which contains the following:

`[Desktop Entry]`
`Encoding=UTF-8`
`Version=1.0`
`Type=Application`
`Name=BetterPrivacy Help - Waterfox`
`Icon=/usr/share/applications/waterfox.png`
`Path=/home/phi/waterfox`
`Exec=/home/phi/waterfox/waterfox`
`StartupNotify=false`
`StartupWMClass=Waterfox`
`OnlyShowIn=Unity;`
`X-UnityGenerated=true`

(I don't know why the name is given as "BetterPrivacy Help - Waterfox". I had that page open exactly once when I first migrated my profile over from Firefox. Assuming it wouldn't hurt to change.)

The specified `mimeapps.list` section contains this:

`x-scheme-handler/http=waterfox.desktop`
`x-scheme-handler/https=waterfox.desktop`

Which looks right to me, but admittedly this is my first time actually having this issue with any browser.

**Comment by criztovyl** [comment]
The `Exec=/gome/phi/waterfox/waterfox` line seems to be missing `%u`, try appending it at the end of the line, with a space infront. :)

This seems more like an issue with Unity generating wrong/incomplete `.desktop` files as an issue with waterfox itself.

**Comment by nullbasis** [comment]
That fixed it! Thanks for taking the time to help me out even though it wasn't specifically a Waterfox issue.

**Comment by criztovyl** [comment]
Your're welcome.

**Comment by adtopkek** [comment]
Just had this same problem with Linux Mint. 

When you opened up mimeapps.list it has a `x-scheme-handler/http=` and it points to alacarte-made-{longstringofcharacters].desktop

Open up that alacarte.desktop file it points to and add `%u` to the Exec like `
Exec=/home/adam/Programs/waterfox/waterfox-bin %u`

**Comment by mrpluto23** [comment]
> The `Exec=/gome/phi/waterfox/waterfox` line seems to be missing `%u`, try appending it at the end of the line, with a space infront. :)
> 
> This seems more like an issue with Unity generating wrong/incomplete `.desktop` files as an issue with waterfox itself.

I had the same issue in Linux Mint. Thanks for the help

**Comment by DoctorSubtilis** [comment]
I solved adding %u to my desktop file (`Exec=flatpak run net.waterfox.waterfox %u`).
Thank you!

EDIT   

ops, today the problem re-appears ...
here my waterfox.desktop

```
[Desktop Entry]
Comment=
Exec=flatpak run net.waterfox.waterfox %u
Icon=firefox
Name=waterfox
NoDisplay=false
Path=
StartupNotify=true
Terminal=false
TerminalOptions=
Type=Application
X-KDE-SubstituteUID=false
X-KDE-Username=
```
