### ISSUE TITLE
Make waterfox respect the XDG Base Directory specification on linux

### ISSUE THREAD

**Issue by Reikimann** [BrowserWorks/waterfox#2747]
**Is your feature request related to a problem? Please describe.**
Programs should respect users filesystems and not contaminate them; we want a clean ``$HOME``.

**Describe the solution you'd like**
Instead of storing configs and data in ``~/.waterfox/``, store them using the XDG Base Directory Specification.

**Describe alternatives you've considered**
You could also use a local/system variable like: ``WATERFOX_{DATA/CONFIG/CACHE}_DIR``. That would enable a user to do the following:
```bash
export WATERFOX_DATA_DIR="$XDG_DATA_HOME"/waterfox
```

EDIT: Now that upstream Firefox supports this feature, maybe this issue should be reopened.

**Comment by largestgithubuseronearth** [comment]
What is the story on this now that upstream Firefox has finally made xdg-config the default path?

**Comment by Parsnip** [comment]
With the new 6.7 release being based on the ESR 153 platform, what's the status of this? I think FF started supporting XDG in 147.
Just grabbed 6.7 and it does seem like waterfox still just uses the home directory as before, at least by default.

**Comment by Parsnip** [comment]
Actually it looks like there's now a .waterfox, and a plain Waterfox directory in my home. The plain Waterfox directory is empty, all the config stuff is still in .waterfox.
Kind of reminds me of this [Thunderbird issue](https://bugzilla.mozilla.org/show_bug.cgi?id=2007074) that cropped up after FF made the change but Thunderbird didn't.
