### ISSUE TITLE
Some youtube videos cant be played

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#275]
Macos High Sierra, WF 55.2.2 
Some youtube videos can start with an error 'An error occured' and video ID. 
E.g. https://www.youtube.com/watch?v=HChqhFygf-Y All is ok in Chrome and FF

**Comment by MrAlex94** [comment]
Could you [test](https://www.reddit.com/r/waterfox/comments/7ed9sf/waterfox_56_test_build_download_plans_please/) the 56 build?

**Comment by ghost** [comment]
Fixed, thank you! Tested several movies, all is ok.

**Comment by grahamperrin** [comment]
Housekeeping … time to close `:-)` – thanks.
