### ISSUE TITLE
feature request - maximize addons popup size

### ISSUE THREAD

**Issue by leedoyle** [BrowserWorks/waterfox#277]
It would be nice to be able to maximize the [popup](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups) in many addons like uMatrix, uBlock or Conex. The default size forces one to tediously scroll down what could have perfectly fit into the screen. 
On a 1920x1080 (and thus on a 1280x1024, too) screen, default popup size could be increased in height by at least 1/3. The problem is, it can't grow more than 600px in height:
>It will grow to a size of 800x600 pixels at most if that fits on the user's screen.

I understand you have a very tight schedule and a big to-do list, but if you could give any insight into this issue - any at all - I would be very grateful. Perhaps it would not even be difficult at all to patch.

That would allow webextensions addons to have the UI similar to tab groups tab preview and enhance usability of other addons like uMatrix.

**Comment by grahamperrin** [comment]
Also worth following (don't be put off by the WebExtensions context): 

- Mozilla bug [1373490 - Webextension add-on popup/panel/subview size is not controllable when it is in the overflow/hamburger menu](https://bugzilla.mozilla.org/show_bug.cgi?id=1373490)

**Comment by leedoyle** [comment]
@grahamperrin 
Thanks!
I was able to increase the popup size with some userChrome.css and userChrome.js hacks, however, the effective addon popup itself stayed the same size, so I still had to scroll it. 
However, in uMatrix source code the dimensions 800 and 600 are not mentioned in popup.html and popup.css  and popup.js, which may indicate that my hacks were not enough. In fact, the dimension 600 is not mentioned in the uMatrix' source code at all.
