### ISSUE TITLE
Extensions xpcom will be available in the new version of Waterfox?

### ISSUE THREAD

**Issue by Extremal1981** [BrowserWorks/waterfox#278]
Hello, my country used an extension for Firefox - jsPrintSetup. We use it in the medical information system, in hospitals and clinics. This extension allows you to print medical documents selected in the printer system, with parameters set in the web application without additional interaction with the user. But mozilla refused to support XPCOM interface, and on webExtension, there is no necessary api interaction and the developer can not port it. We look at WaterFox as the last hope that it will save the xpcom interface in new versions.

**Comment by MrAlex94** [comment]
Yes, they should work unless it uses an removed APIs. If it does, please let me know which ones are important and I can re-implement them. See [here](https://blog.mozilla.org/addons/2017/07/18/compatibility-firefox-56/), [here](https://blog.mozilla.org/addons/2017/05/16/compatibility-firefox-55/) and [here](https://blog.mozilla.org/addons/category/compatibility/) for relevant information.

**Comment by stefantalpalaru** [comment]
> Hello, my country used an extension for Firefox - jsPrintSetup. We use it in the medical information system, in hospitals and clinics.

Hi! Which country is that and how widespread is the use of this extension in your hospitals?

**Comment by Extremal1981** [comment]
Hello! I'm from Russia. I am a web application developer for polyclinics and hospitals. My application uses the jsPrintSetup extension, which was very convenient, because it allowed me to send documents to a regular printer and coupons for POS printer for printing without additional actions from the user, but Firefox refused from XPCOM, and the developer of jsPrintSetup can not port it to WebExtension due to lack of the required API. So now we are looking at the full translation of the users of our medical web application on Waterfox.

**Comment by Extremal1981** [comment]
Dear developers of Waterfox! After upgrading to version 56, my web application stopped working with the jsPrintSetup extension! In the browser, the extension is installed and enabled, but in javascript the jsPrintSetup object is not available. In Waterfox 55, everything worked perfectly! Please help, what could be the reason! The work of this extension is very important for us!

My platform:Ubuntu 16.04 Waterfox 56.0

**Comment by MrAlex94** [comment]
I'll have a look into it for you and what cause the breaking :-)

**Comment by MrAlex94** [comment]
I'll have a look into it for you and what cause the breaking :-)

**Comment by Extremal1981** [comment]
Thank you very much! We are waiting for the solution of the problem, but for now we are rolling back to Waterfox55. Since we can not do without the jsPrintSetup extension.

**Comment by grahamperrin** [comment]
# JS Print Setup

https://addons.mozilla.org/addon/js-print-setup/reviews/ no mention of 56. 

Is the issue reproducible with Firefox 56.0.2 and if so, has it been raised with the developers? 

https://github.com/edabg/jsprintsetup/issues

Compatibility reports: https://addons.mozilla.org/compatibility/reporter/jsprintsetup%40edabg.com

Is the issue reproducible with Waterfox 56.0.3 or 56.0.4? 

Please ensure that multi-process Waterfox is disabled before testing. (With 56.0.3, enabling an incompatible extension such as JS Print Setup is not enough to automatically disable the feature.)

**Comment by Extremal1981** [comment]
Thank you very much! When is disable the multi-process in the Waterfox extension, jsPrintSetup works fine! We really hope that jsPrintSetup will continue to work in new versions of Waterfox. Since for corporative portals, this extension is very important!02.02.2018, 07:44, "Graham Perrin" <notifications@github.com>:JS Print Setup
https://addons.mozilla.org/addon/js-print-setup/reviews/ no mention of 56.
Is the issue reproducible with Firefox 56.0.2 and if so, has it been raised with the developers?
https://github.com/edabg/jsprintsetup/issues
Compatibility reports: https://addons.mozilla.org/compatibility/reporter/jsprintsetup%40edabg.com
Is the issue reproducible with Waterfox 56.0.3 or 56.0.4?
Please ensure that multi-process Waterfox is disabled before testing. (With 56.0.3, enabling an incompatible extension such as JS Print Setup is not enough to automatically disable the feature.)

**Comment by zybersup** [comment]
Thank all you guys very much. This thread help me find the fix of the same "missing jsPrintSetup object" problem.

And BIG thank to @MrAlex94. I have been using Firefox ESR 52 with this jsPrintSetup extension for my POS system for years after Firefox Quantum dropped the old extensions. Now I can use Firefox Quantum for other websites and use our POS system on Waterfox Classic.
