### ISSUE TITLE
html5 playback issue

### ISSUE THREAD

**Issue by narcolepticinsomniac** [BrowserWorks/waterfox#28]
Some html5 videos won't skip at all. For example: 
(NSFW) [deleted, see link below]
I've tested simultaneously in Chrome, Firefox and Waterfox (with add-ons disabled) and this only happens in Waterfox. Firefox was slightly slower than Chrome, but Waterfox doesn't skip at all. It just hangs and hangs.

**Comment by aCoolNz** [comment]
works for me very nice

**Comment by narcolepticinsomniac** [comment]
@aCoolNz, I'm curious if you actually get the video to skip forward correctly. It seems to  play fine, but when I attempt to skip forward it just hangs and does nothing.

**Comment by narcolepticinsomniac** [comment]
I see that Waterfox finally updated but this issue hasn't been addressed. The example I provided is no longer valid because  that site switched to Flash. Here's another (NSFW) example of a video url that will open in the default html5 player: https://pgli38.oloadcdn.net/dl/l/eBNSiXPj4ZY/sAkydbcF8vo/%5BBada+Bing%5D+Mofos.com_+Melissa+Moore+-+Tanning+Teen+Likes+It+Rough+%282015%29+HD.mp4+-+openload.MP4.mp4?mime=true
It will start playing, but it won't skip. It's not a particular player or even a particular host (some vids from this host skip fine). It tends to be adult videos (inferior encodes maybe?). These vids skip fine in Chrome and also skip in Firefox although Firefox tends to become far more resource hungry once they're skipped (using more than double the usual amount of CPU). Chrome has no issues at all.
