### ISSUE TITLE
Actual Requirements?  (Version-based requirements?)

### ISSUE THREAD

**Issue by empimp** [BrowserWorks/waterfox#280]
According to https://www.waterfoxproject.org/downloads Waterfox requires "Any Intel based Mac"  running "Mac OS X 10.5 64-Bit or later", along with "512MB RAM" & "200MB storage space" 

I've got an "2.4 GHz Intel Core 2 Duo" running "Mac OS X 10.6.8"[1], with 8 GB of Ram & 300MB of available storage[2] - these specs meet Waterfox's stated requirements.  However, when I try to run Waterfox, I get the following error message:

>Check with the developer to make sure Waterfox works with this version of Mac OS X.  You may need to reinstall the application.  Be sure to install any available updates for the application and Mac OS X.

I've re-download, re-installed Waterfox, & restarted my system, but still get the same message.

**Are the stated requirements for an older version of Waterfox?**
if yes - **What's the lastest version that should actually work, given my system's specs?**
otherwise - **Do you have any troubleshooting steps that I should follow?**

@MrAlex94 - Thank you for making a more backwards compatible browser.  I wish I'd learned about Waterfox several years ago!

---

[1]: _long story why it's still on 10.6; but ultimately, I can't upgrade it_
[2]: _yes, I need to offload some stuff, but still within the stated requirements_

**Comment by grahamperrin** [comment]
<strike>I can't recall where, but I'm fairly sure </strike>I read that the _512MB RAM_ requirement is outdated. 

Postscript: found, https://www.reddit.com/r/waterfox/comments/7gruoq/waterfox_56_release/dqthcdi/

**Comment by MrAlex94** [comment]
The requirements are all definitely outdated. I’m updating the website so
it will be updated.

OS X 10.6 may also be possible, as it’s missing a dynamic library that can
be built and included

**Comment by grahamperrin** [comment]
Meta, tracking: #582

**Comment by grahamperrin** [comment]
Partly related (spun off from multiple issues): 

- [e10s: availability of multi-process with older versions of operating systems : waterfox](https://www.reddit.com/r/waterfox/comments/8rtb3l/e10s_availability_of_multiprocess_with_older/)
