### ISSUE TITLE
Dark theme issue with blue url text

### ISSUE THREAD

**Issue by anjari** [BrowserWorks/waterfox#282]
I'm using Waterfox v55.2.2 in linux with cinnamon desktop and Adapta-Nokto gtk dark theme.

I understand there is a bug in firefox where the dark theme will cause some form input on web page having dark background, and I use Stylish add-on to fix it.

However there are other issue regarding the dark theme, the blue url text in some UI components (address bar, menu text, about dialog, etc) is hard to see. Here are some screenshots of the blue url text in dark theme:
https://i.imgur.com/9QkHxlm.png
https://i.imgur.com/tpk7jxU.png
https://i.imgur.com/kKpAuKV.png

In latest firefox version, the blue url in address bar has been changed to light blue which is easier to read with gtk dark theme, and for the About dialog, it's using white url text.

I wonder if you can do same changes in Waterfox? Or perhaps there is a workaround with Stylish add-on ?

**Comment by grahamperrin** [comment]
> … dark theme will cause some form input on web page having dark background, …

Do you mean, like this? 

![capture d ecran de 2016-04-30 16-58-48](https://user-images.githubusercontent.com/192271/36947694-6cfd9be2-1fc7-11e8-9c3c-a7964b634ab2.png)

– from Mozilla bug [1268338 - GTK3 not completely compatible with Linux Gnome Global Dark Theme. Input field text is white and inner scroll bars are dark.](https://bugzilla.mozilla.org/show_bug.cgi?id=1268338)

----

> … In latest firefox version, the blue url in address bar has been changed to light blue which is easier to read with gtk dark theme, and for the About dialog, it's using white url text. …

Can you identify the Mozilla bug (or bugs) associated with those enhancements? Thanks.

**Comment by jbeich** [comment]
Can you try mozilla/gecko-dev@4cb65b680138?

**Comment by anjari** [comment]
@grahamperrin Yes. I aware that's a bug on firefox. I wish waterfox can make a fix for that.

> Can you identify the Mozilla bug (or bugs) associated with those enhancements? Thanks.

I don't know about the bug link. I had installed the firefox together with waterfox, and I witnessed the firefox doesn't have this blue url issue.

**Comment by Peacock365** [comment]
FIXED BY https://github.com/MrAlex94/Waterfox/commit/b62734f2913a956f9bffa79bf90f80e79e50b5ac

**Comment by jbeich** [comment]
> I understand there is a bug in firefox where the dark theme will
> cause some form input on web page having dark background, and I use
> Stylish add-on to fix it.

Have you tried `widget.content.gtk-theme-override=Adapta-Nokto` in `about:config`? Firefox 55+ [assumes](https://bugzilla.mozilla.org/show_bug.cgi?id=1158076) light theme for Web content.
