### ISSUE TITLE
Java64 -> ClassNotFoundException

### ISSUE THREAD

**Issue by codeandfix** [BrowserWorks/waterfox#283]
Why do i get a ClassNotFoundExcpetion if i use plain Waterfox with Java64?
IE works fine, firefox worked fine before NPAPI was removed.

**Comment by MrAlex94** [comment]
What version of Waterfox?

**Comment by codeandfix** [comment]
Latest and 1 before

**Comment by MrAlex94** [comment]
Could you try [56.0.1](https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.0.1%20Setup.exe).

**Comment by codeandfix** [comment]
i tried 56.0.1 too. does load java logo but i think java cant load further classes

**Comment by codeandfix** [comment]
btw the version before 56.0.0 was also failing!

**Comment by codeandfix** [comment]
Update from today still not working :-(

**Comment by MrAlex94** [comment]
Try setting all these values to **0** in **about:config**:
`dom.ipc.plugins.sandbox-level.default`
`dom.ipc.plugins.sandbox-level.flash`
`security.sandbox.content.level`

**Comment by codeandfix** [comment]
Still does not work.
the first setting is 0 by default too.
btw i think the problem could be java64+browser64? maybe there is a 32 bit waterfox?

**Comment by grahamperrin** [comment]
> … 32 bit waterfox?

I doubt it. Re: https://www.waterfoxproject.org/#about it originated as 64-bit.

**Comment by codeandfix** [comment]
the loading-logo of java shows but then after loading the class not found exception occurs.
how can i debug this?

**Comment by grahamperrin** [comment]
Please: at what address does the exception occur?

If you visit http://www.cyscape.com/showbrow.asp?doJvmd=1 and (in the location bar) allow Java for that page, then is a _JavaVersion_ shown in the test result?

**Comment by codeandfix** [comment]
JavaVersion | Java N/A (applet not scriptable) -- | --
JavaVendor | Java N/A (applet not scriptable)
Plugin_JavaVer | 1.8.0_161 -- | --

**Comment by codeandfix** [comment]
it occurs on LAN devices. switches, NVR,..
the oracle test page says firefox 64 is not supported so the test applet is not loaded there.

**Comment by codeandfix** [comment]
It seams, that JAVA is loading, because i get an Security dialog.
But the class the main applet wants to load is shown as not found in debug window.
But the class is found, if i paste the url into the browser...
This did not occur on 32 bit firefox in past.
so i fear its a 64 bit issue? are you aware of this or have a 32 bit build?

**Comment by grahamperrin** [comment]
> … 32 bit build?

I doubt it. Waterfox originated as 64-bit only.

**Comment by codeandfix** [comment]
Another pity of Java and older devices is the usage of md5 with rsa or self signed certs.
maybe i should be able to disable nearly all certificate checks to be sure this is not the problem.
But how? Adding exceptions and changing the policy file seems not to be enough?

**Comment by codeandfix** [comment]
it works with internet explorer 32/64 i figured out now.
so it must work with waterfox too i think. but it does not
