### ISSUE TITLE
Licensing of the Waterfox logo

### ISSUE THREAD

**Issue by amitie10g** [BrowserWorks/waterfox#29]
Just a legal question regarding the logo found in Wikimedia Commons.

I found the logo inside this repo, but I don't found any document that license that rather than the MPLv2. Then, **What is the actual licensing of the logo?**

**Comment by owcz** [comment]
@MrAlex94 ?

**Comment by MrAlex94** [comment]
Sorry about that. The Waterfox logo is copyrighted, but can be used under [fair use](https://www.copyrightservice.co.uk/copyright/p09_fair_use).
