### ISSUE TITLE
It would be better to develope an extension istead of Waterfox?

### ISSUE THREAD

**Issue by TerkiKerel** [BrowserWorks/waterfox#290]
Hi,

first of all thanks for this browser :) which is perfect for privacy...

But I am thinking something: there are 3000+ commiters on this project. I see the feature list on the Readme file. AFAIK all these features (+more) can be done with a simple plugin by changing about:config variables such: https://github.com/schomery/privacy-settings#privacy-settings

Now you need to build the source code after each new version of firefox, the end user should wait for new version, we dont have ios + android versions... we dont have nix package for linux, we dont have AppImage version for linux... bla bla...

But we love this project :)

Thank you again

**Comment by criztovyl** [comment]
It looks valid that most of the privacy-related things could be done by a plugin.

But one of Waterfox' features is continued support for the "old" extension API, which cannot be done by an addon :)

**Comment by TerkiKerel** [comment]
@criztovyl you mean Wterfox will support both webapi and legacy add-on api? But this is not the priority/focus of this project :/

**Comment by criztovyl** [comment]
I am only user and cannot really tell more, but afaict that's an essential part of the mission.

**Comment by MrAlex94** [comment]
The settings themselves aren't enough for a lot of things and some people like having an alternative :-)

**Comment by WagnerGMD** [comment]
`pref("security.ssl.treat_unsafe_negotiation_as_broken",true);
pref("security.ssl.require_safe_negotiation",true);`

Just one warning about (the addon)  **Privacy Settings**. You can't trust it (at 100%) because :
- some settings doesn't longer exist (one example I believe that's true for **loop.enabled**)
- it might brake a **legit website** (such as [humblebundle.com](https://www.humblebundle.com/), etc) and yes that's a big trouble.

**Comment by TerkiKerel** [comment]
@WagnerGMD that was exactly the answer with spesific example.

I read the docs of Waterfox. Is there any doc about all differences with Firefox. There is a "Features" title on Readme file but those features are not only differences... It would be great to know what exactly is different than Firefox.

Thank you

**Comment by probonopd** [comment]
> we dont have nix package for linux, we dont have AppImage version for linux... bla bla...

Now we do have an AppImage that might even be runnable using [`appimage-run`](https://nixos.org/nixos/packages.html#appimage-run) on NixOS.

**Comment by jackTaw88** [comment]
On the main readme file writes the differences:

```
    Compiled with Clang-cl on Windows, Clang+LLVM on Linux
    Disabled Encrypted Media Extensions (EME)
    Disabled Web Runtime (deprecated as of 2015)
    Removed Pocket
    Removed Telemetry
    Removed data collection
    Removed startup profiling
    Allow running of all 64-Bit NPAPI plugins
    Allow running of unsigned extensions
    Removal of Sponsored Tiles on New Tab Page
    Addition of Duplicate Tab option (toggle with browser.tabs.duplicateTab, thanks to PandaCodex)
    Locale selector in about:preferences > General (further improved by PandaCodex)
```

Most of these features can be done by user.js configurations (which are already maintaining by other projects on github).

As a waterfox user, I agree with @TerkiKerel . 

with 3500 developers we can do better things. The priorities are important. Most of Waterfox users thinks that they use a private browser. But most of extensions are already getting informations from you. Even the open source ones... Who knows what the maintainers put at extensions-store? I don't believe the maintainer of the extension repo, builds only the source code of the repo and puts it on the mozilla-extension-store. 

libreFox project has a very good idea: a feature to firefox which can block extensions internet connection (extension spesific). This solves %100 privacy concerns for all extensions.

I think 3500 developers can write this features in a month, even with only effort that we give on waterfox project.
