### ISSUE TITLE
En-GB dictionary not loading

### ISSUE THREAD

**Issue by modem7** [BrowserWorks/waterfox#291]
Heya guys, 

Set locale to en-GB, but default dictionary is still en-US. Unable to load en-GB dictionary. 

general.useragent.locale is set to en-GB. 

Waterfox 55.2.2 64bit

**Comment by grahamperrin** [comment]
Which en-GB dictionary? 

With Waterfox 56.0 on FreeBSD-CURRENT I have: 

- [British English Dictionary](https://addons.mozilla.org/addon/british-english-dictionary/) 1.19.1.1-typefix – disabled
- [British English Dictionary (Marco Pinto)](https://addons.mozilla.org/addon/british-english-dictionary-2/) 2.55 – enabled, and loaded as shown below. 

![2017-12-03 20 15 18 waterfox](https://user-images.githubusercontent.com/192271/33529286-dcdd3880-d866-11e7-9780-dfbee6c98b58.png)

**Comment by modem7** [comment]
Ahhah! 

I didn't seem to have either of those installed, even though I had the locale set to en-gb, it was defaulting to an American English dictionary. 

Installing the Marco Pinto dictionary resolved the issue for me, but others might get confused! 

Thanks!

**Comment by grahamperrin** [comment]
Towards closure of this issue … 

Generally for Firefox (and, I guess, for Waterfox): https://addons.mozilla.org/language-tools/ may help to understand the distinction between a language pack and a dictionary. 

Mozilla bugs that may be of interest: 

- [1325870 - [meta] Unify locale selection across components and languages](https://bugzilla.mozilla.org/show_bug.cgi?id=1325870)
- [1352884 - Support for UI language switcher add-ons](https://bugzilla.mozilla.org/show_bug.cgi?id=1352884)
- [1368507 - support locale switcher addons](https://bugzilla.mozilla.org/show_bug.cgi?id=1368507) RESOLVED INVALID
