### ISSUE TITLE
Missing png file breaks build

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#292]
On Archlinux AUR (maintainer of waterfox-git), I just removed it from the list for the jar as a workaround, but FYI:

skin/classic/browser/slowStartup-16.png

Doesn't seem to exist for any of the OSes Waterfox supports.

https://aur.archlinux.org/cgit/aur.git/tree/missing-png-workaround.patch?h=waterfox-git

**Comment by jbeich** [comment]
Duplicate of #281?

**Comment by ilikenwf** [comment]
Yes, apologies. I didn't notice until after submission.

**Comment by grahamperrin** [comment]
Review time. Close this?
