### ISSUE TITLE
Improve task switching using some orange in Icon

### ISSUE THREAD

**Issue by RealRaven2000** [BrowserWorks/waterfox#294]
I find lots of my icons are pure blue, which makes task switching slow especially on live hangouts or in other stressy situations. Skype, Thunderbird, Pale moon, SeaMonkey all have blue icons. Therefore I made a quick edit from the 2015 version (I also created a windows icon) to add a splash of orange (without changing the Fox's fur color!) could this be included?
![waterfox_logo_256](https://user-images.githubusercontent.com/6314674/33515023-0017bbc6-d755-11e7-922c-258f4dd311f1.png)
![waterfox_logo_64](https://user-images.githubusercontent.com/6314674/33515049-62271866-d755-11e7-83f3-78c349b95ecb.png)
![waterfox_logo_32](https://user-images.githubusercontent.com/6314674/33515025-01c6e6ea-d755-11e7-9f4d-16664bae750d.png)
![waterfox_logo_16](https://user-images.githubusercontent.com/6314674/33515026-03db3314-d755-11e7-989d-f859ec80bf25.png)

**Comment by criztovyl** [comment]
I would say this use-case is somewhat too special to include it in the official distribution.

Anyway, you should be able to change the icons yourself, on your machine, if you didn't do already.

If you did, maybe you could document it here, for others to come.

If not, I am happy to assist you changing the icons locally.
