### ISSUE TITLE
'extensions.databaseSchema' causing tool-bar icons to disappear?

### ISSUE THREAD

**Issue by atomGit** [BrowserWorks/waterfox#295]
this is very strange...
far as i know, `extensions.databaseSchema` simply increments for each major release

when i upgraded from waterfox-kde 55 to 56, at some point, and not right of way, all the tool-bar icons that are created by extensions failed to appear (uBlock, uMatrix, etc.) - the placeholders were still there, but no images

i narrowed the problem down to `user_pref("extensions.databaseSchema", 22);` - if i removed it from prefs.js, the icons appeared normally and so i tested this several times to be certain

next i restored my default profile and simply reset the pref in about:config to it's default value (empty) and restarted waterfox and the icons appeared as they should - i then checked the value of `extensions.databaseSchema` in about:config and it was ... drum roll ... 22!

Mint 18.2
WF 56

**Comment by grahamperrin** [comment]
Thanks, can you tell whether this was still an issue with e.g. the update (not long ago) to 56.1.0?

Also: [Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)

**Comment by atomGit** [comment]
well, the icons haven't disappeared and i'm running 56.1 and `extensions.databaseSchema` is 22 - so i guess all is ok

**Comment by grahamperrin** [comment]
Thanks! Go ahead and close this issue, if you like.
