### ISSUE TITLE
Cookie Prompt doesn't work

### ISSUE THREAD

**Issue by jbeich** [BrowserWorks/waterfox#296]
Cookie Prompt (#259) appears to only work from build directory, at least on GTK platforms.

![cookie_prompt_broken](https://user-images.githubusercontent.com/11153579/33518828-96ec44ca-d793-11e7-954e-3ec32f4f1402.png)

### Steps to reproduce
0. `./mach bootstrap`
1. `./mach build`
2. `./mach run "about:preferences#privacy"`
3. Set History -> Waterfox will: **Use custom settings for history** -> [*] Accept cookies from websites -> Keep until: **ask me every time**
4. `./mach run https://en.wikipedia.org/`
5. "Confirm setting cookie" window appeared
6. Click "Show Details"
7. Everything looks OK
8. Click "Allow"
9. `./mach install`
10. `waterfox "about:preferences#privacy"`
11. Repeat step 3
12. `waterfox https://en.wikipedia.org/`
13. Click "Show Details"
14. Notice empty fields
15. Click "Allow"
16. Notice nothing happens (window didn't disappear)
17. Clicking on other buttons (except "Hide Details") also does nothing

**Comment by criztovyl** [comment]
For tracking, this happens when I click on any button, from Browser Console (56.0.1):
```
TypeError: nsICookieAcceptDialog is undefined  cookieAcceptDialog.js:168:3
	cookieDeny chrome://cookie/content/cookieAcceptDialog.js:168:3
	doCancelButton chrome://global/content/dialogOverlay.js:38:11
	oncommand chrome://cookie/content/cookieAcceptDialog.xul:1:1
```

**Comment by MrAlex94** [comment]
Yes, seems even though it's defined and the appropriate component is getting called, it doesn't see the definition! Can any of you see what may have gone wrong in the [commit](https://github.com/MrAlex94/Waterfox/commit/bd7c21e3f3deedaff172019b442c71350b8ceeae)?

**Comment by juneyourtech** [comment]
I'd like to have some confirmation, if cookie prompts are going to be kept long-term, because I just noticed a [revert](https://github.com/MrAlex94/Waterfox/commit/6a6ee5e1593e1c624ab40a858bd12b4cd6c89186) of Savarese's code, with the explanation in code comments, that [cookie prompting] was 'not supported' (by whom?).

Update: @MrAlex94 , It seems from a subreddit [three days ago](https://www.reddit.com/r/waterfox/comments/7qhom0/small_cookie_problem/), that you haven't abandoned it, but just disabled it, until the issue becomes bug-free / gets resolved for a working reimplementation.

I've just let Savarese know about this bug, so I'm hoping for a response.

**Comment by juneyourtech** [comment]
Savarese's response wrt the patch:

> It looks like the wrong patch was applied.  Or rather, the patch for Firefox 56.0.1 was applied to a source tree based on Firefox 57.0.x. The patch for Firefox 57.0.4 should have been used.  Perhaps I had
not yet published a patch for 57.0.4 and someone used the latest one available at the time.

> The problem, of course, is that the patch usually stops working with each major Firefox release and must be updated.  I haven't upgraded to Firefox 59.0.x yet, but will release an updated patch for it when I do. I cannot spend additional time porting the patch to Waterfox, but anyone who wishes to is free to do so.

Savarese's latest cookie prompt restore patch is [currently](https://www.savarese.org/patches/firefox.html) based on the Firefox 57.0 source tree.

cc: @criztovyl @MrAlex94

**Comment by grahamperrin** [comment]
Also [Reintroduce cookie prompting · Issue #203 …](https://github.com/MrAlex94/Waterfox/issues/203)

**Comment by grahamperrin** [comment]
#538

**Comment by juneyourtech** [comment]
My best guess could be, that there was a version/code conflict with merging one of D.F. Savarese's patches. The windows without window titles and other appropriate information seem to suggest, that Waterfox's modal dialog implementation was different (older?) from that of whichever (newer?) version the merged patch supported.

@criztovyl , do you remember, which of Savarese's patches did you merge, and which upstream version did it correspond to? A possible solution is to test cookie prompting with an older patch, and then, if it works reliably in alpha/beta, release.

It should simply be possible to merge, build, and test all of Savarese's patches ([here](https://www.savarese.org/patches/firefox.html)) until there's a patch that works. Merging from newest to oldest and testing should help to find out the right one.
