### ISSUE TITLE
Nix package

### ISSUE THREAD

**Issue by TerkiKerel** [BrowserWorks/waterfox#297]
Hi,

it would be great if you can release nix package (or AppImage) package for stable versions.

Thank you

**Comment by hawkeye116477** [comment]
AppImage is here -> https://bintray.com/probono/AppImages/Waterfox but only 52.0.1 version.

**Comment by TerkiKerel** [comment]
I should not write AppImage :( AppImage can not update itself. We need to check and download each everytime manually the updates...

Nix is perfect. There are nix packages of Firefox, tor browser and pale-moon browser. It would be great to see Waterfox too.

Thank you

**Comment by criztovyl** [comment]
@hawkeye116477 maintains an Apt-Repo for Waterfox: https://github.com/hawkeye116477/waterfox-deb

**Comment by Serkan-devel** [comment]
Ther is https://github.com/AppImage/AppImageUpdate

**Comment by notpushkin** [comment]
I guess making a `-bin` package shouldn't be too hard; and if we really want a source build, we can i. e. fork [Pale Moon's expression](https://github.com/NixOS/nixpkgs/blob/85b4a20db34d31e1bb3fbd41ce99c66c4e14f93b/pkgs/applications/networking/browsers/palemoon/default.nix) and adapt it as needed.

**Comment by TerkiKerel** [comment]
I can test the package if somebody create a nix package.

**Comment by notpushkin** [comment]
@TerkiKerel I have made a simple Nix expr for Waterfox. You can try it:

```
git clone --depth=1 https://github.com/iamale/nixpkgs.git ./tmp/iamale-nixpkgs
nix-env -f ./tmp/iamale-nixpkgs -iA waterfox-bin
```

Please tell me if it works for you too -- I'll submit a PR to Nixpkgs then.

**UPD:** submitted already: https://github.com/NixOS/nixpkgs/pull/33184

**Comment by TerkiKerel** [comment]
@iamale You are too fast :)

I already have installed nix package on my OS. SHould I type your both commands?

**Comment by notpushkin** [comment]
@TerkiKerel Yeah, let's try it :) Perhaps we can move our discussion to https://github.com/NixOS/nixpkgs/pull/33184 to keep it in one place?

I see two bugs right now:
- Open / save dialogs crash the app
- The desktop entry isn't copied to profile (although it happens to me for most of other apps on NixOS as well, probably something wrong with my setup)

**Comment by probonopd** [comment]
An AppImage is available from https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/Waterfox-latest-x86_64.AppImage.mirrorlist (reference: #127).

It looks like (I have not tested it, though) that [`appimage-run`](https://nixos.org/nixos/packages.html#appimage-run) can run AppImages on NixOS (reference: https://github.com/AppImage/AppImageKit/issues/472).

**Comment by Vanderscycle** [comment]
Sorry, this is a really late reply, but I managed to get it working on my nix system with this default.nix. Please adjust the version/download url. Here's the [default.nix](https://github.com/Vanderscycle/nixos-house-of-pain/blob/main/waterfox/default.nix), then all that was required was to import the nix expression. I use home-manager and had to add something like [this](https://github.com/Vanderscycle/dotFiles/blob/5169b5b9daa1d27d592563ad0258ad0420e8fb39/postInstallScripts/nixos/home-manager/home.nix#L8)

@notpushkin took your nixpkgs pr and tinkered with it. Without your PR I would never had this off the ground running.
