### ISSUE TITLE
Possible Adobe CDM Issues (needs confirmation)

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#30]
As of today waterfox will no longer play any videos from netflix giving a error code relating to the Adobe CDM Module. Netflix support ran through troubleshooting and essentially said it has to be an issue with the browser at this point. 

Cleared Cache and Cookies (no change)
Reinstalled Waterfox (no change)
Installed the latest version of Firefox's main branch which played the videos perfectly fine. 

can anyone else confirm this issue and figure out weather or not its a Netflix issue or an issue with waterfox's implementation of adobe CDM

**Comment by DaAwesomeP** [comment]
@mikeloeven There is currently no 64-bit CDM plugin. If you look under Addons > Plugins, you will see it say that it is "about to be installed." However, it never will. There is also no 64-bit silverlight for Mac, so you'd be out of luck there. There is 64-bit Silverlight for Windows and [Pipelight](http://pipelight.net/cms/) for Linux (Waterfox doesn't run on Linux though as there is already a 64-bit version of Firefox).

**Comment by DaAwesomeP** [comment]
I take that back. It looks like they rolled out a 64-bit version. It must be bugged. @MrAlex94 thoughts?

**Comment by DaAwesomeP** [comment]
When I disable Silverlight and force it to use the CDM, I get this error: [F7701-1003](https://help.netflix.com/en/node/32661). There is an obvious problem: The "Enable DRM content in Firefox" box lists an option that doesn't exist in Waterfox. I am running version 40.0.2 on Windows 8.1 Pro.

**Comment by mikeloeven** [comment]
Workaround change the user agenf to an earlier FF build and force silverlight

**Comment by DaAwesomeP** [comment]
@MrAlex94 Any updates? I prefer using the HTML5 version. Silverlight doesn't seem to run well on my computer (or actually any computer I've ever used), and the HTML5 way is the only way to get Netflix on a Mac with Waterfox.

**Comment by MrAlex94** [comment]
Yeah, got confirmation from Mozilla that Adobe only allow Mozilla to run the Adobe CDM. Looks like no 3rd party builds will be able to use HTML5 DRM for a while: https://groups.google.com/forum/#!topic/mozilla.dev.builds/eIonFrb3oUU
