### ISSUE TITLE
information from addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#300]
Please, can/should anything be done to improve integration with AMO?

The first two screenshots below show [Add-ons Manager Context Menu](https://addons.mozilla.org/addon/am-context/) options in Firefox 56.0.2, fewer options in Waterfox 56.0: 

![2017-12-04 18 36 40 add-ons manager - mozilla firefox](https://user-images.githubusercontent.com/192271/33577350-971c7e94-d93a-11e7-8bd3-aba5f55410a5.png)

![2017-12-04 19 25 22 add-ons manager](https://user-images.githubusercontent.com/192271/33577376-af9999ca-d93a-11e7-8d49-452e0fa837f2.png)

Not all add-ons offer a support URL or contribution information but for those that do, the difference is remarkable. 

----

In these two shots Waterfox is to the left, Firefox to the right: 

![2017-12-04 21 23 40](https://user-images.githubusercontent.com/192271/33577423-d2df7b5c-d93a-11e7-8c17-4a0abf81c793.png)

- that's for [Tab Tally](https://addons.mozilla.org/addon/tab-tally/)

![2017-12-04 21 25 48](https://user-images.githubusercontent.com/192271/33577422-d2bc0fa0-d93a-11e7-9e5d-03d04e741817.png)

- that's for [Auto Unload Tab](https://addons.mozilla.org/addon/auto-unload-tab/). 

----

I understand that there'll be changes to AMO in the months ahead – [Legacy Add-on Support on Firefox ESR | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/2017/10/03/legacy-add-on-support-on-firefox-esr/) and so on – but for now, can anything be done to improve the situation? 

It's particularly problematic where the installed name of an extension is significantly different from the name that's given at AMO. _Custom UserAgent String_, for example. True: the root of the problem is with the developers, but if integration can be improved then there should be fewer edge cases. 

Thanks

**Comment by grahamperrin** [comment]
In some situations, probably where both Firefox 56.0.x and Waterfox 56.0.x have used the same profile, I find **the same problem with Firefox 56.0.2**. 

Here, for example: 

![2018-01-03 10 38 29 add-ons manager - mozilla firefox](https://user-images.githubusercontent.com/192271/34574976-f53124dc-f170-11e7-9613-e16e89c15e29.png)

That extension's information as it should normally appear in Firefox: 
<details>

![2018-01-03 10 43 24 add-ons manager - mozilla firefox](https://user-images.githubusercontent.com/192271/34575050-400c777c-f171-11e7-9279-af52e7783fc8.png)

</details>

----

In Waterfox, can I work around the issue by simply setting a preference? At about:config

**Comment by grahamperrin** [comment]
(That closure was accidental.)

**Comment by MrAlex94** [comment]
None of the code has been touched for the add-on manager, strange that the options are so different. I wonder if the user agent has anything to do with it? Any difference if you test **general.useragent.override.*** (will overwrite UA on every connection) with a Firefox 56 UA?

**Comment by grahamperrin** [comment]
Thanks, 

`Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0`

- no improvement. 

A long shot: 

`privacy.resistFingerprinting` `true`

- no improvement. 

----

Maybe remarkable, there's comparable 'dumbing down' of the information with Pale Moon. 

Firefox to the left, Pale Moon to the right: 

![2018-01-04 19 11 23](https://user-images.githubusercontent.com/192271/34580057-6d9fc4d4-f183-11e7-9117-f84812a713e1.png)

… with attention to the pointer in the Firefox window, and the same paragraph in the Pale Moon window, it's like information is **cut off _after a first paragraph_**.

**Comment by grahamperrin** [comment]
Please, did this issue also exist with Waterfox 55?

**Comment by grahamperrin** [comment]
https://searchfox.org/mozilla-central/source/browser/app/profile/firefox.js#44

> `// Preferences for AMO integration`

[How to opt out of add-on metadata updates | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/how-to-opt-out-of-add-on-metadata-updates/) (~2011-02-14)

> … Firefox will ask the Mozilla Add-ons gallery for information about the add-ons you have installed once a day. … 

> … `extensions.getAddons.cache.enabled` …
 
## Experimenting

1. `extensions.getAddons.cache.enabled` from `false` (a default) to `true`
2. `extensions.getAddons.cache.lastUpdate` reset
3. restart Waterfox …

**Comment by grahamperrin** [comment]
## Experimental results for three types of profile

### Waterfox using a profile that was created by Firefox

- root `/home/grahamperrin/.mozilla/firefox/tuk42vu2.minimal everyday-1508231281798`
- no local directory

A good result (with a gold star rating): 

![2018-01-04 22 10 40 waterfox](https://user-images.githubusercontent.com/192271/34587303-be7499a4-f19f-11e7-9210-5992239fa5ab.png)

### Waterfox using a profile that was almost certainly created by Waterfox

- root `/home/grahamperrin/.waterfox/g5lllcwj.test`
- local `/home/grahamperrin/.cache/waterfox/g5lllcwj.test`

Another good result (with a gold star rating): 

![2018-01-04 22 22 26](https://user-images.githubusercontent.com/192271/34587402-20479da2-f1a0-11e7-8c82-db6a5a167802.png)

## Waterfox using _a copy of_ a profile that was created by Firefox

Mixed results. This profile was created long before I knew of Waterfox. 

Focusing on the six most recent updates – _Playback speed_, _Refined GitHub_, _Web Pages Scanner_, _Min Vid_, _uMatrix_ and _Triage with me_: 

![2018-01-04 22 31 17](https://user-images.githubusercontent.com/192271/34587464-5ddac676-f1a0-11e7-9dfa-aa5ad9b7d1e8.png)

– only one of the six, the most recent, has metadata: 

![2018-01-04 22 32 35](https://user-images.githubusercontent.com/192271/34587555-b03cf5ce-f1a0-11e7-85e2-5d095f54cee6.png)

It's proper for [Min Vid](https://testpilot.firefox.com/experiments/min-vid) to **not** have a star rating because it's a Firefox Test Pilot experiment (not distributed through AMO). 

The other four … I'll leave this issue open for maybe a day or so; I have not yet regained a `extensions.getAddons.cache.lastUpdate` entry.

**Comment by grahamperrin** [comment]
> …  I'll leave this issue open for maybe a day or so; …

After waiting a few days, with `extensions.getAddons.cache.enabled` `true` it seems that metadata is cached only when an extension is added or updated. 

For the extensions that I installed before switching to Waterfox, I expect the vast majority to not gain updates from addons.mozilla.org so a few hours ago I began the chore of finding and reinstalling all AMO-based extensions that are without metadata from AMO. (A very tedious chore, because the new AMO makes many older extensions difficult to find.)

**Comment by MrAlex94** [comment]
Hi Graham,

Just to let you know I have read all your replies, I have just been under heavy load getting all the next releases out but I will give a proper in-depth reply when I have the chance 👍

**Comment by grahamperrin** [comment]
Thanks, AOK, no rush 👍 

(If I sense urgency on any issue, I'll simply upvote comments etc. or (in exceptional cases) `@` ping you.)

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/commit/8132766ef286208d7ea5137a1ee49b93bb8d4161#diff-d7a0401e94f68887594ad1d1d9f9c28dR44 a minor comment. 

https://github.com/MrAlex94/Waterfox/commit/8132766ef286208d7ea5137a1ee49b93bb8d4161#diff-d7a0401e94f68887594ad1d1d9f9c28dR45 noted with thanks.

**Comment by grahamperrin** [comment]
Review time. 

Speeding through this issue (not in detail), and from what I recall of a refresh (some time ago), I reckon that there's nothing more to be done.
