### ISSUE TITLE
Removing or making optional the safety list disabling contentscripts on certain pages

### ISSUE THREAD

**Issue by zakius** [BrowserWorks/waterfox#301]
I'm not sure how to contact you about this idea so I'm really sorry if it's not the best place

I wanted to ask if when/if you pick up 57+ and start working with them you'd consider removing or making optional the safety list disabling contentscripts on certain pages since it's one of things that breaks the most and should be easy fix in spirit of user control

Thanks for your hard work till now and giving us hope

**Comment by grahamperrin** [comment]
## removing or making optional the safety list disabling contentscripts on certain pages

Maybe edit the title of this issue? To make it distinctive. 

(We have other issues that relate to _57_ and _57+_.)

**Comment by laniakea64** [comment]
The option already exists in 57+.  See https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/

**Comment by zakius** [comment]
@laniakea64 but it doesn't enable them on internal pages or pages generated by extensions so it doesn't help at all (how often do you visit mozilla pages? and how often you open a new tab?)

**Comment by laniakea64** [comment]
Ok, so what you're asking is more than just disabling the safety list.  IIUC what you're asking is the option to let WebExtensions content scripts run on **all** pages, privileged and unprivileged, including browser internal pages and other WebExtensions' pages.  Correct?

**Comment by zakius** [comment]
that's exactly what I mean, I'm sorry if it wasn't clear enough
