### ISSUE TITLE
Add back old search

### ISSUE THREAD

**Issue by phly95** [BrowserWorks/waterfox#302]
I am a Firefox 57 refugee, but I have always since 2014 had to use some method of getting back the old search, where you just have a drop-down and instantly change your current (default) search engine and it wouldn't screw up the order of the list (look at pale moon's search bar). Most importantly, you can change search engines using just your keyboard.

Currently I use classic theme restorer as a way to get back this feature, but it takes too many steps on public computers, and I think it would be great to add it back in, maybe even as the default option (let's be honest, Firefox made the new search so they could make money from Yahoo, we don't need to inherit any money-grabbing tactics from Mozilla)

Personally, I would also avoid having the address bar suggest search results by default for privacy reasons, I think it would be preferable to put that choice on the browser import screen with a short explanation of the convenience vs privacy trade-off.

**Comment by GitCurious** [comment]
+1 for restoration of "Old Search" if it`s possible.

I also **depend** on CTR currently for several features but one less dependency can only be a good thing going forwards.

**Comment by hockeymikey** [comment]
This should be low priority.  CTR can already add this feature back in and literally takes a minute.

**Comment by ratchetchan** [comment]
No, it should be high priority. CTR's "old search" feature no longer functions.

**Comment by hockeymikey** [comment]
@ratchetchan But it does work, I'm literally using it right now...

**Comment by ratchetchan** [comment]
@hockeymikey it does now. There's been an update that fixed it.

**Comment by phly95** [comment]
Even if it can be added back via classic theme restorer, why would anyone want the new search by default anyway? The only advantage the new search has is that it strengthens search engine sponsorships by making it more difficult to switch search engines quickly. Think about it, is an old granny going to know to go to the settings menu to change the search engine to something they like? (I mean to be fair, old grannys are probably not using waterfox, but that's beside the point)

**Comment by ghost** [comment]
Personally i was thinking that it was meant to be touch friendly and the madness of convergence (one UI everywhere) landed it on the desktop.

I'll add my voice, that the old search box was beater...

**Comment by phly95** [comment]
Just a heads up, turns out you can get old search functionality if you use ctrl+arrow, both on waterfox and modern Firefox.

**Comment by grahamperrin** [comment]
> ctrl+arrow,

In what context?

**Comment by ghost** [comment]
select the search box, then with ctrl+arrow you can change the default engine.... meh... Still a far cry from the original....

**Comment by grahamperrin** [comment]
OK, thanks! 

Slightly disorienting: 

![2018-11-06 06 57 14 waterfox](https://user-images.githubusercontent.com/192271/48048229-bbfa0680-e192-11e8-81ba-583177fbc5be.png)

– and without using either <kbd>Down</kbd> or <kbd>Up</kbd>: 

![2018-11-06 07 04 11 add back old search issue -302 mralex94-waterfox](https://user-images.githubusercontent.com/192271/48048258-daf89880-e192-11e8-834c-48d91650e973.png)

The incomplete (exclusive) arrays look slightly buggy to me, I reckon that they're an unexpected side-effect of a design decision.

**Comment by grahamperrin** [comment]
> … old search …

<strike>What is this, exactly?</strike> 

OK, now I think I understand …

> … instantly change your current (default) search engine …

Whilst I do sometimes use [Old Search Fixed](https://github.com/istador/old-search-fixed/), I do **not** think that the _persistent_ change (resulting from _one-off_ use of a search provider) is a sane/safe default for the browser. 

Too great a risk of end users inadvertently sending a search string to the wrong provider. I did this, myself, too often.

**Comment by ghost** [comment]
in the good old days...

the url bar was JUST an url bar, NO search.

The search box, did the search, you changed search engines easily, and had the little favicon to tell you on what it is set.

The current BS come from copying google chrome, that of course is totally unbiased and wouldn't try to force you to just use google or spy on you...

I had completely forgotten about search in the url bar, i have that deactivated. I'm taking back what i said earlier about touch optimization, like phly95 said, it's just a shity trick.

In my opinion, search in the url bar should be deactivated by default, and next to it have the old search box with clear and easy change of search provider. With this system, the power of the default decreases dramatically. These changes should come together.

**Comment by timur-g** [comment]
Same as  #162. I support this one.

**Comment by MrAlex94** [comment]
As mentioned, using CTR is the best solution to this.
