### ISSUE TITLE
tearing on linux even with force enabled layers acceleration

### ISSUE THREAD

**Issue by davidbepo** [BrowserWorks/waterfox#305]
both firefox and waterfox have a tering issue in fullscreen videos:
https://wiki.archlinux.org/index.php/firefox#Tearing_video_in_fullscreen_mode
but in firefox if you force enable acceleration the issue is fixed
in waterfox it isnt

**Comment by davidbepo** [comment]
also sometimes fullscren only shows a liitle rectangle:
![captura de pantalla de 2017-12-19 21-52-38](https://user-images.githubusercontent.com/18667173/34178365-361fc74e-e507-11e7-9808-fb21c89f3ac6.png)

**Comment by davidbepo** [comment]
this issue is what prevents me from switching to waterfox :(

**Comment by grahamperrin** [comment]
## Intel GM45 GPU

Not reproducible with full screen views of https://vimeo.com/248072306 in Waterfox 56.0.1 on Kubuntu 17.10 on an [Ergo Vista 621](https://web.archive.org/web/20110920184330/http://www.ergo.co.uk:80/document/webdocument.asp?Document=DPU3795) with Intel GM45. 

With and without the force, playback is tear-free. 

### Side note

At a glance, `layers.acceleration.force-enabled` causes this message to appear when Waterfox is started at the command line: 

> ATTENTION: default value of option force_s3tc_enable overridden by environment.

----

@davidbepo what's your hardware? 

Also, please let us have the URL of an affected video. 

Thanks.

**Comment by davidbepo** [comment]
im on intel hd 5500 on latest mesa git
anhything on animeyt.tv dailymotion option for example:
http://www.animeyt.tv/ver/one-piece-818-sub-espanol

**Comment by davidbepo** [comment]
still happens in 56.0.2

**Comment by grahamperrin** [comment]
Thanks, 

> http://www.animeyt.tv/ver/one-piece-818-sub-espanol

Adobe Flash Player there. Is hardware acceleration enabled in the player, or disabled?

**Comment by davidbepo** [comment]
the dailymotion option doesnt use flash and has the problem

**Comment by grahamperrin** [comment]
Thanks. 

Are you now at version 56.0.4.1? 

What's the source of your installation – is it the `.tar.bz2` file at <https://www.waterfoxproject.org/downloads>?

**Comment by davidbepo** [comment]
no im at 56.0.3
i use the aur waterfox-bin

**Comment by davidbepo** [comment]
i updated to 56.0.4.1 and the same still happens

**Comment by jbeich** [comment]
Maybe cherry-pick mozilla/gecko-dev@a67756af6ac4.

**Comment by davidbepo** [comment]
issue is fixed in 56.1.0, switching to waterfox !!
