### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#307]
It's impossible to login on http://www.strat-talk.com/ with WF 56.0. 
Latest FF and other browsers can do it, no problem at all.

**Comment by grahamperrin** [comment]
What exactly happens?

**Comment by ghost** [comment]
It looks like it sends the form but after response it is guest-looking page again. I just can suppose that something is missed in post request or broken cookies. Server does get the data -- e.g. if I type wrong password it renders form with an error message about it. And as I said before, all is ok in all other browsers.

**Comment by ghost** [comment]
All is ok now, so I close the issue. No idea what it was.
