### ISSUE TITLE
Add global keyboard shortcut support to commands API

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#308]
"global" property is currently only supported with Chrome and Opera:

http://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility

That means until Waterfox implements `global` WebExtension keyboard shortcuts
will only work if the browser has focus:

http://developer.chrome.com/apps/commands#scope

Reference:

http://bugzilla.mozilla.org/show_bug.cgi?id=1411795

**Comment by svnpenn** [comment]
https://github.com/andymckay/arewewebextensionsyet.com/issues/21

**Comment by nu8** [comment]
Why close?
