### ISSUE TITLE
Extension IPvFox doesn't work in waterfox 56.0

### ISSUE THREAD

**Issue by jcea** [BrowserWorks/waterfox#310]
I use IPvFox (https://addons.mozilla.org/en-US/firefox/addon/ipvfox/) extensively in Firefox and it is not working in Waterfox 56. It simply shows a question mark instead of IPv4/IPv6 information. This extension works fine under Firefox 56.0.2.

Thanks for your time.

**Comment by Squall-Leonhart** [comment]
it is not e10s compatible, you must open a non-e10s window from the file menu to use it.

**Comment by grahamperrin** [comment]
If you install Waterfox 56.0.2 then multi-process will be disabled by the extension.

**Comment by jcea** [comment]
Suppose I am not familiar with things like "e10s". Could you explain for dummies?. What can I do?.

This extension works just fine with firefox 56.

Is there anything trivial in the code that I can change to make it work under waterfox?.

Could I just disable e10s in waterfox?.

Thanks :-)

**Comment by jcea** [comment]
As I read, e10s comes from "electrolisis", running several content processors. This was supposed to be deployed in firefox 54. I am running firefox 56. In my about:config I see this:

extensions.e10sBlockedByAddons;true
extensions.e10sMultiBlockedByAddons;true

Should I activate those configuration options in waterfox too?.

**Comment by grahamperrin** [comment]
An explanation _for dummies_ would be nice :-) but given the recent (and possible future) e10s-related changes to Waterfox 56.x I should put that explanation on hold. 

If you use 56.0.3, the safest advice is to **disallow multi-process Waterfox**. The preference is at: 

about:preferences#general

----

Technical: [Waterfox: e10s, multi-process, extensions.e10sBlocksEnabling and extensions.e10sMultiBlocksEnabling · Issue #397 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/397)

**Comment by jcea** [comment]
I disabled e10s. Problem solved.

Thanks.
