### ISSUE TITLE
e10s: browser.tabs.remote.force-disable to disable mutiprocess Firefox or Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#311]
## Environment

Edge case. A **single profile** that is: 

- **sometimes** used with Waterfox (e.g. 56.0)
- **other times**, used with a reasonably compatible version of Firefox (e.g. 56.0.2 (64-bit)

– never concurrent. 

## Steps

1. Use Firefox with an extension that is not compatible with e10s
2. quit Firefox
3. launch Waterfox
4. realise the incompatibility – e10s enabled by default, without regard to the presence of incompatible add-ons
5. `[ ] Enable multi-process Waterfox` – disable e10s
6. accept the invitation to restart
7. quit Waterfox
8. use Firefox
9. quit Firefox
10. use Waterfox

## Required

- e10s disabled

## Actual result

- e10s enabled

## Volatile workaround

- again, `[ ] Enable multi-process Waterfox`
- again, accept the invitation to restart
- and so on – clearing the ✔️ from the ☑️ is non-persistent with steps such as those above

## Persistent workaround

- about:config 
- new boolean, `browser.tabs.remote.force-disable`
- `true` – switches off multiprocess for both Firefox _and_ Waterfox
- restart Waterfox.

----

## Side note

Given the likely user bases, I reckon that e10s should be disabled by default. However, I'm very new to the community (my reckoning is without historical knowledge of Waterfox).

**Comment by WagnerGMD** [comment]
```
lockPref("browser.tabs.remote.autostart",false);
lockPref("browser.tabs.remote.autostart.1",false);
lockPref("browser.tabs.remote.autostart.2",false);
lockPref("browser.tabs.remote.force-enable",false);
## In the case I wil add :
lockPref("dom.ipc.processCount",0);
lockPref("dom.ipc.processCount.web",0);
lockPref("accessibility.force_disabled",0);
```
Just if you want to be sure e10s is totally disabled.

**Comment by grahamperrin** [comment]
Thanks, `browser.tabs.remote.force-disable` alone should suffice.

**Comment by grahamperrin** [comment]
> …  reckon that e10s should be disabled by default. …

Noted with thanks, at <https://github.com/MrAlex94/Waterfox/issues/309#issuecomment-353610926> 

> A fair few people complained that e10s blocking wasn't necessary, so I [disabled](https://github.com/MrAlex94/Waterfox/commit/9c4cc5585e2d6b00ce06fcdde9d98fbd400471c6) it but seems that the problems it does cause to add-ons not compatible is greater. Will revert it I reckon for the next release.

## Side note

Mozilla bug [1394225 - multiprocess (e10s) automatically enabled at launch after installing extensions that are not compatible with multiprocess](https://bugzilla.mozilla.org/show_bug.cgi?id=1394225) – in recent months I have not seen (have not watched for) that bug …

… just something to bear in mind if – **without** `browser.tabs.remote.force-disable` – with a future version of Waterfox, there is _apparently_ random behaviour after an incompatible extension is installed.
