### ISSUE TITLE
WATERFOX 56 - JAVA NOT WORKING

### ISSUE THREAD

**Issue by Decopi** [BrowserWorks/waterfox#313]
Hi,

I downloaded JAVA (jre-8u151-windows-x64.exe) from a Alex Kontos comment in Waterfox 56 release page (11 days ago).

I did a clean JAVA install, first uninstalling and cleaning any trace of JAVA.
I also installed JAVA with everything closed, and restarted computer (Windows 10).

At Waterfox (56 64-bit) add-ons page, both JAVA plugins appear "ok" (ask to activate).
At about::plugins, JAVA appears "enable".
At https://www.whatismybrowser.com, JAVA appears "installed".
However, JAVA doesn't work in websites. Sadly after many tests, JAVA doesn't work in my Waterfox (56 64-bit).

If it is not a Waterfox (56 64-bit)' bug, please help me. Thank you!

**Comment by grahamperrin** [comment]
## … x64 … 

Please also subscribe to: 

- [Java64 -> ClassNotFoundException · Issue #283 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/283)

**Comment by MrAlex94** [comment]
Fixed [here](https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.0.1%20Setup.exe).

@grahamperrin, please see if it works for yourself as well.

**Comment by Decopi** [comment]
@MrAlex94 thank you!
I need the portable version. By miracle, do you have the fixed WF56.0.1 in portable version? If not, don't worry, I'll wait for it.
Thanks again!

**Comment by MrAlex94** [comment]
Yes, it's [here](https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_56.0.1_English.paf.exe).

**Comment by Decopi** [comment]
@MrAlex94 thank you!.... now JAVA works perfectly in this WF version! (please, feel free to close the issue).

Just last question: This WF version 56.0.1 is based in which FF version?

Thanks a lot again!

**Comment by MrAlex94** [comment]
56, but security issues patched up to 57.0.2

**Comment by grahamperrin** [comment]
## FreeBSD

https://svnweb.freebsd.org/ports?view=revision&revision=456269 around hour ago for `56.0.1.s20171212` (thanks @jbeich), it'll probably be a few hours before a built package becomes available to me. 

Testing with a FreeBSD-CURRENT that's outdated (but should be fine for this purpose), 

```text
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # date ; uname -v 
Thu 14 Dec 2017 00:55:13 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # pkg info icedtea-web | grep -i version
Version        : 1.6.2_3
root@momh167-gjp4-hpelitebook8570p-freebsd:~ # 
```

(Notes to self: with `56.0.s20171208`, https://www.whatismybrowser.com/ confirms that Java is installed but https://javatester.org/version.html does not present its pink rectangle … (**postscript**) neither does it present a plugin icon in the address bar, although I did activate the IcedTea-Web plugin there a day or two ago. At https://java.com/en/download/installed8.jsp the verification routine (for Firefox ESR) did initially present the plugin icon – during and after activation – but subsequent visits to the page are without the icon in the address bar.)

## Windows 7 Enterprise

I'll have an opportunity to test `56.0.1` later today, at one of the handful of managed workstations where I performed unmanaged (automatically updating) installations of `56.0`.

**Comment by grahamperrin** [comment]
Windows 7 Enterprise: success. 

----

I'll raise a separate issue for the problem involving IcedTea-Web.
