### ISSUE TITLE
waterfoxproject.org displays operating system incorrect

### ISSUE THREAD

**Issue by TomJansen** [BrowserWorks/waterfox#314]
On my Windows machine, waterfoxproject.org greets me with a download for Mac button. I am using Waterfox to browse to waterfoxproject.org.

On Linux, the site detects my machine correctly.

**Comment by TomJansen** [comment]
It works on Waterfox 56 now.

**Comment by Squall-Leonhart** [comment]
I actually see this same thing in both my 8.x and 10 VM's.

**Comment by TomJansen** [comment]
With Waterfox 56?

**Comment by Squall-Leonhart** [comment]
Suddenly its fine on 8.1, but 10 still shows Download for Mac.

oh, Windows 7 host with waterfox 56 also shows "Download for Mac"

strange, i opened a second tab and they load the for windows button properly now even in the first tabs of each.

**Comment by TomJansen** [comment]
Checked again, on Windows 7, it shows "download for mac" for a split second and then switches to "download for windows". Can't test on others OSes for the moment.

**Comment by grahamperrin** [comment]
With `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0`, the download offer is for Windows. 

With `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30`, the offer is for Mac. 

With Firefox Quantum on a Mac, the offer is for Mac.

**Comment by cnleo** [comment]
Maybe a Javascript thing? Used NoScript Addon or something that blocked JS?

**Comment by grahamperrin** [comment]
This evening with 56.0.2_1 on FreeBSD-CURRENT, I found an offer for Linux, which is probably expected in my case. However: with Firefox and Waterfox there's often the problem of stale/outdated content – I can't guess how many hours/days ago the page was loaded – so … 

… with the default user agent `Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0.2 Waterfox/56.0.2` I keyed <kbd>Control</kbd>-<kbd>F5</kbd> then the offer became

> Download for Mac

– with **no** subsequent transition to a different platform.

**Comment by grahamperrin** [comment]
Hmm, maybe the issue is random/transient (I do have a heavily extended profile, maybe an extension increases the risk of the issue occurring). 

In a new tab, subsequent visits to https://www.waterfoxproject.org/ were not bugged. The _Mac_ quickly switched to _Linux_. 

I toyed with other URLs: 

- https://waterfoxproject.org/ 
- http://waterfoxproject.org/

– could not reproduce the issue.

**Comment by TomJansen** [comment]
The first time I loaded the site in a long time (no cached version) the offer was mac (but I am on Windows). Then I opened a second tab with the website and the offer on the second tab became Windows. Reloading the first tab changed it from mac to windows, so I think it has something to with a the cache of the site.

Waterfox 56.0.3 btw

**Comment by grahamperrin** [comment]
Following the recent [reset of the CDN cache](https://github.com/MrAlex94/Waterfox/issues/385#issuecomment-359136689) (for a different issue) I make a screen recording of this issue. 

If it helps, from near the end of the recording: 

![2018-01-20 13 07 31 frame](https://user-images.githubusercontent.com/192271/35183869-c1260934-fde4-11e7-9c65-7a305e062780.png)

```
TypeError: Argument 1 of MutationObserver.observe is not an object.[Learn More] scrollmap.xml:99:37
background: Tab 25 was updated Object { status: "loading" }  background.js:62:8
background: Tab 25 was updated Object { title: "waterfoxproject.org/" }  background.js:62:8
background: Tab 25 was updated Object { status: "loading", url: "https://www.waterfoxproject.org/" }  background.js:62:8
background: Tab 25 was updated Object { title: "Waterfox - The free, open and priva…" }  background.js:62:8
Error: WebExtension context not found! ExtensionParent.jsm:778:13
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  www.waterfoxproject.org:1
ReferenceError: $ is not defined[Learn More]  config.min.js:1:6267
	<anonymous> https://www.waterfoxproject.org/js/config.min.js:1:6267
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  www.waterfoxproject.org:1
Error: WebExtension context not found! ExtensionParent.jsm:778:13
SecurityError: The operation is insecure.  widget_iframe.9c00c8ca14a8618c4db8e2c43139b138.html:12
background: Tab 25 was updated Object { status: "complete" }  background.js:62:8
succesfully created thumbnail for www.waterfoxproject.org/  conex-background.js:284:20
"Handler function DebuggerProgressListener.prototype.onStateChange threw an exception: [Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js :: _docShellToWindow :: line 776"  data: no]
Stack: _docShellToWindow@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:776:9
_docShellsToWindows/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:800:38
_docShellsToWindows@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:800:12
_notifyDocShellsUpdate@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:804:19
DebuggerProgressListener.prototype.onStateChange<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:1620:7
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 776, column: 0"  ThreadSafeDevToolsUtils.js:88
"Handler function DebuggerProgressListener.prototype.onStateChange threw an exception: [Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js :: DebuggerProgressListener.prototype.onStateChange< :: line 1623"  data: no]
Stack: DebuggerProgressListener.prototype.onStateChange<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/tab.js:1623:9
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
Line: 1623, column: 0"  ThreadSafeDevToolsUtils.js:88
[Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: chrome://browser/content/browser.js :: onStateChange :: line 5110"  data: no]  (unknown)
	onStateChange chrome://browser/content/browser.js:5110:9
	callListeners chrome://browser/content/tabbrowser.xml:492:24
	_callProgressListeners chrome://browser/content/tabbrowser.xml:513:13
	_callProgressListeners chrome://browser/content/tabbrowser.xml:595:22
	onStateChange chrome://browser/content/tabbrowser.xml:784:15
NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIWebProgress.DOMWindow]  WebNavigationContent.js:208
Error: WebExtension context not found!
```

The recording: https://photos.app.goo.gl/AUu9R0ADGSftBBuf1

Many extensions, and I have not attempted to reproduce the issue with Waterfox in safe mode, so I should not treat what's above as conclusive. 

(There are other issues in the recording, I'll keep those separate from this issue 314.)

**Comment by grahamperrin** [comment]
Review time. Close this?

**Comment by TomJansen** [comment]
Yes, the whole website has changed, just tested it with internet explorer and waterfox and it works (windows 10)
