### ISSUE TITLE
Waterfox 56: Can't assign file/protocol associations to Waterfox when Firefox is also installed (Windows 7)

### ISSUE THREAD

**Issue by donnch** [BrowserWorks/waterfox#315]
Windows 7 is not seeing Waterfox and Firefox as separate entities in some situations on my computer. If I set Waterfox as the default browser, Windows shows "this program has all its defaults" in the Set Associations interface, but the same is shown for Firefox. For both programs, the checkboxes are ticked but greyed out. Clicking on a file or link will open Firefox.

Notably, the program labelled "Waterfox" in the list of default programs has a Firefox logo, not Waterfox.

And if I assign Waterfox as default for a filetype (e.g. .html) through _Windows Explorer>Open with_ instead of through the _Set Associations_ window, both Waterfox and Firefox lose the association in the Set Associations interface (ie, become unchecked). Waterfox then correctly opens the filetype, but this is not an adequate workaround, because the file protocols are unchanged, so links in emails, for instance, still try to open in Firefox.

**Comment by grahamperrin** [comment]
Were both Firefox and Waterfox installed with admin privileges?

**Comment by donnch** [comment]
Yes, both were.

**Comment by grahamperrin** [comment]
#538
