### ISSUE TITLE
Performance regression in rendering of table elements

### ISSUE THREAD

**Issue by Happy-Ferret** [BrowserWorks/waterfox#317]
Running the following benchmark under the most recent Waterfox build (or any Firefox 56.x based browser, for that matter. I still have an older 56.0 Beta that exhibits the same behavior) yields consistently slower results than is the case under both Firefox Quantum and Basilisk (Firefox 55.x based).

http://sinz.org/Maze/table.html?seed=1

In fact it's so slow, IE11 runs circles around it.

**Comment by grahamperrin** [comment]
## Waterfox 56.0.1

No extensions enabled: 

```text
Maze Complete   (Table)   [Firefox 56]
Maze size: 114 x 59 (6726 tiles)
298 	ms in JavaScript 	0.044 	ms/tile
103482 	ms not in JavaScript 	15.385 	ms/tile
103780 	ms total time 	15.429 	ms/tile
64.81 	tiles per second 	11 	tiles/step
```

## Firefox 56.0.2 (64-bit)

Using the same profile: 

```text
Maze Complete   (Table)   [Firefox 56]
Maze size: 115 x 60 (6900 tiles)
311 	ms in JavaScript 	0.045 	ms/tile
130492 	ms not in JavaScript 	18.911 	ms/tile
130803 	ms total time 	18.956 	ms/tile
52.75 	tiles per second 	11 	tiles/step
```

## Web 3.24.2

```text
Maze Complete   (Table)   [Safari 11]
Maze size: 115 x 63 (7245 tiles)
132	ms in JavaScript	0.018	ms/tile
4753	ms not in JavaScript	0.656	ms/tile
4885	ms total time	0.674	ms/tile
1483.11	tiles per second	11	tiles/step
```

**Comment by Happy-Ferret** [comment]
Yep. 50-60 something tiles per second vs roughly 1,500 on most other browsers (including older versions of Firefox. I went as far back as Firefox 44).

Darn frustrating. Especially as 56 was supposed to be the second fastest Firefox (was hailed as the fastest Firefox ever, prior to the release of Quantum/57).

**Comment by grahamperrin** [comment]
I ran the test at a slower computer with Kubuntu. 

## Firefox Nightly 59.0a1 (2017-12-22) (64-bit)

### Normal mode

```text
Maze Complete   (Table)   [Firefox 59]
Maze size: 88 x 54 (4752 tiles)
380 	ms in JavaScript 	0.079 	ms/tile
24783 	ms not in JavaScript 	5.215 	ms/tile
25163 	ms total time 	5.295 	ms/tile
188.84 	tiles per second 	11 	tiles/step
```

## Firefox 57.0.1 (64-bit)

### Safe mode

```text
Maze Complete   (Table)   [Firefox 57]
Maze size: 88 x 54 (4752 tiles)
461 	ms in JavaScript 	0.097 	ms/tile
100746 	ms not in JavaScript 	21.2 	ms/tile
101207 	ms total time 	21.297 	ms/tile
46.95 	tiles per second 	11 	tiles/step
```

### Normal mode

```text
Maze Complete   (Table)   [Firefox 57]
Maze size: 88 x 54 (4752 tiles)
203 	ms in JavaScript 	0.042 	ms/tile
108663 	ms not in JavaScript 	22.866 	ms/tile
108866 	ms total time 	22.909 	ms/tile
43.64 	tiles per second 	11 	tiles/step
```

## Waterfox 56.0.1

### Safe mode

```text
Maze Complete   (Table)   [Firefox 56]
Maze size: 88 x 55 (4840 tiles)
476 	ms in JavaScript 	0.098 	ms/tile
124947 	ms not in JavaScript 	25.815 	ms/tile
125423 	ms total time 	25.913 	ms/tile
38.58 	tiles per second 	11 	tiles/step
```

### Normal mode

```text
Maze Complete   (Table)   [Firefox 56]
Maze size: 88 x 54 (4752 tiles)
271 	ms in JavaScript 	0.057 	ms/tile
92646 	ms not in JavaScript 	19.496 	ms/tile
92917 	ms total time 	19.553 	ms/tile
51.14 	tiles per second 	11 	tiles/step
```

**Comment by MrAlex94** [comment]
What results do you get in Firefox 57+?

**Comment by MrAlex94** [comment]
Apologies, misread. I see the results are fairly similar. 

On bugzilla now. Checking if there is a filed bug.

**Comment by Happy-Ferret** [comment]
@grahamperrin It's interesting that 57.0.1 would be that slow, as well. I've only run comparisons against Firefox 44, Firefox 55, Firefox 56 and Firefox 58. All but 56 showed superior performance, so I assume this must be something introduced with 56 and fixed after 57 was already released.

@MrAlex94  Thanks for looking into it. I'm in the process of getting my own Firefox fork up to speed (slightly different focus from Waterfox). Would be happy to share code in the future, where applicable.
