### ISSUE TITLE
Waterfox 55.2.2 doesn't update automatically

### ISSUE THREAD

**Issue by Serkan-devel** [BrowserWorks/waterfox#318]
The about-screen of Waterfox says it's up-to date even though it's not.

How can I update it on Debian 9 manually?

**Comment by Remolten** [comment]
I have the same issue on the latest version of macOS (10.13.2).

**Comment by Serkan-devel** [comment]
bump

**Comment by criztovyl** [comment]
How did you install Waterfox, @serkan-devel?

**Comment by Serkan-devel** [comment]
I've extracted the tarball into a directory, created a .desktop-file
<pre>
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Waterfox
Exec=~/waterfox/waterfox
Terminal=false
Type=Application
Icon=~/waterfox/browser/icons/mozicon128.png
</pre>
and ran it. I was able to update it had recieved automatic updates before

**Comment by MrAlex94** [comment]
55.2.2 won't receive the update for now. Some add-ons have broken and testing out reversing the patches [here](https://blog.mozilla.org/addons/2017/07/18/compatibility-firefox-56/) to improve compatibility. Looks like in 56, e10s **needs** to be disable for some popular add-ons as they don't use [CPOWs](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers).

**Comment by Serkan-devel** [comment]
Maybe you could give the option to explicitly update, while losing addons or update to an ESR version. Lots of people seem to be here because they don't like the changes of the newsest Firefox and lost integrity which got resolved here.

It would be nice to see something like **Waterfox ESR** and **Waterfox Quantum**
both without DRM or tracking as allways.

**Comment by Serkan-devel** [comment]
But wait, does Waterfox 55 still use the same profile as Firefox?
Sometimes I get the Waterfox icon on firefox.
How can I import all settings to a newer Waterfox version?

**Comment by angela-d** [comment]
@Serkan-devel 
As of Waterfox 56, it has it's own profile: .waterfox instead of .mozilla/waterfox

When I installed Waterfox on my work computer, I was prompted (by Waterfox 56) to import settings from Firefox and it took everything except the personas theme.

**Comment by Serkan-devel** [comment]
Could I just move everything from `.mozilla/waterfox` to `.waterfox` and reinstall waterfox?

**Comment by angela-d** [comment]
[Give this a try, instead](http://kb.mozillazine.org/Moving_your_profile_folder)

Though, if you're trying to migrate Firefox data to Waterfox 56, the first launch should prompt you for import options.

On my laptop, I had an older version of Waterfox (which was uninstalled prior to installing 56) + Firefox ESR installed and it did not prompt to import any data at all.

Work computer had only Firefox ESR (never Waterfox) and was prompted to import, so your mileage may vary.

**Comment by Serkan-devel** [comment]
Just reinstalled waterfox and managed to preserve all previous settings and extensions.
Don't know if this will work for @Remolten too

**Comment by grahamperrin** [comment]
Please, is this still an issue? 

Has your 55.2.2 picked up the (February 2018) update to 56.0.4.1?

**Comment by Serkan-devel** [comment]
As stated above, I reinstalled it and currently have Watefox 56.0.4.1

**Comment by grahamperrin** [comment]
> Waterfox 55.2.2 doesn't update automatically

Review time. Close this?

**Comment by Serkan-devel** [comment]
@grahamperrin I want to close it but I don't know if @Remolten still has that issue. I've reinstalled WF to fix it

**Comment by Remolten** [comment]
A reinstall fixed it for me.
