### ISSUE TITLE
High load on some pages

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#319]
E.g. this page https://vk.com/id1?z=photo1_278184324 raises CPU usage up to 50%. Problem issued under Firefox and Waterfox on macos. I tried to disable all plugins -- no success. I wrote to the site's support, they said that the problem is related with browser.  Can somebody confirm the problem?

**Comment by MrAlex94** [comment]
I guess a better way to test is in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode).

**Comment by ghost** [comment]
Just tried in safe mode -- the problem is still here.

**Comment by Lalarian** [comment]
It does same for me. But I think that's just because of how the old engine is working, and the reason, why Mozilla developed Quantum. It's just slow on heavy element loaded sites.

**Comment by ghost** [comment]
New FF with Quantum engine has exactly same problem. I just checked it.

**Comment by Lalarian** [comment]
I now have examined the problem somewhat:
I had the same problem. Taskmanager showed me it was the native client, causing one core to work at 100% continuously. When I switched to an AddOn using http instead of native client, everything went fine again!

**Comment by grahamperrin** [comment]
Would anyone above like to review this issue with 56.2.0 before its general release? 

[Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)

Thanks

**Comment by MrAlex94** [comment]
Pretty generic error, but have been keeping an eye out for specific bugs.
