### ISSUE TITLE
Why can't waterfox run at the same time with firefox?  

### ISSUE THREAD

**Issue by compscied** [BrowserWorks/waterfox#32]
It would be good to see if waterfox could run along with firefox at the same time?  I use palemoon (another firefox "fast" fork) and it can run side by side  just fine.  I actually wanted to benchmark Waterfox vs Firefox

I know about -p -no-remote but why not include this by default during install

**Comment by MrAlex94** [comment]
This was an old design choice I made a few years ago. I wanted a "seamless" experience, in which the user would be free to switch between FF/WF and having their data still be there.

**Comment by Prophious** [comment]
try portable... might help

**Comment by danpe91** [comment]
You could change the direct access so it executes with the -p parameter, that's what I did and I have one profile for FF and one for WF

It would be good to add something like this as a choice while installing
