### ISSUE TITLE
Add Autofill address support from mainline Firefox

### ISSUE THREAD

**Issue by Eggbertx** [BrowserWorks/waterfox#320]
Are there any plans to implement the ability to fill out forms with names/addresses that exists in mainline Firefox?

**Comment by jbeich** [comment]
19f76d75988f removed **formautofill** system addon. Firefox has it enabled on Nightly for all, on Beta with [en-US locale](https://bugzilla.mozilla.org/show_bug.cgi?id=1385196), on Release via [staged rollout](https://bugzilla.mozilla.org/show_bug.cgi?id=1405217) (only en-US, only addresses, 20% of users). For FF56+ behavior without relying on **shield-recipe-client** you'd probably need to drop the following conditional:
https://github.com/MrAlex94/Waterfox/blob/85b2f367f5acb06d0b08c694c9dd6f21c0ca6ad4/browser/app/profile/firefox.js#L1675-L1676

**Comment by grahamperrin** [comment]
#538
