### ISSUE TITLE
Remove rust requirement?

### ISSUE THREAD

**Issue by roytam1** [BrowserWorks/waterfox#321]
I wonder if we can remove rust requirement and keep C/C++ only for better portability?

**Comment by jbeich** [comment]
See [bug 1284816 comment 51](https://bugzilla.mozilla.org/show_bug.cgi?id=1284816#c51). Maybe pick up the linked FF55 patch and adjust it to WF56.

**Comment by MrAlex94** [comment]
Hmm, guess we need to weigh the cost–benefit of reverting the patches that affect XP/Vista support. Completely forgot about how Rust might support XP, and turns out that it's not very well at all. It's a Tier 3 platform and seems to be not in consideration at all.

**Comment by roytam1** [comment]
> Completely forgot about how Rust might support XP, and turns out that it's not very well at all. It's a Tier 3 platform and seems to be not in consideration at all.

currently only STD has some XP target support, no cargo/etc.
