### ISSUE TITLE
Oracle Java SE Runtime Environment plugin 11.152.2 not working on Linux

### ISSUE THREAD

**Issue by ijurisic** [BrowserWorks/waterfox#322]
Hello ,

I using Java (NPAPI plugin) at wrok, after switch on Waterfox can't to start aplication (blank page). 

My OS is Debian 9 GNU/Linux, but when I go to my friend on Windows, I ask him to install Waterfox and application works. 

Before try Waterfox, I use Firefox ESR and Pale Moon on my OS Debian 9 GNU/Linux without problems.

Any chance to fix this issue?

**Comment by criztovyl** [comment]
Any output in the Developer Console? (CTRL+SHIFT+J or Hamburger menu &rarr; Developer &rarr; Browser Console)

**Comment by ijurisic** [comment]
Screenshot is on link [https://s14.postimg.org/46y0lvln5/waterfox-java.jpg](https://s14.postimg.org/46y0lvln5/waterfox-java.jpg)

But for compare I open Waterfox and Pale Moon, in Waterfox don't see plugin but in Pale Moon I clear see plugin. [https://s14.postimg.org/6jalx4vb5/waterfox-plugin.jpg](https://s14.postimg.org/6jalx4vb5/waterfox-plugin.jpg)

Link for test: [https://www.java.com/en/download/installed8.jsp?detect=jre](https://www.java.com/en/download/installed8.jsp?detect=jre)

My result is: [https://s31.postimg.org/iz7flo9bf/waterpale.png](https://s31.postimg.org/iz7flo9bf/waterpale.png)

**Comment by PandaCodex** [comment]
@ijurisic does it show in Cyberfox, you have to enable plugins found in the browsers options curious if its just Waterfox 64 issue. might help narrow down more then could form a patch

**Comment by ijurisic** [comment]
@PandaCodex I try with Cyberfox but have result as Waterfox.

**Comment by grahamperrin** [comment]
`about:plugins`

What exactly is installed for Java? 

Here with FreeBSD-CURRENT I have: 

- IcedTea-Web 1.6.2

> NPAPI plugins not work on Linux

@ijurisic have you tested any other plugin? Or just the one? 

(I have NPAPI Adobe Flash Player working with Waterfox on FreeBSD-CURRENT<strike>. I have a hunch that it will also work on Linux.</strike> and Kubuntu.)

**Comment by ijurisic** [comment]
@grahamperrin 

I install last java 8u152 from source [Java SE Runtime Environment 8u152](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) on Pale Moon about:plugins give this [screenshot1](https://s14.postimg.org/i1aaxeci9/jre.png). I make package for Debian 9 if wont test [https://apt.jurisic.org/](https://apt.jurisic.org/). On Waterfox don't see plugin about:plugins looks [screenshot2](https://s14.postimg.org/3uuk2e6up/waterfoxplugin.png).

Ok, if is problem Java, I remove my package and install java from openjdk and my result is in Waterfox [about:plugins](https://s14.postimg.org/ab846erz5/icedtea-web.png) , looks good, but still don't work [screenshot3](https://s14.postimg.org/sgl2kgjrl/java-verifying.png).

**Comment by grahamperrin** [comment]
Thanks. I see two separate issues, one of which is familiar to me. 

@ijurisic maybe edit the title of this issue, to: 

- _Oracle Java SE Runtime Environment plugin 11.152.2 not working on Linux_

----

I'll raise a separate issue for the problem involving _IcedTea-Web_.

**Comment by grahamperrin** [comment]
## `~/.mozilla/plugins/libnpjp2.so` for Oracle's plugin

@ijurisic your screenshot –

![waterfoxplugin](https://user-images.githubusercontent.com/192271/34319642-54bc23e8-e7df-11e7-8507-36cad1486d2c.png)

– is symptomatic of an incomplete installation (or maybe you did not restart Waterfox after completing installation of the plugin). 

If `~/.mozilla/plugins/` does not exist – and if you wish to use Oracle's plugin with Firefox or Waterfox – please make the directory, then follow Oracle's instructions: 

- [Manual Installation and Registration of Java Plugin for Linux](https://docs.oracle.com/javase/8/docs/technotes/guides/install/linux_plugin.html)

----

That's not a workaround – there _is_ a bug (reproduced by me) affecting Oracle's Java Plugin for Linux – but for the plugin to be recognised by Waterfox, it's essential to have a symbolic link at a recognised path.

**Comment by grahamperrin** [comment]
Amongst the testers at <https://javatester.org/othertesters.html>: 

- http://www.cyscape.com/showbrow.asp

After a first run, there's a link to <http://www.cyscape.com/showbrow.asp?doJvmd=1>, results include:

> JavaApplets  True
> JavaEnabled  True
> JavaVersion  Java N/A (applet not scriptable)
> JavaVendor  Java N/A (applet not scriptable)

– and: 
> Plugin_JavaVer  1.8.0_152

**Comment by ijurisic** [comment]
@grahamperrin  

For package [oracle-java8-jre_8u152~stretch_amd64.deb](https://apt.jurisic.org/debian/pool/non-free/o/oracle-java8-jre/oracle-java8-jre_8u152~stretch_amd64.deb) I make folder in both paths (~/.waterfox/plugins and ~/.mozilla/plugins ) and manual copy plugin but still not show in list when calling about:plugins.

But my logic is .. if "is symptomatic of an incomplete installation" - whay that package work in Pale Moon?

Ok, I when get IcedTea plugin I got sam result as You.  In both way Java not work in Waterfox. 

Maybe Firefox blacklist this plugin after Firefox ESR v52 ?

**Comment by grahamperrin** [comment]
> … whay that package work in Pale Moon? …

Good question. I don't know enough about building on Linux to offer a good answer.

**Comment by ijurisic** [comment]
Still not work with Waterfox 2020.06 (64-bit) and with OpenJDK 11.0.7.
