### ISSUE TITLE
Vsync test fail

### ISSUE THREAD

**Issue by zcyzcy88** [BrowserWorks/waterfox#325]
http://www.vsynctester.com/
I see the frame-losing.

**Comment by grahamperrin** [comment]
Here: 

- Firefox 56.0.2 behaves similarly to Waterfox 56.0.1
- Chromium 61.0.3163.100 (Developer Build) (64-bit) is smoother but comparably lossy
- Pale Moon is better
- SeaMonkey 2.49.1 seems to have the best results.

**Comment by Squall-Leonhart** [comment]
Firefox has always used a horrible Vsync timer, a guy tried to get it fixed a few years back but he was unable to express himself well about it and the firefox devs were quite head in sand about the assumptions they were making on DWM

https://www.vsynctester.com/firefoxisbroken.html

**Comment by grahamperrin** [comment]
#538
