### ISSUE TITLE
Java plugin: IcedTea-Web activated but not working with Waterfox 56.0.1

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#326]
## Observations

An initial visit to either https://java.com/en/download/installed8.jsp?detect=jre or https://javatester.org/version.html will cause the generic plugin icon to appear in the address bar (to the right of the ⓘ (information) icon). 

Attention to the address bar will allow activation of the plugin. However: 

- the activated plugin is not effective; and 
- **if** allowance is remembered **then** all subsequent loads of the page will not present the icon in the address bar – in other words, no obvious way to end an allowance. 

[2017-12-19 09:02.ogv.zip](https://github.com/MrAlex94/Waterfox/files/1584059/2017-12-19.09.02.ogv.zip)

### If Adobe Flash Player is also installed

`about:addons` options for IcedTeaWeb include an option that is unexpected: 

> Block dangerous and intrusive Flash content ☑️ 

– the same option appears (and is expected) for Shockwave Flash. 

<https://www.ecosia.org/search?q=%22Block+dangerous+and+intrusive+Flash+content%22+%2B%22IcedTea%22> finds nothing. 

## From prior issues

<https://github.com/MrAlex94/Waterfox/issues/313#issuecomment-351575099> (2017-12-14): 

> … does not present its pink rectangle … (**postscript**) neither does it present a plugin icon in the address bar, although I did activate the IcedTea-Web plugin there a day or two ago. At https://java.com/en/download/installed8.jsp the verification routine (for Firefox ESR) did initially present the plugin icon – during and after activation – but subsequent visits to the page are without the icon in the address bar.) … 
 
<https://github.com/MrAlex94/Waterfox/issues/322#issuecomment-353695114> (2017-12-23): 

> …  openjdk and my result is in Waterfox about:plugins , 
> 
> ![icedtea-web](https://user-images.githubusercontent.com/192271/34319219-6a887dbc-e7d4-11e7-925a-71935536d4a3.png)
> 
> looks good, but still don't work 
> 
> ![java-verifying](https://user-images.githubusercontent.com/192271/34319225-7e98b330-e7d4-11e7-805c-d8ea6eb61304.png)

– the address bar is without the icon for the plugin. 

## Environments tested by me

1. Waterfox 56.0.1 on FreeBSD-CURRENT
2. Waterfox 56.0.1 on Kubuntu 17.10.

The FreeBSD environment: 

<details>
 
```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uname -v
Sat 23 Dec 2017 11:42:15 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info icedtea-web
icedtea-web-1.6.2_3
Name           : icedtea-web
Version        : 1.6.2_3
Installed on   : Tue Dec 19 04:12:55 2017 GMT
Origin         : java/icedtea-web
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : java www
Licenses       : GPLv2
Maintainer     : java@FreeBSD.org
WWW            : http://icedtea.classpath.org/wiki/IcedTea-Web
Comment        : Free Java plug-in and Java Web Start for OpenJDK
Options        :
        DOCS           : on
        PLUGIN         : on
        RHINO          : off
        TAGSOUP        : off
Shared Libs required:
        libintl.so.8
        libglib-2.0.so.0
Annotations    :
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 10.2MiB
Description    :
The IcedTea-Web project provides a Free Software web browser plugin running
applets written in the Java programming language and an implementation of
Java Web Start, originally based on the NetX project.

WWW: http://icedtea.classpath.org/wiki/IcedTea-Web
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info waterfox
waterfox-56.0.1.s20171212
Name           : waterfox
Version        : 56.0.1.s20171212                                                                  
Installed on   : Mon Dec 18 15:53:11 2017 GMT                                                      
Origin         : www/waterfox                                                                      
Architecture   : FreeBSD:12:amd64                                                                  
Prefix         : /usr/local                                                                        
Categories     : ipv6 www                                                                          
Licenses       :                                                                                   
Maintainer     : jbeich@FreeBSD.org                                                                
WWW            : https://www.waterfoxproject.org/                                                  
Comment        : Distilled fork of Firefox                                                         
Options        :                                                                                   
        ALSA           : on                                                                        
        BUNDLED_CAIRO  : on                                                                        
        CANBERRA       : off
        DBUS           : on
        DEBUG          : off
        DTRACE         : on
        FFMPEG         : on
        GCONF          : on
        INTEGER_SAMPLES: off
        JACK           : on
        LIBPROXY       : off
        OPTIMIZED_CFLAGS: on
        PROFILE        : on
        PULSEAUDIO     : on
        SNDIO          : off
        TEST           : off
Shared Libs required:
        libdbus-glib-1.so.2
        libgtk-x11-2.0.so.0
        libXext.so.6
        libpango-1.0.so.0
        libjpeg.so.8
        libpixman-1.so.0
        libsqlite3.so.0
        libcairo.so.2
        libgtk-3.so.0
        libffi.so.6
        libxcb-shm.so.0
        libX11-xcb.so.1
        libfreetype.so.6
        libcairo-gobject.so.2
        libatk-1.0.so.0
        libhunspell-1.6.so.0
        libevent-2.1.so.6
        libvpx.so.4
        libplc4.so
        libXcomposite.so.1
        libxcb.so.1
        libgdk_pixbuf-2.0.so.0
        libgio-2.0.so.0
        libssl3.so
        libXfixes.so.3
        libnss3.so
        libogg.so.0
        libv4l2.so.0
        libgobject-2.0.so.0
        libnssutil3.so
        libplds4.so
        libharfbuzz.so.0
        libstartup-notification-1.so.0
        libX11.so.6
        libdbus-1.so.3
        libXdamage.so.1
        libnspr4.so
        libXt.so.6
        libgraphite2.so.3
        libicuuc.so.60
        libpng16.so.16
        libicui18n.so.60
        libvorbis.so.0
        libglib-2.0.so.0
        libfontconfig.so.1
        libsmime3.so
        libgdk-x11-2.0.so.0
        libgdk-3.so.0
        libXrender.so.1
Annotations    :
        cpe            : cpe:2.3:a:mozilla:waterfox:56.0.1.s20171212:::::freebsd12:x64
        deprecated     : Temporary experiment
        expiration_date: 2018-01-30
        no_provide_shlib: yes
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 213MiB
Description    :
The Waterfox source code is a specialised modification of the Mozilla
platform, designed for privacy and user choice in mind. You should be
able to install it and compile Waterfox without any issues. Other
modifications and patches that are more upstream have been implemented
as well to fix any compatibility/security issues that Mozilla may lag
behind in implementing (usually due to not being high priority). High
request features removed by Mozilla but wanted by users are retained
(if they aren't removed due to security).

Features:

 o Disabled Encrypted Media Extensions (EME)
 o Disabled Web Runtime (deprecated as of 2015)
 o Removed Pocket
 o Removed Telemetry
 o Removed data collection
 o Removed startup profiling
 o Allow running of all 64-Bit NPAPI plugins
 o Allow running of unsigned extensions
 o Removal of Sponsored Tiles on New Tab Page
 o Addition of Duplicate Tab option (toggle with browser.tabs.duplicateTab)
 o Locale selector in about:preferences > General
 o Cookie Prompt

WWW: https://www.waterfoxproject.org/
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info flashplayer
flashplayer-28.0
Name           : flashplayer
Version        : 28.0
Installed on   : Mon Dec 18 15:53:48 2017 GMT
Origin         : www/flashplayer
Architecture   : FreeBSD:12:*
Prefix         : /usr/local
Categories     : multimedia www
Licenses       : 
Maintainer     : emulation@FreeBSD.org
WWW            : https://www.adobe.com/
Comment        : Native wrapper around Linux Flash Player
Annotations    :
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 0.00B
Description    :
Wrapper around Linux Flash Player that allows native browsers to display
Flash content.

WWW: https://www.adobe.com/
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```
 
</details>

**Comment by grahamperrin** [comment]
## BrowserHawk

Result of <http://www.cyscape.com/showbrow.asp?doJvmd=1>: 

- [Browser Capabilities Test Page.html.zip](https://github.com/MrAlex94/Waterfox/files/1584156/Browser.Capabilities.Test.Page.html.zip) or 
- https://screenshots.firefox.com/jmqchkncY8Q8y5Mt/www.cyscape.com

### A comparison

With Oracle's plugin at https://github.com/MrAlex94/Waterfox/issues/322#issuecomment-353726858 I had: 

>> …
>> JavaVersion Java N/A (applet not scriptable)
>> JavaVendor Java N/A (applet not scriptable)
> 
> – and:
> 
>> Plugin_JavaVer 1.8.0_152

Here in #326 with IcedTea-Web I have: 

> JavaApplets  True
> JavaEnabled  True
> JavaVersion  Java N/A (requires Java plugin, not available)
> JavaVendor  Java N/A (requires Java plugin, not available)

– and:

> Plugin_JavaVer  Not installed

----

## Side note

For me on FreeBSD this issue is: 
- a curiosity
- not a showstopper

– IcedTea-Web does work with (old) [Opera 12.16](https://www.freshports.org/www/opera), and with more recently ported [Pale Moon](https://www.freshports.org/www/palemoon).

**Comment by jbeich** [comment]
> ## Environments tested by me
>
> 1. Waterfox 56.0.1 on FreeBSD-CURRENT
> 2. Waterfox 56.0.1 on Kubuntu 17.10.

Are both GTK platforms affected or only FreeBSD?

**Comment by grahamperrin** [comment]
Both affected; and (if it's relevant) both have the same peculiarity with the Flash-related ☑️ at the foot of the preferences page for IcedTea-Web: 

![2017-12-23 18 55 36 add-ons manager - waterfox](https://user-images.githubusercontent.com/192271/34321965-5d8b4e16-e813-11e7-8f2d-dc7ff14ca801.png)

(I'm tempted to compare with `www/firefox-esr` but I don't want to lose the 56.0.2 that's locked down on my main machine. I might try it elsewhere …)

**Comment by grahamperrin** [comment]
> … peculiarity with the Flash-related ☑️ at the foot of the preferences page for IcedTea-Web: …

FWIW that's not apparent with Pale Moon on FreeBSD-CURRENT: 

![2017-12-23 19 07 12 pale moon](https://user-images.githubusercontent.com/192271/34322040-be7c7cda-e814-11e7-93d9-64e5c1c7a0ea.png)

![2017-12-23 19 07 25 pale moon](https://user-images.githubusercontent.com/192271/34322041-c398c598-e814-11e7-9f8e-5ae358f6bb0b.png)

**Comment by ijurisic** [comment]
I confirm this bug because I have the same situation on Debian 9.3 GNU/Linux

**Comment by grahamperrin** [comment]
Java console output: <https://pastebin.com/VHH9ing8>, a few things catch my eye. 

Line 364, 

> Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.

– that's unexpected because I _have_ already used `itweb-settings` to prefer a direct network connection. 

Line 365, 

> java.io.FileNotFoundException: /home/grahamperrin/.mozilla/firefox/home/grahamperrin/.waterfox/g5lllcwj.test/prefs.js (No such file or directory) …

Line 366, 

> Found preferences file: /home/grahamperrin/.mozilla/firefox//home/grahamperrin/.waterfox/g5lllcwj.test/prefs.js

– that's a nonsensical path. 

Line 367, 

> Using firefox's profiles file: /home/grahamperrin/.mozilla/firefox/profiles.ini

– **is that appropriate**?

**Comment by grahamperrin** [comment]
Hmm, I see some of the same peculiarities with Pale Moon, where the plugin does work. https://pastebin.com/ZKaHcRdE from the Java Console (with debugging disabled).

**Comment by grahamperrin** [comment]
Wondering whether the plug-in is bugged: 

- IcedTea [Bug 3535 – IcedTea-Web activated but not working with Waterfox on FreeBSD and Linux](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3535)

**Comment by grahamperrin** [comment]
https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3535#c4

> plugin was discontinued
