### ISSUE TITLE
~/.waterfox/plugins/ and ~/.waterfox/extensions/

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#327]
@MrAlex94 do you foresee any situation where a user might have `~/.waterfox/` **and not** the traditional `~/.mozilla/` directory?

If so, then maybe enhance Waterfox to work with: 

- `~/.waterfox/plugins/`

## Background

Whilst troubleshooting the Oracle side of #322 I experimented with `~/.waterfox/plugins/`: 

- with symbolic link `~/.waterfox/plugins/libnpjp2.so` the plugin is not recognised; is not listed at `about:plugins`
- with symbolic link `~/.mozilla/plugins/libnpjp2.so` the plugin is recognised, listed (but not working, as outlined in #322).

**Comment by MrAlex94** [comment]
> @MrAlex94 do you foresee any situation where a user might have ~/.waterfox/ and not the traditional ~/.mozilla/ directory?

If the user only has v55+ installed and never had the previous version of Waterfox, as well as never having had Firefox installed.

So Waterfox still checks for the .mozilla directory? I find that strange, unless that directory is hard coded somewhere or I’ve missed something somewhere. Hmm.

Also I’d just like to say thanks for helping out around in other issues, it’s a great help!

**Comment by grahamperrin** [comment]
Glad to help :-)

> … Waterfox still checks for the .mozilla directory? …

I'm not sure; I don't know the paths that are/were traditionally associated with plugins for Firefox. 

With FreeBSD I see `/usr/local/lib/browser_plugins/` (with e.g. contents as shown below); I have no idea what the equivalent might be on Linux. 

```text
# ls -hl /usr/local/lib/browser_plugins/
total 82
drwxr-xr-x   2 root  wheel     3B 18 Dec 18:39 linux-flashplayer
-rwxr-xr-x   1 root  wheel   122K 20 Dec 19:03 npwrapper.libflashplayer.so
drwxr-xr-x  10 root  wheel    10B 19 Dec 04:12 symlinks
# ls -hl /usr/local/lib/browser_plugins/symlinks
total 4
drwxr-xr-x  2 root  wheel     3B 19 Dec 04:12 gecko
drwxr-xr-x  2 root  wheel     4B 18 Dec 18:39 linux-firefox
drwxr-xr-x  2 root  wheel     4B 18 Dec 18:39 linux-opera
drwxr-xr-x  2 root  wheel     4B 18 Dec 18:39 linux-opera-devel
drwxr-xr-x  2 root  wheel     4B 18 Dec 18:39 linux-seamonkey
drwxr-xr-x  2 root  wheel     3B 19 Dec 04:12 opera
drwxr-xr-x  2 root  wheel     3B 19 Dec 04:12 opera-devel
drwxr-xr-x  2 root  wheel     3B 19 Dec 04:12 webkit-gtk2
# ls -hl /usr/local/lib/browser_plugins/symlinks/gecko
total 1
lrwxr-xr-x  1 root  wheel    31B 15 Dec 05:18 IcedTeaPlugin.so -> /usr/local/lib/IcedTeaPlugin.so
# 
```

**Comment by ijurisic** [comment]
> With FreeBSD I see /usr/local/lib/browser_plugins/ (with e.g. contents as shown below); I have no idea what the equivalent might be on Linux.

On Debian 9.3 GNU/Linux have symbolic link at /usr/lib/mozilla/plugins/

ls -hl /usr/lib/mozilla/plugins/ 

lrwxrwxrwx 1 root root 39 Dec 23 01:35 libjavaplugin.so -> /etc/alternatives/mozilla-javaplugin.so

ls -hl /etc/alternatives/mozilla-javaplugin.so
 
lrwxrwxrwx 1 root root 61 Dec 23 01:35 /etc/alternatives/mozilla-javaplugin.so -> /usr/lib/jvm/oracle-java8-jdk-amd64/jre/lib/amd64/libnpjp2.so

**Comment by PhantomX** [comment]
`~/.waterfox/extensions/` is not working too.
