### ISSUE TITLE
Extension UnMHT doesn't work (not context menu)

### ISSUE THREAD

**Issue by wiesl** [BrowserWorks/waterfox#328]
Waterfox: 56.0.1
UnMHT: 8.3.2

Save as MHT not show in context menu, works e.g. well in Basilisk.

**Comment by Rikk** [comment]
Perhaps are you using Multiprocess? UnMHT doesn't work with Multiprocess (aka e10s/Electrolysis) enabled.

**Comment by wiesl** [comment]
# Yes, that's the reason. Thnx. Loading MHTs works also again.
https://wiki.mozilla.org/Electrolysis
https://www.ghacks.net/2016/07/22/multi-process-firefox/
browser.tabs.remote.autostart
browser.tabs.remote.autostart.2
https://arewee10syet.com/
https://support.mozilla.org/en-US/questions/1062853
about:support
Multiprocess Windows 	40/40 (Enabled by user)

# set from true to false
browser.tabs.remote.autostart
browser.tabs.remote.autostart.2
about:support
Multiprocess Windows 	0/40 (Disabled)

**Comment by Rikk** [comment]
Btw, Waterfox has a handsome option for disabling/enabling it:

![e10s-option](https://user-images.githubusercontent.com/2916485/34324756-93068fd2-e864-11e7-85e3-3a2050953600.png)
