### ISSUE TITLE
Portable (Windows) - Extensions Break On Path Change (addonStartup.json.lz4 Problem)

### ISSUE THREAD

**Issue by ForkedLightning** [BrowserWorks/waterfox#329]
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.1 Waterfox/56.0.1

Problem:
On Waterfox Portable in Windows, changing the path will cause extensions to break (tested with Classic Theme Restorer and Greasemonkey) .

Solution:
1) The problem lies with addonStartup.json.lz4 that specifies the full path (not relative!) to the extension. Manually changing the path contained in it will allow it to start as normal, but not done easily due to proprietary MozLz4 format. (See Issue #330 . The WaterfoxPortable.exe NSIS script can change this if it was plain text.)

2) Changing the paths in extensions.json will only take effect after Waterfox is started twice. First start will be "broken" because of invalid path in addonStartup.json.lz4 (some addon settings like toolbar placement in CTR will be lost), but it will generate a newaddonStartup.json.lz4 for the next run.

**Comment by crazy-max** [comment]
@ForkedLightning I have [fixed](https://github.com/portapps/waterfox-portable/commit/8d042b20bed670144339940553f3c90dbfb8f05c) this using Portapps if you want to [take a look](https://portapps.io/app/waterfox-portable/).

**Comment by grahamperrin** [comment]
Cross reference: 

- [Problem migrating a profile to a newer browser version : waterfox](https://www.reddit.com/r/waterfox/comments/d09ydr/problem_migrating_a_profile_to_a_newer_browser/)

**Comment by grahamperrin** [comment]
Maybe related: 

- Mozilla bug [1429838 - After restoring profile to a different location, paths in extensions.json are incorrect](https://bugzilla.mozilla.org/show_bug.cgi?id=1429838)
