### ISSUE TITLE
Speed benchmarks

### ISSUE THREAD

**Issue by compscied** [BrowserWorks/waterfox#33]
I have installed the WF and so far have not see the difference between it and Firefox and PaleMoon in terms of speed - do you have any benchmarks you could share around speed claims?  Thanks

**Comment by leelaylay** [comment]
��������������������������

**Comment by MrAlex94** [comment]
I used to have them on the website but I just felt like if they were on there people would think they were biased. A user had some benchmarks a few versions back: https://www.reddit.com/r/waterfox/comments/2xle7k/browser_benchmark_of_google_chrome_canary/

**Comment by DaAwesomeP** [comment]
You really start to tell when you have 20 to 40 tabs open. In my experience, it doesn't miss a beat when in comes to adding or multiplying loads.The actual speed of particular things is not as noticeable, but it scales up very well. Firefox would normally crashes when trying to play 5 videos or have 20 tabs open. I also have 20+ extensions running. This is just my experience. I also think that it runs better than the 64-bit version of Developer Edition. the Dev Edition, even in 64-bit still has problems with large tasks.
