### ISSUE TITLE
Stylo – layout.css.servo.enabled – in Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#332]
From <https://www.reddit.com/r/waterfox/comments/7jndj6/waterfox_5601_is_now_available_for_download_with/dr8fppp/>: 

>>>> … no Stylo? …

>>> about:config
>>> 
>>> `layout.css.servo.enabled`
>>> `true`
>>> 
>>> Result:
>>>> Stylo true (enabled by user)

>> … about:support says "false (disabled by build)". …

> … I guess that it's not disabled, in that way, with the (experimental) port to FreeBSD, … 

## tl;dr 

It seems that for (at least) Windows, Stylo is disabled at build time for Waterfox 56.0.1. 

----

https://github.com/MrAlex94/Waterfox/issues/298#issuecomment-349742544 draws attention to Mozilla bug [1341234 - bindgen doesn't pass CFLAGS for optional system dependencies](https://bugzilla.mozilla.org/show_bug.cgi?id=1341234)

For what it's worth: with Stylo enabled in 56.0.1 on FreeBSD-CURRENT, I have not encountered any problem that I might attribute to the feature.

**Comment by Serkan-devel** [comment]
I can't find `layout.css.servo.enabled` on Waterfox 56.0.1 Debian 9 at all

**Comment by grahamperrin** [comment]
You can add it, as a boolean. 

----

For reference only, some things that I bookmarked a few weeks ago. Not intended to be comprehensive: 

- [Quantum/Stylo - MozillaWiki](https://wiki.mozilla.org/Quantum/Stylo)
- [PSA: You can try out Stylo in Firefox Nightly now! : firefox](https://www.reddit.com/r/firefox/comments/6p9t83/psa_you_can_try_out_stylo_in_firefox_nightly_now/) (2017-07-24)
- [Inside a super fast CSS engine: Quantum CSS (aka Stylo) – Mozilla Hacks – the Web developer blog](https://hacks.mozilla.org/2017/08/inside-a-super-fast-css-engine-quantum-css-aka-stylo/) (2017-08-22)
- in Bugzilla@Mozilla, [_CSS Parsing and Computation_ bugs for _56 Branch_](https://bugzilla.mozilla.org/buglist.cgi?resolution=---&classification=Components&query_format=advanced&version=56%20Branch&component=CSS%20Parsing%20and%20Computation&product=Core&list_id=13944813)

**Comment by grahamperrin** [comment]
Cross reference: [Why is stylo disabled ? : waterfox](https://www.reddit.com/r/waterfox/comments/7m8p86/why_is_stylo_disabled/)

**Comment by Serkan-devel** [comment]
I've added it as boolean and it's still disabled (due to build)

**Comment by grahamperrin** [comment]
OK, I guess that Mozilla bug 1341234 makes it difficult to build Waterfox with Stylo on Linux.

**Comment by jbeich** [comment]
Stylo from FF56 has many security issues fixed in FF57 (via [fuzzing](https://bugzilla.mozilla.org/show_bug.cgi?id=1333171)). MFSA 2017-24 only documented those that also affect non-Stylo code. During FF58-FF60 both non-Stylo (Android, ESR52 for critical) and Stylo would receive attention but after FF60 only Stylo.

**Comment by grahamperrin** [comment]
<https://www.reddit.com/r/waterfox/comments/81y78m/-/dv9jizp/>: 

> (support is) planned for the next release 🙂

👍 cool

**Comment by Serkan-devel** [comment]
But when will the next release happen

**Comment by grahamperrin** [comment]
@Serkan-devel please join the discussion under [Waterfox's current status : waterfox](https://www.reddit.com/r/waterfox/comments/818z1k/waterfoxs_current_status/)

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/commit/01a5bc42160483c24610065c75260d5513dd4161 noted with thanks.

**Comment by grahamperrin** [comment]
With Waterfox 56.1.0, Stylo is [enabled and built on all desktop platforms](https://blog.waterfoxproject.org/waterfox-56.1.0-release-download).

Two points: 

- extension incompatibilities, such as the one at <https://github.com/MrAlex94/Waterfox/issues/332#ref-issue-284962197> above, should be rare
- #498 (Waterfox, or a tab, crashing at <https://bintray.com/>) is probably an edge case.

I reckon that we can close this issue 332. 

----

## Looking ahead, beyond desktop platforms

Mozilla bug [1366049 - (stylo-android) enable Stylo for Android](https://bugzilla.mozilla.org/show_bug.cgi?id=1366049) was

> RESOLVED FIXED in Firefox 59

– and from Quantum-related <https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-376351366>: 

> … While still under research, I plan to plant base in 60 ESR for a "future" variant of the browser. …

**Comment by grahamperrin** [comment]
Without reopening this issue (unless you'd like to, @MrAlex94): 

----

> … extension incompatibilities… should be rare

Re: #512 (fixed in the port to FreeBSD) _Speed Start_ might be added to the shortlist. 

----

> … Waterfox, or a tab, crashing at … is probably an edge case.

#516 is another case. 

----

From pull request <https://github.com/MrAlex94/Waterfox/pull/511>, merged a few minutes ago: 

> Stylo from Firefox 56 is affected by many Web compatibility and security issues. It also crashes and degrades performance in some situations. 

At https://www.reddit.com/r/waterfox/comments/7bj77g/-/dx12nol/ I have a shortlist of known cases/situations where users of Waterfox 56.1.0 have been affected. Just a shortlist; not intended to be comprehensive. Plus https://disqus.com/home/discussion/waterfox/the_waterfox_blog_waterfox_5610_release/#comment-3846181598 the question about why the feature was added/enabled; and so on. 

----

Sorry for not testing more thoroughly!

G
