### ISSUE TITLE
Waterfox resizes itself on opening

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#333]
I used the workaround mentioned in [this thread](https://github.com/Aris-t2/ClassicThemeRestorer/issues/383#issuecomment-353865019) to fix the problem of not being able to add separators between buttons on the toolbar. Here's a pix of what they look like in customize mode:

![spaces](https://user-images.githubusercontent.com/33827636/34342337-73660bf4-e9ad-11e7-8407-4335e198c169.PNG)

However, Waterfox now resizes itself on opening and looks like you see it in the image. I don't know whether the spaces are the cause of it though. 

![reduced_size](https://user-images.githubusercontent.com/33827636/34342342-ab9f1ca4-e9ad-11e7-8c26-26f2412fd6c7.png)

My system is Windows 8.1 patched using security only updates every month rather than the rollups containing telemetry and other Microsoft bloatware just in case that's relevant.

**Comment by Telmesomething** [comment]
I've found the reason why Waterfox was resizing itself as shown in the screenshot above. It has nothing to do with the separators, but rather a config setting namely this one: `privacy.resistFingerprinting`
When set to _true_ in about config, Waterfox resizes itself on opening. 

Resetting it to its default value allows Waterfox to open normally. 

The config setting itself is the second one down in the "Getting Started" recommendations on [this site](https://www.privacytools.io/#about_config)

**Comment by grahamperrin** [comment]
From [the accepted answer](https://tor.stackexchange.com/a/15715) to _fingerprinting - Why does Tor Browser screen size vary across monitors? - Tor Stack Exchange_: 

> … privacy.resistFingerprinting to true to use the client content window size … In addition, we prevent auto-maximizing on browser start, and inform users that maximized windows are detrimental to privacy in this mode. 

Mozilla bug [418986 - window.screen and CSS media queries provide a large amount of identifiable information (Tor 2875)](https://bugzilla.mozilla.org/show_bug.cgi?id=418986) was: 

>  RESOLVED FIXED in Firefox 41

– and modified earlier this year.
