### ISSUE TITLE
Discord doesn't accepts user agent string

### ISSUE THREAD

**Issue by bn4t** [BrowserWorks/waterfox#334]
It looks like Discord doesn't detects Waterfox as Firefox and lets you therefore not interact with the voice chat. 
Maybe it would be possible to adapt the user agent string so Waterfox appears like Firefox. (Just with less metadata in it)

**Comment by grahamperrin** [comment]
This is probably a duplicate of [User-Agent: Waterfox · Issue #178 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/178)

**Comment by bn4t** [comment]
Yeah, you're right. Didn't saw it. 
Gonna close this now.
