### ISSUE TITLE
Tabs animations aren't disable

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#338]
```
## In the past, it was related to :
pref("browser.tabs.animate",false);
## Several months ago it was replaced by this one :
pref("toolkit.cosmeticAnimations.enabled",false);
```
Hello,

apparently Waterfox_v56.0.1 doesn't recognize it. It's a bug ? Because it seem's to work fine with Firefox.
Unless it was rename again ? Or it wasn't replaced for Waterfox ?

Kind regards.

**Comment by hook321** [comment]
Just tested it, setting toolkit.cosmeticAnimations.enabled to false in about:config disabled tab animations for me. What OS are you using?

**Comment by WagnerGMD** [comment]
It's W10 (but I will complete later if you need).
What about the profil ? I had try yesterday (remove it) but it didn't help. Did I miss something ?

**Comment by MrAlex94** [comment]
Works for myself as well.
