### ISSUE TITLE
Permanent Window audio changes MEANS Windows 10 Insider Build 17063 breaks audio in Waterfox-56??

### ISSUE THREAD

**Issue by tweed** [BrowserWorks/waterfox#339]
My audio hasn't worked for days - have discovered much, hoping for fix in 56.02
Does anyone know if there's a work-around?

https://www.google.com/search?q=waterfox+audio+breaks+with+insider&ie=utf-8&oe=utf-8

SO happy to have found waterfox

NOTE: Microsoft has changed audio,  so this break is less of a bug and more of a permanent alteration of windows handling of audio.
https://www.reddit.com/r/Windows10/comments/7kzt7s/psa_if_you_use_firefox_dont_upgrade_to_17063_it/

You don't know what you've got 'till it's gone - currently that's ALL AUDIO :-)
ISSUE being, no audio with windows 10 insider preview
a big deal as so many of us are bleeding edge with windows 10 and use the insider previews

"WIndows 10 Insider Build 17063 breaks audio in Firefox"
"PSA: If you use Firefox, don't upgrade to 17063 (It breaks sound "
"Latest windows insider build broke audio in firefox? : firefox ..."

**Comment by grahamperrin** [comment]
Commentary under [Windows 10 Build 17063 killed sound to sites : waterfox](https://www.reddit.com/r/waterfox/comments/7l5msf/windows_10_build_17063_killed_sound_to_sites/) refers to: 

- Mozilla bug [1426719 - Latest insider build of Windows 10 (17063) breaks sound playback completely](https://bugzilla.mozilla.org/show_bug.cgi?id=1426719)

>  VERIFIED FIXED in Firefox 58 (Needinfo from 2 people)

**Comment by tweed** [comment]
THANKS !   
helpful --
So, fixed in Firefox latest version though not in Waterfox 56 (or earlier Firefox) i guess because of the changes in windows 10 that are permanent.

Looking for work-around and/or happily waiting for Waterfox fix update i guess.

Anyone got their sound back if using latest Windows 10 insider preview?

Appreciated, whatever happens!

**Comment by Squall-Leonhart** [comment]
There is no bug here requiring fixing, Microsoft have resolved the issue in 17073 - It was present in Edge too.

The  code change pushed to 58 was a workaround.
