### ISSUE TITLE
URL bar issues

### ISSUE THREAD

**Issue by colcrunch** [BrowserWorks/waterfox#34]
When I go to open a new tab and then start typing, after a small amount of time, what has been typed is becomes automatically highlighted. This often catches me out when I for example hit Ctrl+T then start typing facebook. I know that if I type face then hit enter it will autocomplete and take me to facebook... but because of this I will get "fac" typed, which will then be highlighted and when I hit "e" then the enter key I get my email page, cause the browser is autocompleting from "e".

**Comment by DaAwesomeP** [comment]
Your control key might be stuck or something. Ctrl + E selects the URL bar, but that's still weird. I don't mean to be cliché, but see if the same thing happens in safe mode (Menu > Question Mark > Restart with Add-ons Disabled).

**Comment by colcrunch** [comment]
The example was arbitrary and meant only to prove a point (i.e the time it takes for the contents of the url bar to be auto-selected), this happens with anything I type.

**Comment by MrAlex94** [comment]
Do you still have this issue?

**Comment by colcrunch** [comment]
No, I have not had this issue for some time.
