### ISSUE TITLE
tabs: cease showing the ' - e10s' suffix on point/hover

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#340]
## Enhancement request

Either: 

- don't apply a suffix

– or: 

- use **plain English** (or localised) e.g. _multi-process_ instead of _e10s_.

I vote to not apply a suffix. I see it as unnecessary clutter. 

It might have been of interest to technophiles during heavy development of multi-process, but nowadays I doubt that an 'average' user will find it of value. 

## Example

In the window at top right: 

![2017-12-30 10 24 15](https://user-images.githubusercontent.com/192271/34453494-a2cfea8c-ed4e-11e7-84e3-08b425fe1ead.png)

– the title of 

> [Waterfox 56 Release](https://www.waterfoxproject.org/blog/waterfox-56.0-release-download) 

– is presented as: 

> Waterfox 56 Release - e10s

## Related

Mozilla bug [1261480 - Remove the '- e10s' tab title annotation](https://bugzilla.mozilla.org/show_bug.cgi?id=1261480)

>  RESOLVED WONTFIX 

Mozilla bug [1175499 - string [e10s] added to the title in all tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1175499)

> RESOLVED INVALID

**Comment by grahamperrin** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1261480#c3>: 

> As of Firefox 58 and bug 1410279, this info is only displayed in Nightly.

**Comment by MrAlex94** [comment]
I suppose it may be worth removing from the title bar. I thought it was nice to keep it just to let users know that they have e10s enabled, but as Waterfox becomes more accessible I suppose that isn't necessary.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/0e188cd34f1372f1c602cf6aaaa2f2dfb71b366c
