### ISSUE TITLE
Crash on trusted webvideo

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#342]
When i click start the trusted web-video (WebID Solutions GmbH - https://webid-gateway.de/service/qa/cn/000239/aid/461678705) crashes Waterfox 56.0.1!

**Comment by Serkan-devel** [comment]
This link seems broken and didn't crash Waterfox 56 on my end

**Comment by grahamperrin** [comment]
From a translation of the page: 

> The ProcessID has expired. …

@DanicaTalos please, can you share troubleshooting information? Visit: 

about:support

**Comment by criztovyl** [comment]
Output from Browser Console meight also be interesting (`CTRL+SHIFT+J` or Hamburger menu &rarr; Developer &rarr; Browser Console).

**Comment by grahamperrin** [comment]
Review time. Is this still an issue?
