### ISSUE TITLE
Google Play Store App 'Waterfox Browser & Search' with AppID 'com.waterfox.waterfox'

### ISSUE THREAD

**Issue by jdunn0** [BrowserWorks/waterfox#344]
As noted in [this reddit post](https://www.reddit.com/r/waterfox/comments/7ivlsh/waterfox_android_app/), there is an app on the Google Play Store called [Waterfox Browser & Search](https://play.google.com/store/apps/details?id=com.waterfox.waterfox) with an AppID that doesn't match the AppID of the Android version available on the Waterfox web site.
There are a couple theories on what it is:
1. A scam app designed to look like Waterfox.
2. An old version of Waterfox put on the store a while ago that has been forgotten about.

Either way, it would be probably be best if that app was removed if possible and a current app version be uploaded.

**Comment by criztovyl** [comment]
See https://github.com/MrAlex94/Waterfox/issues/251#issuecomment-340434173 :)

**Comment by jdunn0** [comment]
@criztovyl: Thanks for the link. I guess I forgot to search the existing issues before opening this one.
It sucks that Alex can't get Google to remove the app.
It seems like businesses going bust is a situation that the Google Play Store should have a way to deal with as that happens sometimes.
I'll close this now.
