### ISSUE TITLE
Zoom-in and Zoom-out mouse cursors don't display

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#347]
Xubuntu 16.04 64-bit
Waterfox 56.0.1
new profile

**Steps to reproduce:**

1) visit an image that's larger than the Waterfox window, such as https://i.imgur.com/562G3UQ.png

2) mouse over the image

3) click to zoom in, and keep mouse over the image

**Expected results:** get a zoom-in mouse cursor at (2), and a zoom-out mouse cursor at (3)

**Actual results:** Mouse cursor doesn't change.  It's default arrow the whole time.  Using the devtools Inspector shows that `cursor: zoom-in` and `cursor: zoom-out` CSS rules are set and active.

This can also be seen in the live examples at https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

Firefox 56.0.2 has this issue as well.  Looks like it was caused by some change from Firefox between Firefox 54 and 55.

**Comment by Squall-Leonhart** [comment]
Not applicable to Windows

**Comment by grahamperrin** [comment]
> … such as <https://i.imgur.com/562G3UQ.png> …

If it helps to refine this issue: I can reproduce the issue at the URL above, but not at <https://user-images.githubusercontent.com/192271/36513849-91e9318e-1769-11e8-83b0-c955b0dae008.png>.

**Comment by grahamperrin** [comment]
## Side note

When zoomed in – particularly where an image is wider than the window – my instinct is to then drag by default <strike>(gloved hand pointer?)</strike> – _hand_ and _closed hand_ pointers. Simply because a horizontal scroll bar feels less ergonomic than the vertical bar. 

I was surprised to find – in both Firefox Quantum and Waterfox – zoom out as the default pointer after zooming in. Discussion: [Missing Add Ons: Please Bring Back, MouseZoom, Grab And Drag, And FaviconizeTabs : firefox](https://www.reddit.com/r/firefox/comments/7d97jq/missing_add_ons_please_bring_back_mousezoom_grab/) …

**Comment by laniakea64** [comment]
> not at https://user-images.githubusercontent.com/192271/36513849-91e9318e-1769-11e8-83b0-c955b0dae008.png.

I'm not seeing what you're seeing.  I _do_ get the issue at that URL.

@grahamperrin 
What OS/version are you on?
What GTK version?

**Comment by grahamperrin** [comment]
Maybe I was mistaken earlier, 

> … I can reproduce the issue at the URL above, …

– now, there's no problem for me: 

![2018-02-22 10 51 00](https://user-images.githubusercontent.com/192271/36534751-582a565c-17bf-11e8-91ad-fe3146ca5fc9.png)

![2018-02-22 10 51 29](https://user-images.githubusercontent.com/192271/36534757-5cbb18f0-17bf-11e8-8aa6-3c72b2c1d71e.png)

## Environment

Waterfox 56.0.4_4 on FreeBSD-CURRENT, https://www.freshports.org/www/waterfox

### about:support

[2018-02-22 10:56 about:support.txt](https://github.com/MrAlex94/Waterfox/files/1747587/2018-02-22.10.56.about.support.txt)

### about:buildconfig

Compiler 
`/usr/bin/cc -std=gnu99`

Version 
`4.0.0`

Compiler flags 
`-Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers  -Wpointer-arith -Wsign-compare -Wtype-limits -Wunreachable-code  -Wclass-varargs -Wloop-analysis -Wstring-conversion  -Wno-error=deprecated-declarations -Wno-error=array-bounds -Wformat  -Wno-gnu-zero-variadic-macro-arguments -Wformat-security -O2 -pipe -O3  -DLIBICONV_PLUG -fstack-protector -isystem /usr/local/include  -fno-strict-aliasing -fno-strict-aliasing -ffunction-sections  -fdata-sections -fno-math-errno -pipe -I/usr/local/include`

Compiler 
`/usr/bin/c++ -std=gnu++11`

Version 
`4.0.0`

Compiler flags 
`-Qunused-arguments -D_GLIBCXX_USE_C99  -D_GLIBCXX_USE_C99_MATH_TR1  -D_DECLARE_C99_LDBL_MATH -DLIBICONV_PLUG  -isystem /usr/local/include   -Qunused-arguments -Wall -Wc++11-compat  -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith  -Wsign-compare -Wtype-limits -Wunreachable-code -Wwrite-strings  -Wno-invalid-offsetof -Wclass-varargs -Wloop-analysis  -Wc++11-compat-pedantic -Wc++14-compat -Wc++14-compat-pedantic  -Wc++1z-compat -Wcomma -Wimplicit-fallthrough -Wstring-conversion  -Wno-inline-new-delete -Wno-error=deprecated-declarations  -Wno-error=array-bounds -Wformat -Wno-gnu-zero-variadic-macro-arguments  -Wformat-security -Wno-unknown-warning-option -Wno-return-type-c-linkage  -O2 -pipe -O3 -DLIBICONV_PLUG -fstack-protector -isystem  /usr/local/include -fno-strict-aliasing -DLIBICONV_PLUG -isystem  /usr/local/include -fno-exceptions -fno-strict-aliasing -fno-rtti  -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno  -pipe -I/usr/local/include  -O2 -O3 -fno-omit-frame-pointer    -D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH_TR1  -D_DECLARE_C99_LDBL_MATH  -DLIBICONV_PLUG -isystem /usr/local/include`

Configure options 
`CONFIG_SHELL=/bin/sh --enable-application=browser --enable-update-channel=release --disable-tests PKG_CONFIG=pkgconf CC=cc CXX=c++ 'BINDGEN_CFLAGS=-isystem/usr/local/include/nspr -isystem/usr/local/include/pixman-1' --disable-debug-symbols --enable-release --enable-jack --enable-profiling --enable-system-ffi --enable-default-toolkit=cairo-gtk3 --with-system-graphite2 --with-system-harfbuzz LLVM_CONFIG=llvm-config50 --enable-rust-simd PERL=/usr/local/bin/perl MAKE=gmake --enable-system-hunspell --enable-alsa --enable-dtrace --enable-extensions=default --enable-gconf --disable-install-strip --disable-libproxy --enable-optimize --enable-pie --enable-pulseaudio --enable-startup-notification --disable-strip --enable-system-pixman --enable-system-sqlite --disable-updater --prefix=/usr/local --with-app-basename=Waterfox --with-app-name=waterfox --with-distribution-id=org.waterfoxproject --with-intl-api --with-pthreads --with-system-bz2 --with-system-icu --with-system-jpeg=/usr/local --with-system-libevent --with-system-libvpx --with-system-nspr --with-system-nss --with-system-ogg --with-system-png=/usr/local --with-system-vorbis --with-system-zlib`

**Comment by laniakea64** [comment]
Thanks.

FreeBSD has [GTK3 version 3.22.15](https://www.freshports.org/x11-toolkits/gtk30/).  Xubuntu 16.04 has [GTK3 version 3.18.9](https://packages.ubuntu.com/xenial-updates/libgtk-3-0).

To check whether it's a GTK3 version thing, I tried with Xubuntu 18.04 pre-release in a VM ([GTK3 version 3.22.28](https://packages.ubuntu.com/bionic/libgtk-3-0)).  Same issue there.

------

In case it helps, I went through Firefox nightlies to get some sense of where this bug was introduced.

Working nightly: 20170308110300/`https://hg.mozilla.org/mozilla-central/rev/58753259bfeb3b818eac7870871b0aae1f8de64a`
Broken nightly: 20170309110215/`https://hg.mozilla.org/mozilla-central/rev/c40ca7a1bdd93632c6bdc5e23bd33d984d508b19`

**Comment by jbeich** [comment]
From dac8dc0c7bfdf...e820f4aba97fd range the culprit is probably be283046034a. See [Mozilla bug 1428755](https://bugzilla.mozilla.org/show_bug.cgi?id=1428755).

**Comment by grahamperrin** [comment]
@jbeich thanks, I'm curious, is there a simple-ish explanation for the issue not present in my case? 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info gtk30
pkg: No package(s) matching gtk30
```

Plasma 5 from Area 51, Adwaita cursor theme preferred in the _GNOME Application Style (GTK)_ area of System Settings, MATE cursor theme preferred in the _Workspace Theme_ area. 

## Postscript, 2018-04-23

Found (`gtk3` (not `gtk30`) with origin `x11-toolkits/gtk30 `): 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info gtk3
gtk3-3.22.29
Name           : gtk3
Version        : 3.22.29
Installed on   : Sat Mar 31 20:07:51 2018 BST                                                                                                 
Origin         : x11-toolkits/gtk30   
…
```

**Comment by laniakea64** [comment]
@jbeich Nice find!  I did a custom Waterfox build with https://github.com/MrAlex94/Waterfox/commit/be283046034a620d11c36764048e6d3b4b8f21d4 reverted, and zoom-in and zoom-out cursors are back!

**Comment by laniakea64** [comment]
Hi @MrAlex94 , do you need more information on this?

I've been reverting https://github.com/MrAlex94/Waterfox/commit/be283046034a620d11c36764048e6d3b4b8f21d4 for my daily-use Waterfox builds ever since it was pointed out, and it hasn't caused any problems.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/d5c25411b0838a4578f8a96aa2e09568d900e9b6

**Comment by laniakea64** [comment]
Hi @MrAlex94 this issue has returned in Waterfox 68.
