### ISSUE TITLE
about:addons ☑ Exclude from updates (Updates: … 🔘 never)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#349]
## Example use case

Two extensions that I want to not update: 

![2018-01-01 16 17 06](https://user-images.githubusercontent.com/192271/34469101-5d0d02a6-ef0f-11e7-9ce2-4702d7aa4998.png)

It's necessary to both: 

1. disable automatic updates **and**
2. in the _Install updates_ area, **repeatedly** deselect add-ons (e.g. de-select before **any** click on the _Install Updates_ button. 

## Enhancement request

End the repetition by adding a feature to Waterfox, 

☑ Exclude from updates

– selectable for any add-on.

**Comment by WagnerGMD** [comment]
```
lockPref("extensions.update.autoUpdateDefault",false);
lockPref("extensions.update.enabled",false);
```
Are you aware or you didn't find them ? It isn't good enough ?

Then to avoid the repetition, you can disable it in the meanwhile (until next Waterfox release). But you can't select the addon (because it will be disable at global).

**Comment by grahamperrin** [comment]
Thanks, 

> … disable at global).

– global is not what's required. 

----

From <https://blog.mozilla.org/addons/how-to-turn-off-add-on-updates/#comment-210512> under _How to turn off add-on updates | Mozilla Add-ons Blog_: 

> … a per-extension setting. In other words, I should be able to disable updates for a specific extension. … 

– that's what's required.

**Comment by MrAlex94** [comment]
Does the functionality of this page not fulfill your request of disable updates per add-on? Or is more that you'd like it to be available on the page you have specified?

<img width="1440" alt="screen shot 2018-01-03 at 18 39 08" src="https://user-images.githubusercontent.com/4728920/34534264-6face712-f0b5-11e7-9f84-d621cb741e7a.png">

**Comment by grahamperrin** [comment]
If automatic updates are switched off at that level, it does not prevent an update from appearing, and being selected, in response to a manual check. 

That type of page _might_ be the best place for an enhancement. (There, without 'cramming' the feature into any list of updates.)

I wonder whether `☑ Exclude from updates` will be difficult for users to understand – if offered as a separate preference. 

Instead, maybe something like this:  

----
**Updates**`    ◯ default    ◯ automatic    ◯ manual    🔘 never`

----

– four radio buttons, instead of three. 

Then: a preference for `🔘 never` followed by any type of check for updates can lead to the update being listed **but not selected** (its box not checked).

**Comment by grahamperrin** [comment]
Cross reference: [I'd like a way to exclude addons from manual "update all" : waterfox](https://redd.it/7v8m3i)

**Comment by grahamperrin** [comment]
These recent screenshots might help to clarify the use case.

----

A simple manual check: 

![2018-02-10 12 24 33](https://user-images.githubusercontent.com/192271/36358289-2fd01ba0-1504-11e8-9fc2-b6227a670738.png)

👍 

I would like that to be followed by another simple, single action. 

Instead I **must not** accept the default selection (everything); I **must not** click this button: 

![2018-02-10 12 26 07](https://user-images.githubusercontent.com/192271/36358292-3c3aff0e-1504-11e8-9d9c-b67ca16692aa.png)

The restraint above is followed by five more clicks, to de-select each add-on that must not be updated: 

![2018-02-10 12 28 32](https://user-images.githubusercontent.com/192271/36358294-408332d4-1504-11e8-8a0c-7e116ad834b2.png)

Now, it's safe to click _Install updates_. 

After the click, after completion of installations: 

![2018-02-10 12 29 09](https://user-images.githubusercontent.com/192271/36358296-441efc20-1504-11e8-8012-93d61f7591c4.png)

Side note: the tip 'Install available updates in this list' is wrong. The browser installed a subset (not what was _available_); and the tip should not appear when the button is greyed out. 

----

After clicking away from, then back to, _Available updates_: 

- again, the browser preselects everything that must not be updated: 

![2018-02-10 12 30 03](https://user-images.githubusercontent.com/192271/36358299-47ee236c-1504-11e8-9a2f-19303e28a5dd.png)

👎

**Comment by grahamperrin** [comment]
Found, thanks to [--NRG--](https://www.reddit.com/user/--NRG--) in Reddit: 

## Add-on Update Checker

From [Add-ons manager ▶ Available updates ▶ viewing version numbers – and avoiding unwanted updates : waterfox](https://www.reddit.com/r/waterfox/comments/8k0hq3/addons_manager_available_updates_viewing_version/):

![image](https://user-images.githubusercontent.com/192271/39648474-3c99aafc-4fda-11e8-93d5-c09d455851e0.png)

**Comment by grahamperrin** [comment]
Add-on Update Checker is effective, so I'll close this issue. 

A screen recording: https://photos.app.goo.gl/SjZfxo7R34gP7iWP8

**Comment by Captain-FLAM** [comment]
@grahamperrin :+1: 

Please Re-open it, as I think this option is a "must have" included in Waterfox !!

Especially this one :

> a preference for `🔘 never`
