### ISSUE TITLE
Wrong Addon Popup Size

### ISSUE THREAD

**Issue by criztovyl** [BrowserWorks/waterfox#351]
e.g. uMatrix, uBlock is also affected.

55.2.2 :+1::
![bildschirmfoto vom 2018-01-02 21-51-09](https://user-images.githubusercontent.com/2174918/34499725-a401e26e-f007-11e7-80ca-4d3b91600ec0.png)
56.0.1 (56.0 too) :-1::
![bildschirmfoto vom 2018-01-02 21-52-54](https://user-images.githubusercontent.com/2174918/34499724-a3e0ac2a-f007-11e7-94c7-8af5a5f14a14.png)

uMatrix 1.0.0
Debian Stretch (9.3)

**Comment by grahamperrin** [comment]
<https://www.reddit.com/r/waterfox/comments/7m1x01/the_umatrix_popup_is_too_small/drqx9r1/>: 

> You're using an outdated version of uMatrix. 1.1.20 works fine.
