### ISSUE TITLE
On Windows: whilst Firefox runs, the installer for Waterfox 56.0.1 can not finish with a launch of Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#353]
Spun off from https://redd.it/7l57vj

## Steps

1. either before or after starting installation of Waterfox
2. start Firefox
3. when installation is complete, accept the default prompt to start Waterfox
4. click 'Finish'

## Expected

- launch of Waterfox

## Actual results

- a false statement that Waterfox is already running; **and**
- no launch

## Workarounds

- exit Firefox
- again, click 'Finish'.

Other workarounds exist. 

## Environment

The issue seems to be consistently reproducible with (old) Firefox ESR 31.2.0. I encountered it at least twice before Christmas, twice again today. 

## Guesses

Without looking at code, I guess that the installer determines whether a lock file is active at a Mozilla path. 

The installer should _also_ determine whether a lock file is active at the Waterfox path. 

Assuming that the user's first run of Waterfox will involve an attempt to import from Firefox, there may be value in ensuring that Firefox does not run during the import. In this case the installer might present a warning along the lines of: 

> Please exit Firefox before your first run of Waterfox.

**Comment by jdunn0** [comment]
I fixed this issue 4 days ago in pull request #367.
I just found this issue though so I can't close this issue as it wasn't originally linked to the pull request.
