### ISSUE TITLE
all builds here on github in releases section

### ISSUE THREAD

**Issue by D0ve** [BrowserWorks/waterfox#354]
Please, put all Waterfox builds and test builds here on github , in releases section!
Many thanks in advance!

**Comment by MrAlex94** [comment]
I am planning to, it's in the release checklist :-)

**Comment by D0ve** [comment]
Thank you!  Hope to see here new rc and android builds!

**Comment by D0ve** [comment]
android and other os builds are still not in 'releases' (((

**Comment by D0ve** [comment]
BTW, an android version here, in 'releases' section, could be signed with sign without a password!
So that could be possible to update by just reinstalling!

**Comment by D0ve** [comment]
PS
Alex, please , fornow place direct link from waterfoxproject.org to an android build !
Or make ftp.waterfoxproject.org access for easier downloading the builds!
Many people hate G.PlayStore ;)

**Comment by grahamperrin** [comment]
> direct link from waterfoxproject.org to an android build 

Please subscribe to [Make standalone APK downloadable from site · Issue #521 …](https://github.com/MrAlex94/Waterfox/issues/521)

**Comment by D0ve** [comment]
PPS
Alex,
I would suggest even, - make another one repository here (on this accaunt) name it smth like 'Waterfox-binaries' , and make it especially for builds! Placing all builds in 'releases' section there!

**Comment by DI555** [comment]
@MrAlex94 , while we're waiting f-droid builds..., may be easier and quicker puting releases and test builds here on github ?
Just don't want using GP ones(.

**Comment by DI555** [comment]
@MrAlex94 , btw, i was reading somewhere else about some difficulties about building with f-droid....
Why just starting with putting builds here on github, and on f-droid sometime later?
I just don't want to use GP or it's mirrows builds, because GP always injects some blobs in theirs compilations :(((.

**Comment by DI555** [comment]
@MrAlex94 
Btw, Imo, the idea using tor code has no use, because android-tor starts to use chromium code now...
But may be you meaned forgotten orfox in terms of 'tor browser' ?

**Comment by tcreek** [comment]
I see the builds are still not in the releases, Only the source code is there. Maybe this needs to be reopened?

In the meantime, any guidance on building the apk? I just tried the Android IDE, and it is spewing errors about Gradle, and other issues. So using the Android SDK is clearly not the correct way.
