### ISSUE TITLE
Waterfox Focus Android version please!

### ISSUE THREAD

**Issue by D0ve** [BrowserWorks/waterfox#355]
Please add a Waterfox Focus version of Firefox Focus !
It's quite good browser for Android, but with injected telemetry, analytics and spy code is no wellcome for wise people!!! (((

**Comment by Serkan-devel** [comment]
I don't think Mozilla will add spyware to Firefox Focus, given that it's open source and <a href="https://f-droid.org/packages/org.mozilla.klar/">on the f-droid store</a> and doesn't have any <a href="https://f-droid.org/wiki/page/AntiFeatures">anti-features</a> noted.

**Comment by Mikaela** [comment]
I think what you want is [Firefox Klar from F-Droid.](https://f-droid.org/packages/org.mozilla.klar/)

> Firefox Klar is a version of Firefox Focus for Germany, Austria and Switzerland with user activity tracking disabled by default.

I was originally misled by that description and name and thinking that it would only support German as language, but it does work in English and I think all other languages that Firefox Focus supports.
