### ISSUE TITLE
javascript.options.shared_memory false by default

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#356]
Taking a hint from this, recently, in Firefox: 

![2018-01-04 17 49 54 add-ons manager - mozilla firefox](https://user-images.githubusercontent.com/192271/34582365-7d306e6e-f18b-11e7-88a4-525c20615b9d.png)

It may be prudent to make `javascript.options.shared_memory` `false` by default. 

[Mitigations landing for new class of timing attack | Mozilla Security Blog](https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/) (2018-01-03) – referred from https://news.ycombinator.com/item?id=16067610

**Comment by MrAlex94** [comment]
Yep, will patch and push tomorrow if the builds don’t take too long!

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/commit/8f77aec80334241d852e79f781a8d973477294bc noted with thanks.

**Comment by grahamperrin** [comment]
56.0.2 on a Mac: 

- `javascript.options.shared_memory` is `false` by default.

56.0.2 on FreeBSD-CURRENT: 

- `javascript.options.shared_memory` is `false` by default.
