### ISSUE TITLE
Plugin Check in extensions menu is non-functional

### ISSUE THREAD

**Issue by Niftator** [BrowserWorks/waterfox#357]
Every page of the addons menu has an annoying permanent nag, "check to see if your plugins are up to date", with a link to https://www.mozilla.org/en-US/plugincheck/

When clicking it, it doesn't run the plugin check, and instead tells me to install Firefox.

Expected behavior would be to either get the plugin check to work(valuable but maybe not easy or ethical) or to remove the broken nag.

**Comment by grahamperrin** [comment]
[about:addons 'Check to see if your plugins are up to date' · Issue #336 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/336)
