### ISSUE TITLE
Slack stopped working

### ISSUE THREAD

**Issue by nofishonfriday** [BrowserWorks/waterfox#3577]
### What happened?

I used to be able to click on 'You can also use Slack in your browser' to use Slack in Waterfox, but since recently when clicking on it, it just loops back to this page.
Happy to provide more details (if I can) when useful.

G6.0.20

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

**Comment by nofishonfriday** [comment]
![Image](https://github.com/user-attachments/assets/722283e4-730e-4d07-8839-7dfbb228599a)

**Comment by Rumperuu** [comment]
Slack dropped support for Firefox 117 and below on 2024-09-01 and now refuses to let users on those browsers access the app [[source](https://slack.com/intl/en-gb/help/articles/1500001836081-Slack-support-life-cycle-for-operating-systems-app-versions-and-browsers#browser-support-life-cycle#h_01H9637G8DSY2BT77MSQ69M88B)]. Waterfox reports the following User-Agent string for me: `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0`

You can workaround Slack's restriction by spoofing your User-Agent to show you as a supported browser (i.e., `Firefox/118.0` or above); I've had success with the [User Agent Switcher and Manager](https://webextension.org/listing/useragent-switcher.html) browser extension.

**Comment by nofishonfriday** [comment]
@Rumperuu Thanks for the heads up and workaround.
But shouldn't the User-Agent bump rather happen on Waterfox' side, or is there something speaking against it?
(I'm not deeply into this topic...)

**Comment by Rumperuu** [comment]
See #3497

**Comment by nofishonfriday** [comment]
Ah so it's in the works already, that's good to know, thanks. :)
This one can be closed then I guess.

**Comment by Rumperuu** [comment]
FYI [Waterfox 6.5.0](https://www.waterfox.net/docs/releases/6.5.0/) (released today) updates to the 128 branch, with an updated User-Agent string to match.

**Comment by nofishonfriday** [comment]
Nice, thanks for the heads up. :)

**Comment by rroose-rvo** [comment]
I'm having this issue after updating to 6.6.13.
