### ISSUE TITLE
Melltdown and Spectre Bugs

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#358]
You probably know by now... All the CPUs around the globe are affected by these security flaws, and need to be fixed.

Mozilla recently issued an update for Firefox, ver. 57.0.4 that fixed the bugs. Here is the official Mozilla Blog post about these issues: https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/

So... It's time to fix that in Waterfox too :-)

**Comment by grahamperrin** [comment]
[javascript.options.shared_memory false by default · Issue #356 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/356)
