### ISSUE TITLE
New benchmarks

### ISSUE THREAD

**Issue by DaAwesomeP** [BrowserWorks/waterfox#36]
Now that there is an official Firefox x64 for Windows, there _really_ need to be some new official benchmarks. I'm convinced, but it'd hard to convince other people why to use it.

**Comment by leelaylay** [comment]
��������������������������

**Comment by DaAwesomeP** [comment]
https://www.mozilla.org/en-US/firefox/all/

**Comment by DaAwesomeP** [comment]
It's listed at the link above and the release notes: https://www.mozilla.org/en-US/firefox/43.0/releasenotes/

**Comment by MrAlex94** [comment]
When we switch back to Clang I'll make sure to get some new benchmarks up :-)
