### ISSUE TITLE
Incpompatibility with Let's Encrypt certificate?

### ISSUE THREAD

**Issue by HTD** [BrowserWorks/waterfox#360]
Try to visit https://www.codedog.pl. I get a message "Secure connection failed". The problem doesn't occur with any Firefox version or literary any other browser except Waterfox and Pale Moon.

**Comment by grahamperrin** [comment]
No problem with https://www.codedog.pl/ in Waterfox 56.0.2 and Pale Moon 27.6.2 on FreeBSD-CURRENT. 

Can you provide details of the failure? Thanks.

**Comment by Rikk** [comment]
My Waterfox also give failure for this site.
![codedog.pl](https://user-images.githubusercontent.com/2916485/34654951-f82ffe76-f3e9-11e7-9da0-3e20647a575c.png)
My IE 11, instead, gives HTTP 500 - Internal Server Error, so I think this site may have something wrong in its configuration, also affecting HTTPS in Waterfox.

**Comment by MrAlex94** [comment]
Are you using any anti-virus software? They may whitelist connections Firefox makes by default. Check if you can add Waterfox to an exception/white list?

**Comment by Squall-Leonhart** [comment]
This is the waterfox user agent, some sites are refusing secure connection on windows unless sent a shorter string.

the initial Get request is rejected.

I just verified that changing the user agent resolves the issue.

Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.2 works
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Waterfox/56.0.2 works

Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.2 Waterfox/56.0.2 does not work.

adding a site specific overide is sometimes not sufficient as not all page resources are loaded.

**Comment by Squall-Leonhart** [comment]
still occurs in 56.0.3

**Comment by HTD** [comment]
I guess we can close that one, it's a site software issue, however none of MY code has issues with UA string. So here: it's .NET Core application served with Kestrel / Caddy combination on Ubuntu server. One of the components is responsible for HTTP 500 error on request with specific UA-s. I'll investigate it and file bug reports to the teams responsible. Of course if it's a weird bug in one of them (Caddy?). Maybe it's just a misconfiguration of some kind. Anyways, it's not a browser bug.

**Comment by SpiritQuaddicted** [comment]
This is/was a server-side problem of Caddy. It should not manifest itself with uptodate versions of Caddy (eg 0.10.11). See https://github.com/mholt/caddy/issues/2073

Please contact the website admin instead and tell them to update their Caddy.

**Comment by grahamperrin** [comment]
Review time. Is this an issue with 56.1.0? 

If so: would anyone above like to test 56.2.0 before its general release?

[Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)
