### ISSUE TITLE
Pages with popup login window crashes waterfox on Linux Mint 18.2

### ISSUE THREAD

**Issue by motivemachine** [BrowserWorks/waterfox#364]
I have a couple servers on my network that require a login username and password. Visiting that server via it's IP address (i.e. `192.168.1.321:8080`) it pops up the dialog box before the page loads. This crashes waterfox on two different PCs running Linux Mint 18.2. Firefox Quantum and Firefox 52 load everything ok. 

I tried getting some more info by launching Waterfox from the terminal, but all it prints at the crash is:
`"Segmentation fault (core dumped)"`

**Comment by MrAlex94** [comment]
Do you have any public facing websites that you can reproduce the crash on for me to test?

**Comment by motivemachine** [comment]
Unfortunately I don't, but I found a way to reproduce it with one program on localhost. One server is a raspberry pi running the Transmission-daemon with an http interface. I just installed Transmission on the linux mint machine and in Edit>Preferences>Remote check 'Allow Remote access' and 'Use Authentication'.
Then I can visit `127.0.0.1:9091` in the Firefox browser and the login prompt appears as normal. Waterfox crashes before displaying the prompt. 
I tried this on my desktop build and a Toshiba laptop both running Linux Mint 18.2, same results. 

If there's any console or debug dialog I can copy for you, let me know.

**Comment by motivemachine** [comment]
Oops, should have tried this first. I restarted Waterfox in safe-mode with add-ons disabled and the problem went away. I traced it down to an add-on called 'PassIfox', a Keepass integration add-on. It is labeled as legacy, and disabling it solved the crashes.

**Comment by grahamperrin** [comment]
PassIfox is incompatible with multiprocess. 

The first restart of Waterfox 56.0.2, after installing the incompatible extension, does not automatically switch off multi-process. 

This is Mozilla bug [1394225 - multiprocess (e10s) automatically enabled at launch after installing extensions that are not compatible with multiprocess](https://bugzilla.mozilla.org/show_bug.cgi?id=1394225).

**Comment by motivemachine** [comment]
Very good then, I'll probably just find a different add-on and quit using that one. Oddly enough it worked fine on all other website logins, just not the ones in a pop-up dialog box.

**Comment by grahamperrin** [comment]
> … a different add-on … logins, … pop-up dialog …

If you choose LastPass (as an alternative to KeePass), aim first for alpha/beta version [4.2.0.8a](https://addons.mozilla.org/addon/lastpass-password-manager/versions/beta?page=1#version-4.2.0.8a), because [4.2.1.21 is not compatible with modal authentication dialogues in Firefox 56.0.2](https://discourse.mozilla.org/t/-/19745/8?u=grahamperrin) …

----

Or simply prefer to use PassIfox, with multi-process disabled in Waterfox.

**Comment by grahamperrin** [comment]
Review time. @tailwheeldriver please, is this still an issue with 56.1.0? 

If so: would you like to test 56.2.0 before its general release?

[Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)
