### ISSUE TITLE
browser.tabs.remote.force-enable is not listed in about:config

### ISSUE THREAD

**Issue by jackfang888** [BrowserWorks/waterfox#368]
I am on Waterfox 56.0.2 on Mac OSX High Sierra and the `browser.tabs.remote.force-enable` option is not listed in `about:config`.  According to the [release notes](https://www.waterfoxproject.org/blog/waterfox-56.0-release-download) it should be.

**Comment by grahamperrin** [comment]
By default, the preference does not exist. 

If you require the preference, you can add it as a boolean.
