### ISSUE TITLE
Visual quirk in Trello card, not happening in Firefox

### ISSUE THREAD

**Issue by BrainCrumbz** [BrowserWorks/waterfox#37]
Hello there

we've found a small visual quirk when working in Trello. It does not happen in Firefox nor Google Chrome, but it happens in Waterfox so we thought it could help notifying that.
### Repro
1. Log in trello with Firefox
2. Open a card with a checklist and some items in it
3. Click on the last item to put it in edit mode
### Expected (Firefox)

![firefox](https://cloud.githubusercontent.com/assets/3185573/11928313/b09aebda-a7d2-11e5-9745-97548cab2819.png)

"Add an item..." element is correctly shown below the "Save" button.
### Actual (Waterfox)

![waterfox](https://cloud.githubusercontent.com/assets/3185573/11928333/ce3ccb9a-a7d2-11e5-8eaa-38cef507f3e3.png)

"Add an item..." element cannot be found under the "Save" button. Instead, it has moved next to the item being edited, and a tiny bit of the initial "A" can be seen.

**Comment by MrAlex94** [comment]
I'll have a look into why this is happening :-)

**Comment by MrAlex94** [comment]
This doesn't appear to happen anymore, let me know if it does for yourself.
