### ISSUE TITLE
Switch on then it will require Waterfox restart

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#375]
Hello,

I had notice a strange trouble on the page **about:addons**. Then I'm wonder if you're aware ?
To resume, the difference between **Waterfox_v56.0.1** (or previous) and **Waterfox_v56.0.2** is very simple. In fact, the addon is supposed to be **restartless**. But now Waterfox doesn't seem to understand that.
Because in the past I didn't need (neither ask me) to restart the browser.

If you need one example you can take the addon [Sticky Password](https://www.stickypassword.com/fr/installation-dextension-windows-firefox)_v8.0.12.130 (at the moment). Sometimes it doesn't work fine that's why I need to disable it. After that I had try to enable and it doesn't work (not as usual). Because the addon will be enable only after the restart of **Waterfox_v56.0.2**.

Kind regards.

**PS :** But if you need more examples, I will assume you will find [them there.](https://addons.mozilla.org/en-US/firefox/tag/restartless)

**Comment by AjvarXX** [comment]
Confirmed by me on installing/updating restartless addons, was about to post this myself on reddit.
Now try with new profile. From my findings new profile will work restartless installing/updating addons while older profile will ask for restarts.

Also please tell if you force multiprocess aka e10s. I do.

**Comment by WagnerGMD** [comment]
You're right @AjvarXX about e10s and no I haven't recreate the profil (too much work).

**Apparently** the trouble was fixed with **Waterfox_v56.0.3**. Because the trouble has vanished after the update (at least that's true at this moment).

**Comment by grahamperrin** [comment]
> … Sticky Password https://www.stickypassword.com/fr/installation-dextension-windows-firefox … 

A strange example … it seems to be Windows-specific but the service allows installation on FreeBSD. Mozilla's Add-on Compatibility Reporter does not treat it as incompatible with multi-process. The extension describes itself as "not installed or running", maybe because a companion application and Microsoft Windows are required.

**Comment by WagnerGMD** [comment]
You're right @grahamperrin about the companion application (it's available on [this page](https://www.stickypassword.com/download)). Because usually at first you need to install it.

You're a little wrong about Windows (not only). Because you will find a [complete list there.](https://www.stickypassword.com/help/which-operating-systems-browsers-and-applications-does-sticky-password-support-101)

**Comment by grahamperrin** [comment]
Yeah, I meant that the linked extension is Windows-specific (I didn't realise until after I had installed it). 

For add-on purposes, Waterfox for FreeBSD can usually be treated as equivalent to Waterfox on Linux.

**Comment by WagnerGMD** [comment]
Nearly 3 months and I haven't met the trouble (not even once despite the update (**Waterfox_v56.0.3** to **Waterfox_v56.1.0**)). Then I will assume, the trouble doesn't exist anymore.
