### ISSUE TITLE
Refreshing Waterfox profile does't actually do it properly

### ISSUE THREAD

**Issue by AjvarXX** [BrowserWorks/waterfox#376]
Same goes for importing from older FF/WF on new WF install.
It doesn't delete addons (but resets settings of half of those) and sure thing leaves something else because on a freshly new profile I don't have a specific addon's bug while on 'refreshed' profile I keep getting that bug.

**Comment by grahamperrin** [comment]
Can you let us have a list of add-ons from a pre-refresh profile? Copied from

about:support

**Comment by MrAlex94** [comment]
I think this is due to the ‘Refresh’ setting utilising the profile import file, which I will rewrite to perform better as at the moment it’s not so great. I am aware of this issue :-)

**Comment by AjvarXX** [comment]
Thank you. Do you know about a bug in _profile import file_ that (at least in my case) it imported only first out of 3 profiles from Firefox' ~Roaming folder? Or it isn't considered a bug?

**Comment by grahamperrin** [comment]
> …  only first out of 3 profiles …

From <https://www.reddit.com/r/waterfox/comments/7ou9na/importing_firefox_profile_was_a_disaster/dschvrk/>: 

> …The current method … only uses the default profile …

**Comment by grahamperrin** [comment]
Things are hugely improved in recent releases. 

@AjvarXX would you like to (backup your data then) test <strike>with 56.1.0? 

Also: [Waterfox 56.2.0 Test Builds! Please give it a whirl. : waterfox](https://www.reddit.com/r/waterfox/comments/8jhzsj/waterfox_5620_test_builds_please_give_it_a_whirl/)</strike>

… with 56.2.0?
