### ISSUE TITLE
Clicking the Home button doesn't load the home page

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#377]
To return to the home page faster after browsing, I usually click the Home button. But on Waterfox 56.0.2, only the page title changes in the respective tab.

Here's a couple of images to illustrate the issue. In the first one I'm writing this message and the title "New issue..." is visible on the tab. But in the second image, I've clicked the Home button and that has caused the tab to revert to "New tab" while the message box data etc., is still visible. I should mention here that my home page is "about:blank". 

![home button not working](https://user-images.githubusercontent.com/33827636/34906765-f1f7670e-f873-11e7-9925-7f7f54d706c3.PNG)

![home button not working2](https://user-images.githubusercontent.com/33827636/34906767-fbd0365c-f873-11e7-8382-6d56d57508d7.PNG)

I should add here that after clicking the home button, nothing is accessible and I can't change the data. Neither is the Github login/logout menu accessible.

**Comment by grahamperrin** [comment]
[about:blank doesn't work anymore - how to blank screen? | Firefox Support Forum | Mozilla Support](https://support.mozilla.org/en-US/questions/1177709)

At first I thought the issue was worked around by disabling uBlock Origin. 

Then I realised, it's worked around by a second click on the home button.

**Comment by grahamperrin** [comment]
Not reproducible with all extensions disabled. 

@Telmesomething please let us have a list of enabled extensions. You can copy it from

about:support

**Comment by Telmesomething** [comment]
Hi Graham,

Setting prefs to "Show a blank page" seems to have done the trick. 

For the record though, I'm not using uBlock Origin, just ABP Plus.

**Comment by grahamperrin** [comment]
Thanks!

----

Incidentally, there's what may be a bug on the Mozilla side (in Firefox 56.0.2) with `about:blank` not respected for _new tab_ purposes. 

First Waterfox: 

![2018-01-17 08 05 07 waterfox](https://user-images.githubusercontent.com/192271/35032249-272f7c4e-fb5e-11e7-917d-ec272e4c31c2.png)

Then (after quitting Waterfox) with Firefox using the same profile, the same preference: 

![2018-01-17 08 07 20 new tab - mozilla firefox](https://user-images.githubusercontent.com/192271/35032257-30b5a2d4-fb5e-11e7-92cd-8d86fba8c006.png)
