### ISSUE TITLE
How to avoid Photon?

### ISSUE THREAD

**Issue by Nadahar** [BrowserWorks/waterfox#379]
The new Firefox UI "Photon" is terrible in so many ways that I won't point it out here. My question is simply if there is a way to avoid this UI in Waterfox?

I think Photon will make a lot of people leave Firefox, and there's a need for an alternative that keeps the proper UI. Waterfox removes other unwanted "features" from Firefox, so being able to avoid Photon would be very useful. I've tried all the "tweaks" for Photon, but it doesn't solve the fundamental problem that the UI and the tabs in particular is very ugly and hard to read. This might be the only thing that could prevent me (and I suspect many others) to look for a non-gecko based browser.

**Comment by grahamperrin** [comment]
Related:

- [Welcome | Photon Design System](https://design.firefox.com/photon/welcome.html)
- <https://github.com/MrAlex94/Waterfox/issues/187#issue-251510440>

> … Photon UI? …

See also: 

- [Hiding titlebar on Linux : waterfox](https://www.reddit.com/r/waterfox/comments/8ca9tt/hiding_titlebar_on_linux/)

**Comment by Nadahar** [comment]
@MrAlex94 It would be nice if you stated if it is a way, you plan to make a way simply isn't going to do anything to fix this. It is my primary reason for wanting to find an alternative to Firefox, so it would be useful to know if this is a dead end in that regard. I'm sure I'm not the only one in this situation.

**Comment by MrAlex94** [comment]
Not sure I understand, Waterfox doesn’t use Photon??

**Comment by Nadahar** [comment]
@MrAlex94 Then that is a useful reply. That said, I got the same fucked up tabs in Waterfox after a certain update as I did in Firefox after Photon was forced on us by Mozilla. It's too long ago now for me to remember the exact details of the versions.
