### ISSUE TITLE
e10s: multiprocess enabled with incompatible add-ons after refreshing waterfox 56.0.3

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#380]
From [Refresh Firefox - reset add-ons and settings | Firefox Help](https://support.mozilla.org/kb/refresh-firefox-reset-add-ons-and-settings)

> … If you're having problems …, refreshing it can help. …

With Waterfox 56.0.3: a refresh causes multiprocess to be enabled with add-ons that are not compatible. There's a significant risk of causing problems; not helpful.

**Comment by AjvarXX** [comment]
56.0.3 implemented new option of enabling e10s with unsupported addons and using single process for those unsupported addon.
_Enable e10s, disable e10s-multi for add-ons marked as incompatible. If you have issues with any add-ons, disable e10s completely.
Removed “e10s - (PID)” label from tabs._

**Comment by grahamperrin** [comment]
>> …  If you have issues with any add-ons, …

Refreshment should reduce, not increase, the likelihood of issues.

**Comment by AjvarXX** [comment]
Refreshment will decrease problems as long as addons will be deleted in the process (it will be fixed hopefully).

I personally always turned on e10s even with few unsupported addons.

**Comment by grahamperrin** [comment]
> … addons will be deleted …

That's a different issue …

**Comment by grahamperrin** [comment]
#538

**Comment by Peacock365** [comment]
@grahamperrin 

Does it still occur in Waterfox 56.1 or 56.2 in the same manner? Please verify. If it doesn't happen anymore, you could close the issue.

**Comment by grahamperrin** [comment]
Given the other e10s-related issues, I don't imagine getting a meaningful test result for this issue at this time.

**Comment by grahamperrin** [comment]
## Mac OS X 10.9.5 (Mavericks)

A clean profile '380' created by Waterfox 56.0.2, with addition of one truly incompatible extension: [Mozilla Archive Format](https://addons.mozilla.org/addon/mozilla-archive-format/). 

56.0.2: 

- not bugged.

56.0.3: 

- multiprocess windows reportedly enabled by user
- truly **not** enabled by me
- the extension malfunctions. 

56.1.0

- multiprocess windows reportedly disabled forcibly 
- not forced by me
- the force persists following a refresh. 

56.2.0: 

- multiprocess windows reportedly disabled forcibly 
- not forced by me
- the force persists following a refresh. 

56.2.1: 

- multiprocess windows reportedly disabled forcibly 
- not forced by me
- the force persists following a refresh. 

Further investigation required. (I guess that Waterfox project-provided builds of Waterfox 56.1.0 and greater disallow multi-process on Mavericks.) 

I might test on Kubuntu. 

Meta, tracking: #538

**Comment by grahamperrin** [comment]
Related (to multiple issues), in Reddit: 

- [e10s: availability of multi-process with older versions of operating systems : waterfox](https://www.reddit.com/r/waterfox/comments/8rtb3l/e10s_availability_of_multiprocess_with_older/)
