### ISSUE TITLE
Waterfox slow to load sites

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#381]
Why does Waterfox take so loooooong to load sites?

I just created a new profile and typed https://www.bbc.com/news in the location bar, but Waterfox stubbornly refuses to load the site at all. I had the same problem earlier trying to load this search engine: http://www.teoma.com/ 

The same URLs typed in Basilisk or FF ESR load in seconds. Here's a pix of Waterfox at the top and Basilisk underneath with the latter having loaded the BBC news site immediately while Waterfox grinds away at the top. Both browsers have exactly the same addons installed. 

And no, I don't accept cookies from the BBC in either browser. 

I really want to keep using Waterfox, but this problem not loading sites quickly is becoming irritating. 

![wf_not_loading](https://user-images.githubusercontent.com/33827636/34950345-35a46dd0-fa13-11e7-9cd7-7f6c0024c57c.PNG)

**Comment by criztovyl** [comment]
Any output in the browser console (<kbd>CTRL</kbd><kbd>ALT</kbd><kbd>J</kbd> or hamburger menu &rarr; Developer &rarr; Browser Console)?
Output from the network panel meight also be interesting in your case (<kbd>CTRL</kbd><kbd>ALT</kbd><kbd>K</kbd> and then "Network", or "Network" in hamburger menu, instead of Browser Console.)

**Comment by Telmesomething** [comment]
In the browser console for today the top entry highlighted in pink is for Self-Destructing Cookies. The links points to domstorage.js The second link points to core.js

Further down the list there are separate entries for RemoteAddonsParent.jsm, filterService.js and overlay.js These are all repeated several times over.

[domstorage.txt](https://github.com/MrAlex94/Waterfox/files/1634279/domstorage.txt)
[corejs.txt](https://github.com/MrAlex94/Waterfox/files/1634280/corejs.txt)
[RemoteAddonsParent.jsm.txt](https://github.com/MrAlex94/Waterfox/files/1634287/RemoteAddonsParent.jsm.txt)
[filterServicejs.txt](https://github.com/MrAlex94/Waterfox/files/1634290/filterServicejs.txt)
[overlayjs.txt](https://github.com/MrAlex94/Waterfox/files/1634318/overlayjs.txt)

I've noticed though that the problem with loading sites only occurs after Waterfox has been closed such as overnight or when I've used the PC for something else such as playing games for a few hours. Once the first site (wherever that might be) has been loaded, others will load promptly.

**Comment by Telmesomething** [comment]
I think I've found the problem. I've always set every FF browser to clear cache on exit via prefs/privacy ever since I read about certain types of malware which use the browser cache to infect machines. However, when that's been set in Waterfox, the site loading problem appears even when a site hasn't been loaded before such as when using bookmarks which have been imported to a new profile. 

I guess this would be a bug of some kind or another since Basilisk or FF ESR don't have that problem.

**Comment by Telmesomething** [comment]
I regret to say that this problem persists when cache is set to clear when exiting Waterfox. Here's another example of that. The three sites which still haven't loaded in spite of taking a screenshot of Waterfox in the background and Basilisk in the foreground are [Reuters UK](https://uk.reuters.com/) [Teoma.com](https://www.teoma.com/) and [Politico.eu](https://www.politico.eu/)

![3x_sites-not-loading](https://user-images.githubusercontent.com/33827636/35096275-e0890730-fc4b-11e7-8547-1e22bf6e2c4a.PNG)

There's obviously something seriously amiss with Waterfox if it will only load sites when the settings for clearing cache is unchecked in prefs/privacy. Here's an image of the settings I'm referring to.

![clearing_history_settings](https://user-images.githubusercontent.com/33827636/35096410-60bf52ec-fc4c-11e7-9825-13984543754d.PNG)

It's taken about ten minutes to take the screenshots, log in here and write this post and in spite of all that, the three sites still haven't loaded!

![3x_not_loaded](https://user-images.githubusercontent.com/33827636/35096541-d79c838a-fc4c-11e7-9aad-02cae8dcd786.PNG)

**Comment by grahamperrin** [comment]
> … [addons](https://github.com/MrAlex94/Waterfox/issues/381#issue-288639548) … 

> … something seriously amiss with …

Please let us have troubleshooting information. Copied from

about:support

**Comment by Telmesomething** [comment]
> Please let us have troubleshooting information.

As requested. 
[troubleshooting_information.txt](https://github.com/MrAlex94/Waterfox/files/1648802/troubleshooting_information.txt)

**Comment by grahamperrin** [comment]
Thanks. From the troubleshooting information: 

> Multiprocess Windows: 1/1 (Enabled by user)

– that might have been silently enabled by Waterfox, not by you. 

Also: 

> Name: Self-Destructing Cookies
> Version: 0.4.12
> Enabled: true

That's not compatible with multiprocess: 

![2018-01-20 14 24 37](https://user-images.githubusercontent.com/192271/35184495-5b3b0660-fdee-11e7-8eef-633c015852f2.png)

[Self-Destructing Cookies compatibility reports](https://addons.mozilla.org/compatibility/reporter/jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E%40jetpack)

https://addons.mozilla.org/addon/self-destructing-cookies/ states: 

> … incompatible with Firefox 55+ … 

– and Waterfox 56.0 was based on Firefox 56.0.2, so I should not expect the extension to work reliably with any 56.x release of Waterfox. 

## about:preferences#general

For compatibility, you can disable multi-process Waterfox. 

### Also/alternatively

Use Mozilla's [Add-on Compatibility Reporter](https://addons.mozilla.org/addon/add-on-compatibility-reporter/) to make yourself aware of other reported incompatibilities with multi-process. 

## Related

[Waterfox: e10s, multi-process, extensions.e10sBlocksEnabling and extensions.e10sMultiBlocksEnabling · Issue #397 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/397)

**Comment by Telmesomething** [comment]
OK, disabling multiprocess seems to have done the trick and sites load normally now even with cache checked to clear on shutdown.

Thanks for the tip re: the compatibility reporter. I shall certainly make use of that.
