### ISSUE TITLE
Waterfox will not remember that I have made it the default browser

### ISSUE THREAD

**Issue by pnighswonger** [BrowserWorks/waterfox#383]
Waterfox recently updated to 56.0.3 on my Windows 7 desktop machine.  Now it asks me if I want it to be my default browser every time I start it.  Each time I tell it yes, but it doesn't remember.  I have the same issue on a laptop of mine with Windows 7 as well.

**Comment by grahamperrin** [comment]
#538

**Comment by grahamperrin** [comment]
@pnighswonger hi, would you like to close this issue 383 and (instead) subscribe/contribute to broader issue 384?

384 considers Windows 7 cases alongside Windows 10 cases. 

– thank you
