### ISSUE TITLE
Website: Version 56.0.3 January 2017?

### ISSUE THREAD

**Issue by BrendonIrwan** [BrowserWorks/waterfox#385]
https://www.waterfoxproject.org/

and see that the release year is wrong.

Also why am I offered to download the Mac version when I'm on Windows?

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by grahamperrin** [comment]
… why am I offered to download the … 

[waterfoxproject.org displays operating system incorrect · Issue #314 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/314) in particular, 

>> … "download for mac" for a split second …

**Comment by BrendonIrwan** [comment]
Okay that makes sense...but the incorrect year makes me think that Waterfox 56 was released a year ago, though I know that's not the case

**Comment by grahamperrin** [comment]
Yeah, probably just a typo from when the corresponding blog post for 56 was first made (in 2017). 

@MrAlex94 I'd like to make a pull request but (sorry) I'm quite focused on other stuff at the moment.

**Comment by MrAlex94** [comment]
Could you [hard refresh](https://wiki.scratch.mit.edu/wiki/Help:Hard_Refresh#Mozilla_Firefox_and_Related_Browsers) the page?

I have fixed the error and flushed the CDN cache as well around a week ago, so it shouldn’t still show, 2017.

**Comment by BrendonIrwan** [comment]
Nope, it still shows 2017. I just found that out a day ago with a fresh instance of Firefox, then Waterfox

EDIT: In private mode and after importing from a clean profile backup

**Comment by grahamperrin** [comment]
The same, 2017: 

![2018-01-17 07 41 46 waterfox - the free open and private browser](https://user-images.githubusercontent.com/192271/35031330-577faada-fb5a-11e7-82d7-3a781a857569.png)

**Comment by Serkan-devel** [comment]
Inspect element fixes all problems

**Comment by grahamperrin** [comment]
> Inspect element fixes all problems

Not for me. I reloaded without the cache, then inspected the element, there's still _2017_.

**Comment by MrAlex94** [comment]
I’ve just reset the CDN cache again. Could you all see if it’s okay?

**Comment by BrendonIrwan** [comment]
Yes yes, it shows the correct year now. Thanks and keep it up!

**Comment by grahamperrin** [comment]
Fix confirmed. Thanks.
