### ISSUE TITLE
56.0.x refreshment of a non-default profile used data from the wrong profile (from the default profile)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#386]
Yesterday whilst running Waterfox 56.0.2_1 or 56.0.3 (I'm not sure which, probably the latter) with a profile root `/home/grahamperrin/.mozilla/firefox/tuk42vu2.minimal everyday-1508231281798` (not the default profile) I opted to refresh the profile. 

## Expected

Refreshment based on the only profile that was in use when the refresh began. 

## Actual result

Refreshment based on a different profile, the default profile. 

## Environment

FreeBSD-CURRENT, 

```text
$ uname -v
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
```

## Workaround

- quit Waterfox
- remove the unwanted data
- put back in place the old data (from the desktop).

**Comment by MrAlex94** [comment]
There was a bug discussing this. Only the default profile gets set, as you can see discussed in [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1100334) bug. Usually the button is hidden, but Waterfox exposes it otherwise it never appears. 

I will try patch this bug for Mozilla as well when I re-do the migration code, as this is where the code for this feature lies.

**Comment by grahamperrin** [comment]
Thanks! 

(Previously, I wondered whether the `~/.mozilla/firefox/` origin of the profile was a factor.)

For me: not a priority. 

(If I need to refresh a non-default profile, I guess that I can work around the bug by temporarily making the profile the default.)

**Comment by grahamperrin** [comment]
This might be a duplicate of at least part of [Refreshing Waterfox profile does't actually do it properly · Issue #376 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/376) … sorry.

**Comment by grahamperrin** [comment]
Probably fixed. If not, we can open another issue.
