### ISSUE TITLE
Update Program Description on Windows

### ISSUE THREAD

**Issue by BrendonIrwan** [BrowserWorks/waterfox#387]
This is minor unless you want to remove as much Mozilla as possible. In short words, see screenshot below.

On a Windows machine, if you head to:

Control panel -> Programs -> Default Programs -> Set Default Programs

Waterfox will be there but is printed to be by Mozilla Corporation

![image](https://user-images.githubusercontent.com/13151306/35028846-a398da4c-fb8a-11e7-8881-c48e61ec95a5.png)

**Comment by roytam1** [comment]
maybe here?
https://github.com/MrAlex94/Waterfox/blob/master/browser/app/module.ver

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/dca0c447a311e2cd8da7f5bebf08b158857174eb
