### ISSUE TITLE
Missing localStorage

### ISSUE THREAD

**Issue by ZatsuneSakurako** [BrowserWorks/waterfox#388]
I'm using Waterfox 56.0.3 on Windows 64bit, and it seems like localStorage is not available (e10s is enabled).

```
Fenêtres multi-processus 	1/1 (Activé par l’utilisateur)
Processus de contenu web 	5/7
```

It's not available in web pages (and localStorage is null), and Web Extensions, for what I have seen. I have likely the same profile in Firefox 56, so an addon or setting should not be messing something around.

I guess it could be the same problem as #246

**Comment by WagnerGMD** [comment]
Do you have an example ? Which website require the localStorage ?
Because according to my memories, I will only have one example and it seem's to work fine.
```
pref("dom.storage.enabled",false);
## It will disable the HTML5 localStorage or sessionStorage.
```
Because no you didn't mentionned the page **about:config** and you must clarify this point.

**Comment by ZatsuneSakurako** [comment]
Well, that website ( https://discord.js.org/#/docs/main/stable/general/welcome ) does not fully work without localStorage. And I didn't even know that preference, and I don't even know why it was disabled, weird. But thanks. (And x-Notifier Neo does not work without localStorage)

**Comment by WagnerGMD** [comment]
I don't remember the other website but I know, there are a few websites which won't work (when it's disable).
Glad I was able to help.

**PS :** In the past, I used the addon [Shim Storage](https://addons.mozilla.org/en-US/firefox/addon/shim-storage/) when I wanted to control it.
Then yes I had stop to use it but perhaps you will be (or find some) interest.

**Comment by ZatsuneSakurako** [comment]
Well as I said, I have no idea about what switched it to disabled. The idea of Shim Storage is nice, in Web Extension it could be nice.

**Comment by grahamperrin** [comment]
Other extensions that can make `dom.storage.enabled` `false` include [Privacy Settings](https://addons.mozilla.org/addon/privacy-settings/), when _Privacy & Security_ or _Full Privacy_ is preferred.

**Comment by ZatsuneSakurako** [comment]
Oh, that's true, that's probably this addon which did it. Thanks
