### ISSUE TITLE
Webextension API merge strategy

### ISSUE THREAD

**Issue by Happy-Ferret** [BrowserWorks/waterfox#389]
As an interested developer, I'd like to know if there's any merge strategy in place for dealing with the newer Webextension APIs introduced with FF57+.

Some of the changes can be easily cherry-picked or applied with ``git am`` (``browser.privacy.websites.trackingProtectionMode``, for one), others require somewhat more work in order to not run into merge conflicts or even touch files outside of ``toolkit/components/extensions``.

Any solid merge strategy to deal with this, @MrAlex94?

I wouldn't mind helping on that front, btw.

**Comment by grahamperrin** [comment]
See also: https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-360014353

**Comment by Peacock365** [comment]
@Happy-Ferret 

I think it would be an amazing idea to merge newer WebExtension APIs in. After all, some add-ons have already ended support for ver.56 as they rely on newer APIs.

Furthermore, I am sure @MrAlex94 wouldn't mind if somebody could assist him with these issues by creating related commits:

https://github.com/MrAlex94/Waterfox/issues/538

I hope you are still interested, I have only found his ticket recently.

**Comment by grahamperrin** [comment]
Handy points of reference, thanks to @jbeich 

- 57 https://developer.mozilla.org/Firefox/Releases/57#New_APIs
- 58 https://developer.mozilla.org/Firefox/Releases/58#New_APIs
- 59 https://developer.mozilla.org/Firefox/Releases/59#New_APIs
- 60 https://developer.mozilla.org/Firefox/Releases/60#New_APIs

**Comment by grahamperrin** [comment]
> if there's any merge strategy

Whilst I'm not aware of an explicit _strategy_ … 

… defocusing from APIs, we **do** have plenty of recent work that goes towards the stated aim of _maintaining_ (security and bug fixes for) Waterfox Classic. <https://github.com/MrAlex94/Waterfox/compare/56.2.14...2019.10-classic-1>, various [PRs](https://github.com/MrAlex94/Waterfox/pulls), and so on. 

@Happy-Ferret all things considered – with Waterfox Current developing nicely in parallel with maintenance of Waterfox Classic – would you like to close this issue? 

Thanks
