### ISSUE TITLE
Refresh Waterfox: the dialogue should not suggest that add-ons will be removed

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#390]
With Waterfox 53.0.3_2 on FreeBSD-CURRENT: 

![2018-01-19 07 35 17 refresh waterfox](https://user-images.githubusercontent.com/192271/35139532-72117f12-fceb-11e7-95a7-0942505f9d9c.png)

> ## Refresh Waterfox
> 
> Start fresh to fix problems and restore performance. 
> 
> This will: 
> 
> - remove your add-ons and customisations
> - restore your browser settings to their defaults
> 
> `[[Cancel]]    [Refresh Waterfox]`

## Actual result of refreshment

Extensions, user styles, plug-ins, dictionaries and languages are (loosely speaking) not removed. I love the convenience, the preservation.

An example, before and after refreshment: 

![2018-01-14 16 20 54](https://user-images.githubusercontent.com/192271/35139810-ada4adfa-fcec-11e7-8bfa-ace22bee1a8d.png)

![2018-01-14 16 35 41](https://user-images.githubusercontent.com/192271/35139815-b424c890-fcec-11e7-89b6-3efd92ee0a53.png)

![2018-01-14 16 53 52](https://user-images.githubusercontent.com/192271/35139821-b7eef072-fcec-11e7-95b4-6834680c9804.png)

Side note: the third screenshot – all pages failing to load – is symptomatic of [e10s: multiprocess enabled with incompatible add-ons after refreshing waterfox 56.0.3 · Issue #380 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/380).

# Issue (enhancement request)

Change the wording in the dialogue, to not suggest that add-ons will be removed.

**Comment by grahamperrin** [comment]
From today's [Waterfox's current status …](https://www.reddit.com/r/waterfox/comments/818z1k/waterfoxs_current_status/): 

> The `Refresh` button has been fixed in `about:support`. You will now be able to reset your profiles while keeping only your important data (same as Firefox).

To clarify: will the fix cause refreshment to remove add-ons from a Waterfox profile (same as Firefox 56.0.2 and Firefox Quantum)?

@MrAlex94 please advise – thanks.

**Comment by MrAlex94** [comment]
No it won’t remove extensions, but it may reset their preferences.

**Comment by grahamperrin** [comment]
Sane. Excellent! Thanks. 

I can probably do PRs for basic issues such as this. (I'll wait until after your offline commits go online, then try to find my way around …)

**Comment by grahamperrin** [comment]
56.2.0, build 20180514223240: 

![2018-05-15 22 10 53 refresh waterfox](https://user-images.githubusercontent.com/192271/40084624-a5ed37ae-588f-11e8-8470-7cd5f7fc83bb.png)

That's enough for me to close this issue. 

----

For other issues with the two **Refresh Waterfox** dialogues, over to: 

- [UX of Refresh Waterfox · Issue #562 …](https://github.com/MrAlex94/Waterfox/issues/562)
