### ISSUE TITLE
Refresh Waterfox: appearance add-ons (themes) are removed

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#391]
In [Refresh Waterfox: the dialogue should not suggest that add-ons will be removed · Issue #390 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/390) the before-and-after screenshots show: 

- fourteen appearances before
- three appearances after. 

If I recall correctly: 

- the three that were preserved were the three that were integral to Firefox 56.0.2 (I used Firefox to create the profile).

**Comment by grahamperrin** [comment]
From <https://github.com/MrAlex94/Waterfox/issues/376#issuecomment-357485743>: 

> …  ‘Refresh’ setting utilising the profile import file, which I will rewrite to perform better …

From <https://www.reddit.com/r/waterfox/comments/7ou9na/importing_firefox_profile_was_a_disaster/dschvrk/>: 

> 56.1 will include a completely re-written profile importer. …

**Comment by grahamperrin** [comment]
IIRC this was fixed. Sorry for not closing in good time.

**Comment by grahamperrin** [comment]
Closed in error. A refresh of 56.2.0, build 20180514223240, removed a theme. 

Meta, tracking: #538

**Comment by MrAlex94** [comment]
Themes are meant to be removed.

**Comment by grahamperrin** [comment]
Interesting, thanks. 

Re: #187 I probably have zero experience with complete themes. A wild guess … are some of them so problematic that it's sane to remove all, as a precaution, when refreshing?
