### ISSUE TITLE
Waterfox and latest uBlock origin 

### ISSUE THREAD

**Issue by BzfpWg9g** [BrowserWorks/waterfox#393]
Maybe intersting for you because of the popularity of the addon. Can't tell if it's only me having this issue.. Posted this first at the uBlock origin developer github-page but Waterfox is not supported, therefore closed.

### Describe the issue

Occasionally I got errors when surfing some webpages on Waterfox 56,0,3: "The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression."

After reloading Site with F5 it usually worked. Trying to change Firwall/Antivir-Settings/network.http.accept-encoding-settings, etc with no change. 

### One or more specific URLs where the issue occurs

https://twitter.com but reproducible for me with other URLs

### Screenshot in which the issue can be seen

Standard error page: See http://1.bp.blogspot.com/-RkOJfqRmp4A/UNOHlErnmyI/AAAAAAAAAHo/FtXK_ueDKQc/s640/compression-error.gif as an example

### Steps for anyone to reproduce the issue

1. https://twitter.com
2. Go to random twitter profile
3. hit Ctrl+F5 till error page appears (~4-5 clicks in my case)

### Your settings

OS/version: Windows 7 Prof
Browser/version: Waterfox 56,0,3
uBlock Origin version: 1.14.25rc1

**Comment by grahamperrin** [comment]
[Content Encoding Error The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression. : waterfox](https://www.reddit.com/r/waterfox/comments/7nl8k0/content_encoding_error_the_page_you_are_trying_to/)
