### ISSUE TITLE
Waterfox 56.0.2 doesn't update

### ISSUE THREAD

**Issue by Serkan-devel** [BrowserWorks/waterfox#395]
Same like here: https://github.com/MrAlex94/Waterfox/issues/318
But I don't want to reinstall it again

**Comment by grahamperrin** [comment]
> … extracted the tarball …

Today I used https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.0.2.en-US.linux-x86_64.tar.bz2 to install on Kubuntu 17.10. 

The About Waterfox window for 56.0.2 presents: 

> Checking for updates… 

– then: 

> Waterfox is up to date

56.0.3 was released around a week ago (2018-01-12) so I don't suspect a CDN issue.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/361#issuecomment-358978477 is thought-provoking.

**Comment by Serkan-devel** [comment]
It seems to have directly updated to 56.0.4
