### ISSUE TITLE
Waterfox: e10s, multi-process, extensions.e10sBlocksEnabling and extensions.e10sMultiBlocksEnabling

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#397]
## _e10s_ and _e10s-multi_

Please: what's **the difference** between these? 

- `extensions.e10sBlocksEnabling` 
- `extensions.e10sMultiBlocksEnabling`

A few days ago I sought an explanation, couldn't find anything that helped me to differentiate. 

## Help ▸ Restart with add-ons disabled… ▸ Waterfox safe mode ▸ Refresh Waterfox

If Waterfox will continue to default to allowing multi-process with any add-on that is not explicitly marked as compatible, then we need: 

- something in or around the _Help_ menu to make it unmistakably clear that the allowance might introduce _problems_. 

## Background

Not intended to be comprehensive …

2017-08-22: [Multiprocess Windows disabled on WF v55.0.2! · Issue mozilla/addons-server#188 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/188)

[2017-12-22](https://github.com/MrAlex94/Waterfox/issues/309#issuecomment-353610926) under _Extension "Scrapbook X" has an issue with WaterFox56_: 

> A fair few people complained that e10s blocking wasn't necessary, so I [disabled](https://github.com/MrAlex94/Waterfox/commit/9c4cc5585e2d6b00ce06fcdde9d98fbd400471c6) it but seems that the problems it does cause to add-ons not compatible is greater. Will revert it I reckon for the next release.

[2018-01-11](https://github.com/MrAlex94/Waterfox/commit/6e345976571abe1b99cddc2b718de1f50af5c4cb): 

>  Now that more users have tested it, e10s seems to be preferred enabled even with add-ons not explicitly marked. Multi will remain blocked for incompatible add-ons.

– with reference to `extensions.e10sBlocksEnabling` (changed from `true` to `false` (for release or beta)) and `extensions.e10sMultiBlocksEnabling`.

2018-01-14: [e10s: multiprocess enabled with incompatible add-ons after refreshing waterfox 56.0.3 · Issue mozilla/addons-server#380 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/380)

>> … refreshing it can help. …

> … significant risk of causing problems; not helpful. 

The refresh lost my preference for [browser.tabs.remote.force-disable](https://github.com/MrAlex94/Waterfox/issues/311), which is understandable. 

The introduction of problems, as a result of Waterfox defaults at the time, is less understandable (less logical). 

[2018-01-20](https://github.com/MrAlex94/Waterfox/issues/246#issuecomment-359150466) under _LocalStorage is not cleared by add-on_, in response to a question about use of 56.0.3 with an extension that's marked as incompatible with multi-process: 

> … should not let me enable e10s because its marked as incompatible. But enabling worked. …

### Plus … 

- various posts, including differences of opinion, at https://www.reddit.com/r/waterfox/ 
- and so on.

**Comment by grahamperrin** [comment]
@MrAlex94 hi …

The set of e10s-related defaults, since 56.0.3, is the _only_ thing that causes me to hesitate before recommending Waterfox. 

From a support perspective, the default allowance – multi-process for extensions that are incompatible with multi-process – is troublesome. 

Please, can it be changed with the next release? 

TIA

**Comment by grahamperrin** [comment]
From <https://github.com/MrAlex94/Waterfox/pull/457#issuecomment-370604318>: 

> … Not sure what to do about mentioning multi-process …

@MrAlex94 as I see it, you have (amongst other groups) these two groups of users: 

1. a good number of power users who are happy to 'push boundaries' for their selves, based on prior experience with consciously overlooking (or not noticing) incompatibilities with multi-process
2. a good number of more recent emigrants from Firefox, most of whom have been shielded from the risks – by the browser logically defaulting to disable multi-process wherever a _reportedly_ incompatible extension is enabled. 

----

Around three weeks ago I threw caution to the wind and enabled multi-process – to begin methodically/holistically getting a feel of how things behave, with my own set of extensions that are flagged as incompatible. I imagined doing that quietly for a week or so, but gave up after a few hours of thrashing things out. There was a clearly identifiable non-intrusive problem with one incompatible extension – fair enough 👍 … 

… what concerned me _more_ was the holistic effect. tl;dr Waterfox behaved as if there were problems with extensions that _are_ compatible with multi-process. After I disabled multi-process, no more misleading symptoms. 

For myself I don't mind working through that type of stuff `:-)` but from a community troubleshooting perspective, I'm not convinced that 'allowing incompatibility' is a logical default. It's one of the reasons for me robotically requesting information from `about:support`; the first thing I wanna rule out is whether there's 'enabled by user' when (a) truly it wasn't enabled by the user and (b) logically it should be disabled.  

Yesterday's https://www.reddit.com/r/waterfox/comments/826gft/-/dv7x8af/ is probably the most recent example of problems being resolved by overriding the Waterfox default, and thankfully it's another good-humoured example but sooner or later … there'll be a sad face from an end user, or worse. 

----

Back to the refresh dialogue: if the result of a refresh will be (re)allowance of incompatibility, then the least we can do is be open about the behaviour. Not do anything that might be misconstrued as sweeping things under the carpet. 

Thoughts? 

Obviously I don't want to upset the apple cart for power users, so there should remain a way of people **force-enabling** multi-process where an enabled extension is incompatible with multi-process. I imagine that it's do-able at `about:config` …

Cheers

**Comment by grahamperrin** [comment]
> … not convinced that 'allowing incompatibility' is a logical default. …

The most recent example: https://github.com/MrAlex94/Waterfox/issues/476#issuecomment-374051348

**Comment by grahamperrin** [comment]
Re: https://github.com/MrAlex94/Waterfox/issues/484#issuecomment-375489430 point (b)

**If** there'll be a web front end to mozilla/addons-server#303, then future polish _might_ include presentation of multiprocess compatibility information. 

https://github.com/mozilla/addons-server/labels/component%3A%20feature%20deprecation includes _Remove multi-process status_ – primarily about presentation in devhub, I wonder whether any of the prior code could be reused for presentation to the (Waterfox) end user.  

NB a couple of closed, non-fixed issues: 

- [API returns wrong e10s information · Issue mozilla/addons#3728 · mozilla/addons-server](https://github.com/mozilla/addons/issues/3728) 
- [Define multiprocess compatibility on add-on pages on AMO · Issue mozilla/addons#4168 · mozilla/addons-server](https://github.com/mozilla/addons/issues/4168).

**Comment by grahamperrin** [comment]
Related: https://www.reddit.com/r/waterfox/comments/88ho5y/-/dwl4i7m/

Technically, I still don't know the difference between `extensions.e10sBlocksEnabling` and `extensions.e10sMultiBlocksEnabling` but it seems that `extensions.e10sBlocksEnabling` `true` has the desired effect (least risk of incompatibilities).

**Comment by grahamperrin** [comment]
> … I still don't know the difference …

As far as I can tell: 

- e10s originally signified multi-process **but not** multiple content processes
- e10s-multi is, by Mozilla's definition, _Ship Firefox with multiple content processes_ e.g. <https://bugzilla.mozilla.org/show_bug.cgi?id=e10s-multi>.

Still, I'm puzzled. `extensions.e10sMultiBlocksEnabling` defaults to `true` in Waterfox 56.1.0 but does **not** block multiple process. 

<https://dxr.mozilla.org/mozilla-central/rev/abf145ebd05fe105efbc78b761858c34f7690154/dom/ipc/ContentParent.cpp#720>: 

```text
  // Let's respect the user's decision to enable multiple content processes
  // despite some add-ons installed that might performing poorly.
  if (!hasUserValue &&
      Preferences::GetBool("extensions.e10sMultiBlocksEnabling", false) &&
      Preferences::GetBool("extensions.e10sMultiBlockedByAddons", false)) {
    return 1;
  }
```

**Comment by ElhemEnohpi** [comment]
FYI, I just tested it and it's true, even with `extensions.e10sMultiBlocksEnabling=true` and `extensions.e10sMultiBlockedByAddons=true` (due to the presence of incompatible add-ons), e10s multi is still enabled - there are four content processes. And restartless addons are still restartless. macOS, WF 56.1.0.

**Comment by grahamperrin** [comment]
> the default allowance – multi-process for extensions that are incompatible with multi-process – is troublesome.

More cases of trouble involving the risky default: 

- [Extensions xpcom will be available in the new version of Waterfox? · Issue mozilla/addons-server#278 …](https://github.com/MrAlex94/Waterfox/issues/278)
- [V56 Breaks these/many addons that worked on v55 · Issue mozilla/addons-server#525 …](https://github.com/MrAlex94/Waterfox/issues/525)
- [Twitter videos aren't being loaded : waterfox](https://www.reddit.com/r/waterfox/comments/8c1j0f/twitter_videos_arent_being_loaded/)
- https://www.reddit.com/r/waterfox/comments/8g57m3/-/dyc3d3r/
- [Extreme resource usage in 56.2 v 56.0.1 · Issue mozilla/addons-server#556 …](https://github.com/MrAlex94/Waterfox/issues/556)
- [FlashGot menu items do not fully display in WF : waterfox](https://www.reddit.com/r/waterfox/comments/8kkm6p/flashgot_menu_items_do_not_fully_display_in_wf/)
- [v56.2 seems to have broken Googlebar Light · Issue mozilla/addons-server#596 …](https://github.com/MrAlex94/Waterfox/issues/596#issuecomment-392830026)
- [MAFF Support? : waterfox](https://www.reddit.com/r/waterfox/comments/8pu0k5/maff_support/) – problem resolved by disabling multi-process, https://www.reddit.com/comments/84fe80/-/e0hpnnt/?context=4
- [56.2.0 (64Bits) Issue with Waterfox and ScrapBook X · Issue mozilla/addons-server#614 …](https://github.com/MrAlex94/Waterfox/issues/614)
- [IE Tab2 not work on 56.2.1 · Issue mozilla/addons-server#631 …](https://github.com/MrAlex94/Waterfox/issues/631)
- https://www.reddit.com/comments/8z156j/-/e2fymlm/?context=1
- [Open new tab does nothing in Vimium/… · Issue mozilla/addons-server#701 …](https://github.com/MrAlex94/Waterfox/issues/701)
- http://disq.us/p/1u2frr9
- http://disq.us/p/1u0nnqp
- https://www.reddit.com/comments/9dibnb/-/e5hsixa/?context=1
- https://www.reddit.com/comments/9dxsov/-/e67dyqo/?context=2
- https://www.reddit.com/comments/9iotxp/-/e6w0iea/?context=2
- https://www.reddit.com/comments/9k2ars/-/e6w7r8q/?context=2
- https://www.reddit.com/comments/9pclnb/-/e82txt5/?context=2
- https://www.reddit.com/comments/9tmn5v/-/eeyeuoe/?context=2
- https://www.reddit.com/comments/cpg1mn/-/ewtvp4s/
- https://redd.it/dn3y0j
- …

**Comment by grahamperrin** [comment]
mozilla/addons-server#538
