### ISSUE TITLE
Keyboard not fully functional in newest version Waterfox

### ISSUE THREAD

**Issue by Pallastor** [BrowserWorks/waterfox#40]
I updated today to the 43.0.4 and since then i cant fully use my keyboard when playing Battle Pirates , i did an reboot , checked my keyboard in Chrome and Edge in game of course and there it worked perfectly , the only addon i use now Lastpass ( usually i use Tab Mix Plus and LastPass ) , any idea how this problem could be solved ?

**Comment by alienx2** [comment]
Can you try Restart Waterfox with Addons Disabled (click Menu > ( ? ) icon > Restart Waterfox with Addons Disabled )? then try test keyboard. If its working, i think one of your addon have bug.

**Comment by MrAlex94** [comment]
Do you still have this issue?
