### ISSUE TITLE
Loss of preferences with Waterfox 56.0.3 after using a profile that has been touched by Firefox 56.0.2

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#402]
The lesson here is probably to **never** allow the two applications to touch the same profile ;-) so I expect this issue to be closed without a fix, but for the record …

## Example: `extensions.getAddons.cache.enabled`

1. Use Waterfox 56.0.3 (with Session Manager and other extensions) to modify the boolean to `true`
2. quit Waterfox
3. in the _Session Manager_ dialogue, choose _Save and restore at startup_
4. use Firefox 56.0.2 (the basis for Waterfox 56.0) with the same profile
5. observe no change to the boolean
6. quit Firefox
7. in the _Session Manager_ dialogue, choose _Save and restore at startup_
8. reuse Waterfox 56.0.3

### Expected (desired)

- `extensions.getAddons.cache.enabled` `true`

### Actual result

- loss of modification; `extensions.getAddons.cache.enabled` is `false`

– and so, for the nth time, I must begin reinstalling extensions to regain information from AMO.

**Comment by AjvarXX** [comment]
There was a reason for moving Waterfox profile out of Firefox I suppose.
Suggested behavior of using both Firefox and Waterfox is using Sync I suppose with each program working with it's own profile.

**Comment by grahamperrin** [comment]
> …  I expect this issue to be closed without a fix, …
