### ISSUE TITLE
Non-smoothed fonts are not rendered on Windows

### ISSUE THREAD

**Issue by SirPL** [BrowserWorks/waterfox#403]
**Steps to reproduce:**
1. Open any website in Waterfox
2. Open "Adjust the apperance and performance of Windows" (type it in a search box in Menu Start)
3. Un-tick "Smooth edges of screen fonts"
4. Apply change

**Result:**
Most of the fonts rendered in the browser dissappear

**Tested on:**
Windows 7 x64 (SP 1), Waterfox 56.0.3 (64-bit)

**Occurence rate:**
3/3

**Comment by Squall-Leonhart** [comment]
then don't untick it.

**Comment by GitCurious** [comment]
**Unable to reproduce.**

Windows 7 x64 (SP 1)

Waterfox 56.0.3 (64-bit) - Installed - personalised.
Waterfox 56.0.3 (64-bit) - Portable - untouched.

**Result:**
Most of the fonts rendered in the browser become aliased but do stay visible.

**Comment by grahamperrin** [comment]
@SirPL can you let us have troubleshooting information? Copied from: 

about:support

– the text option (not raw). Thanks.

**Comment by SirPL** [comment]
I found this problem on my company PC. I think it may be related to a fact that I use quite old laptop with three monitors connected. I wonder if it's a performance issue. I will investigate this further once I'm back at work (in the next week)

**Comment by grahamperrin** [comment]
Review time, folks. 

Is this still an issue?
