### ISSUE TITLE
Sometimes a loading screen appears when switching to another tab

### ISSUE THREAD

**Issue by leafcutterant** [BrowserWorks/waterfox#404]
When I switch to another tab that is already open and loaded, sometimes an animated loading screen awaits me (see below) and stays for about 0.5 - 1 sec before showing the actual content of the tab. 

![asdasdasd](https://user-images.githubusercontent.com/7106231/35284467-31a17194-005b-11e8-9fd5-f0da9b8260b4.png)

This started to happen to me recently (well after updating to 56.0.3), but I've never seen anything like this before. It seems to happen randomly, regardless of the number of open tabs or the age of the tab. I also don't use any tab suspending add-ons and all my add-ons are the same as before.

Any ideas about what could be causing this?

**Comment by TemporaryAccount0x1** [comment]
this has to do with multiprocess 

see: https://support.mozilla.org/en-US/questions/1139890

**Comment by grahamperrin** [comment]
Thanks @TemporaryAccount0x1 

Mozilla bugs: 

- [1131167 - (e10s-spinner) [e10s] tracking bug for spinner-related issues](https://bugzilla.mozilla.org/show_bug.cgi?id=1131167)
- [1384184 - Investigate increased FX_TAB_SWITCH_SPINNER_VISIBLE_MS on e10s-multi](https://bugzilla.mozilla.org/show_bug.cgi?id=1384184)
- [1063169 - (e10s-perf) tracking performance issues with e10s](https://bugzilla.mozilla.org/show_bug.cgi?id=1063169)

----

@leafcutterant can you let us have a list of enabled extensions? From within the text that can be copied from `about:support`, or use [Nightly Tester Tools](https://addons.mozilla.org/addon/nightly-tester-tools/).

**Comment by ghost** [comment]
I have that spinner almost all the time when switching bewtween lodaded tabs. It is really annoying.
