### ISSUE TITLE
some firefox directories still created

### ISSUE THREAD

**Issue by Yay295** [BrowserWorks/waterfox#405]
56.0.3 clean install, Firefox has never been installed

C:\Users\<user>\AppData\Local\Mozilla\updates\6F940AC27A98DD61
C:\Users\<user>\AppData\LocalLow\Mozilla\Temp-{243ec4a7-ba21-4c80-9a09-4cbfbf2fd1f9}
C:\Users\<user>\AppData\Roaming\Mozilla\Extensions

These directories are empty, but shouldn't be there at all.

**Comment by grahamperrin** [comment]
`~/Library/Caches/Mozilla/updates/Applications/Waterfox/updates`

- from https://pastebin.mozilla.org/9087712
- via https://www.reddit.com/comments/8r66jc/-/e0qa0jo/

Postscript: voting myself down through agreement with a closure elsewhere, https://github.com/MrAlex94/Waterfox/issues/463#issuecomment-398044779
