### ISSUE TITLE
Plan for Firefox Quantum Engine

### ISSUE THREAD

**Issue by GulajavaMinistudio** [BrowserWorks/waterfox#406]
Are there any plan to use Firefox Quantum Engine in Waterfox ? But using same addons system like Firefox 56 Engine , so old addons or plugin can still work.

**Comment by grahamperrin** [comment]
Please subscribe to [Waterfox Quantum? · Issue #267 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/267)

**Comment by Squall-Leonhart** [comment]
quantum is just the addition of advanced layers and servo, both exponentially increase vram and ram usage for little gain.
