### ISSUE TITLE
Compile faild with VC2015/VC2017

### ISSUE THREAD

**Issue by Lawlietr** [BrowserWorks/waterfox#407]
He,

I starting create a fork of waterfox in yesterday
But i got a problem, can help me solve this issue

I try build waterfox 56.0.2/56.0.3 got same issue
My platform is windows 10 16299.192 x64
Compiler using VC2017/VC2015
And using your provide the .mozconfig file

thanks

output
` 2:43.18 js\src> checking for strndup... no
 2:44.06 js\src> checking for posix_memalign... no
 2:44.89 js\src> checking for memalign... no
 2:45.71 js\src> checking for malloc_usable_size... no
 2:46.22 js\src> checking whether malloc_usable_size definition can use const argument... yes
 2:46.93 js\src> checking for valloc in malloc.h... no
 2:47.43 js\src> checking for valloc in unistd.h... no
 2:48.43 js\src> checking for setlocale... no
 2:49.30 js\src> checking for localeconv... no
 2:50.18 js\src> updating cache h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/ff-pgo_x64/js/src/config.cache
 2:50.34 js\src> creating ./config.data
 2:52.02 js\src> Creating config.status
 3:01.11 Creating config.status
 3:01.11 Reticulating splines...
 3:01.11 h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\frontend\gyp_reader.py:382: UserWarning: MSVS_VERSION being set to 2015 to appease GYP
 3:01.11   warnings.warn('MSVS_VERSION being set to 2015 to appease GYP')
 3:01.11 Traceback (most recent call last):
 3:01.11   File "h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/configure.py", line 124, in <module>
 3:01.11     sys.exit(main(sys.argv))
 3:01.11   File "h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/configure.py", line 34, in main
 3:01.12     return config_status(config)
 3:01.12   File "h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/configure.py", line 119, in config_status
 3:01.12     return config_status(args=[], **encode(sanitized_config, encoding))
 3:01.12   File "h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\config_status.py", line 147, in config_status
 3:01.12     definitions = list(definitions)
 3:01.12   File "h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\frontend\emitter.py", line 182, in emit
 3:01.13     objs = list(emitfn(out))
 3:01.13   File "h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\frontend\emitter.py", line 1099, in emit_from_context
 3:01.13     for obj in self._process_test_manifests(context):
 3:01.13   File "h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\frontend\emitter.py", line 1220, in _process_test_manifests
 3:01.13     for obj in self._process_test_manifest(context, info, path, manifest):
 3:01.14   File "h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\frontend\emitter.py", line 1336, in _process_test_manifest
 3:01.14     context)
 3:01.14 mozbuild.frontend.reader.SandboxValidationError:
 3:01.14 ==============================
 3:01.14 ERROR PROCESSING MOZBUILD FILE
 3:01.15 ==============================
 3:01.15
 3:01.15 The error occurred while processing the following file or one of the files it includes:
 3:01.15
 3:01.15     h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/dom/canvas/moz.build
 3:01.15
 3:01.15 The error occurred when validating the result of the execution. The reported error is:
 3:01.16
 3:01.16     Error processing test manifest file h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/dom/canvas/test/webgl-conf/generated-mochitest.ini: Traceback (most recent call last):
 3:01.16
 3:01.16       File "h:\Waterfox-56.0.2.tar\Waterfox-56.0.2\python\mozbuild\mozbuild\frontend\emitter.py", line 1265, in _process_test_manifest
 3:01.16         path, ', '.join(missing)), context)
 3:01.16
 3:01.16     SandboxValidationError:
 3:01.16     ==============================
 3:01.16     ERROR PROCESSING MOZBUILD FILE
 3:01.17     ==============================
 3:01.17
 3:01.17     The error occurred while processing the following file or one of the files it includes:
 3:01.17
 3:01.17         h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/dom/canvas/moz.build
 3:01.17
 3:01.18     The error occurred when validating the result of the execution. The reported error is:
 3:01.18
 3:01.18         Test manifest (h:/Waterfox-56.0.2.tar/Waterfox-56.0.2/dom/canvas/test/webgl-conf/generated-mochitest.ini) lists test that does not exist: generated/test_2_conformance2__textures__canvas_sub_rectangle__tex-2d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__canvas_sub_rectangle__tex-3d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__image_data__tex-2d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__image_data__tex-3d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__svg_image__tex-2d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__svg_image__tex-3d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__webgl_canvas__tex-2d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance2__textures__webgl_canvas__tex-3d-r11f_g11f_b10f-rgb-unsigned_int_10f_11f_11f_rev.html, generated/test_2_conformance__ogles__GL__built_in_varying_array_out_of_bounds__built_in_varying_array_out_of_bounds_001_to_001.html, generated/test_conformance__ogles__GL__built_in_varying_array_out_of_bounds__built_in_varying_array_out_of_bounds_001_to_001.html`

**Comment by grahamperrin** [comment]
Review time. Is this still an issue?

**Comment by Lawlietr** [comment]
No, it can compile now
