### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by andoruB** [BrowserWorks/waterfox#409]
Been having this problem for a while now, Waterfox crashes frequently (and seemingly randomly) for no apparent reason. This tends to happen at least 5-10 times a day. I previously cleared all profiles, thinking this would solve the problem, and it did for a while, but then the problem started showing up again. I tried running Waterfox in safe mode, thinking maybe some addons are causing issues, but that didn't fix the problem either...  
So then I wanted to take a look at the crash logs to see what could be causing this... and I followed Firefox's documentation on the logs but I was unable to find them anywhere. I tried accessing about:crashes, but it seems this doesn't work on Waterfox. Then I took a look under ~/.waterfox and ~/.mozilla (I'm on linux) but none of them had any crashlog folders, just the browser profiles.
Could anyone let me know where I could find the crash logs? That way at least I could give you something to look at in finding what's causing the incessant crashes and I can't figure it out.

**Comment by grahamperrin** [comment]
Please let us have troubleshooting information. Copied from: 

about:support

**Comment by andoruB** [comment]
Here you go: https://hastebin.com/exubihojar.json

**Comment by grahamperrin** [comment]
Thanks. 

## about:crashes

<https://www.reddit.com/r/waterfox/comments/7cd3ri/instant_tab_crashes_today/dpqg33f/>: 

> about:crashes has been disabled for years, but may be worth changing that now.

https://firefox-source-docs.mozilla.org/toolkit/crashreporter/crashreporter/index.html#about-crashes 

### … on FreeBSD

Linux and Waterfox aside, for a moment: someone once gave me a good explanation for not enabling the crash reporting subsystem for Firefox on FreeBSD. I can't recall the details but it almost certainly involved the Tier-3 classification: 

- [Supported build targets - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Supported_build_configurations)

## Random crashes

Does 56.0.3 crash in normal mode? 

If so, then does 56.0.3 crash in safe mode?

### Recent top crashers for _Firefox_ 56.0.2 on Linux

Maybe of interest, if you get stuck: https://crash-stats.mozilla.com/topcrashers/?platform=Linux&product=Firefox&version=56.0.2&days=28&_facets_size=300

**Comment by andoruB** [comment]
I can't seem to be able to upgrade to 56.0.3. Will download it manually and try it out.

**Comment by andoruB** [comment]
Okay, upgraded to 56.0.3, and it doesn't seem to crash that much. But then again 56.0.2 stopped crashing in the last few days... Seems to be something time-related?

**Comment by grahamperrin** [comment]
Review time. Is this still an issue with Waterfox 56.1.0? 

Also: in Reddit there's an invitation to test 56.2.0 before general release.

**Comment by andoruB** [comment]
Sorry! I forgot to come back to this issue to let everyone know that I haven't had those random crashes in quite a while! Will close this issue for now.
