### ISSUE TITLE
Waterfox ESR

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#410]
I vaguely recalled reading that 56 is an extended support release, but it took me a **long** time to rediscover where I read it (using search engines, not Reddit, to search Reddit; and so on). 

From [Waterfox 55 Release (Windows, Mac, Linux and Android)](https://www.waterfoxproject.org/blog/waterfox-55.0-release-download) (2017-10-10) – for 55, not 56: 

> …
> ### Short Road Map 
> …
> - 56 will remain as ESR version for the foreseeable future, keeping updated with security patches.
> - In parallel, …

## Suggestions

In no particular order – assuming that 56 _is_ (as planned) an ESR: 

- add something to https://www.waterfoxproject.org/blog/waterfox-56.0-release-download
- maybe use ESR branding in the _About Waterfox_ dialogue for all future releases of 56.x
- when the staging site goes live, state the version number that is likely to be the first post-56.x ESR.

## Related

[PROPOSAL: Please turn Waterfox 56 into an ESR and give us a transition period! : waterfox](https://www.reddit.com/r/waterfox/comments/5ysn9e/proposal_please_turn_waterfox_56_into_an_esr_and/)

[When will there be an esr version of waterfox? : waterfox](https://www.reddit.com/r/waterfox/comments/6xewsz/when_will_there_be_an_esr_version_of_waterfox/)

From <https://www.reddit.com/r/waterfox/comments/7sjykj/firefox_58_released_whats_the_timetable_alex/dt5cjcx/>: 

> …
> - Utilise (Firefox) 60 ESR as the next base, …
> …

**Comment by Serkan-devel** [comment]
https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-352075604

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/412#issuecomment-365820134
