### ISSUE TITLE
PID in Tab

### ISSUE THREAD

**Issue by Scrxtchy** [BrowserWorks/waterfox#411]
I know this was taken out in 0e188cd

but the lack of it makes it a lot harder to forcekill in case the process crashes without recovery\
Both these tabs share a process, one's just been removed from the main window seconds before screencap
![image](https://user-images.githubusercontent.com/12771982/35480845-d32889ee-046b-11e8-890f-b326edc2cbed.png)

I usually just `taskkill /f /pid <x>` whatever process these run, which allows me to restore these tabs in a fresh process

![image](https://user-images.githubusercontent.com/12771982/35480914-370151a2-046d-11e8-8f5a-f59060b2825f.png)

There now exists no relatively easy way to kill these processes, you have to remove all tabs that aren't responding manually, then you won't hit an issue where the browser makes more tabs on this unresponsive process

Regardless that `about:performance` takes a considerable time to load pages, it does not contain those that are unresponsive. Otherwise using a process of elimination for webpages in that list, and striking out waterfox processes which PIDs do not appear works but oh god it's so horrid to do

**Comment by Scrxtchy** [comment]
I killed the process for ublock origin in the process :rofl:

**Comment by criztovyl** [comment]
An option for configuring the behaviour would be best, I think.

**Comment by Scrxtchy** [comment]
Yeah, I can definitely understand the need for it to be optional, since a majority of users would not even require it, since most the time it just comes down to a cosmetic thing

**Comment by grahamperrin** [comment]
Apologies: when I raised #340 I was not aware of some of the use cases. 

This screenshot (originally from something other than 340) was my first ever sight of ' - e10s' against a tab, and there was **no PID number**: 

![2017-12-30 10 24 15](https://user-images.githubusercontent.com/192271/34453494-a2cfea8c-ed4e-11e7-84e3-08b425fe1ead.png)

– if there had been a PID number in the shot, I would have thought more carefully about the issue.

**Comment by Scrxtchy** [comment]
Makes sense, The code for it would only print the PID if there were multiple processes 
```
if (tab.linkedBrowser.frameLoader &&
	Services.appinfo.maxWebProcessCount > 1) {
	label += " (" + tab.linkedBrowser.frameLoader.tabParent.osPid + ")";
}
```

**Comment by grahamperrin** [comment]
#538

**Comment by Peacock365** [comment]
The removal was intentional. WONTFIX, probably.

**Comment by Scrxtchy** [comment]
Could this me made a webextension 🤔
