### ISSUE TITLE
References to Firefox and Firefox ESR and their calendar(s)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#412]
From [Waterfox 56 Release](https://www.waterfoxproject.org/blog/waterfox-56.0-release-download) (2017-11-30): 

> … Waterfox will now remain at 56 for the time being, following the security releases of 59 ESR until it becomes End of Line (Q1 2019). …

https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates shows Firefox 59 – not Firefox _ESR_ 59 – in Q1 2018 

– 2019 is not yet tabled there. 

@MrAlex94 I guess that you need a couple of corrections to the blog post. 

----

Side note: where previously Mozilla's extended support for 52.x was scheduled to end with Firefox ESR 52.8, https://wiki.mozilla.org/index.php?title=RapidRelease/Calendar&diff=next&oldid=1184274#mw-diff-left-l39 there's now a 52.**9**. Allowing more time for users of Firefox ESR 52.x to transition to Firefox ESR 60.x.

**Comment by MrAlex94** [comment]
Yes, each ESR was pushed back by 1 release. Will update :-)

**Comment by grahamperrin** [comment]
Thanks … to clarify, is the plan for Waterfox ESR 56.x to follow security releases of Firefox ESR 5**2**.x until Firefox ESR 52.9 becomes end of life? 

----

Postscript: logically, I guess not. (We're already following security releases from versions of Firefox greater than 56.) 

It's that "59 ESR" and its EOL "Q1 2019" that need clarification.
