### ISSUE TITLE
Basic apache2 authentication no longer working

### ISSUE THREAD

**Issue by madelynseal** [BrowserWorks/waterfox#417]
Hello everyone,
I updated to 56.0.4 yesterday, and now basic authentication is no longer working for me. Apache returns this instead of any authentication popup at all:

# Unauthorized

This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

Edit 1: I have tried deleting the waterfox config and starting fresh, still having the same issue

**Comment by jbeich** [comment]
Probably regressed by d5cf1277b242 and can be fixed by mozilla/gecko-dev@38b712aab29c.

**Comment by madelynseal** [comment]
Ok thanks! I can't fully understand what that commit did, or why it was applied. Hopefully this get fixed soon as it is quite inconvenient while trying to access my web server..

**Comment by fenice2** [comment]
I can also confirm this is happening. Several of my local connections to DNS servers and some nginx sites are failing and also my connection to a seedbox fails with https but works with http. :( All of these work fine with the current version of Firefox.

**Comment by WagnerGMD** [comment]
You can't provide one example ? It's just a question.
What's (for you) the apache2 authentication ? You can't post a picture or an example (documentation links, code, etc) ? Do you have something else (not only this kind of message error) ?
We can't try without any example. And just because it's might help to understand your trouble (only HTTPS ?).

**Comment by fenice2** [comment]
This seems to have been resolved in the latest 56.0.4.1 update, as  far as I'm concerned my issues have gone.

**Comment by madelynseal** [comment]
Ok, seems the issue is fixed now. I tested it myself and I can authenticate properly now

**Comment by grahamperrin** [comment]
@WagnerGMD please forgive the terseness in this case. 

This particular issue was probably quickly recognisable _without_ an example in the opening post. Re: https://www.reddit.com/r/waterfox/comments/7uvihq/waterfox_5604_is_now_available_for_update_and/dto5dhw/ there was some mid-January background.
