### ISSUE TITLE
Waterfox download archive: outdated

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#418]
At https://www.waterfoxproject.org/dlarchive the most recent desktop version is 55.2.2. 

I guess that the list of files should include https://storage-waterfox.netdna-ssl.com/releases/osx64/installer/Waterfox%2056.0.3%20Setup.dmg and so on. 

Thanks

**Comment by grahamperrin** [comment]
Cross references: 

1. [Download repo for old versions : waterfox](https://www.reddit.com/r/waterfox/comments/7vh5m5/download_repo_for_old_versions/)
2. [Waterfox Download Archive versions : waterfox](https://www.reddit.com/r/waterfox/comments/7wa5uk/waterfox_download_archive_versions/)

**Comment by ip004** [comment]
MrAlex94, you should make every version of waterfox, including all previous versions, available for download at a webpage for waterfox archived versions like you used to have at this website "https://www.waterfoxproject.org/dlarchive". Firefox has one at "https://ftp.mozilla.org/pub/firefox/releases/". Some people like to be able to install whatever version they want to for troubleshooting and other reasons. Thanks.

**Comment by grahamperrin** [comment]
Meta, tracking: #582 

Taking hints from (not following) the download links from https://www.waterfoxproject.org/waterfox/new/?scene=1 it's possible to guess the URLs for some past releases. 

**Waterfox 56.2.0 Setup.dmg** for example at https://storage-waterfox.netdna-ssl.com/releases/osx64/installer/Waterfox%2056.2.0%20Setup.dmg

**Comment by grahamperrin** [comment]
At <http://web.archive.org/web/*/https://www.waterfoxproject.org/dlarchive> the most recent capture of the legacy archive page is: 

- http://web.archive.org/web/20180318063205/https://www.waterfoxproject.org/dlarchive (2018-03-18)

**Comment by grahamperrin** [comment]
Moved to https://github.com/grahamperrin/Waterfox/wiki

**Comment by leafcutterant** [comment]
The link to [Waterfox 56.2.5 portable](https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_56.2.5_English.paf.exe) is broken, please fix it.

**Comment by grahamperrin** [comment]
@leafcutterant above, it was written but not linked. 

Please subscribe to: 

- [404 not found on Windows portable download · Issue #792 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/792)
