### ISSUE TITLE
43.0.4: Crash

### ISSUE THREAD

**Issue by galmok** [BrowserWorks/waterfox#42]
While the latest release have been stable, this release (43.0.4) is not stable. I installed it today and it has crashed twice. I didn't even interact with it when the crashes happened.

This is what windows 7 x64 has recorded in the event log (two entries, 5 seconds apart):

Faulting application name: waterfox.exe, version: 43.0.4.5857, time stamp: 0x5697e7ec
Faulting module name: xul.dll, version: 43.0.4.5857, time stamp: 0x5697ead1
Exception code: 0xc0000005
Fault offset: 0x00000000063c1ae7
Faulting process id: 0x50d4
Faulting application start time: 0x01d15423173e1194
Faulting application path: C:\Program Files\Waterfox\waterfox.exe
Faulting module path: C:\Program Files\Waterfox\xul.dll
Report Id: 6beff1ab-c03a-11e5-88f3-c4346b5589da

Faulting application name: waterfox.exe, version: 43.0.4.5857, time stamp: 0x5697e7ec
Faulting module name: xul.dll, version: 43.0.4.5857, time stamp: 0x5697ead1
Exception code: 0xc0000005
Fault offset: 0x0000000006230a23
Faulting process id: 0x50d4
Faulting application start time: 0x01d15423173e1194
Faulting application path: C:\Program Files\Waterfox\waterfox.exe
Faulting module path: C:\Program Files\Waterfox\xul.dll
Report Id: 688acdab-c03a-11e5-88f3-c4346b5589da

I will say that have several windows open and many many tabs in each window. Used to work without issues (except having to restart when reaching approx 5-6 GB memory used).

**Comment by MrAlex94** [comment]
Could you try disabling hardware acceleration?

**Comment by galmok** [comment]
How do I do that?

**Comment by FunFrog-BY** [comment]
Same issue at Win 10. It crashes each 5-60 minutes, making my work almost impossible. Tried with HWA on and off - nothing changes. In last Firefox 64 all working fine. In previous Waterfox version all worked fine too. Seems like it depends on complexity of loaded pages. It can work fine if i`m just browsing web with one window, but when i`m using 7+ windows (i hate tabs) and there is open Wordpress site in realtime editing mode with visual composer - crash is inevitable.

**Comment by FunFrog-BY** [comment]
I tried your fix from twitter, but with no luck: i was browsing like 2 hours with no crashes, then i started to edit wordpress page with Visual Composer and got a crash in just one minute. If i can help you with some debugging info etc. - just let me know.

**Comment by kcwebguy** [comment]
I am getting crashes also. Always when working in the browser. I am also getting choppy scrolling and choppy page focus in fields. 

Sadly, this version of Waterfox is pretty much unusable as it is... =(

**Comment by FunFrog-BY** [comment]
Guys! FireFox 43.0.4 crashed too! But it worked much longer than Waterfox in the same conditions.

**Comment by kcwebguy** [comment]
I can't get go 10 mins without the browser crashing

**Comment by anr2me** [comment]
Same here, after upgrading to v43.0.4 Waterfox Portable crashes too often on my pc, even with only 1 window with 1 tab.

**Comment by MrAlex94** [comment]
Sorry for the late reply. [Here](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration) is how to disable hardware acceleration.

Waterfox 44.0 should phase out most of the crashes as MSVC12 was causing a bit of trouble together with ICL 16. The upgrade to MSVC14 should fix most of the compiler issues I've had as well.

**Comment by anr2me** [comment]
Hmm.. even with hw acceleration disabled, it still crashed when i tried to inspect element on GWD part of this page http://www.marjantrajkovski.com/html5-banners.html, feels like memory leaks.

**Comment by MrAlex94** [comment]
Could you try [this](https://storage-waterfox.netdna-ssl.com/releases/tests/Waterfox%2044.0%20Test%20Build%201.7z) test build to see if it resolves your crashing? I've fixed a header that ICL was generating bad code for and any time a piece of code gets executed that uses it, Waterfox would crash.

**Comment by FunFrog-BY** [comment]
First thing i'll do after waking up tomorrow.

**Comment by FunFrog-BY** [comment]
Doesn`t matter, had crash. Again.
If you need me to provide any debug information you need - just say what to do.

**Comment by MrAlex94** [comment]
What happened when you had the crash? Can you consistently reproduce it?

**Comment by FunFrog-BY** [comment]
Seems like FireBug affects crushes. I opened 8 WF windows with different sites for like 10 minites and all worked fine until i opened firebug on my twitter page - instant crash. Ok, restarting, restoring all windows, opening firebug on my twitter page - crash in few minutes. Restarting/restoring again, opening firebug - instant crash.
P.S. Wow wow wow now it crashed while being in background, when i was working in another app.

**Comment by MrAlex94** [comment]
Ah yes I see, I don't think Firebug has ever worked with Waterfox (I remember users reporting crashes with it a while ago). I'm going to install it and see if I can debug why. If you disable Firebug, do the crashes still occur (even randomly)?

**Comment by FunFrog-BY** [comment]
Already disabled all addons and checking, still no crashes. BTW firebug availability is a dealbreaker for me.
P.S. Yep, you are right. Without addons it`s rock solid.

**Comment by anr2me** [comment]
Before 43.0.4 i never had crashes even with firebug, are you sure it was firebug?
Have you tried disabling firebug only instead of all addons?

**Comment by kcwebguy** [comment]
I have used Firebug daily with Waterfox without issue. 

My problem now is that I can't use Waterfox at all. Constant crashing and memory drags. 

Seriously thinking through changing browsers.

**Comment by james-jaxeton** [comment]
list or reports to establish a pattern

https://github.com/MrAlex94/Waterfox/issues/35
https://github.com/MrAlex94/Waterfox/issues/9
https://github.com/MrAlex94/Waterfox/issues/2
https://www.reddit.com/r/waterfox/comments/44luan/thinking_of_switching_to_nightly_or_ff_beta/czr3abu
https://www.reddit.com/r/waterfox/comments/3vkvo0/wfox_seems_to_not_release_memory_allocated_memory/
https://www.reddit.com/r/waterfox/comments/3us1sg/waterfox_uses_about_6gb_of_ram_with_compare2steam/
https://www.reddit.com/r/waterfox/comments/3sdyrm/memory_issues/
https://www.reddit.com/r/waterfox/comments/3k40lz/does_waterfox_really_use_a_lot_of_memory/
https://www.reddit.com/r/waterfox/comments/3huuc6/waterfox_4002_test_build/cubd6hp
https://www.reddit.com/r/waterfox/comments/3huuc6/waterfox_4002_test_build/cuc2p3i
https://www.reddit.com/r/waterfox/comments/3fil8a/memory_leaks/
https://www.reddit.com/r/waterfox/comments/3e7qtf/memory_leaks_search_hijack/
https://www.reddit.com/r/waterfox/comments/39t69r/waterfox_3810_now_available/csarimt
https://www.reddit.com/r/waterfox/comments/39t69r/waterfox_3810_now_available/csasyhh
https://www.reddit.com/r/waterfox/comments/38ulf2/download_waterfox_3810_test_build/cry1lj6
https://www.reddit.com/r/waterfox/comments/2xamdv/test_drive_waterfox_360_here_leave_feedback_in/cozd1qe
https://www.reddit.com/r/waterfox/comments/35kubl/plugin_container_and_memory/
https://www.reddit.com/r/waterfox/comments/34m0lc/something_is_wrong_with_the_waterfox_build_3702/
https://www.reddit.com/r/waterfox/comments/321swu/memory_nom_nom_nom/
https://www.reddit.com/r/waterfox/comments/31k863/waterfox_3701_test_build_please_leave_feedback_in/cq3mc1l
https://www.reddit.com/r/waterfox/comments/30gnlw/memory_leak_waterfox_please_help_left_it_on/
https://www.reddit.com/r/waterfox/comments/2wv5g0/does_waterfox_never_release_the_memory/
https://www.reddit.com/r/waterfox/comments/2uz4cm/memory_limit/
https://www.reddit.com/r/waterfox/comments/2u2i3o/ram_usage_dont_lower_if_i_close_tabs/
https://www.reddit.com/r/waterfox/comments/2peath/high_memory_usage/
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/7120#post_24869024
forums.mozillazine.org/viewtopic.php?p=14240543#p14240543
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/3830#post_18147962
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6950#post_24255078
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6890#post_24035080
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6870#post_23933895
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6750#post_23634941
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6710#post_23601265
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6700#post_23595122
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6680#post_23580459
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6670#post_23569309
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6670#post_23566957
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6650#post_23550341
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6620#post_23517831
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6600#post_23496044
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6220#post_23105900
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6580#post_23467833
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6260#post_23132877
http://www.overclock.net/t/975626/waterfox-43-0-4-15-january-firefox-64-bit/6060#post_22804825

got tired of searching there are still more.

having memory issues from starting using waterfox long time ago. doing research on the issue yielded that not only am i not the only one it traces very far back and is linked to jemalloc been disabled.

before you claim addons as done in the past it happens without addons on a new profile on many computers but only in waterfox other browsers not have this issue.

going back through the old post was quite alarming as to how long you have know about the issue but not fixed it only made promises now with the above data hope can work it out.

**Comment by MrAlex94** [comment]
Hi James. I've replied on the thread you've posted on reddit. Anyway, @FunFrog-Belarus Funfrog have you had any more crashes since disabling add-ons? @kcwebguy, In the latest test build a fix for the frequent crashes in 43.0.4 has been applied. Have you tried out the test build?

**Comment by galmok** [comment]
I have tried the test version and it still crashes. I cannot say if the
crash frequency is the same or reduced.
Den 11/02/2016 16.58 skrev "Alex Kontos" notifications@github.com:

**Comment by galmok** [comment]
Is there anything new? Waterfox still crashes and now I am losing my windows and tabs as they are getting destroyed during the crash, i.e. the automatic crash backup file is being partially corrupted! Can't you re-release the previous version that was stable?

**Comment by anr2me** [comment]
@galmok you can download previous version from the archive https://www.waterfoxproject.org/dlarchive

**Comment by galmok** [comment]
@ANR2ME Thanks, but that archive doesn't seem to be up to date. I seem to remeber the previous version I used was 43.x. The latest in the archive is 40.x.

**Comment by anr2me** [comment]
@galmok  As i remember it goes from 40 to 43, and 43.x is where these crashes start occurring.

**Comment by FunFrog-BY** [comment]
Tried last version, had crash in 10 minutes even without actually using FireBug (but it was enabled). Please, @MrAlex94 , don`t give up on that problem, i really wanna use your browser.

**Comment by anr2me** [comment]
By last version, you mean 44.0.3 right? because I also had two crashes a few minutes after using it.

**Comment by FunFrog-BY** [comment]
@ANR2ME yep

**Comment by MrAlex94** [comment]
I think I've found the cause of the crash. It appears to happen during JavaScript garbage collection when using development tools (which may be what causes FireBug to crash as well). I'll see if I can fix it in v45.

**Comment by TropicSapling** [comment]
Not sure if it's the same issue as this one, but Waterfox crashes for me as well seemlessly randomly, I think it happens when I'm using Inspect Element though :/

**Comment by MrAlex94** [comment]
Yes I think I've found the cause of the crashes. Seems to happen when SpiderMonkey does some garbage collection.

**Comment by TropicSapling** [comment]
Hope you manage to fix it :)

**Comment by harl** [comment]
So, is there any way to.. prevent this from happening? or is v45 the only feasible solution?
Can we turn down the garbage collection or reduce its chances of causing the crash?
(Edit: Waterfox 44.0.3, Windows 8.1 x64)

**Comment by TropicSapling** [comment]
Haven't had this problem in a while now, so I suppose this is fixed now? Can't find any v45 though, guess you jumped directly to v47?

**Comment by MrAlex94** [comment]
So this should be fixed in the last few versions of WF.
