### ISSUE TITLE
Bookmark editing menu broken with Tree Style Tab addon

### ISSUE THREAD

**Issue by minus7** [BrowserWorks/waterfox#425]
Starting with 56.0.4 clicking bookmark icon or using ctrl-d fails to open the editing menu when using the Tree Style Tab addon. The browser console logs the following error:
```
TypeError: document.getElementById(...) is null[Learn More]  bookmarksOverlayEditable.js:155:3
	TSTBMEditable_initEditUI chrome://treestyletab/content/bookmarksOverlayEditable.js:155:3
	TSTBMEditable_init/StarUI._doShowEditBookmarkPanel chrome://treestyletab/content/bookmarksOverlayEditable.js:64:5
	showEditBookmarkPopup/< chrome://browser/content/browser-places.js:276:9
```

**Comment by grahamperrin** [comment]
Cross references: 

1. [Upgrade to 56.0.4 macOS kills bookmarking : waterfox](https://www.reddit.com/r/waterfox/comments/7uygw1/upgrade_to_5604_macos_kills_bookmarking/)
2. [Legacy Tree Style Tab 0.19.2017090601 versus bookmark popup and properties window in Waterfox 56.0.4 · Issue #1758 · piroor/treestyletab](https://github.com/piroor/treestyletab/issues/1758)
3. [Where's the "add bookmark" dialog? : waterfox](https://www.reddit.com/r/waterfox/comments/8n75e2/wheres_the_add_bookmark_dialog/)

**Comment by grahamperrin** [comment]
@oinkin hi, in the TST area your name was suggested. Any thoughts? 

TIA

**Comment by bege10** [comment]
Having the same issue on Windows 7 Professional 64 bit SP1.

Please, make it high priority. Thanks.

**Comment by bege10** [comment]
Found another extension for a tab tree which is compatible with Waterfox, but unfortunately not with TabMixPlus.
https://github.com/traxium/tabtree/issues/236

**Comment by oinkin** [comment]
@grahamperrin The TST fork I maintain is only for Pale Moon compatibility (and the barest possible amount to get by). Since this issue doesn't affect Pale Moon, and I know absolutely nothing about Waterfox, there's not too much I can do to help here. It looks like 56.0.4 is a pretty small release, so hopefully the Waterfox maintainer will have a good idea of what may have broken.

**Comment by oinkin** [comment]
If I had to guess, I'd say this might be related to fragment sanitization (commit d7f689c984bf15259ae5c882ab7d36919f3bbda8), as the failing code in the extension is inserting a fragment and then immediately attempting to reference it. I'm unclear on what exactly the safe version of this code might be, unfortunately.

**Comment by bege10** [comment]
Thank you very much.
When and in which Waterfox version will this patch be included?

**Comment by VVelda** [comment]
I've hoped, the bug is fixed with new Waterfox version. Bookmarks are somewhat crucial for the browsers :(

**Comment by bege10** [comment]
I am afraid that soon Waterfox will not make much sense any more because hardly any developer of legacy add-ons continues to maintain these add-ons :-(

**Comment by grahamperrin** [comment]
Cross reference [Treestyletab bookmark dialogue box issue : waterfox](https://www.reddit.com/r/waterfox/comments/94j4ey/treestyletab_bookmark_dialogue_box_issue/)

**Comment by JulioJu** [comment]
@oinkin, @bege10 @VVelda maybe take example of https://github.com/vimperator/vimperator-labs/issues/819#issuecomment-439677903

**Comment by happysmash27** [comment]
How has it taken months for me to notice this? Just now I am finding that I can't bookmark a page...
