### ISSUE TITLE
When mouse hover on history item, show URL in status bar

### ISSUE THREAD

**Issue by zcyzcy88** [BrowserWorks/waterfox#426]
History:
![image](https://user-images.githubusercontent.com/15178410/35845071-9f08568a-0b4b-11e8-8def-be8ac5c5147c.png)

Bookmarks:
![image](https://user-images.githubusercontent.com/15178410/35845577-02b3bd08-0b4e-11e8-99ab-f89390f91605.png)

**Comment by grahamperrin** [comment]
Nice catch. 

From my comment under Mozilla bug [765586 - Duplicate url tooltip when hovering on history sidebar](https://bugzilla.mozilla.org/show_bug.cgi?id=765586): 

> I like the use of the status bar; appearance is instantaneous. 
> 
> Less consistently, Firefox 58.0 makes _no_ use of the status bar when pointing at: 
> 
> - bookmarks in the library menu
> - historic items in the library menu
> - historic items in the history menu.

**Comment by zcyzcy88** [comment]
Also [RSS](http://www.feedforall.com/sample-feeds.htm):
![image](https://user-images.githubusercontent.com/15178410/35979466-62047ac8-0d23-11e8-9784-1f9d2469ee4c.png)
