### ISSUE TITLE
Waterfox 56.0.4 compatibility issue with the add-on Vimperator

### ISSUE THREAD

**Issue by JulioJu** [BrowserWorks/waterfox#428]
Hi 

As I've explained at https://github.com/vimperator/vimperator-labs/issues/819#issuecomment-363584398, Vimperator doesn't work well with Waterfox 56.0.4. It worked well with with Waterfox 56.0.4.

@devkev says [on  this comment](https://github.com/vimperator/vimperator-labs/issues/819#issuecomment-363635404)
« Okay, I had a quick look at this. The patch seems to only affect values set via innerHTML. Vimperator only has 2 places where it uses innerHTML, and both are to set it to an empty value.  ».

In Vimperator, it' seems that replace innerHTML  by unsafeSetInnerHTML() doesn't resolve the problem. 

I've bisected. As we can see below, the first bad bisect is  d7f689c984bf15259ae5c882ab7d36919f3bbda8.

I've reverted this commit, and Waterfox works well with Vimperator. All plugins who use innerHTML couldn't work, and the new setUnsaveInnerHTML seems not to be used. Maybe, it could be cool to revert this change on the official Waterfox ? 

```
$ git log --graph
* commit d7f689c984bf15259ae5c882ab7d36919f3bbda8 (refs/bisect/bad)
| Author: Alex Kontos <alex@waterfoxproject.org>
| Date:   Wed Jan 31 12:45:10 2018 +0000
|
|     Bug 1432966: Sanitize HTML fragments created for chrome-privileged documents.
|
* commit fd18ba788a2739088272360bf72fb693fdeb022f (refs/bisect/good-fd18ba788a2739088272360bf72fb693fdeb022f)
| Author: Alex Kontos <alex@waterfoxproject.org>
| Date:   Wed Jan 31 12:03:43 2018 +0000
|
|     Update Registry paths.
|
```

Thanks in advance !

And have good holidays @MrAlex94 :-).

Julio

**Comment by MrAlex94** [comment]
I think for now it's best to keep it sanitized. It's an important security change.

**Comment by JulioJu** [comment]
Fixed thanks https://github.com/vimperator/vimperator-labs/issues/819#issuecomment-439677903 ;-)
