### ISSUE TITLE
default browser

### ISSUE THREAD

**Issue by theQ23** [BrowserWorks/waterfox#429]
Version: 56.0.4.1
OS: Windows 7 Pro, Windows 7 Enterprise

i'm still getting the "set waterfox as default browser" on every load of the browser. In the control panel under default programs i don't' see a waterfox entry. I've tried uninstalling and reinstalling waterfox with the same results.

**Comment by grahamperrin** [comment]
[Detailed Info on the issue of being the Default Browser on Windows and what may still need fixing · Issue #384 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/384)

**Comment by MrAlex94** [comment]
I am aware of what may be the cause, related to the recent changes. Essentially it will be about missing registry entries and I’ve verified it with rudimentary tests. Will aim for a fix in 56 and add to the description in issue 384. Discus in 384 if you do wish.
