### ISSUE TITLE
WF56 compatibility issue with JS scripts for userChromeJS.xpi

### ISSUE THREAD

**Issue by bege10** [BrowserWorks/waterfox#430]
I am using the extension userChromeJS.xpi that allows to integrate JS scripts into FF/WF instead of/additionally to extensions. https://github.com/ardiman/userChrome.js
Many of them don't work with FF57+. That's one reason why I changed to WF.
With WF 56 some of the scripts I use don't work any more: reverttitlebar, ucjs_ExternerEditor.uc.js, SaveUserChromeJS.uc.js
The second one opens an external editor to fill out a text box in a web page like this one. Now the error console throws this error message: Error: unsafe CPOW usage forbidden
Looks like this is a step of Mozilla security before removing XUL extensions. Can this restriction be removed from WF?
With respect to the third one the error console throws: TypeError: contextMenu is null.
Have there been changes from WF55 to WF56 with respect to JS commands?

**Comment by jbeich** [comment]
Can you track it down via **mozregression** or `git bisect`?

**Comment by bege10** [comment]
No, sorry, I don't understand how to do that. And, actually, I came to Waterfox to have less work with search and fixes. This looks like a lot of time for understanding and testing. It's a pity.

**Comment by grahamperrin** [comment]
To clarify: did all three work with Waterfox 55?

> unsafe CPOW usage forbidden

[Unsafe CPOWs are about to be outlawed in browser code - Google Groups](https://groups.google.com/d/msg/mozilla.dev.platform/Nstdr9vsSWI/c7E2lhLoAwAJ) – that was two years ago, so I don't imagine a change between Waterfox 55 and 56 … 

… however, I'm not familiar with the code. 

In a different context, [CPOW error : waterfox](https://www.reddit.com/r/waterfox/comments/7vmxsi/cpow_error/)

**Comment by bege10** [comment]
I think it did, but I cannot tell that definitely, I didn't use it for a while. It works in latest FF ESR 52.
The others worked in WF55.
