### ISSUE TITLE
Support for AngularJS seems not to work

### ISSUE THREAD

**Issue by broadstairs** [BrowserWorks/waterfox#431]
I have an issue with my ISPs website which uses AngularJS but the site fails to load. Specifically does the Linux version of Waterfox support AngularJS? The windows version seems to work OK.

**Comment by criztovyl** [comment]
afaikt Angular works for me.

Maybe it's your ad/script blocker intervening?

A link to the site and/or console output (<kbd>CTRL</kbd><kbd>SHIFT</kbd><kbd>K</kbd>) also might be useful.

**Comment by broadstairs** [comment]
Well I have the error log from the browser when it fails. The issue is that you need an account with TalkTalk to test it because it's only the final part of the login process which displays the account details which fails. I do have a Windows PC with Waterfox and that works fine. Should add that restarting with all extensions disabled and it still fails.
[javaerrors-talktalk.txt](https://github.com/MrAlex94/Waterfox/files/1711603/javaerrors-talktalk.txt)

**Comment by broadstairs** [comment]
I just tested this on my Leap 42.3 laptop with the same version of Waterfox and it worked. So I copied over the profile directory (having renamed the existing one) and now when I access this ISP site it works. So the issue is something corrupt in the profile directory I was using. Question is what file in the profile would cause this error? Have you any ideas please?

**Comment by MrAlex94** [comment]
The file would be one of the SQLite files related to offline storage. Just seems as if it was an issue with localStorage corrupting the JavaScript file. [Here](https://davidjb.com/blog/2017/11/resolving-an-ns_error_file_corrupted-error-in-mozilla-firefox/) a little article here describing one possible way of alleviating the issue if it ever comes up again.
