### ISSUE TITLE
When zoom in, checkbox and radio pixelated

### ISSUE THREAD

**Issue by zcyzcy88** [BrowserWorks/waterfox#433]
Same as: https://github.com/MoonchildProductions/Pale-Moon/issues/1159

**Comment by jbeich** [comment]
On Linux mozilla/gecko-dev@165fab2f8596 may help.

**Comment by Peacock365** [comment]
FIXED BY https://github.com/MrAlex94/Waterfox/commit/6c9c2f06cc041d11f11f551ca2e01db0a0d89467

**Comment by MrAlex94** [comment]
Reverted https://github.com/MrAlex94/Waterfox/commit/d4b014b82aedf01f40a9b068aa92f0c1e40f737d. Needs more than just one patch.
