### ISSUE TITLE
Restore custom onBeforeUnload message

### ISSUE THREAD

**Issue by zcyzcy88** [BrowserWorks/waterfox#434]
Same as: https://bugzilla.mozilla.org/show_bug.cgi?id=641509

**Comment by grahamperrin** [comment]
Mozilla bug [641509 - onbeforeunload event does not display site-supplied text, only standard message](https://bugzilla.mozilla.org/show_bug.cgi?id=641509)

> VERIFIED WONTFIX

**Comment by zcyzcy88** [comment]
"Mozilla won't fix" is not a good reason to justify.

**Comment by grahamperrin** [comment]
Thanks, it wasn't to justify closure here. It was more to assist with speed reading (e.g. making the title etc. visible) at review times. 

#538
