### ISSUE TITLE
Staging site: invalid certificate, expired …

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#438]
> staging.waterfoxproject.org uses an invalid security certificate.
> 
> The certificate expired on 11 February 2018, 21:46. The current time is 13 February 2018, 22:04.
> 
> Error code: `<a id="errorCode" title="SEC_ERROR_EXPIRED_CERTIFICATE">SEC_ERROR_EXPIRED_CERTIFICATE</a>`
> 
> OK

**Comment by MrAlex94** [comment]
Thanks, seems the nginx server didn't restart properly, even thought the cert was renewed (so was using an old one).

Fixed now.

**Comment by grahamperrin** [comment]
@MrAlex94 according to Waterfox 56.2.1 on a Mac, the certificate expired 2018-05-18 12:11. 

Meta, tracking: #582
