### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#439]
### Specifics

The specific list of features at https://github.com/MrAlex94/Waterfox/blob/master/README.md#features is probably a little outdated. 

From <https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-363843831>: 

> … XUL compatibility, its the USP …

– and so on. 

(Compatibility is a selling point, but I don't see XUL compatibility as the sole unique selling point.)

### Non-specific

More broadly – non-specifically – we have phrases such as: 

> … ethos of … customisation and choice, while staying up to do date with the rapidly evolving browser landscape. …

That's probably a good fit for the preamble at https://github.com/MrAlex94/Waterfox/blob/master/README.md – currently a single paragraph, might be improved with some use of bullet points. 

## Long term (future)

I guess: 

1. shift _about Waterfox_ content into https://staging.waterfoxproject.org/about/ 
2. a highly condensed `README.md` with reference to an `/about/` URL.

**Comment by MrAlex94** [comment]
Good suggestions, 56.1 is a big improvement of everything, including the README in the repo, which I may include instructions with as well - or maybe a separate BUILD.md.

**Comment by grahamperrin** [comment]
Meta, tracking: #582
