### ISSUE TITLE
Waterfox should show up as a separate installation from Firefox in Default Programs

### ISSUE THREAD

**Issue by jnm2** [BrowserWorks/waterfox#44]
Currently Waterfox shows up with the name Firefox in Default Programs, with the wrong icon. There is no way to set defaults to the actual Firefox installation.

![Screenshot of Default Programs](http://i.imgur.com/ws8qj5p.png)

**Comment by ROCKNROLLKID** [comment]
On mine, it shows up on Waterfox, so I am guessing this issue is fixed.

**Comment by jnm2** [comment]
@ROCKNROLLKID does yours show both Firefox and Waterfox side by side here? If so it must be fixed.

**Comment by ROCKNROLLKID** [comment]
Just shows up as Waterfox. See here: https://snag.gy/8pKn3y.jpg

**Comment by jnm2** [comment]
This issue is about when you have both Firefox and Waterfox installed though, so I'm not 100% sure that your current setup is relevant.

**Comment by MrAlex94** [comment]
@jnm2  Do you still have this issue?

**Comment by jnm2** [comment]
Yes I do, or a very similar one. Now instead of the Waterfox icon and the Firefox name, I have the Firefox icon and the Waterfox name. Maybe it depends which order I installed them.

In any case, there should be _two_ separate entries in this list that correspond to `C:\Program Files\Waterfox\waterfox.exe` and `C:\Program Files\Mozilla Firefox\firefox.exe`. It seems they are being registered as one and interfering with each other.

![Screenshot of Default Programs](http://i.imgur.com/mlpO8JT.png)

**Comment by MrAlex94** [comment]
A fair few things have changed in Waterfox now to differentiate it from Firefox. Do you still have this issue?

**Comment by jnm2** [comment]
That control panel UI is not (easily) accessible in Windows 10.0.16299.19, and in the replacement UI Firefox and Waterfox now show up separately.
