### ISSUE TITLE
Language pack locale associations

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#440]
For example: 

- `langpack-kn@waterfox` appears to be wrongly associated with a US locale when viewed with Simple Add-on Manager. 

![2018-02-15 04 57 50](https://user-images.githubusercontent.com/192271/36241354-ae0b6c1c-120d-11e8-8789-7a5e936d848a.png)

![2018-02-15 05 02 12](https://user-images.githubusercontent.com/192271/36241510-b02fb72c-120e-11e8-944b-09e017236fc5.png)

A bug with the extension? Or does the extension reveal a bug in Waterfox? 

Side notes: 

- I assume that in this context, _kn_ is Kannada https://en.wikipedia.org/wiki/Kannada
- as a comparison (not to be installed with Waterfox), Mozilla offers a [Kannada (IN) Language Pack](https://addons.mozilla.org/addon/kannada-in-language-pack/) – that's IN, not US
- re: https://www.reddit.com/r/waterfox/comments/7ww1ot/waterfoxbrowserfeatures_lots_of_languagepack_xpi/du51k4i/ I know to not expect a file for _English (US)_
- the misrepresentation of characters e.g. ಇಂಗ್ಲೀಷ್ is a separate issue, platform-specific. 

## Primary test environment

[Simple Add-on Manager](https://addons.mozilla.org/addon/simple-add-on-manager/) 1.1.3

Waterfox 56.0.4_3 on FreeBSD-CURRENT, 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uname -v
Thu 15 Feb 2018 04:52:54 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info waterfox | grep Version
Version        : 56.0.4_3
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% 
```

### Secondary test environment

Reproducible with Simple Add-on Manager alone on Waterfox 56.0.4.1 on Mac OS X 10.9.5.

**Comment by jbeich** [comment]
Can you report to Mozilla? Even Firefox 58.0.2 ships kn.xpi as `ಇಂಗ್ಲೀಷ್ (US) Language Pack`, see [toolkit/defines.inc](https://hg.mozilla.org/l10n-central/kn/file/tip/toolkit/defines.inc)

**Comment by grahamperrin** [comment]
Thanks for the direction 👍 

Mozilla bug [1438632 - Kannada kn locale wrongly associated with US](https://bugzilla.mozilla.org/show_bug.cgi?id=1438632)
