### ISSUE TITLE
(Mozilla 1118086) e10s in Waterfox 56.0.4.x: multi-process versus performance of the 'Select Device' menu/form/drop-down list at samsung-updates.com

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#442]
Origin: https://redd.it/7yglsz

## Bugged

The menu (1,312 nodes?) to the left at: 

- http://samsung-updates.com/device/?id=SPH-L720&details=Galaxy_S_4_Sprint

Reproduced with Waterfox 56.0.4_4 on FreeBSD-CURRENT.

**Comment by grahamperrin** [comment]
New profile, first run, safe mode, multi-process enabled: 

- after loading the page, a delay of around six seconds between a click on the menu icon and appearance of the the menu. 

Normal mode, multi-process disabled: 

- no perceptible delay. 

Normal mode, multi-process enabled: 

- first attempt to restore the tab resulted in a crash
- second attempt, another crash
- third attempt, after loading the page, a delay of around four seconds between a click on the menu icon and appearance of the the menu. 

(In my case, I'm tempted to treat the crashes as negligible.)

**Comment by AjvarXX** [comment]
I found it checking info for my phone but this trouble certainly exists on higher address domain without the need of preceded specific device page load:

http://samsung-updates.com/

I also checked on FF56 x86 new profile right now - same problem. Wonder if it's due to long list in that menu/form but still this huge lag deserves for further investigation, probably on bugzilla (Graham, Alex?).

**Comment by grahamperrin** [comment]
## Firefox 

### 5.8.0.2

`browser.tabs.remote.force-disable` `true`: 

- appearance of the menu is instantaneous. 

Multi-process enabled: 

- a _split-second_ delay before appearance of the menu. 

### Bugzilla@Mozilla

https://bugzilla.mozilla.org/buglist.cgi?list_id=14018348&short_desc_type=allwordssubstr&short_desc=e10s%20menu&resolution=---&classification=Client%20Software&query_format=advanced&component=General&product=Firefox finds a handful of bugs, none of which are similar to this issue 442. 

[1063169 - (e10s-perf) tracking performance issues with e10s](https://bugzilla.mozilla.org/show_bug.cgi?id=1063169) refers to numerous bugs. Speeding through the page source, I can't see anything like this issue. 

----

I'll run this comment past Mozilla's `#firefox` channel, ask whether they'd like it reported as a performance issue. 

(With more than a thousand menu items, I guess that it'll be edge case.)

----

Postscript, note to self: I didn't find 1118086 below because it's _Core_, and because my search terms included _menu_ and _form_ (neither _drop-down_ nor _list_).

**Comment by grahamperrin** [comment]
## Cross reference

Via <https://mozilla.logbot.info/firefox/20180218#c14323990>, thanks to philipp: 

- Mozilla bug [1118086 - [e10s] There is a delay for about 1 seconds to display <select> drop-down list with 1600+ items](https://bugzilla.mozilla.org/show_bug.cgi?id=1118086)

**Comment by MrAlex94** [comment]
Thanks for all the research into this. Wonder if it’s worth implementing the [WIP](https://bugzilla.mozilla.org/show_bug.cgi?id=1421229) patch or wait until it’s properly fixed? The bug doesn’t seem to have moved in a month though.

**Comment by AjvarXX** [comment]
@MrAlex94 I would like to beta test this fix for sure. Mozilla team is insanely slow fixing something if it 'works' without a fix anyw. TBH I won't be surprised if it takes another year for them considering it's way less of a problem on latest FF builds.
Hmmm, on the other hand assignee clearly sais there i work to do further.

**Comment by grahamperrin** [comment]
I'm fairly ambivalent, not bitten by the bug in my environment. 

Less personally, I should be wary of anything that might decrease accessibility.

**Comment by MrAlex94** [comment]
I've encountered it when selecting from a list of countries for example. While it's not critical, it's still a good quality of life improvement. I'll do a beta release of 56.1 anyway, and can be tested with that. If it doesn't work/breaks things I can revert the patch.

**Comment by MrAlex94** [comment]
I investigated this bug further - there are **a lot** of patches collectively made to fix this, which I think all made it to Firefox 59. I'm testing out the [WIP patch](https://bugzilla.mozilla.org/attachment.cgi?id=8934969&action=diff), but so much is changing in it!

**Comment by grahamperrin** [comment]
#538
