### ISSUE TITLE
Windows .URL files have unnecessary data in them

### ISSUE THREAD

**Issue by Yay295** [BrowserWorks/waterfox#444]
When you create a .URL file on Windows with Waterfox (and Firefox), the file contains

```
[InternetShortcut]
URL=https://github.com/MrAlex94/Waterfox
IDList=
HotKey=0
IconFile=C:\Users\Yay295\AppData\Local\Waterfox\Profiles\4zcdwbu5.default\shortcutCache\hcb2r0oXRbfkM99UuoGNbg==.ico
IconIndex=0
```

However, only the first two lines are actually necessary. By default, Windows uses the icon of the default web browser as the icon for all .URL files. The IconFile and IconIndex attributes that Waterfox adds changes this so that it uses Waterfox's cached copy of the webpage's icon instead (or a lower-res version of Waterfox's icon if the webpage doesn't have one).

I can see how this is useful in that having the URL link be the webpage's icon makes it easy to see what site it links to, but it's also fragile in that if the cached icon is ever moved or deleted, the file just shows a blank "page" icon instead, not even degrading to show the proper icon for a URL file (as has happened to all of the URL files I'd made with Firefox before switching to Waterfox). It also hides the fact that it is a URL file, as Waterfox's logo is much more recognizable to me than that of some random website I happened to create a link to.

I would appreciate it if Waterfox would stop adding this extra data to URL files, or at least give a way to disable it. I don't know what the other two attributes do, but I've never seen them have anything set so I'm not sure Waterfox is using them anyways.

as a note: URL files created with Chrome only have the first two lines

**Comment by Obscuris** [comment]
Unfortunately this seems to be a internal _Firefox-thing_ - though would be neat if that could be changed somehow.

**Comment by jbeich** [comment]
Can you try setting `browser.shell.shortcutFavicons` to **false** in `about:config`? See
https://github.com/MrAlex94/Waterfox/blob/79492ecca4785f362537ddca9db3feeb2b29d197/widget/windows/nsDataObj.cpp#L1217-L1220

**Comment by Yay295** [comment]
That does seem to have done it. Thanks!
