### ISSUE TITLE
These config should be set by default, avoid URL phishing

### ISSUE THREAD

**Issue by zcyzcy88** [BrowserWorks/waterfox#447]
```js
user_pref("browser.urlbar.trimURLs", false);
user_pref("network.IDN_show_punycode", true);
```

**Comment by jbeich** [comment]
- [trimURL code](https://searchfox.org/mozilla-central/rev/9a8d3f8191b1/browser/base/content/utilityOverlay.js#938-964) is mainly about `http://` which Mozilla [may mark](https://www.mail-archive.com/dev-platform@lists.mozilla.org/msg24839.html) as insecure, anyway
- Always showing punycode is a usability trade-off akin to turning off JS by default

**Comment by jbeich** [comment]
Also see mozilla/gecko-dev@b0369ebbca69

**Comment by grahamperrin** [comment]
Also [Set network.IDN_show_punycode to true as default. · Issue #261 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/261) (2017-11-04)

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/bb8aa754a7ec4da02587ec046700afc2e127f0d1
