### ISSUE TITLE
I'm not sure how to describe this, but text and icons are everywhere

### ISSUE THREAD

**Issue by SwadicalRag** [BrowserWorks/waterfox#45]
example: 
![aaa](http://i.imgur.com/q0D11Yb.png)

Also, [this](https://github.com/MrAlex94/Waterfox/issues/15) is still an issue for me, and I'm running waterfox on the same computer.

I'm running on windows 10 pro.

**Comment by Xial** [comment]
I'm also on Win10Pro, and can't reproduce this with the default theme.

![not-reproduced](https://cloud.githubusercontent.com/assets/31123/12853713/7ba2f076-cbea-11e5-8a00-d18cf0878326.png)

I noticed that your tabs are squared off, and your back and forward buttons aren't the default versions: Are you using a full theme called Simple White, by any chance?

**Comment by SwadicalRag** [comment]
my god

i can't thank you enough. 

I could've sworn I hadn't had any themes selected. All's normal now, I've been living with this for 6 months now :weary: 

I'll go ahead and close #15 as well.

D:
