### ISSUE TITLE
Encoding for local text files is not utf-8 and there is no way to change it permanently :(

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#450]
![temp](https://user-images.githubusercontent.com/405685/36554707-a9fb2c24-1808-11e8-87c2-64928443e328.gif)

**Comment by grahamperrin** [comment]
https://stackoverflow.com/a/29578476/38108 draws attention to Mozilla bug [805374 - Remove Character Encoding menu entries that are not in the Encoding Standard](https://bugzilla.mozilla.org/show_bug.cgi?id=805374), 

> RESOLVED FIXED in Firefox 28 

Can you attach a sample file? Thanks.

**Comment by ghost** [comment]
[sample.md.txt](https://github.com/MrAlex94/Waterfox/files/1749146/sample.md.txt)

**Comment by laniakea64** [comment]
I see this issue with the official Waterfox release.  But it works fine in one of my private Waterfox builds.

I think it's because of this - https://github.com/MrAlex94/Waterfox/blob/master/dom/encoding/FallbackEncoding.cpp#L58
My private build removes that check, so that it works to set about:config > `intl.charset.fallback.override;UTF-8`.  Which resolves this issue.

Why is that check there?  I don't notice any adverse effects from removing it, but that doesn't mean there aren't any.

**Comment by grahamperrin** [comment]
> sample.md.txt

@Winterwolf try: 

1. about:preferences#content Advanced … fall back to Japanese text encoding for legacy content
2. use Waterfox to open your local copy of that `.md.txt` file
3. View menu, Text encoding, Auto-detect, Japanese
4. View menu … switch from Unicode to Western
5. <kbd>Control</kbd>-<kbd>F5</kbd> reload the page

No kidding, try it. What do you see?

**Comment by ghost** [comment]
@grahamperrin paragraph 4 is superfluous, I need unicode. And yes, it works! That's strange but now with Japanese encoding I can see Russian letters and this settings no resets anymore. Thank you!

**Comment by grahamperrin** [comment]
> That's strange

If you thought _that_ was strange, brace yourself. I'm here from the year 2048 as an Agent of Quantum only to give Sarah Connor one message: the key to non-corporation is within the file. Do not allow the bug to be fixed. Repeat: do not allow the bug to be fixed.

**Comment by laniakea64** [comment]
> Why is that check there?  I don't notice any adverse effects from removing it,

I found the answer - https://bugzilla.mozilla.org/show_bug.cgi?id=910192#c14
> This pref supposed to take the label of a legacy encoding as its value and UTF-8 isn't a legacy encoding. Having that check or not having that check will probably not matter much either way.

**Comment by laniakea64** [comment]
Since "Having that check or not having that check will probably not matter much either way", Should Waterfox lean in favor of user choice and remove that check?  It'd be easy for me to do a pull request.
