### ISSUE TITLE
Bug -- Widevine Netflix Linux error will not work

### ISSUE THREAD

**Issue by ryanmusante** [BrowserWorks/waterfox#451]
I am using Manjaro Linux with kernel 4.15 and Waterfox will not work on Netflix website:

Error F7702-1003 in Netflix
Widevine version 1.4.8.1008 in Add-ons
"general.useragent.compatMode.firefox" is set to true in about:config

**Comment by grahamperrin** [comment]
Please subscribe to [Netflix does not work on Waterfox 56 · Issue #316 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/316). Thanks.

**Comment by ryanmusante** [comment]
roger that.
