### ISSUE TITLE
Bug -- Connection reset by peer message during exit

### ISSUE THREAD

**Issue by ryanmusante** [BrowserWorks/waterfox#453]
On exiting browser each time logs show this message, what is the cause?

`[Parent 15456] WARNING: pipe error (57): Connection reset by peer: file /home/build/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353`

**Comment by grahamperrin** [comment]
https://dxr.mozilla.org/mozilla-release/source/ipc/chromium/src/chrome/common/ipc_channel_posix.cc#353

A search finds https://askubuntu.com/q/959290/25036 and various other scenarios in which the warning may occur. 

From <https://github.com/netblue30/firejail/issues/1576#issuecomment-331971048>: 

> …  pretty sure this is a general Firefox issue. It does seem to just be a warning, and not have any actual impact (older versions apparently seemed to crash). …

**Comment by hawkeye116477** [comment]
I had similar error message on waterfox-kde when I want to print something and I was on e10s mode.
This is bug 1382942 -> `https://bugzilla.mozilla.org/show_bug.cgi?id=1382942`, patch from attachment helps.
