### ISSUE TITLE
Error uploading documentation in netacad.com

### ISSUE THREAD

**Issue by 97carmine** [BrowserWorks/waterfox#454]
Hi

I am currently studying the CCNA, the problem I have is that it is time to upload the exercises to the platform.

I enclose the documents, select the option Deliver task, and stay as shown in the photo:

![imagen](https://user-images.githubusercontent.com/6619414/36741346-2177969a-1be5-11e8-8739-3404a838cdc7.png)

It is somewhat uncomfortable because I have to use another browser to upload the exercises

Regards

**Comment by grahamperrin** [comment]
What's the user agent string? <https://udger.com/resources/online-parser> can tell you. 

If you'd like to experiment with a different string, my preferred extension for site-specific and domain-specific strings is: 

- [Custom UserAgent String](https://addons.mozilla.org/addon/custom-user-agent-revived/) also known as _Custom User-Agent (Revived)_.

**Comment by 97carmine** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4

**Comment by 97carmine** [comment]
The problem has been solved in version 56.1.0 (tested in Windows), you can upload documents without problems to netacad.com
