### ISSUE TITLE
webex UI issues

### ISSUE THREAD

**Issue by theQ23** [BrowserWorks/waterfox#455]
Waterfox 56.0.4.1
windows 7 x64

If you go to https://www.webex.com/pricing/index.html then click on any of the buy items a few times to add them to your cart. If you try to update the quantity to 1 and update, it goes back to the original number.
![image](https://user-images.githubusercontent.com/16393735/36866955-c5a8f2d6-1d61-11e8-86a4-260d972cb367.png)

Is just me or others experienced this?

**Comment by grahamperrin** [comment]
My first click on one of the three _Buy now_ buttons (the one to the left, if I recall correctly) led to a **System Down** alert. Visually similar to the alert that was captured in January 2016, https://web.archive.org/web/20160129094429/https://signup.webex.com/US/components/common/systemdown.html

----

The code for Waterfox is close enough to code for Firefox for me to assume that you have an issue at your end, or with Cisco's service (not with Waterfox). Maybe poll readers at https://www.reddit.com/r/waterfox/
