### ISSUE TITLE
I got an issue

### ISSUE THREAD

**Issue by ldrancer** [BrowserWorks/waterfox#456]
can you make it where i dont have to enable flash on every page?  say for example, nsmb.ytmnd.com i have to enable flash for every *.ytmnd.com page

opera has an option to enable flash on pages, like *.ytmnd.com  or *.anythingelse.net
and it will enable every other site to enable flash on. 
http://drinkbleachemo.ytmnd.com/
http://lexownshubbard.ytmnd.com/
all have to be enabled, individually, when the whole list of ytmnd sites are accessed through ytmnd.com.  i dont know how flash is working on other sites as i havent went to one that uses it yet and rechecked or bothered to pay attention.  but if i have flash enabled, it seems i would know i want to use it.  

can you make an option to enable it?

**Comment by grahamperrin** [comment]
Try: 

Tools menu ▸ Add-ons ▸ Plugins ▸ Shockwave Flash ▸ Always activate

## Related

A Mozilla knowledge base (KB) article, [Always activate plugin (not recommended): …](https://support.mozilla.org/kb/why-do-i-have-click-activate-plugins#w_when-is-it-okay-to-activate-a-plugin) in _Why do I have to click to activate plugins? | Firefox Help?_

**Comment by ldrancer** [comment]
it is on that, i unchekced the block dangerous content.  it always says, this content may slow down firefox click here, click.. box at the top asks me now or every time.  every time.  but it only activates every time on that site, wildcard.ytmnd.com  if it would change to for example.. not that this site makes it surls like this,
ytmnd.wildcard.com  it would activate all the wildcards.  yep yep just checked newgrounds.
seems firefox didnt care.  opera lets you put a wildcard in to the exception box, and you can make the wildcard anywhere.  

but water/fox is blocking that crap
