### ISSUE TITLE
Devtools dark theme makes scrollbars invisible

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#459]
Waterfox 56.0.4.1, new profile
Xubuntu 16.04 64-bit
Greybird GTK theme

**Steps to reproduce:**

1) on the Waterfox blog page that opens at startup, open the devtools
2) open the Style Editor.  Notice there are vertical and horizontal scrollbars.
3) Open devtools settings and change the devtools theme to Dark
4) Go back to the Style Editor

**Expected results:** vertical and horizontal scrollbars visible in the Style Editor

**Actual results:** Style Editor's vertical and horizontal scrollbars are invisible.  They are still there though - clicking/dragging the mouse where the scrollbars should be, does produce expected scrollbar behavior.

**Comment by grahamperrin** [comment]
> … Waterfox blog page …

Can you reproduce the issue elsewhere? 

There may be something unusual about that page, it features in a bug that involves an experimental legacy extension: 

- [Scrollmap 0.9 disappears after loading www.waterfoxproject.org/blog/ · Issue #15 · vovcacik/scrollmap](https://github.com/vovcacik/scrollmap/issues/15)

– as far as I can tell, not an issue with any Waterfox blog page at the staging site.

**Comment by laniakea64** [comment]
Yes, I can reproduce it no matter what page I'm on when I open devtools.

In case it wasn't clear, this affects **all** scrollbars in the devtools, and only the scrollbars within devtools.  Other scrollbars are not affected.

**Comment by grahamperrin** [comment]
Sorry! I misread. You were clear. I thumbed down my own comment :-)

**Comment by jbeich** [comment]
Can you attach a screenshot? Maybe you didn't look [hard enough](https://bugzilla.mozilla.org/show_bug.cgi?id=1100622).

**Comment by laniakea64** [comment]
Screen shot of light theme -
![waterfox-devtools-light](https://user-images.githubusercontent.com/16628411/36942232-59a0571a-1f3b-11e8-96e3-6d945aa2f85e.png)

Screen shot of dark theme -
![waterfox-devtools-dark](https://user-images.githubusercontent.com/16628411/36942233-643c0ade-1f3b-11e8-8d98-5989a76fec73.png)

**Comment by laniakea64** [comment]
It's GTK theme dependent.  With Adwaita GTK theme the scrollbars are visible, although hard to see.

**Comment by laniakea64** [comment]
In Xubuntu **18.04** with Greybird GTK theme, the devtools dark theme scrollbars are visible.

I think this may not be a Waterfox issue.  Sorry about this.
