### ISSUE TITLE
cs9.wac.phicdn.net, what is it?

### ISSUE THREAD

**Issue by memorable111** [BrowserWorks/waterfox#460]
as you can see here https://ibb.co/gfHAyS
Waterfox keeps sending and receiving packets from cs9.wac.phicdn.net, which is apparently a domain owned by verizon

why and what is it doing?

**Comment by grahamperrin** [comment]
Not a Waterfox issue, as far as I can tell: 

- [what are these network requests by Firefox from the blank startup page? : firefox](https://www.reddit.com/r/firefox/comments/62ow86/what_are_these_network_requests_by_firefox_from/) 
- [list of firefox ocsp servers · Issue #73 · pyllyukko/user.js](https://github.com/pyllyukko/user.js/issues/73)

… and so on. 

[Online Certificate Status Protocol - Wikipedia](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol)

**Comment by Atavic** [comment]
>*.wac.phicdn.net HTTP Used by the Verizon Content Delivery Network to perform Windows updates

See: https://docs.microsoft.com/en-us/windows/configuration/manage-windows-endpoints-version-1709

**Comment by grahamperrin** [comment]
Review time. Close this?

**Comment by Atavic** [comment]
It's an ocsp needed connection for validating https.

**Comment by grahamperrin** [comment]
Thanks, that's already understood from <https://github.com/MrAlex94/Waterfox/issues/460#issuecomment-371236964> above. 

Is there a need for Waterfox to change?

**Comment by Atavic** [comment]
I agree with your previous reply: https://github.com/MrAlex94/Waterfox/issues/460#issuecomment-371236964
