### ISSUE TITLE
Secure connection failed

### ISSUE THREAD

**Issue by iimpulse9** [BrowserWorks/waterfox#461]
When trying to open https://www.quaddicted.com it gives the error message "secure connection failed."

This doesn't happen with regular Firefox or even Waterfox mobile. Inspecting the certificate looks like it's valid.

I was unable to add it as an exception in Waterfox as when requesting the certificate using the above URL it was unable to retrieve it.

**Comment by grahamperrin** [comment]
Probably a duplicate. Please see: 

1. the three issues linked from <https://www.quaddicted.com/forum/viewtopic.php?pid=2583#p2583> under _Report website bugs here / Quaddicted.com Discussion / Quaddicted.com Forum_
2. [Secure Connection Failed : waterfox](https://www.reddit.com/r/waterfox/comments/7y3ss3/secure_connection_failed/), which led to that forum post.

**Comment by iimpulse9** [comment]
You're correct. This appears to be the same issue.

Should I close it?

**Comment by grahamperrin** [comment]
You can, if you like, if it's the same issue. Thanks.
