### ISSUE TITLE
Waterfox library - Moving bookmarks alters modification-time

### ISSUE THREAD

**Issue by Obscuris** [BrowserWorks/waterfox#462]
Since v53 (tested 53.0.3) of Waterfox moving bookmarks directly from the star-icon or within library to another directory/folder changes the 'last modified' date/time of the bookmark itself (and not just the folders timestamp). In the current Firefox ESR version this can't be observed, so that's probably not the default Firefox time-handling of moved/relocated bookmarks.

**Comment by grahamperrin** [comment]
With Firefox 58.0.2 I see the date change when, for example, there's a move from the bookmarks toolbar to a subdirectory. 

I asked in <irc://irc.mozilla.org/#sync>:

> when the modification date of a bookmark changes in response to a move of a bookmark (e.g. to a subfolder), is that change of date required for sync purposes?

– the answer was _yes_.

**Comment by Obscuris** [comment]
Isn't Waterfox supposed to be based on Firefox 56 ESR release? Also wondering how it was working the years before and is working now in the current ESR version (without changing the date). In the places.sqlite database every bookmark has its GUID, parent (subfolder), position and syncStatus value, so there's no point to change their modification time, probably just to let Sync basically handle bookmarks like a crude file syncing-tool, for whatever 'reasonable' changes they have done to make this retrogression necessary.

**Comment by laniakea64** [comment]
> Isn't Waterfox supposed to be based on Firefox 56 ESR release?

Waterfox is based on Firefox 56.  Firefox ESR is based on Firefox 52.

In Firefox 56, I do see the modification date change.

**Comment by Obscuris** [comment]
Thanks for checking again with appropriate Firefox version, just looked again as in the blog actually only 'security releases of 59 ESR' are mentioned. Nonetheless is it possible and feasible anytime soon to change it back to the 'original' behaviour of Firefox 52 ESR, or would that be too much effort?

**Comment by grahamperrin** [comment]
Also worth following: 

- Mozilla bug [1433177 - [Meta] Enable structured bookmark application by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1433177)

– some of the linked bugs are RESOLVED FIXED in Firefox 60.

**Comment by grahamperrin** [comment]
#538

**Comment by Lorienna** [comment]
<blockquote>moving bookmarks directly from the star-icon or within library to another directory/folder changes the 'last modified' date/time of the bookmark itself (and not just the folders timestamp)</blockquote>

I've done a little testing against Firefox builds, and the change is associated with the following commits:

- https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=3ce8e7ccf045dafe326157cbd29af2eeebf5518e&tochange=75671ee1ac40b5648898a66e6d63a9afd1ac469b

- [Bug 1258127 - Track bookmark sync changes in Places](https://bugzilla.mozilla.org/show_bug.cgi?id=1258127)

**Comment by Obscuris** [comment]
Since it won't get resolved specifically within/for Waterfox, guess the only way to change it is to report this at Firefox-Bugzilla, so hopefully someday it will be implemented with a regular Firefox release? Or is the timestamp-change required/necessarily related to the 'syncChangeCounter'-update of the 'moz_bookmarks' table?
