### ISSUE TITLE
~/Library/Caches/Mozilla/updates/Applications/Waterfox/ (and other data that's cached on Mac OS X)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#463]
On Mac OS X, 

- `~/Library/Caches/Mozilla/updates/Applications/Waterfox/`

– is created by Waterfox 56.0.4.1. 

----

I don't imagine any problem arising from use of that path but for tidiness, a future version of Waterfox might use e.g.: 

- `~/Library/Caches/org.waterfoxproject.waterfox/profiles/`
- `~/Library/Caches/org.waterfoxproject.waterfox/updates/`

– and so on. 

## References and side notes

`~/Library/Caches` in Mozilla bug [291033 - Enable support for profile temp directory on local filesystem](https://bugzilla.mozilla.org/show_bug.cgi?id=291033)

File System Programming Guide – File System Basics – [macOS Standard Directories: Where Files Reside](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6)

Re: sandboxing there's e.g. [Container Directories and File System Access](https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW6) … but that's a potentially **massive** side note `:-)`

**Comment by MrAlex94** [comment]
For now, will keep it as is, just so things don't break! But good reference for any huge updates.
