### ISSUE TITLE
Native ALSA support

### ISSUE THREAD

**Issue by alekksander** [BrowserWorks/waterfox#464]
could we have ALSA support in waterfox? regular firefox won't have it anymore

**Comment by grahamperrin** [comment]
[No sound using ALSA and JACKD · Issue #224 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/224)

**Comment by alekksander** [comment]
but will it stay in future versions?

also there is no sound if dmixer isn't turned on – no errors concerning audio. just no sound. it say's alsa in about:support, but other fields are empty. with dmix it works. no such problem with other browsers… any ideas how to bite it?

**Comment by hawkeye116477** [comment]
`http://www.rosenauer.org/hg/mozilla/file/firefox58/mozilla-alsa-sandbox.patch`

**Comment by Peacock365** [comment]
FIXED BY https://github.com/MrAlex94/Waterfox/commit/6d9152bf48b329ec818e96cf4014bf46df7db4ad

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/538#issuecomment-386066113

**Comment by jbeich** [comment]
@alekksander, probably wants `--enable-alsa` in `.mozconfig` for official binaries to have native ALSA support. One can set `media.cubeb.backend` pref to `alsa` or let Waterfox fallback from `pulse`:

https://github.com/MrAlex94/Waterfox/blob/67d2b0ee4c226f7d5c45093bed9b3c3832178b08/media/libcubeb/src/cubeb.c#L113-L129

**Comment by grahamperrin** [comment]
#538

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/blob/master/.mozconfig#L29

Am I missing something?

**Comment by alekksander** [comment]
still no sound for me (latest waterfox) if i don't use dmix (which i don't normally use)

**Comment by grahamperrin** [comment]
> <strike>https://github.com/MrAlex94/Waterfox/blob/master/.mozconfig#L29</strike>

https://github.com/MrAlex94/Waterfox/blob/classic/.mozconfig#L36 at the time of writing – `classic/`, no longer `master/`
