### ISSUE TITLE
Make the app update settings reliable and useful (profile independent)

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#465]
Hi!

This annoying inability to properly configure updates is inherited from Firefox. Even though I disable it other profiles will update the browser anyway... Such as when I test for something in a new profile. It's very frustrating.

I really don't like resorting to removing or mucking up via ntfs rights updater.exe

**Comment by WagnerGMD** [comment]
```
lockPref("app.update.auto",false);
lockPref("app.update.enabled",false);
lockPref("app.update.service.enabled",false);
```
Hi,

I'm just wonder are you aware about the file (mostly known as) **mozilla.cfg** ? Because you don't need a profil to disable the update.

PS : If you need a prove I had decide to join these 2 pictures.
http://nsa39.casimages.com/img/2018/03/15/180315052610570751.png
http://nsa39.casimages.com/img/2018/03/15/180315052610651144.png

**Comment by mzso** [comment]
[**@WagnerGMD**](https://github.com/WagnerGMD) commented on [2018. márc. 15. 04:38 CET](https://github.com/MrAlex94/Waterfox/issues/465#issuecomment-373250742 "2018-03-15T03:38:14Z - Replied by Github Reply Comments"):
> lockPref("app.update.auto",false);
>     lockPref("app.update.enabled",false);
>     lockPref("app.update.service.enabled",false);
> 
> Hi,
> 
> I'm just wonder are you aware about the file (mostly known as) **mozilla.cfg** ? Because you don't need a profil to disable the update.
> 
> PS : If you need a prove I had decide to join these 2 pictures.  
> 
> [http://nsa39.casimages.com/img/2018/03/15/180315052610570751.png](http://nsa39.casimages.com/img/2018/03/15/180315052610570751.png)  
> 
> [http://nsa39.casimages.com/img/2018/03/15/180315052610651144.png](http://nsa39.casimages.com/img/2018/03/15/180315052610651144.png)

Sure. Though it's not the most robust method since it's in the program files folder.
(BTW Mozilla started removing it. https://bugzilla.mozilla.org/show_bug.cgi?id=1434655 )

**Comment by grahamperrin** [comment]
Historically: https://wiki.mozilla.org/index.php?title=Firefox/EnterprisePolicies&oldid=1190298

The current edition of that page directs readers to: 

- [Deploying Firefox in an enterprise environment - Mozilla | MDN](https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment)

Companion documentation: 

- [Deploying Firefox in an enterprise environment (before Firefox 60 ESR) - Mozilla | MDN](https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment_before_60)

**Comment by WagnerGMD** [comment]
Sorry but I don't share this opinion (no I don't see the trouble).
And thank you @mzso for the link but I won't be agree. Because as **for now**, there is no trouble : this solution works perfectly fine (since several years. And it won't bother you (you can proceed manually later for the update). And about the futur ? For me, it's just **too soon** (no apparently there are just talking about. Then I imagine it will takes a very long moment (months or years) before another big change).

**Comment by mzso** [comment]
[**@WagnerGMD**](https://github.com/WagnerGMD) commented on [2018. márc. 16. 23:15 CET](https://github.com/MrAlex94/Waterfox/issues/465#issuecomment-373859562 "2018-03-16T22:15:09Z - Replied by Github Reply Comments"):
> Sorry but I don't share this opinion (no I don't see the trouble).  
> 
> And thank you [@mzso](https://github.com/mzso) for the link but I won't be agree. Because as **for now**, there is no trouble : this solution works perfectly fine (since several years. And it won't bother you (you can proceed manually later for the update). And about the futur ? For me, it's just **too soon** (no apparently there are just talking about. Then I imagine it will takes a very long moment (months or years) before another big change).

I just think something in the registry, or the waterfox appdata folder would be more robust. And would be more available for average users if it would reflect the settings in the GUI.
BTW. Thanks for the prefs.

**Comment by MrAlex94** [comment]
I'd recommend using autoconf for this. Any other way is just way too complicated.
