### ISSUE TITLE
Site: rationalise the platform-specific offerings

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#467]
At <http://web.archive.org/web/20180310184526/https://www.waterfoxproject.org/downloads>: 

- two installers for Windows, one of which is _Portable_
- one installer for each of macOS, Linux and Android

– a total of four. 

Plus: 

- experimental <https://www.freshports.org/www/waterfox>

Excluding: 

- [Waterfox Browser & Search – Android Apps on Google Play](https://play.google.com/store/apps/details?id=com.waterfox.waterfox), which IIRC is not a Waterfox Ltd. product. 

----

At <https://staging.waterfoxproject.org/en-US/>: 

- Windows (XP/Vista) 
- Windows 
- Windows 64-bit 
- macOS 
- Linux 
- Linux 64-bit 
- Android
- iOS 

That'll need whittling down to whatever's appropriate.

**Comment by grahamperrin** [comment]
Also at <https://staging.waterfoxproject.org/waterfox/new/> 

> Advanced install options & other platforms

– then in the modal, a Google Play badge with reference to <https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox>, which is not found. 

Plus the stub mentioned at https://www.reddit.com/r/waterfox/comments/84hi0f/-/dvpvy3z/ … and so on, I'll not trawl for every comparable occurrence :-) just a few pointers, for now.

**Comment by grahamperrin** [comment]
I see (amongst other things) https://github.com/MrAlex94/www.waterfoxproject.org/blob/master/en-US/download_button.lang … should I ignore what's in that repo?

**Comment by grahamperrin** [comment]
## For users of Windows Vista

I doubt that many newcomers will aim to install on Vista but here goes (staging site tweaking for after the dust settles :-) …

At <https://staging.waterfoxproject.org/en-US/waterfox/new/?scene=1> (linked from <https://blog.waterfoxproject.org/waterfox-56.0-release-download>)

1. click _Advanced install options and other platforms_
2. click _Windows (XP/Vista)_ 
3. at <https://staging.waterfoxproject.org/en-US/waterfox/new/?scene=2> 

> Thanks for choosing Waterfox. Your download should begin automatically. If not, **click here**. 

- and the click (there) leads to https://staging.waterfoxproject.org/en-US/waterfox/all/ where …

## Windows Portable

### Expected

`https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_56.1.0_English.paf.exe`

– I guess (it exists)

### Actual result

`https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.1.0%20Setup.exe`

## For users of Portable

<https://staging.waterfoxproject.org/en-US/waterfox/new/?scene=1> has the same issue with expected and actual results.

**Comment by jbeich** [comment]
> - experimental https://www.freshports.org/www/waterfox

FreeBSD package is ~300 Firefox commits ahead, has x86 (without SSE2) and aarch64 support. It was created as a **temporary** Firefox 56 refuge, to check what's in store in another Firefox fork, how secfixes are backported (both in Waterfox 56 and Firefox ESR52), what can be deobfuscated and how the codebase ages (e.g., bitrot in WE, Stylo, Photon). What happens after Waterfox 56 EOL isn't decided yet but for now users (via `DEPERECATED` line) are encouraged to migrate away.

**Comment by grahamperrin** [comment]
Thanks for clarification 👍

**Comment by MrAlex94** [comment]
Yeah, cheers!

**Comment by grahamperrin** [comment]
@jbeich as an aside, 

<details>
<summary>(off-topic)
</summary>
how did https://svnweb.freebsd.org/ports/head/www/waterfox/files/patch-bug1400540?revision=461350&view=markup make its way in – were you bit by [Mozilla bug 1400540](https://bugzilla.mozilla.org/show_bug.cgi?id=1400540)?

Or do you cherry pick things from logs, based on your experience with the code bases? 

- https://reviewboard-hg.mozilla.org/gecko/shortlog/ with 1400540 at https://reviewboard-hg.mozilla.org/gecko/shortlog/18723c6944b1
- https://github.com/mozilla/gecko-dev/commits/master
- …
</details>

**Comment by jbeich** [comment]
> were you bit by [Mozilla bug 1400540](https://bugzilla.mozilla.org/show_bug.cgi?id=1400540)?

I've tried to make Stylo stable but soon gave up due to massive code churn under `servo/` directory.

> Or do you cherry pick things from logs, based on your experience with the code bases? 

Majority of regression, crash and security fixes happen during Beta cycle. Even Beta 60 has many that apply just fine. With Nightly cycle I sometimes check all commits to a subdirectory e.g., `widget/gtk/`.

**Comment by grahamperrin** [comment]
Meta, tracking: #582

**Comment by grahamperrin** [comment]
## iOS

Pages such as https://www.waterfoxproject.org/waterfox/#sync lead to: 

**Free Mobile Browser App for iPhone, iPad, iOS | Waterfox**
https://www.waterfoxproject.org/en-US/waterfox/ios/

> ### Waterfox browser for iOS 

– with an App Store button. 

And so on. 

For the App Store button, https://itunes.apple.com/us/app/apple-store/&ct=mozorg-ios_page-appstore-button

> Your request produced an error.
> [newNullResponse]

**Comment by grahamperrin** [comment]
From #835:

> … need a version of Waterfox for XP/Vista …

From the closure of [Firefox is dropping support for XP/Vista · Issue #77 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/77): 

>> Too many new API calls to revert them all to support Vista/XP. 

– sorry, @Mahabarata

**Comment by grahamperrin** [comment]
The site and other things have changed considerably since I opened this issue. 

Closing note: https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-531474275
