### ISSUE TITLE
Addons that were locked by Firefox' signing policy stay locked when switching to Waterfox

### ISSUE THREAD

**Issue by naglfar** [BrowserWorks/waterfox#47]
I've switched two Firefox installs over to Waterfox these past few days, one from 43 and one from 44. Both versions where the addon signing policy had already been enforced.
After starting Waterfox, the message on the addon screen changed to the "could not be verified ... proceed with caution" one as expected, but removing the addon is still the only option given.

Reinstalling the extension in question solves this problem.

It seems like Firefox stores somewhere in the users profile which addons have already been locked and keeps them this way. This will probably confuse users making the switch and finding their addons still being disabled.

**Comment by MrAlex94** [comment]
Hi @naglfar ,

Thanks for the info. I'll see if I can find out how to prevent this.

**Comment by naglfar** [comment]
Hi,
not sure if you actually did anything yet, but updating to the 44 test build seems to have fixed this at least on this installation I'm on right now. I did not yet reinstall any of the addons on this installation but now they're all active.
