### ISSUE TITLE
Memory issues, and tabs getting delazified.

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#474]
Hi!

Recently I've been noticing rather high memory usage, and closing a bunch of tabs doesn't seem to alleviate it. I don't know how I could troubleshoot this.

I also noticed that tabs get delazified on startup so a bunch of content processes start which further aggravates this issue because the processess fail to close.
It used to be on Firefox 56 that I could troubleshoot this by searching the console for error messages such as this: _["[bug 1345098] Lazy browser prematurely inserted via [...]"](https://bugzilla.mozilla.org/show_bug.cgi?id=1345098)_

But i don't see this showing up in Waterfox, so I can't troubleshoot this either.

**Comment by grahamperrin** [comment]
For tracking purposes, maybe shift the delazified issue to a separate issue? Thanks. 

## Memory

> … closing a bunch of tabs …

If any one tab is particularly memory-hungry, simply closing it may be not enough to improve use of memory. 

If you do find a tab that's memory-hungry and behaves in that way, can you let us have the URL? 

I sometimes use [Tab Data](https://addons.mozilla.org/addon/tab-data/) (but do not allow it to track memory usage; I run _Get memory usage_ manually).

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. márc. 17. 17:03 CET](https://github.com/MrAlex94/Waterfox/issues/474#issuecomment-373931308 "2018-03-17T16:03:52Z - Replied by Github Reply Comments"):
> For tracking purposes, maybe shift the delazified issue to a separate issue? Thanks.
 
Sure: #475

> If any one tab is particularly memory-hungry, simply closing it may be not enough to improve use of memory.
> 

Yes but I have several content processes neither's memory usage seem to decrease.

> If you do find a tab that's memory-hungry and behaves in that way, can you let us have the URL?
> 

Based on the above, I don't think it's likely that any particular website is responsible. (Though some can be quite heavy, aliexpress, ebay and such)


> I sometimes use [Tab Data](https://addons.mozilla.org/addon/tab-data/) (but do not allow it to track memory usage; I run _Get memory usage_ manually).

I vaguely remember using something like this, once. I seem to remember it doesn't help with memory used up by addons and such.

**Comment by grahamperrin** [comment]
Thanks. 

My use of Tab Data is primarily to measure, not to reduce. (There's also about:performance and extensions such as [Performance Reporter](https://addons.mozilla.org/addon/performance-reporter/), but Tab Data sometimes offers a little more insight.) 

An extension such as [About sessionstore](https://addons.mozilla.org/addon/about-sessionstore/) can help to: 

- tell whether a closed tab is listed as such
- forget closed tabs
- forget closed windows. 

I'll create a new profile to test with <https://www.aliexpress.com/>. 

Also, [memory.free_dirty_pages in Waterfox 56.x · Issue #423 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/423) –

**Comment by grahamperrin** [comment]
> …  profile to test with <https://www.aliexpress.com/>. …

Tested briefly, nothing leapt out at me. 

## Memory in general (some overlap with storage)

Amongst the Mozilla bugs that I recently began following: 

- [1371255 - Very bad memory efficiency of browser.storage.local](https://bugzilla.mozilla.org/show_bug.cgi?id=1371255)
- [1386177 - Very high memory usage after watching many HTML5 movies on Firefox, even after closing them all](https://bugzilla.mozilla.org/show_bug.cgi?id=1386177)
- [1406181 - Use indexedDB as the backend for storage.local](https://bugzilla.mozilla.org/show_bug.cgi?id=1406181)
- [1428306 - Investigate removing browser.storageManager.enabled pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1428306)

From 1428306: 

> … (Storage Standard) … the UI part, since this persistent storage has been on by default from 57…

I'm aware of one web app with a major bug involving IndexedDB. There's an intention to move away from that API, to Storage Standard. 

### Related

[Storage Standard](https://storage.spec.whatwg.org/)

[Offline Storage for Progressive Web Apps  |  Web Fundamentals  |  Google Developers](https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/offline-for-pwa)
