### ISSUE TITLE
Can't troubleshoot lazy browser insertions

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#475]
I'm having issues with lazy tabs being inserted on startup, but I can't troubleshoot it.
The error messages (["[bug 1345098] Lazy browser prematurely inserted via [...]"](https://bugzilla.mozilla.org/show_bug.cgi?id=1345098)) appearing in the console of Firefox 56 doesn't seem to be present in WF 56.

**edit:**
Or maybe it was only ever present on nightly/aurora builds? Looking at the [patch](https://bug1345098.bmoattachments.org/attachment.cgi?id=8860701) in the relevant bug seems to suggest it.

**Comment by grahamperrin** [comment]
Cross reference https://www.reddit.com/r/waterfox/comments/87cmcu/-/dwdvgi5/?context=3

**Comment by mzso** [comment]
@MrAlex94 
Hi!

Is there any chance that you can add this error message feature to the checklist for the next version?
It seems like a minor thing but it would help a lot with troubleshooting.

It seems to me that only two "if" conditionals need to be removed.

**Comment by grahamperrin** [comment]
> lazy tabs being inserted on startup, 

Do you still have this issue? 

FYI https://www.reddit.com/r/waterfox/comments/dvcpho/-/f8c01jr/

**Comment by mzso** [comment]
I can't remember what was the cause. It's certain that the jdownloader browser extions is one of the addons that cause it. Anyway, that error message would be nice if the issue comes up unexpectedly.
