### ISSUE TITLE
SaveFileTo Add-on No Longer Working With 56.0.4.1 Despite Compatibility

### ISSUE THREAD

**Issue by Bumbo2** [BrowserWorks/waterfox#476]
**Savefileto** allowed me to instantly save files to intended folders without having to navigate. This add-on was incredibly convenient for my work, so much so that can't do without it. I don't know why it won't work properly now, but I've been lead to believe that **webextension** apis from **Firefox** have the same effect on some add-ons by limiting access of them to your default download folder which is very much the same problem as I'm having. Currently it'll show the context menu for it but won't actually save the files when directed unless the specified folder is in my default download folder. 
Can this be fixed at all?

**Comment by laniakea64** [comment]
This addon? - https://addons.mozilla.org/addon/save-file-to/

Do you have e10s enabled? (about:support, check what it says under "Multiprocess Windows")

**Comment by Bumbo2** [comment]
I do have it enabled.

**Comment by laniakea64** [comment]
Does disabling it help?

Waterfox Preferences > General, un-check "Enable multi-process Waterfox".  Restart Waterfox when prompted.

**Comment by Bumbo2** [comment]
Yes! Thank you, very much!

**Comment by grahamperrin** [comment]
Compatibility reports for the extension: 

- https://addons.mozilla.org/compatibility/reporter/savefileto%40mozdev.org

**Comment by grahamperrin** [comment]
Review time. Close this?

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/8p5znl/-/e0dlv74/

:1st_place_medal: big thanks to ulf5576 of https://www.reddit.com/r/XUL_for_Quantum_Dev/ for the reprogramming of **Save File to**
