### ISSUE TITLE
error: doc comment not used by rustdoc

### ISSUE THREAD

**Issue by kuh3h3** [BrowserWorks/waterfox#477]
tried to build recent git on ubuntu 17.04 but failed.

6 warnings generated.
42:06.26 libgfx_cairo_libpixman_src.a.desc
42:15.05 libgfx_ycbcr.a.desc
43:05.79 error: doc comment not used by rustdoc
43:05.79    --> /home/kuh3h3/build-waterfox/Waterfox/servo/components/style/values/specified/image.rs:689:17
43:05.79     |
43:05.79 689 |                 /// `to` keyword is mandatory in modern syntax.
43:05.79     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
43:05.79     |
43:05.79 note: lint level defined here
43:05.79    --> /home/kuh3h3/build-waterfox/Waterfox/servo/components/style/lib.rs:26:9
43:05.79     |
43:05.79 26  | #![deny(warnings)]
43:05.79     |         ^^^^^^^^
43:05.79     = note: #[deny(unused_doc_comment)] implied by #[deny(warnings)]
43:05.79 
43:05.79 error: doc comment not used by rustdoc
43:05.79    --> /home/kuh3h3/build-waterfox/Waterfox/servo/components/style/values/specified/image.rs:695:17
43:05.79     |
43:05.79 695 |                 /// There is no `to` keyword in webkit prefixed syntax. If it's consumed,
43:05.79     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
43:05.79 
43:06.17 error: doc comment not used by rustdoc
43:06.17     --> /home/kuh3h3/build-waterfox/Waterfox/objdir/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-8ec5bd49dffb02bd/out/gecko_properties.rs:9131:9
43:06.17      |
43:06.17 9131 |         /// XXXManishearth this should also handle text zoom
43:06.17      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
43:06.18 
43:10.04 error[E0106]: missing lifetime specifier
43:10.04    --> /home/kuh3h3/build-waterfox/Waterfox/objdir/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-8ec5bd49dffb02bd/out/gecko/bindings.rs:569:9
43:10.04     |
43:10.04 569 |      -> RawGeckoNodeBorrowedOrNull;
43:10.04     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
43:10.04     |
43:10.04     = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
43:10.04     = help: consider giving it an explicit bounded or 'static lifetime
43:10.04 
43:10.04 error[E0106]: missing lifetime specifier
43:10.04    --> /home/kuh3h3/build-waterfox/Waterfox/objdir/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-8ec5bd49dffb02bd/out/gecko/bindings.rs:841:9
43:10.04     |
43:10.04 841 |      -> RawServoAnimationValueBorrowedOrNull;
43:10.04     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected lifetime parameter
43:10.04     |
43:10.04     = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
43:10.04     = help: consider giving it an explicit bounded or 'static lifetime
43:10.04 
43:12.49 error: aborting due to 5 previous errors
43:12.49 
43:13.91 error: Could not compile `style`.
43:13.91 
43:13.91 To learn more, run the command again with --verbose.
43:13.91 /home/kuh3h3/build-waterfox/Waterfox/config/rules.mk:986: 'force-cargo-library-build' 타겟에 대한 명령이 실패했습니다
43:13.91 make[5]: *** [force-cargo-library-build] 오류 101
43:13.91 /home/kuh3h3/build-waterfox/Waterfox/config/recurse.mk:73: 'toolkit/library/rust/target' 타겟에 대한 명령이 실패했습니다
43:13.91 make[4]: *** [toolkit/library/rust/target] 오류 2
43:13.92 make[4]: *** 끝나지 않은 작업을 기다리고 있습니다....
43:19.35 In file included from /home/kuh3h3/build-waterfox/Waterfox/objdir/gfx/angle/Unified_cpp_gfx_angle1.cpp:20:
43:19.35 ./Tokenizer.l:1877:16: warning: 'static' function 'yyinput' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
43:19.35     static int yyinput (yyscan_t yyscanner)
43:19.35                ^
43:19.35 1 warning generated.
43:28.32 libgfx_2d.a.desc
43:48.54 libgfx_angle.a.desc
43:48.64 /home/kuh3h3/build-waterfox/Waterfox/config/recurse.mk:32: 'compile' 타겟에 대한 명령이 실패했습니다
43:48.64 make[3]: *** [compile] 오류 2
43:48.64 /home/kuh3h3/build-waterfox/Waterfox/config/rules.mk:453: 'default' 타겟에 대한 명령이 실패했습니다
43:48.64 make[2]: *** [default] 오류 2
43:48.64 /home/kuh3h3/build-waterfox/Waterfox/client.mk:419: 'realbuild' 타겟에 대한 명령이 실패했습니다
43:48.64 make[1]: *** [realbuild] 오류 2
43:48.64 client.mk:170: 'build' 타겟에 대한 명령이 실패했습니다
43:48.64 make: *** [build] 오류 2
43:48.68 363 compiler warnings present.
43:49.65 /usr/bin/notify-send --app-name=Mozilla Build System Mozilla Build System Build failed

**Comment by grahamperrin** [comment]
Try https://github.com/MrAlex94/Waterfox/issues/473#issuecomment-373929696
