### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by vocaltechie** [BrowserWorks/waterfox#48]
This one baffles me.  I normally keep Google Play music as a pinned tab to listen to music.  It worked fine until recently.  Now, when I go to listen to MY MUSIC, all I get is a blank page.  

This is the URL that appears as I get the blank page: https://play.google.com/music/listen#

It works perfectly in Edge, IE, Chrome, and Firefox but not Waterfox.    

I have the latest update of Waterfox.

**Comment by MrAlex94** [comment]
Sorry about that, has been fixed in 44.0. 
You can fix it now by doing the following:
Type **about:config** in the address bar, search for **dom.webcomponents.enabled** and either double click it so it's value turns to **false** or Right Click > Toggle to do the same.
