### ISSUE TITLE
Scrollbar is invisible at some sites (macOS High Sierra)

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#482]
Steps to reproduce:

1. Install WaterFox 56.0.4.1 in macOS High Sierra
2. Ensure that the "Show scroll bars" option is not set to "When scrolling" in System Preferences
3. Visit an affected site
4. Discover that the scrollbar is present and functional where content overflows, yet is completely invisible

Affected sites include [arstechnica.com](https://arstechnica.com), [bitchute.com](https://bitchute.com) and [extremetech.com](http://extremetech.com). There are many others but those are the ones that I have tried recently.

EDIT: Fixed bogus link.

**Comment by ghost** [comment]
Just to add that I am testing with a mouse, though the use of a trackpad should not make any difference.

**Comment by grahamperrin** [comment]
Is https://www.waterfoxproject.org/blog/ similarly affected? 

I might test with a Mac later.

**Comment by ghost** [comment]
The [waterfoxproject.org](https://www.waterfoxproject.org/) site is unaffected by this issue.

**Comment by grahamperrin** [comment]
Thanks … double-checking: just that one page in particular (not the site in general), because it featured in another issue …

**Comment by ghost** [comment]
Indeed, the blog page is unaffected.

**Comment by grahamperrin** [comment]
Not limited to Waterfox. 

> … Affected sites include arstechnica.com, bitchute.com and extremetech.com. …

I can't connect to the third, but the first two are bugged in Firefox ESR 52.7.2 (64-bit) on pre-release build 17E190a of Mac OS X 10.13.4. 

Also bugged: 

- https://testpilot.firefox.com/

From [Test Pilot site lacks a scroll bar in Firefox on Mac OS X 10.13.x (macOS High Sierra) · Issue #2827 · mozilla/testpilot](https://github.com/mozilla/testpilot/issues/2827):

> Is there a plan to make the site work with Firefox ESR 52.x?

– there's not. 

Given the incompatibility with sites such as Ars Technica, we might find something in Bugzilla@Mozilla.

**Comment by ghost** [comment]
Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1408701.

**Comment by grahamperrin** [comment]
Mozilla bug [1408701 - Firefox scrollbar has no thumb on some pages (on macOS 10.13?)](https://bugzilla.mozilla.org/show_bug.cgi?id=1408701)

> RESOLVED FIXED in Firefox 57

https://hg.mozilla.org/releases/mozilla-beta/rev/adc0384c565a

> Bug 1408701 - Ensure that we continue to show dark scrollbar thumbs on macOS 10.13 when scrollbars are always displayed. r=mstange, a=ritu 

Ha! You beat me to it 😄

**Comment by Peacock365** [comment]
FIXED BY https://github.com/MrAlex94/Waterfox/commit/584dcc02847c59e9e96982c6ae75da44bde6ffa1
