### ISSUE TITLE
Localisation: 'Firefox Developer Tools' (not 'Waterfox Developer Tools')

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#485]
For `about:debugging` the title is: 

> Debugging with Waterfox Developer Tools

Branding aside, is there anything Waterfox-specific in the tool set? 

<strike>If not, should it be _Mozilla_ Developer Tools?</strike>

**Comment by laniakea64** [comment]
> For `about:debugging` the title is:
> 
> > Debugging with Waterfox Developer Tools

I'm seeing "Debugging with Firefox Developer Tools".

Edit: It's locale-specific.  With English (British) or English (South African) I also see "... Waterfox Developer Tools".

**Comment by atomGit** [comment]
> It's locale-specific. With English (British) or English (South African) I also see "... Waterfox Developer Tools".

hmmm... i'm EN-US and i see 'Debugging with Firefox Developer Tools' on WF 56.0.4.1

**Comment by grahamperrin** [comment]
@atomGit thanks, that's correct, consistent. 

At the head of the page, _Learn more_ refers to: 

**about:debugging – Firefox Developer Tools | MDN**
https://developer.mozilla.org/docs/Tools/about:debugging#Enabling_add-on_debugging

A comparison: 

- comments at and under https://www.reddit.com/r/waterfox/comments/84hi0f/-/dvpvy3z/ are for inappropriate Mozilla-_isms_ and Waterfox-_isms_ at the staging website for Waterfox
- this issue 485 is for an inappropriate Waterfox-_ism_ **within** Waterfox.

**Comment by grahamperrin** [comment]
Closing as a duplicate of [about:debugging cleanup · Issue #201 …](https://github.com/MrAlex94/Waterfox/issues/201). Apologies for the noise.
