### ISSUE TITLE
Quickfindbar closing while I type. (56.0.3)

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#487]
Hi!

Recently I've been experiencing this annoyance. I open it via hotkey and start typing quickly. But after 1-2 characters the findbar is closed. Does anyone else experience this?

Though I have a findbar related addon ( [Findbar Tweak](https://addons.mozilla.org/hu/firefox/addon/findbar-tweak/) ) addon, I've been using it since ages since and before I started using Waterfox and I didn't experience this issue. Not sure what's changed.

PS:
I don't use WF 56.0.4 because it has an [annoying bug](https://www.reddit.com/r/waterfox/comments/7uvihq/waterfox_5604_is_now_available_for_update_and/dtpude8/) when dropping text into the location bar.

**Comment by grahamperrin** [comment]
2.1.12 here. 

The issue is not reproducible with Waterfox 56.0.4.72_1 (56.0.4.1) on FreeBSD-CURRENT.

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. márc. 24. 16:28 CET](https://github.com/MrAlex94/Waterfox/issues/487#issuecomment-375897877 "2018-03-24T15:28:11Z - Replied by Github Reply Comments"):
> 2.1.12 here.
> 
> The issue is not reproducible with Waterfox 56.0.4.72_1 (56.0.4.1) on FreeBSD-CURRENT.

Not sure  what's causing it here then...

**Comment by grahamperrin** [comment]
> … I don't use WF 56.0.4 …

Also not reproducible with outdated Waterfox 55.1.0.

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. márc. 24. 17:13 CET](https://github.com/MrAlex94/Waterfox/issues/487#issuecomment-375903864 "2018-03-24T16:13:07Z - Replied by Github Reply Comments"):
> > … I don't use WF 56.0.4 …
> 
> Also not reproducible with outdated Waterfox 55.1.0.

I noted in the title that I use 56.0.3. I don't think I ever used WF 55

**Comment by grahamperrin** [comment]
Sure. I had 55.1.0 (alongside 56.0.4.1) readily available on a Mac. 

I'll download the image for 56.0.3.

Please, have you sought advice from users of the extension? https://github.com/Quicksaver/FindBar-Tweak/issues is still open.

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. márc. 24. 19:08 CET](https://github.com/MrAlex94/Waterfox/issues/487#issuecomment-375913152 "2018-03-24T18:08:44Z - Replied by Github Reply Comments"):
> Sure. I had 55.1.0 (alongside 56.0.4.1) readily available on a Mac.
> 
> I'll download the image for 56.0.3.
> 
> Please, have you sought advice from users of the extension? [https://github.com/Quicksaver/FindBar-Tweak/issues](https://github.com/Quicksaver/FindBar-Tweak/issues) is still open.

Well, since it's abandoned I doubt that anyone's around anymore. And since it was working fine before I guess something else changed.

**Comment by grahamperrin** [comment]
Users of the extension are around, I'm certain that you're not alone :-) 

From the extension's page, beneath the developer's notice about the end to updates: 

> **Contact Info**: For reporting problems and bugs, or if you have comments or suggestions, please either send me an email … or go to https://github.com/Quicksaver/FindBar-Tweak/issues and create an issue, this is so I have a way to communicate with you if I need to.

----

The issue is not reproducible with Waterfox 56.0.3 on Mac OS X 10.9.5.

**Comment by atomGit** [comment]
not an issue with WF 56.0.4.x, Linux

**Comment by mzso** [comment]
Not sure why this was closed. I still experience this daily.
