### ISSUE TITLE
Problem with pages using polymer.js

### ISSUE THREAD

**Issue by lrills** [BrowserWorks/waterfox#49]
For those web apps constructed using polymer.js, it seems javascript doesn't work desirably.
Such like https://design.google.com/icons/
![screen shot 2016-02-23 at 10 50 56 am](https://cloud.githubusercontent.com/assets/7855890/13240176/623dfdb2-da1b-11e5-9892-041298e9a2be.png)
which the whole page is not rendered at all.
Or https://www.polymer-project.org/1.0/
![screen shot 2016-02-23 at 10 54 25 am](https://cloud.githubusercontent.com/assets/7855890/13240230/e3303c96-da1b-11e5-880d-9a0ab73bc704.png)
which some elements are not rendered properly.

**Comment by MrAlex94** [comment]
Can't reproduce so hopefully has been fixed :-)
