### ISSUE TITLE
HTM files/tabs are blank unless I 'initialise' those when they are refreshing

### ISSUE THREAD

**Issue by AjvarXX** [BrowserWorks/waterfox#491]
I have a bunch (hundred) htm files from somewhere (probably exported in the past) and after I draganddropped those in browser they are blank and I can't just click refresh all tabs because they end up being blank anyways.
The only way to see them is after I click them once (so they would start loading) I will have to click on them another one time for the next 4-5 seconds (even if I immediately click another tab afterwards) otherwise they won't be loaded.

**Comment by grahamperrin** [comment]
Can you let us have troubleshooting information? From

- about:support

Thanks

**Comment by AjvarXX** [comment]
It is reproduced on a fresh profile too.
1. Create new profile.
2. Drag-&-Drop htm files to the tab panel (I took 40 this time)
3. They will look as if got uploaded but they are blank.
4. This time right click>Refresh all tabs but immediately start Ctrl+Tabbing jumping to the each next tab and this way they will be uploaded correctly.

`

Name | Waterfox
-- | --
56.0.4.1
20180202202613
Show Update History
release
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4
Windows_NT 6.1
Open Folder
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
0/1 (Disabled by accessibility tools)
 
false (disabled by build)
Missing
Missing
false
about:profiles
`
