### ISSUE TITLE
Waterfox 'Locale select' interface not available with browser.preferences.useOldOrganization false

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#494]
Waterfox 56.0.4.72_1 (56.0.4.1) on FreeBSD-CURRENT

1. `browser.preferences.useOldOrganization` `true`
2. about:preferences#general
3. select a locale
4. if necessary, quit then start Waterfox
5. `browser.preferences.useOldOrganization` `false`
6. about:preferences#general

## Expected

7. the _Locale select_ interface

## Actual result

7. no obvious way to review or change the preferred locale
8. seeking _locale_ finds only the font-related preference

## Workaround

8. `browser.preferences.useOldOrganization` `true`
9. about:preferences#general

Advanced users may prefer an `about:config` workaround.

**Comment by grahamperrin** [comment]
#538

**Comment by MrAlex94** [comment]
I'm not planning to update the new organization UI. Just left it there as some people like to use it.
