### ISSUE TITLE
Site: mixed content at some blog posts

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#495]
https://blog.waterfoxproject.org/waterfox-56.0-release-download and https://blog.waterfoxproject.org/waterfox-55.0-release-download, for example. 

[Mixed content blocking in Firefox | Firefox Help](https://support.mozilla.org/kb/mixed-content-blocking-firefox)

**Comment by MrAlex94** [comment]
I believe this is resolved in newer posts.

**Comment by grahamperrin** [comment]
Yep.
