### ISSUE TITLE
Gah. Your tab just crashed.

### ISSUE THREAD

**Issue by hawkeye116477** [BrowserWorks/waterfox#498]
When I go here -> `https://bintray.com/`, site is loading, then message is displayed „Gah. Your tab just crashed.". That error displayed when I updated to 56.1.0. On 56.0.4.1 everything was ok. Also on Vivaldi this site is loading normally.

**Comment by MrAlex94** [comment]
Seems to be related to having stylo enabled.

**Comment by hawkeye116477** [comment]
Even on Firefox Quantum 59.0.1 everything is ok.
From console:
```
thread '<unnamed>' panicked at 'Resolving style on unstyled element', /checkout/src/libcore/option.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Redirecting call to abort() to mozalloc_abort

[Parent 18493] WARNING: pipe error: Broken pipe: file /home/user/git/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 709
[Parent 18493] WARNING: pipe error (73): Connection reset by peer: file /home/user/git/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 18493] WARNING: pipe error (71): Connection reset by peer: file /home/user/git/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x150078,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
```

Related:
```
https://trac.torproject.org/projects/tor/ticket/21766
https://github.com/mozilla/geckodriver/issues/1111
```

**Comment by grahamperrin** [comment]
Yep, with `layout.css.servo.enabled` `true` and e10s disabled, the page leads to crash of Waterfox 56.0.4.72_1 on FreeBSD-CURRENT.

**Comment by hawkeye116477** [comment]
Related -> https://github.com/mozilla/geckodriver/issues/1111

**Comment by hawkeye116477** [comment]
Related:
```
https://trac.torproject.org/projects/tor/ticket/21766
https://github.com/mozilla/geckodriver/issues/1111
```

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. márc. 28. 21:21 CEST](https://github.com/MrAlex94/Waterfox/issues/498#issuecomment-377005192 "2018-03-28T19:21:31Z - Replied by Github Reply Comments"):
> Yep, with `layout.css.servo.enabled` `true` and e10s disabled, the page leads to crash of Waterfox 56.0.4.72_1 on FreeBSD-CURRENT.

Is stylo even supposed to work without e10s?

**Comment by grahamperrin** [comment]
Yes – <https://mozilla.logbot.info/firefox/20180330#c14540031>, please join me in Mozilla's `#firefox` channel if you find otherwise.

**Comment by MrAlex94** [comment]
Stylo is disabled by default, so can mark this resolved for now.

**Comment by AncalagonX** [comment]
Adding one more late data point: In Waterfox 56.2.0, enabling "Stylo" with ```layout.css.servo.enabled``` ```true``` still results in bintray.com crashing the tab. When set false, there are no issue.

**Comment by grahamperrin** [comment]
Thanks, I added this issue 498 to the _Background_ shortlist at https://www.reddit.com/comments/7bj77g/-/dx12nol/
