### ISSUE TITLE
Scrolling with two-finger on touch pad not working

### ISSUE THREAD

**Issue by FichteFoll** [BrowserWorks/waterfox#5]
It does work on Firefox, but it does not on Waterfox. As you can imagine, scrolling is quite important for a web browser so it would be nice it this was fixed. Until then, I'll need to stick with Firefox.

Setting `dom.w3c_touch_events.enabled` to 1, as by https://www.reddit.com/r/waterfox/comments/39yegl/when_touchscreen_support_is_again_implemented/csbsmj3 did not work, and `apz.overscrolling.enabled` does not exist for me.

WF 38.1.0, Win8.1

**Comment by leelaylay** [comment]
��������������������������

**Comment by MrAlex94** [comment]
Do you still have this issue?
