### ISSUE TITLE
Some further suggestions (new options in the settings).

### ISSUE THREAD

**Issue by Peacock365** [BrowserWorks/waterfox#500]
Hi there!

I would like to recommend that three other changes be introduced into Waterfox:

1) Create a "WebRTC" checkbox in the settings and let it control _media.peerconnection.enabled_

2) Make the hidden pref _browser.safebrowsing.enabled_ visible by default and create a "Google SafeBrowsing" checkbox in the settings which controls it (default on)

3) Replace Google's location service with Mozilla's location service by default. You need to change _geo.wifi.uri_ to https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY% if you want to accomplish this. Create a "Location Services" checkbox in the settings that controls _geo.enabled_ (default on).

I hope you find these suggestions useful.

**Comment by jbeich** [comment]
> 2. Make the hidden pref `browser.safebrowsing.enabled` visible by default

Only used used during profile upgrade to convert into `browser.safebrowsing.phishing.enabled`.

https://github.com/MrAlex94/Waterfox/blob/67d2b0ee4c226f7d5c45093bed9b3c3832178b08/browser/components/nsBrowserGlue.js#L1894-L1906

>    and create a "Google SafeBrowsing" checkbox in the settings which controls it (default on)

Already exposed as "Block dangerous and deceptive content" in `about:preferences#security`.

> 3. Replace Google's location service with Mozilla's location service by default.

Neither are used after 72f29771fa41 and may not work without API keys. For one, open `resource://gre/modules/AppConstants.jsm` in Waterfox to check if your build has any API keys.
