### ISSUE TITLE
Missing item in about: addons

### ISSUE THREAD

**Issue by StVol33** [BrowserWorks/waterfox#502]
![screenshot 2018-03-29 001](https://user-images.githubusercontent.com/11031379/38132690-cdcb7f82-3414-11e8-8cb4-76e48f4fdd76.png)

**Comment by grahamperrin** [comment]
From <https://github.com/MrAlex94/Waterfox/commit/8132766ef286208d7ea5137a1ee49b93bb8d4161>

> Disable the add-ons discovery pane as it hasn't/won't be updated again. …

Re: [Legacy Extensions Database · Issue #303 …](https://github.com/MrAlex94/Waterfox/issues/303) I don't foresee an `about:addons` discovery pane in Waterfox interacting with Waterfox-oriented add-ons services. 

For https://github.com/mozilla/addons-server currently there's nothing open in the [legacy switch off](https://github.com/mozilla/addons-server/labels/project%3A%20legacy%20switch%20off) project, I guess that there'll be something before 2018-08-21.
