### ISSUE TITLE
general.useragent.locale not effective with one Waterfox profile, maybe due to import or migration from Firefox

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#505]
A few hours ago I realised that with my oldest profile, which probably originated with Firefox (for a few weeks I allowed both Firefox 56.0.2 and Waterfox 56.0 to share a single profile, never concurrently): 

- the **Locale select** menu has no effect. 

If either of the following is preferred for `general.useragent.locale`:  

- `ru`
- `fr`

– then with the next start (or restart), the preferred locale is not apparent. 

Waterfox 56.1.0_1 on FreeBSD-CURRENT. 

As far as I can tell: not an issue with new (additional) profiles. 

----

Rewind to early January. From <https://www.reddit.com/r/waterfox/comments/7o26jk/-/ds7whmk/?context=4> for an `nl` problem with with Waterfox 56.0.1: 

> … a first clean installation of Waterfox … the latest standard and updated version of Firefox was installed …

From that, we might infer that: 

- the first run of Waterfox involved import or migration of data from Firefox. 

If that point is true, then – considering both cases (Frank Meijer's and my own) – I guess that we have, or had, a bug affecting migration. 

https://github.com/MrAlex94/Waterfox/commit/286785fc8bedb61b531d041252e3f54538c22d6d (2018-03-02) improved the migration script but (sorry) I can't tell whether it covers this issue. 

----

Should I try to make the issue reproducible with a Waterfox 56.1.0 (or 56.1.0_1) migration from Firefox? I have 59.0.2_1,1 handy on FreeBSD-CURRENT.

**Comment by krystian3w** [comment]
Firefox 59 use new key `intl.locale.requested`<sup> [use-firefox-interface-other-languages-language-pack](https://support.mozilla.org/en-US/kb/use-firefox-interface-other-languages-language-pack) </sup>.

In Waterfox 56 maybe block `intl.locale.matchOS`;**`True`** :arrow_right:  change to `false`.

**Comment by grahamperrin** [comment]
Thanks, `intl.locale.matchOS` is `false` by default.

**Comment by MrAlex94** [comment]
Seems pretty niche. Especially since new prof refresh and import reset prefs now.

**Comment by grahamperrin** [comment]
Definitely nice. I'd **love** to understand why some profiles are better than others (and lose qualities, through a refresh, that might not be regained (e.g. [About sessionstore – not working with new profiles : waterfox](https://www.reddit.com/r/waterfox/comments/855l5r/about_sessionstore_not_working_with_new_profiles/))), but it's probably more a question for Reddit.
