### ISSUE TITLE
56.1.0 updater not working

### ISSUE THREAD

**Issue by 9jkh** [BrowserWorks/waterfox#507]
addon Check for Updates in Help Menu is showing a 404 (wasn't getting this before updating to the 56.1): https://s14.postimg.org/l1plhygo1/Update_Failed_error.png

"About" shows up to date, but looking further into this, doesn't seem like the application is properly prepared to check for any updates. Still stuck on the 56.0.4.1

From updates.xml:

~/Library/Caches/Mozilla/Updates/Applications/Waterfox/updates.xml

"finalURL="https://storage-waterfox.netdna-ssl.com/releases/osx64/update/waterfox-56.0.4.1.en-US.osx64.complete.lzma.mar"

<updates xmlns="http://www.mozilla.org/2005/app-update"><update appVersion="56.0.4" buildID="20180202191140" channel="release" displayVersion="56.0.4" installDate="1520697658163" isCompleteUpdate="false" name="Waterfox 56.0.4" serviceURL="https://www.waterfoxproject.org/update/osx64/56.0.4/en-US/release/update.xml" promptWaitTime="691200" backgroundInterval="0" type="major" detailsURL="https://www.waterfoxproject.org/blog/waterfox-56.0-release-download" previousAppVersion="56.0.4" statusText="The Update was successfully installed" extensionVersion="56.0.4" platformVersion="56.0.4" version="56.0.4"><patch type="complete" URL="https://storage-waterfox.netdna-ssl.com/releases/osx64/update/waterfox-56.0.4.1.en-US.osx64.complete.lzma.mar" finalURL="https://storage-waterfox.netdna-ssl.com/releases/osx64/update/waterfox-56.0.4.1.en-US.osx64.complete.lzma.mar" size="81492829" selected="true" state="succeeded"/></update></updates>

**Comment by laniakea64** [comment]
https://github.com/MrAlex94/Waterfox/issues/361#issuecomment-377710484

**Comment by 9jkh** [comment]
Thanks for pointing me to that.

**Comment by grahamperrin** [comment]
OK, reading this issue alongside the first reply to <https://redd.it/88r6fq>

- do you still get the 404 error?

**Comment by 9jkh** [comment]
No, all good now.
