### ISSUE TITLE
Zoom text only doesn't work

### ISSUE THREAD

**Issue by ryokash** [BrowserWorks/waterfox#509]
Zooming does not work if "Zoom Text Only" is enabled.
Text size won't be changed even if "Zoom In" or "Zoom Out" is clicked.
Only zooming ratio in location bar changes.

Waterfox version: 56.1.0 (64bit) for Windows

**Comment by grahamperrin** [comment]
Cross reference: [Font sizing has stopped working with Waterfox 56.1.0 help please. : waterfox](https://www.reddit.com/r/waterfox/comments/888tti/font_sizing_has_stopped_working_with_waterfox/)

Plus there was some chat in one of the IRC channels for Waterfox.

**Comment by Mikhail-M12** [comment]
Set layout.css.servo.enabled=false - and text only zooming begins to work.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/pull/511#issuecomment-379572918 noted with thanks. 

Also https://www.reddit.com/r/waterfox/comments/87cmcu/-/dwslg9o/

**Comment by tazer4** [comment]
How come this hasn't been fixed yet?  Seems like a big feature bug, I would expect a patch to be released immediatly but its been weeks...

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/commit/1c1261794d1b06583f14f3a4ae7d6b6e6e3941dd was made on 2018-04-06. 

Re: https://blog.waterfoxproject.org/waterfox-56.1.0-release-download I guess that 56.1.1 will include one of the five things that are upcoming (alongside the change to the Stylo-related preference, and other recent commits). 

In the meantime, the workaround is reasonably simple. I think, not the type of thing that would have required immediate release of an update.

**Comment by grahamperrin** [comment]
#538
