### ISSUE TITLE
Segfault while click and drag any content on a webpage

### ISSUE THREAD

**Issue by iwearsable** [BrowserWorks/waterfox#510]
Using Waterfox 56.1.0 (64-bit) Hawkeye 116477 - Rolling
OS Is Ubuntu 16.04, completely up-to-date

Starting in this version if I drag anything on a webpage Waterfox immediately segfaults. By that I mean if I click and and hold and drag a link as if I wanted to drag it up to a tab, or if I select text and drag, or click and drag an image, in all cases it is an immediate segfault with an error like so:

`kernel: [  555.948443] Chrome_~dThread[8615]: segfault at 0 ip 00007fb2689b8265 sp 00007fb2665feb20 error 6 in libxul.so[7fb268370000+554e000]`

**Comment by MrAlex94** [comment]
May be Stylo related. Can you set layout.css.servo.enabled to false and
test again?

**Comment by iwearsable** [comment]
That was fast! I changed that setting and restarted Waterfox, and confirmed that it was showing changed in about:support. Still having the same problem.

I also tried starting waterfox with --safe-mode from a terminal and still have the same problem, but it offers the following extra error information in the terminal after the crash.

`[Parent 11201] ###!!! ABORT: Request 141.8: BadWindow (invalid Window parameter); 3 requests ago: file /home/build/Waterfox/toolkit/xre/nsX11ErrorHandler.cpp, line 147
[Parent 11201] ###!!! ABORT: Request 141.8: BadWindow (invalid Window parameter); 3 requests ago: file /home/build/Waterfox/toolkit/xre/nsX11ErrorHandler.cpp, line 147
Segmentation fault`

**Comment by MrAlex94** [comment]
Do you have a dual monitor setup?

**Comment by iwearsable** [comment]
Actually, I just set up dual monitors a few days ago with Xinerama..

I'm going to mess around with a few things relating to that and see what happens.

**Comment by iwearsable** [comment]
I changed my dual monitor setup so that it uses randr method instead of xinerama and the issue has gone away. Thank you for your time, I'm going to buy you a coffee right now!
