### ISSUE TITLE
56.1.0 crashes with Speed Start add-on when Stylo is enabled

### ISSUE THREAD

**Issue by JustOff** [BrowserWorks/waterfox#512]
STR:
* Install [Speed Start](https://addons.mozilla.org/en-US/firefox/addon/speed-start/)
* Open new tab
* Use right mouse button's menu to create a link to some site
* Restart WF
* Open new tab

WF 56.0.x works just fine and no crushes are observed.

Known workaround is to set `layout.css.servo.enabled` -> `false`. Tag #511.

**Comment by grahamperrin** [comment]
Not crashing with Stylo with 56.1.0_2 on FreeBSD-CURRENT. 

Compatibility reports: https://addons.mozilla.org/compatibility/reporter/SStart%40Off.JustOff

I added links to: 

- https://addons.mozilla.org/en-GB/firefox/addon/speed-start/
- https://github.com/MrAlex94/Waterfox/issues/512
- https://github.com/MrAlex94/Waterfox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by grahamperrin** [comment]
If I: 

- enable multi-process Waterfox (ignore the reported incompatibility with e10s) **and**
- add a link to a page that's known to make a tab crash with Stylo

– then Waterfox will crash at the attempt to create the thumbnail. 

If I disable Stylo before restoring the crashed session, then I can create the thumbnail, re-enable Stylo and open a new tab without a crash. Waterfox will crash if I attempt to refresh the thumbnail.

**Comment by jbeich** [comment]
@grahamperrin, FreeBSD package is unaffected because it backported mozilla/gecko-dev@6905267b2878.
