### ISSUE TITLE
Silently-installed Mozilla addons

### ISSUE THREAD

**Issue by chocolateboy** [BrowserWorks/waterfox#515]
Just noticed in Waterfox 56.1.0/Linux (Arch) that the following addons have been silently installed:

* [ADB Helper](https://github.com/mozilla/adbhelper)
* [Valence](https://github.com/mozilla/valence)

(They may have been installed in an earlier version. The timestamp on the `~/.waterfox/<profile>/extensions/fxdevtools-adapters@mozilla.org/` folder is from February, when I was using 56.0.4.1.)

There's a discussion about them [here](http://techdows.com/2015/08/shocking-firefox-silently-installs-adb-helper-and-valence-add-ons.html) (I don't remember ever using WebIDE) and a Bugzilla issue [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1114380).

They look like they could both be useful (or [were](https://bugzilla.mozilla.org/show_bug.cgi?id=1314811)), but I'd rather not have addons installed without my consent. If it's really the best option, it feels like the user should, at the very least, be asked or notified, and that this behaviour should be restricted to nightlies and/or developer builds rather than release builds like Waterfox.

**Comment by chocolateboy** [comment]
According to [this post](https://news.ycombinator.com/item?id=10840289) (which is also discussed on the [Pale Moon forum](https://forum.palemoon.org/viewtopic.php?t=18681)), these addons can be (partially?) disabled by setting the following preferences:

```javascript
pref("devtools.webide.enabled", false)
pref("devtools.webide.autoinstallADBHelper", false)
pref("devtools.webide.autoinstallFxdtAdapters", false)
pref("devtools.webide.autoConnectRuntime", false)
```

**Comment by MrAlex94** [comment]
Also I’ve pointed the pref that checks for system add-ons to download to a
blank XML file. Any chance the Linux distro might be force installing them,
like Ubuntu does?

Otherwise I’ll check if they’re on other distros/OS.

**Comment by chocolateboy** [comment]
Thanks!

> Any chance the Linux distro might be force installing them, like Ubuntu does?

I don't think so. It looks like it's an [unmodified build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=waterfox-bin&id=e062bd5d34f5db374189828d84171005372b40d0).

**Comment by MrAlex94** [comment]
I've had a look and can't find these installed on any of my macOS, Windows or Debian systems

**Comment by chocolateboy** [comment]
If I reset the preferences mentioned above to their defaults, the addons are installed automatically for me in a clean profile as soon as [WebIDE is opened](https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Opening_WebIDE) e.g. with <kbd>Shift-F8</kbd> (which is probably how I accidentally triggered it).

**Comment by MrAlex94** [comment]
These add-ons are good supplements for WebIDE. What would be the point in removing them?

**Comment by chocolateboy** [comment]
AFAICT, WebIDE is [obsolete](https://bugzilla.mozilla.org/show_bug.cgi?id=1314811).

These addons can still be installed from the WebIDE GUI by anyone who wants to use them via the following [buttons](https://i.imgur.com/Yoahofi.png):

* Install [ADB Helper](https://github.com/mozilla/adbhelper)
* Install [Simulator](https://github.com/mozilla/valence)

The options [above](https://github.com/MrAlex94/Waterfox/issues/515#issuecomment-379748112) just prevent them being secretly/silently installed without the user's consent.

**Comment by Peacock365** [comment]
Relevant information: https://trac.torproject.org/projects/tor/ticket/16222

I agree with @chocolateboy by the way. Who wants them may install them manually. No point in having them in every profile, being installed behind our backs.
