### ISSUE TITLE
Waterfox crashes on this site

### ISSUE THREAD

**Issue by AjvarXX** [BrowserWorks/waterfox#516]
https://resetters.ru/index.php?s=3e3f4ddc82722bb701aa2bcfd9f592d5&act=idx

Even new profile.

**Comment by grahamperrin** [comment]
With Waterfox 56.1.0_7 on FreeBSD-CURRENT, no extensions, multi-process enabled and Stylo enabled, I had: 

- no crash of Waterfox
- crashes of the tab. 

Crashes were not noticeable during, or immediately after, loading the site. 

Crashes first occurred repeatedly when I used the keyboard to view the adjacent tab then review the tab that contained https://resetters.ru/index.php?s=3e3f4ddc82722bb701aa2bcfd9f592d5&act=idx e.g. 

1. load, or reload
2. <kbd>Control</kbd>-<kbd>⇞</kbd>
3. <kbd>Control</kbd>-<kbd>⇟</kbd>

Once, the tab crashed when I used the wheel of a mouse to scroll down. 

Crashes seem to be **consistently reproducible** when clicking, beginning to drag, or rapidly moving the pointer over this animated GIF (not bugged below, bugged where the image appears within <https://resetters.ru/index.php?s=3e3f4ddc82722bb701aa2bcfd9f592d5&act=idx>): 

![4_4_4_logo_resetters_anim](https://user-images.githubusercontent.com/192271/38529445-ac8d26ea-3c5c-11e8-9c74-2aac9b42bed2.gif)

If I point at the underlined part of a word within the GIF: 

- within a split second there's a crash 

– and if I refrain from moving the pointer, then <kbd>Control</kbd>-<kbd>R</kbd> is followed by a crash of the tab whilst loading. 

----

If multi-process Waterfox is <strike>enabled </strike>disabled then the application, not just the tab, will crash. 

----

**Not reproducible with [Stylo disabled](https://www.reddit.com/r/waterfox/comments/7bj77g/do_not_forget_to_enable_styloquantum_css/dx12nol/)**. Related: 

- [Don't enable Stylo by default by jbeich · Pull Request #511 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/pull/511)

**Comment by grahamperrin** [comment]
![2018-04-10 01 52 42](https://user-images.githubusercontent.com/192271/38530534-00fe9226-3c63-11e8-8184-034f8fd3eb6b.png)

**Comment by AjvarXX** [comment]
Thank you. Exactly as you said: E10s enabled = tab crash, E10s disabled = app crash.

**Comment by grahamperrin** [comment]
OK @AjvarXX and please, do you have Waterfox now working more reliably – with Stylo disabled?

**Comment by AjvarXX** [comment]
Yes, site no more crashes tab. For now Stylo stays disabled.
