### ISSUE TITLE
XML parsing error on various about: pages and crash on startup with CTR2

### ISSUE THREAD

**Issue by fghsgh** [BrowserWorks/waterfox#517]
![image](https://user-images.githubusercontent.com/15169281/38555458-6afd1aa4-3cc6-11e8-8a20-d32275f1e177.png)
Above is what happens when I try to open the add-on page. Multiple others also don't work and I had to remove my .waterfox folder to even get it running (otherwise it crashed) so I could submit this issue.
The main reason why I use Waterfox is for the CTR2 add-on and installing it again makes it revert to crashing on startup. Maybe this is an issue with CTR2 but the inspect element thing also won't load:
![image](https://user-images.githubusercontent.com/15169281/38555674-4cf09d46-3cc7-11e8-911f-c6f718f0ee1f.png)
^ that is all I get instead of the inspector

I will be using an older version for now.

(my system is Ubuntu 16.04)

**Comment by grahamperrin** [comment]
<strike>Can you try with [Stylo disabled](https://www.reddit.com/r/waterfox/comments/7bj77g/do_not_forget_to_enable_styloquantum_css/dx12nol/)? Thanks. 

(Note to self: with Stylo enabled and Classic Theme Restorer 1.7.3.4 added to Waterfox 56.1.0_7 on FreeBSD-CURRENT, I can't reproduce the symptoms.)</strike>

**Comment by PandaCodex** [comment]
If memory serves, did alex remove that localization value from the browser or language packs?

**Comment by MrAlex94** [comment]
This is a language pack issue, not an add-on issue. Waterfox has built-in language packs, use them instead :-).
Please let me know how it goes.

**Comment by fghsgh** [comment]
This fixed the issue. Thanks.
