### ISSUE TITLE
XML parsing error undefined entity error

### ISSUE THREAD

**Issue by mathias-freire** [BrowserWorks/waterfox#518]
Windows 10 Pro 64 bit. After updating Waterfox 56.1.0, I'm getting this error.

XML parsing error undefined entity error
Location:chrome://browser/content/browser.xul
Line number 240, Column 5:
<broadcaster id="viewTabsSidebar" autoCheck="false" sidebartitle="&syncedTabs.sidebar.label;"
----^

Is there any fix for this?

Note: I've tried clean install. It might be because of extensions but I don't want to disable them, I need them.

**Comment by grahamperrin** [comment]
<strike>Can you try with [Stylo disabled](https://www.reddit.com/r/waterfox/comments/7bj77g/do_not_forget_to_enable_styloquantum_css/dx12nol/)? Thanks. 

If that doesn't work around the issue, it'll help to have troubleshooting information, which includes names of extensions etc.. Text (not raw data) copied from: 

- about:support</strike>

**Comment by PandaCodex** [comment]
This looks like language pack parse issue. Localization be key point to start shipped browser default and packaged, could be they installed a Firefox language pack or an installed addon referencing a localization value not available in Waterfox causing parse error.

looks more on side of browser local. Are you using default en-us or different language?

Could be related? https://github.com/MrAlex94/Waterfox/issues/517

**Comment by mathias-freire** [comment]
@PandaCodex It turned out thats a language pack issue. Removed old lang packs and everything is good. Thanks for your advices.
