### ISSUE TITLE
Usage of Unity does not work with waterfox

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [BrowserWorks/waterfox#52]
Unity, that little engine used to run browser based applications and programs, and whatnot doesn't seem to work with Waterfox Browsers, but it works fine on Firefox for whatever reason

Can there be hope to make this work in the future?

**Comment by MrAlex94** [comment]
Have you got the 64-Bit web player installed?

 http://forum.unity3d.com/threads/64-bit-webplayer-availability.153599/
