### ISSUE TITLE
NTFS permissions of downloaded files

### ISSUE THREAD

**Issue by VVelda** [BrowserWorks/waterfox#520]
Hello,
could it be possible to fix [this](https://bugzilla.mozilla.org/show_bug.cgi?id=224692) bug, which Mozilla have never fixed? It adding all permissions to everyone for every downloaded file instead of inherit that from file system. It's not problem with all of other browsers.

**Comment by MrAlex94** [comment]
If someone wants to patch it, I won't. Seems like a minefield trying to fix it.

**Comment by grahamperrin** [comment]
#538
