### ISSUE TITLE
Make standalone APK downloadable from site

### ISSUE THREAD

**Issue by leafcutterant** [BrowserWorks/waterfox#521]
I really advocate the inclusion of Waterfox for Android in the F-Droid app repository ( WaterfoxCo/Waterfox-Android#40), but until then, please make a standalone APK available for download from the website, so those that want to avoid the Google Play store will have an option.

**Comment by grahamperrin** [comment]
Cross reference [APK for Android version : waterfox](https://www.reddit.com/r/waterfox/comments/8c0rsr/apk_for_android_version/)

**Comment by D0ve** [comment]
Alex, 
I would suggest even, - make another one repository here (on this accaunt) name it smth like  'Waterfox-binaries'  , and make it especially for builds! Placing all builds in 'releases' section there!

**Comment by benryanau** [comment]
Thanks

**Comment by grahamperrin** [comment]
Meta, tracking: WaterfoxCo/Waterfox#582

**Comment by dbtx** [comment]
+1 (don't accept GApps, can't use the Play Store at all)
I can find "something" already on e.g. APKPure but I have been burned there before and do not trust them. Can we just get an apk & md5sum?

**Comment by Ibuprophen** [comment]
@dbtx, APKPure is a very decent Alternative to obtaining apps but, I've found that they're not the most up-to-date with the apps there. 

APKMirror is basically the go-to alternative to the Play Store and is very reputable as well. 

I would personally recommend APKMirror... 👍 

The following is the APKMirror link for Waterfox. 

https://www.apkmirror.com/apk/waterfox-ltd/ 

Just an FYI... 

The above link reflects the package name of "org.waterfoxproject.waterfox" and MrAlex94 had released the new one under a new package name of "net.waterfox.waterfox" that APKMirror is currently working on creating the new profile to accommodate the new package name. 

I hope I was somewhat helpful to you... 😱 

Good Luck! 


~Ibuprophen

**Comment by leafcutterant** [comment]
So, @MrAlex94 why did you close this?

**Comment by ghost** [comment]
Please reopen this @MrAlex94 . Is there a reason not to give an APK to use while Google takes their sweet time letting it onto their Play Store, if they even will at all?

**Comment by dbtx** [comment]
NB: If anyone really needs it, one can sometimes get Google-obsessed apps to work on a de-Googled phone using microG, and one can get apps anonymously from the Play Store through Aurora Store which is available on F-Droid. YMMV.

For web browsing, I eventually just got Fennec from F-Droid, and only because the old version of Firefox (which previously had the magical ability to save a web page into local storage, as PDF in this case) also occasionally stops displaying another website which has just been Made More Better.

**Comment by Henry-Hiles** [comment]
@MrAlex94 as far as I can see, this is not fixed. Please kindly re-open.

**Comment by expertmanofficial** [comment]
> @MrAlex94 as far as I can see, this is not fixed. Please kindly re-open.

oh hey QuadRadical, nice to see you here :-) 

yup I agree.
