### ISSUE TITLE
[Visual bug] Waterfox "remembers" screensize tiling wm

### ISSUE THREAD

**Issue by TomJansen** [BrowserWorks/waterfox#527]
I am using i3 and every time I have Waterfox open besides an other window (like a terminal), Waterfox "remembers" that setting when it is opened another time. (this time as the only window). When I open Waterfox, the place where the terminal was is now glitched out. The workaround is opening another window and closing it, Waterfox resets itself and is again fully functional. This bug is also in the latest Firefox release (quantum)

**Comment by MrAlex94** [comment]
Have you filed a bug with Mozilla or found an existing one?

**Comment by TomJansen** [comment]
Yes, here is someone with the sample bug https://bugzilla.mozilla.org/show_bug.cgi?id=1435159
