### ISSUE TITLE
Addon disabled by Mozilla in FF56, can it be whitelisted for Waterfox? (extensions.blocklist.enabled)

### ISSUE THREAD

**Issue by JohnEdwa** [BrowserWorks/waterfox#528]
The [only proper Finnish spell checker for Firefox](https://addons.mozilla.org/en-US/firefox/addon/finnish-spellchecker/) has been disabled in 64bit Firefox 56 due to [compatibility and immediate crashing issues,](https://bugzilla.mozilla.org/show_bug.cgi?id=1407147) and also gets blocked in Waterfox 56.1.0 64-bit. However, I've been successfully running it for two weeks now (by setting 'extensions.blocklist.enabled' to false) and have not had a single issue with it not working or causing any crashes. 

I know a sample size of one is basically meaningless but I do believe the changes that caused the issue are not present on Waterfox. Would it be possible to whitelist this addon?

**Comment by MrAlex94** [comment]
Unfortunately we get an updated blocklist from Mozilla every day. No easy way to overwrite it unless you disable the check as you have done. Sorry :/
