### ISSUE TITLE
Pen and Tablet support not working in Windows

### ISSUE THREAD

**Issue by GraithTiger** [BrowserWorks/waterfox#53]
More specifically, flicks is not working.

Platform:
Windows 7 64-bit
Waterfox/44.0.3

**Comment by GraithTiger** [comment]
![Possible related bug](https://cloud.githubusercontent.com/assets/7018897/13625354/e1c4434c-e584-11e5-9cf4-835092104f0e.png)
Possibly related, sometimes previous pen paths seen when loading tabs.

**Comment by GraithTiger** [comment]
New crash caused by InkObj.dll, possibly related. Will try to get more info next crash happens.

**Comment by MrAlex94** [comment]
@GraithTiger is this issue still apparent?

**Comment by GraithTiger** [comment]
I do not have the issues with crashes or the graphical issues, but pen flicks still do not work.

**Comment by MrAlex94** [comment]
Did it ever work with Firefox? I know there were some limitation with touch/pen input in older versions.

If you still have this issue, please re-open.
