### ISSUE TITLE
Waterfox security 

### ISSUE THREAD

**Issue by souperdoupe** [BrowserWorks/waterfox#531]
Hi,

I've been a long-time advocate of this project.  Recently, I read a few sites that expressed concerns about security because Waterfox is based on an "outdated" (56.x) version of Firefox than the stable release (Quantum).  I think the big concerns arose when Meltdown/Spectre entered the picture, and users started evaluating and re-evaluating their browser choices.   

I was just wondering how you would respond to Waterfox security compared to, say Quantum or ESR.

Keep up the great work btw.

**Comment by laniakea64** [comment]
Waterfox gets the security patches from current Firefox releases.

**Comment by MrAlex94** [comment]
Yes, pretty much the same (albeit usually a 1-2 week delay :-)) as release.

**Comment by jbeich** [comment]
Each Firefox branch has tradeoffs: Nightly (most secure), Beta, Release, ESR (least secure). Waterfox is (or was from 2017-11-14 to 2018-09-05) somewhere between Release and ESR but can be between Beta and Release if Beta's fixes are proactively backported. Once ESR52 reaches EOL some components in Waterfox 56 (e.g., non-Stylo codepaths) will be under risk of known unknowns, so Waterfox 56 may end up less secure than ESR60.

Security fixes may decrease stability, have regressions, depend on large code refactorings, so backporting process is always lossy e.g.,

From https://www.mozilla.org/en-US/firefox/organizations/
> Maintenance of each ESR, through point releases, is limited to high-risk/high-impact security vulnerabilities and in rare cases may also include off-schedule releases that address live security vulnerabilities. Backports of any functional enhancements and/or stability fixes are not in scope.

All low-impact and most moderate-impact security fixes are probably "not in scope" as well. For one, many Spectre mitigations landed only in Firefox 60.

**Comment by grahamperrin** [comment]
Nit: 

>  2018-09-05
