### ISSUE TITLE
Website Suggestion: Add "Download for Other Platforms" link to Download button

### ISSUE THREAD

**Issue by ForkedLightning** [BrowserWorks/waterfox#532]
The "Download" button on the front page goes to https://www.waterfoxproject.org/en-US/waterfox/new/?scene=2 which starts automatically and doesn't give any options. Platform detection does not work reliably with privacy addons (and also I can't choose to download the setups for a different platform).

Please add the "Download for Other Platforms" link to the bottom of the download buttons.

**Comment by grahamperrin** [comment]
Meta, tracking: #582

**Comment by MrAlex94** [comment]
Fixed.
