### ISSUE TITLE
Black folders in bookmarks sidebar

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#535]
Is there a means of changing the color of the folders which appear black in the bookmarks sidebar into the the standard yellow color? 
![black_folders](https://user-images.githubusercontent.com/33827636/39186314-59a03fc0-47ca-11e8-9076-2104054a76b7.PNG)

**Comment by grahamperrin** [comment]
Where is yellow a standard?

**Comment by Telmesomething** [comment]
> Where is yellow a standard?

In the dropdown menu, they appear yellow. I'd prefer to keep them that way in the sidebar as well.  

![yellow_folders](https://user-images.githubusercontent.com/33827636/39230823-3c403662-4868-11e8-8ae2-b95baa27fbe0.PNG)

**Comment by grahamperrin** [comment]
## … on Microsoft Windows

From Mozilla bug [1398332 - 4 different styles of folder icons on Windows](https://bugzilla.mozilla.org/show_bug.cgi?id=1398332): 

![folder icon inconsistency](https://user-images.githubusercontent.com/192271/39273946-49a4b290-48d8-11e8-8993-e627f59ca6b7.PNG)

## … on Linux and FreeBSD

There might be comparable Mozilla bugs, with keyword _GTK_, but I can't easily find one. 

Appearances in the **Bookmarks** menu are theme-specific, for example: 

![2018-04-25 22 05 59](https://user-images.githubusercontent.com/192271/39273708-7cd3cd00-48d7-11e8-8bb5-1c66b97c90b6.png)

![2018-04-25 22 11 57](https://user-images.githubusercontent.com/192271/39273706-7c8a73b2-48d7-11e8-8c70-4a028a2fa1c0.png)

## Also

Mozilla bug [1387705 - Inconsistent use of folder icon in add/edit bookmark popup](https://bugzilla.mozilla.org/show_bug.cgi?id=1387705)

**Comment by Telmesomething** [comment]
Thanks for the screenshots and bug reports Graham. 

It doesn't look very encouraging judging the status which reads: "_NEW bug found in Firefox 57 which will not be worked on by staff, but a patch will be accepted_". 

I didn't realize that Waterfox was based on FF Photon which is what all the bug reports refer to so I guess it'll inherit all of the issues as they occur. Just have to live with it I suppose.

**Comment by grahamperrin** [comment]
> … I didn't realize that Waterfox was based on FF Photon …

Waterfox 56.0 was based on Firefox 56.0.2, but I shouldn't think of it as based on (FF) Photon. https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-376351366 should help to put Photon and Quantum in a Waterfox context. 

More generally: https://design.firefox.com/photon/welcome.html

**Comment by Telmesomething** [comment]
> Waterfox 56.0 was based on Firefox 56.0.2, but I shouldn't think of it as based on (FF) Photon.

I only mentioned Photon because most of the bugzilla reports you linked to mention that.

**Comment by grahamperrin** [comment]
OK, sorry if you were misled.
