### ISSUE TITLE
Setting to always allow fullscreen videos.

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#536]
Hi!

It's a never ending issue that websites embed videos without enabling fullscreen view. It would be nice if I could set the browser to always allow this no matter how they embedded the video.

**Comment by MrAlex94** [comment]
Would this [work](https://support.mozilla.org/en-US/questions/1112707#answer-851412)?

**Comment by mzso** [comment]
[**@MrAlex94**](https://github.com/MrAlex94) commented on [2018. máj. 8. 21:29 CEST](https://github.com/MrAlex94/Waterfox/issues/536#issuecomment-387515706 "2018-05-08T19:29:44Z - Replied by Github Reply Comments"):
> Would this [work](https://support.mozilla.org/en-US/questions/1112707#answer-851412)?

Sort of, I think. But it sucked. (I can't find one right now)
If I remember correctly the browser default controls showed up instead of the proper youtube stuff.

Also it's cumbersome to do.
