### ISSUE TITLE
OWA (Outlook Web Access) issues

### ISSUE THREAD

**Issue by TheAquir** [BrowserWorks/waterfox#537]
Hi guys,

I have some weird issue with selecting fields and/or control in Outlook Web Access.

You can see here that I'm unable to click to the DropDown next to the Reply all
![owa reply all](https://user-images.githubusercontent.com/15109477/39249199-033c65d8-4896-11e8-8694-686ab6316cfe.gif)

here I'm unable to edit the Subject (or the control is not "starting" in the right position) but it's working in FF56 (FF56 on the left and WF on the right)
![owa subject](https://user-images.githubusercontent.com/15109477/39249200-036211ac-4896-11e8-8a59-03191baafd99.gif)

on the last screencap you can see that I'm unable to click to the Pencil to edit the Draft or I can bit clicking to te very top pixels or whatever. The Discard button is not working at all
![owa edit draft](https://user-images.githubusercontent.com/15109477/39249201-0384e574-4896-11e8-80e0-4486590da942.gif)

Again, everything works in FF56 portable or in any other browsers and yes, I have some extensions installed but I'm getting the same issues even when I disable all of them.

Any ideas?

Cheers!

**Comment by grahamperrin** [comment]
https://www.reddit.com/r/waterfox/comments/7bj77g/-/dx12nol/ – try disabling Stylo.

**Comment by TheAquir** [comment]
Thanks mate! It worked! Cheers
