### ISSUE TITLE
gamechangercharity.org website crashes all tabs

### ISSUE THREAD

**Issue by rwaguy** [BrowserWorks/waterfox#540]
YouTube's jacksepticeye just announced that he's holding a charity event tomorrow, but when I clicked on the link in his description, the site partially loads, then crashes all of the browser tabs that are open.

The browser doesn't freeze up or completely crash, but the page remains blank and other unrelated tabs have to reload when you switch to them.

**Comment by MrAlex94** [comment]
Have you tried disabling Stylo? about:config > layout.css.servo.enabled
toggle to false.

**Comment by rwaguy** [comment]
Yep, disabling Stylo fixed the problem.  Thank you for the quick reply!

**Comment by grahamperrin** [comment]
+1

Crashing at https://gamechangercharity.org/ and https://gamechangercharity.org/our-mission/ with the green and blue lines that slide in and intersect, on the left hand side, immediately after load completes. 

Not crashing at <https://gamechangercharity.org/ggb/>, which has the animated drop-down banner but not the animated lines.
