### ISSUE TITLE
mouse back/foward buttons are not working (mac)

### ISSUE THREAD

**Issue by azaraks** [BrowserWorks/waterfox#541]
Other browsers - FF, Opera, Chrome - support back/foward buttons on Logitech MX.
But I can't use those buttons with Waterfox.

**Comment by MrAlex94** [comment]
Are there drivers needed for it? Any chance that the drivers look for the browser to implement functionality for? WF hasn't changed anything in regards to mouse buttons etc.

**Comment by azaraks** [comment]
You are right! Haven't thought about that.
Confirmed it only worked with major browsers and Finder.
Sorry for asking w/o deep looking and thanks for you reply.
