### ISSUE TITLE
Installing Extensions

### ISSUE THREAD

**Issue by kaecy** [BrowserWorks/waterfox#546]
Is there no way to install chrome style extensions through the program? I want to be able to install them whether it be from a file on github or the local hard drive.

My first extension for waterfox: https://github.com/kaecy/waterfox_uri
It just redirects waterfox.org to the actual waterfox home page. But there's no way to install it locally like a regular extension.

**Comment by Peacock365** [comment]
I think that this is what you want:

https://addons.mozilla.org/firefox/addon/chrome-store-foxified/

_Keep in mind though, if the developer offers the same extension for Firefox / Waterfox, installing the FF/WF version is always preferable._

**Comment by laniakea64** [comment]
> there's no way to install it locally like a regular extension.

What happens when you attempt to do so?

**Comment by kaecy** [comment]
![image](https://user-images.githubusercontent.com/4354982/39796551-1529b188-534f-11e8-9a41-21db8bf890d2.png)

It works with signed extensions but not with non-signed extensions.

**Comment by laniakea64** [comment]
Unsigned WebExtensions work fine for me.  Your example extension requires signing because its `manifest.json` doesn't specify an addon ID.  See https://developer.mozilla.org/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID

**Comment by kaecy** [comment]
Yeah that was it. I saw that error in the browser window but I didn't think it was important. Thanks. I'll be releasing unsigned extensions from now on. 😄
