### ISSUE TITLE
Miscellaneous links that need to be changed in Waterfox.

### ISSUE THREAD

**Issue by Peacock365** [BrowserWorks/waterfox#548]
Hey there!

This is a short list of links that still point to wrong targets in Waterfox, and which certainly need to be changed:

- [x] In the Sync submenu in the settings, the Android link does not point to Waterfox's Play Store entry, but to a Mozilla page.

- [x] In the Sync submenu in the settings, it still says "Android _and iOS_". Due to Waterfox not having an iOS app, the "_and iOS_" part needs to be removed. Note though that this might have implications for the language packs which possibly also need to be modified.

- [x] In the settings, the "Help" footer at the bottom left of the page points to a Mozilla page instead of https://www.reddit.com/r/waterfox/ (which would be my suggestion).

- [x] Same goes for the "Help" entries under the Help menu  in the main menu bar and in the hamburger menu.

- [x] Under the Help menu in the main menu bar, there is a "Submit Feedback" entry. If you want to keep it, this should probably also point to the Waterfox subreddit. Although this would be just a duplicate of the "Help" entry, which may render "Feedback" obsolete.

That's all. Hope those get fixed.

**Comment by ghost** [comment]
Hi!

I just created a PR at #549, which will fix the first two issues, that you mentioned. 

And I'll take a look at the other issues regarding the help entries. I also think we should let them point to [https://www.reddit.com/r/waterfox/](https://www.reddit.com/r/waterfox/) instead, since it already does that in the android app, I think.

**Comment by grahamperrin** [comment]
A little duplication here; 

> … Under the Help menu in the main menu bar, there is a "Feedback" entry. …

That's [Waterfox ▸ Help ▸ Submit feedback… · Issue #399 …](https://github.com/MrAlex94/Waterfox/issues/399)

> … "Help" entries under the Help menu …

That's [Waterfox ▸ Help ▸ Waterfox help · Issue #400 …](https://github.com/MrAlex94/Waterfox/issues/400)

**Comment by Peacock365** [comment]
@Toromino 

Thanks for having fixed the first ones already. This was rather quick. Amazing!

@grahamperrin 

Thanks for adding context, I didn't know that issues were already created for some of them. When the fixes arrive, you may close them as well.

**Comment by grahamperrin** [comment]
AOK 👍

**Comment by Peacock365** [comment]
@grahamperrin 

#400 is already fixed at large though, you may want to close this one.

**Comment by Peacock365** [comment]
@Toromino 

What is the status of the last three issues? And would it be possible to fix #387 in the same manner?

**Comment by ghost** [comment]
@Peacock365 

Sorry for the delay! I've already written a patch to change the URL of the help buttons and remove the "Submit Feedback" entry, but I didn't test it yet. As soon as I can verify that it's working, I'll create a PR. (Most likely tomorrow) :)

I've also already looked into #387, but came up with no solution yet.

**Comment by Peacock365** [comment]
@Toromino 

Your commit regarding the removal of the iOS link doesn't seem to be effective here in all cases. The following occurs:

_browser.preferences.useOldOrganization_ - **true** (old preferences layout):

-> iOS link still appears.

_browser.preferences.useOldOrganization_ - **false** (new preferences layout)

-> iOS link is gone.

**Comment by grahamperrin** [comment]
#538

**Comment by laniakea64** [comment]
The iOS links aren't completely removed.  The remnants are causing errors in self build from https://github.com/MrAlex94/Waterfox/commit/bd915a697f53c663e5517adb99cb47e75b547949 .

With `browser.preferences.useOldOrganization` set to `false`, opening `about:preferences` gives this error -
```
TypeError: document.getElementById(...) is null  chrome://browser/content/preferences/in-content-new/sync.js:146:5
```

With `browser.preferences.useOldOrganization` set to `true` (the default), I get this when opening the Sync preferences...
```
TypeError: document.getElementById(...) is null  chrome://browser/content/preferences/in-content/sync.js:147:5
```
... and sometimes I can't even open the Sync preferences, getting this error in addition -
```
Error initializing preference category paneSync: TypeError: document.getElementById(...) is null  preferences.js:178
	gotoPref chrome://browser/content/preferences/in-content/preferences.js:178:5
	init_all/< chrome://browser/content/preferences/in-content/preferences.js:70:50
	_fireOnSelect chrome://global/content/bindings/richlistbox.xml:78:13
	selectItem chrome://global/content/bindings/listbox.xml:255:11
	onxblmousedown chrome://global/content/bindings/listbox.xml:1033:13
```

**Comment by Peacock365** [comment]
@laniakea64 

I agree, this should be fixed ASAP. Are you able to create a commit yourself? If not, would @Toromino or @MrAlex94 be able to fix it?

**Comment by ghost** [comment]
@Peacock365 @laniakea64 

Sorry! I created a PR at #568 to fix this issue.

**Comment by Peacock365** [comment]
@Toromino 

Thank you for the extremely quick fix. 

But then, the iOS link **still** shows up when the old preferences layout is used. The link reminds me of Michael Myers from the Halloween horror franchise, hope you get the pun.

Regarding the last issues: I think the Help entries could be changed safely, with the Feedback I would be more careful. Perhaps it would make sense to split a potential commit in two parts.

**Comment by laniakea64** [comment]
> But then, the iOS link **still** shows up when the old preferences layout is used.

Yeah I'm seeing this too.  Looks like each preferences layout has one iOS link for without Firefox Account, and a separate iOS link for with Firefox Account.  Only one iOS link got removed from each preferences layout, each layout still has one iOS link left.

https://github.com/MrAlex94/Waterfox/blob/bd915a697f53c663e5517adb99cb47e75b547949/browser/components/preferences/in-content/sync.xul#L77-L80

https://github.com/MrAlex94/Waterfox/blob/bd915a697f53c663e5517adb99cb47e75b547949/browser/components/preferences/in-content-new/sync.xul#L219-L221

**Comment by ghost** [comment]
@laniakea64 @Peacock365 

Thanks for pointing that out! I really thought I removed everything related to this iOS link... :/
I just added a fix to my PR at #568. 

And yep I got that pun, Michael Myers' theme is also playing in my head right now. :)

**Comment by ghost** [comment]
I created a PR for the help entries at #573. I haven't touched the "Submit Feedback" entry. This may need further discussion in #399, as it seems that there are mixed opinions about this.

**Comment by Peacock365** [comment]
Thanks for having taken care of the Help buttons. Regarding the "Submit Feedback" entry, I'd say remove it. We don't have a feedback page other than the Waterfox subreddit, and the Help button is already pointing to that one. Feedback is a redundant duplicate in our scenario.

**Comment by Peacock365** [comment]
@Toromino 

Any news regarding the "Submit Feedback" entry? I merely want to make sure that it isn't somehow forgotten.

**Comment by ghost** [comment]
@Peacock365 

It won't be forgotten. Fixing this would be a trivially easy thing. 

I wanted to wait for some feedback at #399 first, but as no one seems to have an objection, I might just create a PR.

**Comment by Peacock365** [comment]
@Toromino 

As I said, we don't have a feedback page, and duplicates are not what a good UI should aim for. I'd say go ahead with it. If @MrAlex94 has any issue with the removal, I think he'll voice it ahead of merging the change in.

**Comment by Peacock365** [comment]
@Toromino, thanks for your efforts up unto this point. One more link to be removed: "_Check to see if your plug-ins are up to date_" at about:addons! It can be seen at the top left, on the left side of the cogwheel. The site it links to: https://www.mozilla.org/plugincheck/ is no longer operational, it's dead. So this link can be safely removed, as it no longer provides any functionality.

Issue #336 and #357, for reference.

**Comment by ghost** [comment]
@Peacock365 I agree, there is no reason this link should be kept. I'll look into it.

**Comment by Peacock365** [comment]
@Toromino 

Is any patch in sight? Once this last patch is realized, I think we have at large removed / changed all links that needed to be changed. Good work.

**Comment by grahamperrin** [comment]
From [UX of Refresh Waterfox · Issue #562 …](https://github.com/MrAlex94/Waterfox/issues/562): 

![2018-06-16 07 36 41](https://user-images.githubusercontent.com/192271/41496908-4e496722-7142-11e8-9e0f-42949c430821.png)

The link should be to a Waterfox support area, not Mozilla's area for Firefox.

**Comment by Peacock365** [comment]
@Toromino 

Have you had any positive testing results? I am asking this because I brought this up a month ago, and fear that it has somehow been forgotten.
