### ISSUE TITLE
Be less browser-specific when continuing to AMO with any search that begins at about:addons

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#550]
<strike>It's that time</strike>

`https://github.com/mozilla/addons/issues/11563` (thanks to @jbeich) draws attention to areas of mozilla-central that relate to platform-specificity. 

For now, for Waterfox 56.1.1 (assuming that 56.1.1 will follow 56.1.0), let's cease adding this part of the tail: 

`&appver=56.1.0`

## Background

1. From [Legacy Add-on Support on Firefox ESR | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/2017/10/03/legacy-add-on-support-on-firefox-esr/) (2017-10-03): 

>> AMO (addons.mozilla.org) will continue to support legacy add-on listings throughout the ESR 52 cycle. 

2. today's https://redd.it/8ij7xk

**Comment by grahamperrin** [comment]
Sorry. Major brain fart! I wrongly associated the release of Firefox 60 with the end of the cycle for Firefox ESR 52. 

**Correction**: we'll eventually have Firefox ESR 52.9 until the **2018-09-05** release of Firefox 62.

https://wiki.mozilla.org/Release_Management/Calendar

**Comment by MrAlex94** [comment]
I don't believe WF does this anymore? I see it appends the following: https://addons.mozilla.org/en-US/firefox/themes/**?src=firefox**

[This pref](https://github.com/MrAlex94/Waterfox/blob/04c6debaf8d1391ea48b3872019a3aa38a1f211e/browser/app/profile/firefox.js#L53) isn't used anymore.
