### ISSUE TITLE
about:addons ▶ Appearance ▶ seeking themes (personas) is unreliable

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#552]
## Example A

Seeking _Spring Garden Serenity_: 

- switches from _Appearance_ to _Search_ and finds nothing
- should find _Spring Garden Serenity_ e.g. (en-GB) <https://addons.mozilla.org/en-GB/firefox/addon/spring-garden-serenity-madonna/>

## Example B

Seeking _Quantum Launch_: 

- switches from _Appearance_ to _Search_ and presents a few things at `about:addons` but not _Quantum Launch_, and the top result is not a persona.

Continuing to AMO (in my case, _See all 174 results_ leading to <https://addons.mozilla.org/en-GB/firefox/search/?q=quantum%20launch&platform=FreeBSD&appver=56.1.0>) finds _Quantum_ (with `quantum-launch` in the URL) uppermost: 

- https://addons.mozilla.org/en-GB/firefox/addon/quantum-launch/?src=search

----

Tested first with Waterfox 56.1.0.89 on FreeBSD-CURRENT. 

Example A has the same result with 56.1.0 on build 16G1404 of Mac OS X 10.12.6. 

----

Not an issue with e.g. Firefox Nightly 62.0a1, AFAIK because Firefox no longer presents add-on search results at `about:addons`.

**Comment by grahamperrin** [comment]
#538 for (at least) example A.

**Comment by MrAlex94** [comment]
The UI for this has been removed.

**Comment by grahamperrin** [comment]
I'm not familiar with what came before … but with 56.2.1, I see the _Search all add-ons_ field when _Appearance_ is selected; it's use of this field that's bugged. 

Maybe an issue on the Mozilla side. 

In any case: not a major issue. There's the future variant of Waterfox to look forward to.
