### ISSUE TITLE
Scrollbars disappear on Github

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#554]
Waterfox 56.1.0 (Self build, but not 100% sure the exact commit.  This issue definitely started **before** the update to new Skia.)
Xubuntu 18.04 64-bit
new profile

**Steps to reproduce:**

1) un-maximise the Waterfox window if it's maximised

2) go to `about:addons` by typing it in the address bar

3) go to `github.com/MrAlex94/Waterfox/issues` by typing it in the address bar

**Expected results:** see a scrollbar on the right

**Actual results:** No scrollbar.  It's not even invisible-but-there.  It's just gone.  I have to use mouse wheel to scroll.

I'm not 100% sure the exact commits of my good build & my bad build, but maybe we can guess from build ID?  I'm pretty sure all my recent builds are from latest master at the time.  Certainly the first bad one was.

Good:
```
Services.appinfo.platformBuildID
"20180430210556"
```
Likely built from https://github.com/MrAlex94/Waterfox/commit/d5c25411b0838a4578f8a96aa2e09568d900e9b6

Bad:
```
Services.appinfo.platformBuildID
"20180512115828"
```
Likely built from https://github.com/MrAlex94/Waterfox/commit/2bb1a86e5dbd601cd3b8812e45b69060e1f636de

**Comment by laniakea64** [comment]
These messages appear in the Browser Console when this issue occurs -
```
Content Security Policy: The page’s settings blocked the loading of a resource at chrome://global/content/bindings/scrollbar.xml (“default-src 'none'”).  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at chrome://global/content/platformHTMLBindings.xml (“default-src 'none'”).  (unknown)
```

This regression is caused by https://github.com/MrAlex94/Waterfox/commit/55bef81d59af600d8b68bfd51d654dc887203176 .  Reverting that commit fixes this issue.

**Comment by jbeich** [comment]
Can you reproduce with e10s disabled? 55bef81d59af caused [2 more](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=blocked%3A1432358+status%3Aresolved) regressions (425c5a6ff8fc, e8f515046724) but they look unrelated.

**Comment by laniakea64** [comment]
> Can you reproduce with e10s disabled?

I'm not seeing this with e10s disabled.

**Comment by grahamperrin** [comment]
Yep, <https://testpilot.firefox.com/> is similarly affected with multi-process enabled: 

![2018-05-13 20 09 36](https://user-images.githubusercontent.com/192271/39970820-0674bf68-56ea-11e8-8a82-740264a8dfab.png)

`Content Security Policy: The page's settings blocked the loading of a resource at chrome://global/content/bindings/scrollbar.xml ("default-src https://testpilot.firefox.com").`

56.1.0.89 on FreeBSD-CURRENT.

**Comment by MrAlex94** [comment]
So the "fix" is [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1439444), but even after applying it CSP still blocks. Since Mozilla marked as Firefox 60 and below unaffected, I'm going to revert the patch for now, unless anyone else has any ideas.

**Comment by grahamperrin** [comment]
It's probably obscure enough to not block 56.2.0 release. I say _probably_ because (with e10s disabled so often) I might have missed other examples. 

Maybe mention it in the 56.2.0 blog post amongst a *short*list of known issues, with a simple workaround: 

- tab ▶ context menu ▶ Open in new non-e10s window

> … any ideas.

Yesterday I thought of `https://github.com/mozilla/testpilot/issues/2827` wondering whether it (or a related commit) might help to more positively identify a fix but somehow I doubt it.

**Comment by laniakea64** [comment]
already reverted - https://github.com/MrAlex94/Waterfox/commit/f18036641cb4f7921782d58598ffae1c13609ec8

**Comment by MrAlex94** [comment]
It causes other issues, if a website uses strict CSP then it blocks
in-browser elements (such as XML, which is why the scroll bar ends up being
blocked).

**Comment by grahamperrin** [comment]
#538
