### ISSUE TITLE
Extreme resource usage in 56.2 v 56.0.1

### ISSUE THREAD

**Issue by Chazfr** [BrowserWorks/waterfox#556]
Hi Alex or whoever…

I recently was forced to abandon Firefox for Waterfox due to the Firefox 57 release non-support of add-on critical to my operation. I was thrilled to find Waterfox 56.0.2 functioned perfectly with my critical add-ons… It was a lifesaver. The critical add-ons I use are Piro’s TreeStyleTabs, Quicksaver’s TabGroups, Char01’s  TabGroupsMEnu, and Quicksaver’s OmniSidebar. I  am currently operopreating with 486 open tabs in one instance of Waterfox. I believe there is a bright and expanding future for Waterfox and would like to engage in a dialog in that regard. Is that possible?

However, I recently upgraded to 56.1.0 and now find that it has become a resource hog and spends most of its time saying it is not responding, though eventually it does. Systems Internals’ Process Explorer, shows memory and CPU usage nearly double the usage of 56.0.2. Is there a bug or design  flaw causing issues? Is equipment upgrade a requirement? If it would help, I would be happy to provide remote access to my computer. I have an entire business operational back office built around this browser, and I simply need it to work as it has in the past. If that is no longer possible, I need to know, so I can determine a course of action to regain control of my back office, as what previously took seconds now takes several minutes, or fails altogether.

**Comment by MrAlex94** [comment]
Hi,

Firstly please try disabling stylo: `about:config` > `layout.css.servo.enabled` and set to `false`.

Please let me know if that makes any difference.

**Comment by grahamperrin** [comment]
Please also disable multi-process. 

[TabGroups Menu compatibility reports](https://addons.mozilla.org/compatibility/reporter/tabgroupsmenu%40char.cc)

(Firefox automatically disables multi-process, when incompatible extensions are enabled. Waterfox does not.)

**Comment by Squall-Leonhart** [comment]
frankly, i'd get rid of the incompatible extension,  with that many tabs a single process is going to be a dog.

**Comment by grahamperrin** [comment]
YMMV. 

I habitually work with many tabs with multi-process disabled (for compatibility with extensions). More than 99% of the time the resource usage is proportionate to the degrees to which I 'push' things. 

Just rarely, there's an extreme for which I can't find, or guess, a reasonable explanation. https://www.reddit.com/comments/8jhzsj/-/dz074yy/ yesterday for example, with<strike> a pre-release of 56.2.0</strike> 56.1.0.111172; and this evening I had my first inexplicable incident with 56.2.0.7 (56.2.0 build 20180515213058) on FreeBSD-CURRENT. 

This is _not_ to assume the same cause(s) in my case(s) as in Chazfr's case, but IMHO it's worth tracking. 

– thanks
