### ISSUE TITLE
Firebug causes Waterfox to crash

### ISSUE THREAD

**Issue by CactusPie** [BrowserWorks/waterfox#56]
Firebug 2.0.16 causes Waterfox 44.0.3 to crash. It only happens after opening the developer console (F12) and the crash doesn't occur immediately. It might take a couple of minutes or it might take an hour for it to crash, it seems random. The crash doesn't seem to happen on regular Firefox. Here is the debug info from crash log:

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: waterfox.exe
  Application Version:  44.0.3.5892
  Application Timestamp:    56c5f716
  Fault Module Name:    xul.dll
  Fault Module Version: 44.0.3.5892
  Fault Module Timestamp:   56c5f983
  Exception Code:   c0000005
  Exception Offset: 0000000005f1db52
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1045
  Additional Information 1: 818e
  Additional Information 2: 818ee5bc2647c157015bacf0a1429400
  Additional Information 3: 3b4c
  Additional Information 4: 3b4cc49b1bff7a8c08c159cabb2d5490

**Comment by MrAlex94** [comment]
This should be fixed in 46+, reopen if you're still have issues.
