### ISSUE TITLE
About the bookmarks and the interface of any websites 

### ISSUE THREAD

**Issue by WagnerGMD** [BrowserWorks/waterfox#563]
Hello,

I'm just wondering if you could :
- create inside the profil one folder called **chrome** ?
- and add these files : **userContent.css** and **specially the userChrome.css** ?

To resume, sometimes the people just want the simple solution. It might be a better idea than to have to install an addon.

What about **one button to export or import the bookmarks ?** I think about since several years but Mozilla seem's far away to listen.
By the way, could you explain how to get the right extension ? Because I want a **.jsonlz4** instead of (the usual or normal) **.json** file. Just open the profil (inside the folder **bookmarkbackups**) and you will see the difference (the size is very light).

Kind regards.

**PS :** I didn't follow the story (sound bad) about [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/). But apparently there is (at least) one fork (Stylus ? etc).
Otherwise there is also [the CustomCSSforFx](https://github.com/Aris-t2/CustomCSSforFx/releases/) as another solution but that's too much.

**Comment by criztovyl** [comment]
I am currently using this approach with Waterfox to make it play nice with GTK dark theme enabled.

**Comment by WagnerGMD** [comment]
**As reminder :**

1. At first, you must create one folder called **chrome** (inside the **profile**).
2. Then create the file : **userContent.css**.
3. You need one exemple ? Just recopy the code (as below).
4. Don't forget to restart the browser (Waterfox, Firefox, Cyberfox, etc).
```
@namespace xul url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@namespace html url(http://www.w3.org/1999/xhtml);
@-moz-document domain("reddit.com")
{
	.fggbYQ,.fQMRlP,#hamburgers,.bGDHLv,.cxXdcf{display: none !important;}
	#eu-cookie-policy,#uapp-banner{display: none !important;}
	.fOVPWD,.VWHvb{margin-left: 0 !important;}
}
@-moz-document domain("stackoverflow.com")
{
	#sidebar,.z-banner,.vote,#dfp-tlb,#dfp-mlb,.old-hero._fixed{display: none !important;}
	.post-layout{display: block !important;width: 1100px !important;}
}
@-moz-document domain("paypal.com")
{
	#gdprCookieBanner{display: none !important;}
}
@-moz-document domain("github.com")
{
	.container{width: 1200px !important;}
	.discussion-timeline{width: 950px !important;}
}
@-moz-document url("about:newtab")
{
	#newtab-search-container{display:none !important;}
}
```
**PS :** If you need one explanation (or commentary), let me know.
