### ISSUE TITLE
Bookmarks followed by separators lose descriptions upon HTML import

### ISSUE THREAD

**Issue by Lorienna** [BrowserWorks/waterfox#564]
Upon importing from HTML, bookmarks lose their descriptions if followed by `<HR>` separators.
The regression only affects the bookmark items, not the folders.

### Steps to reproduce:

1. Create a new bookmark or select an already existing one.
2. Fill the description field of this bookmark with text.
3. Right-click and create a new separator following this bookmark.
4. Export the bookmarks to HTML.
5. Import the `bookmarks.html` file created in the step 4.

### Actual results:

The description field of the bookmark is empty.

### Expected results:

The text in the bookmark's description field to be kindly preserved.

---

You can have a look at how the Pale Moon team solved the same issue, and perhaps follow the cue:
https://github.com/MoonchildProductions/UXP/commit/442e2e04efa366a08f6b278e5241d53ba85d1d04

**Comment by ghost** [comment]
Hi!

I could reproduce this issue on my end and it could be solved by implementing Pale Moon's fix. I created a PR at #574 to adopt their solution.

**Comment by Lorienna** [comment]
@Toromino Thank you!

**Comment by Peacock365** [comment]
As this was fixed by https://github.com/MrAlex94/Waterfox/commit/e1d5df5b5a897099562b0554f14d22ea5e7f8eaa ... Please consider to close the issue, @Lorienna. Thank you.

**Comment by Lorienna** [comment]
Thank you for your kind efforts, gentlemen.
