### ISSUE TITLE
Building fails on Linux

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#565]
I'm currently not able to build Waterfox on Linux...

- The first issue occured, when mach tried to compile 'simd'. 'x86::sse2' is an unresolved import in third_party/rust/simd/src/common.rs:17:10. Could prevent this error by removing "ac_add_options --enable-rust-simd" in .mozconfig
![screenshot_1](https://user-images.githubusercontent.com/15093096/40125152-81e328aa-592a-11e8-8401-5c76774e0c2d.png)

- Then it seemed to be compiling for a while, when building failed again at: 
![screenshot_2](https://user-images.githubusercontent.com/15093096/40125288-d8132702-592a-11e8-9c6f-69d5b2c13bb4.png)

- When I acutally add "--disable-elf-hack" as an option, building just fails without any error output

I've already tried it on a variety on distros (Fedora, Debian and Ubuntu) and always stumbled upon the same errors. Nothing changed when I tried to build the newest tagged release instead of 'master'.

**Comment by hawkeye116477** [comment]
I tried to build and no errors, but I compiled it on Manjaro Linux with Rust 1.25 :smile:. What's your Rust version?

**Comment by ghost** [comment]
My main distro (Fedora) runs rustc 1.25.0, but I also tried it with older Rust versions on Debian.

**Comment by MrAlex94** [comment]
I can't reproduce this either. Build system is Debian 9 using Clang 3.8 and
Rust 1.26. Have you done a clobber?

**Comment by ghost** [comment]
I tried to build again after doing a clobber. Now I'm back to this output:
![image](https://user-images.githubusercontent.com/15093096/40131614-c69abbe2-593a-11e8-89f4-1925d80fb566.png)

**Comment by jbeich** [comment]
Ah, wait. That's a different issue. ;)

**Comment by jbeich** [comment]
> 'x86::sse2' is an unresolved import in third_party/rust/simd/src/common.rs:17:10

See https://github.com/rust-lang/rust/issues/46181. Upgrade Rust to 1.26 or build Rust against bundled LLVM.

**Comment by alekksander** [comment]
i can't even get it started under ubuntu 16.04. giving me:
```
~$ waterfox
XPCOMGlueLoad error for file /opt/waterfox/liblgpllibs.so:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/waterfox/liblgpllibs.so)
Couldn't load XPCOM.
```

**Comment by ghost** [comment]
@alekksander Did you make sure, that libc6 is installed? You might wanna install it using: `apt-get install libc6`

**Comment by hawkeye116477** [comment]
@alekksander Have you waterfox or waterfox-kde?

**Comment by alekksander** [comment]
@Toromino „libc6 is already the newest version (2.23-0ubuntu10).”
@hawkeye116477 indeed it is Your build (waterfox-kde), i completely forgot!

**Comment by hawkeye116477** [comment]
@alekksander That's the problem. I have newer libs, Clang (6), Llvm than Alex and something probably broke compiling with statically linked libstdc++ and I later noticed same error about elf-hack as @Toromino. I will publish fixed version when I find fix for this, cuz I unfortunately for now don't have that distro with that old tools :smile:. Previous version I compiled with Clang/Llvm 5, so maybe it's issue with Clang/Llvm 6...

**Comment by ghost** [comment]
I managed to get rid of the errors, that I mentioned earlier by using Arch Linux this time. But now I get this error, when I try to run `./mach bootstrap` 
![image](https://user-images.githubusercontent.com/15093096/40273393-194d142c-5baf-11e8-98ab-2d746defaa23.png)

**Comment by hawkeye116477** [comment]
@Toromino Are you sure that you have Clang installed? Just do `sudo pacman -S clang` :smile:

**Comment by ghost** [comment]
Yep it is installed.
![image](https://user-images.githubusercontent.com/15093096/40273501-835c03cc-5bb0-11e8-940b-ece5a55f244f.png)

**Comment by hawkeye116477** [comment]
@Toromino Ok, so probably something else is missing. Check if you have everything that requires waterfox-git package from AUR.

**Comment by ghost** [comment]
The dependency ffmpeg2.8 (although I do have ffmpeg installed) is missing when I try to user Waterfox-git. But I don't think it has anything to do with my current error. 

I also just tried the same mach command with Firefox's source and it worked fine.

**Comment by jbeich** [comment]
@Toromino, in `./mach bootstrap` choose `2. Firefox for Desktop` as [artifact mode](https://developer.mozilla.org/en-US/docs/Artifact_builds) is not supported by Waterfox.

**Comment by ghost** [comment]
@jbeich 
The thing is, I've never chosen artifact mode. I always chose "2. Firefox for Desktop". :/

**Comment by ghost** [comment]
Okay folks, apparently Waterfox **does** build fine now! 
Although mach shows that building failed, the built version works fine. o_O

**EDIT:** I guess I can close this issue as building Waterfox on my Linux machine works fine now.

**Comment by hawkeye116477** [comment]
For me, it showed that build is successfull, but I used patch from `https://bugzilla.mozilla.org/show_bug.cgi?id=1384062`. I only got error/failures about test-ctors.so and elf-hack, but built was succesfull and worked for me, but apparently it didn't statically linked libstdc++, so it caused error on those peoples distros that has lower version of libstdc++ than me (I have 2.27-3).
