### ISSUE TITLE
waterfox 46 netflix

### ISSUE THREAD

**Issue by theQ23** [BrowserWorks/waterfox#57]
Netflix does not work on the latest version of waterfox. I get error 7352 use official version of firefox. i tried changing my user-agent string but that didn't work.

**Comment by MrAlex94** [comment]
Thanks for the heads up, am looking into this.

**Comment by MrAlex94** [comment]
Okay so I can't seem to reproduce this issue. If you go to about:plugins, is Silverlight listed there?

**Comment by MrAlex94** [comment]
If you go to about:config and change **general.useragent.override.netflix.com** to **Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0**, does Netflix start working again?

**Comment by LC21** [comment]
Just wanted to say that changing the user agent string to 44.0 fixes Netflix playback for me. Previously, I was getting error code N8202 when loading an episode on Netflix but it's working perfectly after the fix.

Is there a new useragent string for every version of Firefox?

**Comment by MrAlex94** [comment]
Looks like Netflix change their accepted user agents for Silverlight playback fairly frequently. I've set it at 38.X for the time being where Silverlight playback was still the main way.
