### ISSUE TITLE
About Waterfox does not display correctly in some cases

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#571]
From <https://github.com/MrAlex94/Waterfox/issues/567#issue-324079777> (edited) and <https://github.com/MrAlex94/Waterfox/issues/567#issuecomment-390153962>: 

> "About Waterfox" does not display correctly on my Mac (macOS High Sierra). The window is completely white with a black ramification / frame around it. A window does open, but no actual information is displayed. 

– and: 

> … I  have noticed a new issue on my Mac in relation to the "About Waterfox"  window. This issue is …. Please have a  look.

Not reproducible with build 16G1404 of Mac OS X 10.12.6 (macOS Sierra). 

I'll boot a pre-release of High Sierra …

----

Meta/tracking: #538

**Comment by grahamperrin** [comment]
@Peacock365 please, are you sure that this is an urgent issue? 

Can you reproduce it with Waterfox in safe mode? 

I can not reproduce the issue with build 20180515140315 of Waterfox 56.2.0 on the current pre-release build of High Sierra, 

```text
highsierra:~ grahamperrin$ date ; sw_vers
Fri 18 May 2018 21:12:37 BST
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F70a
highsierra:~ grahamperrin$ time sudo softwareupdate -l
Password:
Software Update Tool

Finding available software
No new software available.

real	3m17.683s
user	0m0.143s
sys	0m0.233s
```

**Comment by grahamperrin** [comment]
![2018-05-18 20 58 15](https://user-images.githubusercontent.com/192271/40255966-d6fd9548-5ae0-11e8-8b2f-76a4d29a8b55.png)

– MacBookPro8,2

**Comment by Peacock365** [comment]
Okay, it's no like I am not seeing the real "About Waterfox" window, ever. The problem is that in the vast majority of all cases, the issue you described in your initial post appears.

MacBook Pro 2015, macOS 10.13.4, Waterfox 56.2 if that helps.

**Comment by grahamperrin** [comment]
Thanks, can you take a screenshot when it next occurs? 

Graphics hardware?

**Comment by Peacock365** [comment]
My graphics card is the Intel Iris Graphics 6100 found in some MacBook Pro (2015) models. Intel Core i5.

There is nothing a screenshot could show really. The window is blank, no text is displayed whatsoever.

<img width="1280" alt="bildschirmfoto 2018-05-20 um 13 19 56" src="https://user-images.githubusercontent.com/37863161/40278445-7c841054-5c31-11e8-9bdb-0b929e3b0213.png">

**Comment by MrAlex94** [comment]
Not sure another issue needs to be open.

**Comment by MrAlex94** [comment]
Not sure another issue needs to be open.
