### ISSUE TITLE
Waterfox 56.2.0 on Mac OS X launching with an untitled dialogue with four buttons alone – Cancel | Go Back | Continue | Done

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#572]
Initially visible: 

- the Waterfox menu alone
- an untitled dialogue with a Waterfox icon near the top right corner
- four buttons, with emphasis on _both_ **Continue** _and_ **Done**

– critically, I **could not tell which of the two** would have been associated with <kbd>Return</kbd> or <kbd>Enter</kbd>.

## Screenshots

2018-05-18 18:04:54

![2018-05-18 18 04 54](https://user-images.githubusercontent.com/192271/40256092-40d73654-5ae1-11e8-94d5-b6985e25eeb6.png)

2018-05-18 18:07:15, with something other than the dialogue in front

![2018-05-18 18 07 15](https://user-images.githubusercontent.com/192271/40256109-51810868-5ae1-11e8-880d-f1a4c386e3a7.png)

## Observations

The **Go Back** button appears to have no effect; I guess that its effect is invisible. 

Whilst I can't easily tell the build of Waterfox (without a Help menu, and so on), the update to 56.2.0 was gained whilst booted from build 16G1404 of Mac OS X 10.12.6 (macOS Sierra).

## Test environments

Outdated pre-release build 17F35e of Mac OS X 10.13.5 (macOS High Sierra). We should tell whether this issue is reproducible with a current pre-release e.g. _Developer Beta (5)_ and/or a release. 

## Also

It may help to read this issue alongside: 

- [About Waterfox does not display correctly in some cases · Issue #571 …](https://github.com/MrAlex94/Waterfox/issues/571)

----

Meta/tracking: #538

**Comment by grahamperrin** [comment]
The **Cancel** button does respond to clicks but appears to have no effect; the dialogue remained on screen. 

I used the title bar to close the dialogue. 

A browser window appeared. 

Text from about:support will be at https://pastebin.mozilla.org/9085801 for one month. Build ID: 

- 20180515140315

----

OS update complete, restarting …

**Comment by grahamperrin** [comment]
Closed in error.

**Comment by MrAlex94** [comment]
I'm not sure I understand. When does this happen?

**Comment by grahamperrin** [comment]
Sorry, I should have made it clearer. 

> the update to 56.2.0 

– and it _might_ have been for a profile that was previously used with 56.1.0 but (sorry) I didn't keep a note of which profile was in use at the time.
