### ISSUE TITLE
Request of supporting 1Password extension

### ISSUE THREAD

**Issue by ann61c** [BrowserWorks/waterfox#576]
1Password extension is not able to use on Waterfox. Can you support that? I really like Waterfox.

Platform: macOS 10.13.4

Thank you

**Comment by grahamperrin** [comment]
[1Password X – Password Manager](https://addons.mozilla.org/addon/1password-x-password-manager/) 

- [version 1.7.3](https://addons.mozilla.org/addon/1password-x-password-manager/versions/?page=1#version-1.7.3)

– added to Waterfox 56.2.0 on FreeBSD-CURRENT. 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.7_1
$ date ; uname -v
Mon 21 May 2018 18:53:44 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

I'll share results.

**Comment by ann61c** [comment]
I am using standalone version of 1Password (sync with Dropbox). 1Password X may not able to use because it requires 1Password membership.

**Comment by grahamperrin** [comment]
Sorry for the misunderstanding. 

> … standalone version of 1Password …

Please, do you have a link for the extension? Or does installation of the extension become possible only after platform-specific installation of a separate application?

https://addons.mozilla.org/search/?q=1Password&type=extension has only one _1Password_ product in its first page of results.

**Comment by ann61c** [comment]
The extension can be downloaded [here](https://1password.com/browsers/). Open the link with Firefox or Waterfox, you will be able to download Firefox version. The name of the extension is 1Password extension (desktop app required)
![image](https://user-images.githubusercontent.com/3508411/40346993-3bf6b400-5dd1-11e8-9e40-8e6f0a35e41f.png)
![image](https://user-images.githubusercontent.com/3508411/40347073-81e515d8-5dd1-11e8-86fa-f265ea489edb.png)
(You can find that the 1Password icon is grey on Waterfox, and it is not able to click on.)

**Comment by ftntdlp** [comment]
Perhaps this is related NativeMessagingSupport that 1Password folks keep talking about in their threads?
https://discussions.agilebits.com/discussion/83487/waterfox-1password-extension-grayed-out-and-non-functioning
[
something similar for Firefox:
https://discussions.agilebits.com/discussion/84170/unable-to-use-1password-extension-in-firefox-native-messaging-must-be-enabled/p2
]
Ref: 
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

I am using Waterfox on macOS, and I am observing the same behavior described here.

This extension works in Firefox of course, and i see the following json file created under:
/Users/praveena87/Library/Application Support/Mozilla/NativeMessagingHosts/2bua8c4s2c.com.agilebits.1password.json

**Comment by grahamperrin** [comment]
Cross reference https://www.reddit.com/r/waterfox/comments/ag2ih1/-/ee9cxeu/?context=2

**Comment by grahamperrin** [comment]
Comparing this 1Password issue with https://www.reddit.com/comments/dpzvrw/-/f6b3nbf/ for RoboForm

If the issue here is IPC (native messaging) with **the 1Password application not messaging Waterfox**, then @MrAlex94 I can't foresee any change by Waterfox Project that might work around the design of the 1Password application.
