### ISSUE TITLE
https://github.com/browser-update/browser-update Water-/Fire-fox

### ISSUE THREAD

**Issue by ShonkaiDJ** [BrowserWorks/waterfox#577]
This may not be an issue. I am not a coder but an ICT-Support generalist. This post does not need an answer.

I just mean to notice that a german initiative https://github.com/browser-update/browser-update is adding warnings to websites to warn users their browser is out of date. I get these warnings too. Not only from them.
I already started the issue there that Waterfox is not Firefox and that it is not out of date. Yet if they cannot see it's Waterfox that that issue may need to be posted here.

**Comment by ilu33** [comment]
Ah thanks for the reminder - I need to spoof the user agent in Waterfox to get a generic Firefox UA. Annoying task but has to be done. And I always block their scripts anyway, I'm grown up, I can decide for myself.

**Comment by grahamperrin** [comment]
Thanks! 

From the closure of the linked issue: 

> Waterfox is now being whitelisted (for now).

– and the response from http://browser-update.org/ is good now.
