### ISSUE TITLE
Waterfox 56.2.0 about:addons installs a wrong, inferior, version of an extension on FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#578]
Most of what's below is probably FreeBSD-specific, but this issue will spin off into something more general …

## Steps

1. Create and use a new profile
2. install Add-on Compatibility Reporter 2.2.4
3. about:addons
4. seek _Disconnect_
5. observe the list of found extensions, with no invitation to 'See all _nn_ results' at its foot

## Expected

- Disconnect 5.18.21 at the head of the list

## Actual result

- Disconnect 3.15.3 at the head of the list
- install
- observe the requirement to restart (from past experience with Disconnect, this is where I realised that something was wrong)
- click 'Extensions'
- no hint that the extension is not compatible with multi-process

![2018-05-22 18 20 49](https://user-images.githubusercontent.com/192271/40380895-2e70723c-5df2-11e8-8ab4-bc3949ebb880.png)

- accept the invitation to restart
- about:addons
- still, no hint that the extension is not compatible with multi-process
- <kbd>Control</kbd>-<kbd>R</kbd> reload

> Disconnect 3.15.3… ⚠ Not compatible with multiprocess.

## Environment

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.13
$ date ; uname -v
Tue 22 May 2018 18:24:45 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

## Notes, thoughts

https://addons.mozilla.org/addon/disconnect/versions/ presents 5.18.21 as compatible: 

> Works with Firefox for Android 48.0 and later, Firefox 48.0 and later 

– **and** https://addons.mozilla.org/en-GB/firefox/search/?q=disconnect&platform=FreeBSD&appver=56.2.0 does not find the Disconnect extension. @jbeich this is reminiscent of _add-on services: Tier-3 platform BSD equivalence to Tier-1 Linux · Issue #4610 · mozilla/addons-frontend_ but that's a _front-end_ issue so I'm taking care to **not** link on this occasion:  

`https://github.com/mozilla/addons-frontend/issues/4610`

----

https://addons.mozilla.org/addon/disconnect/versions/?page=1#version-3.15.3.1-signed.1-signed presents the installed version as incompatible and: 

> Works with Firefox 1.5 - 31.* 

## The 'no hint' parts of this issue 

Maybe negligible. I think of Mozilla bug [1394225 - multiprocess (e10s) automatically enabled at launch after installing extensions that are not compatible with multiprocess](https://bugzilla.mozilla.org/show_bug.cgi?id=1394225), [comment 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1394225#c2) in particular. 

## Yellow alerts

There's one here: 

![2018-05-22 19 04 45 add-ons manager - waterfox](https://user-images.githubusercontent.com/192271/40381280-33ccca5e-5df3-11e8-8ec5-cbe4278134a4.png)

– so we might expect a user to be unsurprised by _later_ discovery that what was installed is incompatible. However there's a complication …

**Comment by Peacock365** [comment]
FreeBSD is not a platform officially supported by Waterfox. Can you reproduce the issue with a supported operating system? Please verify, otherwise a fix might be extremely hard to find, let alone done.

**Comment by jbeich** [comment]
> 2. install Add-on Compatibility Reporter 2.2.4

AMO [says](https://addons.mozilla.org/en-GB/firefox/addon/add-on-compatibility-reporter/) "This add-on has been removed by its author."

> 5. observe the list of found extensions, with no invitation to 'See all nn results' at its foot

Try replacing `%OS%` with `Linux` in `extensions.getAddons.search.url`. [Le Même en Mieux](https://addons.mozilla.org/firefox/addon/lmem/) is the only missing addon. Maybe `_parseAddons()` returns `aTotalResults == 0` on FreeBSD.

https://github.com/MrAlex94/Waterfox/blob/436898372f8589d4a241e924084119358c58bf45/toolkit/mozapps/extensions/internal/AddonRepository.jsm#L1226
https://github.com/MrAlex94/Waterfox/blob/436898372f8589d4a241e924084119358c58bf45/toolkit/mozapps/extensions/content/extensions.js#L2690

> Disconnect 3.15.3 at the head of the list

`about:addons` before mozilla/gecko-dev@0a51e1ac6452 showed results inline using a different API, see `resource://gre/modules/addons/AddonRepository.jsm`.

Results don't appear to vary between platforms
- [FreeBSD](https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/Disconnect/all/20/FreeBSD/56.2.0/ignore?src=firefox)
- [Linux](https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/Disconnect/all/20/Linux/56.2.0/ignore?src=firefox)
- [macOS](https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/Disconnect/all/20/Darwin/56.2.0/ignore?src=firefox)
- [Windows](https://services.addons.mozilla.org/en-US/firefox/api/1.5/search/Disconnect/all/20/WINNT/56.2.0/ignore?src=firefox)

but `about:addons` probably filters out non-compatible based on
```
  <all_compatible_os><os>Darwin</os><os>WINNT</os><os>Linux</os></all_compatible_os>
```

**Comment by jbeich** [comment]
Doh, `about:addons` filters out Disconnect because RDF contains:
```
  <all_compatible_os><os>Darwin</os><os>WINNT</os><os>Linux</os></all_compatible_os>
```

**Comment by grahamperrin** [comment]
Thanks, 

>> Add-on Compatibility Reporter 2.2.4

https://github.com/mozilla/addon-compatibility-reporter/releases/tag/2.2.4 (via the _Notes_ section of https://redd.it/8c77ii – apologies for the omission).

> … `extensions.getAddons.search.url` … 

Ah! `extensions.update.url` was suitably modified here weeks ago …

… I forgot about `extensions.getAddons.search.url`. Making the string Linux-specific causes Disconnect to not appear amongst results, which at first sight seems strange to me, but …

----

… I'm not in a rush to follow-up. A head-spinning day with extensions (identifying a possible bug in Extension Conflict Troubleshooter, then using the extension to identify issues involving three others, etc.) so I probably need to sit on this issue 578 for a few days. Regain head space. 

----

> … probably FreeBSD-specific, but this issue will spin off into something more general …
> 
> ## Yellow alerts
> 
> … a complication …

Pfft … the stuff that I wanted to spin off from there is no longer in my main profile. (I might have been trigger-happy with housekeeping a few months ago. Dug, found some screenshots from August 2017, not enough to jog my memory. Hopefully it'll come back when I get head space!)

**Comment by grahamperrin** [comment]
> Doh

Oh, comments crossed paths, sorry yours didn't appear until after I posted mine. I'll probably take a look later in the week. Thanks again.

**Comment by jbeich** [comment]
@grahamperrin, can you reproduce using www/firefox-esr (while it tracks 52.*)? Even after mozilla/gecko-dev@aeee1208082b AMO [can limit](https://services.addons.mozilla.org/api/v3/addons/search/?q=Disconnect) to specific platforms (i.e., `all_compatible_os` -> `platform`). Try asking Disconnect folks to publish the addon with `platform=all`.

**Comment by jbeich** [comment]
Fixed by freebsd/freebsd-ports@83794bc14760.

**Comment by Peacock365** [comment]
@jbeich 

Assuming this fixes the issue, why don't you create a pull request for this? I think everyone using Waterfox on a platform not officially supported could profit here.

_Off-topic:_ Same goes for issue #416, there you have brought up a fix, but that fix never made it into the repository. **Please**, if you have a fix for any issue at hand, create a pull request for it. Otherwise the issue is never going to be fixed.

**Comment by jbeich** [comment]
@Peacock365, the fix here is a barely tested ugly hack which needs more work: conditionals to not break addon compatibility on Windows/macOS, submitting upstream (Firefox) for review and anything else I've missed due to unfamilarity with addon machinery.

**Comment by Peacock365** [comment]
Ah, I see. In this case I assume it is better to wait until Mozilla has approved the fix (better safe than sorry).
And I didn't know that #416 is already fixed, nobody ever mentioned it in the issue itself.

Off-topic II: Some love for issue #373 would be nice as well, as you can see here Mozilla didn't bother to fix the bug at this point: https://bugzilla.mozilla.org/show_bug.cgi?id=1415921#c0 If you could fix it this would be really nice.

**Comment by grahamperrin** [comment]
OK, 

> can you reproduce using www/firefox-esr (while it tracks 52.*)? 

Maybe next week, although with time constraints etc. I can't promise. 

@jbeich in the meantime we have the positive test result <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226919#c17> for (marginally outdated) www/waterfox 56.2.0.13_1. **Big** thanks. 

> … Try asking Disconnect folks to publish the addon with `platform=all`.

A smart idea, however I'll defer any such request until after another issue (OT) is addressed.

**Comment by grahamperrin** [comment]
> www/firefox-esr

@jbeich I haven't found time (sorry), if I do then I'll follow up in a FreeBSD area. 

> Pfft … the stuff that I wanted to spin off … is no longer in my main profile. (I might have been trigger-happy with housekeeping a few months ago. Dug, found some screenshots from August 2017, not enough to jog my memory. Hopefully it'll come back when I get head space!)

I have not yet found what was lost, what I needed for the (non-FreeBSD-specific) spin-off issue. 

It's unlikely to resurface in the near future so we can close this issue 578. Thanks folks.
