### ISSUE TITLE
Waterfox web site issues (meta)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#582]
## Partial background

- https://blog.waterfoxproject.org/waterfox-56.0-release-download (2017-11-30) "… staging website is available to test at staging.waterfoxproject.org, …"
- https://redd.it/84hi0f (2018-03-14) "While the next version of Waterfox is being prepared … please check out and test the new Waterfox website before it all launches together: …"
- https://redd.it/87cmcu (2018-03-26) "Waterfox 56.1.0 Release - This release brings with it a brand new website, …"
- https://redd.it/8avoji (2018-04-09) "What do you think is missing from the website? Any bits of informations you’d like to know about but can’t find easily? An FAQ? Please let me know!"

**Comment by grahamperrin** [comment]
## FAQ ideas

From <https://github.com/MrAlex94/Waterfox/issues/484#issuecomment-398047779>: 

> … work on getting WF to pretend its v57 for the add-on store.

Maybe worth having an FAQ paragraph re: expected issues. I'll flesh this out nearer the time. 

### Waterfox Classic

From 603, as requested (condensed or moved): 

- [resource:// images don't work in old addons · Issue #647 …](https://github.com/MrAlex94/Waterfox/issues/647)
- [e10s: availability of multi-process with older versions of operating systems : waterfox](https://www.reddit.com/r/waterfox/comments/8rtb3l/e10s_availability_of_multiprocess_with_older/)
- multi-process by default, especially at refresh time, known issues with incompatible extensions ∴ users who choose to use incompatible legacy extensions should (if/when they learn of e10s stuff) proceed at their own risk
- location services may not work as expected (see for example https://www.reddit.com/comments/8xt831/-/e2aekc2/ ▶ https://www.reddit.com/comments/8oief0/-/e06jqjf/?context=1 and the more recent comments below <https://github.com/MrAlex94/Waterfox/issues/797#issuecomment-439760869>
- …

### Waterfox Current

- some of the above, I guess
- 
…

**Comment by grahamperrin** [comment]
Risks associated with unsigned extensions should be unmistakably clear. Have a line amongst answers to FAQ. 

----

[UX, privacy, security: consider defaulting to disallow unsigned extensions · Issue #695 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/695#issuecomment-404407672) 

If **suggestion 1** is implemented, then an additional answer can include direction to: 

- about:config?filter=xpinstall.signatures.required

**Comment by grahamperrin** [comment]
In the advanced dialogue at e.g. https://www.waterfoxproject.org/en-US/waterfox/new/?scene=1 maybe add _64-bit_ to the _Windows Portable_ link.

**Comment by grahamperrin** [comment]
[Please don't use tracking scripts on your website. : waterfox](https://www.reddit.com/r/waterfox/comments/aizc01/please_dont_use_tracking_scripts_on_your_website/)

**Comment by grahamperrin** [comment]
For reference only, I don't expect fixes for problems with Disqus service …

… this is typical, Disqus repeatedly failing to show responses: 

![image](https://user-images.githubusercontent.com/192271/52176420-81f8ca80-27aa-11e9-8c41-43d570fd4323.png)

[Reload (override cache)](https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_navigation) is, unfortunately, **not** a workaround when Disqus fails in this way. At the time of writing I have overridden the cache twice and still (as shown above), there's no trace of the response that I posted more than thirty minutes ago: 

![image](https://user-images.githubusercontent.com/192271/52176480-3a267300-27ab-11e9-8986-a676545039bd.png)

Problems involving the content delivery network(s) used by Disqus, <strike>I guess.</strike> maybe … maybe not (see below) …

### Postscripts

Not expecting fixes for problems with Disqus service because, for example, Disqus offered no response to https://twitter.com/grahamperrin/status/1045017746004684802 (2018-09-26).

Found today: 

- [Articles Missing Comments · Discuss Disqus · Disqus](https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/articles_missing_comments/) (four years ago, opening poster seriously disappointed by the absence of a response from Disqus, locked, I can't reply)
- [I'm constantly missing comments · Discuss Disqus · Disqus](https://disqus.com/home/channel/discussdisqus/discussion/channel-discussdisqus/im_constantly_missing_comments/) (three years ago, locked)
- [Use Configuration Variables to Avoid Split Threads and Missing Comments | Disqus](https://help.disqus.com/troubleshooting/use-configuration-variables-to-avoid-split-threads-and-missing-comments) (updated "over a week ago"; no visible date of publication but [Finitimus foxified](https://www.reddit.com/r/waterfox/comments/a9ztht/extension_popup_size_issue/ef5n78j/) shows 2015-10-20).

**Comment by grahamperrin** [comment]
`blog.waterfox.project.org` occasional/persistent error 502 (bad gateway) for some readers: 

- https://redd.it/ammote with a Ray ID at https://www.reddit.com/comments/ammote/-/efou7il/

**Comment by laniakea64** [comment]
> `blog.waterfox.project.org` occasional/persistent error 502 (bad gateway) for some readers:

Hi @MrAlex94 this problem has returned, for the past few days I have been consistently getting the 502 error when trying to access https://blog.waterfoxproject.org/ .

**Comment by grahamperrin** [comment]
Spun off from https://www.reddit.com/r/waterfox/comments/asb7hg/-/ehp16we/

Twitter's stretched representation of one of the logos that are currently used in Reddit: 

![image](https://user-images.githubusercontent.com/192271/54069566-2f9b4580-4251-11e9-9a9b-9652b4a0afaf.png)

@MrAlex94 if you can't easily find a Reddit-oriented fix for this, I _might_ be able to find some points of reference elsewhere.

**Comment by grahamperrin** [comment]
@laniakea64 do you have a Ray ID?

**Comment by laniakea64** [comment]
_(deleted, no longer relevant)_

**Comment by grahamperrin** [comment]
Old and new Reddit representations of the new logo in a Waterfox tweet: 

![image](https://user-images.githubusercontent.com/192271/54083735-e5cd6080-431f-11e9-8be2-8f9ff971fb82.png)

![image](https://user-images.githubusercontent.com/192271/54083747-039ac580-4320-11e9-9c33-d6c91d560b04.png)

![image](https://user-images.githubusercontent.com/192271/54083755-19a88600-4320-11e9-91d1-38737b5ea213.png)

Re: the cropping in new Reddit, I don't imagine an easy fix. 

(The cropping doesn't bother me; I prefer old reddit without the subreddit style.)

**Comment by MrAlex94** [comment]
Fixed blog issue, was due to nginx.

**Comment by grahamperrin** [comment]
Slight squashing of the logo at blog pages, for example: 

![image](https://user-images.githubusercontent.com/192271/54416004-fb62d180-46f5-11e9-9285-3019329eb50d.png)

**Comment by grahamperrin** [comment]
From <https://github.com/MrAlex94/Waterfox/issues/1128#issuecomment-530597752>

> … 18.04 is sufficiently new according to system requirements for Waterfox 68.0b1 listed on https://www.waterfox.net/releases/ -
> 
>> Linux
>> Min. OS: Any modern distro

From <https://www.reddit.com/comments/d38c3f/-/f03zg14/?context=3>: 

>>>> It seems that Alex compiled on much newer distro. …

> … Shouldn't the [releases page](https://www.waterfox.net/releases/) mention something different for **Min. OS**?

**Comment by grahamperrin** [comment]
@MrAlex94 

![image](https://user-images.githubusercontent.com/192271/65658071-148df880-e01e-11e9-9b82-6aa3bc6d3ee8.png)

**Comment by grahamperrin** [comment]
**Nit**

https://gist.github.com/MrAlex94 and https://github.com/MrAlex94 have outdated references to: 

- `https://www.waterfoxproject.org/`

(There's a redirect to <https://www.waterfox.net/>.)

**Comment by MrAlex94** [comment]
Thanks for the pings. Website is being re-done 👍

**Comment by grahamperrin** [comment]
Thanks :+1: 

Adding to the mix, partly in relation to #1174: 

- [Where is the full list of privacy features that Waterfox has over Firefox? : waterfox](https://www.reddit.com/r/waterfox/comments/bd72sn/where_is_the_full_list_of_privacy_features_that/)

**Comment by grahamperrin** [comment]
[Download checksums and/or GPG signing … : waterfox](https://www.reddit.com/r/waterfox/comments/cz98l2/download_checksums_andor_gpg_signing_and_other/)

**Comment by grahamperrin** [comment]
### Downloads page

Things are quite scattered. At 1,600 x 900 full screen (the limit of this notebook): 

![image](https://user-images.githubusercontent.com/192271/66709252-3a263c00-ed58-11e9-8d7e-c90adb95b071.png)

If a change is not already drafted (the site redesign), consider something like this as the _essence_:

```text
                 | Windows     portable  | macOS     | Linux     | Android 
-----------------+-----------+-----------+-----------+-----------+-----------⌍
Waterfox Classic | 2019.10.1 | 2019.10.1 | 2019.10.1 | 2019.10.1 |         … |
-----------------+-----------+-----------+-----------+-----------+-----------|
Waterfox Current | 2019.10.1 |         … | 2019.10.1 | 2019.10.1 |         … |
-----------------+---------- +-----------+-----------+-----------+-----------⌏
```

A little more, still essentially a single table, with disclosure triangles: 

```text
                           | Windows     portable  | macOS     | Linux     | Android 
---------------------------+-----------+-----------+-----------+-----------+-----------⌍
Waterfox Classic           | 2019.10.1 | 2019.10.1 | 2019.10.1 | 2019.10.1 |         … |
• comparable to Firefox 56 | ◿         | ◿         | ◿         | ◿         | ◿         | 
---------------------------+-----------+-----------+-----------+-----------+-----------|
Waterfox Current           | 2019.10.1 |         … | 2019.10.1 | 2019.10.1 |         … |
• one-line distinction     | ◿         | ◿         | ◿         | ◿         | ◿         | 
---------------------------+---------- +-----------+-----------+-----------+-----------⌏
```

More (disclosed): 

```text
                           | Windows           portable        | macOS           | Linux           | Android 
---------------------------+-----------------+-----------------+-----------------+-----------------+----------------⌍
Waterfox Classic           | 2019.10.1       | 2019.10.1       | 2019.10.1       | 2019.10.1       |         …       |
• comparable to Firefox 56 | ◹               | ◹               | ◹               | ◹               | ◹               |
                           |  • requirements |  • requirements |  • requirements |  • requirements |  • requirements |
                           |  • blurb        |  • blurb        |  • blurb        |  • blurb        |  • blurb        |
---------------------------+-----------------+-----------------+-----------------+-----------------+-----------------|
Waterfox Current           | 2019.10.1       |         …       | 2019.10.1       | 2019.10.1       |         …       |
• one-line distinction     | ◹               | ◹               | ◹               | ◹               | ◹               |
                           |  • requirements |  • requirements |  • requirements |  • requirements |  • requirements |
                           |  • blurb        |  • blurb        |  • blurb        |  • blurb        |  • blurb        |
---------------------------+-----------------+-----------------+-----------------+-----------------+-----------------⌏
```

Sooner or later you'll want something important (not just the footer) below the table, so aim to keep the table reasonably shallow. Too much blurb, too deep/tall a table, will be a problem for readers who omit to scroll.

**Comment by grahamperrin** [comment]
### Incorrect change log

https://www.waterfox.net/blog/waterfox-2019.10-release-download/

- refers to https://github.com/MrAlex94/Waterfox/compare/68.0a2...2019.10-classic
- should refer to https://github.com/MrAlex94/Waterfox/compare/68.0a2...2019.10-current

**Comment by grahamperrin** [comment]
### Blog dates

[A nit](https://www.reddit.com/r/waterfox/comments/dm9oih/the_201910_release_fiasco_has_been_confusing_and/f4z4wir/), both of these have the same date. The latter should be dated 24th October: 

1. https://www.waterfox.net/blog/waterfox-2019.10-release-download/ 
2. https://www.waterfox.net/blog/waterfox-2019.10-release/

![image](https://user-images.githubusercontent.com/192271/67456879-02f23d80-f62a-11e9-8fc4-58dc0456a8a9.png)

Presence of the latter might fix #1202. I'll check in due course. 

The push-back announcement https://redd.it/djceyv mentioned security advisories. So on one hand, I half-expected the second blog post to mention the relevant advisory (or advisories). On the other hand, we have links to change logs so re: https://www.reddit.com/comments/dlptsq/-/f4y81ze/ with its light humour, it should be possible to include (in the second blog post) links to the more recent logs. 

![image](https://user-images.githubusercontent.com/192271/67457377-6761cc80-f62b-11e9-8646-f987f3dd1f5f.png)

Are we? _Are_ we? `;-)`

**Comment by grahamperrin** [comment]
### Release announcement references to change logs

https://www.waterfox.net/blog/waterfox-2019.10-release-download/ (2019-10-23) already includes these, for 2019-10-15 tags `2019.10-classic` and `2019.10-current`: 

- https://github.com/MrAlex94/Waterfox/compare/56.2.14...2019.10-classic
- https://github.com/MrAlex94/Waterfox/compare/68.0a2...2019.10-current

Should _also_ include these, for 2019-10-24 tags `2019.10-classic-1` and `2019.10-current-1`: 

- https://github.com/MrAlex94/Waterfox/compare/2019.10-classic...2019.10-classic-1
- https://github.com/MrAlex94/Waterfox/compare/2019.10-current...2019.10-current-1

TIA

**Comment by grahamperrin** [comment]
### Versioning guidelines

Nit. 

Given the two most recent tags, maybe edit the two `YYYY.MM.X` examples at https://github.com/MrAlex94/Waterfox/wiki/Versioning-Guidelines#addition-of-channels and https://www.waterfox.net/blog/waterfox-2019.10-release-download/

**PS** also, see below, https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-549589728

**Comment by grahamperrin** [comment]
### Blog: Commento

For reference only (beyond the control of Waterfox Project, I guess): 

https://gitlab.com/commento/commento/issues/36#note_236008535

> Some browsers seems to sometimes, or always, fail to scroll to Commento perma-linked areas. …

**Comment by grahamperrin** [comment]
### Typo and nits in the most recent blog post

> `YY.MM.X`

– should be `YYYY.MM.X` 

> maintainted

Oh dear https://www.thesaurus.com/browse/tainted ha ha I noticed the rogue _t_ whilst quoting. At a glance I see no other typo. 

TIA; fix at your leisure and then hide this comment as resolved.

**Comment by grahamperrin** [comment]
### Downloads page(s) and home page

https://www.waterfox.net/releases/

https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-541384643 above, kicking the ball around, in particular: 

> Too much blurb, too deep/tall …, will be a problem for readers who omit to scroll.

From <https://github.com/MrAlex94/Waterfox/issues/1227#issuecomment-546679759>: 

> … I have to apologize. I downloaded Classic instead of Current simply because I didn't scroll further down the releases page. …
> 
> Maybe it might be a good idea to reverse the layout so that Current appears at the top?

@Telmesomething thanks, but I shouldn't reverse the layout. 

If reversed, muscle memory will cause some readers to 'blindly' reach for and click the wrong link without reading a word of what's linked. Like "OK, I see an Apple, _click_.".

We'll see an increasing number of posts re: comparisons between Waterfox Classic and Waterfox Current so for what it's worth, I imagine a separate page for each flavour. 

A current view of the home page, and a _very_ rough mock-up: 

![2019-10-27 actual](https://user-images.githubusercontent.com/192271/67634250-47dbd580-f8b1-11e9-9373-32f3198f19d1.png)

![2019-10-27 mockup](https://user-images.githubusercontent.com/192271/67634249-47433f00-f8b1-11e9-9340-0750a319b4ab.png)

Very rough. The essence is to have the two flavours linked from the head of the page. 

I have other ideas but GitHub is not a forum for discussion so 😑 I'll save them for Reddit if/when there's an invitation to comment on planned changes to the site. 

### Postscripts

> For what it's worth, I imagine a separate page for each flavour. 

https://redd.it/dl9aam describes Waterfox Classic as "latest waterfox 2019.10 next gen" and may be an example of confusion arising partly from _next generation_ appearing on the same page as Waterfox Classic: 

![image](https://user-images.githubusercontent.com/192271/68073258-0736fd00-fd86-11e9-8cc8-59513d618248.png)

– also partly from 2019.10 describing both Waterfox Classic and Waterfox Current.

A more recent screenshot of the page (2020-04-11) – we now have a different order, Waterfox Current first: 

![image](https://user-images.githubusercontent.com/192271/79041888-2f574180-7beb-11ea-8d96-c40039d23787.png) 

– and people occasionally download the wrong installer.

**Comment by grahamperrin** [comment]
> … other ideas … save them for Reddit …

Discussion of version IDs arose here in GitHub, so here goes …

Re: https://github.com/MrAlex94/Waterfox/issues/1253#issuecomment-549588162

Still kicking the ball around: 

```text
  page                                       page
⌌-------------------------------------⌍    ⌌-------------------------------------⌍
| Waterfox Classic                    |    | Waterfox Current                    |
| ================                    |    | ================                    |
|                                     |    |                                     |
|                                     |    | Beta                                |
|                                     |    |                                     |
| Pre-release: 2019.11-classic-p      |    | Pre-release: 2019.11-current-p      |
|                                     |    |                                     |
|    * note for testers               |    |    * note for testers               |
|    * note for testers               |    |    * note for testers               |
|                                     |    |                                     |
|    Releases: 2019.10                |    |    Releases: 2019.10                |
|                                     |    |                                     |
|              * announcement (blog)  |    |              * announcement         |
|                                     |    |                                     |
|              2019.11-classic-r1     |    |              2019.11-current-r1     |
|                                     |    |                                     |
|              * not yet available    |    |              * not yet available    |
|                                     |    |                                     |
| Features                            |    | Features                            |
| ========                            |    | ========                            |
| …                                   |    | …                                   |
| …                                   |    | …                                   |
| …                                   |    | …                                   |
⌎-------------------------------------⌏    ⌎-------------------------------------⌏

                                 pages at a later date
⌌-------------------------------------⌍    ⌌-------------------------------------⌍
| Waterfox Classic                    |    | Waterfox Current                    |
| ================                    |    | ================                    |
|                                     |    |                                     |
|                                     |    | Beta                                |
|                                     |    |                                     |
| Pre-release: expired                |    | Pre-release: expired                |
|                                     |    |                                     |
|    Releases: 2019.11-classic-r1     |    |    Releases: 2019.11-current-r1     |
|                                     |    |                                     |
|              * announcement         |    |              * announcement         |
|                                     |    |                                     |
| Features                            |    | Features                            |
| ========                            |    | ========                            |
| …                                   |    | …                                   |
| …                                   |    | …                                   |
| …                                   |    | …                                   |
⌎-------------------------------------⌏    ⌎-------------------------------------⌏

                                 pages at a later date
⌌-------------------------------------⌍    ⌌-------------------------------------⌍
| Waterfox Classic                    |    | Waterfox Current                    |
| ================                    |    | ================                    |
|                                     |    |                                     |
| Pre-release: expired                |    | Pre-release: expired                |
|                                     |    |                                     |
|    Releases: 2019.11-classic-r1     |    |    Releases: 2019.11-current-r1     |
|                                     |    |                                     |
|              * announcement         |    |              * announcement         |
|                                     |    |                                     |
|              2019.11-classic-r2     |    |              2019.11-current-r2     |
|                                     |    |                                     |
|              * announcement         |    |              * announcement         |
|                                     |    |                                     |
| Features                            |    | Features                            |
| ========                            |    | ========                            |
| …                                   |    | …                                   |
| …                                   |    | …                                   |
| …                                   |    | …                                   |
⌎-------------------------------------⌏    ⌎-------------------------------------⌏
```

**Comment by grahamperrin** [comment]
### Blog navigation stumbling block

1. Begin with the **«** navigation at the foot of https://www.waterfox.net/blog/waterfox-2019.10-release-download/
2. aim for a link to the earlier blog post about 56.2.14

### Expected

3. after the link appears, time enough to click on the link

### Actual result

3. redirection; disappearance of the required link

### Workaround

4. ignore the **«**
5. step up to the https://www.waterfox.net/blog/ level then browse.

### Context

Redirection was a workaround to #1202

**Comment by grahamperrin** [comment]
[Commentaries with and without a trailing slash / solidus (#260) · Issues · Commento / Commento · GitLab](https://gitlab.com/commento/commento/issues/260) ▶ [Comment fetching is case-sensitive with URL-encoded national characters (#221) · Issues · Commento / Commento · GitLab](https://gitlab.com/commento/commento/issues/221)

**Comment by grahamperrin** [comment]
https://www.reddit.com/r/waterfox/comments/en38kg/waterfox_202001_is_now_available_with_all/ffejjl1/

> … Waterfox Classic profile spoilt by inadvertent use of Waterfox Current.
> 
> At https://www.waterfox.net/download/ it's not immediately obvious that Waterfox Classic exists. Need to page down.

### Postscript, 2020-03-08

[What just happened? Extensions not working? : waterfox](https://old.reddit.com/r/waterfox/comments/fetx8h/what_just_happened_extensions_not_working/) – another case of someone (understandably) confused by gaining Waterfox Current when Waterfox Classic was required.

**Comment by LeeBinder** [comment]
<details>
  <summary>SOLVED (click to expand)</summary> 

Whoever admins the web server needs to do some tiny bit of .htaccess magic and add a line of mod rewrite which adds a trailing slash so even URLs w/o one are being redirected properly.

Guinea pig as an example: https://www.waterfox.net/blog/waterfox-2020.02.1-release (via click onto "What's New").
</details>

**Comment by grahamperrin** [comment]
### Minimum requirements: memory

Given the `2 G` figure at <https://www.mozilla.org/firefox/56.0/system-requirements/>, is the `512 MB` figure below (bottom left) appropriate, for Windows? 

![image](https://user-images.githubusercontent.com/192271/76164551-c5f59600-6147-11ea-8c10-895d52991df2.png)

Gut feeling, from use of Firefox 73.0.1 (64-bit) and Waterfox Classic on (Tier-3) FreeBSD-CURRENT, with KDE Plasma: 

* the two figures for Windows should be `2 G`
* the two figures for Linux should be `1 G`.

Re: the requirements above and at https://www.mozilla.org/firefox/68.0/system-requirements/ you might prefer to express a minimum requirement of `512 MB` for macOS, however screenshots such as those at https://www.askwoody.com/forums/topic/watefox-takes-up-most-of-1-gb-of-ram-even-when-is-just-on-but-not-in-use/#post-2175298 suggest that (at least for Waterfox Classic) `512 MB` might be pushing it. Realistically, `1 GB` might be a better statement for Mac users. 

Maybe Mozilla's figures are similarly questionable … that's not to invite discussion here, just saying. 

<summary>
<details>

Two frames from a screen recording: 

![2020-03-08 13:54:32 frame](https://user-images.githubusercontent.com/192271/76164659-84b1b600-6148-11ea-96d0-c2e819ab33a4.png)

![2020-03-08 13:55:21 frame](https://user-images.githubusercontent.com/192271/76164688-bc206280-6148-11ea-9171-4b5739ca40b7.png)
</details>
</summary>

### Postscript

Discussion, in Reddit: 

* [Minimum requirements – Linux and macOS (Mac OS X) : waterfox](https://old.reddit.com/r/waterfox/comments/ffdw48/minimum_requirements_linux_and_macos_mac_os_x/)

**Comment by grahamperrin** [comment]
@LeeBinder I think you can resolve (hide) your https://github.com/MrAlex94/Waterfox/issues/582#issuecomment-589984251

**Comment by LeeBinder** [comment]
done!

@jorg35 : why :-1: ?

**Comment by grahamperrin** [comment]
64-bit requirements are not mentioned at https://www.waterfox.net/download/. 

(The 64-bit nature is debatably implicit in  file names e.g. `waterfox-current-2020.03.en-US.linux-x86_64.tar.bz2` and `waterfox-classic-2020.03.1.en-US.linux-x86_64.tar.bz2` however IMHO requirements should be upfront, before download begins.)

**Comment by grahamperrin** [comment]
### Documentation

Suggest installing [FFmpeg](https://www.ffmpeg.org/) on systems where it will be of benefit. 

https://www.reddit.com/r/waterfox/comments/fmh0cs/cant_play_live_videos_in_linux_with_waterfox/fl537vi/?context=1

**Comment by grahamperrin** [comment]
### Confusion from the third of the DOWNLOAD options at the home page

From discussions spread across the Internet – most of which focus on compatibility with legacy extensions (and will continue to do so, e.g. when historic/limited discussions are found through search engines) – many newcomers will expect an automatically-chosen download of _Waterfox_ to be _Waterfox Classic_. 

Instead it's _Waterfox Current_ – but no mention of _Current_ (we can't expect readers to observe the intricacies of a URL, foot of this window): 

![image](https://user-images.githubusercontent.com/192271/77842772-42e7be80-718e-11ea-8456-2f55b6255525.png)

Related: https://old.reddit.com/r/waterfox/comments/fqcvpj/-/flskl3n/

**Comment by grahamperrin** [comment]
### Languages

Documentation. Users of Waterfox Current **must not** add packs from https://addons.mozilla.org/language-tools/ 

Cross reference: 

* https://redd.it/ftum7k and various other incidents.

**Comment by grahamperrin** [comment]
@MrAlex94 Waterfox Classic `2020.03.1` updated to `2020.04`	on Windows 10 was not followed by an automated visit to https://www.waterfox.net/blog/waterfox-2020.04-release/

~~An update file issue, maybe?~~ 

@MrAlex94 thanks for the reply, I'll mark this as resolved off-topic (not a web site issue). 

----

No problem with the update to Waterfox Current on the same system. https://www.waterfox.net/blog/waterfox-2020.04-release/?upgrade appeared.

**Comment by MrAlex94** [comment]
It seems later versions of Firefox load the update page whenever the DISPLAY_VERSION changes, but unfortunately Classic does not. Since it still thinks it’s 56.3, it doesn’t launch the page. It’s on the list, just been busy to get it fixed 😬
