### ISSUE TITLE
Site: improve contextual uses of words such as Mozilla, Firefox and Waterfox; and e.g. the Firefox logo

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#585]
Meta, tracking: #582

----

https://blog.waterfoxproject.org/waterfox-56.0-release-download (2017-11-30) ackonwledged _various Mozilla-isms_ at the staging site. 

Some of what's below might have not surfaced until after content shifted – months later – from staging to production, with deeper indexing e.g. by robots. 

## https://www.google.com/search?q=choice+site%3Awww.waterfoxproject.org

Searches such as this reveal mixed messages, which might be not encountered through site-based navigation. What's below is not intended to be comprehensive. 

### The Mozilla Foundation https://www.waterfoxproject.org/foundation/

> … Waterfox, our flagship product, …

### State of Mozilla 2009 - A Competitive World https://www.waterfoxproject.org/foundation/annualreport/2009/a-competitive-world/

> … Waterfox 4 is going to be great. …

### State of Mozilla 2009 - Broadening Our Scope https://www.waterfoxproject.org/foundation/annualreport/2009/broadening-our-scope/

> … We released Waterfox on the Maemo …

### Mozilla 2009 Financial FAQ https://www.waterfoxproject.org/foundation/annualreport/2009/faq/

> … The majority of Mozilla's revenue is generated from search functionality included in our Waterfox …

### State of Mozilla 2009 - Sustainability https://www.waterfoxproject.org/foundation/annualreport/2009/sustainability/ 

> … The majority of Mozilla revenue continues to be generated from the search functionality included in Mozilla's Waterfox …

**Comment by grahamperrin** [comment]
Spun off from <https://www.reddit.com/comments/84hi0f/-/dx6ami5/>: 

![2018-05-26 11 48 35 download waterfox free web browser the waterfox project](https://user-images.githubusercontent.com/192271/40575332-07aa68b0-60db-11e8-989a-0b9287a88042.png)

**Comment by MrAlex94** [comment]
These pages are going to be removed completely.

**Comment by grahamperrin** [comment]
![2018-06-23 15 54 58 download waterfox free web browser the waterfox project - falkon](https://user-images.githubusercontent.com/192271/41813248-fa95720e-7729-11e8-9b53-8600da9dfa01.png)

When clicked: 

![2018-06-23 15 55 21 waterfox web browser download waterfox in your language the waterfox project - falkon](https://user-images.githubusercontent.com/192271/41813247-fa6f63ac-7729-11e8-81d8-1b0ab4b5a878.png)

– a Firefox logo, and the word _mozilla_ refers to https://www.waterfoxproject.org/en-US/
