### ISSUE TITLE
tab crashes occasionally

### ISSUE THREAD

**Issue by br4nnigan** [BrowserWorks/waterfox#589]
Having process crashes with the site twitch.tv for some months, now soundcloud starts acting up too.

On twitch.tv it happens during the initial load of the site, soundclound crashes in the background after some time.

Sorry for the shitty ticket, haven't tested without addons even yet, will do tomorrow
Just wanted to get this off of my :heart: 

Oh wow, those github emojis :joy: nice work boys :+1: 

Can I provide logs somehow?  There is no meaningful error message.

**Comment by grahamperrin** [comment]
Troubleshooting information please. Text (not raw data) from: 

- about:support

**Comment by br4nnigan** [comment]
That's the only stuff the button copies to the clipboard, is this another bug?
Hit the restart without addons button at that chance and sure enough no crash with twitch. I'll investigate further, maybe it's greasemonkey, but I don't think I'm using it for soundcloud.

Name \| Waterfox
-- \| --
56.2.0
20180515020548
Show Update History
release
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
Windows_NT 6.1
Open Folder
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
1/1 (Enabled by user)
0/4
false (disabled by default)
Missing
Missing
true
about:profiles

**Comment by br4nnigan** [comment]
The offender regarding twitch.tv is disconnect. Whitelisting the site solves the issue. Still have uBlock running.
