### ISSUE TITLE
Adding Yandex search

### ISSUE THREAD

**Issue by FunFrog-BY** [BrowserWorks/waterfox#59]
I`ve just reinstalled win10 and installed a new version of Waterfox to give it a try again after firebug problems. So now i get stuck with adding Yandex search engine - i have it out of the box in Firefox, but here, even with "Yandex Search" add-on i don`t have Yandex in search engines list.

**Comment by MrAlex94** [comment]
Can you not add it this way?

![capture](https://cloud.githubusercontent.com/assets/4728920/19076520/0113c20c-8a41-11e6-9ff3-e6aaeb751855.PNG)

**Comment by FunFrog-BY** [comment]
Wow, thanks! I tried to do it form "Search" in WF settings, i didn`t know that it can be done using search bar.
