### ISSUE TITLE
Please pull in the cubeb multichannel changes from Firefox 61

### ISSUE THREAD

**Issue by Squall-Leonhart** [BrowserWorks/waterfox#595]
Bug in reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1432779

**Comment by Scrxtchy** [comment]
I wonder.
Is this so much a critical difference from Firefox?

Recently I fixed windows update and got back on the new insider builds. Sometimes, and I'm unsure why, but when audio comes out of waterfox, it lowers the volume from every other program on the computer, and as soon as the source finishes playing audio/paused, volume is restored.

I can't even find a stable replication method to report, but I'm wondering if this is part of the reason I'm not having these issues on Firefox
