### ISSUE TITLE
(Mozilla 703849) sort direction indicator fails to change when direction changes

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#597]
Bugging Waterox and Firefox on FreeBSD-CURRENT and Kubuntu: 

![2018-05-29 12 19 40 about config](https://user-images.githubusercontent.com/192271/40658509-6662eba6-6343-11e8-9aaf-4bbd71abb34d.png)

![2018-05-29 12 19 25 about config](https://user-images.githubusercontent.com/192271/40658511-66928884-6343-11e8-99dc-f99ea990647a.png)

Related: 

- Mozilla bug [703849 - Column Sorting Indicators don't get refreshed correctly on Linux](https://bugzilla.mozilla.org/show_bug.cgi?id=703849)
- Mozilla bug [1293983 - Sort direction arrow in tree column headers is upside-down](https://bugzilla.mozilla.org/show_bug.cgi?id=1293983)

From the former: 

> I guess that it's related to GTK+

Meta, tracking: #538 

Suggested priority: P5

**Comment by grahamperrin** [comment]
> … on FreeBSD-CURRENT and Kubuntu: …

>> I guess that it's related to GTK+

More specifically: 

- not reproducible with Waterfox 56.2.0 on a Mac; and 
- I guess that it will be not reproducible with Waterfox on Microsoft Windows.

**Comment by MrAlex94** [comment]
Doesn't seem worth investigating further for WF.
