### ISSUE TITLE
about:support ▶ Copy text to clipboard ▶ sometimes does not copy what's required

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#598]
## Case A

<https://github.com/MrAlex94/Waterfox/issues/589#issuecomment-392302078> (2018-05-27 04:09 GMT+1), captured, from @br4nnigan: 

- https://web.archive.org/web/20180529160941/https://github.com/MrAlex94/Waterfox/issues/589#issuecomment-392302078

> … That's the only stuff the button copies to the clipboard, is this another bug? …

## Case B 

<https://github.com/MrAlex94/Waterfox/issues/596#issuecomment-392823105> (2018-05-29), captured, from @IzzySoft: 

- https://web.archive.org/web/20180529161118/https://github.com/MrAlex94/Waterfox/issues/596#issuecomment-392823105

> … Unfortunately the "Copy Text" button only filled in a very little part of the data. …

## Case C

Here, a few minutes ago (very soon after reading the report from @IzzySoft):

```text
Name | Waterfox
-- | --
56.2.0
20180529114927
Show Update History
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:59.0) Gecko/20100101 Firefox/59.0
FreeBSD 12.0-CURRENT
Open Directory
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
0/8 (Disabled)
 
false (disabled by default)
Found
Missing
false
about:profiles
```

Later use of the **Copy text to clipboard** button is, at a glance, bug-free. 

### Environment

```text
$ date ; uname -v
Tue 29 May 2018 17:19:59 BST
FreeBSD 12.0-CURRENT #2 r333587: Mon May 14 01:59:02 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
$ pkg info waterfox | grep Version
Version        : 56.2.0.19
```

## Initial observations

~~Cases A and B are on Windows~~ I shouldn't assume that.  

Case C on FreeBSD-CURRENT.

I'm almost certain that when I first read the report from @br4nnigan I was unable to reproduce the issue. 

Re: <https://www.freshports.org/www/waterfox>: 

- I might have used 56.2.0.13_5 (26 May 2018 00:53:51) on 2018-05-27. 
- the commit history for 56.2.0.19 (28 May 2018 23:53:59) draws attention to https://github.com/MrAlex94/Waterfox/compare/d2cdd42f4115b...01e6727879b2a 

----

Meta, tracking: #538

**Comment by IzzySoft** [comment]
Note that I've tried that button multiple times with the same effect (only few details being captured). Just tried it again now, same result. So

> Later use of the Copy text to clipboard button is, at a glance, bug-free.

Doesn't hold true here for me, unfortunately – while capturing raw data seems to work fine. But maybe @grahamperrin referred to a later build.

Ooops: now that I've written this and just wanted to check another detail, I get the full text? That's 1 try out of 10 then. And while the "broken copy" looked like a failed ASCII table:

```
Name | Waterfox
-- | --
56.2.0
20180515020548
...
```

the successfull export looks correct:

```
Application Basics
------------------

Name: Waterfox
Version: 56.2.0
Build ID: 20180515020548
...
```

Does that somehow ring a bell?

**Comment by grahamperrin** [comment]
@IzzySoft have you encountered this issue in recent months? 

(I have not.)

**Comment by IzzySoft** [comment]
Had no need for it, @grahamperrin. But now that you ask, I tried and:

```
Name | Waterfox
-- | --
56.2.6
20181220132736
…
```

So: Yes. Encountered it just now, on first try. Guess I need another 9 until I hit the right one…

**Comment by grahamperrin** [comment]
A possible recurrence, the head of this: 

- https://pastebin.com/raw/AxkKm4Zg (captured: https://web.archive.org/web/20190324014224/https://pastebin.com/raw/AxkKm4Zg)

From https://www.reddit.com/comments/b45133/-/ej7m7xq/?context=1

**Comment by IzzySoft** [comment]
Here also still the same with 56.2.8:

~~~
Name | Waterfox
-- | --
56.2.8
20190314011207
Show Update History
release
...
~~~
