### ISSUE TITLE
Issues with Swift Selection Search addon

### ISSUE THREAD

**Issue by vertigo220** [BrowserWorks/waterfox#599]
[This issue](https://github.com/CanisLupus/swift-selection-search/issues/92#issuecomment-392605368) on the SSS repo describes the problems, but basically something about Waterfox appears to be causing some of the icons for the addon's popup to not appear on Hacker News (news.ycombinator.com) and possibly other sites and, more crucially, the 56.2.0 update further broke it, causing it to behave how it did on that site on _all_ sites now, and to have additional issues on that site.

**Comment by grahamperrin** [comment]
Waterfox works as expected. I'll reply in the issue for the extension.

**Comment by grahamperrin** [comment]
>> … some of the icons for the addon's popup …

> Waterfox works as expected. …

As things are turning out, after screenshots etc. became available: 

- working as expected in some ways, but not others, with the extension.

**CSP**-oriented [Doesn't work in Bugzilla · Issue #27 · CanisLupus/swift-selection-search](https://github.com/CanisLupus/swift-selection-search/issues/27#event-1659579473) is tentatively closed with reference to Mozilla bug: 

- [1407056 - Override page CSP for content injected by expanded principals](https://bugzilla.mozilla.org/show_bug.cgi?id=1407056)

>  RESOLVED FIXED in Firefox 58

However with 56.2.0.31 on FreeBSD-CURRENT: 

![2018-06-02 19 20 47 1407056 - override page csp for content injected by expanded principals](https://user-images.githubusercontent.com/192271/40879622-c7be0a66-669a-11e8-8a02-303231e866b9.png)


– that's _without_ me enabling either of the two engines that are integral to Swift Selection search. (With both enabled, the pop-up is not entirely blank, there appear the icons for those two engines alone.)

**Comment by grahamperrin** [comment]
Waterfox commits tagged 56.2.0 with reference to **1407056** comprise: 

- https://github.com/MrAlex94/Waterfox/commit/5fdcb5a5d22bc11c0f9db0aaed2f6030c1ed34b6 _Bug 1407056: Part 1 - Provide more consistent principal/origin URL to content policies. r=bz,ckerschb_ | … _MozReview-Commit-ID: LqD9GxdzMte | --HG-- extra : rebase_source : 41ce439912ae7b895e0a3b0e660fa6ba571eb50f_
- https://github.com/MrAlex94/Waterfox/commit/84fb189b8249880099c74dd44a2c9e676bbcc962 _Bug 1407056: Part 2 - Override page CSP for loads by expanded principals. r=bz,krizsa_ | … _MozReview-Commit-ID: GlY887QAb5V | --HG-- extra : rebase_source : 1371b4e4e7f330b7f7721d4aa169fcb52a7622d0_
- https://github.com/MrAlex94/Waterfox/commit/a6e9a2cf4775d3e1e4f708d49a4489b1c96974d2 _Bug 1407056: Part 3 - Test that CSP overrides apply correctly based on triggering principals. r=bz_ | _MozReview-Commit-ID: EbGsI3keeG6 | --HG--
extra : rebase_source : 92d3bf7505641ccd17f0ff98d0adf4ddd5803cb8_
- https://github.com/MrAlex94/Waterfox/commit/f0c7aee168d3fa6426b998a0e009248cb5f4ce9c _Bug 1407056: Follow-up: Skip test on Android debug for flakiness. r=bustage_ | _MozReview-Commit-ID: 39slYE2zP95_
- https://github.com/MrAlex94/Waterfox/commit/98c0c6199879d6cd16874d7065a1953599c8af8d _Bug 1407056: Follow-up: Don't try to truncate data URI strings to a longer length. r=me_ | _MozReview-Commit-ID: CDsYXyrhB7T | --HG-- extra : rebase_source : 5647f2d05def805218a2ee45913da4388a4d9647 | extra : amend_source : e5015c868db64dce924476600f713b6c3aac1e17_

----

From the dates (last year) I can't tell the true order of those five with regard to this years 56.2.0 so @MrAlex94 edit this comment, if necessary. Thanks.
