### ISSUE TITLE
Pinterest.com NOT LOADING IN WATERFOX

### ISSUE THREAD

**Issue by allexradu** [BrowserWorks/waterfox#6]
Pinterest.com loads in every browser I've have installed, except for Waterfox. 

The network settings are good, this is just a Waterfox issue. The site doesn't even gives an error is just trying to loads and nothing happens.

Please do something about it, I had to switch to Cyberfox in the meantime. Cyberfox sucks, it crashes all the time even though I have RAM to spare.

**Comment by ghost** [comment]
I've Waterfox on Mac and on PC (Win 7).. And here it works..
