### ISSUE TITLE
FAQ page or pages, maybe in-browser

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#603]
Meta, tracking: #582 

**Frequently asked questions** might include: 

- …
- …
- …

(I have a handful in mind, but I'd like someone else to make the first suggestion.)

In addition, we have at least one **frequently offered answer** to questions (in a broad range of troubleshooting situations) that have _very_ diverse wording. Finding a 'standard' form <strike>or </strike>of wording for a question like that can't be done correctly on first publication, it'll probably take a handful of changes over a period of months to get it right with enough plain English etc..

**Comment by WagnerGMD** [comment]
Allons-y (like would say Ten in Doctor Who) ! 
Then let's try (or start) by 2 examples **about the privacy** :
- [How to handle the "Exceptions Cookies"](https://www.reddit.com/r/firefox/comments/8op8yg/how_to_disable_cookies_for_a_long_list_of_websites/)
- [The geolocation isn't available](https://www.reddit.com/r/waterfox/comments/8oief0/waterfox_5620_geolocation_not_working/) (remove from the browser)
- Another trouble **Mozilla Memory Leak** ?
- [Load any videos faster and entirely](https://github.com/MrAlex94/Waterfox/issues/606#issuecomment-395319999) (or handle the **buffering** specially on youtube)
- etc

**Comment by grahamperrin** [comment]
Thanks. 

One of those two is also in my personal record (just begun), [Waterfox variations from Mozilla Firefox norms](https://gist.github.com/grahamperrin/aebf423341863643864e1986a40fc501#file-waterfox-diversity-shortlist-md)

I imagine that for brevity, an FAQ page can include two bullet points leading to separate pages: 

- one page listing things that are disabled
- one page listing things that were removed (can not be enabled, even through use of about:config).

**Comment by WagnerGMD** [comment]
You're welcome @grahamperrin and as you can see, I have add 2 anothers examples.

To begun, I believe it could be one good idea to follow (for these pages).
Otherwise for a little page, we can put **an anchor HTML** .

**Comment by grahamperrin** [comment]
We need to explain about multi-process Waterfox, enabled by default (risky) after installing any extension that is reportedly (or truly) incompatible with multi-process. https://github.com/MrAlex94/Waterfox/issues/397#issuecomment-381313681 there's a shortlist of some of the troubles. 

Also make users aware that the workaround to trouble – disabling multi-process – will be lost if Waterfox is refreshed.

**Comment by grahamperrin** [comment]
[resource:// images don't work in old addons · Issue #647 …](https://github.com/MrAlex94/Waterfox/issues/647)

**Comment by grahamperrin** [comment]
Related (to multiple issues), in Reddit: 

- [e10s: availability of multi-process with older versions of operating systems : waterfox](https://www.reddit.com/r/waterfox/comments/8rtb3l/e10s_availability_of_multiprocess_with_older/)

– an authoritative answer there should allow us to draft something for an FAQ.

**Comment by MrAlex94** [comment]
Could you add this info to the meta issue? Too many bugs are clogging up my email :-(

**Comment by WagnerGMD** [comment]
I'm wonder did you create another topic about : **"How to improve Waterfox ?"**
Because otherwise I believe we might need to build a list on this matter. Unless it's already done somewhere ?

**Comment by grahamperrin** [comment]
> … did you create another topic about : "How to improve Waterfox ?" …

Me? No. 

General discussion: https://www.reddit.com/r/waterfox/ – that'll be the best place for generally how to improve things. 

----

Selected issues (meta): https://github.com/MrAlex94/Waterfox/issues/538

Waterfox web site issues (meta): #582 

Open bugs: https://github.com/MrAlex94/Waterfox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug

Open enhancements: https://github.com/MrAlex94/Waterfox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aenhancement

All open issues: https://github.com/MrAlex94/Waterfox/issues/

**Comment by WagnerGMD** [comment]
Now I can take a look (or find) easily the topic about the enhancements.

So thank you @grahamperrin but for now I will avoid reddit (in the futur ? Perhaps)... Let's say I don't like it because it will require a lot of improvements (specially the toolbar and even the MarkDown etc).
No as today it's remain bad....despite I had notice a fews improvements recently (these last months).

**Comment by grahamperrin** [comment]
https://www.reddit.com/r/redesign/ – much ongoing, so I posted a few highlights and lowlights to https://redd.it/8j5dow
