### ISSUE TITLE
I can only add 14 themes before I get a FIFO situation

### ISSUE THREAD

**Issue by Tafnab** [BrowserWorks/waterfox#604]
I am delighted to write my first bug report for Waterfox. It's been working great. However... I was collecting cool themes (just themes) from addons.mozilla.com and I found that the older themes I had added weren't there after I added about 10 new themes (doesn't affect the built in ones). I was also loading, then deleting about 10 themes too. It was quite the party. Maybe these older installed themes are no longer visible on the theme list. Hopefully they are still installed but I just can't see them. 

What to check? Is there a hard coded maximum number of themes? Could I ask for it to be extended? Let me know what diagnositc info you need.

Waterfox 56.2.0 (64-bit)
Linux Fedora 28 with KDE Spin (up to date)

**Comment by grahamperrin** [comment]
Hi

1. about:support
2. Copy text to clipboard
3. paste to wherever suits you, save it somewhere (the troubleshooting information might be needed later). 

> … Is there a hard coded maximum number of themes? …

I doubt it. I have fifteen (the three that are integral to Waterfox, twelve additions): 

![2018-06-03 09 21 26 add-ons manager](https://user-images.githubusercontent.com/192271/40884647-c168c53c-670f-11e8-91fa-dce27f347ec6.png)

I'm almost certain that I had more in the past. I'll add some now. 

It will help if you can let us have: 

- a screenshot of the list of appearances

– plus, ideally: 

- the addons.mozilla.org address of each theme (appearance) that you installed. 

Thanks

**Comment by Tafnab** [comment]
Please mark this closed. I can't reproduce it. I assure you that I was adding a bunch of themes and they started disappearing. Maybe it will happen again. I'll pay more attention if there is a next time.

**Comment by grahamperrin** [comment]
@Tafnab hi, reopen this, if you like. 

The maximum here today is **33**: 

1. _Default_ (persistent)
2. _Compact Light_ (persistent)
3. _Compact Dark_ (persistent)
- plus thirty additions (volatile)

In this screenshot, the most recently added – at the head of list in [Simple Add-on Manager](https://addons.mozilla.org/addon/simple-add-on-manager/) (sorted by state) – is _abstract eighteen_:

![2018-06-03 16 12 12 i can only add 14 themes before i get a fifo situation issue -604 mralex94-waterfox](https://user-images.githubusercontent.com/192271/40888037-6a8fd45a-6749-11e8-8159-3ce7a768ada3.png)

As far as I can tell, any further addition causes disappearance – without warning, before or after the removal – of the least recently added theme. 

In about:config I did a little seeking and browsing, I can't find anything that might relate to the apparent limit. (No relevant names matching values `30` or `33`, and so on.)

If disappearance is a known issue: it should be (at least) documented. 

Thanks

---- 

Meta, tracking: #538

**Comment by Tafnab** [comment]
OK. That's confirmation. I only got to 31 today and quit adding. I can quit anytime. :)

**Comment by MrAlex94** [comment]
https://support.mozilla.org/en-US/questions/975540

**Comment by grahamperrin** [comment]
Thanks! 

about:config?filter=lightweightThemes.maxUsedThemes

– I created integer preference `lightweightThemes.maxUsedThemes`

PS note to self, keyword (for search purposes): _personas_
