### ISSUE TITLE
about:crashes – Waterfox Classic can not present crash information

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#607]
https://www.reddit.com/comments/7cd3ri/-/dpqg33f/ (2017-11-13) @MrAlex94 wrote: 

>> about:crashes has been disabled for years, but may be worth changing that now.

In response: 

> Making a custom crashdump page that doesn't send information to Mozilla but rather to Waterfox HQ in about:crashes might be beneficial.

## Related

https://github.com/MrAlex94/Waterfox/blob/436898372f8589d4a241e924084119358c58bf45/browser/app/profile/firefox.js#L1542

- `browser.tabs.crashReporting.sendReport` should remain `false`

– and so on, to allay concerns about sharing. 

https://firefox-source-docs.mozilla.org/toolkit/crashreporter/crashreporter/index.html#about-crashes

----

Meta, tracking: #538

**Comment by grahamperrin** [comment]
Other mentions include: 

- https://www.reddit.com/comments/8q95gl/-/e0hl5yb/

**Comment by MrAlex94** [comment]
Still keeping it disabled, infrastructure would take too much time.

**Comment by grahamperrin** [comment]
I recently stumbled across `RUST_BACKTRACE=1` – https://www.reddit.com/r/waterfox/comments/aaxyuo/waterfox_crashes/ecy65a7/

**Comment by grahamperrin** [comment]
@MrAlex94 might the future rebase on Firefox ESR 68 be an opportunity to review this? 

TIA
