### ISSUE TITLE
Programmatically reverting Ecosia to Google

### ISSUE THREAD

**Issue by szepeviktor** [BrowserWorks/waterfox#61]
Good afternoon!

Putting `user_pref("browser.search.defaultenginename",      "Google");` in my user.js does not help reverting the search engine. Is there an automated way?
https://github.com/MrAlex94/Waterfox/commit/81f23967bf12195b19ce72164087dd59803db0f9

[I use Waterfox by unpacking it](https://github.com/szepeviktor/windows-workstation/blob/master/ff-dev/START-ffdev.cmd) `7za x -y .\Waterfox*Setup.exe "core\"` and deleting core + profile
 when closed.

**Comment by szepeviktor** [comment]
@MrAlex94 Could you help me?

**Comment by MrAlex94** [comment]
Hi, sorry for the late reply. I'll look into this and get back to you.

**Comment by szepeviktor** [comment]
@MrAlex94 Could you help me revert back to Google by code?

**Comment by szepeviktor** [comment]
@MrAlex94 Could you allow reverting?

**Comment by szepeviktor** [comment]
@MrAlex94 Excuse me for bumping. Could you help?

**Comment by MrAlex94** [comment]
Sorry for the late reply! You should be able to switch your default search engine to whatever you please. I can't seem to reproduce the issue?

**Comment by szepeviktor** [comment]
Thank you. 
You know I use Waterfox by unpacking it then deleting it and the profile also. I call it **disposable browser**

Would there be a way to programmatically set Google as the default engine? 

Now I have to set it manually every time the browser is started.

**Comment by szepeviktor** [comment]
See https://github.com/szepeviktor/windows-workstation/blob/master/waterfox/START-ff-dev.cmd
for the start script. 

## 

+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
@MrAlex94 Could you help me switch search engine programmatically? **I daily unpack Waterfox setup, use it then delete binaries + profile also.** (see my script above)
Thank you.

**Comment by szepeviktor** [comment]
@MrAlex94 Is it possible to programmatically revert Ecosia to Google?
Please advise.

**Comment by szepeviktor** [comment]
@MrAlex94 It would be nice to resolve this one too.

**Comment by szepeviktor** [comment]
Now setting these still leaves Ecosia as the default search engine.

```js
user_pref("browser.search.defaultenginename",		"Google");
user_pref("browser.search.isUS",        false);
user_pref("browser.search.geoSpecificDefaults", false);
```

Of course you may close this one if you are not interested.

**Comment by MrAlex94** [comment]
@szepeviktor is this via user.js? If so, the search engine has to be changed by the user, it can't be done programmatically. This was implemented in Firefox due to the large amount of search engine hijacking occurring. To be fair, I think it was a valid security change. While annoying, it seems better overall.

**Comment by szepeviktor** [comment]
> it can't be done programmatically

Thank you!
Now it is safe to close.
