### ISSUE TITLE
Hide redundant entries from about:config.

### ISSUE THREAD

**Issue by Peacock365** [BrowserWorks/waterfox#611]
Hey there!

_In this issue, I want to present some configs which IMHO could be removed from the Waterfox about:config, as they are not doing anything. Please add more if you find that I have missed one or more prefs._

TELEMETRY
toolkit.telemetry.unified
toolkit.telemetry.updatePing.enabled
toolkit.telemetry.shutdownPingSender.enabled
toolkit.telemetry.shutdownPingSender.enabledFirstSession
toolkit.telemetry.server_owner
toolkit.telemetry.server
toolkit.telemetry.newProfilePing.enabled
toolkit.telemetry.infoURL
toolkit.telemetry.enabled
toolkit.telemetry.debugSlowSql
toolkit.telemetry.archive.enabled
toolkit.telemetry.reportingPolics.firstRun

CRASH REPORTER
browser.tabs.crashReporting.email
browser.tabs.crashReporting.emailMe
browser.tabs.crashReporting.includeURL
browser.tabs.crashReporting.requestEmail
browser.tabs.crashReporting.sendReport
dom.ipc.plugins.flash.subprocess.crashreporter.enabled
dom.ipc.plugins.reportCrashURL
toolkit.crashreporter.infoURL

FIREFOX EXPERIMENTS
experiments.enabled
experiments.manifest.uri
experiments.manifestFetchIntervalSeconds
experiments.supported
extensions.ui.experiment.hidden
network.allow-experiments

New Tab Page ADVERTISEMENTS
browser.newtabpage.enhanced
browser.aboutHomeSnippets.updateUrl

FLYWEB (read more about it here: https://www.ghacks.net/2016/07/26/firefox-flyweb/ )
dom.flyweb.enabled
reason: Waterfox does not have the FlyWeb system add-on, nor any other system add-on.

_Not sure about (might be related to Sync in general):_
services.sync.telemetry.submissionInterval
services.sync.telemetry.maxPayloadCount

_Should be changed before going into hiding:_
experiments.activeExperiment to **false**
security.ssl.errorReportingUrl to **empty string**
services.sync.telemetry.macPayloadCount

**Comment by grahamperrin** [comment]
## about:config?filter=plugins.

`plugins.update.url` `https://www.mozilla.org/%LOCALE%/plugincheck/`

– <strike>can </strike>might be redundant for consistency with: 

- [about:addons 'Check to see if your plugins are up to date' · Issue #336 …](https://github.com/MrAlex94/Waterfox/issues/336)
- [Plugin Check in extensions menu is non-functional · Issue #357 …](https://github.com/MrAlex94/Waterfox/issues/357)
- [Miscellaneous links that need to be changed in Waterfox. · Issue #548 …](https://github.com/MrAlex94/Waterfox/issues/548)

Is `plugins.testmode` ever applicable with Waterfox?

**Comment by Scrxtchy** [comment]
How would this affect profiles that are used between different forks of firefox?

**Comment by grahamperrin** [comment]
## Sharing a Waterfox profile with something other than Waterfox

From experience, I shouldn't recommend it. 

## Sync

Worth thinking about …

**Comment by Scrxtchy** [comment]
Now that I remember, waterfox moved their profiles a few updates ago to seperate them
