### ISSUE TITLE
56.2.0 (64Bits) Issue with Waterfox and ScrapBook X

### ISSUE THREAD

**Issue by Atanacius** [BrowserWorks/waterfox#614]
Well, I like Waterfox, but I dislike when updates (or magic occult forces) **mess** my best favourited extensions.

So, I would report you that before that update I was able to use without any issues the ScrapBook X extension.

Anyway... from now when I want save a page it no save (even it say "successfully saved...").
I found that it's an issue with e10s mode.

Since, when I open the SAME page in a non-e10s tab, it then save my page without issues..

Please can you look what it's going on? :(

And for informations, I use Windows 10, Family, 64 bit.

**Comment by grahamperrin** [comment]
[e10s (multi-process) compatibility reports at addons.mozilla.org (AMO) : waterfox](https://www.reddit.com/r/waterfox/comments/8c77ii/e10s_multiprocess_compatibility_reports_at/) – I added a line for ScrapBook X.

To use an extension that is incompatible with multi-process, you should disable multi-process Waterfox. The preference at: 

- about:preferences#general

Then please be prepared to (again) disable multi-process after any refresh of Waterfox.

**Comment by Atanacius** [comment]
First thanks for answer (and for the link), that's interesting, but I think before it's not working anymore I was always in e10s mode, not sure but I suspect an update related to an API?

**Comment by grahamperrin** [comment]
OK, so it worked for you with e10s enabled in Waterfox 56.1.0? 

To be honest I found the interface confusing, unpredictable (maybe because my first sight of it was bugged with e10s), so can you share a screenshot or two showing a feature that no longer works?

For example, amongst the problem reports for e10s _disabled_ with Firefox 56.0.2 was this: 

> I can't download scrapbook to my FireFox 56 version

– but I could not find a download option.

**Comment by Atanacius** [comment]
No. I can't provide any screenshots since all is ok EXCEPT saving (with no errors, just it save nothing in e10s mode anymore..)

That's a bit (in that way) hard to explain how and where the addon would not work, but keep in mind: it no save or bookmark anymore in Waterfox (starting from: 56.2.0) when e10s mode is enabled (and when we are in a e10s tab!).
The fix is more a workaround than a real fix, but it can help to know it work without issues when in a NOT e10s tab !
(this workaround works currently unless Waterfox staff provide an update working with ScrapBook X in e10s mode (meaning: try at least :))

**Comment by grahamperrin** [comment]
Unless I'm missing something, the developer's screenshots at https://addons.mozilla.org/addon/scrapbook-x/ don't show what's required. 

Here, it was difficult to find a _Save_ feature not working, for example: 

![2018-06-15 18 18 52](https://user-images.githubusercontent.com/192271/41481399-aa029918-70c9-11e8-9454-13e83eeacfee.png)

**Comment by grahamperrin** [comment]
Eventually I realised, the **hidden** Scrapbook X menu. 

Working with single-process Waterfox: 

![2018-06-15 18 20 10 56 2 1 build 20180614221107](https://user-images.githubusercontent.com/192271/41481429-cf429d72-70c9-11e8-8ab6-cdf4f24d295d.png)

![2018-06-15 18 20 57 56 2 1 build 20180614221107](https://user-images.githubusercontent.com/192271/41481428-cf1e02a0-70c9-11e8-8e15-78750bc2a535.png)

Not with multi-process: 

![2018-06-15 18 21 53 56 2 1 build 20180614221107](https://user-images.githubusercontent.com/192271/41481455-f080d580-70c9-11e8-90aa-f420c5102274.png)

**Comment by grahamperrin** [comment]
From the developer: 

> **NOTICE!**
> This addon **is incompatible to Electrolysis (e10s)** …

I wondered what would happen with e10s forced in this month's [Firefox ESR 52.8.1](https://www.mozilla.org/firefox/52.8.1/releasenotes/) (64-bit) on Mac OS X 10.9.5. 

The extension worked once or twice. Firefox stopped responding, I forced a quit, The extension no longer works, here's the same symptom that was seen with Waterfox: 

![2018-06-15 22 53 30](https://user-images.githubusercontent.com/192271/41492190-4c258d7e-70f5-11e8-8adf-d1aa94066475.png)

## Other issues with inappropriate use of e10s in Firefox

In at least two tests, about:addons did not work. An example: 

![2018-06-15 23 14 32](https://user-images.githubusercontent.com/192271/41492243-bd279b34-70f5-11e8-915a-94929a352ade.png)

That's the search interface, without clicking on _Search_, when a simple list of extensions was required. Clicking away from, then back on, _Extensions_ did not present the list.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/issues/309
