### ISSUE TITLE
WebP decoder is leaking memory

### ISSUE THREAD

**Issue by roytam1** [BrowserWorks/waterfox#615]
A crosspost bug is reported in UXP: https://github.com/MoonchildProductions/UXP/issues/483
And a fix is landed there and confirmed fixed: https://github.com/MoonchildProductions/UXP/commit/05e8038c08e76c021564c0e8e91e6f73aff8b795

And it is reported to upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1294490#c126

**Comment by grahamperrin** [comment]
Thanks ‒ I was following the bug, but given the title (Implement experimental WebP image support) I didn't imagine that it was enabled. Now I see: 

about:config?filter=image.webp

`image.webp.enabled` `true` by default. 

Meta, tracking: #538

**Comment by Peacock365** [comment]
@roytam1 

Would it be possible for you to port the patch directly, i.e. creating a pull request? That would be nice. if you have some time to spare, having a look into #538 would help, as well.

**Comment by roytam1** [comment]
I think it is easier to download https://github.com/MoonchildProductions/UXP/commit/05e8038c08e76c021564c0e8e91e6f73aff8b795.diff and `git apply 05e8038c08e76c021564c0e8e91e6f73aff8b795.diff` than taking time cloning repo, checking out files, do `git apply` and push and create PR for me. :P

**Comment by Peacock365** [comment]
I created a fitting pull request, waiting for the merge now.

@roytam1 

Any idea how to solve #387? #373 would also be appreciated.

**Comment by MrAlex94** [comment]
Thanks to @Peacock365 for the patch :-)
