### ISSUE TITLE
Tag v47.0

### ISSUE THREAD

**Issue by szepeviktor** [BrowserWorks/waterfox#62]
Could you tag the new release here on GitHub?

**Comment by MrAlex94** [comment]
Here you go :-) 
https://github.com/MrAlex94/Waterfox/releases/tag/47.0

**Comment by jirutka** [comment]
This tag does not exist, actually there is not any tag in this repository. Why?

**Comment by szepeviktor** [comment]
Maybe tagging is missing from the release checklist...


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
@MrAlex94 Please reconsider adding git tagging to your release checklist.

**Comment by MrAlex94** [comment]
I'll be going through the codebase and adding tags soon. I had to redo the current repository though as when I started using VCS I wasn't very good with them and wasn't merging correctly. I'll add the tags in the old repository [here](https://github.com/MrAlex94/Waterfox-Old) as well.
