### ISSUE TITLE
Recent blog posts misdirect readers to staging.waterfoxproject.org for downloads

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#630]
https://blog.waterfoxproject.org/waterfox-56.2.0-release-download and 
https://blog.waterfoxproject.org/waterfox-56.2.1-release-download for example. 

There's the very pale _Waterfox Downloads_ button referring to: 

- https://staging.waterfoxproject.org/en-US/waterfox/new/?scene=1

Hint: so pale that (happily) readers may be not noticing the button :-)

----

Meta, tracking: #582 

Cross reference: [today's comment](https://github.com/MrAlex94/Waterfox/issues/438#issuecomment-397783290) under _Staging site: invalid certificate, expired … · Issue #438 …_

**Comment by grahamperrin** [comment]
Another cross-reference: https://blog.waterfoxproject.org/waterfox-56.2.1-release-download#comment-3946978515

**Comment by grahamperrin** [comment]
https://www.waterfoxproject.org/downloads/ and https://www.waterfoxproject.org/waterfox/new/?scene=1 both redirect to: 

- https://www.waterfoxproject.org/en-US/waterfox/new/?scene=1

FWIW I favour the more memorable of the two, https://www.waterfoxproject.org/downloads/

**Comment by MrAlex94** [comment]
Fixed.
