### ISSUE TITLE
IE Tab2 not work  on 56.2.1

### ISSUE THREAD

**Issue by klcb2010** [BrowserWorks/waterfox#631]
https://addons.mozilla.org/zh-CN/firefox/addon/ie-tab-2-ff-36/

**Comment by grahamperrin** [comment]
Thank you, 

https://addons.mozilla.org/addon/ie-tab-2-ff-36/

I added a listing for the extension to [e10s (multi-process) compatibility reports at addons.mozilla.org (AMO) : waterfox](https://www.reddit.com/r/waterfox/comments/8c77ii/e10s_multiprocess_compatibility_reports_at/)

I don't have a 64-bit Windows machine handy. 

@klcb2010 please: 

1. **disable** (switch off) multi-process, 

`[  ]` 启用多进程的 Waterfox

about:preferences#general

2. retry the extension.

**Comment by klcb2010** [comment]
yes，  it  work ， when i   disable (switch off) multi-process
