### ISSUE TITLE
An image less Firefox-like when Waterfox is refreshed

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#632]
Spun off from [about:welcomeback – ⓘ Success! – is outdated · Issue #519 …](https://github.com/MrAlex94/Waterfox/issues/519) and [UX of Refresh Waterfox · Issue #562 …](https://github.com/MrAlex94/Waterfox/issues/562)

https://github.com/MrAlex94/Waterfox/blob/1121d1ada82fe2855498a6b043e99dfb2435ac46/browser/themes/shared/incontent-icons/welcome-back.svg

A `.png` produced from the `.svg`: 

![welcome-back](https://user-images.githubusercontent.com/192271/41496804-432f41a6-7140-11e8-95ab-5f79a28f1ff3.png)

Not [trademarked by Mozilla](https://www.mozilla.org/foundation/trademarks/list/), but it's Firefox-like. 

The likeness is not a bad thing :-) but to polish the user experience, someone might like to suggest – or create: 

- something more Waterfox-like
- maybe to re-emphasise what's kept (unlike Firefox) e.g. extensions. 

Suggested priority: P5

## Food for thought

Probably including some blasts from the past (before my time): 

https://yandex.com/images/search?img_url=http%3A%2F%2Frssload.net%2Fgo%3Fhttp%3A%2F%2Fpicbit.net%2Fimage%2F28102012_1351467604657_1351439502645.jpg&rpt=imageview

https://www.bing.com/images/search?q=imgurl:http%3A%2F%2Frssload.net%2Fgo%3Fhttp%3A%2F%2Fpicbit.net%2Fimage%2F28102012_1351467604657_1351439502645.jpg&view=detailv2&iss=sbi&redirecturl=https%3A%2F%2Fwww.bing.com%2Fimages%2Fdiscover%3Fform%3DHDRSC2#enterInsights

https://www.google.com/search?tbs=sbi:AMhZZivSHz8BKracueaPE527El564ytIf28Fyp19ZlePreLMPbFzKZlztYHHUNSpZ9WRZE_1g8oYtjqV9b4xl_1Rxfwj8VFAg7UCsx9gxVA3bT-0KcZSNbdz9VtWihjIj4FsgmDUJVRVEtc_1ibdX50gaHyx3PTdUTEYl4Ms5HFztTYiithBlyafxxt6dCBjuEciIME_1FgCpDDXt-5U6QHBCAjZemK-TmsOmo6_1moRIQjOtlzgA6BRn9UGhno9rBPPUjfg1IU64q4HeSr3wn9p3KrC6TNUQFXl2ml5FsT0SvrIiRdb-psg2qr21qIaYvCKp3NxJbkBh6F1VrKzOltwL0E2u6bMSshnv7w

**Comment by MrAlex94** [comment]
Please add this info to https://github.com/MrAlex94/Waterfox/issues/562
