### ISSUE TITLE
Two settings now act as if mutually exclusive

### ISSUE THREAD

**Issue by SilverlightPony** [BrowserWorks/waterfox#64]
Since updating to Waterfox v47.0, the settings "When I open a new tab, switch to it immediately" (in Preferences) and "load tabs in background" (browser.tabs.loadInBackground in about:config) are mutually exclusive -- check the box for the former, and the latter gets changed to "false"; set the latter to "true", and the former gets unchecked.

**Comment by MrAlex94** [comment]
That's odd, do you still have the issue in 48/49?

**Comment by SilverlightPony** [comment]
Yep, still there.  (v48.0.2)

**Comment by MrAlex94** [comment]
https://www.reddit.com/r/firefox/comments/51jpyo/browsertabsloadinbackground_now_opposes_switch_to/d7ctm4z/
