### ISSUE TITLE
Make it easier to visit sites with self signed TLS certificates

### ISSUE THREAD

**Issue by tuaris** [BrowserWorks/waterfox#643]
Mozilla Firefox requires a user go through several extra steps to open a site with a self-signed TLS certificate.  This serves no purpose and ends up doing more harm than good as user's will learn to 'just ignore the warnings'.

Have Waterfox treat self signed TLS certificates with the same level of trust as a low grade trusted TLS certificate.

**Comment by laniakea64** [comment]
How do you know that all self signed TLS certificates can be trusted?

Or are you asking for a way to tell Waterfox to trust **specific** self signed TLS certificates that you specify?

**Comment by MrAlex94** [comment]
> This serves no purpose and ends up doing more harm than good as user's will learn to 'just ignore the warnings'.

No, this behviour is good. It *should* be a PITA if a cert if self-signed, as it completely defeats the point - even in development - of having an encrypted connection.
