### ISSUE TITLE
resource:// images don't work in old addons

### ISSUE THREAD

**Issue by Prinz23** [BrowserWorks/waterfox#647]
I first thought the addons like nzbfox were broken because i didn't see the button anymore. But inspecting the site I saw the button is there just the image(s) doesn't show up = button invisible.

Same with the "YouTube ALL HTML5" the image for the button doesn't show up. All these use:

```style="background-image: url('resource://... ```

All these ```resource://``` images don't show up anymore since version 56.2.0 
No problem with previous Waterfox versions.

**Comment by grahamperrin** [comment]
## [nzbFox](https://addons.mozilla.org/addon/nzbfox/)

> … i didn't see the button anymore …

I see it with Waterfox 56.2.1 on FreeBSD-CURRENT: 

![2018-06-17 01 22 37](https://user-images.githubusercontent.com/192271/41503481-bb4b7d66-71cd-11e8-9729-0cb16de5e72b.png)

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.53
$ date ; uname -v
Sun 17 Jun 2018 01:27:55 BST
FreeBSD 12.0-CURRENT #5 r335024: Wed Jun 13 11:04:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by Prinz23** [comment]
I mean the buttons that are integrated (inserted) by the addon into indexer sites for that page. It's not affecting the toolbar buttons. 

Same as the button that is inserted into the youtube page at the top drop down menu by "YouTube ALL HTML5".

**Comment by grahamperrin** [comment]
Ah, thanks. 

https://github.com/MrAlex94/Waterfox/issues/235#issuecomment-387634960 comprised five `resource://`-related commits. 

## [No Resource URI Leak](https://addons.mozilla.org/addon/no-resource-uri-leak/)

> … it is **expected** that some add-ons break due to this fix. …

Meta, tracking: #538

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
is this the same thing that is making greasemonkey legacy break some direct images?

all the scripts can be disabled but as soon as I click the greasemonkey button to on it breaks direct images on some sites...

I don't think so, the old extension to block resource uri leaks didn't break that, but then of course maybe it's different. Anyone experiencing that issue? Maybe I'll try deleting all the scripts and trying that. No time/energy to test currently. J/w if anyone else experiencing this. Thanks
