### ISSUE TITLE
Visual Artifact on Download Animation

### ISSUE THREAD

**Issue by whitgroves** [BrowserWorks/waterfox#65]
When downloading files, the animation for a complete download leaves a visual artifact around the button:
![capture](https://cloud.githubusercontent.com/assets/7268925/16844367/7a7ebcf0-49aa-11e6-8fa0-48d1b0f1bf69.PNG)

It returns to normal once the window is resized in any way.

**Comment by MrAlex94** [comment]
Does this still occur in the latest versions?

**Comment by whitgroves** [comment]
Not anymore. Thanks!
