### ISSUE TITLE
Certificate 'Add Security Exception' window gets bigger every time you click 'Get Certificate' button

### ISSUE THREAD

**Issue by vertigo220** [BrowserWorks/waterfox#657]
Steps to reproduce:

1. Go to a site with a bad certificate (e.g. https://expired.badssl.com/)
2. Click 'Add Exception...'
3. In the window that opens, click 'Get Certificate' button
4. Keep clicking the button. Every time the window gets bigger, and there's no way to make it smaller again. It seems to be this new, bigger size permanently now (persists after restarting the browser).

I tried this in Firefox 60 and 52/ESR and neither did it, so it appears to possibly* be a Waterfox issue. This happened in Waterfox 56.2.0x64, now updated to 56.2.1 and the window is still big. This is on Win10x64.

*After restarting the browser, the window no longer grows when clicking on the button, so I'm not sure if it was a random issue that's not happening anymore, and that's why it's also not happening on Firefox, or if it's simply not happening because the window height is now from the top of the screen to the top of the taskbar, and it simply won't go any bigger.

**Comment by grahamperrin** [comment]
Mozilla bug [1424311 - Clicking Get Certificate causes the Add Security Exception window to expand indefinitely](https://bugzilla.mozilla.org/show_bug.cgi?id=1424311)

>  VERIFIED FIXED in Firefox 60

In the FreeBSD area: 

- [[ports] Contents of /head/www/waterfox/files/patch-bug1424311](https://svnweb.freebsd.org/ports/head/www/waterfox/files/patch-bug1424311?view=markup&pathrev=466002)

From 1424311-related commits in the Waterfox area: 

> … we have to call `window.sizeToContent()` more often and unfortunately results in the window growing and shrinking again on Windows, but at least it will always be the "right size" for its content. …

**Comment by IanDGibbons** [comment]
Is there any way of getting the windows size back down ?

Alternatively can someone tell me how many times to press tab to get to the 'accept' button ?

(I can close the windows if I don't want it  )

**Comment by vertigo220** [comment]
I think mine is still large, as it goes from the top of the screen to the top of the taskbar, which is what I mentioned in my original comment, so I guess it won't ever go back down, probably not without reinstalling. When you have the location bar selected, three tabs takes you to the checkbox (which is selected by default--another annoying issue--and can be deselected by pressing space) for permanently storing the exception, a fourth tab takes you to the "Confirm Security Exception" button, and a fifth tab takes you to the cancel button.

**Comment by grahamperrin** [comment]
Meta/tracking: #538
