### ISSUE TITLE
Can't Make Waterfox My Default Browser

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#66]
When I start WF 47.0.1 Mac, I get a box at the top of the page asking if I want to make WF my default browser, I click the the box goes away. But, in Preferences, General, Start, it says that WF is not currently my default browser. When I click "Make Default" nothing happens. Even when I start Safari, in Preferences, it says that WF is my default browser, so how can I make WF my default browser? Please make your reply simple to follow. Thanks, Ken.

**Comment by ghost** [comment]
I forgot to mention that I am using Mac OSX 10.8.5 + Mr. Alex has made Waterfox compatible with 10.8.5.

**Comment by MrAlex94** [comment]
Hi there Ken,

If you set it as the default browser it should be set as that, even if it says it isn't. This seems to be a bug with the OS X version that I haven't resolved. It's the same on my Mac. 
You can just ignore the notification if it's bothersome. 

Really sorry for the late reply as well!

All the best,
Alex

**Comment by ghost** [comment]
Thanks Mr. Alex, happy to know it's not me causing the problem. I just click the "Make Waterfox my default browser" button, a small price to pay for such a brilliant browser, especially your thoughtful gesture to make it compatible with OSX 10.8.5. Your reply is quite timely given all the responses you have to make. Ken.

**Comment by ghost** [comment]
Mr. Alex, in Preferences/Startup, I just uncheck "Always check if Waterfox is your default browser". That seems to solve the problem, I no longer get the box asking if I want to make Waterfox my default browser, it just is!! Even in Safari Preferences, it says that Waterfox is my default browser, so it's working for me. Ken.

**Comment by aminbeedel** [comment]
god bless you man . really . i mean it

**Comment by MrAlex94** [comment]
Glad to see it's all resolved.

**Comment by ghost** [comment]
Thanks Mr. Alex, Waterfox is working perfectly with OSX Mountain Lion. Just a thought, somewhere on the Waterfox website you ought to tell folks thinking of trying Waterfox that it works with more legacy operating systems, enlarges the user base.

Thanks again,
Ken

Ken Kline
pixtureskk@sympatico.ca

,
