### ISSUE TITLE
56.2.1 tag is missing

### ISSUE THREAD

**Issue by jbeich** [BrowserWorks/waterfox#665]
It's not clear which commit corresponds 56.2.1 binary release. For supported platforms (Windows, macOS, Linux) this breaks promise of reproducibility and complicates figuring out which bugs are fixed. For other platforms (BSDs, Solaris) there's no stable version to update.

**Comment by MrAlex94** [comment]
Sorry!
https://github.com/MrAlex94/Waterfox/releases/tag/56.2.1
:-)
