### ISSUE TITLE
Waterfox refuses input when 'New features in version x' page autoloads.

### ISSUE THREAD

**Issue by ladycofb** [BrowserWorks/waterfox#67]
When updating to a new version of Waterfox, the "What's new" page loads at which point the browser no longer accepts any input from keyboard or mouse into either the browser window, or the menu bar. Animations in the browser and video playback in other tabs starts normally; implying the browser is still rendering normally - however one cannot interact with it at all.

This literally only occurs on the what's new page.

OS X 10.7.5, Dual Xeon 4x2.33 processors, 32GB ram, Nvidia GT630 1GB, PSCSI card, Lexington Alpha USB audio. XServe 1,1 booting from normal SATA-1 disk in bay 0.

Please let me know if there's any logs you require? 
I think this might apply: https://xkcd.com/1586/

**Comment by MrAlex94** [comment]
Hmm very odd. Does this still occur on the latest versions?
