### ISSUE TITLE
"waterfox --version" brands itself as "Mozilla Waterfox"

### ISSUE THREAD

**Issue by rehashedsalt** [BrowserWorks/waterfox#678]
**Describe the bug**
Exactly what the title says. Waterfox, when invoked from the terminal with the `--version` or `-v` flags, prints its version information alongside the title "Mozilla Waterfox". As Waterfox is not associated with Mozilla, this is an error and a (non-serious) violation of their trademark.

Tested on Linux x86_64 56.2.1.

**To Reproduce**
1. Open a terminal
2. Invoke `waterfox --version` or `waterfox -v`

**Expected behavior**
The same, but without "Mozilla" prefixing it.

**Screenshots**
![image](https://user-images.githubusercontent.com/12635110/41696746-346f6330-7505-11e8-947e-a287d64d8ff8.png)

**Desktop (please complete the following information):**
 - OS: Debian x86_64
 - Version: Sid

**Additional context**
None necessary.

**Comment by grahamperrin** [comment]
> … Waterfox is not associated with Mozilla …

Waterfox is [Powered by Mozilla](https://www.mozilla.org/about/powered-by/). 

Maybe related (I bookmarked this weeks ago, curiosity): 

https://github.com/MrAlex94/Waterfox/blob/715e79f8f87e9f96e4a26f92ee02c8aec0c3b4e6/xpcom/system/nsIXULRuntime.idl#L200

https://github.com/MrAlex94/Waterfox/blob/715e79f8f87e9f96e4a26f92ee02c8aec0c3b4e6/xpcom/system/nsIXULRuntime.idl#L202

**Comment by hawkeye116477** [comment]
On application.ini also vendor is Mozilla :smile:.

**Comment by rehashedsalt** [comment]
@grahamperrin I could be mistaken, but that looks like it's only for using that particular logo and the "Powered by Mozilla" text, which appears [in the footer of the project's website](https://www.waterfoxproject.org/en-US/). Said footer also states:

>Waterfox is NOT associated with Mozilla or its products.

And then the version information window tries to make it very clear that Waterfox isn't a Mozilla product:

![image](https://user-images.githubusercontent.com/12635110/41749443-dead9718-75a5-11e8-8f4d-fba3815332f6.png)

All of this points toward the `-v` version string just being an oversight.

**Comment by grahamperrin** [comment]
Thanks. Related: 

- [Detailed Info on the issue of being the Default Browser on Windows and what may still need fixing · Issue #384 …](https://github.com/MrAlex94/Waterfox/issues/384)
- [Update Program Description on Windows · Issue #387 …](https://github.com/MrAlex94/Waterfox/issues/387)
- [Waterfox web site colophon (footer) : waterfox](https://www.reddit.com/r/waterfox/comments/8sye18/waterfox_web_site_colophon_footer/)

Meta, tracking: #538 #582

**Comment by grahamperrin** [comment]
> … the `-v` version string just being an oversight.

:+1: I guess so. 

Plus https://www.reddit.com/comments/8sye18/-/e15i187/?context=1 clarity re: the footer. Association in terms of a _company_<strike>, so (for company number 08071145) we probably want _Waterfox Ltd_ or _WATERFOX LIMITED_ somewhere</strike>. 

Plus this: 

https://github.com/MrAlex94/Waterfox/blob/2bdc9aadfd5b57496450f9cb94b90376b7447e0e/browser/branding/unofficial/locales/en-US/brand.dtd#L9

I don't know the context in which that appears, but if the context does **not** make clear that it's about trademarks then (again) it's open to misinterpretation. https://trademarks.ipo.gov.uk/ipo-tmtext no match for Waterfox there but I don't want to complicate this issue. 

Focusing … 

## Version string, branding

I can raise a pull request to address (at least) the version string, but for the version string alone, I'm not sure which files to target. 

A brief comparison: 

```text
$ pkg info palemoon | grep Version
Version        : 27.9.3
$ palemoon --version
Moonchild Productions Pale Moon 27.9.3
$ uname
FreeBSD
```

https://github.com/MoonchildProductions/UXP/search?p=2&q=%22Moonchild+Productions%22&unscoped_q=%22Moonchild+Productions%22 in the UXP area helped me to identify some of what might change in the Waterfox area. 

https://github.com/MoonchildProductions/UXP/blob/master/application/basilisk/branding/unofficial/locales/en-US/brand.properties#L9 there's a `vendorFullName`, https://github.com/MrAlex94/Waterfox/search?q=vendorFullName&unscoped_q=vendorFullName 

> couldn’t find any code matching 'vendorFullName' in MrAlex94/Waterfox

----

https://github.com/MrAlex94/Waterfox/blob/2bdc9aadfd5b57496450f9cb94b90376b7447e0e/browser/branding/unofficial/locales/en-US/brand.properties#L8

I wonder, if we add this below line 8: 

`vendorFullName=Waterfox Ltd`

– will that cause `Mozilla` to **not** appear in the version string? 

I did also glance at `application.ini` files, there are a few. 

### Postscript

Side note: it's New Moon on FreeBSD. tl;dr there's a bug.

**Comment by roman6626** [comment]
How is Waterfox unrelated to Mozilla?!! Waterfox is not an independent project. It works on the Mozilla code. And without Mozilla, he is not viable. It is just an assembly. This is not a fork!

**Comment by hawkeye116477** [comment]
@roman6626 
`This is not a fork!`
It's based on Firefox code and also has few own changes, so it's fork. 

`How is Waterfox unrelated to Mozilla?`
It isn't associated with Mozilla, it's separate company, not owned by Mozilla.

Please don't shout!

**Comment by roman6626** [comment]
I don't scream at all. I speak very quietly. Just call a spade a spade.
There are a large number of browsers based on the Mozilla source code, but only the Pale Moon (now the Basilisk) makes a complete fork of the Gecko engine. Both the first and second did a branch from the original code base at the time of monumental changes in the architecture of the declared Mozilla. Everything else is an assembly based on a fixed engine. A fork of Quantum will only happen when the current Servo begins to radically change the internal architecture and the license for the outdated kernel changes. Until then there will be repacks, assemblies, recompilations, rebuilds, etc. names of the same class of products based on an unchanged code base, differing only in a set of truncated technologies, optimizations at the level of configs.
Many assemblies also have Chrome. As far as I know, none of their creators makes a fork of Blink, but uses the experience of the Chromium project unchanged. The difference between these browsers is only in the installed add-ons and tweaks produced by the author.

**Comment by roman6626** [comment]
By the way, you yourself advised using the Moonchild products. Because they are less dependent on the parent, unlinked from the Mozilla code. They receive not only security patches, but also develop independently. :-)

**Comment by rehashedsalt** [comment]
Mozilla does not publish Waterfox. Waterfox explicitly states that it is "not associated with Mozilla". Per the MPL, which Firefox is licensed under, Waterfox is not permitted to use the name "Mozilla" to brand its browser.

Call it whatever you want -- fork, assembly, reskin, or otherwise -- but it runs afoul of license terms to call it "Mozilla Waterfox".

**Comment by roman6626** [comment]
I agree. Different names. Let it be called whatever you like. 
I talked about something else. There is a big difference between the concepts of fork and assembly. That's all. :-)
The Сhromium has no fork! We do not consider Сhrome. :-)
