### ISSUE TITLE
Moving from Mozilla Firefox; have some questions

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#682]
1. Does Waterfox support WebExtensions? If so, what version is it? Firefox 55 equivalent?
2. Will you continue allowing installation of "unsigned add-on"?
3. I can't find Waterfox on "F-Droid". Any chance adding it to FDroid because I don't use google.

**Comment by ghost** [comment]
Bugs:
1. In "about:addons", 2 lines:
a) Add-on compat check is disabled [Enable]
b) Check to see if your plugins are up to date
Clicking a's [Enable] and b's link does not work at all.

Feature request:
1. Add an option to hide "Sign in to Sync" from burger menu.
	Tor Browser already hide it, and it would be nice if I can hide it.

Question:
1. "about:debugging#addons": Why there are so many Language packs? I just need English. How can I delete else? (I've downloaded Portable edition)
2. I heard you're building "Waterfox add-ons" store. As a extension developer, when can I upload some?

**Comment by grahamperrin** [comment]
<https://github.com/MrAlex94/Waterfox/issues/682#issue-337018106>

1. Please see [The Waterfox Blog | Waterfox, Its Legacy and Looking to the Future](https://blog.waterfoxproject.org/waterfox-its-legacy-and-looking-to-the-future)
2. I imagine so
3. duplicate of [F-Droid · Issue WaterfoxCo/Waterfox-Android#40 …](https://github.com/MrAlex94/Waterfox/issues/234)

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/682#issuecomment-401380599

1. a) see [Waterfox 56.2.0 - extensions.checkCompatibility : waterfox](https://www.reddit.com/r/waterfox/comments/8k48rk/waterfox_5620_extensionscheckcompatibility/); b) subscribe to [about:addons 'Check to see if your plugins are up to date' · Issue WaterfoxCo/Waterfox#336 …](https://github.com/MrAlex94/Waterfox/issues/336)

----

Enhancement request

1. please raise a separate issue (easier to track).

----

Questions

1. <strike>it's a feature, https://www.reddit.com/comments/8r66jc/-/e0qap48/ for some of the context (if you'd like to know the history, I suggest making a new post in Reddit)</strike>
2. …

**Comment by laniakea64** [comment]
> hide "Sign in to Sync" from burger menu.

add to [userChrome.css](http://kb.mozillazine.org/UserChrome.css)
```
#PanelUI-fxa-container {
  display:none !important;
}
```

> "about:debugging#addons": Why there are so many Language packs? I just need English. How can I delete else? (I've downloaded Portable edition)

https://github.com/MrAlex94/Waterfox/issues/201

**Comment by grahamperrin** [comment]
@laniakea64 thanks, more obscurely: 

- [Shifting the Firefox Sync icon to the left : FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/comments/7zdxsc/shifting_the_firefox_sync_icon_to_the_left/)

– is it even possible?

**Comment by laniakea64** [comment]
> more obscurely: 
> 
> - [Shifting the Firefox Sync icon to the left : FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/comments/7zdxsc/shifting_the_firefox_sync_icon_to_the_left/)
> 
> – is it even possible?

I don't have a Sync account, so I can't investigate that, sorry.

**Comment by ghost** [comment]
Wow, that's really helpful replies.

> userChrome.css

Hmm, this idea is good but I'd like to see a checkbox. Waterfox removed all(?) Mozilla trackers so why not add it.
Raised a ticket https://github.com/MrAlex94/Waterfox/issues/683

> https://blog.waterfoxproject.org/waterfox-its-legacy-and-looking-to-the-future

This doesn't tell me much. "The future variant will be: Based on ESR releases" is obvious.
Which ESR? ESR52? ESR60?

Does WF 56.2.1 support:
- Firefox ~56 WebExt APIs
- Firefox ESR 52 WebExt APIs
- Firefox ESR 60 WebExt APIs

??




> Language pack
OK made a comment here: https://github.com/MrAlex94/Waterfox/issues/201#issuecomment-401487099

**Comment by ghost** [comment]
And: https://github.com/MrAlex94/Waterfox/issues/684

**Comment by laniakea64** [comment]
> This doesn't tell me much. "The future variant will be: Based on ESR releases" is obvious.
Which ESR? ESR52? ESR60?

The future variant will be based on ESR60 - https://github.com/MrAlex94/Waterfox/issues/267#issuecomment-376351366

**Comment by grahamperrin** [comment]
> … Waterfox removed all(?) Mozilla trackers …

Incidentally, [Are there any alternatives to Firefox Sync? : waterfox](https://www.reddit.com/r/waterfox/comments/8nd28l/are_there_any_alternatives_to_firefox_sync/)

– and I shouldn't assume that all Mozilla-related services are tracking. https://webmasters.stackexchange.com/q/104628/18125 for example.
