### ISSUE TITLE
Add a checkbox to hide & disable "(Sign in to |)Sync"

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#683]
Add an option to hide "Sign in to Sync" from burger menu.
Tor Browser already hide it, and it would be nice if I can hide it.
I don't use Cloud service anyway.

- Tor Browser contributor

**Comment by grahamperrin** [comment]
[#16488 (Remove "Sign in to Sync" from the menu) – Tor Bug Tracker & Wiki](https://trac.torproject.org/projects/tor/ticket/16488), https://trac.torproject.org/projects/tor/ticket/16488#comment:7 in particular.

**Comment by WagnerGMD** [comment]
`lockPref("identity.fxaccounts.enabled",false);`
Otherwise in the meanwhile, you can open the page **about:config** to disable.
At least, it work's fine with Firefox. Because **apparently** it doesn't exist (anymore or yet ?) for **Waterfox_v56.1.0**
