### ISSUE TITLE
[WebExtension Development] Waterfox refused to install 'nonsigned strict_min_version:60' XPI

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#684]
So I'm trying add-ons which "manifest.json" is like this:

...
"applications":{"gecko":{"id":"{xyz}","strict_min_version":"60.0"}}
...

1. about:addons > "Install from file"
2. Select "addonfolder/manifest.json"

And Waterfox(default configuration) refused to install it because:

x addons.repository	WARN	_formatURLPref: Couldn't get pref: extensions.getAddons.get.url
x addons.repository	WARN	AddonRepository search failed: searching false aURI null aMaxResults 1
x addons.repository	WARN	Search failed when adding add-ons to cache

This doesn't tell me much.

However, when I tried:

1. about:debugging#addons > [Load Temporary Add-on]
2. It loaded.
3. But add-on's option page says: "XYZ is incompatible with Waterfox"

> TypeError: browser.privacy.websites.firstPartyIsolate is undefined

I need to know _what WebExt version_ Waterfox is supporting, so I can slim down my add-on for Waterfox usage.
Currently this add-on is using Fx52-60 WebExt APIs. I didn't use 61+ WebExt APIs.

**Comment by ghost** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/privacy/websites

**Comment by laniakea64** [comment]
Waterfox is based on 56, so right now it has WebExtensions support same as Fx 56.  But it's planned to support the APIs that were added in 57 - https://github.com/MrAlex94/Waterfox/issues/484#issuecomment-375479476

**Comment by ghost** [comment]
Thanks for clarification.
Does this mean the version number is same as Firefox Webext version?

Waterfox 56.x = Support WebExt ~56
Waterfox 57.x = Support WebExt ~57
Waterfox 60.x = Support WebExt ~60
??

(just wondering why you don't import "ESR60" and rip Mozilla trackers. The tor browser devs are making a patch for converting official ESR to their browser.)

**Comment by grahamperrin** [comment]
> Does this mean the version number is same as Firefox Webext version?

No. 

Maybe best to begin with an understanding that Waterfox 56.0 was based on Firefox 56.0.2. Recommended reading: 

- [The Waterfox Blog | Waterfox 56 Release](https://blog.waterfoxproject.org/waterfox-56.0-release-download)
- [The Waterfox Blog | Waterfox 56.1.0 Release](https://blog.waterfoxproject.org/waterfox-56.1.0-release-download) NB the closing point
- [The Waterfox Blog | Waterfox 56.2.0 Release](https://blog.waterfoxproject.org/waterfox-56.2.0-release-download) again NB the closing point.
