### ISSUE TITLE
Waterfox Add-ons page? (addons.(waterfoxprojectdomain))

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#685]
I think I heard Waterfox is developing their own add-ons website but I can't find it.
Anyone can confirm this?

It'll be nice if this is true, because Mozilla is going to delete all leagacy add-ons from AMO sooner or later.

**Comment by grahamperrin** [comment]
Over to the linked issue, please and (if you like) close this issue. 

Thanks.
