### ISSUE TITLE
Javascript 'confirm' function not returning anything

### ISSUE THREAD

**Issue by taublast** [BrowserWorks/waterfox#686]
**Describe the bug**
Javascript 'confirm' function not returning anything in Waterfox 56.2.1 (64-bit) Windows 10 64-bit.

**To Reproduce**
1. Go to https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm2
2. Click on 'Try it'
3. You'll see that confirm function result is undefined.

**Expected behavior**
In other browsers it's working as intended: returns true or false boolean.

**Comment by laniakea64** [comment]
Works as expected for me in Waterfox 56.2.1.

When I click "Try it", then "OK", it says "You pressed OK!".
Click "Try it", then "Cancel", it says "You pressed Cancel!".

Tried modifying their code to this -
```
<!DOCTYPE html>
<html>
<body>

<p>Click the button to display a confirm box.</p>

<button onclick="myFunction()">Try it</button>

<p id="demo"></p>

<script>
function myFunction() {
    var txt;
    var r = confirm("Press a button!");
    if (typeof r == 'undefined') {
      txt = "It's undefined!";
    }
    else if (r == true) {
        txt = "You pressed OK!";
    }
    else if (r == false) {
        txt = "You pressed Cancel!";
    }
    else {
      txt = "I don't know what "+r+" is!";
    }
    document.getElementById("demo").innerHTML = txt;
}
</script>

</body>
</html>
```
Still works as expected.

**Comment by grahamperrin** [comment]
@taublast please, can you reproduce the behaviour with Waterfox in safe mode?

> Works as expected for me in Waterfox 56.2.1.

+1 

56.2.1.48_1 on FreeBSD-CURRENT

![2018-07-02 05 59 14 one](https://user-images.githubusercontent.com/192271/42146094-6704a876-7dbd-11e8-8cb9-6647703b2f6d.png)

**Comment by taublast** [comment]
Yeah it started working as intended after i rebooted my pc the next day. I guess it was due to fact i was debugging an mvc app using waterfox and vs debugger messed something up.
Closed.
