### ISSUE TITLE
Google gms and ads, unwanted connexions in Android version

### ISSUE THREAD

**Issue by jolebaltringue** [BrowserWorks/waterfox#687]
I didn t have the time (nor the will, to be honest) to build Waterfox from source so I downloaded the play store version.
I decompiled it and found in the smalis the infamous google gms loaded with, amongst others, google ads.
![screenshot from 2018-07-01 22-38-55](https://user-images.githubusercontent.com/40738888/42135997-41104a46-7d43-11e8-8adc-ab3e2e0c4be3.png)
There s one more gcm (google cloud messaging) folder in org/mozilla/geko
![screenshot from 2018-07-01 22-38-55](https://user-images.githubusercontent.com/40738888/42136027-e321899e-7d43-11e8-9aba-cf559f8f77f6.png)
There s telemetry stuff and more, and the Android.manifest is truly horrifying, not exactly what I d call a privacy oriented app.
I removed the whole google/gms folder, the other gcm folder, the feeds plus other unpleasant stuff, and I desactivated the google related services and receivers in the AndroidManifest.
![screenshot from 2018-07-01 22-48-58](https://user-images.githubusercontent.com/40738888/42136080-bfcff498-7d44-11e8-8544-adb24743dbc9.png)
I removed more things in the AndroidManifest (like com.google.android.gms.version" android:value="@integer/google_play_services_version", and some invasive permissions), and then I installed the app on my phone, it works.
But, it connects to unwanted IPs before I even open my first web site.
Steps to reproduce are as follows:
install the app on your phone,
don t open it yet and start any network monitor app,
open Waterfox but don t do anything, that is do not go to any web site and do not write anything in the address bar, just open the app and leave it open,
now go back to the network monitor app and see that there are more than a dozen connections to amazonaws and other unsavoury characters (see attachement).
![screenshot_net monitor_20180701-181620](https://user-images.githubusercontent.com/40738888/42135961-a3fca5c4-7d42-11e8-953e-c4afee16cc03.png)
![screenshot_net monitor_20180701-181632](https://user-images.githubusercontent.com/40738888/42135962-a432f836-7d42-11e8-88a9-ad7c10f7e4fe.png)
You say that Waterfox is built for people, not for profit, you talk about privacy and stuff so one question comes to mind:
why?

**Comment by MrAlex94** [comment]
> You say that Waterfox is built for people, not for profit, you talk about privacy and stuff so one question comes to mind:
> why?

Because people kept asking for an Android version, and it's the same reason why it's marked as Unreleased/Beta.

Also, please take note of [Bug 1419581](https://github.com/MrAlex94/Waterfox/search?q=1419581&unscoped_q=1419581&type=Commits) that was commited which removed the Google Play cruft, which will be coming with the next build.
