### ISSUE TITLE
 [BUG? or just broken]  [browser.download.lastDir.savePerSite]   does not appear to be working right...

### ISSUE THREAD

**Issue by MelchiorGaspar** [BrowserWorks/waterfox#688]
**Describe the bug**
browser.download.lastDir.savePerSite;true
does not appear to be working right...

**To Reproduce**
1) make sure  browser.download.lastDir.savePerSite;true is enabled/TRUE
2) trying downloading from a few different sites to different directories..
3) go back and try to download  from those sites again and see if it opens 
to correct download directory... instead of the last used one..

**Expected behavior**
should recall download locations per site... 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 ULTIMATE x64 SP1
 - Version:  Waterfox 56.2.1

**Additional context**
My thoughts....  the db file content-prefs.sqlite is being corrupted?
how, I don't know...

**Comment by grahamperrin** [comment]
> BUG?

I'm not sure. 

Is the issue reproducible with Waterfox in safe mode?

----

Here, 

about:config?filter=browser.download.lastDir.savePerSite

- finds nothing, with Waterfox 56.2.1 on FreeBSD-CURRENT. 

```text
$ pkg info waterfox | grep Version ; date ; uname -v
Version        : 56.2.1.48_1
Tue  3 Jul 2018 07:50:12 BST
FreeBSD 12.0-CURRENT #6 r335800: Sat Jun 30 03:35:14 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

https://redd.it/8at52d in the Firefox area reports that `browser.download.lastDir.savePerSite` does not work. 

https://dxr.mozilla.org/mozilla-central/search?q=browser.download.lastDir.savePerSite&redirect=false finds a few things, and [browser.download.lastDir.savePerSite - Mozilla | MDN](https://developer.mozilla.org/docs/Mozilla/Preferences/Preference_reference/browser.download.lastDir.savePerSite) (updated 2018-02-05) refers to Mozilla bug [702748 - Use a pref for disabling per-site remembering of download directory](https://bugzilla.mozilla.org/show_bug.cgi?id=702748). 

Amongst results for <https://bugzilla.mozilla.org/buglist.cgi?longdesc_type=allwordssubstr&order=Bug%20Number&query_format=advanced&longdesc=browser.download.lastDir.savePerSite>, Mozilla bug [1043629 - firefox does not remember the default download folder, it changes it randomly b/w the current selected one and the ones used in past.](https://bugzilla.mozilla.org/show_bug.cgi?id=1043629) mentions `browser.download.lastDir.savePerSite` in a way that makes me assume that it is not deprecated, so I wonder why there's no preference here (on FreeBSD).

**Comment by MelchiorGaspar** [comment]
@grahamperrin  
Well it use to work just fine...
idk if it works better in safemode.... its not tied to addons so...

**Comment by MelchiorGaspar** [comment]
Also I do not see a  [ .sqlite-shm ] or [ .sqlite-wal ] for the content-prefs.sqlite file....

**Comment by Ulf3000** [comment]
Im 100% sure that this doesnt work on firefox either or some other pref might subdue it , i rewrote the "save file to" addon and came to this pref which was still in the addon code but didnt work and threw exceptions

**Comment by MelchiorGaspar** [comment]
it seems to be working for me for Firefox v62.... but I copied an old version of the content-prefs.sqlite file from backup to both my Firefox and Waterfox profiles... it seems to be working again... for now... but something is breaking it after a while...

**Comment by grahamperrin** [comment]
> BUG?

Not reproducible with Waterfox 56.2.3 on FreeBSD-CURRENT. 

> 1. make sure browser.download.lastDir.savePerSite;true is enabled/TRUE

Per-site is effective with a new profile; without that preference.

**Comment by MelchiorGaspar** [comment]
For some reason its not working in in Waterfox for me... 
I switched back to Firefox for testing and its working fine in FF v63.0.3

**Comment by MelchiorGaspar** [comment]
I see its still not fixed....  :-(

**Comment by MelchiorGaspar** [comment]
@MrAlex94 were you able to identify and fix the issue?
it some times doesn't work right.. happens in the current Firefox too...

**Comment by MrAlex94** [comment]
Unfortunately it's a bug that Mozilla will have to resolve.

**Comment by MelchiorGaspar** [comment]
> 
> 
> Unfortunately it's a bug that Mozilla will have to resolve.

ok...
