### ISSUE TITLE
Compatibility of settings with stock Firefox

### ISSUE THREAD

**Issue by Rikk** [BrowserWorks/waterfox#69]
First off, nice to see version 48 online. Thanks!

Now, my point: I see that if one moves from Firefox to Waterfox, using the same profile, some settings (inside `prefs.js`) are not saved anymore and are cleared from prefs file. Example: `xpinstall.signatures.required`, `browser.eme.ui.enabled`, `media.eme.*`. If the profile is used again in Firefox, well, things won't look good.
`xpinstall.signatures.required` for instance is still supported in LTS and in especial builds of v48.

On other topic, I'm seeing some random and unpredictable black boxes appearing on pages when navigating, which looks like some rendering issue; it never happened with Firefox (and I've been using 48.0 since I found the special build with unsigned addons enabled some days ago).

**Comment by MrAlex94** [comment]
Resolved, as Waterfox now uses its own profile location.
