### ISSUE TITLE
Bugs that need patching

### ISSUE THREAD

**Issue by MrAlex94** [BrowserWorks/waterfox#690]
1437842
1442722
1468523
1450989
1467363
1466577

Will need to implement these bugs at some point, but has been taking up too much time for now. Will focus on other security issue.

**Comment by grahamperrin** [comment]
OK :+1: if I find anything I'll add it here. 

---- 

Meta, tracking: #538

**Comment by grahamperrin** [comment]
I guess, you already have most or all of these …

## 1437842

https://hg.mozilla.org/releases/mozilla-release/rev/3574187cbf66 … https://hg.mozilla.org/releases/mozilla-release/rev/b96020a79cfa (parts 0 … 13) from push ID 1728, https://hg.mozilla.org/releases/mozilla-release/pushloghtml?changeset=b96020a79cfa

1437842 mentioned amongst cherry-picks from upstream in <https://msfn.org/board/topic/177125-my-build-of-new-moon-temp-name-aka-pale-moon-for-xp/?page=35&tab=comments#comment-1151414> (2018-06-23) under _My build of New Moon (temp. name) a.k.a. Pale Moon for XP - Page 35 - Windows XP - MSFN_.

1437842 once (no longer) in the dependency tree for resolved Mozilla bug [1432479 - Spectre mitigations for Value type checks - 64-bit part](https://bugzilla.mozilla.org/show_bug.cgi?id=1432479).

## 1442722

[mozilla-release: changeset 473408:eb37293b1520](https://hg.mozilla.org/releases/mozilla-release/rev/eb37293b1520) (2018-04-06, pushed 2018-06-18 21:12 +0000) was 

> [Bug 1442722](https://bugzilla.mozilla.org/show_bug.cgi?id=1442722) - Move scope into JSStructuredData. r=baku, r=jorendorff, a=RyanVM 

[Refactor structured clone JSAPI to prevent mismatched scopes. · MoonchildProductions/UXP@0e550f2](https://github.com/MoonchildProductions/UXP/commit/0e550f2fb90ada0b608bc1e1982b100291651806) (2018-05-02)

> Roll-up of bugs 1442722, 1455071, 1433642, 1456604 and 1458320.

**Comment by MrAlex94** [comment]
None of those are helpful unfortunately, as Waterfox is currently based on FF that's between ESR52 and ESR60. Which is why I wanted to get other patches out first.

**Comment by hawkeye116477** [comment]
Related with 1437842 `https://github.com/MoonchildProductions/UXP/commit/ff901dc5267903b165c53139ddcff5f31bbf6964`

**Comment by hawkeye116477** [comment]
Do we want it too?
```
https://bugzilla.mozilla.org/show_bug.cgi?id=1462883
https://github.com/MoonchildProductions/UXP/issues/1253
```

**Comment by hawkeye116477** [comment]
Seamonkey already patched:

1442722=> `https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commit/942532d9b9db04b7ce546423b90d0a3ff1d2a375`

1450989 => `https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commit/37bf2df7457af21e4ec5c377b13f69413355789f`

1467363 => `https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commit/eaf8a9f02244b2ea233e762d670b171636d01b8c`

1466577  => `https://gitlab.com/seamonkey-project/seamonkey-2.53-mozilla/-/commit/f90d7e39eebd4496bc4b337808526df26b5adf17`
