### ISSUE TITLE
"Undo" Feature Doesn't Work for Android... 

### ISSUE THREAD

**Issue by Ibuprophen** [BrowserWorks/waterfox#691]
To simply state regarding Waterfox for Android App...

After closing a Website/Webpage Tab, the "Undo" option that pops up at the bottom will appear but, never works when it's selected. 

It would be great, after this feature has been resolved, if the Undo pop up could have a 3-5 second delay added to it before it disappears. 

Thank you very much for your time and understanding with this issue! :-) 

~Ibuprophen

**Comment by grahamperrin** [comment]
Meta, tracking: #538

**Comment by Ibuprophen** [comment]
Should this remain open? 

I just wanted to be sure since I've been scrubbing through open issues from myself and, wanted to know if this is either still being addressed, has already been addressed or cannot be addressed at all. 

Thank you very much! :-) 


~Ibuprophen

**Comment by Ibuprophen** [comment]
@MrAlex94 & @grahamperrin, should I close this issue if it's referenced in https://github.com/MrAlex94/Waterfox/issues/538? 

Or leave it open until it's resolved? 

Thanks a bunch! :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
Leave this open, I think. 

For anyone who has subscribed to this issue: easier to track progress here, than in 538.

**Comment by Ibuprophen** [comment]
Thank you very much for your direction! :-) 


~Ibuprophen

**Comment by Ibuprophen** [comment]
Anything new regarding this @grahamperrin and @MrAlex94? 

Just wondering myself... 😁


~Ibuprophen

**Comment by grahamperrin** [comment]
Nothing that I know of.

**Comment by Ibuprophen** [comment]
I really don't want to be a bother but, I was just curious if there's anything new regarding this issue @grahamperrin and @MrAlex94? 😱

~Ibuprophen

**Comment by MrAlex94** [comment]
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

Could you test this?

**Comment by Ibuprophen** [comment]
I tried @MrAlex94 and the Waterfox Beta v56.1.0 (currently available on the Play Store) I'm currently using is for the ARM 32-bit devices and the new one is not. 

My current/primary device is the Samsung Galaxy S5 klte with LineageOS 16.0 (Android 9.0 - Pie) Installed. 

I've currently got the Waterfox Beta v56.1.0 running pretty well but, I'd really love a new version, even if it were a beta build. 


~Ibuprophen
