### ISSUE TITLE
56.2.2 ("Gah. Your tab just crashed." error)

### ISSUE THREAD

**Issue by strotee** [BrowserWorks/waterfox#692]
I installed the new 56.2.2 and am experiencing odd crashes with this error message: 

"Gah. Your tab just crashed. 
**We can help you!**
Choose Restore This Tab to reload page content."

This occurs when I installed the browser fresh in a VM, then loaded uBlock Origin, then try to go to the dashboard settings. It also occurred yesterday on my host OS (restored to 56.2.1 with no issues) on various login pages. I've found a work-around of sorts. If you uncheck "Enable multi-process Waterfox", then the error disappears and things appear to run normally (but haven't spent a ton of time testing).

**Comment by laniakea64** [comment]
What OS and what OS version?

**Comment by strotee** [comment]
Win 10 LTSB N 2016 (host)
Win 10 RS5 17704 (VM)

**Comment by hawkeye116477** [comment]
Go to about:config and check if layout.css.servo.enabled is true. If is true, then change it to false :smile:.

**Comment by strotee** [comment]
Already set to false.

**Comment by marxosis** [comment]
Disable the NoScript extension ,close Waterfox and try to re-open it to see if it works,it worked for me

**Comment by strotee** [comment]
NoScript? Did you mean uBlock Origin? Your solution is to disable the extension I use just fine in 56.2.1 and what? Leave it disabled? What sort of solution is that?

By the way, I installed the new 17711 (latest build of RS5) and it still crashes with this error. I think there's something amiss in this new version of Waterfox.

**Comment by GitCurious** [comment]
I`m having a similar problem. Win7x64

uBlock dashboard opens but is mostly blank and unpopulated with any data. [no crash]

I DO get the crash however when I try to open the dashboard/prefs of the CookeBro addon, also via the toolbar button.

![2018-07-07_192434](https://user-images.githubusercontent.com/18083484/42413632-1b68fa30-821c-11e8-89e9-0c504de4c063.jpg)
This 'crash' is reproducible every time - not random.

Additionally, uBlock Origin appears to be actually broken. (haven`t tested other addons)

Disabling multiprocess seems to fix it here as well.

**Comment by MrAlex94** [comment]
I’ll investigate this. Maybe a patch integrated incorrectly.

**Comment by grahamperrin** [comment]
> this new version of Waterfox.

Please, what's the build number?

NB 56.2.2 is not yet released. Bugs (and workarounds) may be expected with test builds.

**Comment by strotee** [comment]
Are we not allowed to use test builds and report what we're seeing? Isn't more testing better?

**Comment by GitCurious** [comment]
56.2.2 hasn`t been 'officially' released to the public yet, so there may be changes made behind the scenes...resulting in a different internal build number (not version number)

Several sites picked up **early** on the fact 56.2.2 was physically available on the update server - yet the final public release **may** be different to the one we are testing now.  
Only Alex will know that information.

It`s likely a good thing this issue was noticed and mentioned before the final **public** release as it will potentially save a lot of trouble if it can be verified and fixed beforehand.

**Comment by GitCurious** [comment]
Build ID 	20180705113133

I don`t know if this is relevant:

Multiprocess Windows 	1/1 (Enabled by user)
Web Content Processes 	0/4

yet I **do** see the 4 processes in the task manager.

**Comment by MrAlex94** [comment]
Okay...so this doesn't affect macOS but does Windows. Am doing a git bisect to see what's happened. Also noticed multi web content processes on Windows too, even when off.

**Comment by Squall-Leonhart** [comment]
>Okay...so this doesn't affect macOS but does Windows. Am doing a git bisect to see what's happened. Also noticed multi web content processes on Windows too, even when off.

the GPU process is also created even when acceleration is off.

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/d91f953dc661ea4b412a87a550dcb6b8a62dc59f

Reverted, fixes the add-on issue, such as for uBlock.

In regards to number of processes, I believe that is running correctly. See [here](https://groups.google.com/forum/#!topic/mozilla.support.firefox/FW1P3pfu09w).

**Comment by grahamperrin** [comment]
If it helps, **1456189** <strike>is </strike>was (invisibly) in the dependency tree for an IPC regression: 

- Mozilla bug [1462912 - permafail many crashes [@ mozilla::BufferList<InfallibleAllocPolicy>::Extract(mozilla::BufferList<InfallibleAllocPolicy>::IterImpl &,unsigned int,bool *)] on opt when Gecko 62 merges to Beta on 2018-06-14](https://bugzilla.mozilla.org/show_bug.cgi?id=1462912)

Uplift to **mozilla-esr52** seven weeks ago (2018-05-22): 

- https://hg.mozilla.org/releases/mozilla-esr52/rev/f18535a212da

**Comment by MrAlex94** [comment]
Great find @grahamperrin, just did a test and that solves the issue :-)

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/e9dc9511e5190b72012263e5e1057c3a5e25410e

Please re-open if any issues.
