### ISSUE TITLE
apply change from Attachment #8981969 in bug 1367743 to make About:Profiles launch button work properly.

### ISSUE THREAD

**Issue by Squall-Leonhart** [BrowserWorks/waterfox#693]
https://bugzilla.mozilla.org/show_bug.cgi?id=1367743

This causes the launch profile button to pass "-no-remote" and start new instances with the indicated profile correctly instead of just opening a new empty window in the current process.

**Comment by grahamperrin** [comment]
Meta, tracking: #538
