### ISSUE TITLE
UX, privacy, security: consider defaulting to disallow unsigned extensions

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#695]
With Stylish 3.1.3 as an example, a comparison …

### Firefox 61.0.1 user experience

1. about:config?filter=xpinstall.signatures.required
2. observe the yellow alert, **Here be dragons!** …
3. accept the risk
4. make `xpinstall.signatures.required` `false`
5. aim to install the extension
6. observe the yellow alert, the generic caution about unverified add-ons
7. Add
8. at `about:addons`, observe a single yellow alert, with a generic link – _More information_ – that works
9. eventually, receive a heartbeat message about unavailability of Stylish, with a link  – _Learn more_ – that works.

#### Visually

![2018-07-12 06 34 41](https://user-images.githubusercontent.com/192271/42614607-892c0636-859e-11e8-9466-9ab2b7a3f1e0.png)

![2018-07-12 04 55 57 add-ons manager - mozilla firefox](https://user-images.githubusercontent.com/192271/42614705-ea62dd1c-859e-11e8-9134-91896449d575.png)

> Stylish - Custom themes for any website could not be verified for use in Firefox. Proceed with caution. **More Information**

– with (in my case) more information https://support.mozilla.org/1/firefox/61.0/FreeBSD/en-US/unsigned-addons redirecting to <https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct>.

Learning more: 

![2018-07-12 04 57 57 blocked add-ons - mozilla firefox](https://user-images.githubusercontent.com/192271/42614768-32101f08-859f-11e8-9aba-9701ee2b2c03.png)

(3.1.3 is **not** yet blocked, but that's a separate issue – off-topic from Waterfox.)

----

…

**Comment by grahamperrin** [comment]
The comparison …

#### Waterfox 56.2.1 user experience

1. aim to install the extension
2. observe the yellow alert, the generic caution about unverified add-ons
3. Add
4. at `about:addons` the uppermost yellow alert includes a link that does not work
5. the line below the first yellow alert is another link that does not work
6. the yellow alert for Stylish includes a link that does work
7. no heartbeat – no hint that a prior version (3.1.1) is blocked. 

![2018-07-12 05 11 31 add-ons manager - waterfox](https://user-images.githubusercontent.com/192271/42615139-bc25e5e6-85a0-11e8-8688-f4e5b064a08f.png)

#### Common UX

A welcome to Stylish, for example: 

![2018-07-12 05 41 14](https://user-images.githubusercontent.com/192271/42615530-86d72286-85a2-11e8-97b9-95db3c3248b7.png)

## Related

- https://github.com/MrAlex94/Waterfox/commit/436898372f8589d4a241e924084119358c58bf45 (2018-05-15) modified checks for compatibility; and the `about:addons` GUI to enable checking is not effective
- [about:addons 'Check to see if your plugins are up to date' · Issue #336 …](https://github.com/MrAlex94/Waterfox/issues/336)
- https://www.reddit.com/comments/7ijjzb/-/dqzgb5h/ (2017-12-09) about heartbeat prompts in the context of SHIELD
- https://wiki.mozilla.org/Firefox/Shield

Meta, tracking: #538

**Comment by grahamperrin** [comment]
### Thoughts

With Waterfox 56.2.1 it's too easy to install unsigned, possibly malicious add-ons. 

True: there's a yellow alert at installation time, but those dialogues (and related reference materials) are sometimes verbose and/or difficult for an end user to understand. 

Assume that the user will pay little or no attention. PEBKAM, but this should **not** detract from the wish for Waterfox to take a more cautious approach. 

Critically: learning to ignore **non-working** alerts – https://github.com/MrAlex94/Waterfox/issues/695#issuecomment-404402781 steps 4 and 5, for example – increases the likelihood of end users paying insufficient attention to **genuine** alerts. 

## Suggestion

1. `xpinstall.signatures.required` `true` by default
2. for users who require unsigned add-ons, document what's required. 

https://github.com/MrAlex94/Waterfox/blob/01e6727879b2aa363daa2bdd9878ca7df5039d96/modules/libpref/init/all.js#L4957

– is that it?

**Comment by MrAlex94** [comment]
Sorry, but this is one of the features as even disabling wasn't working for a while on Firefox before they completely disabled it. A lot of older add-ons won't be signed and there's quite a few users use this. If you so wish, disable it for yourself :-)

**Comment by grahamperrin** [comment]
Thanks, understood. It'll help me to draft something for an FAQ.
