### ISSUE TITLE
Waterfox with Gtk2

### ISSUE THREAD

**Issue by luigifab** [BrowserWorks/waterfox#696]
Is there a way to run Waterfox for Linux with Gtk2?

**Comment by laniakea64** [comment]
Try compiling Waterfox from source with the mozconfig option `ac_add_options --enable-default-toolkit=cairo-gtk2`

**Comment by luigifab** [comment]
Yes, but I don't know how to do it.
I'm change my original question to: is there an official build of Waterfox for Linux with Gtk2 from waterfoxproject.org?

**Comment by MrAlex94** [comment]
Ah, unfortunately not :-(

**Comment by luigifab** [comment]
ohhhh :'( okay. I'm so sad.

**Comment by jbeich** [comment]
> `ac_add_options --enable-default-toolkit=cairo-gtk2`

Does it actually build/run? See [bug 1278282 comment 19](https://web.archive.org/web/20180204104300/https://bugzilla.mozilla.org/show_bug.cgi?id=1278282#c19)
