### ISSUE TITLE
china need Firefox Monitor!! please updata

### ISSUE THREAD

**Issue by bAdOoWindy** [BrowserWorks/waterfox#697]
about version!

**Comment by grahamperrin** [comment]
Can you explain?

Maybe a link to something that describes your need. 

Thank you

**Comment by bAdOoWindy** [comment]
https://blog.mozilla.org/futurereleases/2018/06/25/testing-firefox-monitor-a-new-security-tool/

**Comment by bAdOoWindy** [comment]
new version (not just firefox also extend ) fixed bugs,Performance improvement ,ui  Customized

**Comment by grahamperrin** [comment]
### Firefox Monitor

https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&order=Bug%20Number&list_id=14234406&short_desc=Firefox%20Monitor&short_desc_type=substring finds three Mozilla bugs:

- [1463301 - [Shield] Opt-out Study: Firefox Monitor](https://bugzilla.mozilla.org/show_bug.cgi?id=1463301)
- [1473132 - Package Firefox Monitor UI variations individually for user-testing](https://bugzilla.mozilla.org/show_bug.cgi?id=1473132)
- [1475126 - Ship Firefox Monitor UI in m-c](https://bugzilla.mozilla.org/show_bug.cgi?id=1475126).

From 1475126, targeting Firefox 62: 

> … gather some opinions on how we want to ship this. The two routes I see are a) system add-on, b) bake into browser code. …

### SHIELD

[About SHIELD Studies | Firefox Help](https://support.mozilla.org/en-US/shield)

Not a feature of Waterfox; https://www.reddit.com/comments/7ijjzb/-/dqzgb5h/

### Cloudflare

From Mozilla's blog post: 

> … worked closely with HIBP and [Cloudflare](https://blog.cloudflare.com/validating-leaked-passwords-with-k-anonymity/) …

The Cloudflare blog post: 

[Validating Leaked Passwords with k-Anonymity](https://blog.cloudflare.com/validating-leaked-passwords-with-k-anonymity/)

Consider: 

- in the Waterfox support area, the _anti-Cloudflare_ comment above https://www.reddit.com/comments/8p4x1q/-/e1jffzc/?context=1
- the _rant_ at <https://redd.it/8ixnfa> (not my rant, but I did reply). 

I should encourage discussion of Cloudflare at https://www.reddit.com/r/CloudFlare/ (not here in the Waterfox repository). 

### For Waterfox

Given the possibility of anti-Cloudflare reactions from some members of the community, there may be: 

- resistance to a system add-on; and/or 
- calls for baked-in Firefox code to be removed from a Waterfox that will be based on [future Firefox ESR](https://wiki.mozilla.org/Release_Management/Calendar#Future_branch_dates) 68. 

#### A non-system extension, maybe

Mozilla bug 1463301 began with an intention of (SHIELD) shipping to Firefox 60. 

<strike>If I can get a copy of the extension, </strike>I'll try it with Waterfox 56.2.1. I imagine that it will be incompatible.

**Comment by grahamperrin** [comment]
> I'll try it with Waterfox 56.2.1. I imagine that it will be incompatible.

### Firefox Monitor 1.2

<strike>Waterfox 56.2.1 defaults to not check for compatibility, so </strike>the extension installs without difficulty (ignoring the strict minimum): 

![2018-07-14 07 03 24 1463301 - shield opt-out study firefox monitor](https://user-images.githubusercontent.com/192271/42721713-6f32b49c-8737-11e8-9c56-7adb68dc2754.png)

Permission required: 

- Monitor extension usage and manage themes

#### Compatibility and usability

`strict_min_version` `61.0`

Version 1 of the study ended four days ago. 

### Beyond 1.2

https://bugzilla.mozilla.org/show_bug.cgi?id=1475126#c3 asks whether a future version of the extension might be compatible with Firefox ESR 60.

**Comment by bAdOoWindy** [comment]
Fantastic!!!
