### ISSUE TITLE
Crash When Dragging URL

### ISSUE THREAD

**Issue by AndrewPaglusch** [BrowserWorks/waterfox#70]
I've noticed that Waterfox will crash every time I:
1. Click a hyperlink
2. Before the new URL has loaded, click and drag a second hyperlink on that page (can be the same one you just clicked. It makes no difference).
3. Wait until the new page has loaded. Continue to holding the second hyperlink
4. Once the new URL is loaded, drop the second hyperlink onto the tab bar.
5. Crash

I'm currently running Waterfox v47.0.1 on OS X El Capitan

Please let me know if any extra information is needed.

**Comment by MrAlex94** [comment]
Do you get this with 48/49?

**Comment by AndrewPaglusch** [comment]
I just tried to reproduce this again on 48.0.2. The problem remains

**Comment by NotSoSuper** [comment]
I'm also getting this on MacOS Siera.

**Comment by MrAlex94** [comment]
Tried reproducing in v55, no crash. Re-open if this still occurs.
