### ISSUE TITLE
Open new tab does nothing in Vimium/Surfingkeys

### ISSUE THREAD

**Issue by Freedzone** [BrowserWorks/waterfox#701]
Hi.
Love Waterfox and philosophy behind it. 
But one thing that stops me from migration is new tab problem with Vimium or Surfingkeys. Whatever option i tried with these plugins, they simply cannot open new tab. And that's occurs only in Waterfox.

**Comment by grahamperrin** [comment]
### [Vimium](https://addons.mozilla.org/addon/vimium/) 1.36 

![2018-07-22 23 29 17 add-ons manager - waterfox](https://user-images.githubusercontent.com/192271/43050965-4b52833a-8e09-11e8-8b30-cee345a1f73a.png)

<kbd>F</kbd> works as expected. 

### Automation

Waterfox no longer has the ability to automatically disable multi-process where an extension is incompatible with multi-process. 

### Compatibility

[e10s (multi-process) compatibility reports at addons.mozilla.org (AMO) : waterfox](https://www.reddit.com/r/waterfox/comments/8c77ii/e10s_multiprocess_compatibility_reports_at/) – I added a line for Vimium.

**Comment by Freedzone** [comment]
The problem is `Error: Type error for parameter createProperties (Property "openerTabId" is unsupported by Firefox) for tabs.create.` in [openLink()](https://github.com/brookhong/Surfingkeys/blob/cae52688520bf806b86f2f3f19e22406ecba6b36/background.js#L924). Indeed it is supported by [firefox 57+](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Tabs/create)
Without this parameter it works fine.
But i could not find any usages of **openerTabId**. I suppose it can be safely removed from plugin, isn it?

**Comment by grahamperrin** [comment]
> … I suppose it can be safely removed from plugin, isn it?

If about Surfingkeys, I suggest posting under https://github.com/brookhong/Surfingkeys/issues/807 instead.
