### ISSUE TITLE
Can't login at att.com

### ISSUE THREAD

**Issue by vanowm** [BrowserWorks/waterfox#702]
Attempting login at http://att.com/my produces an error (you don't need an account, just type anything):

```
JBWEB000065: HTTP Status 403 -
JBWEB000309: type JBWEB000067: Status report
JBWEB000068: message
JBWEB000069: description JBWEB000123: Access to the specified resource has been forbidden.
JBoss Web/7.4.8.Final-redhat-4
```

Fresh Windows/Waterfox/profile.
Changing user agent string doesn't help.

Error console shows:

```
SyntaxError: invalid regular expression flag ÿ[Learn More]  jquery-1.11.3.min.js%20line%202%20%3E%20eval:1:22
	getActualUserIdFieldValue https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:403:33
	getUserIdFieldValidationStatus https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:415:22
	getLoginFormValidationStatus https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:457:31
	isValidFormToBeSubmitted https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:588:31
	onsubmit https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:159:43
	json2html_events/< https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:16:413
	dispatch https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:3:12392
	add/r.handle https://www.att.com/ui/global_all_cms_common/libs/jquery/1.11.3/jquery-1.11.3.min.js%20line%202%20%3E%20eval:3:9156
```

This very much looks like related to 

https://bugzilla.mozilla.org/show_bug.cgi?id=1452619

Windows 10 x64 1803/Waterfox 56.2.2

There might be more info:
https://www.reddit.com/r/waterfox/comments/8mva2g/error_logging_into_att_uverse_account/

**Comment by grahamperrin** [comment]
Cross reference: 

- [Can't Login to AT&T : waterfox](https://www.reddit.com/r/waterfox/comments/908trh/cant_login_to_att/) (2018-07-19)

>  Changing user agent string doesn't help.

Which strings have you tried?

For me with Waterfox 56.2.2 on FreeBSD-CURRENT, http://att.com/my progresses to https://www.att.com/my/#/login and an attempt to sign in with a nonsensical user ID (I should discourage this) results in: 

> The User ID and password combination you entered doesn't match any entries in our files.
> 
> Select Forgot ID? or Forgot password? below for further assistance.
> 
> (LU100)

**Comment by grahamperrin** [comment]
If it helps, from a [Web REC](https://addons.mozilla.org/addon/web-rec/?src=external-Add-ons_Manager_Context_Menu-extension) recording of gaining the sign in dialogue **without** error 403: 

![2018-07-23 01 40 39 web rec - waterfox](https://user-images.githubusercontent.com/192271/43052063-886cdd8c-8e19-11e8-978a-12ed9480409f.png)

**Comment by vanowm** [comment]
Then it must be Windows only issue.
The javascript fails to produce proper request, hens is 403 error.

**Comment by grahamperrin** [comment]
> from a Web REC recording 

The recording, in full: 

- [2018-07-23 01:31.wbr.zip](https://github.com/MrAlex94/Waterfox/files/2226487/2018-07-23.01.31.wbr.zip)

Key: 

- `XzvY9SbZGbW0Iw0IkPh2YcmToU0Z0qnDmtmu7kGdMJ8=`

**Comment by vanowm** [comment]
Works in v56.0.3 now
