### ISSUE TITLE
language pack.

### ISSUE THREAD

**Issue by agasthene** [BrowserWorks/waterfox#703]
Hello

Concerning the language packs and the language of watefox, all the packs are not valid for waterfox.

There may be a delay in the version. firefox is the standard version is version 61 and goes to quantum.

**Comment by grahamperrin** [comment]
1. about:preferences#general
2. Locale select

Language packs are integrated, there should be no need to add to Waterfox 56.2.2. 

Does one of the integrated locales not work for you?

**Comment by hawkeye116477** [comment]
If you installed waterfox/waterfox-kde from my apt repository, then language packs aren't integrated, but they can be installed also from my apt repository, just search **waterfox-locale-*** :smile:.

**Comment by agasthene** [comment]
for grahamperrin everyone does not necessarily speak the language of sheakspeare

for the language pack, I must rephrase what I have said: not all versions are compatible with waterfox.

and if the packs for wterfox are available elsewhere this feature is no longer available in the browser that automatically returns to mozilla.

in the old home page of the waterfox site or if I have good memory, the download page, there was indeed the list of language packs proposed for waterfox itself.

what is no longer available now;

**Comment by grahamperrin** [comment]
> everyone does not necessarily speak the language of sheakspeare

Here, Greek (amongst the integrated locales, available in the browser): 

![2018-07-25 06 19 15 - waterfox](https://user-images.githubusercontent.com/192271/43181042-25cd28c4-8fd3-11e8-8fc6-0ace2d6acacd.png)

**Comment by Mahabarata** [comment]
For me langage is not ok.
I have done that : change the local langage and choose french
But some things are still in english :
- in the advanced options, general, I checked  for the spelling but the dictionary is in english so every word I type in french is underlined in red
- in the help menu, about waterfox : the menu is ok ("à propos de waterfox") but the window is in english
- in the bookmarks menu ("marque-pages"), the last line (recent tags) is in english
Best regards

**Comment by grahamperrin** [comment]
> in the advanced options, general, I checked for the spelling but the dictionary is in english so every word I type in french is underlined in red

Dictionaries are separate from language packs. Try [French spelling dictionary – Add-ons for Firefox](https://addons.mozilla.org/addon/dictionnaire-fran%C3%A7ais1/)

**Comment by hawkeye116477** [comment]
Yeah, rather should be waterfox-languagepacks repo just like on Cyberfox and someone should translate :smile:. On context menu also some words are still in Enligsh, `duplicate tab`, `open in  new non 10es windows`. Also some search enignes are in English. Cyberfox has that, so why Waterfox wouldn't?

**Comment by grahamperrin** [comment]
> in the bookmarks menu ("marque-pages"), the last line (recent tags) is in english

With one new profile in 56.2.2: the bookmarks toolbar was unexpectedly empty, and _Recent Tags_ did not exist. 

With a more recent new profile in 56.2.2: 

- no issue with emptiness :+ 
- _Most Visited_ is not translated (to French). 

At the time of writing, I can't compare with localisations in Firefox 56.0.2 or 62.0.

**Comment by Mahabarata** [comment]
Dictionaries are separate from language packs. Try French spelling dictionary – Add-ons for Firefox

When I read informations about waterfox, I believe to understand that this software is built upon an old version of firefox.
I use Firefox since version 2 (up to the last version) and I always have automatic french corrections, I never install a specific add-on.
For me, if waterfox needs an add-on, it looks like a bug.

Best regards

**Comment by hawkeye116477** [comment]
@Mahabarata But Firefox has few versions for languages for Windows, so for example Polish version contains Polish language pack and Polish dictionary. Hovewer on Linux, dictionary extension isn't need, cuz Linux has hunspell and we can do symlink to it.

**Comment by agasthene** [comment]
Note that the most recent extensions are no longer compatible with 
waterfox, mozilla technology having changed these extensions can not be 
installed on waterfox.

Le 23-09-18 à 19.32, hawkeye116477 a écrit :
> But Firefox has few versions for languages for Windows, so for example 
> Polish version contains Polish language pack and Polish dictionary. 
> Hovewer on Linux, dictionary extension isn't need, cuz Linux has 
> hunspell and we can do symlink from hunspell to waterfox/dictionaries.

**Comment by grahamperrin** [comment]
> … the most recent extensions are no longer compatible with waterfox …

### Dictionaries

https://addons.mozilla.org/addon/dictionnaire-fran%C3%A7ais1/versions/?page=1#version-6.3 (the most recent) works for me with Waterfox 56.2.3. 

### Language packs

https://addons.mozilla.org/addon/fran%C3%A7ais-language-pack/versions/?page=1#version-56.0 (not the most recent) "Works with Firefox 56.0 - 56.*" (and should not be added to Waterfox).

**Comment by Mahabarata** [comment]
I'm not expert but when I read your answers it looks not good for the future of Waterfox : this software was made because of version 57 of Firefox which was very new for add-on. Most of old add-on, which works with Firefox 56 or older and waterfox, are changed to work with Firefox 57 and more and so stop to work with old versions of Firefox... and waterfox.
One day, there will be no more add-on for waterfox so the reason of existence of this software will disappear, a lot of people will stop to use waterfox and it will be the dead of this sofware...
For the moment it's ok because on the add-on pages we can find old versions of the add-on but how long ?

**Comment by hawkeye116477** [comment]
@Mahabarata For legacy addons, Waterfox will have own addon repository soon and newer webextensions still will be installable from AMO.

**Comment by Mahabarata** [comment]
Great !
Have a nice day
Best regards

**Comment by bogachenkove** [comment]
### I do not want to create a new question, so I will write here. However, the question is a bit off topic. but I do not care.

@MrAlex94  Where can I write to fix localization errors?

![111111111111](https://user-images.githubusercontent.com/8535285/50450360-5ec63a00-0925-11e9-84e5-c044e03dff2d.png)

**Comment by Mahabarata** [comment]
Mahabarata said :
>  I'm not expert but when I read your answers it looks not good for the future of Waterfox : this software was made because of version 57 of Firefox which was very new for add-on. Most of old add-on, which works with Firefox 56 or older and waterfox, are changed to work with Firefox 57 and more and so stop to work with old versions of Firefox... and waterfox. One day, there will be no more add-on for waterfox so the reason of existence of this software will disappear, a lot of people will stop to use waterfox and it will be the dead of this sofware... For the moment it's ok because on the add-on pages we can find old versions of the add-on but how long ?

What I was suggesting is now the truth : 
1) the add-on Greasemonkey has so many new versions that, in the old versions page, there are now only versions 4.x : the version 3.17, working with Firefox 56 and Waterfox, has disappeared
2) the last version (6.3.1) of the dico in french doesn't work anymore with Waterfox : all the words in french are underline in red.
We need to install the old version (6.3) of this dico to have something working : how long before this old version disappeared and no more dico will be ok ?


hawkeye116477 said :
> @Mahabarata For legacy addons, Waterfox will have own addon repository soon and newer webextensions still will be installable from AMO.

I looks like we need this very quickly !!!

**Comment by grahamperrin** [comment]
Dictionaries and Greasemonkey are off-topic from language packs. Please see https://www.reddit.com/r/waterfox/comments/adznrq/-/ee42sut/
