### ISSUE TITLE
CentOS 7 GLIBC 2.18 issue

### ISSUE THREAD

**Issue by mangz007** [BrowserWorks/waterfox#707]
Sorry to start this,
But I have a CentOS 7 machine and when I tried running waterfox I got the following error

XPCOMGlueLoad error for file /home/mchimote/waterfox/libxul.so:
/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/mchimote/waterfox/libxul.so)
Couldn't load XPCOM.

CentOS 7 has GLIBC 2.17 and I saw nothing that will help me in upgrading it to 2.18
Please Help

**Comment by grahamperrin** [comment]
Have you tried asking in the forum? https://www.centos.org/forums/

I found at least one topic about 2.18

Also https://github.com/MrAlex94/Waterfox/issues/205#issuecomment-366253989

**Comment by hawkeye116477** [comment]
Unofficial working package is on `https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-kde`.
