### ISSUE TITLE
Ellipsis bug in Firefox (and Waterfox) prior to version 59

### ISSUE THREAD

**Issue by defrilitus** [BrowserWorks/waterfox#708]
There was a bug in Firefox whereby any web extension that showed user-selected text in the context menu automatically had an ellipsis appended. This has apparently been fixed in FF 59; would it be possible to fix it in Waterfox as well?

Please see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1370228) for the technical information from Bugzilla relating to this bug and its resolution; while [this](https://imgur.com/eCRk2KX) screen grab may help explain it more clearly.

This small problem is obviously not very important ;-) But it would be nice if it could be fixed in Waterfox as well as in Firefox. Thanks in advance!

**Comment by grahamperrin** [comment]
Mozilla bug [1370228 - Context menu title with placeholder always shows ellipsis](https://bugzilla.mozilla.org/show_bug.cgi?id=1370228)

https://hg.mozilla.org/mozilla-central/rev/8882102c7640

> [r=mixedpuppy]

> author	Lukas Jung <lukas.jung>

----

To help visualise the issue … 

### A legacy extension, not bugged

![legacy not bugged](https://user-images.githubusercontent.com/192271/43626334-543af3fe-96e9-11e8-9e32-872d9ae667ee.png)

### A bugged extension

![bugged](https://user-images.githubusercontent.com/192271/43626363-773ad2c0-96e9-11e8-8a35-6059ccb4b965.png)

### Fixed

![firefox](https://user-images.githubusercontent.com/192271/43626374-7ef699c2-96e9-11e8-8c13-73dd164f06b0.png)

One of the context menu items does use an ellipsis, but that's an extension issue (not Mozilla bug 1370228).

**Comment by defrilitus** [comment]
Sorry, I'm getting a bit confused (to be honest, we are now above my level of competence). Are you saying that there is a bug in Waterfox/Firefox, a bug in the [Swift Selection Search add-on](https://github.com/CanisLupus/swift-selection-search) or something else entirely? Apologies if I'm a bit slow ;-)

Incidentally, there are other web extensions that exhibit the same behaviour in Waterfox; for example, [macOS Dictionary Lookup](https://addons.mozilla.org/en-US/firefox/addon/macos-dictionary-lookup/?src=api). In fact, are there any web extensions with placeholders that don't  add the ellipsis in Waterfox?

**Comment by defrilitus** [comment]
Comments, please.

**Comment by grahamperrin** [comment]
Meta, tracking: #538
