### ISSUE TITLE
DRM widevine don't work

### ISSUE THREAD

**Issue by Bundy01** [BrowserWorks/waterfox#709]
OS: archlinux
Waterfox: 56.2.2 (64 bits)
Widevine version: 1.4.8.1008

I have enabled the following options in about:config.
`media.eme.enabled`
`media.eme.vp9-in-mp4.enabled`
`general.useragent.compatMode.firefox`

I need DRM to read French TV with this extension: https://addons.mozilla.org/en-US/firefox/addon/cocktail-molotov/

The widevine files are present in.waterfox, do you have a solution to make it work?

**Comment by Ibuprophen** [comment]
Have You tried adding/enabling the following about:config entry (aka value = true)? 

media.mediadrm-widevinecdm.visible

Just wondering... :-) 


~Ibuprophen

**Comment by Bundy01** [comment]
I just created the value, but the stream is still unbreakable.

**Comment by grahamperrin** [comment]
> OS: archlinux

I do not have credentials for Molotov, but Widevine does work for me with Waterfox 56.2.2 on Linux (Kubuntu). 

Try [Netflix does not work on Waterfox 56 · Issue #316 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/316) – closed, not an issue with Waterfox.

**Comment by Bundy01** [comment]
Do you know a website that tests DRM?
Have you done any special manipulations to make widevine work?

**Comment by Bundy01** [comment]
It's definitely a Waterfox problem, with Firefox it works. I tried to copy the Firefox profile into a new Waterfox profile but the problem persists; so I think it's due to an internal configuration. I also compared the two `about:config` without result :/

**Comment by Ibuprophen** [comment]
I've found that "similar" issues arise if one or more of the NPAPI Plugins needs to be updated like the Adobe Flash Player, Adobe Shockwave and Java. 

Just a thought... :-) 


~Ibuprophen

**Comment by Bundy01** [comment]
I have only flash but it's up to date :/

**Comment by Ibuprophen** [comment]
I always have all 3 because some websites also use Shockwave, some use Java and some use a combination of the 3.

I can only Suggest/Recommend... :-) 


~Ibuprophen

**Comment by Bundy01** [comment]
The site in question only uses DRM and I confirm that with the same configuration it works with Firefox.

**Comment by grahamperrin** [comment]
> Do you know a website that tests DRM? …

<strike>The trailers linked from issue 316 do use DRM.</strike>

Sorry, please ignore that. 

From <https://github.com/MrAlex94/Waterfox/issues/927#issuecomment-487375711>: 

> … I previously believed that Amazon trailers required DRM because they do not play (without DRM) on FreeBSD. My bad. Apologies for any confusion.

**Comment by grahamperrin** [comment]
> Do you know a website that tests DRM?

https://redd.it/aex1ez offers three examples: 

1. <https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd;lang=en-US;build=uncompiled> 
2. <http://demo.theoplayer.com/drm-aes-protection-128-encryption> – choose _Digital Right Management_
3. <https://bitmovin.com/demos/drm>.

From the commentary, with emphasis: 

>> the third example **plays in the absence of DRM** (on FreeBSD-CURRENT).

**Comment by grahamperrin** [comment]
@Bundy01 please retry with Waterfox Current 68.0b1 (Widevine CDM 4.10.1440.18) and/or Waterfox Classic 56.2.14 (Widevine CDM 4.10.1440.19).

**Comment by grahamperrin** [comment]
> archlinux

#1051 by me might be a duplicate … apologies …

**Comment by grahamperrin** [comment]
#709

> ## DRM widevine don't work

> … archlinux …

https://github.com/MrAlex94/Waterfox/issues/1117#issuecomment-543194143

> DRM hasn't ever worked on Waterfox Classic on *nix style OSs. I remember spending time a couple of years ago looking into why, but could never locate the issue.

DRM **does** work *at some sites* with Waterfox Classic 2019.10 on Manjaro Linux. 

Tested: 

[TG4 | Irish TV | Irish Television Channel | Súil Eile | Gaeilge](https://www.tg4.ie/en/) ▶ https://www.tg4.ie/en/player/home/?pid=6112002457001&series=Saol%20an%20Mhadra%20Bh%C3%A1in&genre=Faisneis

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/709#issuecomment-410298938 @Bundy01 asked: 

> Do you know a website that tests DRM? …

### Test Patterns | Netflix

https://www.netflix.com/title/80018499

– truncated from the URL suggested at https://addons.mozilla.org/addon/netflix-1080p/

Result: 

![image](https://user-images.githubusercontent.com/192271/70257104-9ec2ad80-1781-11ea-8e7f-e283d9b93bba.png)
