### ISSUE TITLE
Today's build flickers on scrolling

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#71]
Today's build flickers on scrolling which is really annoying (especially on [this page](https://www.waterfoxproject.org/blog/waterfox-48.0-release-download))…

**Comment by MrAlex94** [comment]
Have you tried[ disabling hardware acceleration](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration)?
