### ISSUE TITLE
Incompatible App Browser... 

### ISSUE THREAD

**Issue by Ibuprophen** [BrowserWorks/waterfox#710]
Hello There! :-) 

I wasn't sure if you were aware of various Google settings for Google+ and other areas reflecting an incompatible Android Browser and won't allow me to proceed in those areas. 

I've attached an image example of the exact message/display I've been receiving (which isn't a big deal for me since I just use my backup browser for those specific places). 

Please keep in mind that I've got the latest Waterfox Beta Release from the Play Store. 

[example1](https://user-images.githubusercontent.com/18060271/43617363-a3ab0abe-968f-11e8-8e98-ffefd4830785.png)

Thanks a bunch for your developments and I hope that I was helpful in some way. 

~Ibuprophen

**Comment by grahamperrin** [comment]
Can a user agent string be set? Maybe with an extension …

**Comment by Ibuprophen** [comment]
Unfortunately not... 

I've even attempted to bump up the PlatformVersion(s) and AppVersion(s) within the about:config with no success. 

As opposed to the PC Browser (Though I've rarely ever needed to) modify any of the Version(s) within the about:config and I used to be able to do this successfully but, not on the Android Browser. 

I've even tried restarting the Android Device and even uninstalled and reinstalled then made the changes within the about:config as well but, the Google error for the Android Browser still remains. 

Unless I examine the app itself on my PC for my own personal modifications, i can't get the Version to be seen as a later version. I don't want to do this part because I've got my other App developments I've got to work on (as an Android app Developer myself).

I really love this browser and the way that the Waterfox App kept its UI as it should be since Firefox had just ruined the UI Look when they updated that. Firefox is now ugly looking (LMAO!) and it can't be reverted without my manual intervention that I'm trying to avoid. 

I'm jabbering on too much but, I hope that you have a better idea on dealing with the increased issue regarding an older Android Version being reflected via websites.

Thanks a bunch! :-) 


~Ibuprophen

**Comment by MrAlex94** [comment]
New version for Android is almost ready, but it's based on newer Firefox releases with Tor browser patches implemented :-). The reason for this is simple, XPCOM add-ons aren't very plentiful, so it's not a blocker for an updated release. Instead the Android browser can focus more on privacy features and the likes. Plus the builds are successful with no Google Play and limited permissions :-)

**Comment by Ibuprophen** [comment]
@MrAlex94, the only portion that I would like to be able to keep is provided on the following example image... 

[example 1](https://user-images.githubusercontent.com/18060271/43787546-41ac5374-9a39-11e8-8b08-f19a024004bc.png)

... because when they messed with the actual Look, it was extremely difficult to even locate a theme that got this look anywhere close to it. 

Thank you very much for your time, support and understanding with this! :-) 


~Ibuprophen

**Comment by Ibuprophen** [comment]
I'm closing this since I'm being told elsewhere from another individual here that the 32-bit is being dropped completely by @MrAlex94... Thank you! :-) 


~Ibuprophen
