### ISSUE TITLE
Portable profile path

### ISSUE THREAD

**Issue by frederick22** [BrowserWorks/waterfox#712]
I'm running Waterfox as my default browser. no other browser can compete.
The profile paths are:
C:\Users\xxx\AppData\Local\Waterfox\Profiles
C:\Users\xxx\AppData\Roaming\Waterfox\Profiles

I've now also installed the portable version from PortableApps but in a different partition/drive. Not set as default.
What I cannot figure is what the profile paths should be?
Currently it's the same the fully installed version on the C drive.
Is this correct, shouldn't it be within the portable installed folder somewhere to make it fully portable?

Any suggestion most welcome.

**Comment by Rikk** [comment]
'PortableApps' places everything inside its own folder in subfolders. I can't help more with details, because I use Firefox/Waterfox native command-line to specify profile folder and don't use these third-party (but officially supported) "Portable" packages.

**Comment by frederick22** [comment]
Thanks Rikk, yes I found the profile folder inside the PortableApps setup but I now think the confusion is due to the extension "ProfileSwitcher" which by default goes to C:\Users\xxx\AppData\...
I'll just have to live with it.

**Comment by Rikk** [comment]
My tip is you download zip version (or extract from installer), create shortcut or batch file using -P parameter: http://kb.mozillazine.org/Command_line_arguments

**Comment by frederick22** [comment]
I will give it a go, thanks.
