### ISSUE TITLE
An iframe bug in firefox

### ISSUE THREAD

**Issue by RaitaroH** [BrowserWorks/waterfox#715]
**Describe the bug**
See https://github.com/openstyles/stylus/issues/215. But the gist is the Stylus cannot theme iframes due to a bug in firefox here: [bugzil.la/1389241](https://bugzilla.mozilla.org/show_bug.cgi?id=1389241)

I was wondering if waterfox could fix that. tophf managed to have an workaround for the newer firefox but waterfox still does not work.

**Comment by grahamperrin** [comment]
Meta, tracking: #538
