### ISSUE TITLE
Distrorted images on varius websites (http://whois.domaintools.com/ and on pdf viewer)

### ISSUE THREAD

**Issue by ssavva05** [BrowserWorks/waterfox#716]
Hello,
 If i visit http://whois.domaintools.com/ from waterfox in some devices running mac OS , or if i try to open a pdf in waterfox from the same device is reproduce a distortion graphic loop instead. I am afraid that this might be a firefox issue as well, but in chrome the website is working fine. I fix the pdf issue in waterfox using a google plugin to open pdf instead of the default viewer , Is there any way to fix the distortion in the websites as well? 
 
p.s. the  device is an a1181 macbook with mac OS 10.8 . I love waterfox and it ability to run on mac os 10.8 . I want to help to make it better!
 
![dist](https://user-images.githubusercontent.com/22216008/44078461-33e03532-9faf-11e8-8ca8-d735fb44597c.jpg)

**Comment by laniakea64** [comment]
Have you tried disabling hardware acceleration? - https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration

**Comment by ssavva05** [comment]
Yes! is working perfectly right now! Thanks a lot, I forget about those hidden settings!!!
