### ISSUE TITLE
Open in app always visible on Android

### ISSUE THREAD

**Issue by vojta-horanek** [BrowserWorks/waterfox#717]
There is an Android icon visible on every webpage next to the URL bar that should open an app for a certain website, but it's there even when I don't have the app installed. When I press it, it just refreshes the webpage. I would like to turn this feature off completely otlr at least fix is so that it only shows when the app that can handle a certain webpage is installed.

1. Go to any website
2. An Android icon appears next to the URL bar
3. When the icon is pressed the page is refreshed

**Expected behavior**
The icon should only appear if an app that can open a certain website is installed. This feature could be preferably turned off.

**Screenshots**
(Unfortunately can't screenshot Waterfox on Android)

 - Device: Xiaomi Redmi Note 4X
 - OS: Android 9.0 Pie
 - Version 60.0.1

**Comment by grahamperrin** [comment]
> … on every webpage …

Not for me. For example, not at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225233 and not at https://gist.github.com/grahamperrin/1815ce5ec1f5c3cfb3d5750b03fe923d

I do get the icon at https://www.reddit.com/r/waterfox/ and the associated dialogue does work with the two compatible apps that are on my handset: Boost and Reddit.
