### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [BrowserWorks/waterfox#718]
Now that Waterfox has dropped play services, it could consider publishing on F-Droid too!

**Comment by dimqua** [comment]
It's great, but the source code of the latest Android version (60.1.0) is not released yet.

**Comment by nicolasmaia** [comment]
Oops, this seems to be a duplicate of WaterfoxCo/Waterfox-Android#40

**Comment by kowith337** [comment]
I swear about pre-update to v60 that I've found by exodus report that v56 have `Google Firebase`, now I think Waterfox is eligible to release on F-Droid.

**Comment by DI555** [comment]
I'm so much awaiting either! Any good news?

**Comment by grahamperrin** [comment]
> duplicate

Yep, mark this issue as _closed_ if you like. Thanks.

**Comment by nicolasmaia** [comment]
Closing in favor of the older WaterfoxCo/Waterfox-Android#40
