### ISSUE TITLE
connects to waterfoxproject.org every launch and leaves cookie, why?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [BrowserWorks/waterfox#72]
Hi,

Can you please explain the purpose of both connecting to waterfoxproject.org on every launch & **more importantly**, why a cookie is left, despite not actually browsing the site? I never experienced this issue with a standard Mozilla Firefox installation.

waterfox.exe    6708    TCP 12920       192.168.1.101   443 https   104.28.27.103   www.waterfoxproject.org Established C:\Program Files\Waterfox\waterfox.exe  Waterfox    Waterfox    48.0.1  Waterfox    9/6/2016 10:13:21 PM    DESKTOP-x\x     A   9/6/2016 10:13:40 PM            Waterfox    

I wouldn't be aware of it if not for self destructing cookies purging said cookie.

Thanks

**Comment by dalu** [comment]
```
curl -v www.waterfoxproject.org
* Rebuilt URL to: www.waterfoxproject.org/
*   Trying 104.28.26.103...
* TCP_NODELAY set
* Connected to www.waterfoxproject.org (104.28.26.103) port 80 (#0)
> GET / HTTP/1.1
> Host: www.waterfoxproject.org
> User-Agent: curl/7.50.3
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Sat, 17 Sep 2016 13:22:37 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=df42a7aab6aa41fd2651ca6778c47cb0f1474118557; expires=Sun, 17-Sep-17 13:22:37 GMT; path=/; domain=.waterfoxproject.org; HttpOnly
< Location: https://www.waterfoxproject.org/
< X-Content-Type-Options: nosniff
< Server: cloudflare-nginx
< CF-RAY: 2e3cde397651395e-VIE
< 
* Curl_http_done: called premature == 0
* Connection #0 to host www.waterfoxproject.org left intact
```

It's Cloudflare setting a cookie  with __cfduid=df42a7aab6aa41fd2651ca6778c47cb0f1474118557
which can be read by the domain waterfoxproject.org and subdomains only.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
That is good information, but why? Why every launch? Won't know until he replies I guess.

**Comment by Atavic** [comment]
Try to untick _check for updates_

**Comment by MrAlex94** [comment]
[Here is information on what the cookie does:](https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-CloudFlare-cfduid-cookie-do-)

> The __cfduid cookie is used to override any security restrictions based on the IP address the visitor is coming from. For example, if the visitor is in a coffee shop where there are a bunch of infected machines, but the visitor's machine is known trusted, then the cookie can override the security setting. It does not correspond to any userid in the web application, nor does the cookie store any personally identifiable information.
> 
> Note: This cookie is strictly necessary for site security operations and can't be turned off.
