### ISSUE TITLE
Bugzilla 1420171: Will you fold known fix into Waterfox?

### ISSUE THREAD

**Issue by reikred** [BrowserWorks/waterfox#721]
Hi Alex,

I need the fixes from https://bugzilla.mozilla.org/show_bug.cgi?id=1420171

Thinking about making a branch from the latest code to do the patching work. If I do, will you accept a merge (pull request I guess they call it) from me?

**Comment by reikred** [comment]
UPDATE: read further comments below first.

Alex, creating a branch (fork?) and patching this bug  has proven to be a bit difficult for me. I have discovered a tall learning curve of git and github, unfortunately.

Perhaps someone who is more of a wizard than I could try and merge the fixes into waterfox. According to the original bugzilla, the necessary patches are as follows: 

https://hg.mozilla.org/mozilla-central/rev/d602eb4467cd
https://hg.mozilla.org/mozilla-central/rev/8c4514cb4120
https://hg.mozilla.org/mozilla-central/rev/85b0368a8c80

It is not a terribly complicated fix, but how to get these diffs/patches from hg into github is beyond my capability at the moment. Can anyone please help? Alex?

**Comment by reikred** [comment]
Hmm, I think I was able to incorporate the known fixes by editing a branch directly on github web rather than having to do a local repository etc etc. Perhaps it was not quite as difficult as I thought it would be. Anyway, please accept/merge my pull request, which is the following link:

https://github.com/MrAlex94/Waterfox/pull/731

**Comment by MrAlex94** [comment]
Ah sorry for not replying sooner, I have already commited the fixes:
https://github.com/MrAlex94/Waterfox/search?q=1420171&type=Commits

Thanks for going through the effort though, hopefully you managed to at least gain some knowledge going through the process 😄

**Comment by reikred** [comment]
Alex, as far as I can tell the previous fixes (commits)  you refer to are  NOT appearing  in the latest git. commit ( https://github.com/MrAlex94/Waterfox/commit/432b42717b0678a933f9d0731f02f9d1d32bdec2). Please look for yourself at line 408 of the following.

https://github.com/MrAlex94/Waterfox/blob/master/widget/gtk/nsDeviceContextSpecG.cpp

I still see the old unfixed code. How is that possible? Also, waterfox 56.2.2 exhibits the behavior that the fix is supposed to abate. Something is amiss here. Can you please double-check?

**Comment by reikred** [comment]
I sure hope these fixes will make it into Waterfox next release (56.2.4?), one way or the other.

**Comment by grahamperrin** [comment]
Does the comment at `https://github.com/MrAlex94/Waterfox/issues/704#issuecomment-408627632` explain the non-effectiveness of those commits?

**Comment by reikred** [comment]
grahamperrin, that question is above my abilities, I hope Alex knows the answer!

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by reikred** [comment]
No sign of these fixes in 56.2.4 either....

**Comment by reikred** [comment]
No sign of these fixes in 56.2.5  either..

**Comment by reikred** [comment]
@grahamperrin @MrAlex94 is there anything that can be done about this bugfix getting included? It was "almost" fixed at one point but if I understand correctly there was some sort of compile error in linux (32b only had the error ??). It is beyond me to fix this.

The compile error stuff is decribed at https://github.com/MrAlex94/Waterfox/pull/731 , the fix was un-merged again there.

**Comment by MrAlex94** [comment]
I think I struggled to get this to commit cleanly, but I’ll have a look
again for you.

**Comment by reikred** [comment]
@MrAlex94  I think the compile problem has to do with some 8b/16b char string class type-conversion that the compiler cannot figure out. I see in the latest mozilla source that a call to MakeStringSpan() has been added that was not present before. It may be better to try the latest mozilla code for the relevant files. Maybe @bobowen would be able to assist if a problem occurs?

CopyUTF8toUTF16(MakeStringSpan(path), filename);

Hoping you can fix it, it causes misery with the PrintEditWE pdf-saver extension by wrecking the awesome filename-derived-from-URL-and-date-time macro functionality.
