### ISSUE TITLE
application/octet-stream is not supported

### ISSUE THREAD

**Issue by Ark74** [BrowserWorks/waterfox#722]
**Describe the bug**
_Trying to open video stream recognized as "application/octet-stream" fails to play._

**To Reproduce**
1. Go to _any web using this, like web.whatsapp.com_
2. Click on _a video file which is recognized as application/octet-stream_
3. See error

**Expected behavior**
Play video file.

**Screenshots**
![error](https://user-images.githubusercontent.com/7444518/44431821-2c669380-a565-11e8-813a-e8403963aef5.png)

**Desktop (please complete the following information):**
 - OS: Trisquel GNU/Linux
 - Version: 8.0 (*buntu Xenial based)

**Additional context**
Maybe related to:
* https://www.reddit.com/r/waterfox/comments/8oajoe/waterfox_5620_linux_h264_videos_doesnt_play/

**Comment by laniakea64** [comment]
`application/octet-stream` means "binary data of unknown type".  How do you expect Waterfox to know what type of video it is in face of that?

**Comment by Ark74** [comment]
My believe is that it's not using the correct libavcodec library to determine the correct MIME type.
Since Firefox and other derivate browsers like Abrowser, Pale Moon, do recognize the mp4 video files.

Not sure.
