### ISSUE TITLE
menu partially grayed out

### ISSUE THREAD

**Issue by maurerr** [BrowserWorks/waterfox#723]
**Describe the bug**
After leaving the waterfox open for a few days ~3-4) the frame above the menu is grayed out

**To Reproduce**
1. Just leave the Waterfox open for a few days

**Expected behavior**
After leaving the waterfox open for a few days ~3-4) the frame above the menu is grayed out

**Screenshots**
https://ibb.co/kWTqne

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Version:  7601, SP1

**Additional context**
I'm not sure how to get additional debug info

**Comment by grahamperrin** [comment]
> … to get additional debug info

1. about:support
2. Copy text to clipboard

**Comment by maurerr** [comment]
changed windows 7 theme to classic (no glass) and issue was fixed
