### ISSUE TITLE
previewing pdfs broken

### ISSUE THREAD

**Issue by storm37000** [BrowserWorks/waterfox#726]
**Describe the bug**
Cant preview .PDF files, it just downloads them and shows a blank page.  This broke with one of the recent updates.  I don't open PDF that much so im not sure when, but it had to be within the last 2 or 3.

**To Reproduce**
1. Open PDF
2. See blank page and it just downloads instantly.
3. Open the download and it downloads another copy with another blank page.

**Expected behavior**
PDF displays in browser.

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - 56.2.2

**Comment by laniakea64** [comment]
Could you please post the link to a specific PDF you can't view?

**Comment by storm37000** [comment]
it seems to have fixed itself magically, i did delete the one file that resets the program open rules but that didnt immediately fix it, something else did much later on.

the pdf i was trying to open was https://www.lua.org/wshop15/Musa2.pdf

**Comment by sheddup** [comment]
about:preferences#applications  
Make sure PDF is set to 'preview in waterfox'

**Comment by grahamperrin** [comment]
OK @storm37000 you can mark this issue as _closed_, if you like. Thanks for follow-up.
