### ISSUE TITLE
port all the recent patches from palemoon ...

### ISSUE THREAD

**Issue by Ulf3000** [BrowserWorks/waterfox#728]
palemoon has recently switched to uxp(ff52+)   and the devv of palemoon has made quite a few patches to remove telemetry completly from the system ..should also give a small performance boost if that module isnt running on every hover and mousein mouseout of the firefox ui elements 
https://github.com/MoonchildProductions/UXP

it would be nice if you could patch those in and build a version  56.2.3 

thanx for listening

**Comment by grahamperrin** [comment]
I don't know about _all_ … 

… for the patches that are most desirable, I should probably recommend suitably-written pull requests. 

Consider for example: 

- https://github.com/MrAlex94/Waterfox/pull/628#issuecomment-397893509
- https://github.com/MrAlex94/Waterfox/pull/670#issuecomment-398222203
- https://github.com/MrAlex94/Waterfox/pull/677#issuecomment-400027024

**Comment by Ulf3000** [comment]
i meant specifically the removal of the telemetry code in both js and c++ , i didnt even see the other modifications , but thanx for the answer , 

i see youre already connected , will there be a new repo for waterfox "quantum"(lol)?

**Comment by grahamperrin** [comment]
> specifically the removal of the telemetry code in both js and c++

Ah, thanks for clarification. 

----

Repo: I have no idea. It's the type of question that might be answered (eventually) in issue 267 :-)
