### ISSUE TITLE
Full screen shows a top bar

### ISSUE THREAD

**Issue by kenorb** [BrowserWorks/waterfox#73]
Watching videos on full screen, still shows a top bar.

**Comment by MrAlex94** [comment]
Do you get this issue in [Safe Mode](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode)?

**Comment by kenorb** [comment]
No, it was a normal mode. I can re-test and give some more details.

**Comment by MrAlex94** [comment]
Hi @kenorb , any more updates in this regards?

**Comment by kenorb** [comment]
Clicking on ![](https://support.cdn.mozilla.net/media/uploads/gallery/images/2014-01-10-13-08-08-f52b8c.png) (even couple of times) doesn't do anything (doesn't open the menu), so I don't know how to restart in the Safe Mode.

**Comment by MrAlex94** [comment]
@kenorb, can you still reproduce this issue?

**Comment by kenorb** [comment]
Has anything changed since then. Was there any new version to try?

**Comment by MrAlex94** [comment]
Yes, 55. Mozilla has changed a fair bit of the code related to this.

Also may I ask which OS?

**Comment by kenorb** [comment]
I've tested Waterfox 55.1.0.1 (September 2017) and it works fine in the full screen now (_YouTube_ videos). Thanks for the update.
