### ISSUE TITLE
Waterfox for Android Versions... 

### ISSUE THREAD

**Issue by Ibuprophen** [BrowserWorks/waterfox#730]
Hello There! 

I've currently been using the Waterfox Beta v56.1.0 and had recently noticed that there was a Non Beta Waterfox v60.1 as well but, it's not compatible with my Galaxy S5 ARM device. 

Are there any plans and such in creating an updated version of Waterfox that's compatible with my device? 

Thank you very much for your time and understanding with this question! :-) 

~Ibuprophen

**Comment by hawkeye116477** [comment]
Waterfox is for 64-bit CPU's, so probably no.

**Comment by Ibuprophen** [comment]
@hawkeye116477, Please think about the question asked and your answer... 

I believe that @MrAlex94 will hopefully provide an update to the Waterfox Beta v56.1.0. I'm not in a race, I'm just wondering if there's any plans for this in the near future. 

Thank you very much! :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
My OnePlus 2 handset gained an automated update to 60.1.0esr. 

I can't recall the origin of the installation. Neither do I know Android well enough to tell when the update occurred.

**Comment by hawkeye116477** [comment]
@grahamperrin But Snapdragon 810 is 64-bit and Galaxy S5 has Snapdragon 801, which is 32 bit and as I know, Waterfox is rather intended for 64-bit CPU's, at least currently.

**Comment by grahamperrin** [comment]
Ah, thanks, I didn't know about Snapdragon.

**Comment by Ibuprophen** [comment]
I've got the Waterfox Beta on my 32-bit Galaxy S5 from the Google Play Store @grahamperrin. 

If it was only for a 64-bit device, then the Beta version wouldn't be available for my device. 

This is why the comment from @hawkeye116477 didn't make sense to me. 


~Ibuprophen

**Comment by hawkeye116477** [comment]
@ibuprophen1 Probably MrAlex changed that. I have one device with 32-bit CPU and Play Store tells me that it's incompatible with my device. On another device with 64-bit CPU, I can install it. Both devices has Android 7. Also see here => `https://www.apkmirror.com/apk/waterfox-ltd/waterfox-privacy-web-browser-free-and-open/waterfox-privacy-web-browser-free-and-open-60-1-0-release/`, architecture arm64-v8a, for 56 it was armeabi-v7a :smile:.

**Comment by Ibuprophen** [comment]
@hawkeye116477, Please refer to the following Play Store link with a 32-bit device and scroll down to the bottom to enroll in the Beta Testing... 

https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox

... I've attached 2 images that reflect what I see at the top and bottom of the Play Store with my 32-bit device as well. 

[example1](https://user-images.githubusercontent.com/18060271/45591110-85340c80-b916-11e8-889c-3587290dda0b.png)
[example2](https://user-images.githubusercontent.com/18060271/45591112-94b35580-b916-11e8-8f69-e7efb6d3de57.png)

The following APKMirror link reflects this Waterfox Version for the 32-bit (armeabi-v7a) as well. 

https://www.apkmirror.com/apk/waterfox-ltd/waterfox-privacy-web-browser-free-and-open/waterfox-privacy-web-browser-free-and-open-56-1-0-release/waterfox-privacy-web-browser-free-and-open-56-1-0-android-apk-download/ 

In addition... This Beta Version for the 32-bit devices was released on 25-MARCH-2018 (approx 5-6 months ago). 



~Ibuprophen

**Comment by hawkeye116477** [comment]
@ibuprophen1 Yeah, I mean that was changed for version 60. Probably that was planned for stable release to release only 64-bit Waterfox for Android. Also MrAlex asked on reddit if people has 64-bit devices, so something was up => `https://www.reddit.com/r/waterfox/comments/98clf8/waterfox_for_android_has_finally_been_updated_the/e4gll8a/`.

**Comment by Ibuprophen** [comment]
Thank you very much for pointing the Reddit link out @hawkeye116477! :-) 


~Ibuprophen

**Comment by DI555** [comment]
@MrAlex94 , pls keep and all 32bits Waterfox versions too, and especially for Android 5+ !!!
Because so many devices are still on it ;) !

**Comment by DI555** [comment]
@MrAlex94 
And btw, very much waiting GP-free version for Android !
Are any good news there?

**Comment by theel0ja** [comment]
My phone's (a3y17lte) CPU is 64b, but my custom ROM (Lineage) for my phone is only 32b. I'd like to have 32b ARM build for Android.

**Comment by Ibuprophen** [comment]
Anything new regarding this @grahamperrin and @MrAlex94? 

I'm just wondering myself because of the increased amount of Firmware on 64-bit devices being developed as a 32-bit. 

Thank you very much! :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
Nothing that I know of.

**Comment by Ibuprophen** [comment]
I really don't want to be a bother but, I was just curious if there's anything new regarding this issue @grahamperrin and @MrAlex94? 😱

~Ibuprophen

**Comment by LeeBinder** [comment]
[hoping, too](https://github.com/MrAlex94/Waterfox/issues/859#issuecomment-504172854)..

**Comment by LeeBinder** [comment]
Is Waterfox for Android officially dead?

**Comment by Ibuprophen** [comment]
Unfortunately it's discontinued for the ARM 32 bit Android OS (like myself), but It's still going strong for those who has the ARM64 Android OS. 

~Ibuprophen

**Comment by LeeBinder** [comment]
obviously and thus needless to say it's discontinued for *all* archs, just that the compile for arm64-v8a was the latest, added to the Play Store on June 9, 2019 as per the [WayBack Machine archive](https://web.archive.org/web/20190620193005/https://play.google.com/store/apps/details?id=net.waterfox.waterfox).

Because by now even the v.68.0A2 apk is helplessly outdated, there is no official spot where it could be downloaded, but can only be found via a [web search](https://www.google.com/search?q=Waterfox+68.0A2+apk&biw=1200&bih=602&sxsrf=APq-WBuETErNQaKPMYpsPG8a1WWYGIi0bg%3A1649278860323&ei=jP9NYsGjE8aE9u8PtpifyAY&ved=0ahUKEwjBmevEqoD3AhVGgv0HHTbMB2kQ4dUDCA0&uact=5&oq=Waterfox+68.0A2+apk&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgjECc6BwgjELADECdKBAhBGAFKBAhGGABQ_wVYrwhgiwtoAXAAeACAAXCIAd4BkgEDMC4ymAEAoAEByAEBwAEB&sclient=gws-wiz) (48.865.380 Bytes, md5 e4d88a4b0fbc3d74935da4628f8ef6d0).

**Comment by Ibuprophen** [comment]
I still see it (though it's an old version) via the Play Store, but only as long as I remain signed up for the Beta version since it's only seen under the Beta Channel. 

The attached Screenshot was just made by myself a few minutes ago. 

[Waterfox Beta Screenshot](https://user-images.githubusercontent.com/18060271/162090158-7e74c508-a897-4fe6-84be-24545436a93c.jpg)

I only use it as necessary as I'm transitioning to another Android Browser. 

~Ibuprophen

**Comment by LeeBinder** [comment]
Interesting fun fact that the WF v.56 play store page is still accessible for you thanks to your previous enrollment into the beta program - for me it isn't.

I'll try installing my desired legacy add-ons into WF v.68.0A2 soon on my new arm64-v8a cell phone with Android 11.

**Comment by Ibuprophen** [comment]
@LeeBinder, Just go to the following link to sign up for the Beta version... 

https://play.google.com/apps/testing/org.waterfoxproject.waterfox

... then select the "download it on Google Play" link on that next page after you signed up. 

It should still work (at least for now).

~Ibuprophen

**Comment by LeeBinder** [comment]
Sync not working in WF 68.0A2 arm64-v8a

**Comment by tungstengmd** [comment]
> @hawkeye116477, Please refer to the following Play Store link with a 32-bit device and scroll down to the bottom to enroll in the Beta Testing...
> 
> https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox
> 
> ... I've attached 2 images that reflect what I see at the top and bottom of the Play Store with my 32-bit device as well.
> 
> [example1](https://user-images.githubusercontent.com/18060271/45591110-85340c80-b916-11e8-889c-3587290dda0b.png) [example2](https://user-images.githubusercontent.com/18060271/45591112-94b35580-b916-11e8-8f69-e7efb6d3de57.png)
> 
> The following APKMirror link reflects this Waterfox Version for the 32-bit (armeabi-v7a) as well.
> 
> https://www.apkmirror.com/apk/waterfox-ltd/waterfox-privacy-web-browser-free-and-open/waterfox-privacy-web-browser-free-and-open-56-1-0-release/waterfox-privacy-web-browser-free-and-open-56-1-0-android-apk-download/
> 
> In addition... This Beta Version for the 32-bit devices was released on 25-MARCH-2018 (approx 5-6 months ago).
> 
> ~Ibuprophen

I got a waterfox ver that works on A13 on samsung devices
https://drive.google.com/file/d/1BZlDSkO_ISStvE9ZkL1PG9m2JgvwHNMn/view?usp=drivesdk

**Comment by LeeBinder** [comment]
@SpyderThingy sure, that's WF 60.1.0 (2018-08) arm64-v8a, the same as on https://www.apkmirror.com/apk/waterfox-ltd/waterfox-privacy-web-browser-free-and-open/waterfox-privacy-web-browser-free-and-open-60-1-0-release/#downloads

You're advised to also read https://www.reddit.com/r/waterfox/comments/9cut8a/waterfox_6010_for_android_is_fundamentally_broken/ and https://www.reddit.com/r/waterfox/comments/98clf8/waterfox_for_android_has_finally_been_updated_the/

But [v.68.0A2](https://www.google.com/search?q=Waterfox+68.0A2.apk&biw=1200&bih=602&sxsrf=APq-WBve083H6XTcxZgTytvN3L3yrA3hzw%3A1649192694472&ei=9q5MYoOxHIOSxc8P8MWzoAk&ved=0ahUKEwiDhOHF6f32AhUDSfEDHfDiDJQ4ChDh1QMIDQ&uact=5&oq=Waterfox+68.0A2.apk&gs_lcp=Cgdnd3Mtd2l6EAM6BwgjELADECdKBAhBGAFKBAhGGABQ7whY7whglhtoAXAAeACAAWCIAWCSAQExmAEAoAEByAEBwAEB&sclient=gws-wiz) is more recent ([2019-06](https://web.archive.org/web/20190620193005/https://play.google.com/store/apps/details?id=net.waterfox.waterfox)) than v.60.1.0.
