### ISSUE TITLE
profession.hu jobs

### ISSUE THREAD

**Issue by MRJOOOOOO** [BrowserWorks/waterfox#732]
**Describe the bug**
The results of searches are good, but the jobs are not showing up.

**To Reproduce**
1. Go to 'www.profession.hu'
2. Click on 'részletes keresés'
3. Scroll down to 'just choose anything'
4. See error when you click on a job, that is not showing up.

**Expected behavior**
should show up.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] windows 10
 - Version [e.g. 22] 56.2.2 waterfox version. the site works fine with chrome 69.0.3497.92 (Official Build) (64-bit)
![hiba1](https://user-images.githubusercontent.com/43236384/45481450-d512a800-b74b-11e8-820d-2e302f22f8f8.jpg)
![hiba2](https://user-images.githubusercontent.com/43236384/45481464-dba11f80-b74b-11e8-983c-6c16f5d4342e.jpg)
![hiba3](https://user-images.githubusercontent.com/43236384/45481465-dba11f80-b74b-11e8-9274-7b93780fc9a8.jpg)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MRJOOOOOO** [comment]
https://www.profession.hu/allas/muvezeto-pannon-freyssinet-kft-1219183?sessionId=656f84e9979c087aa35a1f047b3c5e2a

that is the url of the page what works on chrome but does not work on waterfox

**Comment by grahamperrin** [comment]
Waterfox 56.2.2 to the left, Chromium to the right: 

![2018-09-14 04 51 55 waterfox](https://user-images.githubusercontent.com/192271/45528830-0a65d700-b7da-11e8-888e-722924282f78.png)

Is the issue visible in either of those Windows?

**Comment by MRJOOOOOO** [comment]
Thank you for the answer, after this email, I realized, the problem was with the adguard adblocker, there is no problem with firefox.cheersZoltan
 

    On Friday, September 14, 2018, 5:53:50 AM GMT+2, Graham Perrin <notifications@github.com> wrote:  
 
 
Waterfox 56.2.2 to the left, Chromium to the right:



Is the issue visible in either of those Windows?

**Comment by grahamperrin** [comment]
> … I realized, the problem was with the adguard adblocker, …

OK, you can mark this issue as _closed_. Thanks for the follow-up.
