### ISSUE TITLE
Style Editor won't load in reddit.com (and probably other websites)

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#734]
**Describe the bug**
The Style Editor tool won't load any style sheet on Reddit.

**To Reproduce**
1. Click F12
2. Click on Style Editor
3. See error (Infinite Loading)

**Expected behavior**
Should load the Style Editor.

**Screenshots**
 ![alt text](https://i.redditmedia.com/bnyOOTiu4ZCppYgTrpA7B4gY-xWDVt3oKn_QLV1IyKI.png?w=568&s=8a1ed5c433ecf0a6526f4a8e45534401)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1803 Build 64-bit
 - Version 56.2.3 (64-bit)

**Additional context**
Works in the latest Firefox client.

**Comment by grahamperrin** [comment]
No problem here with 56.2.3 on FreeBSD-CURRENT. 

Is the issue reproducible with Waterfox in safe mode? 

Reproducible with a new profile?

**Comment by ghost** [comment]
No, it isn't. I think [RES](https://redditenhancementsuite.com/) is making this issue then. My bad.

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/addon/reddit-enhancement-suite/versions/ try 5.12.5 (for  _Firefox 57.0 and later_); I use that version here. 

----

If not a conflict with Reddit Enhancement Suite, then try: 

- [Extension Conflict Troubleshooter : waterfox](https://www.reddit.com/r/waterfox/comments/93x02v/extension_conflict_troubleshooter/)

**Comment by ghost** [comment]
Ah, thank you. I was using Chrome's version. (Thanks to Chrome Store Foxified)

**Comment by grahamperrin** [comment]
Thanks. Resolved? If so you can _close_ this issue.
