### ISSUE TITLE
Twitch chat won't stop when scrolling up.

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#735]
**Describe the bug**
In Twitch, if you scroll up the chat, it should stop, but not in Waterfox. This is a bug.

**To Reproduce**
1. Go to 'twitch.tv'
2. Scroll up the chat.
3. See error.

**Expected behavior**
If you scroll up the chat, it's supposed to stop.

**Desktop**
-   OS: Windows 10 Home 1803 Build 64-bit
-   Version 56.2.3 (64-bit)

**Additional context**
This bug doesn't exist in Firefox.

**Comment by grahamperrin** [comment]
Not reproducible with 56.2.3 on FreeBSD-CURRENT. 

Is the issue reproducible with Waterfox in safe mode? 

Reproducible with a new profile?

**Comment by ghost** [comment]
> Is the issue reproducible with Waterfox in safe mode?

Yes, it is.
