### ISSUE TITLE
Cannot install new addons from Firefox Addons or from file

### ISSUE THREAD

**Issue by tngreene** [BrowserWorks/waterfox#736]
**Describe the bug**
When I try to install any addon from https://addons.mozilla.org, it gets stuck at "Verifying" from the web or "Downloaded." from a file.

**To Reproduce**
1. Go to any addon page such as https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/
2. Click on 'Add to Firefox' or download the .xpi file separately
3. If installing from the Web you'll see the addon install dialog get stuck at "Verifying", if installing from a file you'll see the progress bar stuck at a sliver of green and the label says "Downloaded" on the about:addons page

**Expected behavior**
Addons should be installed.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.16299
 - Version 56.2.3 x64 (portable)

**Additional context**
This happens with new addons and addons that I know I was able to install in the past, including addons that have not been recently updated.

I also tried past versions of addons and they all failed too.

**Comment by grahamperrin** [comment]
> 1. Go to any addon page such as https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng
> 2. Click on 'Add to Firefox' …

Tested with 56.2.3 on Windows 7. Worked fine with two fresh installations of Waterfox, the second of which was portable. 

----

@tngreene whilst I can't guess the problem in your case, I _have_ found similar symptoms on a handful of occasions over the past few months, and probably not only with Waterfox; probably also with Firefox. In most cases, maybe all, it was enough to quit/exit the browser. The next run of the browser was trouble-free. 

If you'd like to be more thorough: please actively check the file systems, including the volume that you used for the portable installation.

**Comment by tngreene** [comment]
After a restart, the problem went away entirely. Restarting your computer to fix a problem? Who ever heard of such a thing...

**Comment by grahamperrin** [comment]
By coincidence, I had something like the same issue yesterday. Worked around by a quit of Waterfox. 

### For reference only

Attempting to manually perform two of eleven updates (no more; for nine of the eleven, I prefer outdated versions): 

![2018-09-19 02 07 31](https://user-images.githubusercontent.com/192271/45794071-c1f06280-bc8c-11e8-9aa3-3ff60f0d142e.png)

![2018-09-19 02 08 47](https://user-images.githubusercontent.com/192271/45794077-c7e64380-bc8c-11e8-9f35-e41fa39b214e.png)

![2018-09-19 02 09 34](https://user-images.githubusercontent.com/192271/45794082-cfa5e800-bc8c-11e8-968c-ae0891907d03.png)

At this point, the visible number dropped from 11 to 9: 

![2018-09-19 02 21 46](https://user-images.githubusercontent.com/192271/45794085-d6345f80-bc8c-11e8-88be-47784f6b535a.png)

Then back up to 11: 

![2018-09-19 02 22 31](https://user-images.githubusercontent.com/192271/45794088-dd5b6d80-bc8c-11e8-85d7-8a7f97a6f497.png)

I wondered whether simply waiting a while would cause the number to drop again from 11 to 9. It did not. 11 was correct; truly, the two updates were downloaded but not installed. 

----

After the quit, both updates installed without difficulty.
