### ISSUE TITLE
A page is broken since 56.2.2

### ISSUE THREAD

**Issue by Keyzmo** [BrowserWorks/waterfox#737]
**Describe the bug**
Since 56.2.2 the page http://www.bom.gov.au/products/IDR713.loop.shtml is somewhat broken:

**To Reproduce**
1. Go to http://www.bom.gov.au/products/IDR713.loop.shtml
2. Open the same page in any other browser, e.g. Chrome
3. Do a visual comparison

**Expected behavior**
Page in Waterfox should look similar to Chrome

**Screenshots**
Problematic fragment of the page:
In Waterfox
![Waterfox](https://user-images.githubusercontent.com/35167899/45691512-2aabe200-bb9c-11e8-9e19-61e684a4eed2.PNG)
In Chrome
![Chrome](https://user-images.githubusercontent.com/35167899/45691511-2a134b80-bb9c-11e8-8e80-a141bc0704a1.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7

**Additional context**
While implementation of the page may not be as cross-browser as it should be, it worked for me in Waterfox for many years prior to 56.2.2 and is still broken in 56.2.3. I look at the page daily and while there's a chance that they deployed an update to the page on the same day as I updated to 56.2.2, it would be too big of a coincidence.

**Comment by MrAlex94** [comment]
Strange, seems to work for me. Maybe you have an add-on affecting it?
Try safe mode
<https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_start-firefox-in-safe-mode>
and see if it works then.

**Comment by Keyzmo** [comment]
Very strange indeed: in safe mode the page rendered properly and when I restarted WF in normal mode intending to go through addons one by one, the page rendered properly without me disabling any addons. Prior to safe mode I tried Ctrl+F5,  deleting cookies and clearing disk cache (with WF shut down) and it didn't help.
Thank you.
