### ISSUE TITLE
Bug 1394207 - When firefox is opened with the sidebar open, the sidebar search box gets/steals focus, not the web page as previously

### ISSUE THREAD

**Issue by TheQuickFox** [BrowserWorks/waterfox#738]
Question: Could you please fix this old Firefox 56 bug? It is already fixed in Firefox 57 but it is still present here:

Bug 1394207 - When firefox is opened with the sidebar open, the sidebar search box gets/steals focus, not the web page as previously

https://support.mozilla.org/questions/1180387
https://bugzilla.mozilla.org/show_bug.cgi?id=1394207

**To Reproduce**
1. Open the Waterfox bookmark sidebar.
2. Close waterfox
3. Reopen waterfox.
4. Type an URL. The default active text field will be the bookmark sidebar search instead of the URL address bar.

**Expected behavior**
Current behavior: Bookmark bar search field gets focus by default.
Wanted behavior: URL address bar gets focus by default

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Waterfox 56.2.3

**Additional context**
See the original Mozilla bug entries linked in the bug report

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by TheQuickFox** [comment]
Still present in 56.2.4

**Comment by TheQuickFox** [comment]
Still present in 56.2.7.1

**Comment by grahamperrin** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1394207#c18 ▶

- https://hg.mozilla.org/mozilla-central/rev/9435660523cb
- https://hg.mozilla.org/mozilla-central/rev/5edfd440c97f

**Comment by TheQuickFox** [comment]
Still present in 56.2.8
