### ISSUE TITLE
Bookmarks glitch out url bar....

### ISSUE THREAD

**Issue by furycd001** [BrowserWorks/waterfox#740]
HI. 

I've come across a possible bug/glitch when adding the bookmarks icon to the url bar. Whenever you click on customize and drag the bookmarks icon to beside the url bar, there is empty space added above & below the url bar area. I'm using waterfox 56.2.3 on Xubuntu 16.04.03 with the default compact dark theme. Please have a look at the two screenshots attached below. The first one shows regular waterfox & the second one shows the glitched out url bar after adding the bookmarks icon. Is there any reason for this empty space being added above & below the url bar ?? If so how can it be removed ?? Many thanks....

## Regular Waterfox

![alt text](http://i.imgur.com/QUr9xir.png "Regular Waterfox")
http://i.imgur.com/QUr9xir.png

## Glitched out url bar

![alt text](http://i.imgur.com/8PRZC6T.png "Glitched out url bar")
http://i.imgur.com/8PRZC6T.png

**Comment by laniakea64** [comment]
I'm not seeing this behavior.  Do you still see it in a new, clean Waterfox profile?

**Comment by grahamperrin** [comment]
Cross-post https://redd.it/9hegbq

**Comment by grahamperrin** [comment]
Reproducible with 56.2.3 on Kubuntu. With the button already in the toolbar:  

1. use the context menu for the button
2. Move to Menu
3. again, use the context menu for the button
4. Move to Toolbar

Workarounds include: 

- open a new window; or 
- quit.

**Comment by laniakea64** [comment]
Thanks @grahamperrin , I can reproduce the issue following those steps.  Looks like this is caused by the bookmarks toolbarbutton getting a `style` attribute that sets an absurdly large height (what height it is exactly seems to depend on the system font size).

Another workaround is to add the following to [userChrome.css](http://kb.mozillazine.org/UserChrome.css) -
```
#nav-bar #bookmarks-menu-button {
  height: unset !important;
}
```

**Comment by grahamperrin** [comment]
> an absurdly large height

Yeah, 

![2018-09-21 03 58 52](https://user-images.githubusercontent.com/192271/45857960-13632500-bd53-11e8-8899-7aaaaf9b159e.png)

(That's just for reference, toying, not seeking a CSS workaround.)

**Comment by furycd001** [comment]
Thank you for all of the comments. I just tried a new profile and the same thing happened. I can confirm though that @grahamperrin your workarounds work. I'm currently reading up on how to create userChrome.css to use that css....
