### ISSUE TITLE
Multiprocessing stopped working in v56.2.3

### ISSUE THREAD

**Issue by ramlaxman** [BrowserWorks/waterfox#741]
**Describe the bug**
Firefox e10 process structure is not working in waterfox v56.2.3.

**To Reproduce**
1. Install waterfox 56.2.3 64 bits version.
2. After launch, only single instance of waterfox is running.
3. As per suggestion from some people even "addons disabled restart", e10 is not working.

**Expected behavior**
Multi-process should immediately start right after launching waterfox.

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 64 bits
 - Version 56.2.3

**Comment by grahamperrin** [comment]
> Windows

Try: 

- [Waterfox disabled multiprocess due to accessibility : waterfox](https://www.reddit.com/r/waterfox/comments/7tupr8/waterfox_disabled_multiprocess_due_to/)

If that was the issue, then https://www.reddit.com/comments/8tfseo/-/e17fkal/?context=1 may be of interest.

**Comment by ramlaxman** [comment]
For me this has worked, [Muitiprocess in Waterfox](https://www.reddit.com/r/waterfox/comments/7tupr8/waterfox_disabled_multiprocess_due_to/). 
Thanks for help.
