### ISSUE TITLE
Slack not working in v56.2.3

### ISSUE THREAD

**Issue by ramlaxman** [BrowserWorks/waterfox#743]
**Describe the bug**
Slack.com giving message "Upgrade the browser".

**To Reproduce**
1. Go to 'slack.com'
2. Log in if slack.com prompts.
3. You will get message of "Browser change" or "upgrade".

**Expected behavior**
Slack.com should open without any problem.

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 x64
 - Version: 56.2.3 64 bits

**Additional context**
You need to downgrade to 56.2.1 for using Slack.

**Comment by grahamperrin** [comment]
> … need to downgrade to 56.2.1 for using Slack.

No need. 

Please see [the Slack answer](https://www.reddit.com/comments/9drjqx/-/e66h85p/) to the recent **User Agent** post.

**Comment by rorya** [comment]
just posting an update on this.. today, 2020-09-29, this user-agent is what is needed to get Waterfox Classic.app (v2020.09) working with Slack

`preference: general.useragent.override.slack.com`
`user-agent: Mozilla/5.0 (rv:62.0) Gecko/20100101 Firefox/62.0 `

Yes, v62, this despite the slack.com documentation claiming Firefox v60+ is required.
