### ISSUE TITLE
Can't select text in Waterfox 60.1.0esr Android

### ISSUE THREAD

**Issue by monkeydragon** [BrowserWorks/waterfox#746]
When I long tap on any text in a page the text background turns to blue. I can't move the select cursor, and there's no dialog with 'cut', 'copy' etc.

Mi Mix 2, MIUI 10

**Comment by grahamperrin** [comment]
Maybe a duplicate of https://github.com/MrAlex94/Waterfox/issues/727

**Comment by MrAlex94** [comment]
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

This should be resolved now, please re-open if now :-)
