### ISSUE TITLE
Date field reformat upon exiting field

### ISSUE THREAD

**Issue by OlyDLG** [BrowserWorks/waterfox#748]
**Describe the bug**
At https://complaint.ic3.gov/default.aspx, a required date field requires the format MM/DD/YYYY, but when I enter in the date in that format, upon exiting the field, it is automatically reformatted to YYYY-MM-DD, which prevents the form from being submitted.  I checked and changed my Waterfox Locale setting to EN-US, restarted Waterfox as instructed, but same result.

**To Reproduce**
1. Go to https://complaint.ic3.gov/default.aspx
2. Under Financial Transaction(s), Select any Transaction Type option to activate the Transaction Date field 
3. In that field, enter a (past or present) date in MM/DD/YYYY format
4. Exit the field
5. Observe that the format has changed to YYYY-MM-DD

**Expected behavior**
The date format not to be changed upon exiting the field

**Screenshots**
![screenshot 2018-09-30 14 26 27](https://user-images.githubusercontent.com/6315019/46262920-20071c00-c4bd-11e8-9ab5-92a418f676a8.jpeg)
![screenshot 2018-09-30 14 13 19](https://user-images.githubusercontent.com/6315019/46262926-2bf2de00-c4bd-11e8-9670-12492bd5b3bc.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version  10.13.6 "High Sierra"
Waterfox version 56.2.3 (64-bit) "Waterfox is up to date"

**Additional context**
  I completed the form with no problem in Chrome.

**Comment by grahamperrin** [comment]
Reproducible with Firefox 62.0.2 without using the keyboard for the _Transaction Date_ field; use the pop-up date selector. 

### Workaround (Firefox)

1. click any other field
2. click the _Transaction Date_ field
3. again, click any other field.

Gut feeling: this is partly an issue with the web site; it ought to be made compatible with Firefox. I see no webmaster contact details at https://complaint.ic3.gov/

**Comment by Lorienna** [comment]
Reproducible on Windows 7.

A workaround solution for Waterfox 56 is to set `dom.forms.datetime` to `false`, though you'll get a plain text input box without the date picker functionality.

However, if you want to use the date picker, set the pref to `false` after picking the date, and re-enable it upon submitting the complaint. :stuck_out_tongue:

**Comment by grahamperrin** [comment]
Not reproducible with Firefox 65.0 on FreeBSD-CURRENT. 

> … enter a (past or present) date in MM/DD/YYYY format …

– entry in that format is not possible. 

If reproducible with a Mozilla-supported Firefox ESR on a Tier-1 platform, someone might like to raise a [Web Compatibility](https://webcompat.com/) issue.

**Comment by Lorienna** [comment]
> entry in that format is not possible

Did my workaround work for you?

**Comment by grahamperrin** [comment]
On this occasion I tested Firefox alone.

**Comment by Lorienna** [comment]
Not sure what you meant by "not possible" if the issue is not reproducible with Firefox 65. :confused:

**Comment by grahamperrin** [comment]
If you have Firefox 65 handy, try it; hopefully you'll see what I mean.

**Comment by Lorienna** [comment]
If it's about the possibility of manually entering the date when `dom.forms.datetime`=`true`, then on Win7 it can be done, for example, if highlighting the `mm` placeholder/value with the pointer or the <kbd>Tab</kbd> key, and then successively typing in the correct numbers for _each_ of the 3 values. Also the <kbd>↑</kbd><kbd>↓</kbd> keys can be used to set/edit the values and <kbd>←</kbd><kbd>→</kbd> - to move between them.

---

#### Here's an alternative workaround for Waterfox that allows to use the date picker (tested on Win7):

1. Fill out the fields and solve the captcha on the page.

1. Move up, right-click inside the date input field and choose `Inspect Element` from the context menu.

1. Within the Inspector click on the date input node (i.e. `<input class="date" ...`).

1. Keep the Inspector open.

1. Back on the webpage double-click on the `Transaction Date` label; observe the date in the condensed `mm/dd/yyyy` format.

1. Move down to the bottom of the page, e.g., with the <kbd>End</kbd> key.

1. Click on the `Submit Complaint` button.

1. Close the Inspector.
