### ISSUE TITLE
Waterfox 60.1.0esr for Android no Sync option

### ISSUE THREAD

**Issue by J0n1k4** [BrowserWorks/waterfox#749]
I manually update my Android apps from time to time.
I have updated Waterfox a few days ago (last time before that a few months before, so I don't know what was the previous version).
Today I discovered that I can't log into some forums that I have saved logins for. Looking into settings, the Privacy / Manage logins shows 0 saved logins (and there should be a few).
Also - in Settings - I found "Sync" option missing. I reinstalled the app - If I try to go to the Sync option from welcome screen - it crashes. After restarting - Settings / Sync is missing.

**To Reproduce**
1. Go to 'Settings'
2. Try to find "Sync" sub-menu.
4. It's missing.

**Expected behavior**
Sync option, and syncing 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi Note 3]
 - OS: [Android 6.0.1]
 - Version [MIUI global 9.6 stable]

**Additional context**
Waterfox 60.1.0esr for Android

**Comment by grahamperrin** [comment]
Cross reference https://www.reddit.com/comments/98clf8/-/e4eybys/ – mid-August acknowledgement of issues affecting sync. 

Meta, tracking: #538

**Comment by benryanau** [comment]
Hmmm

**Comment by grahamperrin** [comment]
Cross reference: 

- [Waterfox crashes when pressing "Get Started" to Sync an account on my Galaxy S9+ : waterfox](https://www.reddit.com/r/waterfox/comments/avw81l/waterfox_crashes_when_pressing_get_started_to/)

**Comment by MrAlex94** [comment]
Fixed in the newest release: https://play.google.com/store/apps/details?id=net.waterfox.waterfox
