### ISSUE TITLE
Waterfox lite version

### ISSUE THREAD

**Issue by ROCKNROLLKID** [BrowserWorks/waterfox#75]
Hello.

I think a nice build for Waterfox is a lite version. This is basically Waterfox, but also remove stuff like feedback submitting built into Firefox, sync, developer tools, WebRTC, and maybe some other unneeded features. This is pretty much for people who want the most lightweight, x64-bit browser on the Firefox engine while still maintaining the speed Waterfox offers.

Thank you in advance.

**Comment by MrAlex94** [comment]
I'll have a think about this, disabling/removing these features most likely won't make any different in performance, but I'll give it a try.

**Comment by hsdwww** [comment]
i really like your waterfox.really wanna say "thank you" for it to u

**Comment by ROCKNROLLKID** [comment]
@MrAlex94 Well, if there is no performance boost, then at least it will make Waterfox a little smaller so it will still be more lightweight then.

**Comment by MrAlex94** [comment]
@ROCKNROLLKID, new builds will start trimming the fat and removing dead weight, so closing this issue 🙂.
