### ISSUE TITLE
Some addons have gotten more broken on mor recent WF56 versions.

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#750]
1. Color That Site's sidebar panel used to work normally with multi-process enabled. Now it's empty. I have to open a non-e10s window to be able to use it.

2. The [updated Location Bar Enhancer](https://github.com/grssam/UIEnhancer/issues/155#issuecomment-267835326) used to work flawlessly. Now the breadcrumbs usually get corrupted. Show other tabs' partial breadcrumbs or get completely empty.

3. #487 sometimes started happening on WF56.x and it still constantly does.

**Comment by grahamperrin** [comment]
### Color That Site!

- https://addons.mozilla.org/addon/color-that-site/
- caa:addon/color-that-site

Maybe it's the issue that was known with 56.0. From [Colour That Site! compatibility with Waterfox : waterfox](https://www.reddit.com/r/waterfox/comments/84fj6e/colour_that_site_compatibility_with_waterfox/): 

>> … described as not working with Waterfox [when 56.0 was released](https://web.archive.org/web/20171203013714/https://www.waterfoxproject.org/blog/waterfox-56.0-release-download). 

----

> … I have to open a non-e10s window to be able to use it.

<strike>Doesn't work for me. </strike> The extension doesn't present itself in the sidebar menu of sidebars, I got the relevant sidebar after clicking the toolbar button. 

The **Go** button does not appear in multi-process mode. I should treat that as consistent with the report of incompatibility at https://addons.mozilla.org/compatibility/reporter/ColourThatSite@einspeiser.de?appver=56.0&works_properly=1 – success, when **not** forcing (or allowing) e10s.

**Comment by grahamperrin** [comment]
> … multi-process enabled. …

### Location Bar Enhancer

- https://addons.mozilla.org/addon/ui-enhancer/
- caa:addon/ui-enhancer

![2018-10-02 01 15 11 add-ons manager](https://user-images.githubusercontent.com/192271/46322419-a6684e80-c5e0-11e8-81b0-ef84c055645f.png)

If you start Waterfox in single-process mode, then is the issue reproducible?

Side note: it seems necessary to restart Waterfox after disabling the extension. More specifically: 

- I observed corruption (visual debris) after disabling the extension _without_ a restart. 

[e10s (multi-process) compatibility reports at addons.mozilla.org (AMO)](https://gist.github.com/grahamperrin/12e03fe3d305901c093cb68bce43fe92)

**Comment by mzso** [comment]
[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. okt. 2. 02:17 CEST](https://github.com/MrAlex94/Waterfox/issues/750#issuecomment-426105318 "2018-10-02T00:17:07Z - Replied by Github Reply Comments"):
> If you start Waterfox in single-process mode, then is the issue reproducible?
> 

I wouldn't know. I'm not interested in single process mode. The point is that it used to work without any noticeable issue in previous WF56.x versions.


[**@grahamperrin**](https://github.com/grahamperrin) commented on [2018. okt. 2. 01:51 CEST](https://github.com/MrAlex94/Waterfox/issues/750#issuecomment-426101006 "2018-10-01T23:51:59Z - Replied by Github Reply Comments"):
> ### Color That Site!
> Maybe it's the issue that was known with 56.0. From [Colour That Site! compatibility with Waterfox : waterfox](https://www.reddit.com/r/waterfox/comments/84fj6e/colour_that_site_compatibility_with_waterfox/):
 
It used to have problems with FF and WF 56, initially. The customizations often failed to be applied. But Waterfox fixed it. Even now it works reliably, except that the sidebar completely broke in multi-process mode.

> The **Go** button does not appear in multi-process mode. I should treat that as consistent with the report of incompatibility at [https://addons.mozilla.org/compatibility/reporter/ColourThatSite@einspeiser.de?appver=56.0&amp;works_properly=1](https://addons.mozilla.org/compatibility/reporter/ColourThatSite@einspeiser.de?appver=56.0&amp;works_properly=1) – success, when **not** forcing (or allowing) e10s.

What "go" button are you talking about?
