### ISSUE TITLE
Bookmark buttons' drop-down menus fail on Mojave

### ISSUE THREAD

**Issue by jrobert-gh** [BrowserWorks/waterfox#752]
**Describe the bug**
The bookmarks (star) button and folders on the bookmark work once each per new browser window. When one of these buttons has been used and its drop-down has appeared (and been dismissed) once, subsequent clicks on that button show the "button depressed" icon but no drop-down appears.

**To Reproduce**
1. Have bookmark button on the main bar and folders of bookmarks on the bookmarks bar
2. New launch or new window
3. Click on any one of the buttons named in 1. See its dropdown menu activate. Dismiss the menu.
4. Repeat 3. for another of the buttons. Again, see its dropdown menu activate. Dismiss the menu.
5. Click on either of the buttons from steps 3. or 4. again. This time the dropdown does not activate.

**Expected behavior**
Clicking the bookmark button or a bookmark folder on the bookmark toolbar should work the same way every time: its drop-down menu should appear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14 Mojave
 - Version of Waterfox: 56.2.3 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I also tested with a new download/install of Waterfox and a new profile. I added the bookmark button and a bookmark toolbar with one folder containing one bookmark. I got the same result: each drop-down would activate once.

**Comment by grahamperrin** [comment]
If it helps, Mojave-related commits include: 

- https://github.com/MrAlex94/Waterfox/commit/451da41000df9eac3f8939e0d0c834ed0fda27ec
- https://github.com/MrAlex94/Waterfox/commit/2a36b2fb0d4748bca257b9994c49ebdc84de6e4a

**Comment by grahamperrin** [comment]
@jrobert-gh after the update to 56.2.7.1 becomes available to you, please retest. Is the issue reproducible?

**Comment by jrobert-gh** [comment]
Not reproducible in 56.2.6 or 56.2.7.1. I'll consider it closed. Thanks!

**Comment by grahamperrin** [comment]
Thanks for follow up, you can make the closure :-)

**Comment by jrobert-gh** [comment]
Thanks - I didn't notice the button (duh! ): Closing...
