### ISSUE TITLE
Search plugins

### ISSUE THREAD

**Issue by ilu33** [BrowserWorks/waterfox#754]
I can't install any search plugins from Mozillas site anymore - not on FF ESR 52.9 and FF 56 ("Your firefox version doesn't support search plugins") and not on Waterfox ("only for Firefox"). There seems to be no manual installation option anymore. Did they change the search plugin format too? Do I have to spoof the headers? Or will the classic addon archive solve the problem? Any other solution?

**Comment by grahamperrin** [comment]
Not reproducible here with Waterfox 56.2.3. 

Can you let us have the address of an affected add-on? Thanks.

**Comment by ilu33** [comment]
I've updated to 56.2.3 and it works now for Waterfox. Thank you.
