### ISSUE TITLE
Android support is faltering...?

### ISSUE THREAD

**Issue by R-OLE** [BrowserWorks/waterfox#757]
This is a report of multiple known issues creating havoc with Android support...

Problem 1:
Had issue#727. Tried to "fix" it by clearing data, then uninstalling and reinstalling v60.1.0.esr from Play store again.
Didn't fix anything.
Then found it was a known issues. Left comment on issue 727.

Problem 2:
Could not install add-ons, as Mozilla purged their site of old style add-ons a few days ago.

Attempt to remedy:
Found issue threads, and  then GitHub CA-Archive xpi.
But could not install, despite toggling requirement for signature in about:config...
Opened issue on JustOff's CA-A site.
Response was: Android not supported.

Really?
I've been using Waterford for a couple years now, both for 64b desktop, then for mobile since last fall 

Who is going to go from having signed ad & malware blocking add-ons on a movie browser, to choosing to use one that no longer has any add-ons at all. That is what is get if I moved from Waterfox to Chrome/Chromium.
And if I moved to Firefox, I'd at least have uBlock-origin back! I'd have what other things I'd have list, and other issues with Mozilla's chouces., but I'd have a syncing, extendable browser on both platforms.

How anyone can expect to have no text-selection/copy/paste, nor any add-ons ether, is beyond me.
Even creating this post was a chore!

But I'm very concerned when patterns like this pop up from KNOWN issues.

A quick patch to 60.1.1  is likely all that's needed for the text issue. But in a month nothing is forthcoming.

And the add-on issue was foreseen long in advance, and I can fully understand and support last minute issues that might crop up, but solutions for Android were  either apparently not discussed, or deemed not important enough to get a solution in place before existing support structure collapsed.

There re is even discussion here about not supporting 64b OSes, including Android. Given that only a miniscule percent of Android device out there are 64b, and even many of those don't run the 64b version, this would seem like a Horrible idea! Considering the overwhelming popularity of Android, I can't imagine willingly slashing away such a market!

With more web traffic shifting every day to mobile, treating mobile browsers as third class citizens of a browser's eco-system is going to hurt your projects - badly!

Please note that I'm not posting this to badger anyone, and I wouldn't have taken the (way too much) time to write this if I didn't care. But I do care, and want to bring some attention to this multi-faceted, aggregate issue.

**Comment by grahamperrin** [comment]
> … JustOff's CA-A site.
> Response was: Android not supported.
> 
> Really?

https://www.reddit.com/comments/965yk6/-/e7htkqx/?context=1

**Comment by MrAlex94** [comment]
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

The newest version is now based off of the same branch as v68, so updates are much easier now 👍
