### ISSUE TITLE
Tabs don't fully close

### ISSUE THREAD

**Issue by Painketsu** [BrowserWorks/waterfox#758]
First off I always have a lot of tabs open 60-70+ so the bug might be related to that since on occasions I've seen other odd behavior when past 100 tabs.

**Problem**
This bug seems really easy to overlook but it's pretty obvious when you use many YouTube tabs, when closing one of them, sometimes, it wont "close" even though you don't see it on the bar, and the videos will keep playing on the background until you close the browser, it's happened to me many times by now.

I haven't managed to reproduce this reliably, truly seems to be random, maybe occurs when closing the tab during some internal processes are running?

**Screenshots**
Can't really provide a screenshot since the tab remains "hidden", only noticeable when looking at youtube history or if the video happens to have audio on when you close it, you will keep hearing it.

**Desktop**
 - OS: Win 8.1
 - Version Pro

**Comment by grahamperrin** [comment]
Reproducible with Waterfox in safe mode?

I worked with more than a thousand tabs in the past, with more than a hundred extensions, I don't recall anything like this issue.

**Comment by laniakea64** [comment]
> when closing one of them, sometimes, it wont "close" even though you don't see it on the bar, and the videos will keep playing on the background until you close the browser,

After you closed the tab, how long have you waited for the video to stop playing before you figure it won't and try to close the browser?

**Comment by Painketsu** [comment]
> 
> 
> Reproducible with Waterfox in safe mode?
> 
> I worked with more than a thousand tabs in the past, with more than a hundred extensions, I don't recall anything like this issue.

I can't find a way to reproduce it, it happens like once every 1-2 weeks while I'm not doing anything out of the norm.

**Comment by Painketsu** [comment]
> 
> 
> > when closing one of them, sometimes, it wont "close" even though you don't see it on the bar, and the videos will keep playing on the background until you close the browser,
> 
> After you closed the tab, how long have you waited for the video to stop playing before you figure it won't and try to close the browser?

It doesn't stop, I've noticed a few times on my youtube history that 20-30 videos have been played in the background without me having the tab open, once I restart the browser it stops.

**Comment by Squall-Leonhart** [comment]
what youtube modification extensions are you using?

**Comment by Painketsu** [comment]
> 
> 
> what youtube modification extensions are you using?

Now that you mention that, I have one called Simple Youtube MP3 Button ver 1.2.1

I'll test for a while with it disabled and see if that's the problem.

**Comment by Painketsu** [comment]
It still happens with no youtube extensions

**Comment by grahamperrin** [comment]
Is the file system (NTFS) OK? 

Also, troubleshooting information please. Use the **Copy text to clipboard** button at: 

- about:support
