### ISSUE TITLE
Add setting to enable/disable FLAG_SECURE on android

### ISSUE THREAD

**Issue by Carbuncleo** [BrowserWorks/waterfox#759]
I recently got a new Samsung Galaxy phone and promptly replaced Chrome with Waterfox as the default browser on it. Later on I was browsing ebay and wanted to take a screenshot of an item I found, only to be greeted with a popup saying "Cant take screenshot due to security policy".

Googling about this until I found out that the most probably cause was because Waterfox presumably enables the FLAG_SECURE setting to heighten privacy and security for the app. Fair enough, fully agree that this is a great thing to do, but personally, I screenshot a lot of things on the web and this just means not being able to do it at all in Waterfox I'm just going to have to reinstall Chrome, or some other browser that will allow me to screenshot the window. I believe Chrome implements the flag too but only on private browsing tabs.

Would be great to see the ability to toggle the use of the flag in the prefs. Either in the settings or as just a string in about:config.

**Comment by grahamperrin** [comment]
https://trac.torproject.org/projects/tor/query – maybe worth raising a ticket in the Tor area.

**Comment by Carbuncleo** [comment]
So was this one of the features pinched for the Tor variant of Firefox then? Figures. I read an article about that when I was looking for solutions.

**Comment by Carbuncleo** [comment]
OK so I did that but I'd still like to see perhaps the devs for waterfox implement the feature directly, bypassing the middle man so to speak. It'd probably wind up making it into Waterfox sooner rather than later then rather than having to wait for god knows how long for the feature to trickle down, this assuming Tor even entertain the idea of implementing it.
