### ISSUE TITLE
WF 49.0.1 Won't Work Again With 10.8.5

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#76]
We were just closing my question about the incompatibility of WF 48.0.2 with 10.8.5. You made some simple change, at my request, which made them both compatible again. When launching WF 48.0.2, I got the message to update to 49.0.2. After agreeing, the update installation took place. Then after trying to launch WW 49.0.2, the browser crashed, then kept on crashing. Then after installing 49.0.1 over 49.0.2 I got the message that I was using 10.8.5 but 49.0.1 requires 10.9 + above. I kept the installer for 48.0.2, then after installing it over 49.0.1 I was back in business again. Is there anyway you can accomplish this fix again so I can continue to use WF? If not I will continue using WF 48.0.2 because it is my best browsing experience. Thanks again, Ken.

**Comment by 70599** [comment]
10.11.6
Same issue.
Crashs when start up the browser 49.0.2.

**Comment by ghost** [comment]
I hope that Mr. Alex can make the same fix as he was able to for WF 48.0.2.

**Comment by MrAlex94** [comment]
Yes so seems Waterfox only works on Sierra for some reason, and I'm not sure how to test on older OS X versions so I'm a bit stuck as to what to do.

**Comment by ghost** [comment]
Mr. Alex, you said that the fix for Mac OSX Mountain Lion so I could use WF 48.0.2 was very simple. I think something about a Plist change. Been working perfectly. Thanks, Ken.

**Comment by MrAlex94** [comment]
Could anyone try the build attached and see if it runs?

[Download](https://storage-waterfox.netdna-ssl.com/releases/tests/Waterfox.app.zip)

**Comment by ghost** [comment]
Just gave it a try Mr. Alex, telling me that I have to use 10.9 + above, won't work on 10.8.5. But at least it's not crashing. Ken

**Comment by MrAlex94** [comment]
Awesome. So hopefully this will run on 10.8: https://storage-waterfox.netdna-ssl.com/releases/osx64/installer/Waterfox%2049.0.2.1%20Setup.dmg

**Comment by ghost** [comment]
Mr. Alex, WF 49.0.2.1 is working perfectly. I installed it over 48.0.1, all my settings, bookmarks etc. are in place. This fix is probably the template for future updates. Thank you so much, why not support legacy Mac OS versions, it increases your market exposure for WF. Ken.

**Comment by 70599** [comment]
WF 49.0.2.1@OS X 10.11.6 worked.

**Comment by ghost** [comment]
All is well again in the internet universe. WF again takes it's place as the premiere web browser. Great to know that I won't have to give up WF for another inferior alternative. Thanks again, Alex. Ken.
