### ISSUE TITLE
Save image isn't working

### ISSUE THREAD

**Issue by Carbuncleo** [BrowserWorks/waterfox#760]
**Describe the bug**
When you touch and hold over an image and select save image from the popup menu, nothing happens. When yo do this the first time Waterfox does ask for permission to access storage etc. but even if you allow it, nothing happens.

**To Reproduce**
1. Go to any page with an image on it. For example http://www.google.co.uk/
2. Touch and hold on the image, ie Google's logo.
3. Select "Save image" from the popup.
4. Allow permissions if required.
5. The image is not saved.

**Expected behavior**
Obviously the image should be saved to the device and appear in the appropriate photo/gallery app.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8+
 - OS: Android 8.0 "Oreo"
 - Version: 60.1.0esr

**Additional context**
This happens with a clean install of Waterfox, with no add-ons or changes to the settings. I've tried uninstalling, reinstalling, clearing cache etc. but nothing makes a difference. Just to make sure it wasn't some system-wide setting I'd changed I opened Google Chrome and tried to save an image and that worked with flying colours so the problem is apparently specific to Waterfox.

**Comment by grahamperrin** [comment]
Reproducible with ESR 60.1.0 on Android 6.0.1 on a OnePlus 2 handset. No prompt for permissions, and the image is not saved. 

Meta/tracking: #538

**Comment by MrAlex94** [comment]
Should be fixed: https://play.google.com/store/apps/details?id=net.waterfox.waterfox
