### ISSUE TITLE
Can't add webmail application

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#762]
My webmail application doesn't show in the list and when I visit the site nothing prompts me to add it. 
I use Windows 8.1 and the address is "poczta.wp.pl".
In Firefox it's automatically added and showed in options.
Is there a way to add it manually or something?

**Comment by grahamperrin** [comment]
> the list 

Please, which list?

Can you provide a screenshot?

**Comment by maxoku** [comment]
![eng](https://user-images.githubusercontent.com/17256400/46920189-d9501080-cfea-11e8-8f76-9e32eddb70c5.jpg)

**Comment by grahamperrin** [comment]
Thanks. Please go to this address: 

- about:config?filter=network.protocol-handler.external.mailto

Is `network.protocol-handler.external.mailto` set to `true`?

### A comparison

In Firefox 62.0.3: 

- https://mail.tutanota.com/ redirects to https://mail.tutanota.com/login then there appears the banner, inviting the user to add the application for mailto links
- http://poczta.wp.pl/ redirects to https://profil.wp.pl/login.html?zaloguj=poczta then nothing happens.

**Comment by maxoku** [comment]
> Is network.protocol-handler.external.mailto set to true?

Yes it's set to true by default.

> In Firefox 62.0.3

The last version of Firefox I've used was 52esr on the old computer. Somehow the application had to appeared there. Maybe the Polish version could handle this or something. 
I confirmed that in Polish version of newest Firefox the application is presented on the list. 
Maybe there is there a way to import my webmail application list from Fx52esr to Waterfox or something?

**Comment by grahamperrin** [comment]
> … in Polish version of newest Firefox the application is presented on the list. …

OK, use the menu in the _Action_ column to view application details for _mailto_. 

What exactly is the address of the web application?

**Comment by maxoku** [comment]
> What exactly is the address of the web application?

http://poczta.wp.pl/napisz.html?url=%25s

**Comment by grahamperrin** [comment]
Thanks. For me, it doesn't trigger the web application routine in Firefox (or Waterfox). 

Are you signed in to the service? 

Have you sought advice from the service provider?

**Comment by maxoku** [comment]
> Thanks. For me, it doesn't trigger the web application routine in Firefox (or Waterfox).

I suspect that only Polish version can detect it.

> Are you signed in to the service?

Yes, I regularly use it

> Have you sought advice from the service provider?

Would that have any sense? It works in the Polish version after all. I doubt they would do anything. They rarely answer even if I have a serious problem.

Is there any way to add it manually or import from Fx?

**Comment by laniakea64** [comment]
> Is there any way to ... import from Fx?

Try this -

1) Completely quit both Firefox and Waterfox

2) Locate both your Firefox profile and Waterfox profile

3) Copy `handlers.json` and `mimeTypes.rdf` from your Firefox profile to your Waterfox profile.
If your Firefox profile has only `mimeTypes.rdf`, you may also need to do the following:
  a) remove `handlers.json` from your Waterfox profile (**don't** delete it, it's safer to move it somewhere outside your profile folders until you're sure things are working)
  b) open your Waterfox profile `prefs.js` with a text editor and delete this line if present
```
user_pref("gecko.handlerService.migrated", true);
```

4) Restart Waterfox

Does it work?

**Comment by maxoku** [comment]
@laniakea64 
Fx have only `mimeTypes.rdf` and Waterfox only `handlers.json`. Is it still possible to do it with your instruction to import `mimeTypes.rdf`, remove `handlers.json` and edit `prefs.js`? Would it still work?
Besides I don't know if I want to import all my applications and file types from old version.

**Comment by laniakea64** [comment]
Yes it should still work.

If you are at all unsure about doing this, it wouldn't hurt to first completely quit Waterfox and back up your entire Waterfox profile folder.

**Comment by maxoku** [comment]
It didn't work. It seems to not read anything from mimeTypes.rdf and it's reconstructing handlers.json file. 
The only effect was that it was set to default application instead of 'always ask' option.

**Comment by laniakea64** [comment]
Thanks for testing.

So I downloaded the Polish version of Firefox 52.9.0 ESR for comparison, and noticed these two prefs in about:config set by default -
```
gecko.handlerService.schemes.mailto.2.name;Poczta WP
gecko.handlerService.schemes.mailto.2.uriTemplate;http://poczta.wp.pl/napisz.html?url=%s
```

I tried the following in Waterfox, and it got Poczta WP listed in handlers for `mailto:` -

1) go to Waterfox `about:config`
right-click > New > String
name: `gecko.handlerService.schemes.mailto.4.name`
value: `Poczta WP`
right-click > New > String
name: `gecko.handlerService.schemes.mailto.4.uriTemplate`
value: `http://poczta.wp.pl/napisz.html?url=%s`

2) completely quit Waterfox, remove `handlers.json` from the Waterfox profile

3) restart Waterfox

**Note:**
 - I did this in a disposable test environment.  **This procedure as written will erase your other helper applications and helper application settings.**  I'm not sure how to preserve them, sorry.
 - I don't have an account with this service, so I did not test whether the resulting helper application actually works in Waterfox.

**Comment by Lorienna** [comment]
There's another way:

1. Copy the `mimeTypes.rdf` file to the Waterfox profile folder.
2. Go to `about:config` in Waterfox.
3. Right-click and `Reset` the `gecko.handlerService.migrated` pref.
4. Restart Watefox.

**Comment by maxoku** [comment]
@laniakea64 
It did appeared in the list, but it doesn't work properly. It doesn't send the e-mail address for some reason and it's only opens the site. Very strange.

>  This procedure as written will erase your other helper applications and helper application settings.

I don't have any. It's strange, but it seems that Waterfox just doesn't add anything like Firefox.

**Comment by grahamperrin** [comment]
> I suspect that only Polish version can detect it.

Not detected with Polish Firefox ESR 52.9.0: 

![screen shot 2018-10-18 at 01 09 29](https://user-images.githubusercontent.com/192271/47123870-86d55500-d273-11e8-88d0-6794da60a2b3.png)

Is it necessary to log in for detection to occur?

Not detected with Polish Firefox ESR 60.2.2: 

![screen shot 2018-10-18 at 01 27 23](https://user-images.githubusercontent.com/192271/47124543-5e9b2580-d276-11e8-8ad2-ff924efce47a.png)

**Comment by maxoku** [comment]
@grahamperrin 
Cuz it's probably automatically added to the list. Check the list.

> Is it necessary to log in for detection to occur?

I don't know, it was always in the list.

**Comment by grahamperrin** [comment]
> … probably automatically added …

OK, I found some service providers that I never added so I guess that they were predefined by Mozilla. 

After removing all providers, nothing happened at http://poczta.wp.pl/napisz.html?url=%25s – neither a prompt to add, nor automated addition. 

Back to https://github.com/MrAlex94/Waterfox/issues/762#issuecomment-429650184 for the service provider given there, there _is_ a prompt to add.

**Comment by maxoku** [comment]
@grahamperrin 

> Back to #762 (comment) for the service provider given there, there is a prompt to add.

I doubt it will do anything. More importantly why it doesn't work while adding to the list with @laniakea64 method, but it works in Firefox?

**Comment by grahamperrin** [comment]
> it works in Firefox?

Pre-defined by Mozilla, it seems, with the Polish-specific distribution of Firefox: 

- [427273 - WP.pl mailto handler for Firefox 3+ for Polish (pl)](https://bugzilla.mozilla.org/show_bug.cgi?id=427273)

>>  Component: pl / Polish

**Comment by maxoku** [comment]
@grahamperrin 

> 427273 - WP.pl mailto handler for Firefox 3+ for Polish (pl)

I've read that they released a patch to enable correct processing of mailto protocol in [this link](http://www.whatwg.org/specs/web-apps/current-work/#custom-handlers).
I couldn't find much there especially while Waterfox started freezing and lagging a lot.
Could you read that and provide me with solution how to fix that?

**Comment by grahamperrin** [comment]
@laniakea64 re: your https://github.com/MrAlex94/Waterfox/issues/762#issuecomment-430424434 now I sort of get it, but I don't get the relationship between the content of `handlers.json` and the preferences at 

about:config?filter=gecko.handlerService.schemes.mailto.

Experimentally I edited this into the `.json` file, whilst Waterfox was not running: 

`,{"name":"Poczta WP","uriTemplate":"http://poczta.wp.pl/napisz.html?url=%s"}`

Result: 

![2018-10-20 18 10 11 preferences](https://user-images.githubusercontent.com/192271/47258463-1bfe6680-d48b-11e8-81a3-5e058cc36d11.png)

– but even after selecting Poczta WP, things at about:config appear no different from how they appeared earlier: 

![2018-10-20 17 46 49 about config](https://user-images.githubusercontent.com/192271/47258470-39cbcb80-d48b-11e8-9fd2-53a7294779d0.png)

### Postscript

Edition of `handlers.json` had the desired effect. Tested at https://mailto.now.sh/

**Comment by maxoku** [comment]
@grahamperrin 

> `{"name":"Poczta WP","uriTemplate":"http://poczta.wp.pl/napisz.html?url=%s"}`

I've already have it in `handlers.json`. Am I suppose to delete it and add it again this way?

Edit: I've made it and it did appeared on the list, but it still doesn't work. Seems like Waterfox lacks that patch mentioned in that [bugzilla threat](https://bugzilla.mozilla.org/show_bug.cgi?id=427273).

**Comment by grahamperrin** [comment]
> … Seems like Waterfox lacks that patch …

Works for me now, without patching. Works as in, `mailto:` links take me to the WP login page.

**Comment by laniakea64** [comment]
> I don't get the relationship between the content of `handlers.json` and the preferences at
> 
> about:config?filter=gecko.handlerService.schemes.mailto.

I don't fully understand this either, sorry.  I would suspect the prefs are only used to pre-fill `handlers.json`.

Searching for the string `handlerService.schemes` suggests the related code is in https://github.com/MrAlex94/Waterfox/blob/master/uriloader/exthandler/nsHandlerService-json.js

**Comment by maxoku** [comment]
@grahamperrin 

> Works for me now, without patching. Works as in, `mailto:` links take me to the WP login page.

That's the problem it works rather only as a link to the mail service than to send the mail address to it. It takes to login page then I can log in and there's nothing, only being logged and check my messages. If I'm already logged in then it opens a new mail page but it doesn't feel any fields like mail address. It also opens it in the same tab. In Fx it opened a new tab/window for it. Something doesn't work here properly.

PS: If there's no answer I guess that you don't have any idea why it doesn't work. Thanks anyway.
Does any `mailto:` works at all in Waterfox?
And should I make a new thread that it doesn't work or continue this to receive help?

**Comment by grahamperrin** [comment]
> Does any mailto: works at all in Waterfox?

Yes. 

> And should I make a new thread …

Whilst this issue is open, no. (Spreading an issue across multiple areas makes things harder to track.)

**Comment by maxoku** [comment]
@grahamperrin 
So is that the only that service doesn't work or I have a problem and `mailto:` doesn't work for me. I don't have a gmail or yahoo to check it out.

> Whilst this issue is open, no. (Spreading an issue across multiple areas makes things harder to track.)

Thanks. I hope someone will help me.

PS: Maybe I should change the title?

**Comment by maxoku** [comment]
I wish it could be done :/
