### ISSUE TITLE
Cannot Installing on CentOS7/SL7/

### ISSUE THREAD

**Issue by linuxium88** [BrowserWorks/waterfox#765]
**Describe the bug**
May be IT is not a Bug but Something is Missed
**Expected behavior**
I Downloaded  waterfox-56.2.2.en-US.linux-x86_64.tar.bz2. After Completion of Extraction and Navigate the waterfox file to run on Centos7 but cannot Runs
**Screenshots**
![waterfox](https://user-images.githubusercontent.com/8630354/46972863-36c48a00-d0dd-11e8-9f8f-de34b7336a60.png)

**Desktop (please complete the following information):**
 - OS: CentOS & Scientific Linux 
 - Version 7.5

**Comment by hawkeye116477** [comment]
Yeah, apparently CentOS doesn't have Glibc 2.18, but it was released on 2013. So I recommend to switch to more up to date distro.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/205#issuecomment-366253989

#707

**Comment by linuxium88** [comment]
Okay

**Comment by hawkeye116477** [comment]
Unofficial package for CentOS 7 is now on `https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-kde`.
