### ISSUE TITLE
e10s: content process (multi-process) after switching Waterfox to single-process mode

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#766]
Observed with Waterfox 56.2.3 on FreeBSD-CURRENT, with a preference for session restoration. 

I preferred single-process mode and accepted the invitation to restart, then with htop(1) I noticed that there were two `waterfox` processes, one of which was a child. 

I double-checked – quit then re-ran htop, and I reviewed and reloaded the about:support page for the single instance of Waterfox: 

- whilst about:support _suggested_ that multi-process was disabled, truly there was a separate content process.

**Comment by Squall-Leonhart** [comment]
there will always be a gpu process

**Comment by grahamperrin** [comment]
### Frames from a screen recording

Multi-process mode. PID 6058, with a higher PID for the content process. Accepting the invitation to restart to switch to single-process mode: 

![2018-10-16 21 50 50 frame](https://user-images.githubusercontent.com/192271/47599896-e1775b00-d9af-11e8-93d2-2b67466f20ee.png)

Restarted. Single PID 6058: 

![2018-10-16 21 51 08 frame](https://user-images.githubusercontent.com/192271/47599898-eb995980-d9af-11e8-87d1-5b97ba077c10.png)

Detection of the second process (there should be no such process): 

![2018-10-16 21 51 13 frame](https://user-images.githubusercontent.com/192271/47599903-f2c06780-d9af-11e8-8a77-cb4507822fe7.png)

about:support statement that multiprocess windows are disabled, with contradictory evidence from ps(1): 

![2018-10-16 21 52 25 frame](https://user-images.githubusercontent.com/192271/47599905-fb18a280-d9af-11e8-863a-d6e44df24829.png)

**Comment by grahamperrin** [comment]
> there will always be a gpu process

Which platform(s)?

**Comment by grahamperrin** [comment]
I saw this so rarely, I wonder whether to treat it as a quirk of measurement in (or affecting) `htop`. 

However …

**Comment by grahamperrin** [comment]
> a quirk of measurement in (or affecting) `htop`.

I almost certainly saw that in the past. For now I'll: 

1. close this issue
2. raise another for an e10s peculiarity that's reproducible on Linux.
