### ISSUE TITLE
Firefox branding still shown in Waterfox

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#769]
Not sure if this is intentional or not but there's still a tiny bit of Firefox branding in Waterfox.

![image](https://user-images.githubusercontent.com/14107316/47418105-5f015800-d771-11e8-9924-96501a1856c2.png)

**Comment by MrAlex94** [comment]
That's correct though, because it is a Firefox account you'd be connecting
with.

**Comment by laniakea64** [comment]
I think they are referring to the text "Download Firefox for Android".  That link points to Waterfox for Android.

**Comment by Ibuprophen** [comment]
Exactly... The sync function for Waterfox is the same for Firefox on the PC & Android alike. I use it on both myself. 


~Ibuprophen

**Comment by ghost** [comment]
@MrAlex94  And what of the "Download Firefox for Android" part?

**Comment by Ibuprophen** [comment]
Though ,Waterfox does use the Firefox Sync, maybe @MrAlex94 would be able to reword the text a touch and change the URL towards the appropriate Waterfox location.

**Comment by grahamperrin** [comment]
[Miscellaneous links that need to be changed in Waterfox. · Issue #548 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/548)

**Comment by Ibuprophen** [comment]
Thank you for pointing this out @grahamperrin! :-) 

It looks like it's a verbiage/wording confusion between the two that innocently throws an individual off a bit (like the two ways the word "Tomato" is pronounced). 

This has definitely been noted... :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
I guess, there's a partial fix somewhere in the FreeBSD repo for Waterfox. Partial because the change to Waterfox seems to be too broad: 

![2018-10-25 03 46 47 preferences](https://user-images.githubusercontent.com/192271/47473129-42b0fa00-d809-11e8-8177-342b50fc86e2.png)

– it **is** a Firefox account (must not be misrepresented as a Waterfox Account). 

Strictly speaking, in lieu of: 

> Download Waterfox for (Android logo) [Android](https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox&utm_source=waterfox-browser&utm_medium=waterfox-browser&utm_campaign=sync-preferences) to synchronise with your mobile device.

– it should probably be: 
    
> Download [Waterfox for Android](https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox&utm_source=waterfox-browser&utm_medium=waterfox-browser&utm_campaign=sync-preferences) (Android logo) to synchronise with your mobile device.
