### ISSUE TITLE
Firefox is dropping support for XP/Vista

### ISSUE THREAD

**Issue by ROCKNROLLKID** [BrowserWorks/waterfox#77]
Hello.

I don't know if you are aware fo this, but Firefox is dropping support for XP and Vista in Firefox 53, which isn't too far away now. Firefox 52 will move to ESR once 53 is released. Will you at least use the ESR branch for XP/Vista users for Waterfox?

Alternatively, I assume if Firefox is dropping these 2 systems, then it means maybe not a lot of people are on XP/Vista anymore and thus maybe Waterfox could just consider dropping XP/Vista, too.

More information here: http://news.softpedia.com/news/firefox-53-will-drop-support-for-windows-xp-and-windows-vista-508688.shtml

**Comment by MrAlex94** [comment]
Too many new API calls to revert them all to support Vista/XP. So closing this.

**Comment by JeanPaulLucien** [comment]
> Too many new API calls to revert them all to support Vista/XP. So closing this.

I suppose it was possible task for 5000+ contributors and 5 years. How many to revert? Less than 5000? If so it's easy.

There are people who knows Windows XP inside and resolved many issues. Unfortunately I don't know Waterfox inside well, so somebody other should have a talk with them. They found many solutions to 2021 year.

Oh, you can check my repository about Windows XP and use my repository to publish any issue with Waterfox + Windows XP. In success we will get a responce.
