### ISSUE TITLE
Word wrap on text files doesn't work

### ISSUE THREAD

**Issue by RikisX** [BrowserWorks/waterfox#770]
**Describe the bug**
Automatic word wrap doesn't work on plain text files. View->Page Style->Wrap Long Lines does nothing.

**To Reproduce**
Example for testing: 
https://pastebin.com/raw/pyNW8ZkM

**Expected behavior**
Firefox 56:
![clipboard01](https://user-images.githubusercontent.com/5813374/47452837-d2d44c80-d7d3-11e8-9d52-0a602fe755d1.jpg)

**What I get**
Waterfox 56.2.3-56.2.4 new profile: 
![clipboard04](https://user-images.githubusercontent.com/5813374/47452894-f5666580-d7d3-11e8-9846-d3a0099b651f.jpg)

**Desktop:**
 - OS: Windows 7 x64, Windows 10 x64

**Additional Information**
Word wrap on Firefox 56 only works for ANSI and UTF-8, if file is in UTF-16 it doesn't work. (Tested on local files)

**Comment by laniakea64** [comment]
I also see this bug.  This message in Browser Console seems related -
```
Security Error: Content at https://pastebin.com/raw/pyNW8ZkM may not load or link to resource://gre-resources/plaintext.css.
```

**Comment by RikisX** [comment]
Looks like it's this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1395486

**Comment by grahamperrin** [comment]
> …
> Example for testing:
> <https://pastebin.com/raw/pyNW8ZkM>
> … 
>  Waterfox 56.2.3-56.2.4 new profile:
> …
> - OS: Windows 7 x64, Windows 10 x64
> …

Not bugged for me with 56.2.3 on FreeBSD: 

![2018-10-25 03 00 04 untitled window](https://user-images.githubusercontent.com/192271/47471531-966c1500-d802-11e8-9f58-0f8316c033d9.png)

Also not bugged with a different profile in safe mode.

**Comment by laniakea64** [comment]
@grahamperrin That's because FreeBSD build already includes the patch: https://svnweb.freebsd.org/ports/head/www/waterfox/files/patch-bug1395486?revision=466694&view=markup&pathrev=480899

**Comment by grahamperrin** [comment]
Hurrah so that's one step closer to a PR. G'wan, anybody, g'wan …
