### ISSUE TITLE
Updater updated from 56.2.1 to 56.2.3 - doesn't recognize 56.2.4 as existing

### ISSUE THREAD

**Issue by StinVec** [BrowserWorks/waterfox#771]
Waterfox manually updated normally via "About Waterfox" updater from 56.2.1 to 56.2.3, though 56.2.4 has been available since October 9th - Waterfox still shows as being "up to date" despite newer version being available.

I must manually download the 56.2.4 install file in order to update past 56.2.3.

There seems to be an issue with the 56.2.4 update where it is not being recognized as existing by the updater and it only updated me to 56.2.3 - what it thinks is the latest version.

Windows 7 64-bit

_____
I am on Windows 7 64-bit and was at v56.2.1. I have auto-update disabled currently. I had not manually updated for some time and decided to check the "Toolbar > Help > About Waterfox" to quickly see what the latest version was and view the release notes to see what has changed. It showed the 56.2.3 update as being available. After reviewing the notes I updated via the "About Waterfox" window. This was last night, October 25th in the AM.

The problem is, I encountered an issue of websites not loading for me due to Waterfox now being an "unsupported" browser version due to the user agent being changed from being Firefox. I opened up the "Issues" list here to see if others had encountered the issue or if it was being looked at to offer an option to choose what browser Waterfox reports as being so I can view all of my websites again. There was no sign of this being reported yet (and it is still an issue - can't even log into my web email account to check email now). However, I did see someone mention Waterfox v56.2.4 and I became confused as the updater updated me to 56.2.3 barely a few hours ago.

I was amazed to see that 56.2.4 was released on October 9th, so why did the "About Waterfox" updater only update me to 56.2.3? I again opened "About Waterfox" and checked for an update from 56.2.3 to this 56.2.4 but it still shows me that "Waterfox is up to date", despite my being version 56.2.3 and a newer update has been available since the 9th. And even the direct installer download from https://www.waterfoxproject.org is of v56.2.4. So why did my Waterfox only update to 56.2.3 from 56.2.1 and why is it not seeing that the 56.2.4 update exists?

So the issue is:
- Waterfox reporting that it is up to date, but a newer version is actually available. It only partially updated my browser and refuses to see 56.2.4 as existing to update to.

**Comment by grahamperrin** [comment]
> … 56.2.4 has been available since October 9th … Windows …

More accurately, since 2018-10-22. 

For 56.2.4, the roll-out of automated updates is explicitly slow. With added emphasis: 

>> "Waterfox 56.2.4 is now out for all platforms, and automatic updates on **slow** roll-out! 👨‍💻⏬"

– https://redd.it/9qioz3 – and please note the stuck comment.

**Comment by pirate486743186** [comment]
The problem is not with you.

read this
https://www.reddit.com/r/waterfox/comments/9qioz3/waterfox_5624_is_now_out_for_all_platforms_and/

He got a security certificate late. He need that to sign the application. I don't understand why it's on slow role out though

Just install it manually. It might complain that it's unsigned or invalid, don't get alarmed. I'm just a linux user, i don't know how things are supposed to work on windows.

**Comment by StinVec** [comment]
> More accurately, since 2018-10-22.

Ah, thank you for that correction. I was going off of the release notes page for that version where it states:
> Written by Alex Kontos
> October 9th, 2018

> For 56.2.4, the roll-out of automated updates is explicitly slow. With added emphasis:
> 
> > > "Waterfox 56.2.4 is now out for all platforms, and automatic updates on **slow** roll-out! man_technologistarrow_double_down"
> 
> – https://redd.it/9qioz3 – and please note the stuck comment.

Thank you for this link to the Waterfox subreddit and noting where information on this issue had been relayed. I do not take part in any social media so it had not occurred to me to search for important information about Waterfox releases on any of them - I primarily rely on the information included in the official release notes and read reported bugs posted here. I'll look there in the future for important information about Waterfox.

Thank you again.
