### ISSUE TITLE
User Agent change to being "Waterfox" breaking websites

### ISSUE THREAD

**Issue by StinVec** [BrowserWorks/waterfox#772]
The recent change to Waterfox where it now reports as being "Waterfox" instead of "Firefox" is causing several websites I frequent (including web email) to no longer function as the browser is now an "unsupported" browser. I need to downgrade back to 56.2.1 or try to get myself to use "Firefox" just to be able to check my web email.

Please offer an option in the "Options" screen to manually change the user agent reporting back to what it was previously ("Firefox") instead of reporting as "Waterfox", or, if possible, configure the "Waterfox" user agent reporting to be accepted by sites that do not recognize Waterfox as being a "supported" browser.

Windows 7 64-bit
Waterfox 56.2.3

**Comment by ghost** [comment]
You already can change it. It's a bit scarier then a nice menu though.

In the url bar, type "about:config" and enter
a scary page will appear.
in the search box of the page,
copy paste  "general.useragent.override"
You modify that, with a string that works.

**Comment by StinVec** [comment]
> 
> 
> You already can change it. It's a bit scarier then a nice menu though.
> 
> In the url bar, type "about:config" and enter
> a scary page will appear.
> in the search box of the page,
> copy paste "general.useragent.override"
> You modify that, with a string that works.

Thank you for this information. I am glad to know that it is able to be manually altered to undo this change. I will attempt to revert it to the previous user agent string. Hopefully my change will not be overwritten every time I update Waterfox. If it will be, this being an option in the GUI (whose setting persists across updates) would still be something I would personally desire.

Thank you again.

**Comment by ghost** [comment]
Normally, it will just be the default, nothing to revert. Try this, without the quotes, as an override:
"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"

In the future you'll eventually need to update it manually.

**Comment by grahamperrin** [comment]
https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/e66gcir/ ▶ **User Agent Overrider**

There are other extensions, but that's the one that I use for `general.useragent.override`. 

Elsewhere in that **User agent** post you have examples of service-specific strings. 

----

NB **62.0 is outdated**. 63.0 is current.

**Comment by grahamperrin** [comment]
> … Please offer an option …

Extensions serve this purpose. 

> if possible, configure the "Waterfox" user agent reporting to be accepted by sites that do not recognize Waterfox as being a "supported" browser.

It'll be useful to get a string working in the context of https://github.com/browser-update/browser-update/issues/416#issuecomment-426947276 

**Postscript**: resolved.

**Comment by Telmesomething** [comment]
Seeing image shown in the screenhsot when I login to Github (_courtesy of Microsoft I guess_). 

Also had to install User Agent Overrider grahamperrin recommended to even post the screenshot (thanks for the tip graham). 

![github_error](https://user-images.githubusercontent.com/33827636/48220363-59ba2500-e38f-11e8-96db-de21cd244582.PNG)

**Comment by rdebath** [comment]
I've tried [User-Agent Switcher](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/) from that same thread. It also works nicely to recover the hating on Waterfox that MS seem to have injected. Interestingly, the user agent does NOT have to be one of those mentioned, `Wget` works nicely.

**Comment by grahamperrin** [comment]
Spun off from <https://www.reddit.com/r/waterfox/comments/aeu9iu/-/edticf9/>

> … may have to revert back to a generic UA …

FWIW this non-generic string, which includes `Waterfox`, is also good for <https://chemguide.co.uk/>:

- `Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2 Waterfox/56.2`

Taken from https://github.com/MrAlex94/Waterfox/issues/178#issuecomment-407642688 but NB I haven't tested the string with other sites recently.

**Comment by grahamperrin** [comment]
> Waterfox 56.2.3

@StinVec please test recently released 56.2.7.1. With the new style UA string (without overrides). 

Better for you? 

Feedback re: YouTube might be particularly helpful. 

Please advise – thanks. 

### Related

[User Agent: waterfox](https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/) ▶ [Waterfox 56.2.7.1 default UA strings](https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/efmyx9t/)

[YouTube not rendering pages correctly : waterfox](https://www.reddit.com/r/waterfox/comments/amsugb/youtube_not_rendering_pages_correctly/)

**Comment by grahamperrin** [comment]
@StinVec please, have you tested?

### Retrospective (56.2.3)

https://github.com/MrAlex94/Waterfox/commit/8e978a6df522a2e12ab3080d691fec490db01a56#diff-a633a6dfcf161bf7cb9d3d9cdcdc2faeR439 

For what it's worth, that approach (`Waterfox` somewhere in parentheses) seemed to **not** allow recognition of the version of <strike>Waterfox </strike>the browser in some situations. 

WhatIsMyBrowser.com, for example: 

- https://developers.whatismybrowser.com/useragents/explore/software_name/waterfox/?order_by=software_version
- https://developers.whatismybrowser.com/useragents/explore/software_name/waterfox/?order_by=-software_version (reverse sort)

**Comment by grahamperrin** [comment]
@MrAlex94 close this now, I reckon.

**Comment by gallonmate** [comment]
I think I'm having the useragent issue with version 2019.10 for https://answers.unrealengine.com

**Comment by grahamperrin** [comment]
@gallonmate thanks, an override has been requested. Discussion: 

- https://www.reddit.com/comments/d79h2l/-/f6c2y84/

**Comment by Megalomaniak** [comment]
Use a spoofer such as `User Agent Switcher`. Waterfox should not lie about what it is. And thank god it is not firefox. Blam that piece of-
