### ISSUE TITLE
[pull request] copy the newer emoji fonts from firefox

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#773]
Firefox has newer emoji fonts. I think, just copying the font file over, and updating the license will do.

Also, not to forget to update them from time to time. The current file is probably unchanged for more then a year....

**Comment by ghost** [comment]
What needs to be done:

replace 
/usr/lib/waterfox/fonts/EmojiOneMozilla.ttf
by
/usr/lib/firefox/fonts/TwemojiMozilla.ttf

no need to change the name. The name of the file is not hard coded. I tested it, the new fonts are used.

also, in about:license
delete about:license#emojione
copy over about:license#twemoji
from firefox

**Comment by ghost** [comment]
I did a pull request
https://github.com/MrAlex94/Waterfox/pull/781

**Comment by hook321** [comment]
I think we should take into consideration the fact that the pistol emoji is incorrect in twemoji.
