### ISSUE TITLE
Browser navigates on its own to the first link on certain pages

### ISSUE THREAD

**Issue by morags** [BrowserWorks/waterfox#776]
**Describe the bug**
Sometimes the browser navigates on its own to the first link search results of a Google search. The same query ran in another tab in parallel usually functions as expected.

The same happens consistently on Youtube pages viewed through the [Update Scanner](https://addons.mozilla.org/he/firefox/addon/update-scanner/) addon (`chrome://updatescan/content/diffPage.xul`), and randomly (and more rarely) on other pages as well.

**To Reproduce**
1. Search some arbitrary string on Google through the Google homepage or the "awesome bar".
2. Google displays a list of search results
3. Before the page finishes loading, the browser navigates to the first result on the page
4. Repeating the above in a new tab (usually) does not replicate the behavior

**Expected behavior**
Page finishes loading with no further actions

**Desktop:**
 - OS: Windows 10
 - Version: Latest build, and several older ones

**Additional context**
* Tried toggling addons off (without restarting) - same result
* Console shows the occasional "uncaught exception" and "unexpected error", but nothing definitive
* AFAICT this did not happen under Firefox with the same user profile

**Comment by grahamperrin** [comment]
> … addons off (without restarting) …

For troubleshooting, that's not enough. Please visit: 

- about:support

– and use safe mode. Is the issue reproducible?

**Comment by morags** [comment]
That's a bit of a problems, as the problem is intermittent, so it will take some time to reproduce (or not). Any  logs that I can check? Instrumentation?

**Comment by morags** [comment]
I'm sorry, I've just replicated the problem on FF 56.0.2. I still don't know what's causing it, but I'll look it up elsewhere. You can mark the issues as "closed".

Thanks!

**Comment by grahamperrin** [comment]
Thanks, 

> You can mark the issues as "closed".

I (personally) can not, but you can `:-)`
