### ISSUE TITLE
Question: will the future waterfox keep australis?

### ISSUE THREAD

**Issue by davidbepo** [BrowserWorks/waterfox#779]
this question might have been asked before but i was unable to find a clear answer

the main reason because im using waterfox is because it uses australis UI which IMO is better en every aspect compared to photon

the question is if future versions of waterfox will keep using australis or at least if it will be an option even if not default

**Comment by ghost** [comment]
I'm just a user, i think the UI will be fossilized in for years, a bit like seamonkey, because they aren't enough resources. If it is dropped, it will be because the dev decided that it wasn't viable to maintain the old code base.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/775#issuecomment-434575988

**Comment by ghost** [comment]
I don't think that necessarily means that he will dump australis....

**Comment by grahamperrin** [comment]
@davidbepo are you happy enough with the appearance of Waterfox Current? 

The integral themes; compatibility with [Firefox Color](https://addons.mozilla.org/addon/firefox-color/); customisability e.g. <https://www.reddit.com/r/firefoxcss/>; and so on. 

If you're reasonably happy, I suggest closing this issue; there can be discussions in Reddit. 

Thanks 👍

**Comment by davidbepo** [comment]
i will test it, but i want to say that there is much more to australis than the rounded tabs, the navigation bar layout changes, the menu is different, new tab page is also different
IMO all of those are better in australis

**Comment by davidbepo** [comment]
okay just tested waterfox current and
new tab page is in photon format, cant use the old better australis one
![Captura de pantalla de 2020-03-07 22-15-54](https://user-images.githubusercontent.com/18667173/76152596-8c7a4780-60c1-11ea-9d2d-f0067f3120c6.png)
i can either use a custom theme or rounded tabs but not both
![Captura de pantalla de 2020-03-07 22-16-12](https://user-images.githubusercontent.com/18667173/76152618-be8ba980-60c1-11ea-8418-394ebc4d44b2.png)
and the "hamburger" menu is also photon, without a way to change to australis
so even tough waterfox current has some of the australis stuff most of it is lost, as long as waterfox classic keeps being maintened this is not a big issue, but if it isn't i will really like to be able to keep using australis since that is the reason why i changed to waterfox in the first place
