### ISSUE TITLE
unsupported browser issue

### ISSUE THREAD

**Issue by diomed** [BrowserWorks/waterfox#78]
if you go to any [discord channel](http://www.discordlist.com):

And click on UNMUTE or UNDEAFEN 
it throws out error - UNSUPPORTED BROWSER

Can something be done about it from your side?

**Comment by Serkan-devel** [comment]
This issue still persists on Waterfox 55.2.2, debian 9, lxqt.

**Comment by MrAlex94** [comment]
Oh sorry, need to add useragent override for Linux too. In about:config you can add a string general.useragent.override.discord.com and an appropriate [user agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox)

**Comment by Serkan-devel** [comment]
Will a patch come with it?
