### ISSUE TITLE
Linux Mint 18.3 (Based on Ubuntu 16.04) Waterfox Won't Update.

### ISSUE THREAD

**Issue by LinuxUserNewbieForever** [BrowserWorks/waterfox#782]
It wouldn't update properly from 56.2.4 (64-bit) to 56.2.5 (64-bit) on Linux Mint 18.3 XFCE. 

Using ppa deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/ /

term.log
Log started: 2018-11-02  23:10:12
Selecting previously unselected package ubuntu-advantage-tools.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 450001 files and directories currently installed.)
Preparing to unpack .../ubuntu-advantage-tools_10ubuntu0.16.04.1_all.deb ...
Unpacking ubuntu-advantage-tools (10ubuntu0.16.04.1) ...
Preparing to unpack .../ubuntu-minimal_1.361.2_amd64.deb ...
Unpacking ubuntu-minimal (1.361.2) over (1.361.1) ...
Preparing to unpack .../python3-update-manager_1%3a16.04.15_all.deb ...
Unpacking python3-update-manager (1:16.04.15) over (1:16.04.14) ...
Preparing to unpack .../update-manager-core_1%3a16.04.15_all.deb ...
Unpacking update-manager-core (1:16.04.15) over (1:16.04.14) ...
Preparing to unpack .../libsoundtouch1_1.9.2-2+deb9u1build0.16.04.1_amd64.deb ...
Unpacking libsoundtouch1:amd64 (1.9.2-2+deb9u1build0.16.04.1) over (1.9.2-2) ...
Preparing to unpack .../waterfox_56.2.5-0_amd64.deb ...
Unpacking waterfox (56.2.5-0) over (56.2.4.2) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 changed doc-base file...
Registering documents with scrollkeeper...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
Setting up ubuntu-advantage-tools (10ubuntu0.16.04.1) ...
Setting up ubuntu-minimal (1.361.2) ...
Setting up python3-update-manager (1:16.04.15) ...
Setting up update-manager-core (1:16.04.15) ...
Setting up libsoundtouch1:amd64 (1.9.2-2+deb9u1build0.16.04.1) ...
Setting up waterfox (56.2.5-0) ...
dpkg: error processing package waterfox (--configure):
 subprocess installed post-installation script returned error exit status 10
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 waterfox
Log ended: 2018-11-02  23:10:17

**Comment by grahamperrin** [comment]
> ppa

@hawkeye116477 ^

**Comment by hawkeye116477** [comment]
@LinuxUserNewbieForever Sorry for errors, but anyway that should be fixed in 56.2.5.1 :smile:.

**Comment by ghost** [comment]
Actually, it did update, you can use it just fine. You can ignore that error, it's not important and alredy fixed for next version.

**Comment by LinuxUserNewbieForever** [comment]
I confirm that the issue is fixed.  However @hawkeye116477 Where is the new commands for installing the new PPA?  I spent a lot of time with google.com and startpage.com and I can't find any.

**Comment by ghost** [comment]
I haven't tested them, but these should work.

```
echo 'deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/ /' | sudo tee /etc/apt/sources.list.d/home:hawkeye116477:waterfox.list

curl https://build.opensuse.org/projects/home:hawkeye116477:waterfox/public_key | sudo apt-key add -
```

**Comment by LinuxUserNewbieForever** [comment]
@pirate486743186 I tested the commands on Linux Mint 18.3 XFCE in Virtualbox.  I confirm it works.

**Comment by ghost** [comment]
lol, virtualbox? i wasn't sure they were no errors. Not that they might be malicious. XD

**Comment by hawkeye116477** [comment]
@LinuxUserNewbieForever 
![screenshot_20181105_101023](https://user-images.githubusercontent.com/19818572/47988683-2fdcd600-e0e3-11e8-86e0-a2f9ab487ea7.png)

All commands are here => `https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox` :smile:

PS: VMware Player is better.

**Comment by LinuxUserNewbieForever** [comment]
@hawkeye116477 Ok that link seems to be what I needed.  

In my opinion that is not the best way to show someone information.  The user can't just glance at the website and figure out where He needs to go.  I had to use some concentration, and trial and error to find them.  The first time I clicked on the ubuntu icon nothing happened.  Then I tried the debian icon and then something happened.  Then I tried the ubuntu icon again and then I got the link I needed.

I don't currently have a clean install that I can test the commands on.  But here is the commands I will be trying, when I get one setup.

**For xUbuntu 16.04 run the following:**

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/home:hawkeye116477:waterfox.list"
sudo apt-get update
sudo apt-get install waterfox

**You can add the repository key to apt. Keep in mind that the owner of the key may distribute updates, packages and repositories that your system will trust (more information). To add the key, run:**

wget -nv https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/xUbuntu_16.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update

**Comment by hawkeye116477** [comment]
That links for instructions are now also on readme on my GH repo.

**Comment by grahamperrin** [comment]
▶ https://github.com/hawkeye116477/waterfox-deb#readme

**Comment by LinuxUserNewbieForever** [comment]
@hawkeye116477 Those set of commands for xUbuntu 16.04 seems to be working for Linux Mint 18.3 XFCE in VirtualBox.  (It installed)

I did this:
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/home:hawkeye116477:waterfox.list"
sudo apt-get update

wget -nv https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/xUbuntu_16.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update

sudo apt install waterfox

**Comment by ghost** [comment]
mint 18 is actually a mod of ubuntu 16.04
