### ISSUE TITLE
Github stopped working in Waterfox due to "outdated version of Firefox"

### ISSUE THREAD

**Issue by vearutop** [BrowserWorks/waterfox#785]
Recently Github started to show me "Please note that Github no longer supports old versions of Firefox." and many buttons stopped working (for example preview in comment).

I tried to fake my user agent to latest versions of Firefox and Chrome, but that didn't help.

Is it possible to make Github work again in Waterfox (even through some dirty hackery)?

I like Waterfox very much and I hate the idea of migrating to Chrome/FF, I'd rather migrate from Github to Gitlab. :D

**Comment by hawkeye116477** [comment]
For me it works correctly, but I have Linux, maybe this doesn't happen on Linux.

**Comment by vearutop** [comment]
I have problems on macOS.

**Comment by vearutop** [comment]
Oh, seems I messed up with changing user agent, now I've set `general.useragent.override` to `Firefox/59` in `about:config` and it all fixed.

Thanks.

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/pull/784

**Comment by vanowm** [comment]
Please re-open this issue, as it's not 100% working: we no longer can preview issue messages or edit them.

**Comment by grahamperrin** [comment]
@vanowm what override did you apply?

**Comment by vanowm** [comment]
```Mozilla/5.0 (Windows NT 10.0; Win64; rv:57.0) Gecko/20100101 Firefox/57.0```
and
```Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0```

I don't think it's related to user-agent string, there is an error shown in browser console:
```TypeError: window.customElements is undefined[Learn More]  frameworks-ffc171466564e0794f5ca22623586452.js:1:85866```

P.S.
it seem none-of the issue message form tools are working, can't change font, type of text, etc.

**Comment by grahamperrin** [comment]
Try the short string for 60.

**Comment by grahamperrin** [comment]
Try the short string for 60.

**Comment by don-reba** [comment]
This started for me again today. Tried different user agents—Firefox 64, Chrome, etc—nothing seems to help.

**Comment by grahamperrin** [comment]
> Try the short string for 60.

Do not. See https://github.com/MrAlex94/Waterfox/pull/784#issuecomment-439939670
