### ISSUE TITLE
Open Link in silent tab broken

### ISSUE THREAD

**Issue by Squall-Leonhart** [BrowserWorks/waterfox#788]
Can't be sure when this broke, but clicking the relevant context menu item on a link prints "Error: CPOW usage forbidden in this add-on in the browser console"

**Comment by Ibuprophen** [comment]
Wow! I haven't seen a Cross Process error in a while... 

The following link may be helpful for the CPOW errors. 

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiprocess_Firefox/Cross_Process_Object_Wrappers


It looks like an add-on may broken by some type of multiprocess compatibility... 


~Ibuprophen

**Comment by Squall-Leonhart** [comment]
E10S compatibility was added in 0.2.5

**Comment by Squall-Leonhart** [comment]
Also it was working in Firefox 56, and Waterfox 56.0

**Comment by grahamperrin** [comment]
> … was working in Firefox 56, and Waterfox 56.0

Works for me with Waterfox 56.2.5 on FreeBSD-CURRENT. The tab opens as expected and (unless I'm missing something) I don't see anything CPOW-related in the browser console. 

Can you share troubleshooting information? Plain text please from about:support

### Links

For readers who may be unfamiliar with the extension: 

- caa:addon/open-link-in-silent-tab
- https://addons.mozilla.org/addon/open-link-in-silent-tab/

**Comment by Squall-Leonhart** [comment]
do you have e10s enabled?

**Comment by Squall-Leonhart** [comment]
Your profile is forced to single process when this addon is enabled.

mines set to override.

**Comment by Squall-Leonhart** [comment]
hmm, i seem to have fixed it.

reinstalled the extension straight over the top of the existing on.

**Comment by grahamperrin** [comment]
Thanks. 

> E10S compatibility was added in 0.2.5

If issues recur, please test with Waterfox in single-process mode. 

[Open Link in Silent Tab Compatibility Reports :: Add-ons for Firefox](https://web.archive.org/web/20180414141154/https://addons.mozilla.org/en-GB/firefox/compatibility/reporter/%7Bd4c46ca0-999d-11da-a72b-0800200c9a66%7D)

> … was working in … Waterfox 56.0

56.0 took a more careful approach. 56.2.5 defaults to allowing multi-process with extensions that are not compatible with multi-process.
