### ISSUE TITLE
 Please note that GitHub no longer supports old versions of Firefox.  We recommend upgrading to the latest Safari, Google Chrome, or Firefox.

### ISSUE THREAD

**Issue by Tsoccerguy3** [BrowserWorks/waterfox#789]
Please note that GitHub no longer supports old versions of Firefox.
We recommend upgrading to the latest Safari, Google Chrome, or Firefox.
WaterFox 56.2.5 (64-bit} is not 100 percent compliant with GitHub

Can not select Branch or upload pictures

**Comment by Tsoccerguy3** [comment]
GitHub is not supporting Waterfox . I could not even edit my first comment

**Comment by hook321** [comment]
See this pull request, discussion has been happening there: https://github.com/MrAlex94/Waterfox/pull/784

**Comment by IzzySoft** [comment]
As a funny sidemark: my second browser I use from time to time to cross-check things is Qupzilla, which wasn't updated for ages (I don't remember any update ever). And you get no warning when using that. Smells like deliberate action. And my first thought (right or not) was: ah, the first effects from the MS overtake …

It *is* quite deliberate, as all it needs to make it work again is changing the UserAgent string. So it's not that the site *cannot* work but that they don't want it to. 😠

**Comment by grahamperrin** [comment]
What's your UA of Qupzilla? 

What's a UA of Fallon, and how does GitHub respond?

**Comment by Tsoccerguy3** [comment]
I downloaded one of the User Agent addons , set it to Edge on windows .
Amazing MS Edge setting does work , Microsoft , if your reading this , I'm still not using Edge Browser

**Comment by IzzySoft** [comment]
> What's your UA of Qupzilla?

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1

So it should basically appear as an outdated Safari. I get no warning with that. Though I must admit I didn't test what features might be blocked (didn't log in with it to start with). Page doesn't render correctly – and as the OP noted, I cannot switch branches with it. First thought the warning is only shown when logged in – but then, thinking of broken cache/cookies I had a.o. deleted all cookies in Waterfox (which must effectively have logged me out), and promply got the warning. Maybe the warning just got lost in rendering :rofl: But as the page source doesn't contain it either, I doubt that.

> What's a UA of Fallon, and how does GitHub respond?

What is Fallon?

Btw: the UA override (making it "60.0" instead of "56.2") works perfectly, all features are available again (as far as I've tested). Even with Firefox 55 (which I'm currently using; this machine will be migrated to Waterfox next week).

**Comment by mikeloeven** [comment]
Fyi still getting issues with github edit / preview buttons are not working.

**Comment by mikeloeven** [comment]
Cant even edit my own post ^^

**Comment by IzzySoft** [comment]
@mikeloeven sure you correctly implemented the work-around (as the code change most likely hasn't yet been published)?

1. go to `about:config`
1. type "useragent" into the search mask to see what entries exists. You should see one for AMO.
1. create a new property, type "string", name "general.useragent.override.github.com", and paste the one from AMO over. Only change the version numbers (2 places: `rv:57.0` and `Firefox/57.0`) to "60".

Done. Reload the Github page(s), and all should work fine. It does here. Including preview and edit.

**Comment by grahamperrin** [comment]
> What is Fallon?

Sorry, that was a typo on my mobile phone. 

### Falkon

https://userbase.kde.org/Falkon

On FreeBSD, for 3.0.0: 

`Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.0.0 Chrome/56.0.2924.122 Safari/537.36`

**Comment by grahamperrin** [comment]
> … Qupzilla… should basically appear as an outdated Safari. …

QupZilla is outdated, but I should not expect GitHub's alert to be comprehensive. The note focuses on the three supported browsers. 

#### Side note

Re: https://github.com/github/site-policy/issues/15#issuecomment-438073022 the _Supported Browsers_ document is no longer a _Site Policy_.

**Comment by IzzySoft** [comment]
Falkon is not available on my machine. Maybe after the next distupgrade. And yes, that have been my thoughts as well: there might be browsers missing from their list. Which makes it even more stupid to go by the UA if it's possible to check feature compatibility another way …

But nevermind: Qupzilla doesn't even render the page correctly – but the UA trick does it fine for me in Waterfox. I can absolutely live with that :smile:

**Comment by grahamperrin** [comment]
> … one of the User Agent addons , set it to Edge …

Misrepresenting Waterfox as Edge may be troublesome in some domains. 

about:config?filter=general.useragent.override

@Tsoccerguy3 is there a preference for `general.useragent.override.github.com` (not to be confused with `general.useragent.override`) and if so, what's it's value?

**Comment by grahamperrin** [comment]
> Falkon is not available …

Which Linux distro?

**Comment by IzzySoft** [comment]
Linux Mint 18.3 currently. Based on Ubuntu 16.04 and supported at least for another year (LTS), hence I didn't yet upgrade to Mint 19 (too many possible side effects in my setup :wink:)

**Comment by grahamperrin** [comment]
Thanks, 

> Linux Mint 18.3 …

I see eight editions of 18.3. Which one?

**Comment by mikeloeven** [comment]
I am surprised changing the user agent fixes the buttons. Is github intentionally sabotaging the page or is it that edge doesn't support the features the site is trying to use so it falls back to an older script?

**Comment by grahamperrin** [comment]
> … Is github intentionally sabotaging the page …

No.

**Comment by Scrxtchy** [comment]
> Is github intentionally sabotaging the page

Debatable
![image](https://user-images.githubusercontent.com/12771982/48472644-cb401a80-e84a-11e8-9148-9a081ca793f5.png)

Github will only send you a single javascript file for unsupported. Which is different to the one that supported browsers get
![image](https://user-images.githubusercontent.com/12771982/48472761-122e1000-e84b-11e8-8997-6459f7dcc5d0.png)

**Comment by IzzySoft** [comment]
@grahamperrin 

> I see eight editions of 18.3. Which one?

Cinnamon. But that shouldn't make a difference on what's available in the repos :wink:

**Comment by Ibuprophen** [comment]
I'm speechless.

Welcome to the new world of Github courtesy of Microsoft... LMAO! 


~Ibuprophen

**Comment by IzzySoft** [comment]
@ibuprophen1 my thoughts (see the 4th comment here) :rofl:

**Comment by TheQuickFox** [comment]
GMX.net (German e-mail provider) also stopped support for this browser. Of course, the fault is with these websites and not this browser but it is a bit annoying for the users of Waterfox.

**Comment by Ibuprophen** [comment]
Regarding the Waterfox Android Mobile App, so far I had found that the following manual input within the about:config seems to be working (it's only been a few days and I haven't seen the top message bar return yet). 

Interger:
String

Name:
general.useragent.override

String:
Mozilla/5.0 (Android 7.0; Mobile; rv:54.0) Gecko/62.0 Firefox/62.0

I just wanted to provide my input to, hopefully help out. 


~Ibuprophen

**Comment by grahamperrin** [comment]
GitHub now whitelists Waterfox based on the contents of its UA. 

@Tsoccerguy3 would you like to close this issue?

**Comment by Tsoccerguy3** [comment]
> > … one of the User Agent addons , set it to Edge …
> 
> Misrepresenting Waterfox as Edge may be troublesome in some domains.
> 
> about:config?filter=general.useragent.override
> 
> @Tsoccerguy3 is there a preference for `general.useragent.override.github.com` (not to be confused with `general.useragent.override`) and if so, what's it's value?

Here is the plugin I'm using on Waterfox , It has its uses . easy to turn it on and off
https://addons.mozilla.org/en-CA/firefox/addon/user-agent-switcher-revived/?src=search

**Comment by Scrxtchy** [comment]
@Tsoccerguy3 can we close the issue?
Anything else would be covered in #790, as github is no longer a problem right now

**Comment by ghost** [comment]
@Tsoccerguy3 If you started an issue, there's a close issue button next to the comment button.

**Comment by Tsoccerguy3** [comment]
yes I see that Github has fixed issue
