### ISSUE TITLE
longterm useragent solution

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#790]
Waterfox is a lesser used browser, so it will always have to struggle with user agent strings.

The simplest thing to do. Is set the default user agent as "waterfox $version", while let the end user easily pick a user agent with a bundled addon( that already exist) with an obvious new button. He will have a predefined list of user agents to chose from,plus the ability to use his own with a few links where he can find more.

It's a simple solution, doesn't drain resources and less users will complain about their favorite site breaking.

**Comment by grahamperrin** [comment]
Nope to the less compatible default.

**Comment by ghost** [comment]
The default is simply the real one. The bundled useragent changer is to lie easily.

**Comment by grahamperrin** [comment]
#178

**Comment by ghost** [comment]
vivaldi
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36 Vivaldi/1.2.490.43`

opera
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.52 Safari/537.36 OPR/15.0.1147.100`

they both identify them selves at the end and pretend other stuff before that. Stuff at the beginning more important then stuff at the end. So i guess waterfox should be something like this:

`Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 Waterfox/56.2.5`

i think alex had done something  similar? The same?

the Firefox version can be regularly changed to what is currently most compatible. For the remaining sites, the user uses the bundled useragent changer.....

**Comment by grahamperrin** [comment]
> … i think alex had done something similar?  …

https://github.com/MrAlex94/Waterfox/commit/8e978a6df522a2e12ab3080d691fec490db01a56#diff-a633a6dfcf161bf7cb9d3d9cdcdc2faeR439 lines 439 and 442, I guess. Related: 

- [The Waterfox Blog | Waterfox 56.2.3 Release](https://blog.waterfoxproject.org/waterfox-56.2.3-release-download) (2018-09-14)

> … guess waterfox should be something like this:
> 
> `Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 Waterfox/56.2.5`

-1

56.2.5 is, loosely, more like 56 (with some 57) than like 60. 

----

Respectfully, 

-1 
to bundling an extension.

**Comment by ghost** [comment]
Are they sites that treat the UA of firefox and the same UA with "Waterfox/56.2.5" at the END differently? Github seams ok. other sites seam ok also.

I think Alex's error, was to put "Waterfox" first. Stuff more to the beginning are more important. Sites will simply ignore the end they don't understand, and interpret the beginning as firefox. And he also gave firefox the version number of waterfox, a version number that doesn't exist.

Do you have a problem with something like this as a default?
`Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 Waterfox/56.2.5`

Bundling an extension is easier then making UI changes.... It's a more realistic proposal.

**Comment by grahamperrin** [comment]
> … Alex's error, was to put "Waterfox" first. …

Probably **not** an error. Please refer to the previously linked issue, https://github.com/MrAlex94/Waterfox/issues/178#issuecomment-366699777 in particular.

**Comment by ghost** [comment]
you forgot the "rv:57.0" part?

rv:XX and Firefox/XX at the same version number that really exist. The beginning is just a copy paste from firefox. Then at the end Waterfox/YY with YY the real version of Waterfox. XX and YY shouldn't be the same.

github doesn't complain with this
`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 Waterfox/56.2.5`

**Comment by grahamperrin** [comment]
GitHub takes an exceptional approach to at least one Linux-specific string. #789 

> you forgot the "rv:57.0" part? …

Nope, not forgotten. 

Please refer to the previously linked issue, https://github.com/MrAlex94/Waterfox/issues/178#issuecomment-394196794 in particular. 

` Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 Waterfox/56.2.5` is no good for (at least) Discord.

**Comment by ghost** [comment]
you used "56.2" for that experiment A-0X
Firefox 56.2 exist? Keep the beginning a real UA of Firefox. On the server side, you can have a completely brain dead script.

about
`Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 Waterfox/56.2.5`

it's treated differently from
`Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0`

It's the Waterfox part or the 57 part? Firefox 57 is quite old now.

**Comment by grahamperrin** [comment]
57 was suggested at https://github.com/MrAlex94/Waterfox/issues/790#issuecomment-438630290 above.

**Comment by Scrxtchy** [comment]
I think a year ago, a number of default user agents overrides were shipped with Waterfox just for compatibility. But this meant that a lot of rules where being made and updated every so often. And I'm sure that these were all cut until some we found out a better solution to manage them.

I've had a few problems with the default user agent string too. Just having 'Waterfox' in there breaks slack's god awful whitelist. Even though they support the version of the browser.

Usually when I do my manual overrides, I target 60, or just mask it completely
