### ISSUE TITLE
404 not found on Windows portable download

### ISSUE THREAD

**Issue by TheQuickFox** [BrowserWorks/waterfox#792]
**Describe the bug**
Clicking on the Waterfox Portable version link results in a 404 not found error.
https://storage-waterfox.netdna-ssl.com/releases/win64/portable/WaterfoxPortable_56.2.5_English.paf.exe

404 Not Found
nginx

**To Reproduce**
1. Go to https://www.waterfoxproject.org/en-US/waterfox/new/?scene=1
2. Click on 'Advanced install options & other platforms'
3. Click on to 'Windows Portable'

**Expected behavior**
A download starting of file WaterfoxPortable_56.2.5_English.paf.exe

**Screenshots**
Using Waterfox
![waterfox download error](https://user-images.githubusercontent.com/30596092/48567085-955b6e80-e8fc-11e8-88ed-f78dc56f55ac.jpg)

Using Internet Explorer
![waterfox download error ie](https://user-images.githubusercontent.com/30596092/48567213-cdfb4800-e8fc-11e8-8775-5a3c7910e49b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro x64

**Additional context**
It has never worked for Portable releases 56.2.4. and 56.2.5
An explanation and fix would be welcome as uses are experiencing and reporting this problem on the Waterfox Blog comments and Reddit as well.

**Comment by TheQuickFox** [comment]
I have no idea why this is taking so long.

With some googling I found a download:
https://www.upload.ee/files/9138285/WaterfoxPortable_56.2.5_English.paf.exe.html
(Not uploaded by me)

VirusTotal check:
https://www.virustotal.com/#/file/c1266f623e6eedceb3b143bd36aa886d4f995a5818984439e36650a20bfc1fc5/detection

A check with malwarebytes 3.6.1.2711 (Updates 2018/11/30) gives a all clean.

It extracts and starts fine and shows the correct version but I cannot guarantee anything because I did not upload it.

**Comment by MrAlex94** [comment]
Sorry, have had some issues with the build bot and have been working on
fixing it (plus life has been busy!) but an older version of portable
should update it to it fine in the meanwhile. I wouldn’t trust anything
that isn’t signed by Waterfox Limited digital signal.

**Comment by TheQuickFox** [comment]
Thanks for commenting, @MrAlex94. I really appreciate it.

**Comment by grahamperrin** [comment]
Now found. Thanks Alex.

**Comment by MrAlex94** [comment]
No problem! Sorry for the delay.

**Comment by grahamperrin** [comment]
https://www.virustotal.com/#/file/0cdad0c945180c1c0546ef2c02747fd0790e93dac62b0fd84909dcbbb4199d32/detection

> No engines detected this file
