### ISSUE TITLE
XUL.DLL, frequent but intermittent crashing

### ISSUE THREAD

**Issue by MelchiorGaspar** [BrowserWorks/waterfox#793]
**Describe the bug**
my use of Waterfox has been having frequent but intermittent crashing,
Windows says the faulty module is the XUL.DLL 
I don't know for sure if its an extension OR the xul.dll itself 
ie. a bug in Waterfox vs a extension, possibly a bug in uBlock Origin as its the only extension always running 
doing something...
these crashes occur even when I am afk and the browser is loaded and idle... 
so this bug report is just a starting point to try and better hunt down the cause of the crashing...

**To Reproduce**
idk or n/a, 
or try installing uBlock Origin extension.. and run with it for a few days...

**Expected behavior**
I expect Waterfox to run without crashing all the time.

**Screenshots**
![waterfox_ff-extensions_list_screenshot_01](https://user-images.githubusercontent.com/1712842/48577358-02fba080-e8e5-11e8-926c-2fd9e5c80829.png)
![waterfox_ff-extensions_list_screenshot_02](https://user-images.githubusercontent.com/1712842/48577359-02fba080-e8e5-11e8-93ed-cf65f64d532f.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 ULTIMATE SP1 x64
 - Version  Waterfox v56.2.5

**Additional context**
Addon list: see screenshots

**Comment by MelchiorGaspar** [comment]
as GitHub does not support older versions of Firefox I had to use the up to date Firefox instead of Waterfox to publish this bug report... 

more info as I can get it or as requested....

**Comment by MelchiorGaspar** [comment]
it could also be related to out of control memory usage...
Waterfox/Firefox becomes less responsive after 2GB of usage...

**Comment by grahamperrin** [comment]
Troubleshooting information please. Use the **Copy text to clipboard** button at: 

- about:support

----

> … GitHub does not support …

https://www.reddit.com/comments/9drjqx/-/e94m0yv/

**Comment by MelchiorGaspar** [comment]
@grahamperrin  ok brb

**Comment by MelchiorGaspar** [comment]
Application Basics
------------------

Name: Waterfox
Version: 56.2.5
Build ID: 20181030205921
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0; Waterfox) Gecko/20100101 Firefox/56.2.5
OS: Windows_NT 6.1
Multiprocess Windows: 0/1 (Disabled by add-ons)
Web Content Processes:
Stylo: true (enabled by user)
Google Key: Missing
Mozilla Location Service Key: Missing
Safe Mode: false

Waterfox Features
-----------------

Extensions
----------

Name: about:addons-memory 2016
Version: 10.0.1
Enabled: true
ID: about-addons-memory@sturdiguns.org

Name: Add-ons Manager - Version Number
Version: 1.5
Enabled: true
ID: AMVersionNumber@Aris_CTRdev

Name: Add-ons Manager Context Menu
Version: 0.4.2.1-signed.1-signed
Enabled: true
ID: amcontextmenu@loucypher

Name: Classic Theme Restorer
Version: 1.7.8
Enabled: true
ID: ClassicThemeRestorer@ArisT2Noia4dev

Name: Download Manager Tweak
Version: 1.0.13
Enabled: true
ID: {F8A55C97-3DB6-4961-A81D-0DE0080E53CB}

Name: Easy Youtube Video Downloader Express
Version: 14.0
Enabled: true
ID: {b9acf540-acba-11e1-8ccb-001fd0e08bd4}

Name: Google search link fix
Version: 1.6.7
Enabled: true
ID: jid0-XWJxt5VvCXkKzQK99PhZqAn7Xbg@jetpack

Name: Mozilla Archive Format
Version: 5.2.1
Enabled: true
ID: {7f57cf46-4467-4c2d-adfa-0cba7c507e54}

Name: Secure Login (Embedded WebExtension)
Version: 0.2.1
Enabled: true
ID: @slogin

Name: Secure Password Generator
Version: 1.0.9
Enabled: true
ID: password.generator@kolya.ca

Name: Stylus
Version: 1.4.23
Enabled: true
ID: {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}

Name: Tab Mix Plus
Version: 0.5.5.0
Enabled: true
ID: {dc572301-7619-498c-a57d-39143191b318}

Name: To Google Translate
Version: 3.3
Enabled: true
ID: jid1-93WyvpgvxzGATw@jetpack

Name: uBlock Origin
Version: 1.17.2
Enabled: true
ID: uBlock0@raymondhill.net

Name: UnMHT
Version: 8.3.2
Enabled: true
ID: {f759ca51-3a91-4dd1-ae78-9db5eee9ebf0}

Name: About Sync extension for Firefox
Version: 0.0.23
Enabled: false
ID: aboutsync@mhammond.github.com

Name: Add-on Compatibility Reporter
Version: 2.2.4
Enabled: false
ID: compatibility@addons.mozilla.org

Name: Elite Download Manager
Version: 0.1.0
Enabled: false
ID: {07b7d513-2280-4ae2-b482-d12a156913c1}

Name: GitHub Notifier
Version: 1.3.1
Enabled: false
ID: {0906178a-2043-4d0c-a099-bd6a4d00945e}

Name: Greasemonkey
Version: 4.1
Enabled: false
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Tab Memory Usage
Version: 0.2.7
Enabled: false
ID: jid1-fRvgLzKONCsPew@jetpack

Name: Web ScrapBook
Version: 0.27.0
Enabled: false
ID: webscrapbook@danny0838.addons.mozilla.org

Graphics
--------

Features
Compositing: Direct3D 11
Asynchronous Pan/Zoom: none
WebGL 1 Driver WSI Info: EGL_VENDOR: Google Inc. (adapter LUID: 000000000001315f) EGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses
WebGL 1 Driver Renderer: Google Inc. -- ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
WebGL 1 Driver Version: OpenGL ES 2.0 (ANGLE 2.1.0.dec065540d5f)
WebGL 1 Driver Extensions: GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object
WebGL 1 Extensions: ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_shader_texture_lod EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture
WebGL 2 Driver WSI Info: EGL_VENDOR: Google Inc. (adapter LUID: 000000000001315f) EGL_VERSION: 1.4 (ANGLE 2.1.0.dec065540d5f) EGL_EXTENSIONS: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_EXTENSIONS(nullptr): EGL_EXT_client_extensions EGL_EXT_platform_base EGL_EXT_platform_device EGL_ANGLE_platform_angle EGL_ANGLE_platform_angle_d3d EGL_ANGLE_device_creation EGL_ANGLE_device_creation_d3d11 EGL_ANGLE_experimental_present_path EGL_KHR_client_get_all_proc_addresses
WebGL 2 Driver Renderer: Google Inc. -- ANGLE (NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0)
WebGL 2 Driver Version: OpenGL ES 3.0 (ANGLE 2.1.0.dec065540d5f)
WebGL 2 Driver Extensions: GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_pack_reverse_row_order GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_sync_query GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_frag_depth GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_dxt1 GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_norm16 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth32 GL_OES_element_index_uint GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object
WebGL 2 Extensions: EXT_color_buffer_float EXT_texture_filter_anisotropic EXT_disjoint_timer_query MOZ_debug OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc
Direct2D: true
DirectWrite: true (6.2.9200.22164)
GPU #1
Active: Yes
Description: NVIDIA GeForce GTX 750 Ti
Vendor ID: 0x10de
Device ID: 0x1380
Driver Version: 25.21.14.1694
Driver Date: 11-12-2018
Drivers: nvd3dumx,nvwgf2umx,nvwgf2umx nvd3dum,nvwgf2um,nvwgf2um
Subsys ID: 37593842
RAM: 2048

Diagnostics
AzureCanvasAccelerated: 0
AzureCanvasBackend: direct2d 1.1
AzureContentBackend: direct2d 1.1
AzureFallbackCanvasBackend: skia
Decision Log
GPU_PROCESS:
unavailable by default: Multi-process mode is not enabled
WEBRENDER:
opt-in by default: WebRender is an opt-in feature
unavailable by runtime: Build doesn't include WebRender
ADVANCED_LAYERS:
disabled by default: Disabled by default




Media
-----

Audio Backend: wasapi
Max Channels: 2
Preferred Channel Layout: stereo
Preferred Sample Rate: 48000
Output Devices
Name: Group
Speakers (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
NVIDIA Output (NVIDIA High Definition Audio): HDAUDIO\FUNC_01&VEN_10DE&DEV_0060&SUBSYS_38423759&REV_1001\5&2d67065c&0&0001
NVIDIA Output (NVIDIA High Definition Audio): HDAUDIO\FUNC_01&VEN_10DE&DEV_0060&SUBSYS_38423759&REV_1001\5&2d67065c&0&0001
Realtek Digital Output(Optical) (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Realtek Digital Output (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
NVIDIA Output (NVIDIA High Definition Audio): HDAUDIO\FUNC_01&VEN_10DE&DEV_0060&SUBSYS_38423759&REV_1001\5&2d67065c&0&0001
Input Devices
Name: Group
Front Green In (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Side (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Microphone (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Microphone (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Internal AUX Jack (NVIDIA High Definition Audio): HDAUDIO\FUNC_01&VEN_10DE&DEV_0060&SUBSYS_38423759&REV_1001\5&2d67065c&0&0001
Line In (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Internal AUX Jack (NVIDIA High Definition Audio): HDAUDIO\FUNC_01&VEN_10DE&DEV_0060&SUBSYS_38423759&REV_1001\5&2d67065c&0&0001
Stereo Mix (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Internal AUX Jack (NVIDIA High Definition Audio): HDAUDIO\FUNC_01&VEN_10DE&DEV_0060&SUBSYS_38423759&REV_1001\5&2d67065c&0&0001
Front Pink In (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Front (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Subwoofer (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Rear (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Line In (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001
Center (Realtek High Definition Audio): HDAUDIO\FUNC_01&VEN_10EC&DEV_0892&SUBSYS_10438436&REV_1003\4&e8b890b&0&0001

Important Modified Preferences
------------------------------

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.smart_size_cached_value: 358400
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 3
browser.cache.memory.capacity: 513024
browser.download.folderList: 2
browser.download.lastDir.savePerSite: true
browser.download.useDownloadDir: false
browser.places.smartBookmarksVersion: 8
browser.search.context.loadInBackground: true
browser.sessionstore.resume_from_crash: false
browser.sessionstore.upgradeBackup.latestBuildID: 20181030205921
browser.startup.homepage: about:blank
browser.startup.homepage_override.buildID: 20181030205921
browser.startup.homepage_override.mstone: 56.2.5
browser.tabs.closeWindowWithLastTab: false
browser.tabs.drawInTitlebar: false
browser.tabs.remote.autostart.2: true
browser.urlbar.daysBeforeHidingSuggestionsPrompt: 0
browser.urlbar.lastSuggestionsPromptDate: 20170821
browser.urlbar.searchSuggestionsChoice: false
browser.urlbar.suggest.searches: false
browser.urlbar.timesBeforeHidingSuggestionsHint: 3
dom.push.userAgentID: fd5af983b1014d6d97b281fd5b451a28
extensions.lastAppVersion: 56.2.5
general.useragent.locale: en-US
gfx.crash-guard.d3d11layers.appVersion: 56.2.5
gfx.crash-guard.d3d11layers.deviceID: 0x1380
gfx.crash-guard.d3d11layers.driverVersion: 25.21.14.1694
gfx.crash-guard.d3d11layers.feature-d2d: true
gfx.crash-guard.d3d11layers.feature-d3d11: true
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d9video: 2
layers.mlgpu.sanity-test-failed: false
layout.css.servo.enabled: true
media.benchmark.vp9.fps: 233
media.benchmark.vp9.versioncheck: 3
media.eme.enabled: true
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1522120461
media.gmp-gmpopenh264.version: 1.7.1
media.gmp-manager.buildID: 20181030205921
media.gmp-manager.lastCheck: 1542233720
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1522120462
media.gmp-widevinecdm.version: 1.4.8.1008
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
media.webrtc.debug.log_file: C:\Temp-Sys\WebRTC.log
network.cookie.prefsMigrated: true
network.dns.disablePrefetch: true
network.http.pipelining: true
network.http.pipelining.max-optimistic-requests: 20
network.http.pipelining.maxrequests: 128
network.http.pipelining.ssl: true
network.http.proxy.pipelining: true
network.http.speculative-parallel-limit: 0
network.predictor.cleaned-up: true
network.predictor.enabled: false
network.prefetch-next: false
network.warnOnAboutNetworking: false
places.database.lastMaintenance: 1542036927
places.history.expiration.transient_current_max_pages: 115229
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.state.java: 0
plugin.state.npdeployjava: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_bgcolor: false
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_bgimages: false
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_duplex: -437918235
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_edge_bottom: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_edge_left: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_edge_right: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_edge_top: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_evenpages: true
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_footercenter:
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_footerleft: &PT
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_footerright: &D
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_headercenter:
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_headerleft: &T
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_headerright: &U
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_in_color: true
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_margin_bottom: 0.5
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_margin_left: 0.5
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_margin_right: 0.5
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_margin_top: 0.5
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_oddpages: true
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_orientation: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_page_delay: 50
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_paper_data: 1
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_paper_height: -1.00
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_paper_name:
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_paper_size_unit: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_paper_width: -1.00
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_resolution: 600
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_reversed: false
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_scaling: 1.00
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_shrink_to_fit: true
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_to_file: false
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_unwriteable_margin_bottom: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_unwriteable_margin_left: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_unwriteable_margin_right: 0
print.printer_HP_Universal_Printing_PCL_6_(v5.8.0).print_unwriteable_margin_top: 0
privacy.cpd.cache: false
privacy.cpd.cookies: false
privacy.cpd.extensions-tabmix: false
privacy.cpd.formdata: false
privacy.cpd.sessions: false
security.dialog_enable_delay: 500
security.sandbox.content.tempDirSuffix: {6d872cf8-c8f6-421e-9bc8-8d80f4d84aeb}
services.sync.declinedEngines:
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1541430154

Important Locked Preferences
----------------------------

Places Database
---------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0
Accessible Handler Used: true

Library Versions
----------------

NSPR
Expected minimum version: 4.16
Version in use: 4.16

NSS
Expected minimum version: 3.32.1
Version in use: 3.32.1

NSSSMIME
Expected minimum version: 3.32.1
Version in use: 3.32.1

NSSSSL
Expected minimum version: 3.32.1
Version in use: 3.32.1

NSSUTIL
Expected minimum version: 3.32.1
Version in use: 3.32.1

Experimental Features
---------------------

Sandbox
-------

Content Process Sandbox Level: 1
Effective Content Process Sandbox Level: 1

**Comment by grahamperrin** [comment]
> Stylo: true (enabled by user)

With Waterfox 56.x, please: 

- do **not** enable Stylo unless advised to do so

– it's known to cause crashes with some web pages. 

https://github.com/MrAlex94/Waterfox/issues/332#issuecomment-380200636 refers to a shortlist that Reddit has archived, I can no longer add to the list. 

Can you let us have the address of a web page that crashed with Stylo enabled? Thanks.

**Comment by MelchiorGaspar** [comment]
gmail, Twitter, Facebook are three of four tabs I have open all the time.... the other is my primary email...
I haven't had any crashes there were immediate opening loading a webpage... its always intermittent... 

Stylo huh... I don't recall that one.. how do I disable it..
is this it? 
- layout.css.servo.enabled = disabled/false

ok its disabled now...

**Comment by MelchiorGaspar** [comment]
I seem to be having less crashing since I disabled Stylo!

**Comment by MelchiorGaspar** [comment]
I just woke up from a nap to find that Waterfox crashed with xul.dll as the culprit...
go figure... lol..

**Comment by MelchiorGaspar** [comment]
I will get and post more as requested by @MrAlex94 if when he sees this.. 
but last commit was the end of October so he seems to be afk/mia...

**Comment by grahamperrin** [comment]
> mia

Not missing in action. There's more to Waterfox Project than GitHub and 56.x. See for example the tweets; the responses to blog post commentary; this week's posts in Reddit; and so on.

**Comment by MelchiorGaspar** [comment]
ok... 
I have a bunch of memory DUMP files if you guys would find them useful... 
If you have other requests for info let me know...

**Comment by Squall-Leonhart** [comment]
Melchior, I seriously think your system is just not fully stable with that manufacturer overclocked Fx processor.

**Comment by MelchiorGaspar** [comment]
Squall-Leonhart, aaah huh..   could be.. but the rest of the time my system works fine...

anyway I got a stack trace using GNU Debugger (gdb64) took all night and into today for it to finally crash... here it is I hope it helps
-----
-----
```
[Thread 4612.0x11b8 exited with code 0]
warning: [JavaScript Error: "NS_ERROR_FAILURE: Couldn't decrypt string" 
{file: "jar:file:///C:/Program%20Files/Waterfox/omni.ja!/components/crypto-SDR.js" line: 136}]

Above REPEATS 15 TIMES

[New Thread 4612.0x1cd0]

Program received signal SIGSEGV, Segmentation fault.
0x000007fee32ecbc3 in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
(gdb) bt
#0  0x000007fee32ecbc3 in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#1  0x000007fee32ee8d8 in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#2  0x000007fee32eb5eb in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#3  0x000007fee329de16 in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#4  0x000007fee329bade in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#5  0x000007fee32981d2 in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#6  0x000007fee329be67 in xul!XRE_GetBootstrap () from C:\Program Files\Waterfox\xul.dll
#7  0x000007fee156f9ff in xul!mozilla_dump_image () from C:\Program Files\Waterfox\xul.dll
#8  0x000007fee1578747 in xul!mozilla_dump_image () from C:\Program Files\Waterfox\xul.dll
#9  0x000007fee0a09323 in ?? () from C:\Program Files\Waterfox\xul.dll
#10 0x000007fee0a088b7 in ?? () from C:\Program Files\Waterfox\xul.dll
#11 0x000007fee0dc50c5 in xul!??4SoundTouch@soundtouch@@QEAAAEAV01@AEBV01@@Z () from C:\Program Files\Waterfox\xul.dll
#12 0x000007fee0da580b in ?? () from C:\Program Files\Waterfox\xul.dll
#13 0x000007fee220b858 in xul!mozilla_dump_image () from C:\Program Files\Waterfox\xul.dll
#14 0x000007fee226df24 in xul!mozilla_dump_image () from C:\Program Files\Waterfox\xul.dll
#15 0x000007fee30ec223 in xul!workerlz4_maxCompressedSize () from C:\Program Files\Waterfox\xul.dll
#16 0x000007fee316751c in xul!workerlz4_maxCompressedSize () from C:\Program Files\Waterfox\xul.dll
#17 0x000007fee3165d72 in xul!workerlz4_maxCompressedSize () from C:\Program Files\Waterfox\xul.dll
#18 0x000007fee3165818 in xul!workerlz4_maxCompressedSize () from C:\Program Files\Waterfox\xul.dll
#19 0x000000013f8519ee in ?? ()

Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by grahamperrin** [comment]
Side note: to avoid the inappropriate # cross-references, use markdown for code blocks. https://commonmark.org/help/

**Comment by grahamperrin** [comment]
```text
Name: Secure Login (Embedded WebExtension)
Version: 0.2.1
Enabled: true
ID: @slogin
```

What was the origin of that extension?

**Comment by MelchiorGaspar** [comment]
I downloaded it from the Mozilla Firefox addon page... I'm pretty sure...
https://addons.mozilla.org/en-US/firefox/addon/secure-login-webextension/
Secure Login is a login extension for Mozilla Firefox integrated password manager
but its gone now from the addon site.... I wonder why...???

its main site is..
https://add0n.com/secure-login.html
and its GitHub page = https://github.com/sarahavilov/secure-login
no updates in over a year...
I don't even really use it...

**Comment by grahamperrin** [comment]
> … gone …

[Timeline for disabling legacy add-ons on addons.mozilla.org | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/)

With the Classic Add-ons Archive extension, you'll find it at: 

- caa:addon/secure-login-webextension

**Comment by MelchiorGaspar** [comment]
scrapping XUL addons was the worse thing Mozilla ever did to Firefox and all its users...

**Comment by MelchiorGaspar** [comment]
I ran Waterfox through the GNU Debugger again and got the exact same crash and backtrace...
if I only had debug build of Waterfox maybe I could get some more info for @MrAlex94 to use in fixing this.

**Comment by MelchiorGaspar** [comment]
@MrAlex94 were you able to identify and fix the issue?
I have not been having any chrashes in a long time with Waterfox.. BUT I don't use much either...
I some times use it to access old .MAFF and .MHT webpage archive files....
and I like the addon Download Manager Tweak as one of my favorites.. as the newer Firefox downloads manager sucks..
