### ISSUE TITLE
webgl.enable-debug-renderer-info should be set to false by default

### ISSUE THREAD

**Issue by hook321** [BrowserWorks/waterfox#798]
It's a potential privacy concern.

It's set to false by default in SeaMonkey, Pale Moon, and Basilisk. It's also disabled whenever ``privacy.resistFingerprinting`` is set to true (https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info). All of which lead me to believe setting it to false won't break stuff.

**Comment by grahamperrin** [comment]
I suggest caution. 

Users who are concerned about privacy can/should be encouraged to know the consequences of, and then maybe use, `privacy.resistFingerprinting`

### Considerations

[The use cases](http://codeflow.org/entries/2016/feb/10/webgl_debug_renderer_info-extension-survey-results/#q4-can-you-briefly-describe-your-use-or-planned-use) found in [WEBGL_debug_renderer_info extension survey results - Codeflow](http://codeflow.org/entries/2016/feb/10/webgl_debug_renderer_info-extension-survey-results/#q4-can-you-briefly-describe-your-use-or-planned-use) (2016-02-10). These two in particular: 

> We use WEBGL_debug_renderer_info together with UA string to estimate device performance and available VRAM. Based on this information we enable or disable computation expensive features and adapt texture sizes in order to optimize performance and reduce battery consumption.

> Diagnosing broken-driver-related rendering issues, preemptively moving low-performing clients to fallback renderers.

The second case – Google Maps – was also the first case mentioned in response to this month's https://twitter.com/grorgwork/status/1062395616867700736

**Comment by hook321** [comment]
I'm not suggesting we set ``privacy.resistFingerprinting`` to true by default, if I remember correctly that setting has negative effects on the user, while changing ``webgl.enable-debug-renderer-info`` would have little or no perceivable negative impact to the user. It also wasn't supported until Firefox 53, so Firefox 52 ESR users would have noticed perceivable negatives of not having it if there are any.

**Comment by hook321** [comment]
Correction on my other comments: Changing ``privacy.resistFingerprinting`` only has an effect on this feature starting in Firefox 60-ish (https://bugzilla.mozilla.org/show_bug.cgi?id=1337157)

**Comment by Squall-Leonhart** [comment]
it should be left alone because it causes issue #1549
