### ISSUE TITLE
English language news report displayed in garbled text

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#800]
**Describe the bug**
The Guardian newspaper released a copy of a leaked Brexit declaration today. The document displays correctly in IE11, but not in Waterfox 56.2.5

**To Reproduce**
1. Go to 'https://www.theguardian.com/politics/2018/nov/22/brexit-leaked-political-declaration-in-full...'
2. The document can be seen below the image of PM May and EU Commission President Junker. 

**Expected behavior**
The declaration should be displayed in English. 

**Screenshots**
This is how it appears in Waterfox.

![waterfox_display](https://user-images.githubusercontent.com/33827636/48917890-652a4780-ee89-11e8-8217-6c5852e5704a.PNG)

This is how it appears in IE11
![display_ie11](https://user-images.githubusercontent.com/33827636/48917910-90149b80-ee89-11e8-9956-980edd9086b1.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 8.1

**Comment by grahamperrin** [comment]
>  The declaration should be displayed in English.

It is, for me: 

![2018-11-23 01 55 16 waterfox](https://user-images.githubusercontent.com/192271/48926116-db976b80-eec2-11e8-924c-edbb2178edb2.png)

Waterfox 56.2.5 on FreeBSD-CURRENT. 

@Telmesomething is the issue reproducible with Waterfox in safe mode? 

Does https://www.scribd.com/document/393865079/POLITICAL-DECLARATION-SETTING-OUT-THE-FRAMEWORK-FOR-THE-FUTURE-RELATIONSHIP-BETWEEN-THE-EUROPEAN-UNION-AND-THE-UNITED-KINGDOM#fullscreen appear OK?

What's your preferred locale? 

- about:preferences#general

What are your preferred languages for content? 

- about:preferences#content

**Comment by Telmesomething** [comment]
It appears to be a profile issue. I just created a new one and that displays the page properly. I guess I should have done that before posting.

Apologies for the inconvenience.
