### ISSUE TITLE
Two Concerning UUID Leak and Fingerprinting Vectors, Still Not Fixed in Firefox Either

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#801]
I am wondering if we can devise a way to address these? I don't think TBB has done anything with them yet, either.

https://bugzilla.mozilla.org/show_bug.cgi?id=1405971
https://bugzilla.mozilla.org/show_bug.cgi?id=1372288

**Comment by ilikenwf** [comment]
I don't grasp why the firefox devs are seemingly not rushing to fix this one because it negates most if not all of the tor uplift stuff they've been doing.

**Comment by ilikenwf** [comment]
clicked wrong button, sorry

**Comment by Atavic** [comment]
[Latex Gloves](http://www.cse.chalmers.se/~andrei/ndss19.pdf) proposes a mitigation that is present in uBlock Origin, see:
https://github.com/gorhill/uBlock/tree/6815c85521142a34477f8a347da88b195c015088/src/web_accessible_resources

That obviously needs extensions devs work, as users for *Resetting Firefox random UUID* we can reinstall the extension or create a whole new profile.

A related [issue](https://github.com/mozilla-services/screenshots/issues/3429)

**Comment by mparnelldmp** [comment]
I somewhat wonder if perhaps uMatrix could be used to firewall such requests so that at the very least one has to explicitly enable a given domain permission to access anything in the moz-extension namespace?

For the headers, I guess we could use an extension or build in a system to automatically purge a header that matches moz-extension ...

**Comment by mparnelldmp** [comment]
I can't actually reproduce this one with a fetch request myself...

**Comment by Atavic** [comment]
Bugzilla lead me to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1271354#c14).

**Comment by mparnelldmp** [comment]
I guess we could just roll this back in the source code, then...although I'm not entirely sure that this still leaks the origin header.

https://hg.mozilla.org/mozilla-central/rev/60823f6c03f2
