### ISSUE TITLE
Firefox forks, split into several libraries?

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#803]
They are 3 Firefox forks, that seam to ignore each other.
The sources can't be split into several libraries that they can more or less share?
Additionally, maybe some others might use some of these libraries in their own projects.

Even Gecko it self is a massive monster. Maybe it could be split? In linux there's X that actually draws the screen, and then they are window managers that tell X where to draw. I mean by this, that the splits could look exotic.

**Comment by grahamperrin** [comment]
Maybe of interest, historical: #121 (closed)
