### ISSUE TITLE
Enable setting HTMLInputElement.files

### ISSUE THREAD

**Issue by tmkk** [BrowserWorks/waterfox#807]
HTMLInputElement.files property is read-only until Firefox 56. This is fixed in Firefox 57 and could you backport a patch available at [bugzilla #1384030](https://bugzilla.mozilla.org/show_bug.cgi?id=1384030)?

**Comment by grahamperrin** [comment]
OK, via https://bugzilla.mozilla.org/show_bug.cgi?id=1384030#c1 I see the issue with the demo at https://output.jsbin.com/vaxagel/quiet

Demos aside … please: are you aware of any production site that is bugged by this issue? 

Thanks. 

(Not doubting the value of the enhancement. Just curious about what types of site require the feature; I have never encountered the issue.)

**Comment by tmkk** [comment]
No, it's a problem in a userscript (user.js) for my personal use. Anyway this is a trivial issue for me and it is ok to give priority to other important issues.

Thanks
