### ISSUE TITLE
[Feature request] Bundle I don't care about cookies and uBlock

### ISSUE THREAD

**Issue by probonopd** [BrowserWorks/waterfox#809]
Give back some sanity to the out-of-the-box web experience by pre-installing and pre-configuring those 2 essential plugins:

* Get rid of annoying cookie warnings from almost all "infected" websites with https://www.i-dont-care-about-cookies.eu/
* Block ads with https://addons.mozilla.org/de/firefox/addon/ublock-origin/

**Comment by TheQuickFox** [comment]
These are two excellent add-ons, I run them myself at every browser I use.

But should these be bundled? I don't know. These add-ons may break a website once in a while and this may be a problem for the average Joe or Jane. Also, some users may want to display ads to generate some income for the website owners.

I would say: let power users install them manually.

**Comment by laniakea64** [comment]
These types of extensions represent a clear user choice and require the user to be at least somewhat informed.  It needs to be up to the user to consciously install them.

**Comment by Squall-Leonhart** [comment]
Nope

**Comment by probonopd** [comment]
> These types of extensions represent a clear user choice and require the user to be at least somewhat informed. 

Maybe a dialog  could ask the user at first startup:

```
[x] I don't want to be asked about cookies
[x] I don't want to see advertising
```

**Comment by laniakea64** [comment]
> Maybe a dialog could ask the user at first startup:

Unfortunately it is not that simple.  In the case of uBlock Origin, it is far more than just an ad blocker.  Trying to describe its blocking by a single purpose doesn't cover it.  Even if it were preconfigured to only block ads, there is still the issue of false positives and breaking websites.  Users would need to be able to tell the difference between that and Waterfox bugs, which again requires the user to be somewhat informed.  Bundling uBlock Origin with Waterfox would blur that important line for users who don't understand uBlock Origin well enough.

I don't use "I don't care about cookies" myself, but [its website](https://www.i-dont-care-about-cookies.eu/) acknowledges the need for users to be informed -
> By using it, you explicitly **allow** websites to do whatever they want with cookies they set on your computer (which they mostly do anyway, whether you allow them or not). Please educate yourself about cookie related privacy issues and ways to protect yourself and your data. For example, you can block 3rd party cookies, install ad blocking extensions and then block tracking tools, delete browsing data regularly, enable Tracking Protection in your browser etc.

And as TheQuickFox mentioned, this extension may come with a risk of breaking websites, so users would need to be able to distinguish between "I don't care about cookies" false positives and Waterfox bugs.  Again, bundling it with Waterfox risks blurring that line.

Users who actively seek out and install these extensions will, by the nature of actively seeking out and installing extensions, do enough reading and have a sense of what's what.  The required information is too much to be conveyed with bundling these extensions.
