### ISSUE TITLE
New WF Update Won't Work Again With Mountain Lion

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#81]
Hi Alex, just applied the new WF update 49.0.0.3 on my Mac OSX Mountain Lion OS, got the message again, that this update requires Mac OSX 10.9 Mavericks. So I went back to WF 49.0.2.1, your previous fix, works perfectly again. Thanks, Ken.

**Comment by ghost** [comment]
Just another point Alex, in Preferences, Updates, I checked "do not check for updates" until WF 40.0.0.3 will work on Mountain Lion. Thanks, Ken.

**Comment by ghost** [comment]
Hey Mr. Alex94 just got WF 50.0 works perfectly on mac osx Mountain Lion. Thanks, Ken.

**Comment by MrAlex94** [comment]
Sorry about that, hopefully won't happen again :-)

**Comment by ghost** [comment]
Mr. Alex, just installed WF 50.0 over WF 48.0.2.1, works perfectly. Thanks so much, Ken.
Ken Kline
pixtureskk@sympatico.ca
