### ISSUE TITLE
WF keeps complaining that can't update.

### ISSUE THREAD

**Issue by Achaean** [BrowserWorks/waterfox#810]
**Describe the bug**

WF complains that couldn't update.
Ehm...what update? I already have the latest version (56.2.5).

**To Reproduce**

Do nothing. WF pops up this reminder regularly.

**Expected behavior**

Not to have this reminder.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

Devuan ASCII x64.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Achaean** [comment]
![screenshot](https://user-images.githubusercontent.com/3608053/49371539-746a8a00-f700-11e8-92a4-4336a354dbdb.png)

**Comment by ghost** [comment]
I have the same problem. I am running Waterfox 56.2.5 (64-bit) on Linux Mint 18.3.
I have even downloaded and installed a fresh copy of 56.2.5 but the message to update still keeps appearing.

**Comment by grahamperrin** [comment]
Cross reference: [[support] Update message telling me to manually update, but on latest version? : waterfox](https://www.reddit.com/r/waterfox/comments/9zm0c5/support_update_message_telling_me_to_manually/)

**Comment by Achaean** [comment]
THANKS grahamperrin!!! :-)

Installing WF from the repository, solved this issue.
I suppose, because it doesn't check any more, for newer versions.

I'm leaving the issue open, because it has to be solved.
(Eg. for distros that are not Debian based).

**Comment by reticulatus** [comment]
I am still running the same installation (version 56.2.5) of Waterfox, yet the problem stopped occurring several days ago. Perhaps a change was made on the server?

**Comment by grahamperrin** [comment]
Is this still an issue? 

https://www.waterfoxproject.org/update/linux64/56.2.5/en-US/release/update.xml looks OK, at a glance.

**Comment by ghost** [comment]
I updated to 56.2.6 on 21st Dec and haven't seen the error message since then.

**Comment by Achaean** [comment]
Neither I (so I'm closing this report).
