### ISSUE TITLE
Waterfox 52.2.5 wants to update to non existing newer version on Linux 64 Bit

### ISSUE THREAD

**Issue by Lalarian** [BrowserWorks/waterfox#815]
Hello!

 As the title says:
I am on Linux (Xubuntu 18.04 64 Bit) and have Waterfox 56.2.5. The update notification keeps popping up, telling me there was a more recent version - of course there is none, because I already have 56.2.5.

**Comment by ghost** [comment]
i don't know what's wrong with that, but just install with this repo
https://github.com/hawkeye116477/waterfox-deb

**Comment by Lalarian** [comment]
I don't know why: But the problem solved itself somehow.
