### ISSUE TITLE
Waterfox shows http://cosmicshambles.com/ninelessons as 'forbidden'

### ISSUE THREAD

**Issue by petefoth** [BrowserWorks/waterfox#817]
**Describe the bug**
When I try to browse to the url cosmicshambles.com/ninelessons, or the top level cosmicshambles.com I see a page containing only the word 'Forbidden'

**To Reproduce**
1. Go to http://cosmicshambles.com/
2. See error
3. Error also occurs at https://cosmicshambles.com/

**Expected behavior**
I expect to see the content of the web pages at those addresses 

**Desktop (please complete the following information):**
 macOS 10.13.6 (MacBook Air)
Running Waterfox 56.2.5 (64-bit)
 
**Further information**
The pages display  with no problems in other browsers on the system:
Firefox 63.0.3 (64-bit)
Chromium Version 70.0.3538.110 (Developer Build) (64-bit)
Safari Version 12.0.2 (13606.3.4.1.4)

**Comment by Lorienna** [comment]
Looks like rv:_geckoversion_ and Firefox/_firefoxversion_ tokens of the Waterfox user agent indicate different minor version numbers, and this can break web-sites. Those numbers are equal in Firefox, and the site is displayed correctly there.

So, for example, you can try the following:

about:support > copy user agent string > about:config > "I accept the risk!" > right-click > new > string > name: `general.useragent.override.cosmicshambles.com` > value: your user agent > change __Firefox/56.2.5__ to __Firefox/56.0__ or __rv:56.0__ to __rv:56.2__.

**Comment by grahamperrin** [comment]
Thanks @Lorienna 

Alternative values, which seem to work around the _forbidden_ response from the domain, include: 

- `Mozilla/5.0 (rv:56.0) Gecko/20100101 Firefox/56.0`
- `Mozilla/5.0 (rv:60.0) Gecko/20100101 Firefox/60.0`

– tested with Firefox 64.0_3,1 on FreeBSD-CURRENT. 

@petefoth for more general help with user agents with Waterfox 56.x, there's https://redd.it/9drjqx and then (if you like) you can close this issue.

**Comment by petefoth** [comment]
<snip>

> So, for example, you can try the following:
> 
> about:support > copy user agent string > about:config > "I accept the risk!" > right-click > new > string > name: `general.useragent.override.cosmicshambles.com` > value: your user agent > change **Firefox/56.2.5** to **Firefox/56.0** or **rv:56.0** to **rv:56.2**.

Using  the value 'Gecko/20100101 Firefox/56.0.5` means I don't see the 'Forbidden' response, but the page either times out loading, or doesn't render properly: text is displayed but no pictures or other graphics. This is true for the original version of Waterfox - 56.2.5 and the recent update

Changing the value to `(rv:60.0) Gecko/20100101 Firefox/60.0`. seems to give the same result. I'll try again when the CosmicShambles site may be less busy, but I won't close the issue yet as it still doesn't seem to work

**Comment by grahamperrin** [comment]
Thanks. 

Can you reproduce the second issue with Waterfox in safe mode?

I briefly tested http://cosmicshambles.com/ninelessons and http://cosmicshambles.com/ in very old Opera 12.16, no problem with graphics.

**Comment by petefoth** [comment]
> Can you reproduce the second issue with Waterfox in safe mode?
> 
Safe mode doesn't appear to make any difference

**Comment by petefoth** [comment]
Sorry - no idea how I closed this issue :(

**Comment by grahamperrin** [comment]
Re: https://www.reddit.com/r/waterfox/comments/9drjqx/user_agent/ecgcug6/

![image](https://user-images.githubusercontent.com/192271/50399633-c68b5200-0778-11e9-943c-397ff9659897.png)

- Waterfox 56.2.6
- FreeBSD-CURRENT

**Comment by grahamperrin** [comment]
@petefoth with the _forbidden_ issue worked around, is there still the other issue?

**Comment by grahamperrin** [comment]
@petefoth please cease the user agent override for the site. 

Re: https://github.com/MrAlex94/Waterfox/issues/882#issuecomment-473111312 you should find the site works as expected with Waterfox 56.2.8.

**Comment by petefoth** [comment]
Done. The site works fine without the re-direct.
Thank you.
I'll close the issue
