### ISSUE TITLE
WF 50.0 Works On Mac OSX Mountain Lion

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#82]
Hey Mr. Alex, just installed WF 50.0 over WF 49.0.2.1 in Mac OSX Mountain Lion, works perfectly. Thanks again so much, Ken.

**Comment by MrAlex94** [comment]
Does [this ](https://storage-waterfox.netdna-ssl.com/releases/osx64/installer/Waterfox%2050.0.2.1%20Setup.dmg) fix it?
