### ISSUE TITLE
Single click treated as double click when Waterfox regains focus

### ISSUE THREAD

**Issue by pokeshark** [BrowserWorks/waterfox#820]
Single click is treated as double click when Waterfox regains focus.

1. Load a webpage with text in a tab in Waterfox
2. Give focus to another application (send Waterfox in the background)
3. Single click on the text in the Waterfox window
4. Notice that the clicked word from text is now selected (which is double click behavior)

Alternatively with Tab Mix Plus (how I initially discovered this issue):
1. Having set behavior: Mouse -> Mouse Clicking -> Double click -> on a tab: Close Tab
2. Open tab(s)
3. Give focus to another application (send Waterfox in the background)
4. Single click on a tab from the Waterfox tab bar
5. Notice that the clicked tab will close (which is double click behavior)

Expected behavior:
Single clicking in out of focus Waterfox window should act as single click.

Desktop:
 - OS: Windows 10
 - Waterfox version: 56.2.5 (64-bits)

**Comment by pokeshark** [comment]
Issue was actually caused by FlashGot legacy extension v1.5.6.13

**Comment by maxoku** [comment]
Actually it's cased by FlashGot along with Multiprocess enabled.
While the extension is no loger maintained and there is no alternative for its functions it would be nice to have that fixed on Waterfox side.
