### ISSUE TITLE
[Feature Request] U2F / FIDO2 Support

### ISSUE THREAD

**Issue by corch** [BrowserWorks/waterfox#821]
**Describe the bug**
Waterfox does not currently support U2F or FIDO2 MFA protocols. I am unable to use my Yubikey 5 as a second factor on supported sites when using Waterfox.

Firefox has apparently supported this since v57, any chance this can be back-ported?

**To Reproduce**
1. Go to 'about:config'
2. Set security.webauth.u2f to 'true'
3. Restart Waterfox
4. Login to Github (for example, have also tried with AWS and Centrify)
5. Navigate to Profile->Settings->Security->Security Keys->Edit
6. Click "register new device" button.
7. Enter a name, click add
8. An error message is immediately displayed "The device cannot be registered"

**Expected behavior**
A message asking to insert the U2F key and activate it should appear. The U2F key should be registered once the device is inserted and acivated

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 
 - Version 1803

**Additional context**
Attempting to use with Yubikey 5 nano. The key works as expected using Brave.

**Comment by noplanman** [comment]
Would love to see proper support for this too.

At the moment it seems quite broken, and some websites register my key as inserted, even though it's not there. There seems to be some weird cache somewhere that keeps it "alive".

**Comment by noplanman** [comment]
Still have this in the current version 56.2.12 (64-bit).

This is really bugging me, as it makes the 2FA key useless!

Works perfectly on Firefox.

**Comment by ChiaYen-Kan** [comment]
I use WaterFox classic test the Security Key Series of yubikey in demo page https://demo.yubico.com/webauthn-technical/registration,
but it can't work and i got a error:

![yubikey-error-1](https://user-images.githubusercontent.com/40080620/91918986-1f094580-ecf7-11ea-80a8-69327fb3095f.png)

How to use yubikey with WaterFox classic ?

OS:
Windows 7 64bit

Browser:
WaterFox classic 2020.08.1

Config:
security.webauth.u2f to 'true'
security.webauth.u2f_enable_usbtoken to 'true'
security.webauth.webauthn to 'true'
security.webauth.webauthn_enable_usbtoken to 'true'

**Comment by hawkeye116477** [comment]
@ChiaYen-Kan I guess that's probably partially implemented, so it's not possible.

**Comment by thewho2018** [comment]
Getting a key soon. Would love to have it in Waterfox G3. Any news about it?

**Comment by noplanman** [comment]
Hi @thewho2018, it works for me 👍 

For both [Yubi](https://www.yubico.com/) (i have a version 4) and [Solo](https://solokeys.com/).

**Comment by thewho2018** [comment]
@noplanman i got my keys today! It works perfectly! i just read something old and i thought it did not work. My bad!
