### ISSUE TITLE
Flash Plugin still crashing

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#822]
Well, I really like waterfox, but its tottaly broken when I try open an site with flash animation.
I know, flash sucks, but I really need it, especially for the use of web banking...
I try to compile it again and again, e nothing...
So, what are we going to do?

**To Reproduce**
1. Go to 'any site with flash animation, like http://www.totaljerkface.com/happy_wheels.tjf'
2. Click on 'flash animation' and nothing nothing happens
3. See error

**Desktop (please complete the following information):**
 - OS: Arch Linux or Windows. 
- Versions: All versions of waterfox

sorry for my bad english.

**Comment by grahamperrin** [comment]
> See error

What do you see?

(I do not have Linux, Mac OS X or Windows at the moment.)

**Comment by ghost** [comment]
sorry, I I forgot to say...
Flash just does not load.

**Comment by grahamperrin** [comment]
Thanks. To clarify: no crash – true?

**Comment by grahamperrin** [comment]
Is there any mention of Flash at this address? 

- about:plugins

**Comment by grahamperrin** [comment]
https://helpx.adobe.com/uk/flash-player.html in Firefox 64.0_3,1 and Waterfox 56.2.6 on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/50400001-516d4c00-077b-11e9-836b-c5400d421e6a.png)

### Side notes (FreeBSD)

If I recall correctly, the plug-in did not become available to Waterfox until after I ran [www/nspluginwrapper](https://www.freshports.org/www/nspluginwrapper) as superuser. 

No trace of the text that usually appears, in the yellow rectangle, indicating whether the version is up-to-date. Not specific to Firefox or Waterfox; here's the symptom in surf: 

![image](https://user-images.githubusercontent.com/192271/50400468-ec1b5a00-077e-11e9-8f4b-1253449de0b9.png)
