### ISSUE TITLE
Wordpress Dashicons display issue on Mac OS X 10.8.5

### ISSUE THREAD

**Issue by schubidubi** [BrowserWorks/waterfox#823]
**Describe the bug**
Many of the [WordPress Dashicons](https://github.com/WordPress/dashicons) appear cropped or off-center when viewed with Waterfox 56.2.5 and Waterfox 56.2.6 on Mac OS X 10.8.5.

**To Reproduce**
1. Go to https://developer.wordpress.org/resource/dashicons 
2. Scroll down e.g. to section "Sorting"
3. See e.g. characters f139, f140, f141, f142 – some are barely visible, some aren't visible at all.

Reproducible on my system with a clean Waterfox 56.2.x installation after deleting all known Waterfox/Firefox/Mozilla cache and user folders.
Of course, the bug is also in effect when using the WordPress Admin Dashboard that makes excessive use of Dashicons.

**Expected behavior**
All icon characters should be fully visible. 

**Screenshots**
1. Waterfox 56.2.6 
![1_waterfox56_dashicons_bug](https://user-images.githubusercontent.com/46035925/50317423-d591ac00-04bb-11e9-9a43-67e720bd3cea.png)

2. Firefox ESR 52.9.0 ("hacked" to run on OS X 10.8.5)
![2_firefox52esr_dashicons_no_bug](https://user-images.githubusercontent.com/46035925/50317424-d591ac00-04bb-11e9-962f-169798052da9.png)

3. Safari 6.2.8
![3_safari6_dashicons_no_bug](https://user-images.githubusercontent.com/46035925/50317425-d62a4280-04bb-11e9-9a24-5938368d37e1.png)

**Desktop:**
 - OS: Mac OS X
 - Version: 10.8.5 Mountain Lion

**Additional context**
* Dashicons display correctly in other OS X 10.8.5 compatible browsers: Chrome 49, Firefox 45esr, Firefox 48, Firefox ESR 52.9.0 ("hacked" to launch and run on OS X 10.8.5, see screenshot 2), even in Safari 6.2.8 (see screenshot 3). Obviously it isn't a general Mac OS X 10.8.5 issue.

* Dashicons also display correctly using Waterfox 56.2.6 on MacOS 10.11.6 and MacOS 10.12.6.

**Comment by laniakea64** [comment]
Does disabling hardware acceleration help? - https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration

**Comment by schubidubi** [comment]
> Does disabling hardware acceleration help? - https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration

No. 
In fact, I still had hardware acceleration _disabled_ right now, after my earlier tests a couple of days ago.

**Comment by schubidubi** [comment]
This issue might be somewhat related though:
https://github.com/WordPress/dashicons/issues/277
But I'm neither a programmer nor a very skilled web designer, so what do I know… :)

**Comment by schubidubi** [comment]
Just noticed that the same kind of bug also appears on https://calendar.google.com which uses the "Material Icons Extended" font family: some icons are being displayed off-center and are barely visible. 
Again, no problem when using Chrome 49 or Firefox 52 ESR. So it's not a general Mountain Lion font display issue, only in Waterfox.

**Comment by grahamperrin** [comment]
Cross reference [Google Calendar Rendering : waterfox](https://www.reddit.com/r/waterfox/comments/alt6pm/google_calendar_rendering/)

**Comment by schubidubi** [comment]
It's been fixed in v56.2.10! Hooray!

**Comment by grahamperrin** [comment]
Thanks, feel free to close the issue (the button below).

**Comment by schubidubi** [comment]
I just noticed that something was apparently fixed in **WordPress 5.2.x** to make the icons appear correctly. It wasn't a Waterfox bugfix. On older installations of WordPress (or elsewhere), the display issue remains.
