### ISSUE TITLE
Freshly installed Waterfox missing spacers in Customize

### ISSUE THREAD

**Issue by IzzySoft** [BrowserWorks/waterfox#824]
**Describe the bug**

On a fresh machine running Win10 Enterprise, the *Customize* menu is not listing any separators or spaces -- so other than described in #312, I do not even see any. Is there any way to make them show up -- apart from using addons like CTR?

**To Reproduce**

1. Go to the Hamburger menu
2. Click on 'Customize'
3. See no Separator, Flexible Space, Fixed Space

**Expected behavior**

See Separator, Flexible Space, Fixed Space and be able to use them

**Screenshots**

![Customize](https://i.imgur.com/AOteqGG.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 56.2.5

**Additional context**

It's a fresh system, and a fresh install of Waterfox without any profile import.

**Comment by grahamperrin** [comment]
> Expected behavior
>
> See Separator, Flexible Space, Fixed Space and be able to use them

IIRC that is _not_ expected with Firefox 56.0.2, upon which Waterfox 56 was based. 

To minimise multiplication of discussions, please continue under #312

**Comment by IzzySoft** [comment]
@grahamperrin I deliberately opened a new issue as this is ***NOT*** the same – as I even pointed out. In my case, separator and spaces don't even show up. Do you really think the two are connected (same root cause)?

**Comment by Lorienna** [comment]
Spacers and separators disappeared from the customization palette with the introduction of Australis.

https://bugzilla.mozilla.org/show_bug.cgi?id=985308
https://bugzilla.mozilla.org/show_bug.cgi?id=873501

**Comment by mzso** [comment]
[**@IzzySoft**](https://github.com/IzzySoft) commented on [2018. dec. 23. 11:46 CET](https://github.com/MrAlex94/Waterfox/issues/824#issuecomment-449628126 "2018-12-23T10:46:18Z - Replied by Github Reply Comments"):
> [@grahamperrin](https://github.com/grahamperrin) I deliberately opened a new issue as this is _**NOT**_ the same – as I even pointed out. In my case, separator and spaces don't even show up. Do you really think the two are connected (same root cause)?

They only disappear when you open the customize view more than once. (switching away and back also counts) You can only open it once, and you can only add these items via the context menu.

**Comment by IzzySoft** [comment]
@Lorienna strange I saw them mentioned in some Waterfox documentation somewhere. Must have been pre-29 then.

@mzso I've tried it on a new profile, and didn't see them once.

**Comment by grahamperrin** [comment]
Yes, please continue under #312

**Comment by jabcreations** [comment]
This might help someone though you can add them via about:config. Here is my Waterfox Classic GUI. Go to about:config and then look for the key **browser.uiCustomization.state**. The code for the spacers is in the code below though I don't have half an hour to dump on answering something about ~3/4 years old to great depth.

Secondly you can also customize the width that they use via Classic Theme Restorer in it's "Custom css code" menu using the following:

/*** Toolbar Spacers ***/
toolbarspacer {min-width: 64px !important;}

Here is the bit for **browser.uiCustomization.state** in about:config:

{"placements":{"PanelUI-contents":["edit-controls","zoom-controls","new-window-button","e10s-button","privatebrowsing-button","save-page-button","print-button","history-panelmenu","fullscreen-button","find-button","preferences-button","add-ons-button","sync-button"],"status4evar-status-bar":["status4evar-status-widget","status4evar-progress-widget","status4evar-download-button","status4evar-legacy-widget"],"toolbar-menubar":["menubar-items","customizableui-special-spring21","web-developer-resize-toolbar","web-developer-disable-toolbar","web-developer-cookies-toolbar","web-developer-css-toolbar","web-developer-forms-toolbar","web-developer-images-toolbar","web-developer-information-toolbar","web-developer-miscellaneous-toolbar","web-developer-outline-toolbar","web-developer-tools-toolbar","web-developer-view-source-toolbar","web-developer-options-toolbar","ctraddon_window-controls"],"TabsToolbar":["tabbrowser-tabs","alltabs-button","ctraddon_tabs-closebutton"],"nav-bar":["ctraddon_appbutton","ctraddon_back-forward-button","ctraddon_reload-button","ctraddon_stop-button","home-button","ctraddon_bookmarks-menu-toolbar-button","downloads-button","ctraddon_history-button","new-tab-button","customizableui-special-spacer8","search-container","pg2-pasteandsearch-toolbar-button","customizableui-special-spacer10","_d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d_-browser-action","developer-button","_7a7a4a92-a2a0-41d1-9fd7-1e92480d612d_-browser-action","tabGroups-tabview-button","_c45c406e-ab73-11d8-be73-000a95be3b12_-browser-action","_e4a8a97b-f2ed-450b-b12d-ee082ba24781_-browser-action","_41f9e51d-35e4-4b29-af66-422ff81c8b41_-browser-action","ankpixiv_snca_net-browser-action","jid1-ybzygxhcbi9fha_jetpack-browser-action","jid0-urzplu7vtyef3iy7a2tpx21yj3a_jetpack-browser-action","livehosts_aioros_net-browser-action","foxyproxy_eric_h_jung-browser-action","flashgot-media-tbb","abp-toolbarbutton","_174b2d58-b983-4501-ab4b-07e71203cb43_-browser-action","action-button--keybinderfailcl-keybinderoolbarutton","firebug-badged-button","cors-everywhere_spenibus-browser-action"],"PersonalToolbar":["urlbar-container","ctraddon_go-button","pg2-pasteandgo-toolbar-button","feed-button","personal-bookmarks","web-developer-render-mode-statusbar","web-developer-css-statusbar"],"ctraddon_addon-bar":["ctraddon_addonbar-close","customizableui-special-spring1","ctraddon_statusbar"],"web-developer-toolbar":["web-developer-javascript-statusbar"],"addon-bar":["addonbar-closebutton","status-bar"],"ctraddon_extra-bar":["customizableui-special-spring2"]},"seen":["developer-button","_d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d_-browser-action","webide-button","status4evar-legacy-widget","_7a7a4a92-a2a0-41d1-9fd7-1e92480d612d_-browser-action","tabGroups-tabview-button","_c45c406e-ab73-11d8-be73-000a95be3b12_-browser-action","_e4a8a97b-f2ed-450b-b12d-ee082ba24781_-browser-action","ankpixiv_snca_net-browser-action","_41f9e51d-35e4-4b29-af66-422ff81c8b41_-browser-action","jid1-ybzygxhcbi9fha_jetpack-browser-action","jid0-urzplu7vtyef3iy7a2tpx21yj3a_jetpack-browser-action","livehosts_aioros_net-browser-action","foxyproxy_eric_h_jung-browser-action","abp-toolbarbutton","_174b2d58-b983-4501-ab4b-07e71203cb43_-browser-action","jid1-oy8xu5bskzqa6a_jetpack-browser-action","action-button--keybinderfailcl-keybinderoolbarutton","zakius_polly-browser-action","cors-everywhere_spenibus-browser-action"],"dirtyAreaCache":["PersonalToolbar","nav-bar","TabsToolbar","toolbar-menubar","PanelUI-contents","ctraddon_addon-bar","addon-bar","ctraddon_extra-bar","status4evar-status-bar","web-developer-toolbar"],"currentVersion":6,"newElementCount":3728}
