### ISSUE TITLE
Compact Dark theme does not work on Web eveloper tools

### ISSUE THREAD

**Issue by shiftyshady** [BrowserWorks/waterfox#825]
**Describe the bug**

**To Reproduce**
1. Go to We

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by laniakea64** [comment]
Duplicate of https://github.com/MrAlex94/Waterfox/issues/826
