### ISSUE TITLE
Compact Dark theme does not work on Web Developer Tools

### ISSUE THREAD

**Issue by shiftyshady** [BrowserWorks/waterfox#826]
**Describe the bug**

**To Reproduce**
1. Go to We

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shiftyshady** [comment]
Github does not work well on my browser (sorry I am not using Internet Explorer or Edge, I prefer Waterfox), so I cant edit previous comment (pressed enter by mistake). I'll explain here:
Enable Dark compact theme go to Web Developer Tools: Ctrl Shift I
It should be dark as on Firefox Dev Ed 56, but it isnt.

**Comment by laniakea64** [comment]
Devtools theme setting is separate from browser theme setting.  You need to go into devtools settings to change the devtools theme to dark.

**Comment by grahamperrin** [comment]
![image](https://user-images.githubusercontent.com/192271/50454520-fafd3a80-093f-11e9-8e82-b2a7d788302d.png)

**Comment by shiftyshady** [comment]
Thanks.
