### ISSUE TITLE
Appcrash xul.dll on one site

### ISSUE THREAD

**Issue by Vallek** [BrowserWorks/waterfox#828]
Waterfox always crashing on [this page](https://www.24a11y.com/2018/i-threw-away-my-mouse/). In SafeMode too. 
 
Problem signature:
  Problem Event Name:       APPCRASH
  Application Name:         waterfox.exe
  Application Version:      56.2.4.6868
  Application Timestamp:    5bd8d1b4
  Fault Module Name:        xul.dll
  Fault Module Version:     56.2.4.6868
  Fault Module Timestamp:   5bd8d266
  Exception Code:           c0000005
  Exception Offset:         000000000183334d
  OS Version:               6.1.7601.2.1.0.256.1
  Locale ID:                1049
  Additional Information 1: ba56
  Additional Information 2: ba560ca4dd3f36c7f1da922dd8d9a27b
  Additional Information 3: 5293
  Additional Information 4: 52935a7c36df5991310388bed13b17a4

Firefox and Chrome aren't crashing on this page.

**Comment by grahamperrin** [comment]
Not crashing with 56.2.6 on FreeBSD-CURRENT. 

Please try: 

1. exit Waterfox
2. uninstall Waterfox
3. restart Windows
4. use the full installer for Waterfox 56.2.6

Then if the crash is reproducible, and if hardware acceleration is enabled: try disabling acceleration.
