### ISSUE TITLE
[Bug] Youtube video playback corruption on variants of S3 and S4 due to no blacklist for adaptive playback

### ISSUE THREAD

**Issue by AjvarXX** [BrowserWorks/waterfox#829]
**Describe the bug**
Mozilla team introduced adaptive playback feature in 53-rd version and that made unplayable videos on american variants of S4 and S3 Galaxy phones.
Now this is an essence of I hate Mozilla for and their products. They manually added few exceptions from bugreports and called it a day... instead of simply googling the full model list of american phone variants! :facepalm Even though devs figured out that reason was behind SOC in american phones of S3 and S4 models! FFS.
The exceptions were filled in  mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/HardwareCodecCapabilityUtils.java
Unlisted phones that have this problem are: SAMSUNG-SGH-T999, SGH-T999L, SGH-L720. Probably SGH-L720T too.

**To Reproduce**
1. Have an USA variant of S4 or S3 which is unlisted in exception...
2. Try watching youtube video in browser
3. See huge grey cubes instead of a picture.

**Expected behavior**
A clear video image.

**Screenshots**
Same like this:
![ff](https://user-images.githubusercontent.com/9568793/50500930-32add480-0a5d-11e9-972e-cb5756d1350e.png)

**Smartphone (please complete the following information):**
 - Device: Qualcomm Snapdragon based Samsung Galaxy S4 or S3 (american variants)
Unlisted phones that have this problem are: SAMSUNG-SGH-T999, SGH-T999L, SGH-L720. Probably SGH-L720T too.
 - OS: Android 4.4 and 5.0
 - Version since Firefox 53

**Additional context**

Now, the finicky part is that these Galaxy S4 and S3 phones are 32 bits so technically are discontinued... THAT is a reason why I informed about this bug here instead of bugzilla site is because mozilla fixes will not help owners of these S4 and S3 phones because they don't receive newer version of Waterfox. For fixes to be delievered it is either needed for newer Waterfox 56.1 version or developing a compatibility of newer versions of Waterfox for 32 bit phones.

More links:
https://hg.mozilla.org/releases/mozilla-beta/rev/0884adb687d1
https://bugzilla.mozilla.org/show_bug.cgi?id=1360626#c38

**Comment by MrAlex94** [comment]
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

Sorry but Waterfox has almost always been for 64-Bit devices where available. I don't have the man power to support 32-Bit phones.
