### ISSUE TITLE
50.0.2 crashes immediately on OSX 10.11.6

### ISSUE THREAD

**Issue by baracudda** [BrowserWorks/waterfox#83]
I just installed the latest update, 50.0.2, and now I cannot open Waterfox at all. =(

**Comment by ghost** [comment]
Same here, so went back to WF 50.0, works perfectly. In Preferences/Advance/Updates, just checked "Do not check for updates" until this situation is fixed. Mr. Alex always knows how to fix this. I am using OSX 10.8.5

**Comment by pixturesk** [comment]
Just forgot to mention, I am using OSX 10.8.5

**Comment by MrAlex94** [comment]
Sorry about that again. Does [this ](https://storage-waterfox.netdna-ssl.com/releases/osx64/installer/Waterfox%2050.0.2.1%20Setup.dmg) build fix it?

**Comment by ghost** [comment]
Perfect again Mr. Alex. I'll reset to check for updates automatically again. Thanks, you are the greatest!!

**Comment by ghost** [comment]
Also WF 50.0 was slow to bootup, lots of spinning icons, some pages loading quite slowly. Now everything is quick again.

**Comment by baracudda** [comment]
Yes, that build fixes the problem.  Thanks @MrAlex94 !
