### ISSUE TITLE
Site: /waterfox/all/ Oh Noes! An error occurred. Try back later!

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#831]
With Firefox or Waterfox on FreeBSD-CURRENT: 

1. https://blog.waterfoxproject.org/waterfox-56.2.6-release-download
2. [Waterfox Downloads](https://www.waterfoxproject.org/en-US/waterfox/new/?scene=2)
3. click here
4. https://www.waterfoxproject.org/en-US/waterfox/all/

### Expected

5. a list of downloads

### Actual result

> Oh Noes!
> 
> An error occurred. Try back later!

![image](https://user-images.githubusercontent.com/192271/50562645-7fb7d200-0d0d-11e9-955c-3e1e5915ab78.png)

----

Meta, tracking: #582

**Comment by IzzySoft** [comment]
Strike OS limitation. Same "Oh Noes" with Waterfox on Win 10 on the URL at number 4.
