### ISSUE TITLE
Waterfox 56.2.5 on Windows still thinks it's up-to-date

### ISSUE THREAD

**Issue by IzzySoft** [BrowserWorks/waterfox#833]
**Describe the bug**
Though 52.2.6 is out for quite a while, the Windows version is not updating -- because of https://www.waterfoxproject.org/update/win64/56.2.5/en-US/release/update.xml being empty. Could that be filled with the necessary details, so the update is taking place?

**To Reproduce**

1. Go to *Help > About Waterfox"
2. See "56.2.5" and, below that, "Waterfox is up to date"
3. Try `https://storage-waterfox.netdna-ssl.com/releases/win64/update/waterfox-56.2.6.en-US.win64.complete.xz.mar` and see it's there
4. According to [the blog](https://blog.waterfoxproject.org/waterfox-56.2.6-release-download), 52.2.6 was released on 2018-12-18 (more than 2 weeks ago)

**Expected behavior**

Seeing the update available and being able to apply it.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Version 56.2.5

**Comment by Ibuprophen** [comment]
I've also got a similar/same issue on my Windows 8.1 Pro x64 PC. 

It has been quite a while since any updates have been reflected as well. 


~Ibuprophen

**Comment by grahamperrin** [comment]
> … because of https://www.waterfoxproject.org/update/win64/56.2.5/en-US/release/update.xml being empty …

Nice catch, thanks! Not editable by me, sorry. 

Meta/tracking: #582

Reference: https://github.com/MrAlex94/Waterfox/blob/1b45a31324716b7069da1cdc4e7b6c4f7dcb09ee/browser/app/profile/firefox.js#L176

**Comment by IzzySoft** [comment]
Thanks, @grahamperrin! Would it help to modify that URL in about:settings to point to staging (and if so, what would be the URL)? I already considered copying the file from the previous release, adjusting it, then putting it on one of my web servers and finally point Waterfox there – which would certainly work, but not help anyone except me…

If it takes snick… ahem, a bit longer: would it work to just download the latest version manually and install it over the existing one? Just wondering because the integrated update uses a completely different file.

**Comment by grahamperrin** [comment]
I'm not aware of a stage-related URL. 

Staging is mentioned at lines 168–174 of https://github.com/MrAlex94/Waterfox/blob/1b45a31324716b7069da1cdc4e7b6c4f7dcb09ee/browser/app/profile/firefox.js#L168 and there's an `#ifdef` for `XP_WIN` but I don't know enough about the code to tell whether versions of Windows _other_ than XP are treated differently. 

about:config?filter=app.update.staging.enabled 

– what's your default and what's your version of Windows?

**Comment by grahamperrin** [comment]
> … would it work to just download the latest version manually and install it over the existing one? …

I assume so. 

Sometimes in Reddit I suggest uninstalling the application then restarting Windows before using a full installer, but where those suggestions are made it's usually in cases of trouble. 

If Waterfox is essentially **trouble-free** but outdated, I imagine no harm from leaving the outdated version in place before using the full installer. Just (common sense) exit Waterfox before launching the installer.

**Comment by IzzySoft** [comment]
> about:config?filter=app.update.staging.enabled

Default and current setting: false; Windows 10 (not my own machine or it would rather be Linux 😉)

Thanks for the advice on the "general installer", I'll keep that in mind. Version is not that horribly outdated (one digit in the patch level) so I don't feel urgency. But if it's not solved with the next update, this information might come in handy. Had I installed one week later, the question hadn't arisen…

What's the chance of getting this fixed? Shouldn't be that big effort to create and place that file, just needs "access rights" and knowing the correct content 😄.

**Comment by Ibuprophen** [comment]
@grahamperrin, since this issue has/is being fixed, should I be manually updating the Browser for the applied fixes? 

It just seems as though, if the currently installed release can't/won't be able to see the updates right now, it may require that it be done manually and let the Browser take it from there. 

Thank you very much! :-) 


~Ibuprophen

**Comment by IzzySoft** [comment]
@ibuprophen1 

> since this issue has/is being fixed

Did I miss something? Or did you mean "until" instead of "since"?

Apart from that, I was hoping @MrAlex94 would just update [that one XML file](https://www.waterfoxproject.org/update/win64/56.2.5/en-US/release/update.xml) (and probably also all previous once, which still point to 56.2.5; I've checked that back to 56.2.0; 56.1.* and 56.0.* even point to 56.2.3), which then would really solve this issue. Currently, none of the Windows users will receive this update, though it is clearly available.

**Comment by grahamperrin** [comment]
Cross reference https://www.reddit.com/r/waterfox/comments/a7s6j4/-/edpdvtt/?context=2

**Comment by IzzySoft** [comment]
Thanks to whoever fixed that file and hence solved this issue: My Waterfox just updated to 56.2.6 \o/ 🎉

**Comment by IzzySoft** [comment]
We have the very same issue again: `https://www.waterfox.net/update/win64/56.2.12/en-US/release/update.xml` and below still point to 56.2.13, and `update.xml` for 56.2.13 is empty – while 56.2.14 has been published as security release 2 days ago. Have they been forgotten again, or is this intentional?
