### ISSUE TITLE
Holiday Wishes...

### ISSUE THREAD

**Issue by Ibuprophen** [BrowserWorks/waterfox#834]
I almost forgotten about wishing @MrAlex94 and @grahamperrin Family and Friends the Best Wishes, Happy Holidays and a Happy New Year!!!

I hope this year ends even more Uplifting and Promising as the last (bumpy) year has ended with!!

Take care My Friend's.

~Ibuprophen

**Comment by grahamperrin** [comment]
Thanks! Season's greetings, all. Here's to a healthy, happy and Waterfox Sixty 2019 :-)

**Comment by IzzySoft** [comment]
Uh, where? And will it update? 😈 

But yeah, happy new year to all 🎉 🎆 🥂

**Comment by DI555** [comment]
Yes, many New Year wishes to Alex!!! 
Hope to see android 5+, and others builds also, here on github in 'releases' ! Will it)?

**Comment by Ibuprophen** [comment]
I'm just going to close this before it morphs from Holiday Wishes to a Misc Monster. LMAO! 😨


~Ibuprophen

**Comment by MrAlex94** [comment]
Sorry I missed this, was busy at various conferences and holidays.

Happy New Year everyone! Here's to the best one yet 🌊
