### ISSUE TITLE
Release for XP/Vista

### ISSUE THREAD

**Issue by Mahabarata** [BrowserWorks/waterfox#835]
Hi,

On your official website (waterfoxproject.org), when we click on the button "windows (XP/Vista)", nothing appends except that the webpage is reloaded (/en-US/waterfox/new/?scene=1)

Best regards

**Comment by MrAlex94** [comment]
Hi,

Where are you seeing this button? Do you have a screenshot by any chance?

Thanks,
Alec

**Comment by Mahabarata** [comment]
I understand your question ; when I go to the main page to download Waterfox, I have not the same result in Opera and in Firefox !
Opera =
![waterfoxopera](https://user-images.githubusercontent.com/3121119/50669366-c833f180-0f92-11e9-93cd-ed06d926469a.jpg)
Firefox =
![waterfoxfirefox](https://user-images.githubusercontent.com/3121119/50669372-cbc77880-0f92-11e9-92fa-9f612410e7af.jpg)

In Firefox I have an addon to stop javascript : I just desactived it and the page like the one for Opera is now visible.

So the pb of the button is solved.
But not my issue : I need a version of Waterfox for XP/Vista (not for me but for a friend with an old computer) : is there a release of this kind somewhere ?

Best regards

**Comment by grahamperrin** [comment]
> solved

Thanks, you can close this issue. 

----

> …  not my issue : I need a version of Waterfox for XP/Vista …

[Site: rationalise the platform-specific offerings · Issue #467 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/467)

– I'll add something there.

**Comment by Mahabarata** [comment]
Ok, you can close
