### ISSUE TITLE
New tab top-sites icons are blank in WF 56.2.6 on MacOs 

### ISSUE THREAD

**Issue by jrobert-gh** [BrowserWorks/waterfox#836]
**Describe the bug**
After updating Waterfox 56.2.5 -> 56.2.6, the top-sites displayed on a new tab have blank images. It doesn't matter whether they are pinned or unpinned, whether I again visit the site with them pinned or unpinned; they remain blank.

**To Reproduce**
1. In 56.2.5, create a new tab page with top-sites displayed. Notice the top-site icons contain page-images.
2. Upgrade to 56.2.6.
3. Open a new-tab. **Notice that the top-site icons are blank.
4. Click one of the top-site icons to visit that site. The browser visits that site.
5. Again, open a new tab. **Notice that the site icon you used in step 4 remains blank.

6. Revert Waterfox to 56.2.5. Notice that the top-site icons' behavior is restored.

**Expected behavior**
The site icon should have retained - or should regain - a page image.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14.2

**Additional context**

**Comment by grahamperrin** [comment]
Reproducible with 56.2.6 in safe mode on 10.14.2?

- about:support

Reproducible with a new profile?

- about:profiles

Not reproducible with 56.2.6 on FreeBSD-CURRENT.

**Comment by MrAlex94** [comment]
I can't reproduce this on macOS 10.14.3/Waterfox 56.2.6 either.

**Comment by jrobert-gh** [comment]
It must have been a failed update process the first time around. :-(  I re-updated v56.2.5 -> v56.2.6 and I can't reproduce it either - working properly now. Sorry for the distraction.
