### ISSUE TITLE
Apple Music Previews can't play because of DRM issue

### ISSUE THREAD

**Issue by grr** [BrowserWorks/waterfox#838]
**Describe the bug**

Track previews won't play on the Apple Music Preview site.

**To Reproduce**
1. Go to https://itunes.apple.com/us/album/electro-swing-elite-compilation-2015/1052790660
2. an icon appears in the url bar to "manage use of drm software", hovering shows the warning "Some audio or video on this site uses DRM software, which may limit what Waterfox can let you do with it."
3. clicking on the Configure drm shows that the "play drm content" option is already enabled
4. Click any of the tracks to play preview and they won't play.

**Expected behavior**

Preview of track should play when clicked.

Opening the web console when clicking on preview will display the link to the m4a it's attempting to play (example: https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/Music69/v4/bf/2b/90/bf2b906c-d0a0-9b4c-cb6f-1c7d88e8649b/mzaf_3553155826547053132.plus.aac.p.m4a). And opening that link directly it plays fine without any drm issue.

**Desktop (please complete the following information):**
 - OS: macOS Sierra (10.12.6)
 - Version 56.2.6 (all addons disabled)

**Comment by grahamperrin** [comment]
> Preview of track should play when clicked.

Works for me: 

- without DRM with Waterfox 56.2.6 on FreeBSD-CURRENT
- before installing DRM with Waterfox 56.2.6 on Kubuntu 18.10
- after activating DRM on Kubuntu
- after deactivating DRM on Kubuntu (ignore the DRM-related banner). 

On FreeBSD-CURRENT: if I temporarily change my UA string for the `itunes.apple.com` domain to `Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:56.0; Waterfox) Gecko/20100101 Firefox/56.2.6` and reload the page, then above the playlist there appears a button, which is not applicable on Linux (or FreeBSD): 

> Listen on **Apple Music**

– and still, previews work without DRM.

**Comment by grahamperrin** [comment]
> 3. clicking on the Configure drm shows that the "play drm content" option is already enabled

Does the banner (at the Apple Music Preview page) persist after reloading the page?

Is the issue reproducible with a new profile? 

- about:profiles

**Comment by grr** [comment]
> > 1. clicking on the Configure drm shows that the "play drm content" option is already enabled
> 
> Does the banner (at the Apple Music Preview page) persist after reloading the page?

yes, but it's not the initial need drm banner, it's an icon indicating a problem with drm.

<img width="361" alt="screen shot 2019-01-10 at 00 32 29" src="https://user-images.githubusercontent.com/690894/50950339-4569d580-146f-11e9-93af-178a03c499d4.png">

> Is the issue reproducible with a new profile?
> 
> * about:profiles

after the new profile downloads the plugin, playback does work, but the drm problem icon is still present.

i checked about:config for both my default profile and the new profile and all widevine settings are identical. i toggled the drm preference, and that forced the plugin to be reinstalled, but the issue still persists.

**Comment by grr** [comment]
repeated the process a few times and now the plugin works properly on my default profile, though it still displays the drm icon. i'll close this ticket since my issue is resolved. don't know if another issue needs to be created for the drm icon.
