### ISSUE TITLE
rel="noreferrer" leaks referer on links with target="_blank" when e10s is enabled

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#839]
Waterfox 56.2.6
new profile

**Steps to reproduce**

1) put these pages up on a server -

noreferer-test.html
```
<!doctype html>
<a rel="noopener noreferrer" href="referer.php">Left Click Me (same window)</a>
<br/>
<a rel="noopener noreferrer" target="_blank" href="referer.php">Left Click Me (new window)</a>
```

referer.php
```
<!doctype html>
<div>
<?php
if (isset($_SERVER['HTTP_REFERER'])) {
  echo 'You came from <span>' . $_SERVER['HTTP_REFERER'] . '</span>';
}
else {
  echo 'I dont know where you came from.';
}
?>
</div>
```

2) visit the `noreferer-test.html`

3) Left-click each of the two links in turn, and compare the results.

**Expected results**

Both links should result in 'I dont know where you came from'

**Actual results**

The link with `target="_blank"` leaks the referer when e10s is enabled.

@MrAlex94 This can be fixed by porting the patches from Mozilla bug 1420702 .  I have tried to do it on top of patches from https://github.com/MrAlex94/Waterfox/pull/832 , and so far it seems to be working, so when/if that pull request gets merged I can open a pull request for this.

**Comment by grahamperrin** [comment]
Thanks

Mozilla bug [1420702 - Referrer policy ignored in pinned tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1420702)

> RESOLVED FIXED in Firefox 59

----

> … patches from Mozilla bug 1420702 … 

Towards a PR/merge: 

- https://github.com/MrAlex94/Waterfox/commit/1cbe6d16c5e4f6a401d0b43637d6c94f169a6046
- https://github.com/MrAlex94/Waterfox/commit/51c703955bd7b69c52971d7c3ed2b84ebfc37e3d

**Comment by laniakea64** [comment]
Fixed by https://github.com/MrAlex94/Waterfox/commit/1aed8506a11790c1315965ec8da817bf93b95486 , thanks! :smiley:
