### ISSUE TITLE
Memory overflow with Greasymonkey and mouseover image viewer script

### ISSUE THREAD

**Issue by Deldrinov** [BrowserWorks/waterfox#84]
I'm using Greasymonkey with https://greasyfork.org/en/scripts/404-mouseover-popup-image-viewer and I've noticed mousing over gifv in this comment: http://imgur.com/gallery/Fq14oec/comment/832012414 causes rapid memory increase to the point of using swap file. Video in its own tab plays correctly.

I've tested addon and script on Firefox 50.0.2 on another computer and there was no issue.

**Comment by MrAlex94** [comment]
@Deldrinov, does this still occur?

**Comment by MrAlex94** [comment]
No response, please re-open if needed.
