### ISSUE TITLE
Cannot upload new Waterfox Add-ons to ATN

### ISSUE THREAD

**Issue by RealRaven2000** [BrowserWorks/waterfox#840]
I am an Add-on developer who does mainly Thunderbird add-ons but 3 classic add-ons that are also compatible with Waterfox. Although they are, these are not shown on AMO (addons.mozilla.org) and cannot be updated either.

When I follow the link to Add-ons (from the waterfox project page) and then look for my (Waterfox Compatible) Extensions QuickPasswords and Zombie Keys, no results are shown - this is not useful. On upload in developer center, the error message simply states: "Pleeasee complete your add-on by adding or version or missing meta data. When I try to upload a new version there is only 1 validation error "Legacy extensions are no longer supported in Firefox" so there is basically no way to support my Waterfox users with updates.

**Comment by hawkeye116477** [comment]
> there is basically no way to support my Waterfox users with updates

You can also host it in GitHub Releases and updates also can be on GitHub. You'll just need to follow instructions on `https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Updates#Enabling_updates_to_your_extension`.

**Comment by ilu33** [comment]
On waterfoxproject,org is a link to AMO but as we all know classic addons got kicked off that site. Next to it: "Classic add-on archive coming soon!" "Soon" might be sooner or later, there's only so much one single programmer can do. Find the discussion here: https://github.com/MrAlex94/Waterfox/issues/303 and offer help if you can.
