### ISSUE TITLE
Incomplete WebRTC-implementation, missing event RTCPeerConnection.oniceconnectionstatechange

### ISSUE THREAD

**Issue by esrat** [BrowserWorks/waterfox#845]
Hi,
in a German forum (https://threema-forum.de/thread-4418-post-42589.html) it was currently stated by a developer that Waterfox is implementing WebRTC, but is not implementing the RTCPeerConnection.oniceconnectionstatechange event.
This prohibits the use of Waterfox as a fallback for Firefox in the case of Threema-Web. (Threema [https://threema.ch/en] is a secure mobile chatting app which uses WebRTC to bind an open-source-browser-client to the actual app running on some mobile device [preferable] within the same local Wifi).
Missing this event, it seems that the state of the connection is unknown to the browser app. So the most critical functionality (sending messages) will not be allowed.

Is it possible to support the event RTCPeerConnection.oniceconnectionstatechange in Waterfox?

EDIT:
The post in the German forum has moved to: https://threema-forum.de/index.php?thread/4418-threema-web/&postID=42579#post42579

**Comment by grahamperrin** [comment]
[RTCPeerConnection.oniceconnectionstatechange | MDN](https://developer.mozilla.org/docs/Web/API/RTCPeerConnection/oniceconnectionstatechange) shows full support in Firefox 22. 

With Waterfox 56.0 based on Firefox 56.0.2, I wonder what might cause the situation in the German forum (with Waterfox 56.2.6, presumably) to occur. 

A platform-specific issue? I wonder …

**Comment by esrat** [comment]
The platform is Windows (e.g. verified with Windows 7 64 bit).
Their browser app works fine with the latest Firefox ESR (also 64 Bit) - and it worked fine with older versions until the latest update. The discussion in the German forum started when they had raised their minimum requirements for the browser app to this latest Firefox ESR to be able to clean out some of their old code. This broke the compatibility with older Firefox versions, on which some users are still depending (for several reasons, e.g. not willing or able to discard XUL-based add-ons).
At this point, Waterfox came into discussion as an alternative. It is working fine - despite the one issue that you cannot send any messages!
The developer in the German forum mentions that functionality this was never done differently before. And yes, trying their older versions from the archive with Waterfox, they always work fine - despite not being able to send anything!

**Comment by esrat** [comment]
Just a thought of mine (not having any deeper insight):
Maybe the support of this event was removed according to Waterfox's rules?

In this case, could it be added again?

**Comment by grahamperrin** [comment]
> …  Maybe the support of this event was removed according to Waterfox's rules? …

https://github.com/MrAlex94/Waterfox/search?q=RTCPeerConnection.oniceconnectionstatechange&unscoped_q=RTCPeerConnection.oniceconnectionstatechange no matching commits, so I doubt it. 

----

It may help to find the commit(s) through which Firefox gained compatibility. 

As mozregression https://mozilla.github.io/mozregression/ can be used to find a _regression_, so I guess it might also be used to help find an _enhancement_ …

**Comment by esrat** [comment]
Well, could someone do this?

I have no experience in this and sadly also no time to get familiar with it.
The issue stays unresolved. The German forum "concludes" that keep using Firefox ESR 52 is a bad idea, obviously. But there will be no support for the Waterfox browser since the problem was identified within the browser!

**Comment by grahamperrin** [comment]
My next use of mozregression will be for a privacy bug that affects both Firefox and Waterfox …

**Comment by MrAlex94** [comment]
Will take a look at this.

**Comment by esrat** [comment]
Is there any progress with this issue?

**Comment by esrat** [comment]
Hi,
I just want to add that the problem persists with the newest portable version of 56.2.8.
I am only using portable versions and back in January (when I opened this issue) there was only the version 56.2.6 available.
Even so the version 56.2.8 claims to got WhatsApp Web working, this seems to have no effect on Threema Web. You still cannot send messages!

**Comment by esrat** [comment]
Another sad update:
Nothing seems to have changed with the newest version of 52.2.10.
The problem still persists. It is impossible to send messages with Threema Web; no matter if you change the useragent to Firefox or not.

**Comment by esrat** [comment]
I could have copied my last message from nearly half a year ago. ... Also version 52.2.14 does not seem to implement the missing parts of WebRTC.
You still cannot send any messages in Threema Web.

Is really someone "looking into this"? Or am I soliloquizing?

**Comment by grahamperrin** [comment]
Meta, tracking: #538
