### ISSUE TITLE
VirusTotal Scan Results

### ISSUE THREAD

**Issue by ssavva05** [BrowserWorks/waterfox#846]
**Describe the bug**
An engine in VirusTotal mark the windows executable as malicious. This is might be False Positive. If there is any way to update the result please do it.

**Comment by MrAlex94** [comment]
What is it marking? Happens a few times, not sure what to do to get over it tbh apart from reporting to them.

**Comment by grahamperrin** [comment]
### Zillya

Seeking _VirusTotal_ (not Virus Total) finds https://www.reddit.com/r/waterfox/comments/ado37m/-/edl67bq/ ▶ https://www.reddit.com/r/waterfox/comments/9pazyj/-/e87p77v/

From the latter: 

>> … One of the Mozilla bugs refers to UXP, …

**Comment by ssavva05** [comment]
> 
> 
> What is it marking? Happens a few times, not sure what to do to get over it tbh apart from reporting to them.

As mentioned in the previous post the results is that: https://www.virustotal.com/#/file/075193608495547eca6678d37cbad3b73301328d775d37240590cc40236e68a1/detection

Is it possible to change the packing method (not use UXP) or change the 7zS.sfx naming without brake anything in the installer?

**Comment by grahamperrin** [comment]
> … reporting to them.

I stumbled across this, sent a few months ago: 

![2018-07-10](https://user-images.githubusercontent.com/192271/51891822-2c7e8100-2398-11e9-9adf-df76be412ea7.png)

From my e-mail: 

>> … matches a file with a different name,
>> 
>> 7zS.sfx
>> 
>> – with a report of Trojan.GenericKD.Win32.119950 from Zillya alone.
>> 
>> Please, can you investigate? Confirm that it's a false positive?
>> 
>> Thank you.

Unless I'm missing something: no response from Zillya. 

Given the non-response, I have posted a caution: https://redd.it/akxsco

**Comment by MrAlex94** [comment]
Odd, they're just reporting
https://github.com/MrAlex94/Waterfox/blob/master/other-licenses/7zstub/firefox/7zSD.sfx
as a Trojan? It's used by a lot of programs. Maybe because it's similar to
Firefox's?

**Comment by grahamperrin** [comment]
<strike>No _Zillya_ today at `https://www.virustotal.com/#/url/79686502c0369051d1b7748c63a54b56c379cf69b679a045711322d437d102db/detection`</strike>

Sorry, ignore that. It was a URL scan, not a file scan. 

----

Instead, for **Waterfox 56.2.6 Setup.exe**: 

- https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.2.6%20Setup.exe

> SHA-256 a6a010673ed80fc77c8f541d987dbc2e8d4a2d80099bd57b0952126640eebcd4
> 
> File name 7zS.sfx

**Comment by grahamperrin** [comment]
Also https://www.waterfox.net/blog/waterfox-2020.03-release/#commento-comment-card-122af93ad3d00ff07df86b66f8f4cebf1084f355579c0e0c0397ecd1c819336c re: Cylance and Emsisoft.
