### ISSUE TITLE
Disconnects bugging Rabb.it after around 78 seconds (maybe with 30 seconds of inactivity)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#847]
Whilst watching, listening at sites such as Rabbit <https://www.rabb.it/>: 

- disconnections may occur every **78 (seventy-eight) seconds**. 

Reproducible with Waterfox 56.2.6 on (unsupported) FreeBSD-CURRENT. 

### Rationale for this bug report

From [#21312 (Memory and file descriptor leaks in programs that use go-webrtc) – Tor Bug Tracker & Wiki](https://trac.torproject.org/projects/tor/ticket/21312) (2017-01-25, closed defect (fixed), closed 2018-03-21) I _assume_ that the periodic disconnects with Waterfox involve _go-webrtc_. Assumption based on the second of these phrases (with added emphases): 

- <https://trac.torproject.org/projects/tor/ticket/21312#comment:41>, 

> Well, `CGO_DestroyPeer` doesn't appear to be thread-safe; so let's fix that. The client is currently defaulting to 1 concurrent peer, which would explain why it doesn't hit this issue, if that's the cause. The proxies, which are handling multiple peers, each of which are voluntarily exiting every **30s** of inactivity, seem like they could be hitting some contention there, but possibly not at the rate things are failing?

- from <https://trac.torproject.org/projects/tor/ticket/21312#comment:43>, 

> … Potentially of note: the abort happens immediately after the first `OnClose` channel. The client had been connected for **78 seconds**. 
> …

### Discussions

[Firefox 56.2.2 Causing disconnect issues with Rabb.it : waterfox](https://www.reddit.com/r/waterfox/comments/90tyn3/firefox_5622_causing_disconnect_issues_with_rabbit/) (sic – probably _Waterfox_ 56.2.2 (there was no such version of Firefox) (2018-07-22, archived)

[Waterfox 56.2.5 not working with Rabb.it Version 56.2.0 does : waterfox](https://www.reddit.com/r/waterfox/comments/a65psj/waterfox_5625_not_working_with_rabbit_version/) (2018-12-14)

> … constant disconnects …

Technically, I doubt that the disconnects are _constant_; I assume that they are periodic. Probably disconnected after 78 seconds although re: the first of the quotes above I guess that other timings may be observed/perceived. 

From <https://www.reddit.com/comments/a65psj/-/ef8mqcq/>: 

> … can you reproduce the issue with Rabbit with Firefox ESR 60?

### Meta/tracking

#538

**Comment by grahamperrin** [comment]
https://trac.torproject.org/projects/tor/ticket/21312#comment:66 from me seeks advice.

**Comment by arlolra** [comment]
@grahamperrin Sorry, but it doesn't appear as if Waterfox is using go-webrtc.

**Comment by grahamperrin** [comment]
@arlolra thanks for investigating. 

----

@MrAlex94 and all: other possible explanations for Rabb.it ceasing to work with Waterfox at/around the time of release of 56.2.2? 

For me the exactness (78 seconds) was remarkable but if you think it'll help to be less specific, I can remove this from the title of the issue.

**Comment by arlolra** [comment]
> For me the exactness (78 seconds) was remarkable but if you think it'll help to be less specific, I can remove this from the title of the issue.

I grepped the webrtc source for a constant timer of `78` but didn't come up with anything.

The [log from that report](https://trac.torproject.org/projects/tor/attachment/ticket/21312/proxy-go-abort.20180314.log) shows a user's session with `48s` of activity, followed by `30s` of inactivity after which a timer killed the connection.  Alas, it may have just been a coincidence.

**Comment by grahamperrin** [comment]
https://www.rabb.it/ ([archived](https://web.archive.org/web/20191001194218/https://www.rabb.it/)) ▶

- [Kast Acquires Key Assets From Rabbit](https://kast.gg/kast-acquires-rabbit-assets-press-release.html)
- [A Message to the Rabbit Community](https://kast.gg/message-to-rabbit-community.html)
- [Kast - Share your experiences live](https://kast.gg/)

– an application, no longer web-based. This issue is redundant.
