### ISSUE TITLE
Library window (History, Downloads, All Bookmarks …) fails to open with some locales

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#849]
https://www.reddit.com/comments/al8qdn/-/efe5uy3/ observed: 

> (56.2.7) has a problem with the german localizaion. XML Parsing Error under the download tab and the chronicles. Switching back to 56.2.6 and all is fine.

The bug is reproducible with _French - Français_ in 56.2.7 on FreeBSD-CURRENT. 

Bugged: 

- **Afficher l'historique** and its shortcut <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>H</kbd> | <kbd>Control</kbd>-<kbd>Maj</kbd>-<kbd>H</kbd> 
- **Afficher tous les marque-pages** and its shortcut <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>O</kbd> | <kbd>Control</kbd>-<kbd>Maj</kbd>-<kbd>O</kbd> 

In both cases: 

```text
Erreur d’analyse XML : entité non définie
Emplacement : chrome://browser/content/places/places.xul
Numéro de ligne 344, Colonne 13 :
            <treecol label="&col.parentfolder.label;" id="placesContentParentFolder" anonid="parentFolder" flex="1" hidden="true"
------------^
```

### Meta/tracking

#538
### Side note

I vaguely recall reading a comparable report for an earlier version of 56.* but at the moment, I can't find it.

**Comment by MrAlex94** [comment]
I’ve seen it. Must be the patch I pulled. Always forgot about locales.

**Comment by grahamperrin** [comment]
Sidebar views still working, happily: 

![sidebar](https://user-images.githubusercontent.com/192271/52028035-6751f780-2505-11e9-9b2c-208d88caa875.png)

NB home directory housekeeping after testing some locales: 

![telechargements](https://user-images.githubusercontent.com/192271/52028045-7042c900-2505-11e9-82a2-eca9c954eec0.png)

Also, but I didn't take a screenshot: for a few minutes, after starting in British the sidebar continued to show the French translation of _Mobile Bookmarks_.

**Comment by grahamperrin** [comment]
Closed in error, sorry (clumsy hands on annoying HP hardware).

**Comment by kazerniel** [comment]
I'm using Britith English Waterfox, and get the following error when trying to open my browsing history:

> XML Parsing Error: undefined entity
> Location: chrome://browser/content/places/places.xul
> Line Number 336, Column 13:            <treecol label="&col.parentfolder.label;" id="placesContentParentFolder" anonid="parentFolder" flex="1" hidden="true"
> ------------^

**Comment by grahamperrin** [comment]
Workaround: 

1. set the locale to _English (US)_
2. ignore the invitation to restart Waterfox
3. open the Library window
4. reset the locale to whatever you prefer
5. leave the Library window open, or minimised, until you quit Waterfox. 

Plus, a working address for downloads that does not use the Library window: 

- about:downloads

**Comment by hawkeye116477** [comment]
That's related with https://github.com/MrAlex94/Waterfox/pull/843. Places.dtd from each locale (except default) misses two lines.

**Comment by grahamperrin** [comment]
Thanks @hawkeye116477 

Taking a hint from https://www.reddit.com/comments/alucm4/-/efilvus/ I downloaded https://github.com/hawkeye116477/Waterfox/blob/master/browser/extensions/langpack-en-GB%40waterfox.xpi and put it in place, 

```text
# pwd
/usr/local/lib/waterfox/browser/features
# ls -hl langpack-en-GB\@waterfox.xpi
-rw-r--r--  1 root  wheel   516K Feb  1 19:19 langpack-en-GB@waterfox.xpi
# 
```

Works for me (en-GB) :+1:

**Comment by kazerniel** [comment]
Thanks, it fixed it for me too!

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/alr5ft/-/efkv7vp/?context=1>: 

> nothing of that solved the problem on macos and italian language

The old Mac with which I sometimes tested no longer boots (file system irreparable). 

For what it's worth here's a FreeBSD-CURRENT 56.2.7 view of things with `langpack-it@waterfox.xpi` **temporarily** added from <https://github.com/hawkeye116477/Waterfox/tree/master/browser/extensions>: 

![image](https://user-images.githubusercontent.com/192271/52164470-bb1d3600-26e9-11e9-988c-ea1d3e5331ea.png)

Note, this screenshot was without a restart of Waterfox, and without a waiting period, so I should ignore apparently non-translated strings such as _Mobile Bookmarks_. 

### Postscript

Sorry, things spread across three separate discussions, I found <https://www.reddit.com/r/waterfox/comments/alucm4/-/efkvkqi/>: 

> thanks solved also for italian language...

**Comment by linuxgirl22** [comment]
Hello :-) Using latest waterfox appimage, 56.2.7, and same issue; after reading any threads to do with the issue, unfortunately I don't know how to apply the fixes eg there are no folders to place the downloaded fix in. Already using English (UK, I presume) when installed. It's a case of waiting for updated appimage?

**Comment by hawkeye116477** [comment]
@paint-rulz 56.2.7 isn't latest, so just update through AppImageUpdate.

**Comment by linuxgirl22** [comment]
Thanks hawkeye :-) Do I just download that and run it? Sorry, I can't find the bookmark for that, ironically lol, due to not being able to search bookmarks. :-) Can't find it via web search.

**Comment by hawkeye116477** [comment]
@paint-rulz Just download latest AppImageUpdate from https://github.com/AppImage/AppImageUpdate/releases, then run it and choose your old AppImage package.

**Comment by linuxgirl22** [comment]
Great; thanks for link and advice. :-)

**Comment by linuxgirl22** [comment]
I've tried both the appimage updater from that link, and the manjaro inbuilt appimage updating I've found, but both do the same ... unfortunately only a .part file is downloaded and waterfox doesn't update.

**Comment by hawkeye116477** [comment]
@paint-rulz Strange, I see the same problem, previously it worked, maybe it's something on SUSE's side. You can also try to download newer AppImage from https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/Waterfox-latest-x86_64.AppImage.mirrorlist, then just run that newer and should be good :smile:.

**Comment by linuxgirl22** [comment]
Thank you very much indeed; works perfectly! Much appreciate. :-)
