### ISSUE TITLE
appimage 56.2.7

### ISSUE THREAD

**Issue by linuxgirl22** [BrowserWorks/waterfox#851]
Hello :-)
I downloaded the January 27th latest appimage from here: https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/ ... but it's v56.2.6. Not sure what's happening.  Thanks for all your work.

**Comment by grahamperrin** [comment]
It's not maintained by the Waterfox project.

**Comment by linuxgirl22** [comment]
I thought he was linked with the Waterfox project, as appimage maintainer: [https://www.reddit.com/r/waterfox/comments/9rsvcm/appimage_for_waterfox/](url) I can see you comment there, saying there is also another link. When I click through to one of the links, it shows the appimage was last updated a month ago. 
Generally concerned about if appimage is phasing out for Linux.

**Comment by hawkeye116477** [comment]
Oops, forgot about that. It's ready now :smile:.
Sometimes OBS can automatically build package when it find new versions of ingredient, but Waterfox version will be the same until I change that.

**Comment by linuxgirl22** [comment]
Hi hawkeye and thank you very much; appreciate your work ... great that the appimage is available. :-)

**Comment by grahamperrin** [comment]
https://build.opensuse.org/project/show/home:hawkeye116477:waterfox

NB 56.2.7.1 includes an important bug fix for locales.

**Comment by hawkeye116477** [comment]
Currently I'm using official package to make appimage and 56.2.7.1 isn't on official page yet, so I'm must wait for that. Maybe in the future I will change that, to just built it from source, but on the past I had some compatibility problems with it, that's why I chosen to just repackage official package.

Update: It's ready now.

**Comment by grahamperrin** [comment]
https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.2.7.1.en-US.linux-x86_64.tar.bz2 now available
