### ISSUE TITLE
[BUG]  Shows synthaxis error warning when try to open History (Ctrl+Shift+H)

### ISSUE THREAD

**Issue by AjvarXX** [BrowserWorks/waterfox#852]
**Describe the bug**
Instead of opening a History window it tells me there is error in line <treecol label="&col.parentfolder.label;" id="placesContentParentFolder" anonid="parentFolder" flex="1" hidden="true"

**To Reproduce**
1. Ctrl+Shift+H

**Expected behavior**
New history window

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 52.6.7

**Additional context**
Downgrading to 56.2.6 solved the issue.

**Comment by MrAlex94** [comment]
Have you tried 56.2.7.1?

**Comment by AjvarXX** [comment]
> 
> Have you tried 56.2.7.1?

I haven't as update was set to automatic but I just did and it works now.
Thanks.
