### ISSUE TITLE
56.2.7.1 update to 56.2.7.1 on Mac OS X, OS X, macOS

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#853]
https://www.waterfoxproject.org/update/osx64/56.2.7/en-US/release/update.xml at the time of writing: 

```text
<?xml version="1.0"?>
<updates>
    <update type="major" appVersion="56.2.7.1"  buildID="20190201223501" detailsURL="https://www.waterfoxproject.org/blog/waterfox-56.2.7-release-download" displayVersion="56.2.7.1" extensionVersion="56.2.7.1" platformVersion="56.2.7.1" version="56.2.7.1">
        <patch type="complete" URL="https://storage-waterfox.netdna-ssl.com/releases/osx64/update/waterfox-56.2.7.1.en-US.osx64.complete.xz.mar" hashFunction="SHA512" hashValue="3872f991fd688413b91005f07b753fdc361032276d35f4006bd66089a484cf4ccaa718bff00131367117d172c14f766e5db3444fac2aa706bee02cc5f2411351" size="83909941"/>
    </update>
</updates>
```

@MrAlex94 compare the first line above with the first line of the …`/56.2.7/en-US/release/update.xml` files for other platforms. 

Meta/tracking: #582 

Cross references: 

- [Infinite update loop with 56.2.7.1 : waterfox](https://www.reddit.com/r/waterfox/comments/amkuw9/infinite_update_loop_with_56271/) 
- http://disq.us/p/1zg1bto

**Comment by grahamperrin** [comment]
Additional information for end users on Macs: this is, as far as I can tell, a harmless cosmetic issue. 

Where the two versions in the dialogue are the same, for example: 

![image](https://user-images.githubusercontent.com/192271/52179108-0f99e180-27ce-11e9-8cb3-fb79d124c890.png)

– you may ignore the **Update to …** button.

**Comment by MrAlex94** [comment]
Fixed!
https://www.waterfoxproject.org/update/osx64/56.2.7/en-US/release/update.xml?force=1
```<?xml version="1.0"?>
<updates>
    <update type="major" appVersion="56.2.7"  buildID="20190201223501" detailsURL="https://www.waterfoxproject.org/blog/waterfox-56.2.7-release-download" displayVersion="56.2.7.1" extensionVersion="56.2.7" platformVersion="56.2.7" version="56.2.7">
        <patch type="complete" URL="https://storage-waterfox.netdna-ssl.com/releases/osx64/update/waterfox-56.2.7.1.en-US.osx64.complete.xz.mar" hashFunction="SHA512" hashValue="3872f991fd688413b91005f07b753fdc361032276d35f4006bd66089a484cf4ccaa718bff00131367117d172c14f766e5db3444fac2aa706bee02cc5f2411351" size="83909941"/>
    </update>
</updates>```
