### ISSUE TITLE
(1379148) (WebExtensions) Waterfox Classic with sites such as answers.microsoft.com (Microsoft Answers): document.write does not synchronously modify a document if an extension has content scripts at document_start

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#856]
Spun off from https://redd.it/akpg72 involving any one of a number of _blocking_ extensions. 

----

Waterfox 56.2.7.1 on Lubuntu with (experimental, [featured](https://addons.mozilla.org/search/?featured=true&type=extension)) [Malwarebytes Browser Extension](https://addons.mozilla.org/addon/malwarebytes/) 1.0.32 enabled, but disabled for an affected page: 

![image](https://user-images.githubusercontent.com/192271/52258417-f6507c80-2916-11e9-8b60-58cde938362b.png)

- note the **endlessly spinning** asynchronous progress indicator. 

Broadly disabling protection is not a workaround: 

![image](https://user-images.githubusercontent.com/192271/52258543-71b22e00-2917-11e9-89a8-e474af4e3e76.png)

Worked around by disabling the extension: 

![image](https://user-images.githubusercontent.com/192271/52258576-94444700-2917-11e9-9eee-38ce5d17fc0a.png)

### Observations

Re: https://github.com/openstyles/stylus/issues/100#issuecomment-460536521 under [Firefox: Microsoft Answers is broken · Issue #100 · openstyles/stylus](https://github.com/openstyles/stylus/issues/100) I guess that one **or** two patches will resolve this issue. Just a guess; not enough for a pull request from me (sorry). 

### Nutshell

- https://svnweb.freebsd.org/ports/head/www/waterfox/files/patch-bug1379148?view=markup&pathrev=461852 one patch
- https://github.com/search?q=org%3Amozilla+8cGxywiUzWj&type=Commits two commits

Might we get lucky with the _one_ patch that applied on FreeBSD? I wonder.  

### Thoughts

Whilst we're without a fix for 56 e.g. 56.2.7.1 for Linux, Mac OS X and Windows: I have a hunch that there might be another workaround … if I find another, I'll add a comment.

**Comment by grahamperrin** [comment]
Meta/tracking: #538

**Comment by rebop** [comment]
This now works in 68 Alpha. Any chance the fix can get into the 56 line of builds? Thanks!

**Comment by MrAlex94** [comment]
Yep I’ll pull this in from upstream.

**Comment by rebop** [comment]
Thanks so much!
 
Also, I hope my learnings on 68 on Reddit are helpful. If there is a better
way of posting what I discover, please let me know.

  _____

**Comment by rebop** [comment]
Surprised this has not yet been pulled in. Still broken in 56.2.12

**Comment by rebop** [comment]
And still not working in 56.2.13. Can we get this one corrected please?

Thanks.

**Comment by rebop** [comment]
Still not working in 56.2.14. A hopeful reminder to fix this on eplease.

**Comment by rebop** [comment]
Fixed in 2019.10 Classic.

**Comment by grahamperrin** [comment]
Thanks. 

Also, please retry an outdated version of Waterfox Classic. 

Posted without difficulty using outdated home-built Waterfox Classic 56.2.14 (20191007063316) on FreeBSD-CURRENT: 

[Skype and Skype for Business on FreeBSD - Microsoft Community](https://answers.microsoft.com/en-us/skype/forum/sk_else-sk_other/skype-and-skype-for-business-on-freebsd/7b8e9ea4-93d5-49a8-964c-a4da31eeb355)

![2019-10-31 23:35:17 outdated Waterfox Classic 56 2 14 posting to Microsoft Community](https://user-images.githubusercontent.com/192271/67993692-e82b5480-fc39-11e9-8378-b252957ebf9c.png)

**Comment by hawkeye116477** [comment]
So this issue can be closed, just like also #1065 :smile:.
