### ISSUE TITLE
Android updates beyond 60.1.0?

### ISSUE THREAD

**Issue by LafinJack** [BrowserWorks/waterfox#859]
Hello, are updates beyond 60.1.0 in the works for Android? I have had to stick to 56.1.0 because of problems with 60.1.0, from 18 August 2018.

Thank you for your help!

**Comment by Ibuprophen** [comment]
@LafinJack, This is a duplicate of the https://github.com/MrAlex94/Waterfox/issues/730 issue i had submitted a while ago. 

From time to time I check in with @MrAlex94 and @grahamperrin regarding a status update and so far (thankfully) this has not been disregarded/dismissed but, there has been no new updates for this as well (unfortunately). 


~Ibuprophen

**Comment by grahamperrin** [comment]
I thought that #730 was focused on 32-bit. 

> … problems with 60.1.0, …

I, too, have problems with 60.1.0 on a device that was identified as 64-bit: 

- [Can't select text in Waterfox 60.1.0esr Android · Issue #746 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/746) (maybe a duplicate of [Android: copy/paste not working · Issue #727 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/727))

– and so on.

**Comment by LafinJack** [comment]
Thanks! I know multiplatformness is a mess to keep track of, and I appreciate all the work everyone is doing on the project. :)

**Comment by grahamperrin** [comment]
Cross reference ["Save video" is not working : waterfox](https://www.reddit.com/r/waterfox/comments/aozed8/save_video_is_not_working/)

> … on android 9. Will this be fixed in an update?

I can't guess a date but I imagine that the next pre-release, or release, for (64-bit) Android will include fixes for bugs such as #760

**Comment by LafinJack** [comment]
Hi there, just checking on updates for, uh, Android updates. :)

**Comment by LafinJack** [comment]
Bump.

**Comment by MrAlex94** [comment]
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

**Comment by LeeBinder** [comment]
> https://play.google.com/store/apps/details?id=net.waterfox.waterfox

Alex, can you compile Waterfox 68 for Android also for the armeabi-v7a arch as you did with the 56.1.0 version? There's still [quite a few out here](https://github.com/MrAlex94/Waterfox/issues/730) with non-64 bit mobile CPUs. That would be really awesome!
