### ISSUE TITLE
Website detects Microsoft Edge as Mac OS

### ISSUE THREAD

**Issue by Scrxtchy** [BrowserWorks/waterfox#86]
Upon recently installing Windows 10 Pro Insider Preview build 14986, 
the webpage offered a download for Mac, instead of the wanted windows installation file.

Accessing it today, gave a Windows option, but refreshing the page delivered a Mac download again, this must mean I refreshed the page, and it returned this.

Accessing the page from another source, or from URL entry gives a windows option, it's just every refresh seems to point to mac file

The `navigator.useragent` is `"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.14986"` if it means anything

**Comment by MrAlex94** [comment]
It's an issue with the CDN delaying the load in the script. Am updating the website so this will be resolved soon.
