### ISSUE TITLE
Craiglist Reply button does not work on Waterfox but does on Firefox

### ISSUE THREAD

**Issue by Areopagitics** [BrowserWorks/waterfox#861]
try replying to this post or any on Craigslist:

https://newyork.craigslist.org/mnh/laf/d/new-york-city-paid-you-to-sell-me-your/6816730308.html

"An error has occurred. Please try again later."

I am surprised no one has reported it before

**Comment by Ibuprophen** [comment]
I took a look at the link you had provided and, it had reflected the same error.

So I had taken a slightly deeper look at weather or not it's the browser. 

I then found that it was, ultimately, their server that was a bit congested. 

I had quickly cleaned up the Browsers temporary files (like the cache and such) and then restarted the browser.

I then tried again it looks like it's up and working now. This isn't uncommon. 

Maybe someone else can take a look and confirm this as well... 

Good Luck! 


~Ibuprophen

**Comment by grahamperrin** [comment]
Not specific to Waterfox. 

The error occurs with Firefox 65.0 in safe mode: 

![image](https://user-images.githubusercontent.com/192271/52755880-66d25a00-2ff7-11e9-8848-7cfdb5870b1b.png)

`Mozilla/5.0 (X11; FreeBSD amd64; rv:65.0) Gecko/20100101 Firefox/65.0`

**Comment by reikred** [comment]
@grahamperrin, this is the same problem as you have commented on elsewhere(*), namely that many sites that use reCaptcha  do not like certain User Agent strings, in particular unusual ones like  

"User Agent Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0 Waterfox/56.2.7"

(*)For reference, here are those reddit threads

https://www.reddit.com/r/waterfox/comments/apvnrg/captcha_problems/

https://www.reddit.com/comments/amy85w

The problem is real.

**Comment by grahamperrin** [comment]
Reproducible with Firefox 65.0 in Lubuntu, 

`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0`

**Comment by grahamperrin** [comment]
Not reproducible with Chromium 71.0.3578.98 (Official Build) built on Ubuntu , running on Ubuntu 18.10 (64-bit) (Lubuntu), 

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36`

**Comment by grahamperrin** [comment]
### [reCAPTCHA v3](https://www.google.com/recaptcha/intro/v3.html)

(<https://www.google.com/recaptcha/> redirects to v3.)

> … many sites that use reCaptcha do not like certain User Agent strings, …

If that alone were the problem, then I should expect Firefox on ([Tier-1](https://developer.mozilla.org/docs/Mozilla/Supported_build_configurations)) Linux to work with the newyork.craigslist.org example with: 

- `general.useragent.override` `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36`

The site does **not** work with Firefox in that way. 

Also please note, this is **not** an encouragement to anyone to experiment with `general.useragent.override` in Firefox or Waterfox – bad things can happen. 

#### In the subreddit for Firefox

[Craigslist "reply to" button doesn't load : firefox](https://www.reddit.com/r/firefox/comments/abk3km/craigslist_reply_to_button_doesnt_load/) (2019-01-01) is a different symptom, not the symptom pictured above. No mention of reCAPTCHA. 

https://www.reddit.com/r/firefox/search?q=reCAPTCHA&restrict_sr=on&sort=new&t=year

For now, ignore the 2019-01-08 post that is supposedly solved. 

There's plenty of advice, but much of it is irrelevant to cases where the reCAPTCHA UI does not appear. 

From <https://www.reddit.com/comments/ahi9kd/-/eef25kh/> (2019-01-19): 

> … I personally haven't seen this issue, but Firefox can't really do much about this, …
> 
> … I don't see any reports of this on bugzilla - if Firefox developers are like me, they haven't seen it, and since no one has reported it, it is not getting worked on.
> 
> See: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=recaptcha&list_id=14520375
> 
> You should report the issue, along with any steps to reproduce - hopefully we can get a handle on what is happening to resolve it for you. …

**Comment by grahamperrin** [comment]
![2019-02-16 03 14 screenshot](https://user-images.githubusercontent.com/192271/52894723-c9b62380-31a6-11e9-9a11-0d1b415095ff.png)

I drafted a bug in the Mozilla area, then the problem began affecting Chromium: 

![image](https://user-images.githubusercontent.com/192271/52894005-adac8500-319a-11e9-894f-f3c77bb4319f.png)

– so I refrained from reporting to Mozilla. 

Given the broad range of affected browsers – including Firefox in Lubuntu – someone should report the problem to a Craigslist service administrator (I'm not a user of the service). 

I reported to [the reCAPTCHA Google Group](https://groups.google.com/forum/#!forum/recaptcha) but my post has not yet appeared.

**Comment by grahamperrin** [comment]
> ## Craiglist Reply button does not work on Waterfox but does on Firefox
> 
> … 
> 
>> An error has occurred. Please try again later.
> 
> I am surprised no one has reported it before …

2019-01-22 from a user of Firefox: 

- ["An error has occurred. Please try again later". Please suggest how I overcome it. : craigslist](https://www.reddit.com/r/craigslist/comments/aetgeo/an_error_has_occurred_please_try_again_later/)

**Comment by grahamperrin** [comment]
Currently working with [Falkon](https://www.falkon.org/) on FreeBSD-CURRENT: 

![falkon](https://user-images.githubusercontent.com/192271/52897570-3f81b580-31ce-11e9-8d21-9567f083f38c.png)

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Sat 16 Feb 2019 09:25:57 GMT
FreeBSD 13.0-CURRENT r344013 GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' falkon
www/falkon 3.0.0_5 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

User agent string: 

`Mozilla/5.0 (X11; FreeBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.0.0 Chrome/56.0.2924.122 Safari/537.36`

Use of the string in Waterfox ~56.2.7.1 on the same system is **not** a workaround. 

### Generally

Given the unreliability of Google reCAPTCHA with Chromium, Firefox and other browsers on Ubuntu (Lubuntu): 

- I should not expect _any_ discovered workaround – such as use of Falkon, Mozilla Firefox or Google Chrome – to be lasting or reliable.

**Comment by grahamperrin** [comment]
@Areopagitics is the error reproducible if you login to craigslist before attempting to reply?

**Comment by reikred** [comment]
Has anyone seen the error occur  if the User Agent string is of a "Windows" type? I have not, only linux and FreeBSD seem affected (only tested Firefox and Waterfox on Fedora 25 and Win10).

**Comment by grahamperrin** [comment]
> Has anyone seen the error occur if the User Agent string is of a "Windows" type? 

Yes, albeit not tested on Windows.

**Comment by grahamperrin** [comment]
Currently not reproducible with SeaMonkey 2.49.4 on FreeBSD-CURRENT. 

If I recall correctly: a few days ago, it _was_ reproducible. 

### Waterfox

No longer reproducible with Waterfox ~56.2.7.1 on FreeBSD-CURRENT. 

@Areopagitics with Waterfox, please visit [Road Trip](https://roadtrip.glitch.me/) and start the trip. Is your location found?

**Comment by grahamperrin** [comment]
> The error occurs with Firefox 65.0 in safe mode: …

Still reproducible with Firefox on FreeBSD-CURRENT, which can't find my location (for Road Trip) (and I can't be bothered to fix it at the moment).

**Comment by grahamperrin** [comment]
> https://newyork.craigslist.org/mnh/laf/d/new-york-city-paid-you-to-sell-me-your/6816730308.html

– has expired. 

@Areopagitics can you let us have the address of another post that's affected?

Is https://newyork.craigslist.org/mnh/laf/d/bryn-mawr-new-yorklost-cats-dog-pets/6809209908.html bugged for you?

Thanks

**Comment by Areopagitics** [comment]
yes, any other Craiglist post with a reply button

https://newyork.craigslist.org/mnh/act/d/new-york-city-looking-for-companion/6829949171.html

pardon the post, but this is the first one that popped up

take care!

**Comment by grahamperrin** [comment]
> pardon the post

Ha ha, flagged for removal before I could get there. 

@Areopagitics bumping https://github.com/MrAlex94/Waterfox/issues/861#issuecomment-464440347 above, is the error reproducible if you login to craigslist before clicking any **Reply** button?

If you like, try the pets-related link in my previous comment.

**Comment by Areopagitics** [comment]
hi Graham,

I usually don't log into Craigslist when searching for things ... I think
most people don't have a Craigslist account ... I tested your pets link and
it also doesn't work.

take care!

**Comment by grahamperrin** [comment]
> tested your pets link and it also doesn't work.

Works for me, with a profile that had its history cleared a day or two ago: 

![2019-03-04 21 36](https://user-images.githubusercontent.com/192271/53843125-60515580-3f99-11e9-9a9b-b0e13d354320.png)

**Postscript**: this is not an encouragement to clear history. Doing so is not a workaround.

**Comment by grahamperrin** [comment]
Failure in Firefox on Manjaro: 

![image](https://user-images.githubusercontent.com/192271/53771898-3a19b000-3edc-11e9-8363-86e518e58dc9.png)

**Comment by grahamperrin** [comment]
### [Otter](https://www.otter-browser.org/)

![image](https://user-images.githubusercontent.com/192271/53789103-8f28e680-3f1b-11e9-90a6-5ae5801e5716.png)

> Web backend: WebKit Backend 602.1.

> SSL library version: OpenSSL 1.1.1b-freebsd 26 Feb 2019.

With Otter 1.0.01 on FreeBSD-CURRENT, I have not yet got got the Reply button to work. [reCAPTCHA Problem](https://thedndsanctuary.eu/index.php?topic=3499.0) mentions a problem but I can't tell the details. 

Screenshots (after a screen recording): 

![image](https://user-images.githubusercontent.com/192271/53789357-20985880-3f1c-11e9-98cb-aa4ebbf56458.png)

![image](https://user-images.githubusercontent.com/192271/53789401-3279fb80-3f1c-11e9-856f-c9e38834d955.png)

![image](https://user-images.githubusercontent.com/192271/53789420-3c9bfa00-3f1c-11e9-9e8c-eac40e853e18.png)

![image](https://user-images.githubusercontent.com/192271/53789442-46256200-3f1c-11e9-9b86-d425a6a70b7e.png)

**Comment by reikred** [comment]
My latest datapoint: After failing reply operation on craigslist on linux firefox and waterfox, and windows firefox, waterfox and chrome AND edge browser, I started suspecting having another IP address would help. So I tested my android tablet with firefox, and reply failed again. I then got a different ip address by using an xfinitywifi hotspot that is not mine, and craigslist reply worked in firefox. Conclude that somebody, including craigslist,  is being incredibly overzealous and breaking the internet for many users. Not cool.

**Comment by grahamperrin** [comment]
> … Conclude that somebody, including craigslist, is …

[Bump](https://github.com/MrAlex94/Waterfox/issues/861#issuecomment-464279520), 

>> … someone should report the problem to a Craigslist service administrator …

Has anyone done so?

**Comment by grahamperrin** [comment]
@bugandy wrote: 

> … try an old waterfox version …

Tested: 56.2.7 https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.2.7.en-US.linux-x86_64.tar.bz2 – in the same Lubuntu virtual machine that I previously used to test 56.2.7.1. 

[lost & found](https://newyork.craigslist.org/search/brk/laf) ▶ tested six, six were trouble free. Quit 56.2.7. 

Launched 56.2.7.1 in the same virtual machine ▶ tested the same six, three were troublesome. I avoided excessive clicks. Quit 56.2.7.1. 

Launched 56.2.7 ▶ success with the three that were previously troublesome. Quit 56.2.7.

Launched 56.2.7.1 ▶ success with the three that were previously troublesome.

**Comment by grahamperrin** [comment]
I tried the UA string for 56.2.7 in 56.2.7.1. It seemed to help on one platform, not another.

**Comment by grahamperrin** [comment]
Has no true user of craigslist contacted a craigslist service administrator? 

:-(

Re: https://github.com/MrAlex94/Waterfox/issues/861#issuecomment-469577753 where previously all tests failed, now all tests succeed **and** there has been no change to Otter, its back end, or the SSL library.

**Comment by grahamperrin** [comment]
Does anyone have a craiglist account? 

I made one for myself this morning, but I must wait one week before a new user can post to the [craigslist help desk forum](https://forums.craigslist.org/?area=24&forumID=9). 

Whilst we wait, I see (but can not respond to) this: 

- [Anyone else not able to reply to ANY posting? – forums - craigslist](https://forums.craigslist.org/?act=Q&ID=297830104)

**Comment by reikred** [comment]
>>Does anyone have a craiglist account?

I don't, because craigslist last I tried would not let me create an account without revealing my cellphone number. And when I did, it disallowed me because it says the number looks like a landline And it won't accept google voice numbers, either. So Craigslist has multiple levels of impossible challenges before you can use their site. reCaptcha prblems is just the start of it. The retardation at Craigslist is a strong one.

**Comment by grahamperrin** [comment]
### Google reCAPTCHA

I sent three tweets to reCAPTCHA. 

### craigslist

> … last I tried would not let me create an account without revealing my cellphone number. …

No comparable requirement when I registered this morning. 

Registration required nothing more than: 

1. an e-mail address
2. verification of the address.

**Comment by grahamperrin** [comment]
### Otter

> Re: #861 (comment) where previously all tests failed, now all tests succeed and there has been no change to Otter, its back end, or the SSL library.

… and now again, all reply buttons fail in Otter views of craigslist posts. 

Flip, flop.

**Comment by grahamperrin** [comment]
### UA strings for Firefox ESR

At <https://www.reddit.com/comments/b0ncy6/-/eighmb6/> _b1k3rdude_ tested this: 

`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.5) Gecko/20100101 Firefox/60.5`

I tested it on FreeBSD-CURRENT (not Windows): 

- for the first three of six craigslist posts, success 👍

A contracted form, not specifying a platform: 

`Mozilla/5.0 (rv:60.5) Gecko/20100101 Firefox/60.5`

- for the other three posts, an **explanatory** failure, like this

![image](https://user-images.githubusercontent.com/192271/54316928-c2353f00-45d9-11e9-84e0-d21af1b28c35.png)

– leading to [browser requirements](https://support.google.com/recaptcha#6223828). 

Expanded to a FreeBSD-specific string: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.5) Gecko/20100101 Firefox/60.5`

- success for all six posts. 

I removed Firefox 66, installed Firefox ESR 60.5.2esr (64-bit). Its actual string: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.0) Gecko/20100101 Firefox/60.0`

- applied to Waterfox ~56.2.7.1, tested aggressively (all six concurrently), the reply button failed (non-explanatory error) for five of the six posts. 

Re: Mozilla's [future branch dates](https://wiki.mozilla.org/Release_Management/Calendar#Future_branch_dates) I pretended to use a version that does not yet exist: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9`

- tested slightly less aggressively, resulted in four successes (including the one that failed in the previous test) and two failures
- for the two that failed, a non-aggressive test (one at a time) led to success for both.

**Comment by grahamperrin** [comment]
### Firefox ESR and Firefox on FreeBSD-CURRENT

#### 60.5.2esr 

Tested six other posts, all succeeded. 

#### 66, safe mode

Tested six other posts, all failed. 

Re-tested the same six, non-aggressively, all failed. 

#### 66, normal mode

Re-tested the same six, non-aggressively, all failed.

**Comment by grahamperrin** [comment]
### ESR string revisited

I quit Waterfox ~56.7.2.1, relaunched, restored the previous session (206 tabs across twelve windows). 

Continued testing with the futuristic, FreeBSD-specific string: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9`

Opened fifty previously non-viewed posts. 

After finding success in the first of the fifty, I remembered that I was signed in, so I signed out then reloaded all tabs. 

Forty-eight successes. 

One of the two failures was for a window that I obscured (with another window of Waterfox) whilst awaiting the result of reCAPTCHA. This one succeeded after a simple reload. 

The one other failure failed again after a simple reload, succeeded after a reload with an override of the cache.

**Comment by grahamperrin** [comment]
### Blended UA strings: current Waterfox and future Firefox ESR

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Waterfox/56.2.7 Firefox/60.9`

(56.2.7 is not _exactly_ 56.2.7.1 but for this test, it's close enough.)

Tested four previously non-viewed posts. All reply buttons succeeded. 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.9) Gecko/20100101 Firefox/60.9 Waterfox/56.2.7`

Tested ten previously non-viewed posts, aggressively (all ten spinning concurrently). 

Seven succeeded. 

One failed with a non-explanatory error, another could not connect to the service: 

![2019-03-13-23 23:25:06 frame](https://user-images.githubusercontent.com/192271/54321177-c9634980-45e7-11e9-9fae-ab901ce9ca5d.png)

– the third span endlessly (not surprising, given the previously reported connection issue). 

I stopped all three, performed simple reloads then all three succeeded.

**Comment by grahamperrin** [comment]
### Waterfox 56.2.8

To anyone who found an issue with the reply buttons with 56.2.7.1: 

- please tell whether things are better with 56.2.8. 

– thanks.

Full installers are available from <https://www.waterfoxproject.org/>.

If you do find a problem, please state: 

1. the version of Waterfox
2. the operating system
3. the version of the OS. 

### Postscript – IMPORTANT

Before testing 56.2.8, please **cease any site-specific user agent string override** that you might have made.

**Comment by grahamperrin** [comment]
[Um](https://www.youtube.com/watch?v=pUgFXuAYPrs), test results now (still using ~56.2.7.1 to spoof) are entirely different. 

Back to <https://github.com/MrAlex94/Waterfox/issues/861>:

> … I then found that it was, ultimately, their server that was a bit congested. …


Maybe that's a complicating factor.

**Comment by grahamperrin** [comment]
### Around eleven hours later

Still using ~56.2.7.1 to spoof: 

- five or six failures (no success) with a heavily extended profile, which I might describe as a _congested profile_
- <strike>three </strike>two successes followed by two failures with a relatively clean profile in safe mode, after I reloaded all tabs none were successful. 

Tested: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.0) Gecko/20100101 Firefox/60.0`

![image](https://user-images.githubusercontent.com/192271/54488639-048da300-489c-11e9-8c8c-e0b67ec54889.png)

**Comment by grahamperrin** [comment]
### A little later …

Taking a hint from <https://www.reddit.com/comments/b0ncy6/-/eior3lj/>:

`Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0`

With the relatively clean profile in safe mode: 

- successes, for the four that previously failed. 

With the relatively congested profile: 

- five of five failures. 

Back to the relatively clean profile in safe mode, tested a little more aggressively: 

- three of five succeeded
- two of five seemed to spin endlessly

![image](https://user-images.githubusercontent.com/192271/54488880-b201b600-489e-11e9-9edb-e14a919f5ff1.png)

I reloaded the two that were spinning, both succeeded.

**Comment by grahamperrin** [comment]
@Areopagitics you should find that Google reCAPTCHA is less troublesome with recent releases of Waterfox Classic. 

If so, you can close this issue. Thanks.
