### ISSUE TITLE
WhatsApp Web complains about an outdated firefox version

### ISSUE THREAD

**Issue by TPXP** [BrowserWorks/waterfox#863]
**Describe the bug**
When opening web.whatsapp.com, it complains about an old Firefox version instead of working properly.

**To Reproduce**
1. Go to https://web.whatsapp.com
2. See error

**Expected behavior**
The QR code to pair the web client with WhatsApp should appear

**Screenshots**
![Error screenshot](https://user-images.githubusercontent.com/7191841/52907671-f3537580-32a0-11e9-888b-0788f6a144e5.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux - `Linux MYCOMPUTER 4.20.7-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 6 18:42:40 UTC 2019 x86_64 GNU/Linux`
 - Version: 56.2.7.1

**Additional context**
It's probably looking for a specific variable or matching against Firefox somewhere. I understand this is a third-party service but I don't expect them to fix the bug. It would be great if Waterfox could include a workaround. :wink:

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/9drjqx/-/eglsjfk/?context=2

**Comment by TPXP** [comment]
Oops! Good catch, sorry next time I will search the subreddit first :confounded:

**Comment by grahamperrin** [comment]
Thanks! 

If the combined workaround (attention to both the UA string and the service worker) has a **lasting** and reliable effect for you – over a period of hours or days including session restorations; closing WhatsApp Web then using the History menu to reopen the tab; and so on – then please leave a quick reply under https://www.reddit.com/comments/ara5ia/-/egls7sa/

If not lasting: you can ask for this issue to be reopened.

**Comment by grahamperrin** [comment]
Cross reference https://twitter.com/grahamperrin/status/1104607644948541441 (2019-03-10):

> … Please, can you fix the web app? …

Previously https://twitter.com/grahamperrin/status/1094654582230339584 (2019-02-10): 

> … please can you whitelist UA strings for recently released Waterfox 56.2.7.1? To work with WhatsApp Web. …

**Comment by grahamperrin** [comment]
### Waterfox 56.2.8 with WhatsApp Web

@TPXP please:

1. [install](https://www.waterfoxproject.org/) (or update to) 56.2.8
2. if you previously set a user agent string for WhatsApp Web, **cease the override**
3. tell whether things are better with 56.2.8

– thanks.

If a reload of the page causes the "Firefox 30+" stuff to reappear, you can follow the four steps at https://www.reddit.com/comments/b151j7/-/eijtejp/

---

If you do find a problem, please state: 

- the version of Waterfox
- the operating system
- the version of the OS.

**Comment by TPXP** [comment]
Just updated to 56.2.8. After clearing the cache and history, the message (which appeared after sometime, can't remember what changed...) to update to Firefox 30+ disappeared. It seems to work correctly now. I also enabled service workers, even though I'm not sure they're required.

Thanks for improving general web compatibility in this new build! I also had a few issues with Github and I'm glad to see that they're also fixed :+1:

**Comment by grahamperrin** [comment]
Thanks for the feedback. 

With ~56.2.7.1 and the service worker not blocked, I got this … after a while (not with the initial reload): 

![image](https://user-images.githubusercontent.com/192271/54572291-a87f6780-49de-11e9-8b17-6ef9c3dddbfc.png)

**Comment by TPXP** [comment]
Yes, I had a similar issue and had to clear the cache for WhatsApp web to work again after the upgrade. Let's hope it won't happen again on this version :crossed_fingers:

**Comment by grahamperrin** [comment]
The interesting thing for me (still with ~56.2.7.1, I can not yet build on FreeBSD-CURRENT): I get [what's above](https://github.com/MrAlex94/Waterfox/issues/863#issuecomment-474153152) – with service workers disabled – **after** (but not immediately after) overriding the cache e.g. <kbd>Control</kbd>-<kbd>F5</kbd> or <kbd>Shift</kbd>-Reload.

### Key point

With the web app supposedly reliable (e.g. after overriding the cache then restarting the browser) with service workers disabled: 

1. sooner or later a simple reload will cause WhatsApp Web to present the UA-related error; **and**
2. the only way to increase reliability is to un-register the service worker **and then** either block it or again, disable service workers

– and the un-registration that is essential to step (2) can not be performed with workers disabled. 

----

@MrAlex94 @laniakea64 in other words, the mere presence of the worker – with all workers **disabled** – is enough to lead to a symptom that would normally be associated with the worker **enabled**. 

I found this strange behaviour a few weeks ago but (sorry) I can't recall which web app was affected when I first found the strangeness. There might be a mention somewhere in Reddit. I have a screen recording from a few hours ago that sort of captures the behaviour but it's a bit of a messy recording that might cause confusion so for now, I'll withhold it. 

If we're lucky: the strangeness will be limited to FreeBSD … and/or my collection of extensions, although now (as I write this) I vaguely recall making it reproducible with a different, relatively clean profile. 

Fingers crossed …

**Comment by ForgeSource** [comment]
WhatsApp Web was working fine for me in Waterfox until the latest (Beta) version - 2.20.6 - which arrived this morning.

Now I just get the "WhatsApp works with Mozilla Firefox 52+" error, and refreshing the tab doesn't help. Nor does rebooting the phone handset. Waterfox Classic is 2020-01 on Windows 10.
