### ISSUE TITLE
Unable to delete QuoVadis certificates

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#868]
**Describe the bug**
According to an article on [ghacks.net](https://www.ghacks.net/2019/02/24/how-to-remove-darkmatter-certificates/#comment-4404036) QuoVadis certificates which are associated with UAE intelligence services have been involved with hacking individuals and companies. The article continues with instructions on how to delete these. 

However, after doing so they reappear once the menu is reopened again. 

**To Reproduce**
1. Go to about:preferences#advanced 
2. Click on Certificates, then View Certificates.
3. Scroll down to QuoVadis Limited and select all the certificates listed under that heading. 
4. Click the "Delete or Distrust button". Confirm deletion and click OK to exit. 
5. Reopen the menu and perform steps 1 to 3. 
6. All the certificates have been reinstated. 

**Expected behavior**
Certificates which have been deleted shouldn't reappear. 

**Screenshots**
![quovadis_certificates](https://user-images.githubusercontent.com/33827636/53301206-202efc00-3850-11e9-9176-3e6ceffded08.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 8.1

**Comment by grahamperrin** [comment]
The same behaviour with Firefox 65.0.1 (64-bit) on FreeBSD-CURRENT.

**Comment by grahamperrin** [comment]
Maybe this, from <https://support.mozilla.org/questions/952512#answer-414361> (2013): 

> Firefox will remove the trust bits if you delete a build-in root certificate, but not remove the certificate.
> 
> If the trust bits are cleared then the certificate can no longer be used to build a certificate chain that ends with a root certificate, so this disables the certificate and blocks servers that use them.

**Comment by grahamperrin** [comment]
Cross reference: the uppermost discussion at https://www.reddit.com/r/waterfox/duplicates/augrpg/waterfox_has_this_too_right/
