### ISSUE TITLE
Unable to load some sites - SEC_ERROR_OCSP_OLD_RESPONSE

### ISSUE THREAD

**Issue by szepeviktor** [BrowserWorks/waterfox#87]
https://wordpress.org/
https://chocolatey.org/

After googling some mention Waterfox as the source of the problem.
My clock is correct and I'd like to check OCSP.
Please advise.

v50.0.2

**Comment by szepeviktor** [comment]
Seems to be solved in v50.1.0
Thank you.

@MrAlex94 Could you point out which line corresponds to this issue in the release notes?

**Comment by szepeviktor** [comment]
No, this is an issue sometimes. For example right now.

**Comment by PandaCodex** [comment]
@szepeviktor 

Re-sync your windows clock with time servers, if there is a system date\time mismatch certificates can not be validated correctly.

**Comment by szepeviktor** [comment]
Thank you.
I've been through couple of steps including checking RTC.

As of RTC: After synchronization I've checked it on https://time.is/ it was +/- 1 second.

**Comment by MrAlex94** [comment]
@szepeviktor, do you still have this issue?

**Comment by szepeviktor** [comment]
Thank you for the question, not any more.
Now on v55.0.2
