### ISSUE TITLE
Waterfox crashes with "gah your tab just crashed" on Lloyds banking login page

### ISSUE THREAD

**Issue by andonevris** [BrowserWorks/waterfox#870]
When trying to login to 
https://onlinebusiness.lloydsbank.co.uk/business/logon/login.jsp

Waterfox tab crashes 100% of the time (gah your tab just crashed).  Tested with all addons disabled (safe mode) with the same result. Firefox and chrome handle the page fine.

After reading various reports of stylo CSS being problematic I checked about:config and Stylo is disabled (default setting)

**To Reproduce**
1. Go to https://onlinebusiness.lloydsbank.co.uk/business/logon/login.jsp
Page will crash at the end of loading 

**Expected behavior**
Not crash :)

**Desktop (please complete the following information):**
 - OS: Win 10 X64
 - Version 1809
 - Waterfox 56.2.7.1 (64-bit)

**Comment by grahamperrin** [comment]
Is the crash reproducible if you block Adobe Flash at the page? 

Reproducible with Waterfox in safe mode? 

- about:support

Reproducible with a new profile? 

- about:profiles

https://helpx.adobe.com/flash-player.html is your Flash Player up-to-date? 

For me, <https://onlinebusiness.lloydsbank.co.uk/business/logon/login.jsp> does not crash Waterfox ~56.2.7.1 in single-process mode on FreeBSD-CURRENT with Adobe Flash enabled at the page. At other sites I did, however, have crashes (extraordinarily rare) three times yesterday, at least two of these were traced to my carelessness at about:addons where I had allowed the plug-in to run without asking.

**Comment by andonevris** [comment]
Reproducible with Waterfox in safe mode? Yes
Reproducible with a new profile? Yes  
Is your Flash Player up-to-date? Yes

I am on windows so maybe something there, perhaps another windows user can check?

**Comment by grahamperrin** [comment]
Thanks. 

Also crash-free with 56.2.7.1 on Linux (Manjaro) with Adobe Flash enabled at the page.

**Comment by strotee** [comment]
The page doesn't crash for me.

OS: Win 10 X64
Version 1809
Waterfox 56.2.7.1 (64-bit)

**Comment by grahamperrin** [comment]
@andonevris 

Use File Explorer to perform a live check of the file system e.g. C:

Does it appear to be OK? 

Is your data backed up? (A more thorough check may be appropriate, with a risk of worsening the situation.)

**Comment by andonevris** [comment]
file system is fine. Have run chkdsk and spinrite, all clear. I have multiple system images and data backups  data is safe :)

I have no instability with any other browsers, firefox works fine, chrome even edge but waterfox is crashing tabs a lot, on some pages 100% of the time (Lloyds) but also random crashes elsewhere.

Is there anyway to look at crash dumps to get a clue?  My main reason for switching to waterfox was to keep some legacy add-ons that I need for work, the quantum versions just don't cut it.  Is there a way old addons could affect waterfox even when running in safe mode/new profile?

Worst case scenario I can refresh waterfox and start from scratch, re-install all addons but I don;t fancy doing that if I end up back in the same place.

EDIT: BTW I have also tried turning graphics acceleration off & updated graphics drivers

**Comment by grahamperrin** [comment]
Excellent. 

> … look at crash dumps to get a clue? …

Re: https://www.reddit.com/comments/aaxyuo/-/ecy51vn/ about:crashes is disabled. 

Integral crash reporting aside: I don't know how to approach dumps on Windows, someone else will know (expect to find guides online). 

On FreeBSD I sometimes use [truss(1)](https://www.freebsd.org/cgi/man.cgi?query=truss&sektion=1&manpath=FreeBSD), sometimes I find it more useful to simply run the application from the command line and then if I'm lucky, something intelligible will appear (in the terminal window) when a problem occurs. 

Try: 

1. exit Waterfox
2. uninstall
3. restart Windows
4. use the full installer. 

I know, it's lazy advice but IIRC people do sometimes report success following a clean-ish installation. 

----

> …  Is there a way old addons could affect waterfox even when running in safe mode/new profile?

#### Safe mode

From results at https://helpx.adobe.com/flash-player.html for a _new_ plug-in, I _should_ say that plug-ins are disabled in safe mode, however something at the back of my mind tells me that there may be exceptions.

**Comment by andonevris** [comment]
Ok I'm getting somewhere.

Managed to trace the faults to 2 .acm files (audio compression modules)

The faulting modules in my case were:
c:\windows\system32\lameACM.acm
c:\windows\system32\ff_acm.acm

Uninstalled lame and ffdshow (codecs) and can browse to lloyds bank now, hooray.

Maybe some x86/x64 mix-up when trying to load those .acm files? Just a guess, I'll leave it to those more qualified to figure out the exact mechanics.

Thanks for the tips, pointed me in the right direction and saved me a lot of time.

**Comment by IzzySoft** [comment]
Not related to this specific site, but starting with Waterfox 56.2.9 I start seeing these tab-crashes about once a week with different sites (latest one was https://qualityland.de/ just a couple of minutes ago). Never saw that before. Nasty thing is that as a side-effect, all other tabs are unloaded, so I e.g. lose notifications on my Stack Exchange chat tabs.

I'm currently on 56.2.10 (via the PPA), running on Linux Mint 18.3. If I should open a separate issue for this, please let me know.
