### ISSUE TITLE
Non-functional 'Enable' button and misleading yellow alert at about:addons

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#878]
I thought this bug was reported a year or so ago, <strike>I can't find it (maybe it's in Reddit)</strike> … found: 

- https://www.reddit.com/comments/89bcgx/-/dwq62cl/ (2018-04-03)

![image](https://user-images.githubusercontent.com/192271/53861752-f8bcf980-3fdc-11e9-9daf-494c75c47baa.png)

> ❗ Add-on compatibility checking is disabled. You may have incompatible add-ons. **Enable** 

Suggestions: 

1. remove this line from Waterfox 56.x
2. review the requirement before a major update to Waterfox. 

Meta, tracking: #538

**Comment by grahamperrin** [comment]
> ## misleading yellow alert 

Here, for example, the second and third yellow alerts contradict the first: 

![image](https://user-images.githubusercontent.com/192271/53862714-1e97cd80-3fe0-11e9-9b1f-4c4102db575c.png)

**Comment by laniakea64** [comment]
(I pointed this out in https://github.com/MrAlex94/Waterfox/pull/501 and was not told that I was wrong to assume this is intended behavior.)

**Comment by grahamperrin** [comment]
Thanks 👍 for the reminder …

**Comment by laniakea64** [comment]
> (I pointed this out in #501 and was not told that I was wrong to assume this is intended behavior.)

Turns out that must have been simply missed, as this issue seems fixed by https://github.com/MrAlex94/Waterfox/commit/6d47f085ecc2dc8c59e0ae21adcb008d13e0847b , so I thumbed down my earlier comment.

Nice to have this fixed in Waterfox! :smiley:

**Comment by grahamperrin** [comment]
Waterfox 56.2.8 on Windows 7 Enterprise: 

![image](https://user-images.githubusercontent.com/192271/54686216-aa494800-4b10-11e9-9d32-6865d79bfe64.png)

![image](https://user-images.githubusercontent.com/192271/54686290-d664c900-4b10-11e9-8db6-df38dd95a783.png)
