### ISSUE TITLE
When logged in, Youtube homescreen does not load.

### ISSUE THREAD

**Issue by cjfreeze** [BrowserWorks/waterfox#880]
**Describe the bug**
Youtube homescreen does not load. Loading placeholders are present but not intractable. Menu is also not intractable. Directly visiting a video lets you watch the video but the rest of the page is still not intractable. Web console gives `TypeError: window.customElements is undefined` and no other errors. This happens on both Windows 10 and OSX Mojave.

**To Reproduce**
1. Go to youtube.com
2. Log in with a Youtube account (not sure if it breaks for both types of accounts or just brand accounts)
3. You should now not be able to interact with anything on the page or see any videos. 

**Expected behavior**
The scripts on the page should load without incident and the page should be usable. This does not happen in Firefox. This is likely due to a change in google's scripts.

**Screenshots**
_uninteractable youtube_
<img width="1680" alt="Screen Shot 2019-03-11 at 11 54 21 AM" src="https://user-images.githubusercontent.com/11078691/54141887-9016b800-43f4-11e9-8a31-35ac927723f6.png">

**Desktop (please complete the following information):**
 - OS: Windows 10, OSX Mojave
 - Version: 56.2.7.1 (64-bit)

**Additional context**
Works in latest version of Firefox.

**Comment by laniakea64** [comment]
Try this -

go to `about:config`
right-click > New > String
name: `general.useragent.override`
value: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0`

Does the issue still persist?

**Comment by grahamperrin** [comment]
[“Investigating issues with @YouTube. Not sure why sometimes it's not rendering but am unable to reproduce, so would appreciate if users would let me know if they have issues and on what platform.” : waterfox](https://www.reddit.com/r/waterfox/comments/ayjop0/investigating_issues_with_youtube_not_sure_why/)

NB the unanswered question about feedback to YouTube: 

- https://www.reddit.com/comments/ayjop0/-/ei85817/

Hint: before masking the problem, please consider sending feedback.

**Comment by laniakea64** [comment]
@grahamperrin Thanks for the link.

@MrAlex94 I've seen two causes for the issue with Youtube.

One is UA sniffing.  If Youtube sees UA string of Firefox 64 or above, it will sometimes serve a version of the page that requires Shadow DOM and Custom Elements API support.  Waterfox doesn't have such support, and Firefox didn't have it until [version 63](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63#APIs).

The other cause is (I think) overzealous adblock filters that don't apply the same to all versions of the Youtube video page, but I thought that one was unique to my setup.

Based on console message mentioned by @cjfreeze, it looks like the UA sniffing one is what this issue is about.

**Comment by grahamperrin** [comment]
> … adblock filters …

:+1: 

https://www.reddit.com/comments/amsugb/-/ehv2qe4/ ▶ https://support.mozilla.org/questions/1236839

![image](https://user-images.githubusercontent.com/192271/54162155-6db08900-444c-11e9-9f1c-8460d5572cb8.png)

There, the chosen solution for YouTube bugged in **Firefox** was to disable: 

>> the YouTube Adblock 2.2.2 extension 

The topic continued with another user of Firefox reporting: 

>> My adblock is off on Youtube - still the blank space instead of video

**Comment by laniakea64** [comment]
(In my case, I'm not using a dedicated Youtube adblock extension.  I have a number of custom filters that tend to break some sites in this type way.  Whereas Waterfox's _default_ UA says Firefox 65.0.  Thus if my experience is something to go by here, people who have the issue with Youtube should check if they're affected by UA sniffing before messing with their (non-Youtube-specific) adblock type extensions.)

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/aztdus/-/eib71rl/>: 

> This problem started over a year ago when youtube switched to polymer, and it is present in firefox as well. You can either change user agent (at least for youtube) to something other than firefox 38-6X or use modifier below https://www.youtube.com/?disable_polymer=true (you have to add `&disable_polymer=true` to subsites as well).

https://www.reddit.com/comments/ayjop0/-/ei43ry2/ includes some Polymer-related links … 

----

… re: https://github.com/MrAlex94/Waterfox/issues/880#issuecomment-471753622 above I reckon, the Firefox parts of UA strings should be less expansive (should not infer 65). I'll add this to the checklist at #882

**Comment by cjfreeze** [comment]
As of this morning with no changes to my setups Youtube now works on both Windows 10 and Mojave, I'll leave the issue open just in case but I no longer have the problem so feel free to close it if it is truly resolved.

**Comment by cjfreeze** [comment]
I should mention in my case when Youtube was not working I tested it with all extensions disabled, so adblock was not the issue (though this may be a moot point now)

**Comment by grahamperrin** [comment]
<https://www.reddit.com/comments/amsugb/-/eftbujc/> (2019-02-05): 

> … not reproducible with Waterfox 56.2.7.1 on Windows 7 Enterprise. …

I re-tested today, whilst signed in to YouTube. 

Still not reproducible for me: 

![image](https://user-images.githubusercontent.com/192271/54308466-f9015a00-45c5-11e9-8148-3ca40353b3f8.png)

![image](https://user-images.githubusercontent.com/192271/54308550-2221ea80-45c6-11e9-8232-c041233ca460.png)

**Comment by LeeBinder** [comment]
@all : I was experiencing this issue with only ONE of my 3 YT accounts when logged in (macOS High Sierra 10.13.6, and macOS Mojave 10.14.3)!! I even created a new virgin account via Profile Manager with NO add-ons and verified that indeed only 1 account when logged in triggered this "skeleton masking", which is what it's called officially. Even when looking into the YT page's source code I was seeing "skeleton" and "mask" all over the place.

Solved or rather worked-around with the awesome add-on [User-Agent Switcher and Manager](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) (by Ray):

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0`

I wanted to stay as close as possible to Waterfoxe's v.56.x

However then there was a new issue: I could not edit my Github comments anymore (no kidding)!

Same with Firefox 59 as UA (there is no 58 in the list).

When picking a higher 60.x version of Firefox as global setting, both was working (YT, Github), but for now across Waterfox I simply want to stay with how MrAlex94 chooses to identify it, which as of 56.2.7.1 is

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0 Waterfox/56.2.7`

So via Ray's User-Agent Switcher and Manager Options: White-list Mode: youtube.com
--> both work, YT and Github editing my comments :)

I don't have time right now for narrowing down which segment of the UA string YT depreciates, but maybe one of you folks do and can share, so for the next WF release, MrAlex94 can use a YT AND Github comment editing friendly US string.

Also I have not tested if an older version of WF  - which would need to use a different UA - is fully YT *AND* Github compatible.

**Comment by grahamperrin** [comment]
> Github

Best to keep the requirements for GitHub separate from the requirements for YouTube.

**Comment by grahamperrin** [comment]
### YouTube with Waterfox 56.2.8

@cjfreeze please:

1. [install](https://www.waterfoxproject.org/) (or update to) 56.2.8
2. if you previously set a user agent string for YouTube, **cease the override**
3. tell whether things are better with 56.2.8

– thanks.

----

If you do find a problem, please state: 

- the version of Waterfox
- the operating system
- the version of the OS
- the address where the problem occurred.

**Comment by LeeBinder** [comment]
@grahamperrin @MrAlex94  YEEHAAH, with 56.2.8 (installed manually because in Waterfox 56.2.7.1 Mac/ About, it still read "Waterfox is up to date") and UA-Switcher disabled: YouTube working again when logged in, and Github comment editing still working, too 👍 

Verified via https://google.com/search?q=display+user+agent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0`

Also: wow what an AWESOME new logo!! the W as a blue watery wave with depth and perspective, the fox face worked in smoothly and beautifully, lively colors and even a slight green tint on the left. That graphics designer (who is it ?) deserves a gold🥇 !

**Comment by grahamperrin** [comment]
Thanks for the follow up 👍

Re: the logo,  I quoted you at https://www.reddit.com/comments/asb7hg/-/eime65l/

@cjfreeze if you, too, find that things are OK now with YouTube, you can close this issue (the button below).

**Comment by grahamperrin** [comment]
@mzso I can't post links to Disqus so in response to your https://disqus.com/home/discussion/waterfox/waterfox_680a1_release_waterfox_web_browser/#comment-4467552164 please ▲ see above and ▶ comments such as https://www.reddit.com/comments/ayjop0/-/ei1i6pm/ re: A/B testing.

**Comment by mzso** [comment]
> 
> 
> @mzso I can't post links to Disqus so in response to your https://disqus.com/home/discussion/waterfox/waterfox_680a1_release_waterfox_web_browser/#comment-4467552164 please ▲ see above and ▶ comments such as https://www.reddit.com/comments/ayjop0/-/ei1i6pm/ re: A/B testing.

Thanks.

**Comment by grahamperrin** [comment]
@cjfreeze can you confirm that Waterfox 56.2.10 fixes this issue for you? 

Thanks

### Postscript

For reference only, from [Waterfox 56.2.10 Release | Waterfox Web Browser](https://www.waterfox.net/blog/waterfox-56.2.10-release-download/):

> … Waterfox has now updated its user agent … should also fix issues with Google doing [A/B testing](https://en.wikipedia.org/wiki/A/B_testing) on YouTube …

**Comment by cjfreeze** [comment]
Resolved, thanks!
