### ISSUE TITLE
will this work with mountain lion ??????

### ISSUE THREAD

**Issue by snes666** [BrowserWorks/waterfox#889]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by snes666** [comment]
I'm new to this whole waterfox thing if not can you make it compatible in the next update?????? 
@alex

**Comment by grahamperrin** [comment]
[Wordpress Dashicons display issue on Mac OS X 10.8.5 · Issue #823 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/823)
