### ISSUE TITLE
Strange issue with Microsoft Speech Recognition

### ISSUE THREAD

**Issue by ClanstvoR** [BrowserWorks/waterfox#89]
Sometimes I use MS Speech Recognition and I noted that only Waterfox (among many browsers I use) influence somehow on Speech Recognition. Speech Recognition's small gadget on the screen shows on it's right side blue circle when is busy recognizing words. It recognize words in real time or this circle is on for e.g 1 second. When I start Waterfox circle is nonstop running, CPU get to max and PC totally slows down. When I close Waterfox everything get back to normal. And I have no sound coming from Waterfox (or watch any video etc) but for Speech Recognition it looks like it constantly recognizing some sound from Waterfox ?!

**Comment by MrAlex94** [comment]
If you still have this issue, please re-open. 

I believe this was caused by accessibility features not being supported with e10s enabled. If it still occurs, you could try disabling e10s (about:preferences > Enable mulit-process Waterfox).
