### ISSUE TITLE
New logo displays poorly on taskbar

### ISSUE THREAD

**Issue by morags** [BrowserWorks/waterfox#891]
**Describe the bug**
The new logo adopted on v56.2.8 displays poorly on the taskbar. The duel "bunny ears" create the illusion of "[double vision](https://en.wikipedia.org/wiki/Diplopia)", and with many windows might even cause dizziness, depending on the configuration. Conventional icons, which have a single focus point, don't do that.

**To Reproduce**
1. Look at taskbar.
2. Look away.
3. Look at taskbar again.
4. Get dizzy.

**Expected behavior**
Need a simple, single-focus-point icon.

**Screenshots**
![Modified taskbar](https://user-images.githubusercontent.com/5771389/54431715-d0956f00-472f-11e9-8415-28093c845a25.png)
![Conventional taskbar](https://user-images.githubusercontent.com/5771389/54432003-98daf700-4730-11e9-97c0-b32815f3b997.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Mod: 7+ Taskbar Tweaker

**Additional context**
AFAICT icon design guidelines usually assume a single point of focus; [Apple specifies it](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

**Comment by hockeymikey** [comment]
Expressed my views perfectly. Pains me to look in the corner now at the ugly icon that exists now.

**Comment by morags** [comment]
As an interim solution you can use [Resource Hacker](http://www.angusj.com/resourcehacker/) to replace the icons embedded in the Waterfox executable with ones from previous versions. There are guides online on how to do this.

**Comment by kazerniel** [comment]
I actually quite like the new logo. Finally something unique, not a Firefox logo knockoff.

(Though I'm using Win7 with uncombined taskbar buttons, so they don't repeat in quick succession.)

![waterfox logo](https://user-images.githubusercontent.com/5689996/54457935-9f7e6400-475a-11e9-9380-b4f6feea02d9.jpg)

Edit: Some addons let the user pick an icon from multiple versions, not sure if that would be viable for the whole browser. (addons eg. LastPass, Google Shortcuts, Stylus)

**Comment by maxoku** [comment]
It's rather generally a poor design. 
1. the blue "W" is already taken by Word.
2. In thumbnails it looks more like a bird or variation of a state emblem.
3. It simply looks ugly.
4. Barely can see it on a blue title-bar
Please try again and maybe consult it with users.

**Comment by grahamperrin** [comment]
> single point of focus;

From the current HIG: 

>> a single, centered point 

– and Apple's primary example of something with a single, centred point has two points of focus, neither of which is centred: 

![image](https://user-images.githubusercontent.com/192271/54467991-b33cc100-4780-11e9-8409-e3887d43021e.png)

**Comment by grahamperrin** [comment]
> blue "W" is already taken

https://www.google.co.uk/search?hl=en&tbm=isch&source=hp&biw=&bih=&ei=s0aMXK_sB5DPwQKth59o&q=%22blue+W%22+logo

> by Word.

![image](https://user-images.githubusercontent.com/192271/54468404-25fb6b80-4784-11e9-8ba5-b93e2c8b3503.png)

… and https://logos.fandom.com/wiki/Microsoft_Word_for_Mac and so on. 

Microsoft makes wild changes to logos and so on. 

A change for Waterfox is not unreasonable. 

### Similarities 

See https://www.reddit.com/comments/asb7hg/-/eguft5t/ in particular, the screenshot of what was found by Google.

**Comment by grahamperrin** [comment]
> maybe consult

Certainly there was Alex's post about the logo, a few weeks ago. Most of the replies were unrelated to the logo.

**Comment by maxoku** [comment]
> Certainly there was Alex's post about the logo, a few weeks ago.

By consulting I mean also noticing users about it e.g. in the change log. 
How was I suppose to know that Alex was planning to change the logo?

**Comment by hockeymikey** [comment]
> How was I suppose to know that Alex was planning to change the logo?

Exactly, I'm not on reddit everyday, so I didn't see it until after the fact when everything was changed. I still think the best solution would be have people in the community come up with designs (there has to be tons of great graphic designers out there) and have some voting for people to pick the best one. Less people would complain about a logo change and honestly you'll get a better logo with all the input/designs from multiple people instead of just one.

**Comment by grahamperrin** [comment]
Change logs are usually for changes that have occurred, not for roadmaps. 

> … not on reddit everyday, …

There's also Twitter, https://twitter.com/Waterfoxproject/status/1097870975738228736

> … multiple people instead of just one.

There's enough attention to detail, in the logo, for me to believe that more than one person was involved.

**Comment by morags** [comment]
All of this doesn't matter. I can appreciate that a lot of effort went into the logo, it's just not well-suited for taskbar use.

**Comment by grahamperrin** [comment]
<http://disq.us/p/20g839a>: 

> For me the new icon is far better on my windows taskbar. Depends on the selected color of the windows taskbar. For that reason it is better to provide a few options.

**Comment by maxoku** [comment]
> There's also Twitter

Not everyone has twitter or reddit and follow everyone. Every user however has a change log popping at them after every update. So it's the perfect place to inform users about such major changes.

**Comment by grahamperrin** [comment]
> popping at them after every update

I forgot about that. 

When I think of it as a blog post (not a change log), it makes sense.

**Comment by SmiVan** [comment]
The logo's been changed so this issue should probably get closed or at least reviewed.
