### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by bitwombat** [BrowserWorks/waterfox#895]
https://www.waterfoxproject.org/en-US/waterfox/ has the word "Brower"

**Comment by Ibuprophen** [comment]
I'm sure that it's just an innocent oversight but, it's good for a laugh too... LMAO! :-) 


~Ibuprophen

**Comment by grahamperrin** [comment]
Meta, tracking: #582

**Comment by MrAlex94** [comment]
Haven't you heard of a web brower before? 🤨

**Comment by grahamperrin** [comment]
I thought of this bug um feature on the bus this morning, couldn't remember which letter had been dropped. I quite like bowser.
