### ISSUE TITLE
Crazy tabs

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#896]
For some time my tabs act crazy. It's when I open another tab from a link with middle mouse button. Normally it should open on the right from active tab. But sometimes it opens on the left! And very often it opens at the end on right instead of next to active one.

I've investigated it and figured out that the culprit is an add-on Tab Mix Plus. Problem here is that this add-on is a legacy extension that didn't have any updates for a very long time. The only updates was from Waterfox itself. So my guess is that one of its updates made some conflict with the add-on or something like that.

Please investigate if it could be fixed somehow without removing the add-on.

**Comment by grahamperrin** [comment]
> Tab Mix Plus. … didn't have any updates for a very long time. 

You're probably using an outdated version. 

0.5.6.0 is recent, dated 2019-02-07. 

https://bitbucket.org/onemen/tabmixplus/downloads/

Please note, the developer of Tab Mix Plus is working on another update, for compatibility with Waterfox 56.2.8.

**Comment by laniakea64** [comment]
> Please investigate if it could be fixed somehow without removing the add-on.

Hi @maxoku , can you please test https://github.com/MrAlex94/Waterfox/pull/892 and let us know if that does the trick?  Thanks!

**Comment by maxoku** [comment]
@grahamperrin 
> 0.5.6.0 is recent, dated 2019-02-07

I thought they abandoned it. I had version from Mozilla site so it hasn't updated at all.
Thanks for the information.

@laniakea64 
> Hi @maxoku , can you please test #892 and let us know if that does the trick? Thanks!

It seems I'm too stupid for it. I don't know how to patch/build it for testing.

**Comment by laniakea64** [comment]
> I don't know how to patch/build it for testing.

What OS are you using?

**Comment by maxoku** [comment]
@laniakea64 
> What OS are you using?

Windows 8.1, but I might soon reinstall to Windows 7.

**Comment by laniakea64** [comment]
Thanks.  I added instructions for modifying omni.ja in Windows.

**Comment by maxoku** [comment]
@laniakea64 Thanks. It seems that it worked.

**Comment by 613TheEvil** [comment]
I have the exact same problem, it started recently, probably after a Waterfox update? I don't know. My tab mix plus used to run smoothly, opening new tabs next to the parent tab, on the right side. Then, suddenly they open randomly on the left, or at the end of all the tabs... Is there really a fix?

**Comment by laniakea64** [comment]
> Is there really a fix?

Yes, and the fix is https://github.com/MrAlex94/Waterfox/pull/892 , it just hasn't been merged yet.

**Comment by 613TheEvil** [comment]
So, I can only wait? I see there is some code in it, could I put it somewhere? Also, I use the 0.5.5.0 version of Tab mix plus, could I/should I install the latest? I use Win 7 64bit and the latest Waterfox. But I see more versions here, I am tempted to try. https://bitbucket.org/onemen/tabmixplus/downloads/
I can also see the fix can be applied manually by tampering with omni.ja file, whatever this is... I could do it and probably succeed, but I could also make a bigger mess than I have in my hands now, what do you suggest? And how soon could we expect this fix to be available?

**Comment by 613TheEvil** [comment]
I installed tab_mix_plus-0.5.7.0pre.190408a1.xpi and so far it looks like it's back to normal, I should test it more though.

**Comment by laniakea64** [comment]
The Waterfox side fix is now merged.  Close this issue?

**Comment by maxoku** [comment]
@laniakea64 Great news. When we can expect new update?
