### ISSUE TITLE
No video at Instagram

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#898]
From some time I can't watch any videos on Instagram. When scrolling the main page there's no picture/video in those posts like it was blocked with ad-blocker or something. If previewed in single post there's only black where picture should be, without play icon on center.

**Comment by grahamperrin** [comment]
▶ https://www.reddit.com/comments/b0evjb/-/eiinzea/?context=1 

– please note Alex's comments.

Also: 

- [Instagram Blank Page OSX 10.13.4 : waterfox](https://www.reddit.com/r/waterfox/comments/b2n3cg/instagram_blank_page_osx_10134/)

**Comment by maxoku** [comment]
@grahamperrin 
Thanks, but it seems to start working today by itself. Maybe Instagram fixed it.

**Comment by grahamperrin** [comment]
https://www.instagram.com/p/Bu53KI7B-G6/ working for you?

**Comment by maxoku** [comment]
Today not, stopped again, but after applying that css it started to work again, strange.

**Comment by grahamperrin** [comment]
Works for me now with Waterfox 56.2.10 on FreeBSD-CURRENT. 

@maxoku can you confirm the fix? 

If so, please close the issue. Thanks.
