### ISSUE TITLE
DRM enabled but not effective for ITV Hub

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#899]
Spun off from: 

- https://redd.it/aog4s5 for Waterfrox 56.2.7.1
- https://github.com/MrAlex94/Waterfox/issues/882#issuecomment-472656276 for pre-release 56.2.8

### Bug

Waterfox 56.2.8 with Widevine Content Decryption Module 1.4.9.1088 can not play ITV Hub content. 

### Steps

Screenshots, Windows 7 Enterprise: 

![image](https://user-images.githubusercontent.com/192271/54685162-0494d980-4b0e-11e9-8d8a-f04ec2bbfaa0.png)

![image](https://user-images.githubusercontent.com/192271/54685178-137b8c00-4b0e-11e9-9209-6cd8bd0dabb1.png)

![image](https://user-images.githubusercontent.com/192271/54685191-1b3b3080-4b0e-11e9-9e4a-7462569527e5.png)

![image](https://user-images.githubusercontent.com/192271/54685244-44f45780-4b0e-11e9-908e-30776116efed.png)

-- with and without overriding the cache, reloading the page does not work around the issue. 

Meta, tracking: #538

**Comment by grahamperrin** [comment]
I forgot to include an address. 

A current example: https://www.itv.com/hub/vera/1a7314a0033

(Playback requires sign in.)

If it helps to understand the issue … on Manjaro Linux, the content: 

- does not play in Brave 
- does play in Chromium 

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36`

**Comment by grahamperrin** [comment]
From https://www.waterfox.net/blog/waterfox-56.2.10-release-download/

> … I will also be investigating updating related DRM code to be inline with ESR releases …

I suspect that ITV Hub and Spotify Web Player #982 are examples of services that require updated code.

**Comment by grahamperrin** [comment]
FWIW https://www.reddit.com/r/firefox/comments/c17f7t/-/erbmi39/

> …  sites like 4od, and the ITV one still require flash to stream videos.

**Comment by grahamperrin** [comment]
_If_ it's true that Widevine > 1.4.9.1088 is required by ITV Hub, these three Mozilla bugs might help: 

- [1486482 - [meta] Update Widevine CDM to Version 4.10.1146.0 (Windows, Linux, Mac)](https://bugzilla.mozilla.org/show_bug.cgi?id=1486482)
- [1499880 - [meta] Update Widevine CDM to Version 4.10.1196.0 (Windows, Linux, Mac)](https://bugzilla.mozilla.org/show_bug.cgi?id=1499880)
- [1514206 - Update rules to serve Widevine 4.10.1146.0 to Windows users instead of 4.10.1196.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1514206)

**Comment by grahamperrin** [comment]
56.2.12, FreeBSD-CURRENT: 

- live https://www.itv.com/hub/itv there's playback but nothing audible
- live https://www.itv.com/hub/itv2 I'm directed to https://help.itv.com/hc/en-us/articles/360004308253-I-m-having-trouble-streaming-the-live-channels
- live https://www.itv.com/hub/itv4 there's playback but again, no sound
- https://www.itv.com/hub/the-saint/ENT1414a0021 the usual, endless asynchronous progress indicator (four dots)

**Comment by hawkeye116477** [comment]
Maybe looking into that with mozregression tool could help, but unfortunately I can't, cuz it's geo-locked.

**Comment by grahamperrin** [comment]
Cross reference https://redd.it/f8fyt5

Side note: not mentioned by me above or at https://redd.it/aog4s5 but last year, I _did_ experiment with numerous user agent (UA) overrides.
