### ISSUE TITLE
Crash on Windows 7 x64 when going to a different YouTube video

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#90]
Nearly every time I try to go to a different YouTube video, Waterfox crashes almost as soon as the actual player loads. I have YouTube set to use the HTML5 player where possible. I'm _extremely sure_ I'm on the latest version of Waterfox, scream at me if I'm not.
Here's the crash info that Windows gives me:

```
  Problem Event Name:	APPCRASH
  Application Name:	waterfox.exe
  Application Version:	49.0.3.6156
  Application Timestamp:	5821effb
  Fault Module Name:	xul.dll
  Fault Module Version:	49.0.3.6156
  Fault Module Timestamp:	5821f1b9
  Exception Code:	c0000005
  Exception Offset:	0000000000d22bf7
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	263185
  Additional Information 1:	4728
  Additional Information 2:	47283e0d9dde84c8af1a82818a1a85a6
  Additional Information 3:	8c73
  Additional Information 4:	8c734c0fc68d4f00a621b7e7b1719a3f
```

EDIT: Just experienced another crash right now, seemingly caused by attempting to change where I was in a video.

**Comment by grisotto** [comment]
The lasted version is Waterfox 50.1.0 Setup.
https://www.waterfoxproject.org/downloads

**Comment by grahamperrin** [comment]
@tomatohentai is this issue reproducible with Waterfox 56.0.3?

**Comment by MrAlex94** [comment]
Switched away from Clang-cl to Visual C++, which may have been the issues of the crashes back then. Please re-open the issue if it still persists.
