### ISSUE TITLE
Waterfox freeze & Reducing system resources

### ISSUE THREAD

**Issue by hubitor** [BrowserWorks/waterfox#900]
**Describe the bug**
Waterfox sometimes freezes and causes a system freeze when many tabs are open. When the freeze occurs I'm forced to reboot my system. This behavior I have also noticed in Firefox before. 

**To Reproduce**
The freeze might occur when some windows with some dozens tabs in each one of them are opened.  

**Expected behavior**
No freeze...

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 56.2.8

**Additional context**
Since I'm not sure if this happens when my system resources are limited I wanted to reduce the resources that Waterfox needs. I've tried to accomplish this with some addons such as "Tab Wrangler", "Auto Tab Discard", "Dormancy" but none of them seem to work.

**Comment by grahamperrin** [comment]
> system resources

Can you describe your system in more detail? 

Hardware; the amount of memory; and so on. 

Thanks

**Comment by grahamperrin** [comment]
> … to reduce the resources that Waterfox needs …

Re: https://www.reddit.com/comments/atuw4c/-/eh3o8we/ maybe try **Auto Unload Tab** but NB "… Proceed with caution because with some web content, load after unload can increase use of memory. …". 

> Auto Tab Discard

[strict_min_version in manifest.json, and declarations of compatibility at AMO · Issue #83 · rNeomy/auto-tab-discard](https://github.com/rNeomy/auto-tab-discard/issues/83)

> Dormancy

[strict_min_version in manifest.json, and declarations of compatibility at AMO · Issue #39 · autonome/Dormancy](https://github.com/autonome/Dormancy/issues/39)

**Comment by grahamperrin** [comment]
> Linux

@MrAlex94 FYI looking ahead (I don't imagine this landing in Firefox 68): 

- Mozilla bug [1532955 - Implement low-memory detection on Linux for automatic tabs discard](https://bugzilla.mozilla.org/show_bug.cgi?id=1532955)

**Comment by hubitor** [comment]
> Can you describe your system in more detail?
> 
> Hardware; the amount of memory; and so on.

memory: 4 x  DIMMs
- Size: 8192 MB
- Type: DDR3
- Speed: 1333 MT/s

CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
graphics card: nVidia GM107 [GeForce GTX 750 Ti]
network: Intel 82579V Gigabit Network Connection

My issue could be related to this:
[https://superuser.com/questions/1115983/prevent-system-freeze-unresponsiveness-due-to-swapping-run-away-memory-usage/1142197#1142197](https://superuser.com/questions/1115983/prevent-system-freeze-unresponsiveness-due-to-swapping-run-away-memory-usage/1142197#1142197)

I've removed Dormancy and Auto Tab Discard and installed Auto Unload Tab which seems to be doing the job fine. Thanks!

**Comment by grahamperrin** [comment]
Thanks, would you like to close this issue? 

Technically, I don't imagine a freeze (or apparent freeze) of Waterfox _causing_ a system freeze. 

> … forced to reboot my system. … noticed in Firefox before.

That, too, might support the view that the (Linux) system requires attention.
