### ISSUE TITLE
Checkboxes in some addons are not displayed

### ISSUE THREAD

**Issue by hubitor** [BrowserWorks/waterfox#901]
**Describe the bug**
I've installed some addons such as "Tab Wrangler" and "Auto Tab Discard" and noticed that the checkboxes in their preferences are not displayed.

**To Reproduce**
1. Install  addon "Tab Wrangler" or "Auto Tab Discard"
2. Go to Preferences

**Expected behavior**
Display checkboxes

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 56.2.8

**Comment by laniakea64** [comment]
What version of GTK 3 do you have?
What GTK theme are you using?

**Comment by hubitor** [comment]
I'm using KDE Plasma 5.15.3 with Breeze Dark theme.

**Comment by laniakea64** [comment]
FWIW, I do see those checkboxes with Breeze-Dark GTK theme on Xubuntu 18.04.

Again, what version of GTK 3 do you have?

**Comment by hubitor** [comment]
This package is installed:
gtk3 1:3.24.7+11+g3a959e984f-1

**Comment by laniakea64** [comment]
I tested official Waterfox 56.2.8 in Antergos + KDE + Breeze-Dark theme (set as desktop theme and as GTK 2/3 theme).  The checkboxes are visible there too.

The GTK 3 version I got in Antergos is `1:3.24.7+25+g17665f06e3-1`.  Since Antergos directly uses Arch Linux repos, can you check if that update is available to you?

**Comment by hubitor** [comment]
Thanks for checking!

The package:
gtk3 1:3.24.7+25+g17665f06e3-1 is available and I've just installed it. I've rebooted and checked again. The problem persists.
I've checked other installed addons and this the result:

Affected addons:

- 	HTTPS Everywhere
- 	NoScript
- 	Restart
- 	Snap Links
- 	Tab Mix Plus
- 	Export Tabs URLs
- 	Tree Style Tab
- 	Session Manager

Not Affected addons:
- 	Adblock Plus

As example, this is how Tree Style Tab normally looks like:
[http://johnbokma.com/mexit/2011/07/22/tree-style-tab-1-appearance.png](http://johnbokma.com/mexit/2011/07/22/tree-style-tab-1-appearance.png)

and in my case:
![TreeStyleTabConfiguration](https://user-images.githubusercontent.com/6114541/54724871-312c0e00-4b6d-11e9-96d9-5a10603f4adc.png)

check boxes and radio boxes are not visible anymore. I know for sure that e.g. Tab Mix Plus was working fine before but I have no idea what has changed.

**Comment by laniakea64** [comment]
> check boxes and radio boxes are not visible anymore.

Nor is the entire Breeze-Dark theme!  Your Tree Style Tab options is supposed to look like this -

![Screen shot 2019-03-20 1](https://user-images.githubusercontent.com/16628411/54729602-e3a6a580-4b5a-11e9-8b76-a146afd2c560.png)

Check your settings in System Settings > Application Style > GNOME/GTK Application Style

**Comment by hubitor** [comment]
@laniakea64: Many thanks!
check boxes are back...
The selected GTK2 and GTK3 themes were Breeze and not Breeze Dark. Somehow the settings were changed.
