### ISSUE TITLE
Language problems in Polish

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#902]
First the translation of Start Page in Polish is too long. Probably it's because of Firefox translation in the first place, but Waterfox could fix it.
![wat](https://user-images.githubusercontent.com/17256400/54712017-8a834580-4b4b-11e9-8702-fdb1a2603261.jpg)
In Polish it is "Strona startowa programu Waterfox" which literally means "Start page of Waterfox application". So I suggest to change it to "Strona Startowa Waterfox" to be more like in the original.

Other things are the popup etiquette when hovering the reload and stop buttons. In Firefox it was only "Reload" and "Stop" I think and it was translated to Polish. Seems like in Waterfox it was changed to "Reload current page" and "Stop loading this page" so maybe for that reason they aren't translated at all. So please translate it or reverse to single words that it maybe be translated.

**Comment by hawkeye116477** [comment]
`Other things are the popup etiquette when hovering the reload and stop buttons. In Firefox it was only "Reload" and "Stop" I think and it was translated to Polish. Seems like in Waterfox it was changed to "Reload current page" and "Stop loading this page" so maybe for that reason they aren't translated at all. So please translate it or reverse to single words that it maybe be translated.`
 
But it's translated, I've *Odśwież bieżącą stronę*.

**Comment by maxoku** [comment]
@hawkeye116477 
> But it's translated, I've Odśwież bieżącą stronę.

I don't and never had in Waterfox.

**Comment by hawkeye116477** [comment]
@maxoku So it's probably something bad on your side, are you sure that you aren't using language pack for Firefox on Waterfox?

**Comment by maxoku** [comment]
I don't use any language pack. Waterfox has its own language packs after all.

**Comment by maxoku** [comment]
It turned out it was about buttons from Classic Theme Restorer. I sometimes forget those functions aren't native, sorry lol. I've asked Aris about it and he doesn't know how to fix it.

So please fix the first issue.

**Comment by maxoku** [comment]
Now it's "Strona startowa programu Waterfox Classic" 😒
Can't you just leave it "Start Page" and it will be short in every language?
