### ISSUE TITLE
Import Data broken in non US languages

### ISSUE THREAD

**Issue by NebelNidas** [BrowserWorks/waterfox#903]
I haven't tried all languages yet, but with all I have tested so far, when you head to "Show all Bookmarks" -> "Import and Backup" -> "Import Data from Another Browser" this error shows up:

![Waterfox import bug](https://user-images.githubusercontent.com/48808497/54783445-afe28300-4c21-11e9-829a-9945caa4743e.PNG)

It seems to work only with English (US).
Edit: Probably related to #849

**Comment by decembre** [comment]
It seems working for me:
I do an import my bookmarks by choosing a previous backup (json) and it worked fine...
Maybe another addon interfere ?
I use a french interface.

**Comment by NebelNidas** [comment]
Because that's the wrong function. I mean the "Import Data from Another Browser" one.
Also, it occurs without having any Add-ons installed, too.

**Comment by hawkeye116477** [comment]
I have Polish lang and also has that. On en-US no problem.

**Comment by NebelNidas** [comment]
Sad that there's still no response. It shouldn't be that hard to just make it default back to the US strings.
