### ISSUE TITLE
The Open Add-Ons menu item sometimes randomly doesn't work

### ISSUE THREAD

**Issue by NebelNidas** [BrowserWorks/waterfox#905]
**Description**
Sometimes, regardless if you have e10 enabled or not, even in fresh installs, the "Add-Ons" menu item in the "Tools" menu won't work! Entering "about:addons" manually still works, though.

**To Reproduce**
Unfortunately, I don't know any way on how to reproduce it. It seems to happen very randomly and quite rarely, too. 

**Screenshots**
![Waterfox addons wont open](https://user-images.githubusercontent.com/48808497/54788083-2d13f500-4c2e-11e9-85c2-d7b890352c07.gif)

**Desktop:**
 - OS: Win7 x64
 - All Waterfox 56 releases, maybe even older

**Comment by laniakea64** [comment]
Can you reproduce this in [Safe Mode](http://kb.mozillazine.org/Safe_Mode)?
When this issue occurs, do you see anything related in the Browser Console (Ctrl-Shift-J)?

Also, can you please post your full list of extensions as reported in `about:support`?

**Comment by NebelNidas** [comment]
I could list them here, but as already said, it can also occur without any extensions installed. When I once set up a friend's computer, this happened to a completely fresh install of Waterfox.
Speaking of Safe Mode, I would have to at least use it for the next entire month for it to randomly happen again; it really doesn't occur often :/

**Comment by NebelNidas** [comment]
I don't get any errors in the Console, but with CSS warnings and reflows on, this shows up:

> reflow: 0.3ms function rect, eval line 3
> reflow: 0.06ms function get topTabY, tab.js line 1053
> reflow: 0.22ms
> reflow: 8.44ms function onxblpopupshowing, popup.xml line 281
> reflow: 8.38ms
> reflow: 0.36ms function rect, eval line 3
> reflow: 0.08ms function get topTabY, tab.js line 1053
> reflow: 0.2ms

**Comment by grahamperrin** [comment]
When I find this bugging Waterfox Classic, it's always (or nearly always) coincidental with – maybe a symptom of – a problem with **session management**. 

I might reproduce it. 

Mozilla bugs: 

- [874381 - [meta][SessionStore] Clean up and document session restore](https://bugzilla.mozilla.org/show_bug.cgi?id=874381)
- [1330633 - (ss-reliability) [meta] Sessionstore reliability tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=1330633)
- [1330635 - (ss-perf) [meta] Sessionstore performance tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=1330635)

----

Side note, for anyone who's interested: 

- [1330638 - (ss-feature) [meta] Sessionstore feature development](https://bugzilla.mozilla.org/show_bug.cgi?id=1330638)

**Comment by NebelNidas** [comment]
I never thought about that, but it may be the reason, yeah. I always use session restore on startup, in the past with TMP and the built in one, currently with Session Manager. It happened to me with all three. Maybe it's the underlying system that's broke 🤔

**Comment by grahamperrin** [comment]
First attempt to reproduce: 

> the "Add-Ons" menu item in the "Tools" menu won't work! 

- not reproducible (using a traditional menu bar)
- the browser **did** cease responding to <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>A</kbd> …

**Comment by grahamperrin** [comment]
Second attempt to reproduce: 

- success. 

Screen recording, with (non-visible) <kbd>Control</kbd>-<kbd>T</kbd> and <kbd>Control</kbd>-<kbd>W</kbd> to open and close two tabs:

- https://put.re/player/yYExonEw.mp4
- [2019-10-12 13:37 Waterfox issue 905.zip](https://github.com/MrAlex94/Waterfox/files/3720663/2019-10-12.13.37.Waterfox.issue.905.zip)

To reproduce this issue, I enabled a bugged feature of legacy **Vertical Tabs Reloaded** 0.8.5.2:

- caa:addon/vertical-tabs-reloaded

☑ Hide tabs in fullscreen

When it's known that manual session management will fail (in the recording above, SessionBuddy can not present its Save dialogue), it's preferable to: 

1. crash the browser
2. allow restoration of the last auto-saved session

– in Session Manager, this should appear amongst backup sessions. 

To crash in these situations I use **Crash Me Now! (Simple)**: 

- caa:addon/crash-me-now-simple
- https://github.com/luser/crashme-simple/
