### ISSUE TITLE
Unused search buttons in omnibox not really invisible

### ISSUE THREAD

**Issue by NebelNidas** [BrowserWorks/waterfox#906]
**Description**
When Mozilla basically merged the URL bar with the search bar, they added the search engine buttons on the bottom. But they did it poorly - exactly like in the original search bar!
Cause there isn't a new button added for every new engine, the buttons are already there. For us users to not notice they made them invisible, but with a poor technique. If you have Add-Ons like GMF installed (as mentioned in #904 ), these buttons will become visible. Not really nice from a UX point of view.

**To Reproduce**
1. Install GMF (caa:addon/glassmyfox)
2. Check the "Buttons" checkbox
3. Type something in the omnibox or search box

**Expected behavior**
These buttons should either be completely invisible or only be created when really needed.

**Screenshots**
Omnibox:
![Waterfox omnibox buttons issue](https://user-images.githubusercontent.com/48808497/54789178-e6c09500-4c31-11e9-92b4-dfa1efc4e0b4.png)
Search Box:
![Waterfox search box buttons issue](https://user-images.githubusercontent.com/48808497/54789287-4b7bef80-4c32-11e9-8450-04809fcd803d.png)

**Desktop:**
 - OS: Win7 x64
 - All Versions, I guess

**Footnote**
Just a small cosmetic flaw, but hey.

**Comment by laniakea64** [comment]
Does adding this to [userChrome.css](http://kb.mozillazine.org/UserChrome.css) help? -
```
.searchbar-engine-one-off-item.dummy {
  visibility: hidden !important;
}
```

**Comment by NebelNidas** [comment]
Yes, this works! Thanks! :D
However, I do think this should be set as default. Maybe Alex could implement it in the next release? Or would this break something with some other Add-On?
