### ISSUE TITLE
Android Waterfox removed from Google Play Store?

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#907]
Following [the link](https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox) from the official waterfox website yields a "not found" error, on both desktop browser and my android phone. If I search for waterfox in either the desktop website for the play store or using the app on my phone, I get no results for it (only for other browsers).

Also found a thread on the [subreddit](https://www.reddit.com/r/waterfox/comments/b49d6c/is_the_android_version_dead/) where people seem to be having the same problem. Has the app been removed for some reason and is it coming back any time soon?

**Comment by grahamperrin** [comment]
[Site: rationalise the platform-specific offerings · Issue #467 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/467)

**Comment by ghost** [comment]
Sorry, I'm confused. Apologies if I'm missing something obvious but I'm finding that issue you linked to somewhat confusing to read.

Am I to assume then the button on the website that links to the play store app has been broken for over a year? Based on you reporting it in March 2018. But Waterfox was still on the play store. I came across it in October last year when I went from an iPhone to a Samsung S8. It was the first result when I searched for it, version 60.1.0 I believe (or similar), and was rather buggy so I stopped using it and went with standard Firefox. Every now and then I would search for Waterfox on play store looking to see if it had been updated and it had always shown up until quite recently. I think I searched for it beginning of this month and it was there. Searched for it today and it's gone.

What has happened to it is what I'm asking. Removed for any particular reason? Is it coming back any time soon (hopefully updated with bug fixes)?

**Comment by Ibuprophen** [comment]
I see the ARM version on the Play Store... 

[Waterfox-ARM](https://user-images.githubusercontent.com/18060271/55036857-459b5b00-4ff2-11e9-8a9e-b86cc712d339.jpg)

... I just took this screenshot too. 


~Ibuprophen

**Comment by ghost** [comment]
It likely shows up for you because you already have it installed. I don't have waterfox installed anymore, and I also removed it from my library ages ago.

[This is what I get](https://imgur.com/a/IjPQ0ZL) when I search for waterfox in various forms on the play store (ie nothing but other browsers).

I'm starting to think it's been removed for new users because it was somewhat broken and perhaps [this new version of Waterfox announced last week](https://www.reddit.com/r/waterfox/comments/b3jrgc/alpha_of_the_next_generation_of_waterfox_along/) extends to a new android version too (seems a bit more than coincidence the app vanishes from the store around the same time MrAlex94 announces next version). Either that or he's just removed it because he can't find the time to develop it and probably just figured it wasn't worth bothering with anymore given the number of bugs present in it. Either way, would have been nice to be informed about it.

Maybe someone could tweet him or, pm him on reddit asking what's up since he doesn't seem to respond to things on here much (I would, but I'm not registered - nor will I ever be - on those platforms).

**Comment by grahamperrin** [comment]
https://redd.it/b6rg1w

> … Android browser is temporarily removed from the Google store so it's updated and inline with the new guidelines.

**Comment by Ibuprophen** [comment]
@dildoswaggins, go to the following link to join in the Waterfox Beta Program... 

https://play.google.com/apps/testing/org.waterfoxproject.waterfox

... Once joined, give it about 5 minutes or so and then go to that same Google Play Store link for Waterfox and see if it works. 

It should reflect "Waterfox Web Browser - Open, Free and Private (Beta)". 

Hopefully it will work for you now. 

Good Luck! 


~Ibuprophen

**Comment by ghost** [comment]
Ah thank you. I guess thats all explained then so ill close this.
