### ISSUE TITLE
Gnome Keyring with Waterfox [Question]

### ISSUE THREAD

**Issue by hubitor** [BrowserWorks/waterfox#908]
In Chrome/Chromium it is possible to set a password store in the file: 

`chrome-flags.conf
`

with the flag:

`--password-store=<basic|gnome|kwallet|detect>
`

Is there something similar for Waterfox?
How can Gnome Keyring be used with Waterfox?
How does Waterfox save credentials?

**Comment by hawkeye116477** [comment]
I found this `https://github.com/swick/mozilla-gnome-keyring`, maybe it will be useful for you.

**Comment by hubitor** [comment]
@hawkeye116477 : Thanks! I tried it but it didn't work. I'm using now pass+browserpass and I like it so far.
