### ISSUE TITLE
crash report pop up every time click within Tutanota

### ISSUE THREAD

**Issue by linuxgirl22** [BrowserWorks/waterfox#909]
**Describe the bug**
Crash report pop-up per click.

**To Reproduce**
1. any mouse click to open an email, refresh page, anything. 

**Expected behavior**
No crash report pop-up per click. 

**Screenshots** ... (expanded the pop-up to show error report also)
![pop up](https://user-images.githubusercontent.com/35760727/55245188-92717280-523a-11e9-9603-fe6bcecc230d.png)

**Desktop (please complete the following information):**
Manjaro KDE Stable.

**Additional context**
I asked on Tutanota's github and they were helpful in saying: 
"The error is caused by the 3 things:
    Waterfox not implementing Promises correctly (because old Gecko was not): MrAlex94/Waterfox#857
    Waterfox setting userAgent to Firefox 60 in one of the recent versions
    Us expecting it to not do this two things
We have a workaround for Waterfox and Palemoon but we need to know that it's Waterfox and not Firefox.
Setting your userAgent to Waterfox should help."
Also, "The problem may be silenced with our next search update. Maybe we should just enable our fix for all Firefox 60, real and not."

about:config ... 
![different overrides](https://user-images.githubusercontent.com/35760727/55245465-1deb0380-523b-11e9-853f-d366e5f38b30.png)

Just reporting the bug incase it's useful or anything can be done to work with Tutanota, and because I don't know what override to set things to. 
Thanks.

**Comment by grahamperrin** [comment]
>> … Waterfox setting userAgent to Firefox 60 in one of the recent versions …

I see no evidence of that. Am I missing something? 

I _was_ able to produce an error by signing in whilst _wrongly_ using a 60-based string. 

No such error when I allowed a string that's normal (on FreeBSD-CURRENT): 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.12`

**Comment by linuxgirl22** [comment]
My apologies, as I think I must have updated a different place with the news that Tutanota fixed things.  There's not this issue now.
