### ISSUE TITLE
Waterfox Portable is always opening a second Waterfox executable on the Windows Taskbar, regardless of shortcut targeting

### ISSUE THREAD

**Issue by notNSANE** [BrowserWorks/waterfox#91]
I'm sure this issue is a common one along portable users, here's a quick gif of the issue:

![halcbqh](https://cloud.githubusercontent.com/assets/7162375/21976372/3cbdeee8-dbb0-11e6-8cf2-04f37474261c.gif)

As you can see, it creates a new icon and it's very annoying, personally this is a showstopper for me so I can't use Waterfox until it's fixed. What's really strange is that Firefox Portable _can_ use a single icon. This is how it's achieved:

1. Open Firefox Portable
2. Right click on the taskbar icon and select "Pin to Taskbar".
3. Close Firefox Portable.
4. Right click on the taskbar icon and then right click on the "Firefox Portable" just above the "Unpin from Taskbar"
5. Go to Propierties
6. On the **Target** field, select the location of **FirefoxPortable.exe** instead of "firefox.exe" (it's two folders below)
7. OK to save
8. Click on the Firefox Portable icon

Result: No extra icon is generated.

![ng3kvzb](https://cloud.githubusercontent.com/assets/7162375/21976597/651fa736-dbb1-11e6-8d8c-e7d2a3e647f0.gif)

Hopefully this issue can be solved, I have to go back to Firefox for this minor issue :(

**Comment by PandaCodex** [comment]
@notnsane 

Side effect from your other issue https://github.com/MrAlex94/Waterfox/issues/92 Firefox portable like Waterfox portable are not designed for setting as default web browser or program icon pinning. Install the full version to resolve.

**Comment by notNSANE** [comment]
Then how it is working _perfectly_ with Firefox portable?

**Comment by PandaCodex** [comment]
@notnsane

You can't set both Firefox and Waterfox as default browsers, setting default browser and registering default application types i.e html, url creates registry entries. same when pinning an icon to the task bar.

This goes against what the portable application was designed for and defeats its main functionality just ask John at http://portableapps.com great guy btw.

The icon duplication is cased by the follow registry entries.

``` INI
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\WaterfoxProject\Waterfox\TaskBarIDs]
"C:\\Program Files\\Waterfox\\waterfox"="7EC74E9D63B33BF7"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\WaterfoxProject\Waterfox\TaskBarIDs]
"C:\\Program Files\\Waterfox\\waterfox"="7EC74E9D63B33BF7"
```

In your case it will be the path to the WaterfoxPortable\Waterfox folder remove the entries completely.

#### Save registry code below as a *.reg then merge it to remove the registry entries.
``` INI
Windows Registry Editor Version 5.00

[-HKEY_CURRENT_USER\Software\WaterfoxProject\Waterfox\TaskBarIDs]
[-HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\WaterfoxProject\Waterfox\TaskBarIDs]
```
