### ISSUE TITLE
Doesn't Build Against Rust 1.33 On Arch

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#910]
I get a number of errors about functions not supported on this architecture (x86_64 of course) using rust 1.33 under Archlinux.

I admit this could be due to my cflags, but since downgrading to 1.32 is allowing me to build, I somewhat doubt it.

**Comment by grahamperrin** [comment]
Not limited to Linux. 

On the freebsd-gecko list, see the responses to: 

- [Building (deleted) Waterfox 56.2.8: error: missing documentation for macro](https://lists.freebsd.org/pipermail/freebsd-gecko/2019-March/009201.html)

[FreshPorts -- lang/rust](https://www.freshports.org/lang/rust/) ▶ [Announcing Rust 1.33.0 | Rust Blog](https://blog.rust-lang.org/2019/02/28/Rust-1.33.0.html) ▶ detailed release notes at https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1330-2019-02-28

From <https://lists.freebsd.org/pipermail/freebsd-gecko/2019-March/009203.html>: 

> … Either remove `missing_docs` from `#![deny(...)]` lines (or lines themselves)
for each one that triggers error (no need to bother with unused ones) or
add `MOZ_OPTIONS+=--disable-stylo` to `Makefile.local`. …

Re: `--disable-stylo` I encountered problems _beyond_ the one mentioned at https://lists.freebsd.org/pipermail/freebsd-gecko/2019-March/009209.html …

**Comment by grahamperrin** [comment]
### FreeBSD

Made it 🎉 

Waterfox 56.2.8 built with Rust 1.33.0_1 and installed on FreeBSD-CURRENT, with this: 

```text
root@momh167-gjp4-8570p:~ # cat /usr/ports/www/waterfox/Makefile.local 
MOZ_OPTIONS+=--disable-stylo
root@momh167-gjp4-8570p:~ # 
```

– plus **manual removal** of the `LLVM_CONFIG=llvm-config80` line from: 

`/usr/ports/www/waterfox/work/Waterfox-56.2.8/.mozconfig` 

There's a little more to it than that, but that's the essence.

![image](https://user-images.githubusercontent.com/192271/55531958-f6b18d80-56a3-11e9-8e41-e8740b37d2d2.png)

### Linux

I made no attempt to build. 

I assume that presence of the `llvm-config` line will not present an obstacle.

**Comment by hawkeye116477** [comment]
Probably related `https://bugzilla.mozilla.org/show_bug.cgi?id=1521249`

**Comment by ilikenwf** [comment]
As an aside, setting --disable-rust-simd and --disable-stylo in the mozconfig builds it.

**Comment by grahamperrin** [comment]
What happens if `--disable-rust-simd` is **not** set?

**Comment by hawkeye116477** [comment]
You can just comment/remove `enable-rust-simd`, no need to add `--disable-rust-simd` :smile:.

@grahamperrin Without commenting/removing `--enable-rust-simd` there are errors same as on `https://bugzilla.mozilla.org/show_bug.cgi?id=1521249`.

**Comment by hawkeye116477** [comment]
@ilikenwf You can re-enable rust-simd, stylo at build time and elf-hack now.
