### ISSUE TITLE
PortableApps version of Waterfox uses existing installation's profile

### ISSUE THREAD

**Issue by CyberBotX** [BrowserWorks/waterfox#911]
When running the PortableApps version of Waterfox, instead of it using its own separate profile to avoid conflicting with an existing installation, it instead loads with the existing installation's profile. This does not occur with the PortableApps version of Firefox, so it might be helpful to look at how they did it there to fix it with Waterfox.

I noticed this after I installed the PortableApps version of Waterfox and ran it, instead of giving me a brand new clean profile, it instead created a new window for the already running instance of Waterfox, despite that I also included a WaterfoxPortable.ini file next to WaterfoxPortable.exe, with its WaterfoxExecutable set to waterfox-portable.exe and renaming waterfox.exe within the App\waterfox folder to waterfox-portable.exe.

One thing I did not test in the below is running WaterfoxPortable.exe without having an existing copy of Waterfox running.

**To Reproduce**
1. Install a non-PortableApps version of Waterfox and customize it in some way so it won't look like a brand new profile anymore (maybe customize the UI, add some bookmarks, etc.)
2. Leaving that open, install a PortableApps version of Waterfox, but do not run it after install.
3. In the folder that Waterfox Portable was installed to, copy `WaterfoxPortable.ini` from `Other\Source` to the base directory, so it is next to WaterfoxPortable.exe
4. Edit `WaterfoxPortable.ini` so WaterfoxExecutable says waterfox-portable.exe
5. In `App\Waterfox`, rename `waterfox.exe` to `waterfox-portable.exe`
6. Run WaterfoxPortable.exe

What happens is that there will not be a new waterfox-portable.exe process running and instead a new window for the existing Waterfox installation will open.

**Expected behavior**
A new instance of waterfox-portable.exe with a new window showing a brand new profile.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 64-bit

**Comment by laniakea64** [comment]
> One thing I did not test in the below is running WaterfoxPortable.exe without having an existing copy of Waterfox running.

Please test running WaterfoxPortable.exe without having an existing copy of Waterfox running.  If that works as expected, try setting the portable Waterfox to run with the `-no-remote` [command-line switch](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options).

**Comment by CyberBotX** [comment]
I have tested this, I can confirm that Waterfox Portable runs correctly when no existing copy of Waterfox is running, and that if I set the AdditionalArguments in WaterfoxPortable.ini to `-no-remote` while an existing copy is running, it also runs correctly. It only does not run correctly if an existing copy is running and `-no-remote` is not in WaterfoxPortable.ini. I do not have to include `-no-remote` when I use Firefox Portable, which is why I opened this issue up.

**Comment by laniakea64** [comment]
> I do not have to include `-no-remote` when I use Firefox Portable, which is why I opened this issue up.

Maybe it's default there?  If not with the command-line option, maybe with the environment variable `MOZ_NO_REMOTE`?

**Comment by CyberBotX** [comment]
I looked at the `FirefoxPortableU.nsi` file within FirefoxPortable's `Other\Source` folder, and they commented out the `CheckMultipleInstances:` line, so it appears that `-no-remote` is always set no matter what. And it appears that `AllowMultipleInstances` in the default WaterfoxPortable.ini is set to false. I can verify that setting that to true also works without `-no-remote` being there. Firefox Portable's FirefoxPortable.ini defaults to false for `AllowMultipleInstances`.
