### ISSUE TITLE
Portable Waterfox is not really portable

### ISSUE THREAD

**Issue by esrat** [BrowserWorks/waterfox#912]
**Describe the bug**
Portable Waterfox (verified with the official downloads of versions 56.2.6 and 56.2.8 from the website) obviously saves some absolute paths to some installed add-ons which is untenable for a "portable" application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and "install" (unpack) the portable Waterfox to some place A.
2. For simplicity copy an already used profile-subdirectory into its Data-directory. This should use add-ons like "Classic Theme Restorer", "Flashblock", "FlashGot", "SearchWP", "Status-4-Evar", "Tab Mix Plus" or others.
3. Start Waterfox portable: All works fine.
4. Copy WaterfoxPortable-directory to some other place B.
5. Start copy B (no matter if you closed copy A beforehand or if you start copy B with "AllowMultipleInstances=true"): All works fine.
6. Close copy B (and A), then delete or rename the original copy A.
7. Start (the untouched) copy B again: **The browser looks "broken"!**
   All of the above mentioned add-ons (and more) are still listed as installed, but they cannot be used since their .xpi-files within the extensions-subdirectory of the profile cannot be found anymore. When you hit the settings-button for one of the broken add-ons, the GUI freezes and you need the TaskManager or similar to close the browser.
   (Rightclicking the button in the taskbar still works. You can even open a new window this way which can be used without restarting the whole browser. But the first window remains frozen.)
8. Just to verify: Restore the copy A and restart copy B: All looks well again!

**Expected behavior**
A portable application needs to use relative paths only and must not depend on absolute paths of the first start! The WaterfoxPortable-directory needs to be freely movable.

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional 64 Bit
 - Version: 56.2.6, 56.2.8, 56.2.10

**Comment by Ibuprophen** [comment]
There's a previously reported issue https://github.com/MrAlex94/Waterfox/issues/911 that may also apply to this one and may also answer this issue as well. 

Just an FYI... :-) 


~Ibuprophen

**Comment by esrat** [comment]
No, I have looked at the existing issues before. Mine has nothing to do with #911.
As you can see in my bug report, I am aware of the AllowMultipleInstances-setting. I am using it since years with the portable Firefox ESR which is *really* portable.
I also never used something else than the portable version of Waterfox.

**Comment by esrat** [comment]
I just reproduced the problem on a virtual machine (Windows 7 Professional 64 Bit with no Waterfox on it before) with the current "portable" Waterfox version of 56.2.10.
1. I unpacked the portable installer.
2. I started Waterfox, verified issue #845 and closed it again.
3. I copied my profile folder of Waterfox 56.2.6 into the Data-directory (deleted the old one beforehand).
4. I started Waterfox (which in turn verified my add-ons successfully) and verified all opened tabs and installed add-ons. All looked fine.
5. I closed Waterfox and moved the installation directory to a subdirectory.
6. I started Waterfox and all tabs were gone. Strangely, most of the add-ons did still work at this point.
7. I opened a new tab and closed Waterfox.
8. I moved the installation directory back to the first place and started Waterfox again.
9. -> Only the newly opened tab was restored and now all the add-ons are broken like I already described in step 7 of the original bug description.

**Comment by esrat** [comment]
Just another update:
10. I closed Waterfox and moved the installation directory again to the same subdirectory.
11. I started Waterfox an all the add-ons were back working again!!! Only the tabs did never reappear.

That means, for this test, Waterfox did save the absolute path to the add-ons only for the second time (and place) Waterfox was started with the already existing profile!

**Comment by tcreek** [comment]
I just ran a quick test today. It seems each one running alone will use its own correct profile. When you start the other up, installed or portable, the second one running will use the first running one's profile instead of its own.

**Comment by grahamperrin** [comment]
[Portable (Windows) - Extensions Break On Path Change (addonStartup.json.lz4 Problem) · Issue #329 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/329)

**Comment by jrappen** [comment]
@MrAlex94 what is the resolution here?

**Comment by tcreek** [comment]
There is none. Can't/won't fix
