### ISSUE TITLE
Website crashes content process

### ISSUE THREAD

**Issue by mzso** [BrowserWorks/waterfox#913]
**Describe the bug**
This website crashes the Waterfox content process even with a brand new profile when it loads:
https://www.basschouten.com/blog1.php/using-windowrecording-to-analyze-visual

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - Version: 56.2.3

**Comment by laniakea64** [comment]
Works for me with Waterfox 56.2.8 on Linux.  Do you see this issue with Waterfox 56.2.8?

**Comment by mzso** [comment]
[**@laniakea64**](https://github.com/laniakea64) commented on [2019. ápr. 6. 17:44 CEST](https://github.com/MrAlex94/Waterfox/issues/913#issuecomment-480514151 "2019-04-06T15:44:28Z - Replied by Github Reply Comments"):
> Works for me with Waterfox 56.2.8 on Linux. Do you see this issue with Waterfox 56.2.8?

Yes. Just tried the portable.

**Comment by laniakea64** [comment]
There is a video on that page, could this be something similar to https://github.com/MrAlex94/Waterfox/issues/870#issuecomment-468641442 ?

**Comment by grahamperrin** [comment]
> Works for me with Waterfox 56.2.8 on Linux. 

Also works for me with 56.2.8 on FreeBSD-CURRENT.

**Comment by strotee** [comment]
Works for me. v56.2.8 on Win 10 LTSC 17763.437

**Comment by mzso** [comment]
Did you guys all make sure to enable multi-process mode? (Also no other win8 testers)

**Comment by grahamperrin** [comment]
Rested, FreeBSD-CURRENT, 56.2.8, new profile, https://www.basschouten.com/blog1.php/using-windowrecording-to-analyze-visual including playback of the video: no crash. 

I might find time tomorrow to test on Windows 7 Enterprise.

**Comment by grahamperrin** [comment]
Waterfox Classic 2019.10 on Windows 10: no crash.
