### ISSUE TITLE
Dynamic emails gmail

### ISSUE THREAD

**Issue by theQ23** [BrowserWorks/waterfox#918]
OS: windows 7
version: 56.2.8

stuff tried: Safe mode, new profile, 

Works fine in : chrome, firefox 66, firefox ESR 60

issue: when opening a dynamic email in gmail the loading box appears and nothing happens. 

i can get it to work if i disable option security.csp.enable, but that opens up a new can of worms.

here is info from the console in firefox of it not working 

Attempt to set a forbidden header was denied: Connection  m=b:579:75
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead. (unknown)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-X7NsBSCHD97ILW5F4jFg2g' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'”). Source: onsubmit attribute on INPUT element.  0
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.  (unknown)
Content Security Policy: Couldn’t process unknown directive ‘worker-src’  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-5tKqD/Fkv84kPN82jU6prg' https://contacts.google.com 'unsafe-eval' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com”). Source: ;!function(){var t,e,n,o=0,u=function(t,....  2:1
AbortError m=m,m_i:3764:163
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Content Security Policy: The page’s settings blocked the loading of a resource at https://mail.google.com/dynamic-email/relay/v0/index.html#origin=https%3A%2F%2Fmail.google.com&prerenderSize=0&visibilityState=visible&paddingTop=0&history=1&p2r=0&horizontalScrolling=0&storage=1&development=0&log=0&cap=errorReporter%2Ckeyboard%2CxhrInterceptor%2CviewerRenderTemplate&csi=1&messagingToken= (“frame-src 'none'”).  (unknown)
uncaught exception: CustomError: Error in protected function: Nla  (unknown)
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75

  And here it is working with the csp option disabled

Attempt to set a forbidden header was denied: Connection  m=b:579:75
AbortError m=m,m_i:3764:163
Empty string passed to getElementById().  m=b:658:240
Attempt to set a forbidden header was denied: Connection  m=b:579:75
Attempt to set a forbidden header was denied: Connection  m=b:579:75
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.  0
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.  index.html
Powered by AMP ⚡ HTML – Version 1904101725150 data:text/html;charset=utf-%2Fcdn.ampproject.org%2Frtv%2F011904101725150%2Fv0%2Famp-mustache-0[…]  ampdoc-impl.js:534:2
Use of attributes’ nodeValue attribute is deprecated. Use value instead.

**Comment by Ibuprophen** [comment]
This looks like the same/similar issue as described on the following links that also reflects some possible resolutions for this as well. 

https://www.reddit.com/r/firefox/comments/6yftwt/gmail_no_longer_loading_on_firefox_works_fine_on/

https://forum.palemoon.org/viewtopic.php?t=21784 


~Ibuprophen

**Comment by theQ23** [comment]
I guess they are similar because they talk about GMail in general. I can get it to work disabling CSP. thanks for searching though.
