### ISSUE TITLE
Most emoji reverted to black&white with 56.2.9

### ISSUE THREAD

**Issue by kazerniel** [BrowserWorks/waterfox#919]
**Describe the bug**
My Waterfox used to have coloured emojis. Since I updated to v56.2.9 yesterday most of them reverted to the black&white versions they used to have years ago on Firefox.

**To Reproduce**
1. Go to any website that features emoji without a designated emoji font.
2. See that most of them are black & white.

**Expected behavior**
To keep showing coloured emoji as it was since I started using Waterfox with v56.2.2.

**Screenshots**

![Screenshot(22)](https://user-images.githubusercontent.com/5689996/56459807-fd711d80-6390-11e9-964a-e112da8536ee.png)

(Screenshot of https://en.wikipedia.org/wiki/List_of_emoji )

**Desktop (please complete the following information):**
 - OS: Win7 SP1 x64

**Additional context**
The issue seems to appear in some instances even on emoji that *does* have an emoji font set. Eg. see the navigation row here and some of the emoji in the list:

![Screenshot(21)](https://user-images.githubusercontent.com/5689996/56459780-9c494a00-6390-11e9-911e-548c1c571c1d.jpg)

(Screenshot of ~~https://emojipedia.org/~~ http://getemoji.com/ )

**Comment by hawkeye116477** [comment]
Same emojis are on Firefox, so it's not a bug, it's feature :smile:. Waterfox switched to new Twemoji Fonts.

**Comment by grahamperrin** [comment]
> (Screenshot of emojipedia.org )

Which page?

**Comment by kazerniel** [comment]
Sorry, my bad, it's http://getemoji.com/ Gonna edit the OP too.

**Comment by hawkeye116477** [comment]
I can confirm that too, I see the difference.

**Comment by grahamperrin** [comment]
From [Waterfox 56.2.9 Release | Waterfox Web Browser](https://www.waterfox.net/blog/waterfox-56.2.9-release-download/)

> - Switched to twemoji for platforms that do not natively support emoji.

**Comment by hawkeye116477** [comment]
Even some emojis are wrong, people and next to it hair, people rather should has hair on head. Hovewer site `http://getemoji.com/` uses different font to show emoji, when I manually switch it on Firefox to Twemoji, then I get almost same result as on Waterfox. So problem is that Waterfox doesn't apply Segoe UI Emoji Font.

**Waterfox**
![Screenshot_20190425_203519](https://user-images.githubusercontent.com/19818572/56759640-b1abe300-6799-11e9-9269-4b687e3bd325.png)
![Screenshot_20190425_203721](https://user-images.githubusercontent.com/19818572/56759739-f20b6100-6799-11e9-90aa-071097e95da2.png)

**Firefox**
![Screenshot_20190425_203550](https://user-images.githubusercontent.com/19818572/56759653-bb354b00-6799-11e9-95f9-086926a4d386.png)
![Screenshot_20190425_203641](https://user-images.githubusercontent.com/19818572/56759694-da33dd00-6799-11e9-8ed4-3c04119c332d.png)

**Comment by grahamperrin** [comment]
On FreeBSD-CURRENT, I find Waterfox better than Firefox. 

Firefox: 

![Firefox](https://user-images.githubusercontent.com/192271/56788465-78a25b80-67f7-11e9-92d8-65f6b6151e6f.png)

**Comment by grahamperrin** [comment]
… Waterfox: 

![Waterfox](https://user-images.githubusercontent.com/192271/56788490-87890e00-67f7-11e9-94e3-a707599ca2df.png)

**Comment by grahamperrin** [comment]
Waterfox (in response to <https://www.reddit.com/comments/bhfvum/-/elshrjf/>): 

![image](https://user-images.githubusercontent.com/192271/56791583-501e5f80-67ff-11e9-9e0b-fc7face516d7.png)

**Comment by satovey** [comment]
I find that the emoji plugin show a colored emoji but when the plug in copies and pastes them into a YouTube comment box, the emoji is black. In Firefox, the emoji is it's depicted color.

**Comment by hawkeye116477** [comment]
Twemoji 0.4.0 fixes problem with people's hair.
