### ISSUE TITLE
Using "Make Waterfox Portable the default browser" doesn't work in Windows (10)

### ISSUE THREAD

**Issue by notNSANE** [BrowserWorks/waterfox#92]
Instead of using the Portable installation it opens a whole new Waterfox Profile in Windows %APPDATA% folder.

I have to use this app to make external links use Waterfox: http://www.winhelponline.com/blog/register-firefox-portable-with-default-programs-in-vista/

**Comment by PandaCodex** [comment]
@notnsane 

Firefox portable like Waterfox portable is not designed to be made default browser. In fact there is a preference override shipped with Firefox portable to prevent this. 

Why on earth would you want to make a portable version default browser just install Waterfox normally then set as default browser as the installed version will be faster and consume less memory. Waterfox portable uses ram cache which is slower then disk cache.

**Comment by notNSANE** [comment]
Portable applications have many advantages to normal, installable apps.

* They don't write ANYTHING in the Windows Registry - UWP apps, the new Windows paradigm are going this way too! AFAIK, also Linux Mint is starting to go this way too. It's simply better.
* You can carry around your installation anywhere.
* When you format for X reason, everything will remain the same and don't have to spend hours and hours getting everything how it was before (for every single program you have!)
* I have a very limited C:\ partition on a SSD, so I try to move small apps outside of it. While a browser is not the case, it's very useful for all the rest of my occasional usage apps.

Even if the drawback is that it uses more RAM, I have 12 GB of RAM and will have 16 GB soon w/ dual channel, so RAM isn't an issue, nor it's the milliseconds of speed I'd lose.

And anyways, **it's about choice**.

**Comment by PandaCodex** [comment]
@notnsane

Setting the portable as default web browser. Setting any default applications types i.e html, url. Pinning the WaterfoxPortable.exe or Waterfox.exe icon to the windows task bar, start menu or quick launch **will create registry entries**. This defeats the portable purpose.

I know how portable apps work have been contributing for years to the project.

**Comment by notNSANE** [comment]
I know, but that's Windows, not on Firefox.

**Comment by PandaCodex** [comment]
@notnsane

Actually in the nsis code the Firefox.exe or this case Waterfox.exe there is code that updates the registry for pinned icons. Same with default browser and registering default extensions. Small [example](https://github.com/MrAlex94/Waterfox/blob/master/browser/installer/windows/nsis/shared.nsh#L37)   and [another](https://github.com/MrAlex94/Waterfox/blob/master/browser/installer/windows/nsis/shared.nsh#L175)

**Comment by MrAlex94** [comment]
Sorry, marking this as wontfix. I've added disabling the prompt on Waterfox portable to the release checklist.
