### ISSUE TITLE
@media (hover: hover) not working

### ISSUE THREAD

**Issue by Jaap12345** [BrowserWorks/waterfox#922]
**Describe the bug**
@media (hover: hover)  has no effect in Waterfox

**To Reproduce**
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover
Try hovering the link "Try hovering over me!" 

**Expected behavior**
When hovering over the link in Chrome or Firefox the text background becomes yellow.
In Waterfox nothing happens.

**Desktop:
 - OS: Windows 7
 - Version 56.2.9

**Comment by laniakea64** [comment]
What version of Firefox?

Waterfox 56.2.9 is based on Firefox 56.  The page you linked says `@media (hover: hover)` requires at least Firefox 64.  So I wouldn't expect this to work in Waterfox yet.

I would suggest waiting for the upcoming Waterfox 68 alpha before revisiting this.
