### ISSUE TITLE
wallstreetcn.com article  disappear.

### ISSUE THREAD

**Issue by alextooter** [BrowserWorks/waterfox#923]
**Describe the bug**
Open a article link in wallstreetcn.com,the article show two seconds,then disappear.

1. Go to https://wallstreetcn.com/articles/3516802
or  https://wallstreetcn.com/articles/3516707
2. see the article
3. water a second
4. the article disappear,only page head and page foot left.

**Expected behavior**
I want article still there like normal web pages.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Waterfox 56.2.9

**Additional context**
I have tried following things:
1,disable all adds-on, start Waterfox in safe mode,this bug happen.
2,refresh Waterfox,bug happen.
3,Totally uninstall Waterfox,delete all my profiles, reinstall Waterfox 56.2.9, bug still happen.

**Comment by grahamperrin** [comment]
<strike>Not </strike>reproducible with 56.2.9 on Manjaro Linux: 

![VirtualBox_Manjaro_25_04_2019_19_48_41](https://user-images.githubusercontent.com/192271/56760542-4f4fe400-6793-11e9-8ff0-715e2166027f.png)

**Comment by grahamperrin** [comment]
Worked around in 56.2.8 on FreeBSD-CURRENT with a user agent string override: 

`Mozilla/5.0 (rv:56.0) Gecko/20100101 Firefox/56.0`

You can set an override for the site with the **Custom UserAgent String** extension, see https://www.reddit.com/comments/9drjqx/-/e66gcir/

**Comment by alextooter** [comment]
> Worked around in 56.2.8 on FreeBSD-CURRENT with a user agent string override:
> 
> `Mozilla/5.0 (rv:56.0) Gecko/20100101 Firefox/56.0`
> 
> You can set an override for the site with the **Custom UserAgent String** extension, see https://www.reddit.com/comments/9drjqx/-/e66gcir/

Thanks Graham,it works for me.
