### ISSUE TITLE
Soundcloud.com - country flags not displayed correctly with new update (Twemoji issue?)

### ISSUE THREAD

**Issue by Stephen-Mc** [BrowserWorks/waterfox#926]
# Summary
With the new update, many of the flags on soundcloud have been replaced by either country codes, or even worse, weird combinations of emojis. The page was displayed correctly before upgrading to the latest versions, and displays correctly in other browsers.

The code, for example for the Union Jack is:
`<div class="statsCountryFlag large">🇬🇧</div>`

But instead of showing the Union Jack flag, this now shows "GB" as a country code.  Thailand is even worse, with a combination of two emojis superimposed on each other. I have attached screenshots so you can see what I mean.

## To Reproduce

1. Go to https://soundcloud.com and log in to an account with some plays
2. Navigate to the Stats page

I appreciate that this might not be that easy to reproduce if you don't have a Soundcloud page - but presumably this is more to do with the wrong images being displayed in Waterfox than the page itself. The behaviour would presumably be the same on any site that uses flags in this way.

## Expected behavior

The flags should be displayed correctly (i.e. as country flags, not country codes or random combination of emoji letter images).

## Screenshots

**Waterfox:**
![countries in Waterfox](https://user-images.githubusercontent.com/11058269/56849578-a5896800-68f6-11e9-986a-a8d6d41c2d58.png)

**Chrome:**
![countries in chrome](https://user-images.githubusercontent.com/11058269/56849586-aae6b280-68f6-11e9-910f-77473e9602bd.png)

## System Information
 - OS: Windows 7 Home Premium Service Pack 1
 - Waterfox version: 56.2.9 (64-bit)

**Comment by reallyuniquename** [comment]
Same here. Any updates?

**Comment by hawkeye116477** [comment]
Is it still broken or fixed?

**Comment by Stephen-Mc** [comment]
It was fixed in the interim for me.
