### ISSUE TITLE
No "network.trr" hierarchy in Waterfox 

### ISSUE THREAD

**Issue by Telmesomething** [BrowserWorks/waterfox#928]
Setting DNS-over-HTTPS in Waterfox doesn't appear to be possible since there's no "network.trr" hierarchy present. Mozilla has a Wiki on the subject [here](https://wiki.mozilla.org/Trusted_Recursive_Resolver)

My question derives from an article on [ghacks.net](https://www.ghacks.net/2019/04/29/check-if-your-browser-uses-secure-dns-dnssec-tls-1-3-and-encrypted-sni/) which contains a link to Cloudflare's browser experience security test. Even after logging in to a VPN with an encrypted DNS server the test still results in TLS3 and SNI tests failing. 

I checked in prefs and **network.security.esni.enabled** doesn't appear to be included either. 

Will these options be included in a future release?

**Comment by Ibuprophen** [comment]
This topic looks like it's still an open issue that's inclusive within the https://github.com/MrAlex94/Waterfox/issues/768 and https://github.com/MrAlex94/Waterfox/issues/783 as well. 

This may be duplicate to one or both of them but, only @grahamperrin and @MrAlex94 can provide a better clarification for this as well. 


~Ibuprophen

**Comment by Telmesomething** [comment]
> This topic looks like it's still an open issue that's inclusive within the #768 and #783 as well.

> This may be duplicate to one or both of them but, only @grahamperrin and @MrAlex94 can provide a better clarification for this as well.

Thanks for the info Ibuprophen1.

**Comment by laniakea64** [comment]
It will be in Waterfox 68 - https://www.reddit.com/r/waterfox/comments/bioat5/does_waterfox_support_dns_over_https/em3a289/

**Comment by grahamperrin** [comment]
Is this issue resolved with Waterfox Current `2020.03`?
