### ISSUE TITLE
[56.2.9] Checking for updates when security.tls.version.min set to 4 results in a crash

### ISSUE THREAD

**Issue by sheddup** [BrowserWorks/waterfox#929]
**Describe the bug**
Checking for updates when security.tls.version.min is set to 4 results in a crash on Waterfox 56.2.9, Windows 10 x64

**To Reproduce**
1. Go to about:config
2. Set `security.tls.version.min` and `security.tls.version.max` to 4
3. In the 'About Waterfox' dialog click on check for updates
4. Waterfox completely locks up then crashes shortly after

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 17134.706

**Comment by Atavic** [comment]
Shouldn't *security.tls.version.min* have a value of *3* ?

**Comment by grahamperrin** [comment]
`security.tls.version.min` defaults to 1 in Waterfox 56.2.8 and Firefox 66.0.3 (64-bit) on FreeBSD-CURRENT.
