### ISSUE TITLE
Invisible characters in release page on website

### ISSUE THREAD

**Issue by jpiel** [BrowserWorks/waterfox#930]
Around the « Buy me a coffee » links, there are characters U+FE0F that makes autopkg’s parser to hang. There is one right before the heart and one right after the coffee pot, on both links.

I’m maintaining the [autopkg recipe for waterfox](https://github.com/autopkg/jpiel-recipes/tree/master/Waterfox) and for some days now I have issues finding the download link. This is due to some invisible chars in the page where i find the download URL.

U+FE0F character (“Unicode Character ‘VARIATION SELECTOR-16’ (U+FE0F)”) is also EF B8 8F in hex format.

Removing this invisible character from the [release page](https://www.waterfox.net/releases/) would make the recipe work again.

**Comment by grahamperrin** [comment]
#582
