### ISSUE TITLE
Waterfox fails to decode mp4, with different behaviors between Windows 7 and 10.

### ISSUE THREAD

**Issue by Squall-Leonhart** [BrowserWorks/waterfox#931]
The Following video which works in Firefox, Chrome and Edge fails to work on Waterfox with the following scenarios

Windows 7: 
The file buffers, as would  be expected but immediately skips to the end of the seek bar.
The browsers GPU process consumes an entire core and ram usage grows further and further

Windows 10:
Video fails to start with error "Video can't be played because the file is  corrupt"

**To Reproduce**
1. Download video from 
https://mega.nz/#!wQ0xUSCT!mxaHpwJA5go9PUP0pxBAw9A5A5dfv3eEPuLqWCy1V-Y (palmtree.mp4)
2. Load the mp4 into the browser with the file:/// protol

**Expected behavior**
The video plays as it does in the other browsers

**Desktop (please complete the following information):**
- Windows 10 and Windows 7 desktops

**Comment by MrAlex94** [comment]
In about:plugins, is the OpenH264 plugin listed?

**Comment by Squall-Leonhart** [comment]
Yep!

**Comment by Squall-Leonhart** [comment]
Infact, on Firefox, the video played before the OpenH264 codec was even finished downloading. o.O

**Comment by grahamperrin** [comment]
According to VLC: 

> Codec: H264 - MPEG-4 AVC (part 10) (avc1)

The downloaded file plays in Waterfox 56.2.8 on FreeBSD-CURRENT. 

If I try to play the file in MEGA, after a few seconds there's a red alert: 

> This file uses a video codec that is not supported by your browser.

**Comment by Squall-Leonhart** [comment]
The buffer but no play situation also carries over from 7 to 8.x

The leak  only manifests if its used on a site that runs it in repeat.
