### ISSUE TITLE
[FIX]: Google Hangouts phone calls don't work because of current useragent

### ISSUE THREAD

**Issue by LeeBinder** [BrowserWorks/waterfox#933]
Another useragent thingy.. good news is, I can provide THE FIX at least for macOS (not working in Windows, Linux not tested) right along :)

**Issue**:
the current Waterfox 56.2.9 rv:60.0 useragent string (in my macOS High Sierra: _Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0_) causes phone calls via [hangouts.google.com](https://hangouts.google.com/) to get stuck on "Calling..." without the call making it out. Reproduced also on a new/ virgin "from scratch" account w/o any add-ons or alike.

**Fix (verified working in macOS)**:
Copy
`about:config?filter=useragent`

into the clipboard, paste it into Waterfox' address bar, press Enter

Right click into the white part of the window below the lines with text, New -> String:
`general.useragent.override.hangouts.google.com`

Copy/ paste the value matching your OS:

**For Mac**:
~~`Mozilla/5.0 (Macintosh; rv:53.0) Gecko/20100101 Firefox/60.0`~~
`Mozilla/5.0 (Macintosh; rv:53.0) Gecko/20100101 Firefox/78.0`

**NOT TESTED - For Linux**:
`Mozilla/5.0 (Linux; rv:53.0) Gecko/20100101 Firefox/78.0`

(**Windows: _not possible_** because Waterfox is a 64bit application but the Windows version of the Google Talk plugin is pure 32bit, so it does not even appear in Waterfox/ Add-ons/ Plugins)

**DONE!**

**NOTES**:
1. To make calls via Hangouts in Waterfox, the legacy Google Talk/ Voice/ Video Support Plugin must be installed. Google does not offer it anymore on [the old plugin page](https://www.google.com/tools/dlpage/hangoutplugin), but as of this writing it was still possible to download it directly from their server. Here's the [link to the latest macOS plugin v.5.41.3.0](https://dl.google.com/googletalk/googletalkplugin/GoogleVoiceAndVideoSetup.dmg). If Google removed that, too, then a search for [GoogleVoiceAndVideoSetup.dmg](https://www.google.com/search?sclient=psy-ab&site=&source=hp&btnG=Search&q=GoogleVoiceAndVideoSetup.dmg&oq=&gs_l=&pbx=1) might help.

2. A balance is needed in one's Google Hangouts account to make calls to phone lines. Not sure if this issue also applies to calls to other "hangouters".

My recommendation: leave this issue open until you have integrated the useragent override for hangouts.google.com into the next release so people can find this fix AEAP.

**More details**:
A complete string like _Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:53.0) Gecko/20100101 Firefox/60.0_ has not been necessary in my extensive tests.

The "do-jobby" here is the **rv parameter which needs to have a value <= 53.0** for some odd reason only some Google hangouts coder can know...

**Also working in my tests as of date of this posting 2019-05-03 (might not work anymore in the future):**
OK ranges : any useragent string with **rv: <= 53.0**:
Mozilla/5.0 (Macintosh; rv:53.0) Gecko/20100101 Firefox/68.0
....
Mozilla/5.0 (Macintosh; rv:53.0) Gecko/20100101 Firefox/66.0

Mozilla/5.0 (Macintosh; rv:53.0) Gecko/20100101 Firefox/60.0
...
Mozilla/5.0 (Macintosh; rv:10.0) Gecko/20100101 Firefox/60.0

Mozilla/5.0 (Macintosh; rv:10.0) Gecko/20100101 Firefox/62.0
etc.

**Also OK (LOL):**
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0

**NOT working: any useragent string with rv: >= 54.0:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:54.0) Gecko/20100101 Firefox/60.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:55.0) Gecko/20100101 Firefox/61.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko/20100101 Firefox/62.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0
...
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/68.0
____
**[TROUBLESHOOTING]**: In case above fix is _not_ working for you, test if Google's plugin communicates correctly with the Hangouts servers in general by testing in other Browsers which also use the plugin, which are:
- **macOS**: Safari, [Firefox 52.9.0 ESR](https://archive.mozilla.org/pub/firefox/releases/52.9.0esr/mac/)
- **Windows**: Internet Explorer, [Firefox 52.0.9 ESR 32bit](https://archive.mozilla.org/pub/firefox/releases/52.9.0esr/win32/)!!
- **Linux**: [Firefox 52.0.9 ESR 32bit](https://archive.mozilla.org/pub/firefox/releases/52.9.0esr/linux-i686/)!!

Background: just in parts of May 2019, [Hangouts wasn't working at all in *any* plugin based Browser](https://support.google.com/hangouts/thread/6319539?hl=en).

In any case you can always use [voice.google.com](https://voice.google.com/u/0/calls) as an alternative because it does _not_ use the plugin to begin with but connects to Google directly.

**Comment by IanKemp** [comment]
Considering all Firefox versions >= 60 will encounter this bug, surely this should've/would've come to the attention of Mozilla and Google by now?

**Comment by LeeBinder** [comment]
@IanKemp : why are you "considering all Firefox versions >= 60 WILL encounter this bug" .. if they simply don't? This is a Waterfox not a Firefox issue. Goggle Hangouts phone calls work fine in current FIrefox builds - 1st thing I tested.

As you most likely know Waterfox' current useragent **Mozilla/5.0 ({OS}; {OS version}; rv:60.0) Gecko/20100101 Firefox/60.0** is fake! It is neither Firefox nor v.60.

All that can be said empirically regarding the behavior of the Google Hangouts webpage is that it must be either counter-checking or applying some of the values passed on via useragent against something in Waterfox, which causes a mismatch and consequently G.H. to fail.

As I wrote: why rv: <= 53.0 fixes this issue IN WATERFOX could only be known with access to all the code from Google, which we don't have.

**Comment by LeeBinder** [comment]
Sadly the useragent string fix stopped *completely* working even in macOS now - same idle non-connection as it was already occurring in WF Windows. Details:

After updating to WF 56.2.10 (macOS) I checked if they were still working with the UA fix applied and was surprised disappointingly. Unfortunately same thing after downgrading back to WF 56.2.9, and even same thing with Firefox ESR 52.9.0 However still working fine with current Firefox and latest ESR 60.6.3.

I tried all of the previously working UA strings and some more - no go. This occurs in both of my macOS installs, High Sierra 10.13.6 and Mojave 10.14.5. Obviously Google changed something on THEIR side - implemented some tighter browser verification.

Via my Firewall app is was seeing that Firefox suddenly was getting an INCOMING request from Google via UDP. As soon as I allowed that both ways, the mike would connect (icon then visible in the menu bar) and the call starts. This is NOT occurring with FF/ WF 5x.x.x: no UDP negotiation between Google and legacy browser - the mike icon does NOT appear in the menu bar even after allowing mike access, and the call window on the right stays on "Calling" forever, unlike before. Sad :(

**Comment by grahamperrin** [comment]
> To make calls via Hangouts in Waterfox, the Google Hangout Plugin must be installed.

Is this certain? 

When I last made a real call, Waterfox worked with neither the plug-in, nor a change to the UA string. 

From <https://github.com/MrAlex94/Waterfox/issues/231#issuecomment-352817390>: 

>> I reported an issue to Google.
>> 
>> Hangouts now works for me with Waterfox 56.0.1 without a plug-in.

Testing today with 56.2.10 on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/58622394-68344380-82c3-11e9-84bb-8a321e835b18.png)

![image](https://user-images.githubusercontent.com/192271/58622470-9580f180-82c3-11e9-8c23-447a83b1fdc9.png)

**Comment by LeeBinder** [comment]
when you go to

about:addons?filter=plugins

there sure is no mention of a 'Google Talk Plugin'?

**Comment by grahamperrin** [comment]
No such plugin; it's not available for FreeBSD.

**Comment by LeeBinder** [comment]
After quitting WF 56.2.10, I uninstalled the GT Plugin [as per instructions](https://support.apu.edu/hc/en-us/articles/221896868-Hangouts-Known-issues), restarted WF, verified the plugin is gone, removed the custom UA string, cleared cache, went to [hangouts.google.com](https://hangouts.google.com/), tried to make a call to my land line, and as described by many others on the web with legacy browsers: the call does NOT go out. Even w/o a plugin I get to the screens you posted, but then nothing happens.

Please also call yourself to see if your call actually _does_ arrive or gets stuck in nirvana, too.

**Comment by LeeBinder** [comment]
@grahamperrin You ever tried calling all the way through? It doesn't work in FreeBSD either, does it?

**Comment by grahamperrin** [comment]
> call yourself 

Does this require a Google Voice number?

**Comment by LeeBinder** [comment]
> > call yourself
> 
> Does this require a Google Voice number?

I have one but I do not know if it's actually required or optional. But as I wrote under Notes, "a balance is needed in one's Google Hangouts account to make calls to phone lines".

**Comment by grahamperrin** [comment]
Yeah, 

> "a balance is needed in one's Google Hangouts account to make calls to phone lines".

– a few hours ago I could find no way to purchase credit. Now I see a way but it's not worth £10 +VAT for a test. 

Anyone: PM me on Reddit with reference to this issue, I can give an address that might be usable for testing.

**Comment by LeeBinder** [comment]
thanks, I'm good.
