### ISSUE TITLE
Can't add Bookmarks to Bookmarks Toolbar (Linux)

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#934]
Hi!

I can't add Bookmarks to Bookmarks Toolbar (waterfox-56.2.9.en-US.linux-x86_64)
Waterfox is blocking to add Bookmarks in the 'Bookmarks Toolbar.

See picture:
[url=https://postimg.cc/tZPW5s1N][img]https://i.postimg.cc/tZPW5s1N/can-t-add-bookmarks.jpg[/img][/url]

In about:config, there is no entry:
("browser.pageActions.persistedActions", "{"version":1,"ids":["bookmark","bookmarkSeparator","copyURL","emailLink"],"idsInUrlbar":["bookmark"]}"

When I add this to user.js, Waterfox crashed.

Or is it another entry to edit?
What must I edit in about:config to fix that?

Please help, thanks!

**Comment by grahamperrin** [comment]
https://firefox-storage-test.glitch.me/

Do you get a _good_ result for all four subsystems?

**Comment by ghost** [comment]
I went to another fork of firefox and now it's working.
