### ISSUE TITLE
Enter key does nothing (issue with autocomplete)

### ISSUE THREAD

**Issue by CasAdair** [BrowserWorks/waterfox#938]

**Comment by CasAdair** [comment]
woops, accidentally opened an issue without typing the description. 
WaterFox version 56.2.8 from COPR repo running on Fedora 30
I'll happily provide any needed info beyond this.

**Comment by grahamperrin** [comment]
Reproducible with 56.2.9?

**Comment by CasAdair** [comment]
I'm not entirely sure @grahamperrin, 56.2.9 wasn't in the COPR repo. However I did find that after switching to XFCE the problem solved itself.

**Comment by CasAdair** [comment]
Sorry for the late reply, I had all but given up hope for a response here.
