### ISSUE TITLE
alt tabbing from Eve to an active Twitchtv tab makes waterfox freeze for a good 30 seconds

### ISSUE THREAD

**Issue by 0Pinger** [BrowserWorks/waterfox#94]
Had this issue for a few weeks now, I have Waterfox open with an active twitchtv.com stream and usually Eve running in windowed node.  I either alt tab direct too Waterfox or press the widows key and click the Waterfox icon from the taskbar, which usually has twitchtv as the active tab.  Doing either will eventually cause the twitchtv stream and Waterfox to freeze for a good 30 seconds.

Before 50.1.0 it was never an issue

**Comment by 0Pinger** [comment]
bit more testing and getting this with just twitch.tv stream tab active, no games etc running in background.  Also tried on current firefox 32bit client with same issue, then tried Opera 42 with no issue at all.

**Comment by MrAlex94** [comment]
@0Pinger, do you still have this issue with Twitch?

**Comment by 0Pinger** [comment]
Partly but found Twitchtv and Waterfox just don't mix, I would get that and that streams would stutter randomly.  I use another browser[Opera] to watch Twitchtv now and use Waterfox for everything else

________________________________
