### ISSUE TITLE
addons for "retire" tabs don't work

### ISSUE THREAD

**Issue by jackpallet** [BrowserWorks/waterfox#941]
**Describe the bug**
Simply all addons that I've tried to suspende tabs (like dormancy, auto tab discards and others) don't work, the tabs are not suspended. Why?

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Waterfox version: 56.2.9 (64 bit)

**Comment by laniakea64** [comment]
Waterfox 56.2.9 is based on Firefox 56.  The required API wasn't available in Firefox until version 58 - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard
AFAIK it hasn't been ported to Waterfox 56.x.

I would suggest waiting for the upcoming Waterfox 68 alpha before revisiting this.

**Comment by grahamperrin** [comment]
There's also **Auto Unload Tab** (legacy, compatible with 56.2.9) Links etc. at https://www.reddit.com/r/waterfox/comments/atuw4c/-/eh3o8we/

**Comment by LeeBinder** [comment]
https://piro.sakura.ne.jp/xul/_suspendtab.html.en has been working perfectly for me for ages with Waterfox and before Firefox legacy. Also available via https://github.com/piroor/suspendtab/releases

**Comment by grahamperrin** [comment]
@LeeBinder thanks, legacy Suspend Tab 1.0.2016061501 is also in the Classic Add-ons Archive at: 

- caa:addon/suspend-tab

**Comment by LeeBinder** [comment]
@grahamperrin yes I was aware. I did not post because it's not possible to have that as a clickable link. Still neat it's in there :)
