### ISSUE TITLE
Bring Waterfox to the Microsoft Store as Packaged Desktop App

### ISSUE THREAD

**Issue by jebeld17** [BrowserWorks/waterfox#942]
With Microsoft now playing nice with other web browser platforms not of their own making, this is a great chance to compile Waterfox for inclusion in the Microsoft Store, bringing Windows 10 users in both Enterprise and Consumer environments a real, safe alternative to Microsoft's built in solutions.

To read about converting Win32 binaries and packages into AppX packages for Microsoft Store inclusion, visit https://aka.ms/converterdocs

**Comment by MrAlex94** [comment]
I was under the impression that Microsoft wouldn't allow other browser onto the store. But if that has changed I'd love to get Waterfox on there!

**Comment by jebeld17** [comment]
Microsoft has definitely seen a change of heart, in my personal opinion. Facebook, Messenger, and Apple's iTunes all use WebKit and are listed in the Microsoft Store.
This can really help out users on ARM PCs find an alternative web browser that really works.

**Comment by jebeld17** [comment]
Any news on a release? :)

**Comment by jebeld17** [comment]
I've successfully converted the .PAF.EXE executable to AppX form, and can be sideloaded on Windows 10 machines with Developer Options enabled. Visit https://1drv.ms/f/s!Atsjh-pCpQhZjvQ1wF6Ww8iRSV4yGQ to download. (Sorry, I couldn't attach the file)

I chose the .PAF.EXE instead of the standard .EXE executable due to the "containerized" behavior Portable Apps and UWP apps share.

**Comment by manfromarce** [comment]
Sorry if I reopen this, but as Firefox is now on the Microsoft Store (packaged as MSIX) I think it should be possible for Waterfox too.
