### ISSUE TITLE
Waterfox 68 and webext-hybrid extensions?

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#946]
I have a custom webext-hybrid extension, I tried to load it into a new, clean Waterfox 68.0a1 profile but it doesn't work.  Among the errors:
```
addons.xpi WARN Exception running bootstrap method startup on [my addon id]: TypeError: data.webExtension is undefined(jar:file:///home/******/.mozilla/waterfox/2yfciogw.dev-edition-default/extensions/[my addon id].xpi!/bootstrap.js:103:3) JS Stack trace: startup@jar:file:///home/******/.mozilla/waterfox/2yfciogw.dev-edition-default/extensions/[my addon id portion before the @]@bootstrap.js:103:3
startup@BootstrapLoader.jsm:354:16
callBootstrapMethod@XPIProvider.jsm:1742:33
startup@XPIProvider.jsm:1841:32
_install@XPIProvider.jsm:1914:18
install@XPIProvider.jsm:1903:17
startInstall/this._startupPromise<@XPIInstall.jsm:1625:60
async*startInstall@XPIInstall.jsm:1627:9
async*install@XPIInstall.jsm:1207:12
install@XPIInstall.jsm:1851:18
checkForBlockers@XPIInstall.jsm:1502:10
install@XPIInstall.jsm:1204:12
install@XPIInstall.jsm:1851:18
checkPrompt/<@XPIInstall.jsm:1477:12
async*checkPrompt@XPIInstall.jsm:1478:7
install@XPIInstall.jsm:1201:12
install@XPIInstall.jsm:1851:18
install@XPIInstall.jsm:2370:29
startInstall@AddonManager.jsm:1752:13
installAddonFromAOM@AddonManager.jsm:1863:26
installAddonFromAOM@AddonManager.jsm:3295:26
onDrop@extensions.js:3808:22
async*initialize/<@extensions.js:142:15
EventListener.handleEvent*initialize@extensions.js:141:13
EventListener.handleEvent*@extensions.js:99:10
```

This particular error has me wondering, does Waterfox 68 alpha support webext-hybrid extensions?

(FWIW the legacy part of the extension in question is bootstrap.js based.)

**Comment by laniakea64** [comment]
Since I never received any answer on this, and converting to WebExtension+experiment worked for my cases, I'm closing this assuming webext-hybrid won't be supported in Waterfox Current.

**Comment by grahamperrin** [comment]
Thanks, are you aware of any 'mainstream' webext-hybrid extensions?

**Comment by MrAlex94** [comment]
My apologies, this must have slipped under the radar. This is for [Embedded WebExtensions](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Embedded_WebExtensions) right? I don’t think the loader knows how to deal with these anymore, as that was removed in 64. Not sure if it would be worth re-supporting it?

**Comment by laniakea64** [comment]
> Thanks, are you aware of any 'mainstream' webext-hybrid extensions?

The only 'mainstream' webext-hybrids I'm aware of were transitional for their migration to full WebExtension.

> This is for [Embedded WebExtensions](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Embedded_WebExtensions) right?

Yes, specifically classic bootstrap.js based ones.

> I don’t think the loader knows how to deal with these anymore, as that was removed in 64.

Thank you for this clarification.

> Not sure if it would be worth re-supporting it?

Well, any classic extensions already need some migration work to be ported to Waterfox Current, and again WebExtension+experiment does work for my cases.

So I would say:

1) just make sure to keep supporting WebExtension+experiments (this would include fixing https://github.com/MrAlex94/Waterfox/issues/1012 again in official builds),

2) under https://github.com/MrAlex94/Waterfox/wiki#required-changes document the need for webext-hybrid to convert to WebExtension+experiment.
