### ISSUE TITLE
v68 - Checkerboard recording is enabled by default

### ISSUE THREAD

**Issue by GitCurious** [BrowserWorks/waterfox#949]
In Waterfox v68 - Checkerboard recording is enabled by default

1. Go to about:checkerboard

**Expected behavior**
Unknown - should it be disabled or enabled ?

**Comment by Ibuprophen** [comment]
If you look at the following... 

https://github.com/MrAlex94/Waterfox/blob/7ca3cf32553e41357ff1bb1b95cc9bb9f306fafd/modules/libpref/init/all.js 

... You'll notice the following lines... 

761 pref("apz.record_checkerboarding", true);
763 pref("apz.record_checkerboarding", false);

... that looks, to me, like checkerboarding is turned on BUT, the Recording for checkerboarding is turned off. 


~ Ibuprophen

**Comment by GitCurious** [comment]
Thanks for the find

I checked a portable Nightly earlier today and noticed it was was disabled as it was in v66
Just now I have just tested a Nightly install and it's enabled.

I don`t know what it is, so wonder whether it's better to disable or ignore ?

**Comment by Ibuprophen** [comment]
I've never actually needed to touch this myself (that I can remember LOL!) so I really can't advise you one way or another. 

Your best bet is for either @MrAlex94 or @grahamperrin to provide you with some additional guidance with this. 

Good Luck! 


~Ibuprophen
