### ISSUE TITLE
Can't remove a bookamark by the boomarks button at address bar (Waterfox Alpha)

### ISSUE THREAD

**Issue by aquaspy** [BrowserWorks/waterfox#950]
Hi, I loved waterfox alpha, but seens like there is an bug in the "star" button of bookmarks, I can add a site as bookemark but can't remove it.

**Comment by ciciolina** [comment]
Hi, i have the same issue this morning, i found a workaround until next update...
If you can't delete bookmarks, close the browser and open again, go to the view history, saved bookmarks button (next to the star), and you can delete the bookmarks again, if you use the "star"  the browser block the option again and you need to restart the browser. I hope works for you.

**Comment by p1usminus** [comment]
To add to this, I get this error in the console when I click the star for a bookmarked page:
`TypeError: this._handleMessageRequest is not a function` from BookmarkPanelHub.jsm:65:33

If the panel (I assume this is the Edit bookmark menu) can't open then there'll be no way to edit the bookmark (from the toolbar), no? :P
