### ISSUE TITLE
vimfx for waterfox 68

### ISSUE THREAD

**Issue by RaitaroH** [BrowserWorks/waterfox#953]
If there is ONE extension that it makes it impossible to move to anything else besides good old waterfox is ![vimfx](https://github.com/akhodakivskiy/VimFx). Could it be possible for this addon to be fully supported under waterfox 68? One thing that I hate is that in new firefox and in chrome vim like extensions don't work on the newtab, don't work in any browser page, can't really focus the url bar and have some urlbar like thing etc. Not to mention they feel clunky.

**Comment by Peacock365** [comment]
You'd have a greater chance of success by opening this issue on the GitHub page of VimFx. The developer of the add-on porting it is generally the best solution imaginable. The developer knows the code better than anyone else. The developer should be pointed to the related documentation:

https://github.com/MrAlex94/Waterfox/wiki

**Comment by RaitaroH** [comment]
I have opened an issue there as well :)
.... with not much luck there.

**Comment by sholland1** [comment]
I switched to Waterfox because VimFx stopped working in Firefox. If it stops working in Waterfox, I will probably switch again.

**Comment by girst** [comment]
It's done: 
https://github.com/akhodakivskiy/VimFx/releases/tag/v0.21.0

compatible with firefox/waterfox 56, firefox 64, waterfox 68a1
