### ISSUE TITLE
68.0a1 on Manjaro Linux with KDE Plasma: peculiar responses to clicks in some areas

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#958]
I don't know what to make of this, can't tell whether it's a bug with the alpha … 

Screen recording: https://put.re/player?id=nvkBd1zB.mp4

At first I suspected an issue affecting parts of https://put.re/ – in some areas of the page, a simple click caused Konsole to come to front. 

After recording the screen and quitting all applications other than Waterfox, I realised that the misbehaviour (essentially: **not responding normally to clicks**) was not limited to the page. For example: a click on the adjacent tab, to the right, did not bring the tab to front. 

I doubt that this will be reproducible, so feel free to close this issue.

**Comment by grahamperrin** [comment]
This might help to visualise the symptoms. 

With a relatively small window, not too far from the left of the screen, pointing at (hovering over) the account button (for example) was effective: 

![image](https://user-images.githubusercontent.com/192271/57573518-b40c6f00-7420-11e9-852b-319b4c21d5ff.png)

With the same window maximised, pointing at the same button had no effect: 

![image](https://user-images.githubusercontent.com/192271/57573524-cedee380-7420-11e9-9049-8cf1f56e46e8.png)

### Worked around

After a simple quit, I could not reproduce the peculiarity.

**Comment by hawkeye116477** [comment]
I have same distro and for me it works ok :smile:.
