### ISSUE TITLE
wf68: vimperator install shows addon is corrupted

### ISSUE THREAD

**Issue by neg-serg** [BrowserWorks/waterfox#960]
Cannot install vimperator with 68 alpha. Is the any change that old xpi-based addons will be supported? I am not fully understand what is "bootstrapped" addons. Does the bootstraped addons has differenct architecture?

**To Reproduce**
```
git clone https://github.com/vimperator/vimperator-labs
git checkout origin/ff56-fixes
make
```

and load it with waterfox, then get smth like "...could not be installed because of it appears to be corrupt"

**Expected behavior**
Vimperator works well.

**Desktop (please complete the following information):**
- OS: Arch linux, rolling release.
 - 68.0.1 alpha

**Comment by grahamperrin** [comment]
I know nothing of `ff56-fixes`, I guess that the original e.g. https://ca-archive.biz.tm/storage/4/4891/vimperator-3.16.0-fx.xpi?origin=caa will require changes for compatibility with Waterfox 68. 

https://github.com/MrAlex94/Waterfox/wiki
