### ISSUE TITLE
Crashes: no such file or directory

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#961]
```
[grahamperrin@momh167-gjp4-virtualbox-manjaro .mozilla]$ find . -name "*default" | sort
./firefox/93ogp617.default
./firefox/93ogp617.default/storage/default
./waterfox/2comghpi.dev-edition-default
./waterfox/2comghpi.dev-edition-default/storage/default
./waterfox/xoo6tnbb.default
[grahamperrin@momh167-gjp4-virtualbox-manjaro .mozilla]$ ls -hl firefox/93ogp617.default/crashes
total 32K
drwx------ 2 grahamperrin grahamperrin 4.0K May 11 21:13 events
-rw------- 1 grahamperrin grahamperrin  26K May 11 21:12 store.json.mozlz4
[grahamperrin@momh167-gjp4-virtualbox-manjaro .mozilla]$ ls -hl waterfox/2comghpi.dev-edition-default/crashes
ls: cannot access 'waterfox/2comghpi.dev-edition-default/crashes': No such file or directory
[grahamperrin@momh167-gjp4-virtualbox-manjaro .mozilla]$ ls waterfox/2comghpi.dev-edition-default/crashes
ls: cannot access 'waterfox/2comghpi.dev-edition-default/crashes': No such file or directory
[grahamperrin@momh167-gjp4-virtualbox-manjaro .mozilla]$ 
```text

Firefox to the left, Waterfox to the right: 

![image](https://user-images.githubusercontent.com/192271/57576680-e8eae700-745d-11e9-8bef-25b00469fed3.png)

**Comment by troysjanda** [comment]
Can confirm that there is no crash saves in the profile folder. This can be problematic if trying to toubleshoot issues. I have an issue that sometimes hitting the back arrow causes that tab to crash. WF68.0a Windows 10 Enterprise.

**Comment by grahamperrin** [comment]
@troysjanda to add some context, <https://github.com/MrAlex94/Waterfox/issues/607#issuecomment-398057612> a few months ago: 

> Still keeping it disabled, infrastructure would take too much time.

– to which I gave a thumbs-up, because I can't argue with how anyone chooses to spend their time. 

From more recent <https://www.waterfox.net/about/>: 

> … Waterfox focuses on giving users choice. The browser is focused on power users, which lets you make the important decisions. …

IMHO we have enough power users in the support area i.e. https://www.reddit.com/r/waterfox/ to offer a sane response to anyone who might question the presence of crash files. 

Wild guess: `about:crashes` might be _relatively_ difficult to implement in a way that is both (a) meaningful and (b) respectful of this statement: 

> no data or telemetry is sent back to Mozilla or the Waterfox project.

### In the absence of `about:crashes`

People might scream bloody murder at the sight of something like this: 

![image](https://user-images.githubusercontent.com/192271/57586756-547e9400-74f2-11e9-8b3d-af199056990d.png)

– however if relevant preference are preset and immutable, then the response, to concerned users, is that the data simply **can not be sent**. A whittled down dialogue that uses the word _save_ in lieu of _send us_ and then the choice for the end user is simple. Either: 

1. quit Waterfox; or 
2. restart Waterfox. 

Re: preferences I'm uncertain. I imagine that this one (at least) must be immutable if sending of reports is to be prevented: 

`browser.tabs.crashReporting.sendReport` `false`

Re: whittling down I'd offer to submit a pull request but I know from experience that I'd have difficulty making a coherent job of it!
