### ISSUE TITLE
v68: Config pref 'toolkit.telemetry.enabled' defaults to TRUE

### ISSUE THREAD

**Issue by GitCurious** [BrowserWorks/waterfox#964]
The pref: toolkit.telemetry.enabled

defaults to TRUE in v68 (normal in pre-release Firefox)

For Waterfox purposes, it needs to be unlocked and changed to False.

**Comment by WagnerGMD** [comment]
Just once advice : rename the title because it's confusing.

PS : If you need the list of settings about this matter. Just ask me nicely.

**Comment by MrAlex94** [comment]
Will change this in next Alpha. Although it shouldn't do anything as the telemetry modules aren't being built: https://github.com/MrAlex94/Waterfox/blob/gecko68/browser/branding/alpha/configure.sh#L9

**Comment by GitCurious** [comment]
Thanks @WagnerGMD  I did manage to fix it after seeing others with the same problem.


@MrAlex94 

Thanks, I am oblivious to how the inner workings work but noticed the about:telemetry page was populated with data when this pref was active and when disabled it appears empty.

It also creates a folder called 'datareporting' with [admittedly] little inside it due to telemetry being hobbled, the folder is not created otherwise.

I am sure telemetry is an insidious problem within the code base which is beyond my understanding but presumed it would be better if the actual collection of data was also stymied as it's pointless to gather useless data, even though it ultimately gets sent nowhere .

------------------

v68 was virtually painless to move over to from Fx 66 - apart from a couple of minor tweaks the profile transferred without issue, including some extensive css styling, what a relief.

So thanks again for getting 68 out !
