### ISSUE TITLE
v68 - Java jre support?

### ISSUE THREAD

**Issue by GeekinaCave** [BrowserWorks/waterfox#965]
Good day

v68 will support java jre like the v56 version?, i want to know if i can use it in workplace to.

**Comment by sagudev** [comment]
Check here: https://github.com/MrAlex94/Waterfox/releases/tag/68.0a1 It says:
> Known Issues:
    - NPAPI plugins load, but web pages can't access them (except for Adobe Flash).

So they are planned to be supported.

**Comment by aikitect** [comment]
Any news about support. It would be great to have java npapi support on last waterfox branch
