### ISSUE TITLE
confused how to fix linux waterfox 59.2.9 (unable install add-ons/themes)

### ISSUE THREAD

**Issue by linuxgirl22** [BrowserWorks/waterfox#966]
Hello :-)

Thanks for the previous fix, which had worked great, but, reading reddit threads, I'm very confused by what to do now. There are so many different versions/links etc and I'm not great at anything other than the basics. I click on a link that looks likely and get a 'waterfox stopped install' message. 

Unable to install add-ons/themes (download failed; please check your connection)

Manjaro 18.0.4 kde stable, using 56.2.9 appimage.

**Comment by laniakea64** [comment]
The best option would be to self build Waterfox from latest master branch.  If you don't know how to do this, or don't have time, you can install https://addons.mozilla.org/firefox/addon/disabled-add-on-fix-52-56/ (if the "Add to Firefox" button is greyed out for you, see https://github.com/MrAlex94/Waterfox/issues/956#issuecomment-492028985 )

**Comment by linuxgirl22** [comment]
Thanks for responding laniakea64. Sorry that I'm still a bit confused; really am not very tech ... no way I could build waterfox. But I tried right-clicking on the greyed 'add to firefox', then pasted that link into a new tab, and it's installed. Extension's active, but unfortunately hasn't fixed things.

**Comment by grahamperrin** [comment]
This alone, from Mozilla, should fix Waterfox 56.2.9: 

- https://addons.mozilla.org/firefox/downloads/file/2851310/disabled_add_on_fix_for_firefox_52_56-1.1.4.xpi

(It's the extension that you installed around three hours ago, with the tail trimmed from the address.)

> hasn't fixed things.

Can you share a screenshot? Thanks. 

PS even better, 

> themes

Let us have the address of one of the themes that you can't install.

**Comment by linuxgirl22** [comment]
Thanks for response, grahamperrin. The same error message happens for whichever theme I click on from the main page eg [https://addons.mozilla.org/en-GB/firefox/addon/calm-sunrise-by-madonna/?src=hotness](url) I can provide any screenshots you need; which would be helpful?

EDIT: I checked the link works, but it opens in github (for me), so here's a picture of the linked-to example theme on the main page ... 

![calm sunrise](https://user-images.githubusercontent.com/35760727/57811543-66666e00-7762-11e9-9597-df6a2780919a.png)

The fix definitely looks to be active, so it's puzzling. 

![hotfix active](https://user-images.githubusercontent.com/35760727/57811715-f0163b80-7762-11e9-9c91-e9c6ed218943.png)

**Comment by laniakea64** [comment]
> The same error message happens for whichever theme I click on from the main page eg https://addons.mozilla.org/en-GB/firefox/addon/calm-sunrise-by-madonna/?src=hotness

This error is unrelated to armagadd-on-2.0.  I don't know anything about this type of theme, so I have no idea why the error.  But [version 2.0 of this theme](https://addons.mozilla.org/firefox/addon/calm-sunrise-by-madonna/versions/) does install in Waterfox.  Does it work for you?

**Comment by linuxgirl22** [comment]
Unfortunately version 2.0 doesn't install either; the same error. When the mozilla issue started both add-ons and themes wouldn't install ... I'd presumed it was the same now, after seeing the reddit post saying about removal of the fix, but have just tried a couple of extensions and there's no error message there, so the latest fix extension, from earlier today, has enabled the add-on extensions part, but not add-on themes. 

If I right-click on the theme's install button and copy the link into another tab (the same way I installed today's fix extension), a message comes up about being unable to install because add-on appears to be corrupt.

**Comment by LeeBinder** [comment]
it's just a theme.... nothing you need at all... Just forget about it and move on... ;)

**Comment by linuxgirl22** [comment]
No. Everyone freely themes their browser. I've used Waterfox for quite a while, and been impressed at how things are fixed, so look forward to that when possible. Adding in unnecessary comments clutters the thread for anyone with the same issue who wants to read through what to do, and for those responding to the issue.

**Comment by LeeBinder** [comment]
Everyone? I don't so that's not everyone .. ;) Maybe rather *hardly* anybody themes their Browser?

Anyway, please note that in the process of the recent purge on addons.mozilla.org, Mozilla not only removed all legacy Extensions but also Themes. For example (I know you're running WF on Linux), they ONLY left themes for Firefox Android 65.0+. You might still find an older theme version on addons.mozilla.org which might install, but might not have any effect.

In the case of your theme, toggle to a different useragent string for addons.mozilla.org (in case you indeed do want to keep messing with this).

Good luck & bye

**Comment by linuxgirl22** [comment]
I've just tried installing a theme from Waterfox's internet archive add-ons backup, and it worked! An extension hasn't though ... whether compatible or not compatible, says 'does not match the add-on Waterfox expected'. Extensions directly install, and themes install via Waterfox's backup, at this point.

**Comment by grahamperrin** [comment]
> An extension 

Please let us have the address. 

(What you describe is probably expected behaviour, for which there will be a workaround.)

**Comment by grahamperrin** [comment]
> version 2.0 doesn't install 

Please try the direct link below. 

A simple click (refrain from right-clicking): 

https://addons.mozilla.org/firefox/downloads/file/1683209/calm_sunrise_by_madonna-2.0-an+fx.xpi

**Comment by grahamperrin** [comment]
> … In the case of your theme, toggle to a different useragent string …

@LeeBinder thanks, but this is not a workaround. 

@linuxgirl22 if you changed the UA string, please revert your change.

**Comment by linuxgirl22** [comment]
Thanks grahamperrin. If I pick e.g. Reddit Enhancement Suite: [https://web.archive.org/web/20170909162055/https://addons.mozilla.org/en-uS/firefox/addon/reddit-enhancement-suite/](url) there's a long wait and the issue happens. I right-click on the link and open it in another tab ... there'd been an error, which I was going to quote now, but I've just gone back and clicked on the tab where the error was, and the extension offered to install! I'm trying out the Ghostery extension install now, as a 2nd test, but that page is going through the long wait/read/transfer, then just stops doing that. Going to reboot browser and try again. 

Thanks about the UA string ... luckily I didn't know how to do that. :-)

**Comment by linuxgirl22** [comment]
Thanks grahamperrin. If I pick e.g. Reddit Enhancement Suite: [https://web.archive.org/web/20170909162055/https://addons.mozilla.org/en-uS/firefox/addon/reddit-enhancement-suite/](url) there's a long wait and the issue happens. I right-click on the link and open it in another tab ... there'd been an error, which I was going to quote now, but I've just gone back and clicked on the tab where the error was, and the extension offered to install! I'm trying out the Ghostery extension install now, as a 2nd test, but that page is going through the long wait/read/transfer, then just stops doing that. Going to reboot browser and try again. 

Thanks about the UA string ... luckily I didn't know how to do that. :-)

**Comment by linuxgirl22** [comment]
The reboot sorted things ... didn't have enough time to copy/paste the issue that came up (had time to see 503?/redirecting) and then install options came up. 
So both themes and extensions work great from the archive location; thank you that's there, and enables things to work great on Linux.

**Comment by grahamperrin** [comment]
Thanks, re: https://github.com/MrAlex94/Waterfox/issues/966#issuecomment-493264562 above please, can you confirm that your fixed Waterfox 56.2.9 works with the direct link to version 2.0 of _Calm Sunrise by MaDonna_?

**Comment by linuxgirl22** [comment]
My apologies for missing that; yes, the theme installs through directly clicking the link.

**Comment by grahamperrin** [comment]
OK, thanks. 

You already discovered the workaround that sometimes applies in the Wayback Machine – great. 

You'll probably find that [yesterday's release of Waterfox 56.2.10](https://www.waterfox.net/blog/waterfox-56.2.10-release-download/) is without a fix for themes such as version 3.0 of _Calm Sunrise by MaDonna_. If you like, subscribe to this issue: 

- [(Mozilla 1403840) implement COSE for add-on signatures · Issue #972 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/972)

**Comment by linuxgirl22** [comment]
Thank you for the links and for opening the other thread; I've subscribed. Hadn't known there was a 56.2.10 release ... very interesting to read about, and about the privacy measures coming into the website too. Really impressive, also about repeat captchas going. 

When the appimage for 56.2.10 comes through, being able to use the Wayback will be great ... or do you mean the fix earlier in this thread can't be used with 56.2.10, and the Wayback may not work also?

**Comment by grahamperrin** [comment]
### Wayback Machine

The Wayback Machine is [an Internet Archive project](https://archive.org/projects/). 

Usable with any web browser that has JavaScript enabled. 

(Without JavaScript: it's less usable. Less easy to browse from one capture – one point in time – to another.) 

The Wayback Machine should be as usable with Waterfox 56.2.10 as it is with version 56.2.9. 

### Mozilla's _Disabled Add-on Fix for Firefox 47 - 56_

https://addons.mozilla.org/firefox/downloads/file/2851310/disabled_add_on_fix_for_firefox_52_56-1.1.4.xpi 

- presents itself as _Hotfix for Firefox bug 1548973 (armagaddon 2.0) mitigation_ (the name of the page at AMO is specific; the name of the installed extension is generic)
- can apply to Waterfox 56.1.0, but it is not required
- will not help in cases such as these: https://github.com/MrAlex94/Waterfox/issues/972#issuecomment-493660807

**Comment by linuxgirl22** [comment]
Thank you for explanation; that's great that the Wayback Machine will work across versions. Thanks for further information about fixes.

**Comment by hawkeye116477** [comment]
@linuxgirl22 AppImage will be much later, cuz I build it from official tar package, which currently it's not available.  
Anyway for Manjaro KDE there is also package `waterfox-kde-bin`, which you can get from aur or directly from `https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-kde` and that package has 56.2.10 version :smile:.

**Comment by linuxgirl22** [comment]
Hi @hawkeye116477! I'd just seen the 'No data for home:hawkeye116477:waterfox / waterfox-appimage' message lastnight, and panicked a bit, so thanks for your message and links. Great that the unofficial source/AUR versions are there too. I'll look forward to the appimage when that's possible, and I appreciate all your work. :-)

**Comment by grahamperrin** [comment]
@linuxgirl22 would you like to close this issue?

56.2.10, which includes Mozilla's fix for armagadd-on 2.0, is now available from https://www.waterfox.net/releases/

For versions of themes that are currently not addable to Waterfox 56.2.10, we have issue #972

**Comment by linuxgirl22** [comment]
Thanks @grahamperrin for your help with this, and, yes, it makes sense to close it, with #972 taking in anything relating to this. I'll wait a bit longer to see what happens about the appimage. I haven't compiled anything before, but there's a 56.2.10 just shown up in the AUR (manjaro kde stable), so I'll give that some thought. Thanks again. :-)

**Comment by hawkeye116477** [comment]
@linuxgirl22 `I'd just seen the 'No data for home:hawkeye116477:waterfox / waterfox-appimage' message lastnight, and panicked a bit`
It always said `No data`, cuz SUSE didn't make download page with instructions for AppImage, here is proper page => `https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/` and instructions are always here => `https://appimage.github.io/Waterfox/`. Anyway for KDE, waterfox-kde should be better, cuz it includes SUSE's patches for better integration with KDE (KDE file dialogs, file associations, etc) little modified by me and Global Menu support :smile:

**Comment by linuxgirl22** [comment]
Thanks hawkeye :-) I'd had that page bookmarked for months, so there's gremlins at work somewhere, lol. [EDIT: just clicked on it now and it's back] Thank you very much for the links, and advice. I've always preferred appimages for main programs (waterfox/krita/freetube), if at all possible, so, if there are any glitches/big changes, there's always the option of the previous appimage eg only appimages could be used for Krita over a number of weeks, due to qt changes they said. 
If there aren't going to be Waterfox appimages, it may be best to not do upgrades for a couple of weeks or so, as I'd be more of a hindrance if there was any initial large bug-fixing to do. Not great at all that, unless it's very clear and basic, so I've done donations along the way instead.

**Comment by hawkeye116477** [comment]
@linuxgirl22 `if there are any glitches/big changes, there's always the option of the previous appimage`, with pkg.tar.xz packages it's still possible, you should have previous versions saved on `/var/cache/pacman/pkg`. Anyway AppImage for 56.2.10 is ready, just not published yet, it will probably be in about an hour :smile:

**Comment by linuxgirl22** [comment]
@hawkeye116477 Cool about the appimage! I'd misunderstood that the AUR and appimages updated at the same time, so wasn't sure if appimages were continuing, incase you were (understandably) busy  ... thank you! Is there a way to send a donation?

**Comment by hawkeye116477** [comment]
@linuxgirl22 AppImage is mainly repack of official package, so it can be faster than waterfox-kde (which is compiled from offical GH repo by me with my special patches), but from recently it's opposite, cuz MrAlex has little delays with Linux package. I do not accept donations at the moment.

**Comment by linuxgirl22** [comment]
@hawkeye116477 Thanks for explanation, and let me know if you do start accepting donations. :-)
