### ISSUE TITLE
68.0a1 - Not able to move bookmarks

### ISSUE THREAD

**Issue by goteksc** [BrowserWorks/waterfox#967]
**Describe the bug**
In addition to #950 (star button in the URL-bar not doing anything) we can't move bookmarks between folders or up/down the list.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: latest

**Comment by N-R-G** [comment]
Same bug on my **Mac OS X 10.10.5**

I need to restart Waterfox Alpha to make bookmark's managment available without the issue

In meantime you can solve the issue using this add-on:

[Bookmarks Manager and Viewer](https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager-and-viewer/?src=search)

**Comment by grahamperrin** [comment]
Reproducible with a new profile? 

- about:profiles

**Comment by goteksc** [comment]
Yes it seems like it.

Ran waterfox -P, created a new profile, imported my bookmarks and moved them around. Worked so far. But *after* creating a new bookmark with the star button (that works, but it does nothing else afterwards as the guys in #950 talked about) moving bookmarks around is no longer possible. I failed to notice that it works until using the star-button earlier.

I'm beginning to feel this issue is redundant and I should've just added to #950

**Comment by laniakea64** [comment]
Does https://github.com/MrAlex94/Waterfox/pull/975 fix this issue as well?

**Comment by N-R-G** [comment]
> Does #975 fix this issue as well?

how can I apply it on Waterfox 68 for mac and for windows?

**Comment by laniakea64** [comment]
@N-R-G The best way is to download the patch from the pull request and compile Waterfox 68 yourself.  If you don't know how to self build Waterfox 68, or don't have the time, that patch can be "hacked" into `browser/omni.ja`.

**Note: Although modifying omni.ja is less time-consuming than building from source, it is much more risky.  Waterfox could crash if omni.ja is modified incorrectly.  I wouldn't do this in a production environment.**

Waterfox 68 `omni.ja` seems to be a standard zip file in v68, so this should work -

1) completely quit Waterfox

2) open `<waterfox install dir>/browser/omni.ja` with your favorite archive manager
(In Mac OS it's `Waterfox Alpha.app/Contents/Resources/browser/omni.ja`)

3) inside the archive, navigate to `chrome/browser/res/activity-stream/lib/`.  The file to patch is `BookmarkPanelHub.jsm`

4) Near the top of `BookmarkPanelHub.jsm`, you'll see these lines -
```
class _BookmarkPanelHub {
  constructor() {
    this._id = "BookmarkPanelHub";
    this._trigger = {id: "bookmark-panel"};
    this._handleMessageRequest = null;
    this._addImpression = null;
    this._initalized = false;
    this._response = null;
    this._l10n = null;
```

As shown in https://github.com/MrAlex94/Waterfox/pull/975/files , change
```
this._handleMessageRequest = null;
```
to
```
this._handleMessageRequest = function() {};
```

5) Update the file in `omni.ja`

6) Start Waterfox with `-purgecaches` command-line option
