### ISSUE TITLE
v68: Roomy Bookmarks Toolbar

### ISSUE THREAD

**Issue by p1usminus** [BrowserWorks/waterfox#968]
Hello,

I had a go at updating one of my favourite addons for the Waterfox 68 alpha, using the documentation on the wiki. I have made a repo for this new version here: https://github.com/p1usminus/roomybookmarksredux

Sorry for posting this here - I know it's not an issue but I wasn't sure _where_ to post this. 😅 To this end, I wondered if a general thread, here or maybe on r/waterfox to discuss legacy addons that already work with v68, or have been updated to do so, would be helpful.

**Comment by p1usminus** [comment]
A small issue: I have had zero success using the JSON manifest as outlined [here](https://github.com/MrAlex94/Waterfox/wiki/Engage-the-new-overlay-loader#switch-to-json-manifest) - when I try to use this instead of install.rdf, the extension installs, but doesn't work at all:
- There is no options button in about:addons. Rather annoying. I wondered if it was related to [this](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57#Removed_and_changed_in_mozilla59) but it happens whether I use open_in_tab or not.
- There is no legacy badge so it looks like Waterfox thinks it's a webextension, but the console errors suggest otherwise:
`WebExtensions: Legacy WebExtension ALone-live@ya.ru loading for other reason than startup (ADDON_INSTALL), refusing to load immediately.`
- These messages showed up after restarting the browser but I don't know what the second one means
`WebExtensions: Loading add-on preferences from <xpi location>`
`WebExtensions: Firing profile-after-change listeners for ALone-live@ya.ru`
- Even adding an update_url to the manifest produced errors: `addons.webextension.ALone-live@ya.ru	WARN	Loading extension 'ALone-live@ya.ru': Reading manifest: Error processing update_url: An unexpected property was found in the WebExtension manifest.`

At the moment, it seems bootstrap.js + install.rdf is the way to go...

- [Latest version with manifest.json](https://github.com/p1usminus/roomybookmarksredux/raw/manifest/ALone-live%40ya.ru%201.5.4.1%20manifest.xpi)
- [Manifest.json](https://github.com/p1usminus/roomybookmarksredux/blob/manifest/src/manifest.json)

**Comment by Mikhail-M12** [comment]
I have faced same issues trying to run another overlay extension. It works only in debug mode ("Load Temporary Add-on..." in about:debugging ). But in G3 even it has stopped working: "ExtensionError: can't access property "getService", Cc['@mozilla.org/component-manager-extra;1'] is undefined" in ExtensionUtils.jsm:56:5 - message in Browser Console.

**Comment by p1usminus** [comment]
Good evening!

> 
> 
> I have faced same issues trying to run another overlay extension. It works only in debug mode ("Load Temporary Add-on..." in about:debugging ). 

That is strange. Installing normally in Waterfox Current has always worked for me.

>
> 
> But in G3 even it has stopped working: "ExtensionError: can't access property "getService", Cc['@mozilla.org/component-manager-extra;1'] is undefined" in ExtensionUtils.jsm:56:5 - message in Browser Console.

My version installs on G3 but does not work, unsurprisingly 😥

However. I tried @117649's very nice fork (for Firefox Developer Edition) on G3 in a Ubuntu VM and most of the features work. The multirow feature does not - I think it may be trying to use a XUL feature that is no longer available. You can download it here: https://github.com/117649/roomybookmarksredux

(I am not aware of what has changed between ESR 68 and 78 - is there more Thunderbird documentation? - so I do not know what to change to bring the multirow bookmarks back specifically, but I will definitely be reading through what @117649 has changed/added when I have time 🥰)

Thank you,
+-

**Comment by Mikhail-M12** [comment]
>when I try to use this instead of install.rdf, the extension installs, but doesn't work at all

>Installing normally in Waterfox Current has always worked for me

I have not understood something...

Anyway, I have already rewritten my addon to bootstrapped format. It works in Current and G3.

**Comment by p1usminus** [comment]
> 
> 
> > when I try to use this instead of install.rdf, the extension installs, but doesn't work at all
> 
> > Installing normally in Waterfox Current has always worked for me
> 
> I have not understood something...
> 
> Anyway, I have already rewritten my addon to bootstrapped format. It works in Current and G3.

I think I misunderstood 😅 I thought you were discussing this addon!

Yes. The bootstrapped format worked fine for me, but the manifest version did not.

**Comment by 117649** [comment]
> Good evening!
> 
> > I have faced same issues trying to run another overlay extension. It works only in debug mode ("Load Temporary Add-on..." in about:debugging ).
> 
> That is strange. Installing normally in Waterfox Current has always worked for me.
> 
> > But in G3 even it has stopped working: "ExtensionError: can't access property "getService", Cc['@mozilla.org/component-manager-extra;1'] is undefined" in ExtensionUtils.jsm:56:5 - message in Browser Console.
> 
> My version installs on G3 but does not work, unsurprisingly 😥
> 
> However. I tried @117649's very nice fork (for Firefox Developer Edition) on G3 in a Ubuntu VM and most of the features work. The multirow feature does not - I think it may be trying to use a XUL feature that is no longer available. You can download it here: https://github.com/117649/roomybookmarksredux
> 
> (I am not aware of what has changed between ESR 68 and 78 - is there more Thunderbird documentation? - so I do not know what to change to bring the multirow bookmarks back specifically, but I will definitely be reading through what @117649 has changed/added when I have time 🥰)
> 
> Thank you,
> +-

I think what I'm changed was majorly matching what mozilla has done on change property names and I modified logic of bookmarks bar hiding to hid when mouse cursor move away from the area instead of exit whole Nav toolbox. I also edit CSS of bookmarks on top so it looks and function like the normal one. Multirow however isn't a function I really ever used thus it hasn't been tested or fixed in any way.

In fact I myself still stuck with WF classic so I just backport those function changes to old version and use that.

For multirow I think it was done using CSS? One thing I notice for 7x+ is that it seems only user_sheet works for CSS registered by addons the other two just won't give a shit, Maybe you should check that first.

**Comment by 117649** [comment]
> I have faced same issues trying to run another overlay extension. It works only in debug mode ("Load Temporary Add-on..." in about:debugging ). But in G3 even it has stopped working: "ExtensionError: can't access property "getService", Cc['@mozilla.org/component-manager-extra;1'] is undefined" in ExtensionUtils.jsm:56:5 - message in Browser Console.

The whole Overlay system just gone with XUL.

**Comment by Mikhail-M12** [comment]
>The whole Overlay system just gone with XUL.

Then article https://github.com/MrAlex94/Waterfox/wiki should be edited.

**Comment by MrAlex94** [comment]
Indeed - apologies for such a delayed response. Documentation needs to be updated and is a priority task at the moment.

**Comment by hawkeye116477** [comment]
> The whole Overlay system just gone with XUL

As I see there is code for loading overlays, but it's not completed, some parts are missing, so that's the reason why that error appears. 

I experimented a bit and appears that something starts working.
![2021-01-04_23-57](https://user-images.githubusercontent.com/19818572/103588020-ab678700-4ee8-11eb-92a9-91c70e1bd2d6.png)

**Comment by 117649** [comment]
> > The whole Overlay system just gone with XUL
> 
> As I see there is code for loading overlays, but it's not completed, some parts are missing, so that's the reason why that error appears. 
> 
> I experimented a bit and appears that something starts working.
> ![2021-01-04_23-57](https://user-images.githubusercontent.com/19818572/103588020-ab678700-4ee8-11eb-92a9-91c70e1bd2d6.png)
> 

As far as I know old Overlay() is c++ code and it is gone. And now firefox is using rust. 

I think what that textscript in wiki suggested is a pice of JavaScript code that load overlays. Bootstrap add-ons use such thing all the time. @MrAlex94

**Comment by hawkeye116477** [comment]
> I think what that textscript in wiki suggested is a pice of JavaScript code that load overlays. 

Yes, that's what I meant and here is that code => https://github.com/MrAlex94/Waterfox/blob/future/browser/components/extensions/common/src/Overlays.jsm.

**Comment by 117649** [comment]
> > I think what that textscript in wiki suggested is a pice of JavaScript code that load overlays. 
> 
> Yes, that's what I meant and here is that code => https://github.com/MrAlex94/Waterfox/blob/future/browser/components/extensions/common/src/Overlays.jsm.

Oh, this one. In fact the function of this file is rather limited. I think it won't load nested js file from script tag and can't insert tool bar button right. It just can't handle a complex overlay structure right. I have a heavily modified version with right tool bar button handling and tweaked scripts loading logic for my Tab mix plus convert, and Tab-group have an more complex one that even have hot overlay unload for restartless add-on enable, disable.
