### ISSUE TITLE
Shift+scrollwheel does not scroll horizontally

### ISSUE THREAD

**Issue by AstroSnail** [BrowserWorks/waterfox#969]
**Describe the bug**
Shift+scrollwheel does not scroll horizontally.

**To Reproduce**
1. Go to a page (preferably to one that scrolls horizontally e.g. zoom into an absurdly large image)
2. Hold shift
3. Turn the scrollwheel

**Expected behavior**
The page should scroll horizontally, as it does in Firefox and many other desktop applications.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 56.2.9

**Additional context**
Instead of the above expected behaviour, shift+scroll seems to go forwards and backwards in history.

**Comment by grahamperrin** [comment]
### Extensions

#### Horizontal Scroll

- caa:addon/horizontal-scroll

I used this occasionally a few months ago, with Waterfox 56.2.3. 

#### Shift + Scroll (Horizontal Scrolling)

I had this installed but disabled with 56.2.3. 

From <https://addons.mozilla.org/addon/shift-scroll/>:

> This functionality has been added in Firefox 58.

– which probably explains why you expect, but don't find, the functionality in Waterfox classic. 

(Historically: Waterfox 56.0 was based on Firefox 56.0.2.)

**Comment by AstroSnail** [comment]
Thanks for the find! I guess I got too used to the newer firefoxes.
