### ISSUE TITLE
youtube player HTML5 problem

### ISSUE THREAD

**Issue by BlindMeister** [BrowserWorks/waterfox#97]
Hello,
First, I'm sorry for bad EN lng.
I'm running Windows 7 Pro x64 on DIY PC: MSI 990FXA-GD65 m/b, AMD FX-4300, 16GB DDR3, AMD R9-2XX series vga, Kingston Hyperx Savage 240GB ssd.
So, here is a reason why I post issue on WaterFox - 51.0.1 (64-bit):
When I want to open: [https://www.youtube.com/watch?v=dHlFBegnN0c&gl=GB] Youtube player screen pop-up with message:

> Your browser does not currently recognize any of the video formats available.
Click here to visit our frequently asked questions about HTML5 video.

I'll peep on freq. asked questions - but without any useful help in there.

Here is Debug Info:
`{"ns":"yt","el":"detailpage","cpn":"NgQHNhJt_DNLLkcu","docid":"dHlFBegnN0c","ver":2,"referrer":"https://www.youtube.com/watch?v=dHlFBegnN0c","cmt":"0","plid":"AAVHdIL97LFc_RNi","ei":"jqeRWKSpMsX11gKbqIv4Ag","fmt":"243","fs":"0","rt":"747.94","of":"b-mjnC0miEaLmvnU7TivOQ","adformat":null,"content_v":null,"euri":"","lact":1,"live":null,"cl":"146103989","mos":0,"osid":null,"state":"80","vm":"CAEQAQ","volume":100,"c":"WEB","cver":"1.20170131","cplayer":"UNIPLAYER","cbr":"Firefox","cbrver":"51.0.1","cos":"Windows","cosver":"6.1","hl":"en_US","cr":"GB","len":"36","fexp":"9422596,9428398,9431012,9431681,9433221,9434046,9434289,9434905,9438971,9439580,9441513,9443443,9445363,9446054,9446364,9449034,9449243,9450059,9450707,9451688,9451873,9456640,9457141,9457494,9459008,9460067,9460072,9460260,9460727,9461331,9461588,9461984","afmt":"250","vct":"0.000","vd":"NaN","vpl":"","vbu":"","vpa":true,"vsk":false,"ven":false,"vpr":1,"vrs":0,"vns":0,"vec":null,"vvol":1,"debug_error":{"errorCode":"html5.missingapi","errorDetail":"nocodecs.1","message":"This video format is not supported.","messageKey":"YTP_HTML5_NO_AVAILABLE_FORMATS_FALLBACK"},"ismb":11300000,"debug_videoId":"dHlFBegnN0c","0sz":false,"op":"","yof":true,"dis":"","cgr":true,"debug_playbackQuality":"medium","debug_date":"Wed Feb 01 2017 10:29:32 GMT+0100 (Central European Standard Time)"}`

Somehow, I managed issue in this way: I started any video on the right side column of the Youtube site, and when that video start to play, I tap backspace cap and in that moment first selected video start to play.

PS
I have following extensions (addons) installed on WaterFox: BitTorrent-WebUI, DownThemAll,  Ghostery and uBlock Origin - but the same thing appear when I disable all of them.
Here is a hardcopy of screen:
![image](https://cloud.githubusercontent.com/assets/25477804/22503698/35c12e0a-e873-11e6-935f-564ceb29793d.png)

Thanx in advance

**Comment by PandaCodex** [comment]
Ghostery harvests your data and is owned by an **advertising company**, uBlock origin has all the same features and blockers as Ghostery making Ghostery obsolete.

**Ghostery sells the user data collected to advertisers**

Are all the boxes marked with a blue checkbox https://www.youtube.com/html5

![html5](https://cloud.githubusercontent.com/assets/25470255/22505600/0ef6550c-e8c8-11e6-8b58-aa3ef1b8addf.JPG)

**Comment by BlindMeister** [comment]
On 01.02.2017. 12:50, Panda wrote:
> Ghostery harvests your data and is owned by an **advertising company**, uBlock origin has all the same features and blockers as Ghostery making Ghostery obsolete.
>
> **Ghostery sells the user data collected to advertisers**
>
> Are all the boxes marked with a blue checkbox https://www.youtube.com/html5
>
> ![html5](https://cloud.githubusercontent.com/assets/25470255/22505600/0ef6550c-e8c8-11e6-8b58-aa3ef1b8addf.JPG)
>
>
Hi Panda,

Thanx on your very fast response...
My WaterFox not support only H.264 & WebM VP8, here is proof...

...but, I have "OpenH264 Video Codec" which is odd to me in this case. 
Why is in red on upper pic?!

Here is a pic about this H264 codec:

**Comment by PandaCodex** [comment]
**OpenH264 Video Codec** is used only for WebRTC and nothing else.

Type **about:config** in your browsers address bar then locate the following preferences and set to **true**

- media.mediasource.enabled
- media.webm.enabled
- media.mp4.enabled
- media.mediasource.mp4.enabled

Then visit https://www.youtube.com/html5 to verify all blue.

**Comment by BlindMeister** [comment]
On 02.02.2017. 00:38, Panda wrote:
> **OpenH264 Video Codec** is used only for WebRTC and nothing else.
>
> Type **about:config** in your browsers address bar then locate the following preferences and set to **true**
>
> - media.mediasource.enabled
> - media.webm.enabled
> - media.mp4.enabled
> - media.mediasource.mp4.enabled
>
> Then visit https://www.youtube.com/html5 to verify all blue.
>
Hey, that's work. In my case, only "media.webm.enabled" was false. When 
I change to true all reds gone.

Now I am all blue  ;-)

Thank you very much Panda.
