### ISSUE TITLE
AMO: port changes from Firefox 59 for compatibility with themes that appear to be for Firefox 53 and later

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#972]
# Note

When this issue was opened, I assumed that incompatibilities related to COSE. 

Re: https://github.com/MrAlex94/Waterfox/issues/972#issuecomment-495521922 below it seems that COSE is unrelated so to minimise confusion, I'm removing much of my commentary (it'll remain visible through use of the _Edited_ menus). 

### Distinguishing this issue from Mozilla armagadd-on 2.0

At https://github.com/mozilla/addons/issues/851#issuecomment-489277802 _Wood time_ (amongst the [test cases](https://github.com/MrAlex94/Waterfox/issues/972#issuecomment-493660807) below) bugged both Waterfox **and Firefox** on Saturday 2019-05-04 – coinciding with the onset of armagadd-on 2.0. 

Since fixes for armagadd-on became available: 

- release versions of Firefox are no longer bugged
- as far as I can tell, Waterfox 56.2.9 remains without support for recent versions of themes at AMO.

**Comment by grahamperrin** [comment]
(COSE-related commentary removed.)

**Comment by grahamperrin** [comment]
### Test cases

Themes: 

- https://addons.mozilla.org/addon/calm-sunrise-by-madonna/versions/ version 3.0 of _Calm Sunrise by MaDonna_
- https://addons.mozilla.org/addon/fractal-frost/versions/ version 3.0 of _fractal frost_
- https://addons.mozilla.org/addon/multicolor-trail/versions/ version 3.0 of _multicolor trail by candelora_
- https://addons.mozilla.org/addon/dark-blue-fog/versions/ version 2.0 of _Dark Blue Fog_
- https://addons.mozilla.org/addon/grad2018/versions/ version 2.0 of _grad2018_
- https://addons.mozilla.org/addon/jack-style/versions/ version 2.0 of _Jack Style_
- https://addons.mozilla.org/addon/linen-light/versions/ version 2.0 of _Linen Light_
- https://addons.mozilla.org/addon/minimal_light/versions/ version 2.0 of _minimal_light_
- https://addons.mozilla.org/addon/outer-clouds-space/versions/ version 2.0 of _Outer Clouds Space_
- https://addons.mozilla.org/addon/wood-time/versions/ version 1.0 of _Wood time_

– and so on.

**Comment by MrAlex94** [comment]
I’ll need to keep an eye on how this will affect Waterfox. Thanks for the
links. I hope that disabling signature requirements will still be available
to stop any issues in the future.

**Comment by linuxgirl22** [comment]
Hello again :-)
Thanks for this great update eg captchas change is awesome!
Just to continue from the other thread (#966). I installed the AUR's 56.2.10 temporarily, cleared cache/cookies, and extensions install, which is great, but unfortunately not themes eg [https://addons.mozilla.org/en-GB/firefox/addon/under-the-deep-blue-sea/?src=featured](url). I tried right-clicking to save then load the theme manually, but error said corrupt. 
Unfortunately it's not possible to search themes on the Wayback, so I'm not sure what to do. 
(Manjaro KDE Stable)

**Comment by grahamperrin** [comment]
### Themes (personas/appearance) at AMO

At this time, in most cases of incompatibility there are (touch wood) multiple versions; and where: 

- the most recent version of a theme can not be added to 56.2.10
- a less (or least) recent version **can** be added. 

So for example @linuxgirl22 at https://addons.mozilla.org/addon/under-the-deep-blue-sea/versions/ you'll be able to add version 1.0.

**Comment by grahamperrin** [comment]
### Themes at AMO

In my limited understanding, where a page states:

> Works with Firefox 53.0 and later, …

– for a theme that can not be added to Waterfox 56.2.10, strictly speaking the statement could be more like: 

> Works with Firefox 59.0 and later, …

Given that 59 falls below the currently supported version 60 of Firefox ESR, I should not expect a fix in Mozilla's `/addons-frontend/` area of GitHub. 

No response (from any user of an unsupported version of Firefox) to https://discourse.mozilla.org/t/-/39845/46?u=grahamperrin and really, I don't expect one. 

----

Side note: https://discourse.mozilla.org/t/-/36770/2?u=grahamperrin re future _types_ of add-on.

**Comment by linuxgirl22** [comment]
"So for example @linuxgirl22 at https://addons.mozilla.org/addon/under-the-deep-blue-sea/versions/ you'll be able to add version 1.0."
Thanks grahamperrin :-) ... that's worked great, and I've found how to access the older versions.

**Comment by grahamperrin** [comment]
(COSE-related commentary removed.)

I wonder, what else is significant about: 

- the themes that were released on 2015-09-13
- the Wood time theme, version 1.0 released 2019-04-05

**Comment by Lorienna** [comment]
I ported the changes from <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1415878" title="Bug 1415878 - Accept both Chrome arrays and CSS colors for all properties | RESOLVED FIXED in Firefox 59"><code>bug 1415878</code></a> and <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1442437" title="Bug 1442437 - Rename background_tab_text to tab_background_text | RESOLVED FIXED in Firefox 59"><code>bug 1442437</code></a> to `C:\Program Files\Waterfox\omni.ja`, and the test case themes successfully installed themselves on Waterfox 56.2.10 on my Win7.

[Here](https://hg.mozilla.org/mozilla-central/log/tip/toolkit/components/extensions/schemas/theme.json) are some of the most recent changes related to theming; see also <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1347171" title="Bug 1347171 (themingapi-chrome) - Theming API - Google Chrome theme parity"><code>bug 1347171</code></a>.

Maybe someone can take a closer look into this?

**Comment by grahamperrin** [comment]
Thanks @Lorienna! So I was way off with the COSE assumption. I should change the title of this issue, what would you suggest?

**Comment by angela-d** [comment]
Changing the user agent (as well as **general.useragent.override.addons.mozilla.org**) seems to have no effect.

I randomly tried to install a handful of different themes, *not a single one* added after the early May addon debacle worked; but versions added prior, **all** installed successfully.

I am curious if anyone else has come to the same conclusion - that the checking is being done at their end and not browser-side?  They're checking some sort of identification string and refusing the download based on the version (or browser UA.. Waterfox) returned.  Perhaps something uploaded along with the new versions that wasn't present in earlier versions.

Example:
> Works with firefox 53.0 and later, android 65.0 and later

for **both** available versions: https://addons.mozilla.org/en-US/firefox/addon/dark-blue-fog/versions/ - yet *only* the one uploaded in January works; the version uploaded May 13th will not download.

Has anyone encountered any themes added after the debacle that will install?

Did all of these theme authors really upload new versions on the same day...?  Or did Mozilla roll out of a change on May 13th that forced new versions into the database?

Found one added in April that does *not* download: https://addons.mozilla.org/en-US/firefox/addon/outer-clouds-space/versions/ - version from January, does.

**Comment by grahamperrin** [comment]
> Changing the user agent … seems to have no effect.

True. From [Waterfox 56.2.10 compatibility with addons.mozilla.org (AMO)](https://www.reddit.com/r/waterfox/comments/bq7t2l/waterfox_56210_compatibility_with/): 

>> user agent (UA) strings are not a workaround

Sorry! I should have begun this issue with a cross-reference to the post in Reddit, but at the time I wasn't certain about the COSE stuff. 

To help people in your situation: 

- https://www.reddit.com/r/waterfox/comments/bq7t2l/-/eotyxbj/

**Comment by grahamperrin** [comment]
An example of the effect, on themes, at about:addons

![image](https://user-images.githubusercontent.com/192271/59180984-29717980-8b5e-11e9-83fd-a9041406682e.png)

> There was an error downloading …

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/c2d131b2df0cff955a11bd6cbf0b1546d6fa7aac
https://github.com/MrAlex94/Waterfox/commit/ac11ae3d342952d2a8ba0d4c2a7edd4b9a2b0e76

Thanks to @laniakea64 for the bugs. I've tested and seems to work well. Please re-open if you spot any issues related to the changes.

**Comment by laniakea64** [comment]
> Thanks to @laniakea64 for the bugs.

Not me :P
Credit for this goes to @Lorienna https://github.com/MrAlex94/Waterfox/issues/972#issuecomment-495521922

**Comment by MrAlex94** [comment]
Oops, wrong tag heh.
