### ISSUE TITLE
webRequest details.url doesn't match actual request url

### ISSUE THREAD

**Issue by AstroSnail** [BrowserWorks/waterfox#973]
**Describe the bug**
When an addon listens onBeforeRequest, sometimes the details.url passed to the callback isn't what the browser actually intends to request.

**To Reproduce**
1. Install an addon that observes details.url onBeforeRequest, and open a debugger on it. Make sure to enable request logging.
_The addon I'm using is [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/). [Here](https://github.com/einaregilsson/Redirector/blob/master/js/background.js#L47) is where it does its business._
_If you need to recreate my redirector settings, I have a redirect from `^https://www\.youtube\.com/([^?]*)(\?(((?!disable_polymer=1).)*))?$` to `https://www.youtube.com/$1?disable_polymer=1&$3`._
_You are not expected to understand this._
2. Copy the link of a YouTube video, and add `&disable_polymer=1`
_e.g. https://www.youtube.com/watch?v=dQw4w9WgXcQ&disable_polymer=1_
3. Observe how the url in the urlbar loses `&disable_polymer=1` but the page doesn't refresh.
4. Refresh the page manually.
5. Observe in the debugger how the details.url contains `&disable_polymer=1` but the request log doesn't have `disable_polymer` in the params.
If this isn't observed, go back to step 2 (or 3 if the param has persisted in the url).
_If you've followed my setup, you'll also notice the new YouTube design is used instead of the old one. If you reopen YouTube and browse without refreshing or navigating history, you'll remain in the old YouTube design._

**Expected behavior**
details.url should never lie. It should contain the exact url that will be requested if it isn't manipulated.

**Screenshots**
https://0x0.st/zARJ.png The addon's debug log, with a line printing its details.url containing `&disable_polymer=1`, followed by the request log lacking such a param.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 56.2.9

**Additional context**
The bug seems to be triggered when a page changes the url without refreshing the page. I haven't looked into this with detail however.
I also neglected to test this in Firefox.

**Comment by Lorienna** [comment]
If the goal is to retain the old Youtube layout, you can instead try a Firefox 42-43 user agent override, with or without Waterfox part.

**Comment by AstroSnail** [comment]
@Lorienna The bug still stands, but thanks for the tip.
