### ISSUE TITLE
Waterfox for Linux 56.2.10: error 404 (not found) for waterfox-56.2.10.en-US.linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#976]
<https://www.waterfox.net/blog/waterfox-56.2.10-release-download/> ▶ <https://www.waterfox.net/releases/> ▶
<https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.2.10.en-US.linux-x86_64.tar.bz2>

> # 404 Not Found
> 
> nginx

Maybe a content delivery network (CDN) issue affecting my area alone. I'll retry later. 

(Did I jump the gun?)

Meta/tracking: #582

**Comment by zANavAShi** [comment]
Same issue here from New Zealand ISP

**Comment by msmafra** [comment]
Same here on Brazil.
The link to the alpha works fine.

**Comment by skaendo** [comment]
Still 404'ing here. USA

**Comment by grahamperrin** [comment]
I reckon, give it a day or so

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/bqbkdw/-/eo3xuvq/?context=1 _an hour ago_: 

> It works now, thanks!

– but not yet for me, I guess that it's making its way through the CDN …

**Comment by msmafra** [comment]
Worked now for me.

**Comment by grahamperrin** [comment]
Also now for me. 

A few hours ago, someone in IRC found it: 

1. first not available in Canada
2. then five minutes later 

> woo, worked from phoenix in arizona

(I didn't ask but I guess that they used remote access to the computer in Arizona.)
