### ISSUE TITLE
56.1.0: Reset all updates to update manually: has the opposite effect

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#977]
Screen recording: 

- <strike>https://put.re/player?id=s9KbiAJZ.10.mp4</strike>
- https://s.put.re/s9KbiAJZ.10.mp4

Two frames from the recording: 

![frame a](https://user-images.githubusercontent.com/192271/57984938-8b0b6000-7a58-11e9-9935-f7afb048aebd.png)

![frame b](https://user-images.githubusercontent.com/192271/57984943-93639b00-7a58-11e9-9ccf-11e2e5f7bd0e.png)

In the first frame: automatic updates are off i.e. manual. 

In the second frame – after supposedly resetting to manual – the preference for manual updates is lost. 

Do I misunderstand the meaning of the word 'manual'?

**Comment by laniakea64** [comment]
Screen recording link returns 404 for me.

> Do I misunderstand the meaning of the word 'manual'?

No, you misunderstand the meaning of the word 'default'.

"Automatic Updates: Default" means use YOUR default preference for addon updates.  Your screenshots show your default preference is manual updates - "Update Add-ons Automatically" is un-checked.

Your first screenshot shows you have set **that specific addon** to never automatically update.  Meaning, that specific addon won't update automatically, **regardless of your default preference for addon updates**.  In your second screenshot, the addon is set to just use your default preference for automatic updates.  Which in your case is update manually.  So you should have the same result in both configurations.

Does this help clarify?

**Comment by grahamperrin** [comment]
Thanks, it sort of makes sense now, in a test profile, with this: 

![image](https://user-images.githubusercontent.com/192271/57989077-c2e0ca80-7a8d-11e9-8e5c-f7dba5093188.png)

Using the word 'Reset' for something that's a user preference (**not** a factory preset) and presenting things in the menu in that way, when the end result will be a 'Default' radio button (indicating a user preference, **not** a browser default) is **terrible** UX! 

It would have been much clearer if Mozilla had offered something like this: 

> Automatic updates: 
> 
> ◯ enable for all add-ons
> 🔘 disable for all add-ons
> …

– that's more like what I want. But I don't expect anyone to fix it. At least now I can make sense of the insanity of the UX :-)

**Comment by grahamperrin** [comment]
> Screen recording link returns 404 for me.

:+1: 

Reproducible, when I upload the same file and try to visit the resulting URL. I have reported the issue to put.re

Thanks!

**Comment by grahamperrin** [comment]
> Screen recording link returns 404 for me.

:+1: thanks @laniakea64 for drawing my attention. 

I received a reply within fifteen minutes of writing to put.re – classy! They will look into fixing the player bug and for now, I have added a working link to [the opening post](https://github.com/MrAlex94/Waterfox/issues/977#issue-445836117).
