### ISSUE TITLE
Sponsored tiles

### ISSUE THREAD

**Issue by PandaCodex** [BrowserWorks/waterfox#98]
Sponsored tiles with analytical tracking campaigns still exist in Waterfox despite multiple places saying they have been removed or disabled.

Shared profiles with Firefox is the cause, using own profile system is recommended for how you toggle this browser feature. To share the profile suggestions would be to remove the sponsored tile code from the browser core.

![sponsored_tiles](https://cloud.githubusercontent.com/assets/25470255/22505812/08b5befc-e8c9-11e6-8780-2ff9987e5d6d.JPG)

**Comment by PandaCodex** [comment]
@MrAlex94 did you want a patch to remove this feature to prevent further issue?

**Comment by MrAlex94** [comment]
Yes please, that would be much appreciated. I think I've got an old patch somewhere to completely gut the code but that was a while ago. I'll merge all the patches when I'm not traveling as much, thanks for all the help so far!

**Comment by MrAlex94** [comment]
Oh yes also, in Waterfox 52 I'll be making a separate profile location and import users existing profile, so should alleviate this from happening in the future as well.

**Comment by never93489** [comment]
> separate profile location

[hooray emoji]

**Comment by PandaCodex** [comment]
Please see PR work https://github.com/MrAlex94/Waterfox/pull/110 and review the changes for the above issue.

**Comment by MrAlex94** [comment]
Cool. Thanks for all the patches. I'll have a look through them all. Some __may__ not be needed as a lot of components don't get built at all such as the health report, so even if someone has Firefox resetting the configs when they use Waterfox nothing should be happening.

**Comment by PandaCodex** [comment]
> Cool. Thanks for all the patches. I'll have a look through them all. Some may not be needed as a lot of components don't get built at all such as the health report, so even if someone has Firefox resetting the configs when they use Waterfox nothing should be happening.

None of the patches submitted do anything for Firefox Health Report, mind you Firefox Health Report is still enabled in Waterfox looking back through older builds it was enabled too, would you like a patch to disable Firefox Health Report. Currently if shared profile with Firefox Waterfox will submit telemetry data because it gets enabled by Firefox also the data from Waterfox gets submitted by Firefox so technically Waterfox is still collecting and submitting user telemetry data.

I can have a patch later tonight if urgent for Waterfox 52.0 release let me know.

Edit: added images

![hreport](https://cloud.githubusercontent.com/assets/25470255/23641260/269b226a-033e-11e7-88c4-92c90b2524cc.JPG)
![hreport1](https://cloud.githubusercontent.com/assets/25470255/23641261/269c75b6-033e-11e7-8876-6d2576975178.JPG)

**Comment by MrAlex94** [comment]
I know, just meant as an example. It's a regression though that the component is getting built at all, MOZ_SERVICES_HEALTHREPORT is meant to be defined as false but looks like I missed it since they're slowly getting rid of configure. It shouldn't require a patch, just that MOZ_SERVICES_HEALTHREPORT is false.

**Comment by PandaCodex** [comment]
> I know, just meant as an example. It's a regression though that the component is getting built at all, MOZ_SERVICES_HEALTHREPORT is meant to be defined as false but looks like I missed it since they're slowly getting rid of configure. It shouldn't require a patch, just that MOZ_SERVICES_HEALTHREPORT is false.

@MrAlex94 Doing a regression check from current latest to 38.0.1 from [archive](https://www.waterfoxproject.org/dlarchive) shows Firefox Health Report still enabled and able to bleed data long before the moz.configure changes with introduction of rust. So will make a patch to squash this issue for you. Really should make the Firefox Health Report in another issue thread keeping this one on its main reason.
