### ISSUE TITLE
Waterfox can't open spotify due to agent "waterfox"

### ISSUE THREAD

**Issue by aquaspy** [BrowserWorks/waterfox#982]
Hi, I read that Alex Kontos now changed agent for waterfox again, and the browser identifies itself as Firefox only for certain sites. I think that spotify is not included and needs to be, because I can't open it in waterfox 56.2.10

Thanks!

It may be cool also if it was possible to add some site to make waterfox identifies itself as Firefox too.

**Comment by grahamperrin** [comment]
Cross reference https://redd.it/brfvtq

A simple string (not platform-specific) will set aside the message about compatibility, e.g. 

`Mozilla/5.0 (rv:60.0) Gecko/20100101 Firefox/60.0`

However the service behaves as if DRM is not enabled. 

For me the string at https://www.reddit.com/comments/agpv4e/-/ee8a30d/ is not a workaround.

**Comment by p1usminus** [comment]
> 
>
> `Mozilla/5.0 (rv:60.0) Gecko/20100101 Firefox/60.0`

This useragent, as well as
`Mozilla/5.0 (Windows NT 10.0; Win64; rv:60.0) Gecko/20100101 Firefox/60.0`
fixed Spotify for me.

**Comment by grahamperrin** [comment]
Not fixed for me: 

![image](https://user-images.githubusercontent.com/192271/58357797-25faa480-7e74-11e9-818d-ecb8b71d8bc3.png)

**Comment by piotrmil** [comment]
Doesn't work for me. Spotify now loads, but waterfox shows a banner saying that it "installs software to play music, please try again later". WTF?

**Comment by grahamperrin** [comment]
> WTF?

That's normal. Did you try later?

**Comment by piotrmil** [comment]
How do you define later?

Also, I have DRM enabled in the options

**Comment by piotrmil** [comment]
It's five minutes later. It still tries to install stuff.

**Comment by piotrmil** [comment]
Okay, figured it out thanks to a reddit thread. https://www.reddit.com/r/firefox/comments/788yws/firefox_unable_to_update_widevine_content/

I temporarily removed everything from my hosts file, that allowed the widevine module to update, and that in turn was the software Waterfox needed. 

I suppose it was 0.0.0.0 redirector.gvt1.com as the reddit comment suggests, so I have now muted that line

**Comment by grahamperrin** [comment]
@piotrmil do you now get playback? With the plug-in icon in the address bar?

**Comment by piotrmil** [comment]
Yeah, Spotify works now for me. I have an "i" icon, a chain-link DRM icon and a padlock one. And widevine plugin doesn't have a warning sign in the plugins anymore (it used to before I modified hosts)

**Comment by grahamperrin** [comment]
Thanks. 

Alex has `☐ spotify.com` amongst the domains in pinned issue 985 so @aquaspy if you like, close this issue (i.e. expect a fix under the umbrella of 985). 

----

My issue, pictured above, seems to involve something more than the UA; I can create a separate issue in due course.

**Comment by grahamperrin** [comment]
Working with Waterfox Classic 56.2.14 and Waterfox Current 68.0b1 (20190908151900) on Windows 10: 

https://put.re/player/yew3zgFm.mp4

(No soundtrack in that recording, but Spotify _is_ open; and I see the pause button after I click to play …)

@aquaspy would you like to close this issue? Thanks.

**Comment by aquaspy** [comment]
Of course, @grahamperrin . Thanks!
