### ISSUE TITLE
56.2.10: UA string for www.cambridge.org (Cambridge Core … Cambridge University Press)

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#984]
`Mozilla/5.0 (rv:60.0) Gecko/20100101 Firefox/60.0`

Without an override, at https://www.cambridge.org/core/ (and pages such as <https://www.cambridge.org/core/journals/international-journal-of-middle-east-studies/article/civil-society-tribal-process-and-change-in-jordan-an-anthropological-view/15CF85CDAE808418035509AF283C9E61>) there's this: 

![2019-05-22 Cambridge Core](https://user-images.githubusercontent.com/192271/58168126-7069fe80-7c85-11e9-816d-1d9a9d155309.png)

**Comment by MrAlex94** [comment]
Functionally seems to work though?

**Comment by grahamperrin** [comment]
TBH I don't know, I don't recall visiting the site before, I found myself there whilst seeking something for a colleague. 

I have sent feedback re: the site, with reference to this issue, let's see what happens …
