### ISSUE TITLE
User Agent Override Requests

### ISSUE THREAD

**Issue by MrAlex94** [BrowserWorks/waterfox#985]
If a website does not load properly because of a User Agent it does not recognise, please post it here, with a screenshot. The format of your post should be:

`<URL here>`
`<Screenshot here>`

⚠️ Please do not have discussions here. This is only for User Agent override requests for site that do not work.

Current (and requested) overrides:

- [x] addons.mozilla.org
- [x] netflix.com
- [x] chase.com
- [x] web.whatsapp.com
- [x] amazon.com
- [x] amazon.co.uk
- [x] amazon.de
- [x] amazon.co.jp
- [x] spotify.com
- [x] cosmicshambles.com
- [x] volunteerlogin.org
- [x] polar.com
- [x] eon.tv
- [x] slack.com
- [x] wire.com
- [x] trello.com
- [x] tresorit.com

**Comment by grahamperrin** [comment]
<https://volunteerlogin.org/chat/index.php>
![image](https://user-images.githubusercontent.com/192271/57985454-2fdd6b80-7a60-11e9-8b9b-169ab6a00cee.png)

**Comment by alahu** [comment]
https://open.spotify.com/
![image](https://user-images.githubusercontent.com/3238965/58202537-d6ff1480-7ca5-11e9-8443-92466b669b4b.png)

**Comment by gerardp** [comment]
https://web.whatsapp.com/

**Comment by gerardp** [comment]
https://web.whatsapp.com/

**Comment by OmaJantzen** [comment]
https://flow.polar.com
https://flow.polar.com/notCompatible/true/ie/firefox/56
![2019-05-23 15_47-Waterfox](https://user-images.githubusercontent.com/50956159/58258265-bbae0b00-7d72-11e9-8550-655ffc05d4d4.png)

**Comment by Nikolacc** [comment]
https://eon.tv/unsupported-browser
![Waterfox-EON](https://user-images.githubusercontent.com/50957275/58260754-aab7c680-7d7f-11e9-85e3-0ee7cbd9965d.png)

**Comment by EvilCronos** [comment]
YouTube new creator studio doesn't work and neither does Prime video, even after clearing my cache and restarting the browser. Using the latest update 56.2.10 64-bit on Windows 7 64-bit.

![no youtube](https://user-images.githubusercontent.com/37010742/58306309-f71afa80-7daf-11e9-9b69-8ad054b5a8bd.png)

![prime](https://user-images.githubusercontent.com/37010742/58306364-26316c00-7db0-11e9-8663-2543b87418d0.png)

**Comment by ntrf** [comment]
URL: `https://*.slack.com`
Any Slack workspace. I can't share the exact workspace with you, 'cause it's private. It works fine if i set override as `Mozilla/5.0 (Windows NT 10.0; Win64; rv:68.0) Gecko/20100101 Firefox/68.0`
![Screenshot](https://monosnap.com/image/1brQKmcVe8BkEzxpPJ4j7eSkHpxg0e)

**Comment by DeepMac** [comment]
URL: https://rtpsecbeers.slack.com/messages

Confirmed this doesn't work in Slack spaces. See screenshot for this specific page
![image](https://user-images.githubusercontent.com/4560942/58373761-6b18e800-7f01-11e9-9d81-3b82bcf98050.png)

**Comment by georg-h** [comment]
https://app.wire.com/auth/#
![wire_vs_waterfox](https://user-images.githubusercontent.com/5622476/58381176-69f7c180-7fba-11e9-9c1a-fd98d3c7c438.jpg)

**Comment by NekomanmaCc** [comment]
https://trello.com/
![trello](https://user-images.githubusercontent.com/51054256/58383767-7e1cdc80-8015-11e9-8f9f-54f9ec3e1291.png)

**Comment by HapaxOromenon** [comment]
https://web.tresorit.com/
![Tresorit Waterfox Screenshot](https://user-images.githubusercontent.com/40141645/58397180-c0f7a800-8047-11e9-9bcf-c9e5b5becb07.png)

**Comment by Geralt28** [comment]
Can not put screenshots that is why i put link under:)

Whatsup web:
https://web.whatsapp.com/
<img src="https://screenshots.firefox.com/6osuD89sfgkTPJ8Y/web.whatsapp.com"> 
https://screenshots.firefox.com/6osuD89sfgkTPJ8Y/web.whatsapp.com

Steam (not sure but dont work for me today and yesterday (this or white screen) - it works on chrome in the same time:
https://store.steampowered.com/
<img src="https://screenshots.firefox.com/7JcQAjSRqpvQ1SXC/store.steampowered.com"> 
https://screenshots.firefox.com/7JcQAjSRqpvQ1SXC/store.steampowered.com

**Comment by Geralt28** [comment]
Still dont see steam on the list. it is very important for me - does it dont work only for me?

**Comment by HapaxOromenon** [comment]
Steam doesn't work for everyone, but MrAlex94 seems to be away, as he hasn't updated the list in 4 days. In the mean time, while we're waiting for him to fix it, you can use the extension User Agent Switcher (https://addons.mozilla.org/en-GB/firefox/addon/user-agent-switcher-revived/) to change the user agent string manually.

**Comment by Geralt28** [comment]
Ok I understand. This is my last post here to not spam posts in this thread, but want to only say that this user agend add on does not work (it looks like it does not change anything - it still say i need firefox on whatsup and also can not use steam shop (maybe it is incompatible with current version).

**Comment by HapaxOromenon** [comment]
Once you've installed the extension, you have to click the button which it placed in the top toolbar, then select a user agent of Firefox 56.

**Comment by Geralt28** [comment]
of course i did it (also reloaded pages and start waterfox again):
<img src="https://snag.gy/irgN5a.jpg"> 


NEXT edit:
It works and second time it does not. Guess that is why it did not worked 5 times and started to work. Some time i can enter page sometime not. For example when i enter web.whatsup it says i use bad browser but after i make ctr+shift+r it works. Steam usualy does not work, but somehow it worked at last once..

**Comment by HapaxOromenon** [comment]
You could also try selecting Microsoft Edge as the user agent. That worked for me before when YouTube was broken.

**Comment by BillyTBum** [comment]
As of last night, Youtube appears to be broken with all current versions of Waterfox (tested 56.2.8 and 56.2.10). A rogue element loads and completely disaligns everything; a Reddit thread on the matter suggested I post screenshots here:

![1559102706409](https://user-images.githubusercontent.com/49573696/58561170-26849980-81ec-11e9-980c-8b051a8bd9eb.jpg)
![1559102950597](https://user-images.githubusercontent.com/49573696/58561175-2a182080-81ec-11e9-94a7-3d3926b79b12.jpg)

(Note: second screenshot is what it looks like when a video is loaded)

Results seem to vary according to the [reddit thread](https://www.reddit.com/r/waterfox/comments/bu9ftx/youtube_not_working_with_waterfox_56210/), but this persisted for me even after adding a user agent override.

**Comment by LeeBinder** [comment]
Hello @MrAlex94 : **hangouts.google.com** needs a different one. No screenshot necessary - calls simply don't go through all the way until the phone rings, best tested by calling oneself ...

Details see [my posting here](https://github.com/MrAlex94/Waterfox/issues/933)

**Comment by grahamperrin** [comment]
> YouTube new creator studio

https://studio.youtube.com/

Discussion: https://redd.it/buqvm2

**Comment by LeeBinder** [comment]
The thread over at **[hangouts.google.com](https://github.com/MrAlex94/Waterfox/issues/933)** needs some more contributors, esp. (but not limited to) Linux / FreeBSD users. So head on over and share your findings [over there](https://github.com/MrAlex94/Waterfox/issues/933), please.

**Comment by zenerbufen** [comment]
spotify web player broken with new user agent, wants me to 'upgrade' to firefox to jam out to tunes

**Comment by MrAlex94** [comment]
Added requests https://github.com/MrAlex94/Waterfox/commit/3d735123dd028d1b306cfb0031a4099e3ed4f87f

**Comment by c33s** [comment]
not sure if its an user agent or the sites owners issue. https://dev.to is broken on waterfox (worked before. don't know the date when it started to be broken).

see https://github.com/thepracticaldev/dev.to/issues/3081

**Comment by mindwarp42** [comment]
Site: [https://www.hoopladigital.com](https://www.hoopladigital.com)
Screenshot: 
![Hoopla in Waterfox 56 2 10](https://user-images.githubusercontent.com/36110616/59210546-d60e2400-8b7b-11e9-895e-9a715384f3af.jpg)


I use portable Waterfox at library I work at - this is one of the downloadable media options we offer, and the only one that isn't working with Waterfox unless I spoof the user agent currently.

**Comment by grahamperrin** [comment]
https://ucf.org.au/wp-login.php

- [discussion](https://www.reddit.com/r/waterfox/comments/byueh7/56210_wordpress_login_fails/eqq38x9/)

![image](https://user-images.githubusercontent.com/192271/59308722-9dfd0300-8c99-11e9-9158-ba882138365a.png)

**Comment by grahamperrin** [comment]
<https://discordapp.com/>

- [discussion](https://github.com/MrAlex94/Waterfox/issues/1025#issuecomment-502372028)

![image](https://user-images.githubusercontent.com/192271/59552788-16f2a800-8f83-11e9-9592-038f1d5a1604.png)

**Comment by xbipin** [comment]
https://gizmodo.com/
![screenshot](https://user-images.githubusercontent.com/10514905/59655183-8dbdba00-91aa-11e9-9b41-278a8d256942.png)

**Comment by grahamperrin** [comment]
…

![image](https://user-images.githubusercontent.com/192271/59627589-7c3aca80-9136-11e9-8165-29abe7f872eb.png)

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/11a3012d04715ee371a1d1a5909871f6c26e1e69

**Comment by grahamperrin** [comment]
https://internet.xfinity.com/

- works for me with the terse override given at https://github.com/MrAlex94/Waterfox/issues/1036#issuecomment-504296539
- without an override, there's redirection to <https://internet.xfinity.com/unsupported-browser.html>: 

![image](https://user-images.githubusercontent.com/192271/59900313-bc78a200-93ef-11e9-942c-a84623f3b2e0.png)

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/c34fej/-/etmpi8g/?context=1 tl;dr I no longer suspect a UA issue with Lifehacker.

**Comment by grahamperrin** [comment]
https://www.reddit.com/comments/c34fej/-/etmpi8g/?context=1 tl;dr I no longer suspect a UA issue with The Onion.

**Comment by fontmaniac** [comment]
https://banking.westpac.com.au

Basically, Westpac online banking refuses to login with non-standard useragent. It doesn't show any specific message, just repeatedly shows login screen. Setting general.useragent.override to something standard fixes it.

**Comment by reluctantuser** [comment]
Waterfox 56.2.11, Windows 7 fully patched, 64-bit

Google Apps spreadsheets go into continuous reload cycle. Spreadsheet never stabilizes so that any aspect of the spresheet can be clicked. Spreadsheet buttons/features never become useable.

Issue began within the past 24 hours. Error reports to Google go unanswered.

https://docs.google.com/spreadsheets/[link to actual spreadsheet]

Actual spreadsheet cannot be provided because it is a private, "secure" property that I do not control. Access to the spreadsheet is controlled by Google login credentials.

Error message in box:
Unable to load file
Try to load it again or send an error report.
[Reload button]

When the reload button is pressed, the spreadsheet starts to reload but tosses the same error. You can click reload for 5 minutes or more and it does not help at all.

Exact same links (we have multiple spreadsheets) have been tested and they work 100% correct in "Portable Opera" from PortableApps, Version 60.0.3255.165

Perhaps Google or at least Google Apps needs to be added to the UA Override Request list

**Comment by grahamperrin** [comment]
<https://www.phishrivieramaya.com/packages/#box1>

- override at https://www.reddit.com/comments/c2ijsb/-/es4w8xs/?context=1
- without the override: 

![image](https://user-images.githubusercontent.com/192271/60224598-042d7c80-987b-11e9-8840-5c7d6a99befc.png)

**Comment by grahamperrin** [comment]
https://playinginthesand.com/packages/#box1

- override at https://www.reddit.com/comments/cbxwk5/-/etj6e62/?context=1
- without the override: 

![image](https://user-images.githubusercontent.com/192271/61072903-2ba04f80-a40c-11e9-84bc-73e1f3ced35d.png)

**Comment by HETLAN** [comment]
It's ridiculous to do that, don't get mad at me. As security, these are the points. option must be added to settings. so everyone can make their own list .)

**Comment by HETLAN** [comment]
It's ridiculous to do that, don't get mad at me. As security, these are the points. option must be added to settings. so everyone can make their own list? .)

**Comment by grahamperrin** [comment]
> … Please do not have discussions here. …

**Comment by grahamperrin** [comment]
@fontmaniac please join the discussion at https://www.reddit.com/comments/ccduyc/-/evv121q/ – include a note of the user agent that works for you. Thanks

**Comment by hawkeye116477** [comment]
Possible override ua for uBlock Origin? It seems that html filtering works now, but if someone add that filter in condition `!#if cap_html_filtering`, then it's not applied and I see that's because of following line on uBO => `https://github.com/gorhill/uBlock/blob/c34326cf4e191c2ee2723523d0a57fa4d9f425bd/platform/chromium/vapi-common.js#L68`, so it checks if it's Firefox 57.

**Comment by grahamperrin** [comment]
Possible regression in Waterfox Classic 56.2.14: 

https://github.com/MrAlex94/Waterfox/issues/978#issuecomment-532834646

**Comment by grahamperrin** [comment]
> :warning: Please do not have discussions here.

A place for discussion, for anyone who needs it: 

- [User agent (UA) string overrides: discussion : waterfox](https://www.reddit.com/r/waterfox/comments/d79h2l/user_agent_ua_string_overrides_discussion/)

**Comment by Octopod2** [comment]
youtube.com, but not all pages. Not Creators Studio cited above. No toolbar at bottom of video, video takes almost entire screen.( Green box is my screen capture program.) 
 
![ytfull](https://user-images.githubusercontent.com/36056477/65799467-2ec0f700-e142-11e9-9124-927842722ba2.jpg)

**Comment by grahamperrin** [comment]
@Octopod2 thanks and if you have a Reddit ID, please share troubleshooting information under https://www.reddit.com/comments/d4xgb2/-/f1anblu/ 

> … No toolbar at bottom of video, …

– reminiscent of https://www.reddit.com/comments/d4xgb2/-/f16qz9b/

> … video takes almost entire screen. …

– reminiscent of https://www.reddit.com/comments/d4xgb2/-/f0mv2dj/

**Comment by Octopod2** [comment]
That's my thread, just wanted to bring it to Alex' attention.

**Comment by grahamperrin** [comment]
@Octopod2 thanks, 

> Alex' attention.

– he's there already, https://www.reddit.com/comments/d4xgb2/-/f0n0rdi/

**Comment by grahamperrin** [comment]
https://answers.unrealengine.com/

- not working with Waterfox Classic

Discussion: 

- https://www.reddit.com/comments/d79h2l/-/f6c2y84/

Workaround: 

`Firefox/60.0`

**Comment by grahamperrin** [comment]
<https://codex.wordpress.org/WordPress_Versions>

- 403 forbidden with Waterfox Classic 56.2.14 and 2019.10

Discussion: 

- https://redd.it/duwvae

Workaround: 

`Firefox/60.0`

**Comment by grahamperrin** [comment]
https://help.zoho.com/

![2019-12-10 11:35:43](https://user-images.githubusercontent.com/192271/70533873-dcdd1a00-1b51-11ea-862f-b702a269b8a4.png)

Discussion: 

* https://www.reddit.com/r/waterfox/comments/d79h2l/user_agent_ua_string_overrides_discussion/fadt1b7/

– there's not yet a workaround for _Zoho Mail_. 

Workaround for Zoho help: 

`Firefox/60.0`

**Comment by krystian3w** [comment]
If waterfox removed "web compact" extension (or does not work property):

domain | source
--- | ---
rolb.santanderbank.com  | https://bugzilla.mozilla.org/show_bug.cgi?id=1563839
supportforms.embarcadero.com | https://bugzilla.mozilla.org/show_bug.cgi?id=1577179
att.tv | https://bugzilla.mozilla.org/show_bug.cgi?id=1577519
steamcommunity.com | https://bugzilla.mozilla.org/show_bug.cgi?id=1570108
sling.com | https://bugzilla.mozilla.org/show_bug.cgi?id=1582582

**Comment by VictorSago** [comment]
Recently, my bank's site stopped accepting my browser.
URL: https://swedbank.se/
Screenshot (immediately after clicking the Login button):
![20191216-1127-wfscreen ](https://user-images.githubusercontent.com/13367992/70899936-071e5400-1ff8-11ea-93e3-23cd24c6b5bd.jpg)

Changing the UserAgent string in the `about:config` did not help in this case.
The key I created in the `about:config` is: `general.useragent.override.swedbank.se`. I changed its value to `Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0`, but it didn't help.

Additional information:
I am on Linux -- 2 different distros, one on laptop and another on the desktop. The same site that rejects Waterfox, accept Basilisk browser, for some reason.

**Comment by grahamperrin** [comment]
> Changing the UserAgent string … did not help

Discussion: https://www.reddit.com/r/waterfox/comments/ebdczg/swedish_bank_swedbank_not_working_with_waterfox/fb71fs1/?context=2 with alternative workaround (not an override) https://www.reddit.com/r/waterfox/comments/ebdczg/swedish_bank_swedbank_not_working_with_waterfox/fb5w1ws/

**Comment by grahamperrin** [comment]
<https://www.qwant.com/>

![2019-12-21 08:15:18](https://user-images.githubusercontent.com/192271/71305427-bb8af200-23cb-11ea-9e24-1e16922d20f6.png)

Discussion: https://www.reddit.com/r/waterfox/comments/d79h2l/user_agent_ua_string_overrides_discussion/fbivzb5/

Workaround: 

`Mozilla/5.0 Gecko/20100101 Firefox/68.0`

**Comment by hawkeye116477** [comment]
#1387

**Comment by hawkeye116477** [comment]
In case of https://github.com/MrAlex94/Waterfox/issues/985#issuecomment-552585021, seems that global useragent override works, but specifc for `wordpress.com` doesn't help.

**Comment by krystian3w** [comment]
> https://github.com/MrAlex94/Waterfox/issues/985#issuecomment-584085621

That is TLD **suffix** like as:

`blogspot.com`?

When this is not real domain.

**Comment by Ropliplo951** [comment]
Good evening.

The replay site of a Belgian TV channel no longer works with Waterfox.

A message saying that "Your browser version is too old to read this video. We invite you to update it" appears.

Example:
https://www.rtlplay.be/chasing-life-p_16535/s01e03-leucemie-sexe-et-carottes-c_12598105

Thanks.

![rtlplay](https://user-images.githubusercontent.com/62814587/77833789-30df2f00-7140-11ea-8f48-151d16383313.jpg)

**Comment by grahamperrin** [comment]
### Google Photos

https://photos.google.com/?tab=mq1&pageId=none

![image](https://user-images.githubusercontent.com/192271/78554179-94352500-7802-11ea-88e0-b3b272a1fe9d.png)

Non-working override: `Mozilla/5.0 (X11; rv:63.0) Firefox/63.0`

Working override: `Mozilla/5.0 (X11; rv:64.0) Firefox/64.0`

![image](https://user-images.githubusercontent.com/192271/78554447-132a5d80-7803-11ea-8807-09af854a498a.png)

Discussion: https://redd.it/fu0ysr

### Postscript

https://old.reddit.com/r/waterfox/comments/fu0ysr/google_photos_issue/fn02f0q/

I'll make this GitHub comment outdated.

**Comment by TheTechRobo** [comment]
lexiacore5.com

I had to install a Mozilla addon for it. This only seems to happen in Classic, but correct me if I'm wrong.

**Comment by happysmash27** [comment]
These people... they changed it the day of the test!!!!!
![incompatible_useragent](https://user-images.githubusercontent.com/3620657/82349182-a7651400-99ae-11ea-9d3f-f806b0ad3336.png)

**Comment by happysmash27** [comment]
It turns out that the test works fine, but the message about the outdated browser combined with a completely seperate error made it look like it wasn't: 

`{"errorType":"SucredProviderError","errorMessage":"{\"code\":\"RAOTTLoginTimeRange\",\"message\":\"you're not within the allowed login interval: from Tue May 19 2020 17:27:46 GMT+0000 (Coordinated Universal Time) to Tue May 19 2020 19:52:46 GMT+0000 (Coordinated Universal Time)\",\"retryable\":false}","trace":[""]}`

So, the outdated browser message probably existed in the past, but I didn't realise it since the test worked fine. The test still worked fine after the correct time allotment was reached, but the message misleaded me into thinking it was a new browser problem when I tried to take the practice test.

**Comment by SPWGitHub** [comment]
[https://www.chase.com/digital/resources/privacy-security/security/system-requirements](https://www.chase.com/digital/resources/privacy-security/security/system-requirements)

**They say that FF50 or greater is okay, but no joy!**

![image](https://user-images.githubusercontent.com/22408621/83988460-44153480-a911-11ea-924b-a7f7a27ccc1d.png)

**Comment by SPWGitHub** [comment]
OH. You already have chase.com. 🤷‍♂️

**Comment by SPWGitHub** [comment]
OH. You already have chase.com. 🤷‍♂️

**Comment by c33s** [comment]
~~maybe it's not a user agent problem but i post it here for reference: https://github.com/MrAlex94/Waterfox/issues/1724~~

gitlab now using a function which looks like to be not available in waterfox. so it's a bug of its own

**Comment by Yoposoc** [comment]
trello still has a not supported flag,even though I've tried useragent spoofing with Custom UserAgent String
![image](https://user-images.githubusercontent.com/2718371/92333531-07092d00-f03b-11ea-99d5-206a21ff5df7.png)
I may be doing something dumb, as I'm very unfamilar with UserAgents. I just put in the latest FF useragent.
![image](https://user-images.githubusercontent.com/2718371/92333463-834f4080-f03a-11ea-8ca0-7e154e16c95c.png)

**Comment by Ropliplo951** [comment]
> 
> 
> Good evening.
> 
> The replay site of a Belgian TV channel no longer works with Waterfox.
> 
> A message saying that "Your browser version is too old to read this video. We invite you to update it" appears.
> 
> Example:
> https://www.rtlplay.be/chasing-life-p_16535/s01e03-leucemie-sexe-et-carottes-c_12598105
> 
> Thanks.
> 
> ![rtlplay](https://user-images.githubusercontent.com/62814587/77833789-30df2f00-7140-11ea-8f48-151d16383313.jpg)

The problem is still present :(

**Comment by SPWGitHub** [comment]
**Describe the bug**

Refuses to play videos.

**To Reproduce**

1. Install FBP Facebook Purity [Fluff Busting Purity Add-on](https://www.fbpurity.com/install.htm?v=30.6.11)
2. Revert to the old Facebook (if you're running the crappy new version).
3. Try playing a video.
4. When it doesn't play, click "Learn More" on the video overlay.
5. See this:
<p><img src="http://accuratepetsupply.com/github/FB_UB.PNG"</img></p>

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: Classic 2020.09


**Additional context**

This really blows!

**Comment by vanowm** [comment]
Has anyone got chase.com working? I've tried latest FF user agent, but it still says browser is out of date.
`Mozilla/5.0 (Windows NT 6.1; rv:80.0) Gecko/20100101 Firefox/80.0`

**Comment by AntiSol** [comment]
https://www.rottentomatoes.com/
![Screen Shot 2020-12-16 at 18 52 39-fullpage](https://user-images.githubusercontent.com/351169/102320056-e8b6b400-3fcf-11eb-94b4-70d349b379cd.png)

**Comment by hawkeye116477** [comment]
It's very weird, but https://languagetool.org won't work properly on Classic with default UA, switching to FF 60 makes it working properly.

**Comment by InvisibleManX** [comment]
That's what Yahoo mail says: "The latest version of AT&T Yahoo Mail is not supported on your browser."

Waterfox G3.0.2
OS: Windows 8.1

**To see the problem you must be logged into the Yahoo mail** to actually see it. It's not visible if you're not logged into it.

[https://mail.yahoo.com/](https://mail.yahoo.com/)

![102682256-d192e480-41d0-11eb-9147-020c2194db1d](https://user-images.githubusercontent.com/66888405/102699160-633f3800-424b-11eb-9f28-f7a9b816d326.jpg)

**Comment by ibeladi-mrsool** [comment]
https://www.meistertask.com/

![image](https://user-images.githubusercontent.com/11488356/117585768-dbd06380-b11c-11eb-8af8-a18dbfab330f.png)
