### ISSUE TITLE
68.0a1: Control-D does not allow editing bookmark, menu neither

### ISSUE THREAD

**Issue by reikred** [BrowserWorks/waterfox#986]
Menu bookmark-this-page (Control-D) creates a bookmark, but does not pop up the bookmark for editing (say adding the tags).  After Control-D, menu appears as Edit-this-bookmark, but pressing Control-D again also does not pop up the bookmark for editing.

<del>No bookmark gets created. Is anyone able to create bookmarks? </del> 

UPDATE: The bookmark actually DOES get created. It can be found under "other bookmarks". But it will not pop up and allow itself to be edited!!

Conditions: From old profile reused for wf68.0a1. Can see all my old bookmarks. 
Setup: Linux fc25, but seems I cannot edit a bookmark via Control-D in win10 either (clean profile in this case, nothing from an old profile)

**Comment by grahamperrin** [comment]
Also: [Can't remove a bookamark by the boomarks button at address bar (Waterfox Alpha) · Issue #950 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/950)

**Comment by laniakea64** [comment]
https://github.com/MrAlex94/Waterfox/pull/975 fixes this

**Comment by tycrek** [comment]
@grahamperrin @MrAlex94 Suggesting to close issue since this is directly related to [#975](https://github.com/MrAlex94/Waterfox/pull/975) and [#950](https://github.com/MrAlex94/Waterfox/issues/950).
