### ISSUE TITLE
v68.0a1:  creates persistent "VideoDecodeStats" folder on /home SOLUTION HERE!

### ISSUE THREAD

**Issue by ciciolina** [BrowserWorks/waterfox#987]
**Describe the bug**
I found a persistent folder "VideoDecodeStats" on home folder every moment i run my laptop, first i don't know why or who process create this folder, but searching in my system i found its the alpha version of waterfox, you can delete this folder but if you open any video on internet the folder re-creates every time.

**To Reproduce**
1. Go to '/home'
2. Find the folder 'VideoDecodeStats'
5. Delete 'VideoDecodeStats'
6. Open Waterfox and go to 'youtube' open any video
7. 'VideoDecodeStats' its created again on '/home'

**SOLUTION**
1. Open 'Waterfox'
2. Go to 'about:config'
3. Search for 'media.video_stats.enabled'
4. Toggle to 'false'
5. Close 'waterfox'
6. The folder 'VideoDecodeStats' its gone...
7. If you have the folder on '/home' you can delete and this never back again

**Desktop (please complete the following information):**
 - OS: [Arch BTW]
 - Version [Last kernel release]
 - I think this affects other Linux flavors 

**Additional context**
Its solved if you follow the instructions. Disable this config don't affect the waterfox video player 
Thanks for the beta, its amazing and works fine for me! 
Kisses!!!!

**Comment by ibuprophen1** [comment]
I had located the "media.video_stats.enabled" as false on 2 locations and 1 of them as true. 

I can't state that this is the underlying issue in itself but, it just seems to me as a minor thing that might have been overlooked. 

I could be wrong as well... 

Good Luck! :-) 


~Ibuprophen
