### ISSUE TITLE
Waterfox still report update available after update

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#989]
**Describe the bug**
After I've update to waterfox 5.2.10 waterfox still report "update available".

**Screenshots**
![screenshot](http://images.collectiontricks.it/images/14826483732284503119.png)

**Desktop (please complete the following information):**
 - OS: Linux Arch

**Comment by grahamperrin** [comment]
Did the original installation use a `tar.bz2` file from Waterfox Project?

If you use https://storage-waterfox.netdna-ssl.com/releases/linux64/installer/waterfox-56.2.10.en-US.linux-x86_64-1.tar.bz2 to overwrite the current installation of 56.2.10, is the update issue reproducible?

56.2.10 on Lubuntu finds itself up-to-date: 

![image](https://user-images.githubusercontent.com/192271/58369884-aebb2400-7ef8-11e9-9a6b-da68811c7be8.png)

**Comment by ghost** [comment]
I've installed waterfox using .tar.bz2 you linked through AUR build script. :-\

**Comment by grahamperrin** [comment]
What's the build ID? 

- about:support

Try a fresh download of the installer, then reinstall, then review the build ID. 

Re: https://www.reddit.com/comments/bs2krj/-/eoisof7/?context=1 there were multiple builds of 56.2.10 for Windows, maybe the same was true for other platforms.

**Comment by ghost** [comment]
Hello. Build ID is: 20190520134324

Fresh reinstalled, build ID is same above.

Anyway for the moment no more annoying "update alert" popup, reporting just showed in "about waterfox" panel.

**Comment by MrAlex94** [comment]
There was another supplementary update. That's the final build number.
