### ISSUE TITLE
[DOS] Crash with language selection

### ISSUE THREAD

**Issue by PandaCodex** [BrowserWorks/waterfox#99]
Patch https://github.com/MrAlex94/Waterfox/commit/efa1f09c3d1478387538c64afac5a6dd50405349 brought with it a series of issues.

- Using arrow keys for selection causes large CPU spiking
- Using arrow keys causes memory leak from notification spam
- Using arrow keys can crash waterfox
- Using arrow keys creates browser lag creating a **denial of service** for few seconds to few minutes

Currently using the arrow keys to select language causes the above issues, every change made triggers `nsIAlertsService` when scrolling 91 entries that is 91 notifications passed through `nsIAlertsService` this causes a memory leak and can crash the browser.

Suggestion would be to only select the selected item once the drop down menu closes creating a single notification and resolving the above issues.

![dos](https://cloud.githubusercontent.com/assets/25470255/22506041/05ef2a18-e8ca-11e6-9c49-b637c591d948.JPG)

Lastly the field remains empty even after changed, there is no visual feedback to the current default selected language, for usability and readability this is highly suggested.

**Comment by MrAlex94** [comment]
Yes I was rather hasty with the way I implemented this, I'll have to go back and choose a better method. Maybe a drop down box isn't the best way to accomplish this.

**Comment by PandaCodex** [comment]
@MrAlex94 The current PR work for language selection fixes should resolve the above mentioned issues.
