### ISSUE TITLE
[SUGGESTION] Ship w/ Microsoft ATP (Active Threat Protection) Integration

### ISSUE THREAD

**Issue by jebeld17** [BrowserWorks/waterfox#991]
With Microsoft now allowing third-party browsers access Microsoft Defender and ATP APIs, it would be worth while to include this integration in new Waterfox builds. 

To do this, it can be a) as simple as shipping Microsoft's extensions already available for Firefox and Chrome onboard, or b) including the API in the source code and browser settings silently and without wasting space with additional extensions.

Edit: If implemented, please offer users an "Off" switch for Microsoft ATP integration for users who wish to not share their metadata.

**Comment by ilu33** [comment]
Pleas leave it out of Linux versions. And stuff from MS should be opt-in only - so if you care to implement that, offer an ON switch.

**Comment by jebeld17** [comment]
I respect and agree to that, Ilu33.
I think it would be great to present ATP Integration as a choice for users 1. to automatically download, install, and enable or 2. to not when Waterfox starts for the first time on a detected Windows system.
