### ISSUE TITLE
Waterfox Portable includes too much Firefox branding

### ISSUE THREAD

**Issue by jebeld17** [BrowserWorks/waterfox#992]
The PortableApps version of Waterfox contains a perceivable amount of Firefox branding and not enough custom branding pretty much everywhere throughout the browser, ranging from the application title to install folder names, branding in Settings, etc.

**Comment by beppe9000** [comment]
It _is_ Firefox, after all...

**Comment by jebeld17** [comment]
It is, but it isn't legally.
Even though Firefox is open source, Mozilla still has strong trademarking of the Firefox brand. Part of Mozilla's trademarking agreement is that any copy of Firefox-branded software must be (mainly) unaltered. 

Though I do not work for Mozilla, I think it's safe to speak for them and state that these open source projects are definitely good, but it's posing an IP risk.
