### ISSUE TITLE
v68: bookmarks in new tab (highlights) dissapear without reason

### ISSUE THREAD

**Issue by RaitaroH** [BrowserWorks/waterfox#996]
**Describe the bug**
I find it annoying to place bookmarks in the new tab page of firefox quantum, thus waterfox alpha included. But something weird happens where for some reason one or more already existing bookmarks under highlights in the new tab page simply disappear. The bookmark is not gone, is simply the page was removed from the new tab page. Then I have to remove the bookmark (if I can) and readd it. Then it will appear back on the page.

**To Reproduce**
I am not sure. I simply have my new tab page with bookmarks only. I have 3 bookmarks there. It already happened twice for some bookmarks o disappear, first time all 3, now just 1.
I also have a clean profile. I simply imported previously exported bookmarks and addon settings. That is all.

**Expected behavior**
The bookmarked links on the new tab page should remain there. 
I also wish to be possible to rearrange them manually.

**Desktop (please complete the following information):**
- Operating System: KDE neon 5.15
- KDE Plasma Version: 5.15.5
- KDE Frameworks Version: 5.58.0
- Qt Version: 5.12.0
- Kernel Version: 4.15.0-50-generic
- OS Type: 64-bit

**Comment by grahamperrin** [comment]
Can you share a screenshot? Thanks

**Comment by RaitaroH** [comment]
What will that do? Also right now I fixed the disappeared stuff so everything is back. If it helps these are my settings for the new tab page. As you can see bookmarks only. Adding any new bookmark will make a new highlight. I usually dismiss them.
![image](https://user-images.githubusercontent.com/19552720/58384478-86abed80-7fea-11e9-9bed-872b2825f4d1.png)
Still, I made a few css modifications to the new tab page using userContent.css as well. Here is 2/3 bookmarks, one disappeared:
![image](https://user-images.githubusercontent.com/19552720/58384515-1c477d00-7feb-11e9-8f45-ed251a96fd08.png)

**Comment by RaitaroH** [comment]
Also, I noticed that if you click on delete from history, you cannot readd the bookmarked page to the new tab list. Even after deleting the bookmark and making it again, no automatic adding. Is not domain based though, is just that same page will not be added again.
![image](https://user-images.githubusercontent.com/19552720/58384586-fa022f00-7feb-11e9-8bc0-3dd7cabffab1.png)

**Comment by grahamperrin** [comment]
> will that do? 

Yes¸thanks 👍 (I deleted my previous comment after getting, for myself, a non-empty home screen).

**Comment by RaitaroH** [comment]
```
Yes¸thanks +1 (I deleted my previous comment after getting, for myself, a non-empty home screen).
```
@grahamperrin Oh... you don't get anythingon the page. That is most interesting.
In case it helps I did try to set a different url as a new tab page, and it does work.
