### ISSUE TITLE
v68 - private tab not fully working

### ISSUE THREAD

**Issue by RaitaroH** [BrowserWorks/waterfox#997]
**Describe the bug**
open in new private tab context menu entry - works as expected
extensions.privateTab.key.toggleTabPrivate shortcut - works as expected
extensions.privateTab.key.openNewPrivateTab shortcut and the button to open a new private tab - does not work properly. A new tab appears, the private mask logo is there but is not actually a private tab at all.

**To Reproduce**
1. I simply installed the xpi provided with the release of alpha.
2. Add the new private tab button / use the shortcut to open a new tab.
3. See that the tab is not actually private.

**Desktop (please complete the following information):**
    Operating System: KDE neon 5.15
    KDE Plasma Version: 5.15.5
    KDE Frameworks Version: 5.58.0
    Qt Version: 5.12.0
    Kernel Version: 4.15.0-50-generic
    OS Type: 64-bit

**Comment by marty60** [comment]
This is another one of xiaoxiaoflood's modified addons. People need to post on his thread and let him know, if he doesn't already:

https://www.reddit.com/r/XUL_for_Quantum_Dev/comments/a9rzcz/legacy_addons_in_firefox_65/

**Comment by Peacock365** [comment]
I've hinted at the issue in the Private Tab GitHub page, feel free to chime in: 

https://github.com/Infocatcher/Private_Tab/issues/291

**Comment by p1usminus** [comment]
Hmm, I couldn't reproduce this on Windows 10
